Repository mantidproject/mantid, pull requests merged in 2018-04, with the labels that each got.

#22194 SofQW3 segfault
  Framework/Algorithms/test/SofQWCutTest.h
  Framework/DataObjects/src/FractionalRebinning.cpp
Labels: Component: Direct Inelastic, Misc: Bug, Patch Candidate

#22220 Migrate management-type develop pages from wiki
  dev-docs/source/DesignDocumentGuides.rst
  dev-docs/source/DevelopmentAndReleaseCycle.rst
  dev-docs/source/GettingStarted.rst
  dev-docs/source/JenkinsConfiguration.rst
  dev-docs/source/PatchReleaseChecklist.rst
  dev-docs/source/ReleaseChecklist.rst
  dev-docs/source/TSC.rst
  dev-docs/source/images/DevelopmentAndReleaseCycle.png
Labels: Component: Documentation

#21655 Remove dependence of Kafka Live Listener on ISIS specific event data
  Framework/LiveData/src/Kafka/KafkaEventStreamDecoder.cpp
  Framework/LiveData/test/KafkaEventStreamDecoderTest.h
  Framework/LiveData/test/KafkaTesting.h
Labels: Component: Live Data, Patch Candidate

#22246 SortXAxis algorithm: documentation fix, generalised (dx, ascending - descending sorting)
  Framework/PythonInterface/plugins/algorithms/SortXAxis.py
  Framework/PythonInterface/test/python/plugins/algorithms/SortXAxisTest.py
  docs/source/algorithms/SortXAxis-v1.rst
  docs/source/release/v3.13.0/framework.rst
Labels: Component: Framework, Component: Python

#22130 Dev-docs: debugging, doxygen.
  dev-docs/source/DebuggingUnitTests.rst
  dev-docs/source/DoxygenSetup.rst
  dev-docs/source/images/AttachToProcess.png
  dev-docs/source/images/VisualStudioTestDebugProperties.png
Labels: Misc: Maintenance

#22235 Attempted fix for jupyterconsole test on macOS
  qt/python/mantidqt/utils/qt/testing/__init__.py
  qt/python/mantidqt/widgets/test/test_jupyterconsole.py
Labels: Quality: Unit Tests

#22163 Maxent algorithm output of iteration records and use of complex data
  Framework/API/src/EqualBinSizesValidator.cpp
  Framework/Algorithms/src/MaxEnt.cpp
  docs/source/algorithms/MaxEnt-v1.rst
  docs/source/release/v3.13.0/framework.rst
Labels: Component: Documentation, Component: Framework

#22257 Fix test failures on SL7
  Testing/SystemTests/tests/analysis/VesuvioCommandsTest.py
  Testing/SystemTests/tests/analysis/VesuvioCorrectionsTest.py
  qt/widgets/common/test/FindFilesThreadPoolManagerTest.h
  qt/widgets/common/test/FindFilesWorkerTest.h
Labels: Quality: Unit Tests

#21835 Better statistics for equivalent peaks
  Framework/Crystal/inc/MantidCrystal/PeakStatisticsTools.h
  Framework/Crystal/inc/MantidCrystal/PredictPeaks.h
  Framework/Crystal/src/LoadHKL.cpp
  Framework/Crystal/src/LoadIsawPeaks.cpp
  Framework/Crystal/src/PeakStatisticsTools.cpp
  Framework/Crystal/src/PredictPeaks.cpp
  Framework/Crystal/src/SaveHKL.cpp
  Framework/Crystal/src/SaveIsawPeaks.cpp
  Framework/Crystal/src/SortHKL.cpp
  Framework/Crystal/src/StatisticsOfPeaksWorkspace.cpp
  Framework/Crystal/test/PeakStatisticsToolsTest.h
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  Framework/DataObjects/inc/MantidDataObjects/Peak.h
  Framework/DataObjects/src/Peak.cpp
  Framework/DataObjects/src/PeakColumn.cpp
  Framework/DataObjects/src/PeaksWorkspace.cpp
  Framework/DataObjects/test/PeaksWorkspaceTest.h
  Framework/Geometry/inc/MantidGeometry/Crystal/IPeak.h
  Framework/Geometry/test/MockObjects.h
  Framework/Kernel/inc/MantidKernel/Statistics.h
  Framework/Kernel/src/Statistics.cpp
  Framework/MDAlgorithms/src/FindPeaksMD.cpp
  Framework/PythonInterface/mantid/api/src/Exports/IPeak.cpp
  Framework/PythonInterface/plugins/algorithms/SaveReflections.py
  Framework/PythonInterface/test/python/plugins/algorithms/SaveReflectionsTest.py
  Testing/SystemTests/tests/analysis/SortHKLTest.py
  docs/source/algorithms/FindPeaksMD-v1.rst
  docs/source/algorithms/IntegrateEllipsoids-v1.rst
  docs/source/algorithms/IntegrateEllipsoidsTwoStep-v1.rst
  docs/source/algorithms/IntegratePeaksMD-v2.rst
  docs/source/algorithms/SaveIsawPeaks-v1.rst
  docs/source/algorithms/SortHKL-v1.rst
  docs/source/algorithms/StatisticsOfPeaksWorkspace-v1.rst
  docs/source/images/EquivalentIntensities.png
  docs/source/release/v3.13.0/diffraction.rst
  qt/widgets/sliceviewer/inc/MantidQtWidgets/SliceViewer/QPeaksTableModel.h
  qt/widgets/sliceviewer/src/QPeaksTableModel.cpp
Labels: Component: Diffraction, Group: Single Crystal

#22256 Create index page for developer documentation
  dev-docs/source/AutomatedBuildProcess.rst
  dev-docs/source/BuildingVATES.rst
  dev-docs/source/BuildingWithCMake.rst
  dev-docs/source/DataFilesForTesting.rst
  dev-docs/source/Dependencies.rst
  dev-docs/source/DeveloperAccounts.rst
  dev-docs/source/GUIDesignGuidelines.rst
  dev-docs/source/GettingStarted.rst
  dev-docs/source/GitWorkflow.rst
  dev-docs/source/IssueTracking.rst
  dev-docs/source/JenkinsConfiguration.rst
  dev-docs/source/LoadAlgorithmHook.rst
  dev-docs/source/Logging.rst
  dev-docs/source/MVPTutorial/CalculatorExample/index.rst
  dev-docs/source/MVPTutorial/Introduction.rst
  dev-docs/source/MultiThreadingInAlgorithms.rst
  dev-docs/source/QtDesignerForPython.rst
  dev-docs/source/RemoteJobSubmissionAPI.rst
  dev-docs/source/Standards/AlgorithmDocumentation.rst
  dev-docs/source/Standards/AlgorithmUsageExamples.rst
  dev-docs/source/Standards/CPPStandards.rst
  dev-docs/source/Standards/DocumentationGuideForDevs.rst
  dev-docs/source/Standards/InterfaceDocumentation.rst
  dev-docs/source/Standards/Libraries.rst
  dev-docs/source/Standards/MantidStandards.rst
  dev-docs/source/Standards/PythonStandards.rst
  dev-docs/source/Standards/UnitTestStandards.rst
  dev-docs/source/Standards/index.rst
  dev-docs/source/SystemTests.rst
  dev-docs/source/ToolsOverview.rst
  dev-docs/source/WritingCustomConvertToMDTransformation.rst
  dev-docs/source/conf.py
  dev-docs/source/index.rst
Labels: Component: Documentation

#22251 Delete interpreter dock before python shutdown
  MantidPlot/src/ApplicationWindow.cpp
Labels: Component: GUI

#22152 Updated IDF for D2B
  instrument/D2B_2018-03-01_Definition.xml
Labels: Component: Diffraction

#22229 Remove duplicate instrument name property from kafka event listener
  Framework/LiveData/inc/MantidLiveData/Kafka/KafkaEventListener.h
  Framework/LiveData/src/Kafka/KafkaEventListener.cpp
Labels: Component: Live Data

#21716 Add automatic saving of ASCII files to Reflectometry GUI
  docs/source/release/v3.12.0/reflectometry.rst
  qt/scientific_interfaces/ISISReflectometry/CMakeLists.txt
  qt/scientific_interfaces/ISISReflectometry/IReflAsciiSaver.cpp
  qt/scientific_interfaces/ISISReflectometry/IReflAsciiSaver.h
  qt/scientific_interfaces/ISISReflectometry/IReflEventPresenter.h
  qt/scientific_interfaces/ISISReflectometry/IReflEventView.h
  qt/scientific_interfaces/ISISReflectometry/IReflMainWindowPresenter.h
  qt/scientific_interfaces/ISISReflectometry/IReflSaveTabPresenter.h
  qt/scientific_interfaces/ISISReflectometry/IReflSaveTabView.h
  qt/scientific_interfaces/ISISReflectometry/QWidgetGroup.h
  qt/scientific_interfaces/ISISReflectometry/QtReflEventView.cpp
  qt/scientific_interfaces/ISISReflectometry/QtReflEventView.h
  qt/scientific_interfaces/ISISReflectometry/QtReflMainWindowView.cpp
  qt/scientific_interfaces/ISISReflectometry/QtReflMainWindowView.h
  qt/scientific_interfaces/ISISReflectometry/QtReflSaveTabView.cpp
  qt/scientific_interfaces/ISISReflectometry/QtReflSaveTabView.h
  qt/scientific_interfaces/ISISReflectometry/ReflAsciiSaver.cpp
  qt/scientific_interfaces/ISISReflectometry/ReflAsciiSaver.h
  qt/scientific_interfaces/ISISReflectometry/ReflDataProcessorMainPresenter.h
  qt/scientific_interfaces/ISISReflectometry/ReflDataProcessorPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/ReflDataProcessorPresenter.h
  qt/scientific_interfaces/ISISReflectometry/ReflEventPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/ReflEventPresenter.h
  qt/scientific_interfaces/ISISReflectometry/ReflEventWidget.ui
  qt/scientific_interfaces/ISISReflectometry/ReflMainWindowPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/ReflMainWindowPresenter.h
  qt/scientific_interfaces/ISISReflectometry/ReflRunsTabPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/ReflRunsTabPresenter.h
  qt/scientific_interfaces/ISISReflectometry/ReflSaveTabPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/ReflSaveTabPresenter.h
  qt/scientific_interfaces/ISISReflectometry/ReflSaveTabWidget.ui
  qt/scientific_interfaces/test/ReflEventPresenterTest.h
  qt/scientific_interfaces/test/ReflMainWindowPresenterTest.h
  qt/scientific_interfaces/test/ReflMockObjects.h
  qt/scientific_interfaces/test/ReflSaveTabPresenterTest.h
  qt/widgets/common/CMakeLists.txt
  qt/widgets/common/inc/MantidQtWidgets/Common/DataProcessorUI/DataProcessorMainPresenter.h
  qt/widgets/common/inc/MantidQtWidgets/Common/DataProcessorUI/GenericDataProcessorPresenter.h
  qt/widgets/common/inc/MantidQtWidgets/Common/DataProcessorUI/GenericDataProcessorPresenterThread.h
  qt/widgets/common/inc/MantidQtWidgets/Common/DataProcessorUI/TreeData.h
  qt/widgets/common/src/DataProcessorUI/GenericDataProcessorPresenter.cpp
  qt/widgets/common/src/DataProcessorUI/TreeData.cpp
  qt/widgets/common/test/DataProcessorUI/GenericDataProcessorPresenterTest.h
Labels: Component: GUI, Component: Reflectometry

#22262 Corrected Rendering of Rectangular Detectors
  qt/widgets/instrumentview/src/BankRenderingHelpers.cpp
  qt/widgets/instrumentview/src/InstrumentRenderer.cpp
Labels: Component: GUI

#22226 Error when deleting a workspace group in MantidPlot.
  Framework/API/inc/MantidAPI/WorkspaceGroup.h
  Framework/API/src/WorkspaceGroup.cpp
  Framework/API/test/WorkspaceGroupTest.h
  qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidget.cpp
Labels: Component: GUI, Misc: Bug, Patch Candidate

#22205 Fix header for TOPAS files
  Framework/DataHandling/src/SaveFocusedXYE.cpp
  Framework/DataHandling/test/SaveFocusedXYETest.h
Labels: Component: Diffraction, Group: Powder, Misc: Bug, Patch Candidate

#22200 Fix unreliable tests: Disable ClearCache doc test
  buildconfig/Jenkins/buildscript
Labels: Priority: High

#21915 Added unit tests to userfile parser changes
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/SANSStitchTest.py
  scripts/SANS/sans/user_file/user_file_parser.py
  scripts/test/SANS/gui_logic/state_gui_model_test.py
  scripts/test/SANS/user_file/user_file_parser_test.py
  scripts/test/SANSReductionStepsUserFileTest.py
Labels: Component: SANS, Quality: Unit Tests

#21916 Engineering Diffraction GUI - run GSASIIRefineFitPeaks in a separate thread
  Framework/PythonInterface/plugins/algorithms/GSASIIRefineFitPeaks.py
  docs/source/release/v3.13.0/diffraction.rst
  qt/scientific_interfaces/EnggDiffraction/CMakeLists.txt
  qt/scientific_interfaces/EnggDiffraction/EnggDiffGSASFittingModel.cpp
  qt/scientific_interfaces/EnggDiffraction/EnggDiffGSASFittingModel.h
  qt/scientific_interfaces/EnggDiffraction/EnggDiffGSASFittingPresenter.cpp
  qt/scientific_interfaces/EnggDiffraction/EnggDiffGSASFittingPresenter.h
  qt/scientific_interfaces/EnggDiffraction/EnggDiffGSASFittingViewQtWidget.cpp
  qt/scientific_interfaces/EnggDiffraction/EnggDiffGSASFittingViewQtWidget.h
  qt/scientific_interfaces/EnggDiffraction/EnggDiffGSASFittingWorker.cpp
  qt/scientific_interfaces/EnggDiffraction/EnggDiffGSASFittingWorker.h
  qt/scientific_interfaces/EnggDiffraction/EnggDiffMultiRunFittingQtWidget.cpp
  qt/scientific_interfaces/EnggDiffraction/EnggDiffMultiRunFittingQtWidget.h
  qt/scientific_interfaces/EnggDiffraction/GSASIIRefineFitPeaksOutputProperties.cpp
  qt/scientific_interfaces/EnggDiffraction/GSASIIRefineFitPeaksOutputProperties.h
  qt/scientific_interfaces/EnggDiffraction/IEnggDiffFittingPresenter.h
  qt/scientific_interfaces/EnggDiffraction/IEnggDiffGSASFittingModel.h
  qt/scientific_interfaces/EnggDiffraction/IEnggDiffGSASFittingObserver.h
  qt/scientific_interfaces/EnggDiffraction/IEnggDiffGSASFittingPresenter.h
  qt/scientific_interfaces/EnggDiffraction/IEnggDiffGSASFittingView.h
  qt/scientific_interfaces/EnggDiffraction/IEnggDiffMultiRunFittingWidgetView.h
  qt/scientific_interfaces/EnggDiffraction/RunLabel.h
  qt/scientific_interfaces/test/EnggDiffGSASFittingModelMock.h
  qt/scientific_interfaces/test/EnggDiffGSASFittingModelTest.h
  qt/scientific_interfaces/test/EnggDiffGSASFittingPresenterTest.h
  qt/scientific_interfaces/test/EnggDiffGSASFittingViewMock.h
  qt/scientific_interfaces/test/EnggDiffMultiRunFittingWidgetViewMock.h
Labels: Component: Diffraction, Component: GUI, Misc: Bug

#22216 SANS Reduced unit test file dependencies
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/sans/SANSConvertToQTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/sans/SANSScaleTest.py
  Testing/SystemTests/tests/analysis/SANSBatchReductionTest.py
  Testing/SystemTests/tests/analysis/SANSBeamCentreFinderCoreTest.py
  Testing/SystemTests/tests/analysis/SANSDiagnosticPageTest.py
  Testing/SystemTests/tests/analysis/SANSLoadTest.py
  Testing/SystemTests/tests/analysis/SANSMaskWorkspaceTest.py
  Testing/SystemTests/tests/analysis/SANSMoveTest.py
  Testing/SystemTests/tests/analysis/SANSReductionCoreTest.py
  Testing/SystemTests/tests/analysis/SANSSingleReductionTest.py
  scripts/SANS/sans/command_interface/command_interface_state_director.py
  scripts/SANS/sans/common/file_information.py
  scripts/SANS/sans/gui_logic/presenter/gui_state_director.py
  scripts/SANS/sans/gui_logic/presenter/run_tab_presenter.py
  scripts/SANS/sans/state/data.py
  scripts/SANS/sans/state/scale.py
  scripts/SANS/sans/test_helper/file_information_mock.py
  scripts/SANS/sans/test_helper/test_director.py
  scripts/SANS/sans/user_file/state_director.py
  scripts/test/SANS/algorithm_detail/scale_helper_test.py
  scripts/test/SANS/gui_logic/property_manager_service_test.py
  scripts/test/SANS/state/adjustment_test.py
  scripts/test/SANS/state/calculate_transmission_test.py
  scripts/test/SANS/state/convert_to_q_test.py
  scripts/test/SANS/state/data_test.py
  scripts/test/SANS/state/mask_test.py
  scripts/test/SANS/state/move_test.py
  scripts/test/SANS/state/normalize_to_monitor_test.py
  scripts/test/SANS/state/reduction_mode_test.py
  scripts/test/SANS/state/save_test.py
  scripts/test/SANS/state/scale_test.py
  scripts/test/SANS/state/slice_event_test.py
  scripts/test/SANS/state/wavelength_and_pixel_adjustment_test.py
  scripts/test/SANS/state/wavelength_test.py
  scripts/test/SANS/user_file/state_director_test.py
Labels: Component: SANS, Misc: Maintenance

#22283 Fix a date time string error in SaveVulcanGSS.
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SaveVulcanGSS.py
Labels: Component: Diffraction, Misc: Bug

#22277 ConjoinXRuns can receive input workspaces containing Dx values
  Framework/Algorithms/inc/MantidAlgorithms/RunCombinationHelpers/RunCombinationHelper.h
  Framework/Algorithms/src/ConjoinXRuns.cpp
  Framework/Algorithms/src/RunCombinationHelpers/RunCombinationHelper.cpp
  Framework/Algorithms/test/ConjoinXRunsTest.h
  Framework/Algorithms/test/ConvertToPointDataTest.h
  Framework/Algorithms/test/CopyInstrumentParametersTest.h
  Framework/Algorithms/test/MergeRunsTest.h
  Framework/Algorithms/test/RunCombinationHelperTest.h
  Framework/Algorithms/test/WorkspaceCreationHelperTest.h
  Framework/Crystal/test/SCDCalibratePanelsTest.h
  Framework/DataHandling/test/MaskDetectorsTest.h
  Framework/TestHelpers/inc/MantidTestHelpers/WorkspaceCreationHelper.h
  Framework/TestHelpers/src/WorkspaceCreationHelper.cpp
  Framework/WorkflowAlgorithms/test/ExtractQENSMembersTest.h
  docs/source/algorithms/ConjoinXRuns-v1.rst
  docs/source/release/v3.13.0/framework.rst
Labels: Component: Framework

#22290 Updated print statement to python 3 in SaveWorkspaces
  qt/widgets/common/src/SaveWorkspaces.cpp
Labels: Component: SANS, Patch Candidate

#22285 Add script to build dev site
  buildconfig/Jenkins/dev_site.sh
Labels: Component: Documentation, Misc: Maintenance

#22273 Update OFFSPEC Parameter File
  instrument/OFFSPEC_Parameters.xml
Labels: Component: Reflectometry

#22292 Fake dae responsive cancel
  Framework/LiveData/inc/MantidLiveData/ISIS/FakeISISEventDAE.h
  Framework/LiveData/inc/MantidLiveData/ISIS/FakeISISHistoDAE.h
  Framework/LiveData/inc/MantidLiveData/ISIS/ISISLiveEventDataListener.h
  Framework/LiveData/src/ISIS/FakeISISEventDAE.cpp
  Framework/LiveData/src/ISIS/FakeISISHistoDAE.cpp
  Framework/LiveData/src/ISIS/ISISLiveEventDataListener.cpp
  docs/source/algorithms/FakeISISEventDAE-v1.rst
  docs/source/algorithms/FakeISISHistoDAE-v1.rst
  docs/source/algorithms/StartLiveData-v1.rst
Labels: Misc: Bug

#22164 D2B detector efficiency calculation
  Framework/Algorithms/inc/MantidAlgorithms/SumOverlappingTubes.h
  Framework/Algorithms/src/SumOverlappingTubes.cpp
  Framework/Algorithms/test/SumOverlappingTubesTest.h
  Framework/CurveFitting/src/Algorithms/SplineInterpolation.cpp
  Framework/DataHandling/src/LoadILLDiffraction.cpp
  Framework/PythonInterface/plugins/algorithms/ApplyDetectorScanEffCorr.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/PowderDiffILLDetEffCorr.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/PowderDiffILLDetScanReduction.py
  Framework/PythonInterface/test/python/plugins/algorithms/ApplyDetectorScanEffCorrTest.py
  Testing/Data/SystemTest/ILL/D2B/532008.nxs.md5
  Testing/Data/SystemTest/ILL/D2B/532009.nxs.md5
  Testing/SystemTests/tests/analysis/ILLPowderDiffDetScanReductionTest.py
  Testing/SystemTests/tests/analysis/ILL_D2B_DetEffCorrTest.py
  Testing/SystemTests/tests/analysis/reference/D2B_DetEffCorr_Ref.nxs.md5
  Testing/SystemTests/tests/analysis/reference/D2B_scan_test.nxs.md5
  docs/source/algorithms/PowderDiffILLDetEffCorr-v1.rst
  docs/source/algorithms/PowderDiffILLDetScanReduction-v1.rst
  docs/source/algorithms/SumOverlappingTubes-v1.rst
  docs/source/diagrams/PowderDiffILLDetEffCorr-v1_D20_wkflw.dot
  docs/source/diagrams/PowderDiffILLDetEffCorr-v1_D2B_wkflw.dot
  docs/source/images/D20_calib.png
  docs/source/images/D2B_calib.png
  docs/source/release/v3.13.0/diffraction.rst
  instrument/D20_Parameters.xml
  instrument/D2B_Parameters.xml
Labels: Component: Diffraction

#22295 Add information to filtering documentation
  docs/source/algorithms/FilterEvents-v1.rst
  docs/source/algorithms/GenerateEventsFilter-v1.rst
Labels: Component: Documentation

#21739 Implement algorithm FitPeaks
  Framework/Algorithms/CMakeLists.txt
  Framework/Algorithms/inc/MantidAlgorithms/FitPeaks.h
  Framework/Algorithms/src/FitPeaks.cpp
  Framework/Algorithms/test/FitPeaksTest.h
  Testing/Data/UnitTest/vulcan_diamond.nxs.md5
  docs/source/algorithms/FitPeaks-v1.rst
  docs/source/release/v3.13.0/framework.rst
Labels: Component: Framework

#22301 Fix GroupDetectors crash when input doesn't have SpectraAxis
  Framework/DataHandling/inc/MantidDataHandling/GroupDetectors2.h
  Framework/DataHandling/src/GroupDetectors2.cpp
  Framework/DataHandling/test/GroupDetectors2Test.h
  Framework/TestHelpers/inc/MantidTestHelpers/ComponentCreationHelper.h
  Framework/TestHelpers/src/ComponentCreationHelper.cpp
  Framework/TestHelpers/src/WorkspaceCreationHelper.cpp
  docs/source/algorithms/GroupDetectors-v2.rst
  docs/source/release/v3.13.0/framework.rst
Labels: Component: Framework, Misc: Bug

#22308 direct inelastic config script for ISIS
  scripts/Inelastic/Direct/ISISDirecInelasticConfig.py
  scripts/test/ISISDirecInelasticConfigTest.py
Labels: Component: Python, Misc: Easy, Patch Candidate, Priority: High

#22311 Fix OSX docs tests.
  docs/source/algorithms/CrystalFieldEnergies-v1.rst
  docs/source/algorithms/MaxEnt-v1.rst
  docs/source/algorithms/SetUB-v1.rst
  docs/source/concepts/CrystalStructureAndReflections.rst
  docs/source/fitting/fitfunctions/LatticeFunction.rst
Labels: Component: Documentation

#22329 Replace deprecated member function removed in HDF5 1.10.2
  Framework/DataHandling/src/LoadDiffCal.cpp
Labels: Component: Framework

#21744 FitFunction TeixeiraWater lacks Planck constant
  Framework/PythonInterface/plugins/functions/TeixeiraWater.py
  Framework/PythonInterface/test/python/plugins/functions/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/functions/TeixeiraWaterTest.py
  Testing/SystemTests/tests/analysis/ISISIndirectBayesTest.py
  Testing/SystemTests/tests/analysis/reference/ISISIndirectBayes_JumpTeixeiraTest.nxs.md5
  docs/source/fitting/fitfunctions/TeixeiraWater.rst
Labels: Component: Fitting, Misc: Bug

#22145 Fix binning params in the SofQW* algorithms
  Framework/Algorithms/CMakeLists.txt
  Framework/Algorithms/inc/MantidAlgorithms/SofQCommon.h
  Framework/Algorithms/inc/MantidAlgorithms/SofQW.h
  Framework/Algorithms/inc/MantidAlgorithms/SofQWCentre.h
  Framework/Algorithms/inc/MantidAlgorithms/SofQWNormalisedPolygon.h
  Framework/Algorithms/inc/MantidAlgorithms/SofQWPolygon.h
  Framework/Algorithms/src/SofQCommon.cpp
  Framework/Algorithms/src/SofQW.cpp
  Framework/Algorithms/src/SofQWCentre.cpp
  Framework/Algorithms/src/SofQWNormalisedPolygon.cpp
  Framework/Algorithms/src/SofQWPolygon.cpp
  Framework/Algorithms/test/SofQCommonTest.h
  Framework/Algorithms/test/SofQWNormalisedPolygonTest.h
  Framework/Algorithms/test/SofQWTest.h
  Framework/Kernel/inc/MantidKernel/VectorHelper.h
  Framework/Kernel/src/VectorHelper.cpp
  Framework/Kernel/test/VectorHelperTest.h
  docs/source/release/v3.13.0/direct_inelastic.rst
Labels: Component: Direct Inelastic

#22319 Refactor find peak background
  Framework/Algorithms/inc/MantidAlgorithms/FindPeakBackground.h
  Framework/Algorithms/inc/MantidAlgorithms/FitPeaks.h
  Framework/Algorithms/src/FindPeakBackground.cpp
  Framework/Algorithms/src/FitPeaks.cpp
  Framework/Algorithms/test/FitPeaksTest.h
  Framework/HistogramData/CMakeLists.txt
  Framework/HistogramData/inc/MantidHistogramData/EstimatePolynomial.h
  Framework/HistogramData/inc/MantidHistogramData/QuadraticGenerator.h
  Framework/HistogramData/src/EstimatePolynomial.cpp
  Framework/HistogramData/test/EstimatePolynomialTest.h
  Framework/HistogramData/test/QuadraticGeneratorTest.h
Labels: Component: Diffraction, Group: Powder, Misc: Maintenance

#22334 Make SumSpectra::validateInputs aware of WorkspaceGroups
  Framework/Algorithms/inc/MantidAlgorithms/SumSpectra.h
  Framework/Algorithms/src/SumSpectra.cpp
  Framework/Algorithms/test/SumSpectraTest.h
  docs/source/release/v3.13.0/framework.rst
Labels: Component: Framework

#22333 Add qt5-qtx11extras to the developer package.
  buildconfig/dev-packages/deb/mantid-developer/ns-control
  buildconfig/dev-packages/rpm/mantid-developer/mantid-developer.spec
Labels: Group: Vates

#22330 Allow PeaksWorkspace createPeakQSample to calculate goniometer for CW
  Framework/DataObjects/src/PeaksWorkspace.cpp
  Framework/Geometry/inc/MantidGeometry/Instrument/Goniometer.h
  Framework/Geometry/src/Instrument/Goniometer.cpp
  Framework/Geometry/test/GoniometerTest.h
  Framework/MDAlgorithms/src/FindPeaksMD.cpp
  docs/source/algorithms/FindPeaksMD-v1.rst
  docs/source/concepts/PeaksWorkspace.rst
Labels: Component: Diffraction, Group: Single Crystal

#22276 Add force-overwrite option to GSAS-II installation scripts
  scripts/GSAS-II/install_gsas_common.bat
  scripts/GSAS-II/install_gsas_latest.bat
  scripts/GSAS-II/install_gsas_proxy.py
  scripts/GSAS-II/install_gsas_vetted.bat
Labels: Component: Diffraction, Component: Python

#22341 Set CMAKE_SYSTEM_VERSION for external project configuration
  buildconfig/CMake/Eigen.cmake
  buildconfig/CMake/GoogleTest.cmake
  buildconfig/CMake/Python-xmlrunner.cmake
Labels: Component: Framework

#22267 Engineering GUI GSAS tab add Refine All button
  Framework/PythonInterface/plugins/algorithms/GSASIIRefineFitPeaks.py
  docs/source/interfaces/Engineering Diffraction.rst
  docs/source/release/v3.13.0/diffraction.rst
  qt/scientific_interfaces/EnggDiffraction/EnggDiffFittingViewQtWidget.cpp
  qt/scientific_interfaces/EnggDiffraction/EnggDiffFittingViewQtWidget.h
  qt/scientific_interfaces/EnggDiffraction/EnggDiffGSASFittingModel.cpp
  qt/scientific_interfaces/EnggDiffraction/EnggDiffGSASFittingModel.h
  qt/scientific_interfaces/EnggDiffraction/EnggDiffGSASFittingPresenter.cpp
  qt/scientific_interfaces/EnggDiffraction/EnggDiffGSASFittingPresenter.h
  qt/scientific_interfaces/EnggDiffraction/EnggDiffGSASFittingViewQtWidget.cpp
  qt/scientific_interfaces/EnggDiffraction/EnggDiffGSASFittingViewQtWidget.h
  qt/scientific_interfaces/EnggDiffraction/EnggDiffGSASFittingWorker.cpp
  qt/scientific_interfaces/EnggDiffraction/EnggDiffGSASFittingWorker.h
  qt/scientific_interfaces/EnggDiffraction/EnggDiffMultiRunFittingQtWidget.cpp
  qt/scientific_interfaces/EnggDiffraction/EnggDiffMultiRunFittingQtWidget.h
  qt/scientific_interfaces/EnggDiffraction/EnggDiffMultiRunFittingWidgetPresenter.cpp
  qt/scientific_interfaces/EnggDiffraction/EnggDiffMultiRunFittingWidgetPresenter.h
  qt/scientific_interfaces/EnggDiffraction/EnggDiffractionQtTabGSAS.ui
  qt/scientific_interfaces/EnggDiffraction/IEnggDiffGSASFittingModel.h
  qt/scientific_interfaces/EnggDiffraction/IEnggDiffGSASFittingObserver.h
  qt/scientific_interfaces/EnggDiffraction/IEnggDiffGSASFittingPresenter.h
  qt/scientific_interfaces/EnggDiffraction/IEnggDiffMultiRunFittingWidgetPresenter.h
  qt/scientific_interfaces/EnggDiffraction/IEnggDiffMultiRunFittingWidgetView.h
  qt/scientific_interfaces/test/EnggDiffGSASFittingModelMock.h
  qt/scientific_interfaces/test/EnggDiffGSASFittingModelTest.h
  qt/scientific_interfaces/test/EnggDiffGSASFittingPresenterTest.h
  qt/scientific_interfaces/test/EnggDiffMultiRunFittingWidgetPresenterMock.h
  qt/scientific_interfaces/test/EnggDiffMultiRunFittingWidgetPresenterTest.h
  qt/scientific_interfaces/test/EnggDiffMultiRunFittingWidgetViewMock.h
Labels: Component: Diffraction, Component: GUI
