Repository mantidproject/mantid, pull requests merged in 2019-11, with the labels that each got.

#27108 Fix sequential fitting bug to update parameters and do plot
  docs/source/release/v4.2.0/mantidworkbench.rst
  qt/python/mantidqt/_common.sip
  qt/python/mantidqt/widgets/fitpropertybrowser/fitpropertybrowser.py
  qt/widgets/common/inc/MantidQtWidgets/Common/FitPropertyBrowser.h
  qt/widgets/common/inc/MantidQtWidgets/Common/SequentialFitDialog.h
  qt/widgets/common/src/FitPropertyBrowser.cpp
  qt/widgets/common/src/SequentialFitDialog.cpp
Labels: ISIS Team: CoreTeam

#27214 Muon Analysis 2 Crash When Fitting
  docs/source/release/v4.2.0/muon.rst
  qt/widgets/common/src/FunctionTreeView.cpp
Labels: ISIS Team: Spectroscopy, Muon

#27218 Add unscripted test instructions for live data
  dev-docs/source/Testing/LiveData/LiveDataTests.rst
  dev-docs/source/Testing/index.rst
Labels: Documentation

#27219 Bundle mock with macOS Python
  installers/MacInstaller/make_package.rb
Labels: Easy, macOS Only

#27240 Create skeleton release notes for version 4.3
  docs/source/release/index.rst
  docs/source/release/v4.3.0/diffraction.rst
  docs/source/release/v4.3.0/direct_geometry.rst
  docs/source/release/v4.3.0/framework.rst
  docs/source/release/v4.3.0/index.rst
  docs/source/release/v4.3.0/indirect_geometry.rst
  docs/source/release/v4.3.0/mantidplot.rst
  docs/source/release/v4.3.0/mantidworkbench.rst
  docs/source/release/v4.3.0/muon.rst
  docs/source/release/v4.3.0/reflectometry.rst
  docs/source/release/v4.3.0/sans.rst
  docs/source/release/v4.3.0/ui.rst
  tools/release_generator/release.py
Labels: Documentation

#27230 Fix SANS MUD crash on changing save dir
  docs/source/release/v4.2.0/sans.rst
  scripts/Interface/ui/sans_isis/sans_data_processor_gui.py
  scripts/SANS/sans/gui_logic/models/create_state.py
Labels: Bug, Easy, ISIS Team: LSS, SANS

#27234 Direct inelastic reduction string and unboundedlocal bugfixes
  scripts/Inelastic/Direct/AbsorptionShapes.py
  scripts/Inelastic/Direct/CommonFunctions.py
  scripts/Inelastic/Direct/DirectEnergyConversion.py
  scripts/Inelastic/Direct/ISISDirecInelasticConfig.py
  scripts/Inelastic/Direct/NonIDF_Properties.py
  scripts/Inelastic/Direct/PropertiesDescriptors.py
  scripts/Inelastic/Direct/PropertyManager.py
  scripts/Inelastic/Direct/ReductionHelpers.py
  scripts/Inelastic/Direct/ReductionWrapper.py
  scripts/Inelastic/Direct/RunDescriptor.py
  scripts/Inelastic/Direct/dgreduce.py
  scripts/Inelastic/Direct/diagnostics.py
  scripts/test/DirectPropertyManagerTest.py
Labels: Bug, Direct Inelastic, High Priority, Workbench

#27213 Updates to Error Report Manual Testing
  dev-docs/source/Testing/ErrorReporter-ProjectRecovery/ErrorReporterTesting.rst
Labels: Documentation

#27217 Disable fit button for tiled plots
  qt/applications/workbench/workbench/plotting/figuremanager.py
Labels: Fitting, ISIS Team: CoreTeam

#27237 Fix colorbar scale not updating in colorfill plot
  qt/python/mantidqt/widgets/plotconfigdialog/imagestabwidget/presenter.py
  qt/python/mantidqt/widgets/plotconfigdialog/imagestabwidget/test/test_imagestabwidgetpresenter.py
Labels: High Priority, ISIS Team: CoreTeam, Workbench

#27209 Add catch for negative min x when plotting with a log scale
  qt/python/mantidqt/widgets/plotconfigdialog/axestabwidget/presenter.py
  qt/python/mantidqt/widgets/plotconfigdialog/axestabwidget/test/test_axestabwidgetpresenter.py
Labels: Bug, Workbench

#27235 Fix Duplication of Workspaces in GroupWorkspaces when Saving Projects
  docs/source/release/v4.2.0/mantidworkbench.rst
  qt/python/mantidqt/project/project.py
  qt/python/mantidqt/project/test/test_project.py
Labels: Added during Sprint, ISIS Team: Diffraction, Workbench

#27254 Package ParaView python modules on macOS
  Framework/PythonInterface/mantid/BundlePython.cmake
  buildconfig/CMake/DarwinSetup.cmake
  installers/MacInstaller/make_package.rb
Labels: macOS Only

#27243 Add unscripted testing instructions for ISIS Reflectometry
  dev-docs/source/Testing/ReflectometryGUI/ReflectometryGUITests.rst
  dev-docs/source/Testing/index.rst
Labels: Documentation, Reflectometry

#27270 Correct precision for header on data window
  docs/source/release/v4.2.0/mantidworkbench.rst
  qt/python/mantidqt/widgets/workspacedisplay/matrix/table_view_model.py
Labels: ISIS Team: CoreTeam, Workbench

#27067 Remove group of groups from elemental analysis
  docs/source/release/v4.2.0/muon.rst
  scripts/Muon/GUI/ElementalAnalysis/LoadWidget/load_utils.py
  scripts/Muon/GUI/ElementalAnalysis/elemental_analysis.py
  scripts/test/Muon/elemental_analysis/elemental_analysis_test.py
  scripts/test/Muon/elemental_analysis/lmodel_test.py
  scripts/test/Muon/elemental_analysis/load_utils_test.py
Labels: ISIS Team: Spectroscopy

#27220 Restore functionality to the home button
  qt/applications/workbench/workbench/plotting/figuremanager.py
Labels: Easy, Workbench

#27251 Fix meaning of wavelength_spread in HFIRSANS2Wavelength
  Framework/PythonInterface/plugins/algorithms/HFIRSANS2Wavelength.py
  Framework/PythonInterface/test/python/plugins/algorithms/HFIRSANS2WavelengthTest.py
  docs/source/algorithms/HFIRSANS2Wavelength-v1.rst
Labels: SANS

#27259 Keep interfaces above workbench when plot is loaded
  qt/applications/workbench/workbench/plotting/figurewindow.py
Labels: ISIS Team: CoreTeam, ISIS Team: Spectroscopy, Windows Only

#27263 Log Xvfb errors to a file
  buildconfig/Jenkins/buildscript
Labels: Unit Tests

#27258 fix plotting multiple single spectra workspaces
  qt/python/mantidqt/dialogs/spectraselectordialog.py
  qt/python/mantidqt/dialogs/spectraselectorutils.py
  qt/python/mantidqt/dialogs/test/test_spectraselectiondialog.py
  qt/python/mantidqt/dialogs/test/test_spectraselectorutils.py
Labels: Added during Sprint, Bug, Easy, ISIS Team: CoreTeam, Workbench

#27089 Modify registerFeatureUsage in usage service to reduce misuse
  Framework/API/src/Algorithm.cpp
  Framework/Kernel/inc/MantidKernel/UsageService.h
  Framework/Kernel/src/UsageService.cpp
  Framework/Kernel/test/UsageServiceTest.h
  Framework/PythonInterface/mantid/kernel/src/Exports/UsageService.cpp
  Framework/PythonInterface/test/python/mantid/kernel/UsageServiceTest.py
  MantidPlot/src/Mantid/InstrumentWidget/InstrumentWindow.cpp
  MantidPlot/src/ProjectRecovery.cpp
  MantidPlot/src/ProjectRecoveryGUIs/ProjectRecoveryView.cpp
  MantidPlot/src/ProjectRecoveryGUIs/RecoveryFailureView.cpp
  qt/paraview_ext/VatesSimpleGui/ViewWidgets/src/MdViewerWidget.cpp
  qt/scientific_interfaces/DynamicPDF/DPDFBackgroundRemover.cpp
  qt/scientific_interfaces/DynamicPDF/SliceSelector.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Event/QtEventView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/QtExperimentView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Instrument/QtInstrumentView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/MainWindow/QtMainWindowView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Runs/QtRunsView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/RunsTable/QtRunsTableView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/QtSaveView.cpp
  qt/widgets/common/inc/MantidQtWidgets/Common/TrackedAction.h
  qt/widgets/common/src/TrackedAction.cpp
  qt/widgets/common/src/UserSubWindow.cpp
  qt/widgets/common/test/TrackedActionTest.h
  qt/widgets/sliceviewer/src/LineViewer.cpp
  qt/widgets/sliceviewer/src/PeaksViewer.cpp
  qt/widgets/sliceviewer/src/SliceViewer.cpp
  qt/widgets/spectrumviewer/src/SpectrumView.cpp
  scripts/DGSPlanner/DGSPlannerGUI.py
  scripts/FilterEvents/eventFilterGUI.py
  scripts/HFIR_4Circle_Reduction/reduce4circleControl.py
  scripts/Interface/reduction_gui/reduction/scripter.py
  scripts/Interface/ui/reflectometer/refl_gui.py
  scripts/Interface/ui/sans_isis/SANSSaveOtherWindow.py
  scripts/Interface/ui/sans_isis/beam_centre.py
  scripts/Interface/ui/sans_isis/sans_data_processor_gui.py
  scripts/Interface/ui/sans_isis/settings_diagnostic_tab.py
  scripts/Muon/GUI/Common/usage_report.py
  scripts/QECoverage.py
  scripts/TofConverter/converterGUI.py
Labels: ISIS Team: CoreTeam

#27233 Restrict ISIS Reflectometry batch save/load file extension
  qt/scientific_interfaces/ISISReflectometry/GUI/MainWindow/MainWindowPresenter.cpp
  qt/widgets/common/inc/MantidQtWidgets/Common/QtJSONUtils.h
  qt/widgets/common/src/QtJSONUtils.cpp
  qt/widgets/common/test/QtJSONUtilsTest.h
Labels: Added during Sprint, Easy, ISIS Team: LSS, Reflectometry

#27286 Accept spec nums other than 4 or 5 for SANS Monitor
  scripts/SANS/sans/user_file/user_file_parser.py
  scripts/test/SANS/user_file/user_file_parser_test.py
Labels: Bug, Easy, High Priority, ISIS Team: LSS, SANS

#27292 Fix documentation typo in DetectorInfoItem
  Framework/Geometry/inc/MantidGeometry/Instrument/DetectorInfoItem.h
Labels: Easy

#27287 Add back event slices tooltip
  scripts/Interface/ui/sans_isis/sans_data_processor_window.ui
Labels: Documentation, Easy, ISIS Team: LSS, SANS

#27296 Add check on qt version to disable docking in I(Q, t) fit tab browser
  qt/scientific_interfaces/Indirect/IndirectFitAnalysisTab.cpp
Labels: ISIS Team: Spectroscopy, Workbench

#27239 Move file loading and processing async in SANS
  scripts/SANS/sans/gui_logic/models/batch_process_runner.py
  scripts/SANS/sans/gui_logic/models/table_model.py
  scripts/SANS/sans/gui_logic/presenter/create_file_information.py
  scripts/SANS/sans/gui_logic/presenter/run_tab_presenter.py
  scripts/SANS/sans/state/data.py
  scripts/test/SANS/gui_logic/CMakeLists.txt
  scripts/test/SANS/gui_logic/batch_process_runner_test.py
  scripts/test/SANS/gui_logic/create_file_information_test.py
  scripts/test/SANS/gui_logic/run_tab_presenter_test.py
  scripts/test/SANS/gui_logic/table_model_test.py
Labels: Bug, ISIS Team: LSS, SANS

#27276 Fix figure options on matplotlib v1.5 - RHEL7 only
  qt/python/mantidqt/widgets/plotconfigdialog/legendtabwidget/legend_tab.ui
  qt/python/mantidqt/widgets/plotconfigdialog/legendtabwidget/presenter.py
  qt/python/mantidqt/widgets/plotconfigdialog/legendtabwidget/view.py
Labels: Bug, High Priority, ISIS Team: CoreTeam, Linux Only, Workbench

#27273 Update Release Notes 4.2
  docs/source/images/CHESS.PNG
  docs/source/images/IndexPeaks.PNG
  docs/source/images/MantidPlotMeme.jpg
  docs/source/images/PredictFractionalPeaks.png
  docs/source/images/UpdateOS.png
  docs/source/images/WB_ColormapIcons.png
  docs/source/images/WB_GenerateaScript.png
  docs/source/images/WB_Scriptrepo.png
  docs/source/images/WB_Tiled.png
  docs/source/images/WB_Viewmessages.png
  docs/source/images/fish.jpeg
  docs/source/release/v4.2.0/diffraction.rst
  docs/source/release/v4.2.0/direct_geometry.rst
  docs/source/release/v4.2.0/framework.rst
  docs/source/release/v4.2.0/index.rst
  docs/source/release/v4.2.0/indirect_geometry.rst
  docs/source/release/v4.2.0/mantidplot.rst
  docs/source/release/v4.2.0/mantidworkbench.rst
Labels: Documentation, High Priority

#27301 Update Release Notes v4.2 Step2
  docs/source/images/LiveDataUserInput.png
  docs/source/images/MuonAnalysis.PNG
  docs/source/release/v4.2.0/muon.rst
  docs/source/release/v4.2.0/reflectometry.rst
  docs/source/release/v4.2.0/sans.rst
Labels: Documentation, High Priority

#27303 Convert output workspace from elemental analysis to histogram
  scripts/Muon/GUI/ElementalAnalysis/LoadWidget/load_utils.py
Labels: ISIS Team: Spectroscopy

#27295 Pull in latest fixes for mslice from external repository
  scripts/ExternalInterfaces/CMakeLists.txt
Labels: Direct Inelastic

#27255 Update to PEARL IDF
  Testing/SystemTests/tests/analysis/reference/ISIS_Powder-PEARL00098472_splined.nxs.md5
  Testing/SystemTests/tests/analysis/reference/ISIS_Powder-PEARL00098507_tt70Atten.nxs.md5
  Testing/SystemTests/tests/analysis/reference/ISIS_Powder-PEARL00098507_tt70_absorb.nxs.md5
  Testing/SystemTests/tests/analysis/reference/ISIS_Powder_PRL98472_tt70_all.nxs.md5
  Testing/SystemTests/tests/analysis/reference/ISIS_Powder_PRL98472_tt70_groups.nxs.md5
  Testing/SystemTests/tests/analysis/reference/ISIS_Powder_PRL98472_tt70_mods.nxs.md5
  Testing/SystemTests/tests/analysis/reference/ISIS_Powder_PRL98472_tt70_trans.nxs.md5
  docs/source/release/v4.2.0/framework.rst
  instrument/PEARL_Definition_new_lowangle.xml
Labels: Framework

#27194 Add constraint slots so signal is passed through
  qt/widgets/common/inc/MantidQtWidgets/Common/EditLocalParameterDialog.h
  qt/widgets/common/inc/MantidQtWidgets/Common/LocalParameterItemDelegate.h
  qt/widgets/common/src/EditLocalParameterDialog.cpp
  qt/widgets/common/src/FunctionBrowser/FunctionBrowserUtils.cpp
  qt/widgets/common/src/FunctionModel.cpp
  qt/widgets/common/src/LocalParameterEditor.cpp
Labels: Added during Sprint, Fitting, ISIS Team: CoreTeam

#27302 Change output name in fit browser for multiple plots of the same workspace
  docs/source/release/v4.2.0/mantidworkbench.rst
  qt/python/mantidqt/widgets/fitpropertybrowser/fitpropertybrowser.py
  qt/python/mantidqt/widgets/test/test_fitpropertybrowser.py
Labels: Bug, Fitting, ISIS Team: CoreTeam

#27306 Fix Mantid crashing if the ALC interface was closed while loading a data set.
  docs/source/release/v4.2.0/muon.rst
  qt/scientific_interfaces/Muon/ALCDataLoadingPresenter.cpp
  qt/scientific_interfaces/Muon/ALCDataLoadingPresenter.h
  qt/scientific_interfaces/Muon/ALCInterface.cpp
  qt/scientific_interfaces/Muon/ALCInterface.h
Labels: ISIS Team: Spectroscopy

#27323 Release Notes 4.2 Step3
  docs/source/images/CHESS.PNG
  docs/source/release/v4.2.0/diffraction.rst
  docs/source/release/v4.2.0/direct_geometry.rst
  docs/source/release/v4.2.0/framework.rst
  docs/source/release/v4.2.0/index.rst
  docs/source/release/v4.2.0/indirect_geometry.rst
  docs/source/release/v4.2.0/mantidworkbench.rst
  docs/source/release/v4.2.0/muon.rst
  docs/source/release/v4.2.0/sans.rst
  docs/source/release/v4.2.0/ui.rst
Labels: Documentation, High Priority

#27311 Update reflectometry release notes
  docs/source/images/LiveDataUserInput.png
  docs/source/images/Reflectometry-GUI-release4.2.png
  docs/source/release/v4.2.0/reflectometry.rst
Labels: Documentation, High Priority

#27285 Add case for sqw workspaces in show data
  docs/source/release/v4.2.0/mantidworkbench.rst
  qt/python/mantidqt/utils/testing/mocks/mock_mantid.py
  qt/python/mantidqt/widgets/workspacedisplay/matrix/table_view_model.py
  qt/python/mantidqt/widgets/workspacedisplay/matrix/test/test_matrixworkspacedisplay_table_view_model.py
Labels: ISIS Team: CoreTeam, Workbench

#27308 Added application to feature usage messages
  Framework/Kernel/inc/MantidKernel/UsageService.h
  Framework/Kernel/src/UsageService.cpp
Labels: Framework

#27304 Fix user sample thickness resetting when processing data
  scripts/SANS/sans/gui_logic/models/table_model.py
  scripts/test/SANS/gui_logic/gui_state_director_test.py
  scripts/test/SANS/gui_logic/table_model_test.py
Labels: Bug, ISIS Team: LSS, SANS

#26972 Fix ConvertToMD Q conversion for indirect spectroscopy
  Framework/MDAlgorithms/inc/MantidMDAlgorithms/MDTransfModQ.h
  Framework/MDAlgorithms/inc/MantidMDAlgorithms/MDTransfQ3D.h
  Framework/MDAlgorithms/src/MDTransfModQ.cpp
  Framework/MDAlgorithms/src/MDTransfQ3D.cpp
  Framework/MDAlgorithms/test/MDTransfQ3DTest.h
  Framework/TestHelpers/src/WorkspaceCreationHelper.cpp
  docs/source/release/v4.2.0/framework.rst
Labels: High Priority, ISIS Team: Spectroscopy, Indirect Inelastic

#27227 Fix ISIS Reflectometry batch load crash
  qt/scientific_interfaces/ISISReflectometry/GUI/MainWindow/MainWindowPresenter.cpp
  qt/widgets/common/inc/MantidQtWidgets/Common/QtJSONUtils.h
  qt/widgets/common/src/QtJSONUtils.cpp
  qt/widgets/common/test/QtJSONUtilsTest.h
Labels: Easy, ISIS Team: LSS, Reflectometry

#27325 Remove disconnected start and end x comboboxes
  qt/scientific_interfaces/Indirect/IIndirectFitDataView.h
  qt/scientific_interfaces/Indirect/IIndirectFitDataViewLegacy.h
  qt/scientific_interfaces/Indirect/IndirectFitDataView.cpp
  qt/scientific_interfaces/Indirect/IndirectFitDataView.h
  qt/scientific_interfaces/Indirect/IndirectFitDataView.ui
  qt/scientific_interfaces/Indirect/IndirectFitDataViewLegacy.cpp
  qt/scientific_interfaces/Indirect/IndirectFitDataViewLegacy.h
  qt/scientific_interfaces/Indirect/IqtFit.cpp
  qt/scientific_interfaces/Indirect/IqtFit.h
  qt/scientific_interfaces/Indirect/test/ConvFitDataPresenterTest.h
  qt/scientific_interfaces/Indirect/test/IndirectFitDataPresenterTest.h
  qt/scientific_interfaces/Indirect/test/JumpFitDataPresenterTest.h
Labels: Bug, Indirect Inelastic

#27265 Estimates initial parameters for exponential function in Iqtfit
  docs/source/release/v4.2.0/indirect_geometry.rst
  qt/scientific_interfaces/Indirect/IndirectFunctionBrowser/IqtFunctionModel.cpp
  qt/scientific_interfaces/Indirect/IndirectFunctionBrowser/IqtFunctionModel.h
Labels: ISIS Team: Spectroscopy, Indirect Inelastic

#27327 Fix various memory bugs detected by the address sanitizer
  Framework/DataObjects/inc/MantidDataObjects/MDEventWorkspace.h
  Framework/DataObjects/inc/MantidDataObjects/MDEventWorkspace.tcc
  Framework/Parallel/inc/MantidParallel/IO/EventParser.h
  qt/scientific_interfaces/EnggDiffraction/EnggDiffFittingModel.cpp
  qt/scientific_interfaces/test/ISISReflectometry/Reduction/ValidateRowTest.h
  qt/widgets/sliceviewer/inc/MantidQtWidgets/SliceViewer/LineViewer.h
  qt/widgets/sliceviewer/src/LineViewer.cpp
Labels: Bug

#27333 Make overplotting preserve legend properties
  Framework/PythonInterface/mantid/plots/__init__.py
  qt/python/mantidqt/plotting/functions.py
Labels: Bug, Easy, ISIS Team: CoreTeam, Python, Workbench

#27329 Fix compiler warnings in debug build
  qt/scientific_interfaces/Indirect/IndirectFittingModel.cpp
  qt/scientific_interfaces/Indirect/IndirectFunctionBrowser/IqtFunctionModel.cpp
Labels: Bug

#27315 Use file name rather than nxs tag in SANS
  Testing/SystemTests/tests/analysis/SANS2DReductionGUIAddedTest_V2.py
  Testing/SystemTests/tests/analysis/SANSLOQCan2D_V2.py
  docs/source/release/v4.2.0/sans.rst
  scripts/SANS/sans/common/file_information.py
  scripts/SANS/sans/gui_logic/presenter/gui_state_director.py
  scripts/SANS/sans/test_helper/file_information_mock.py
  scripts/test/SANS/common/file_information_test.py
  scripts/test/SANS/state/data_test.py
Labels: ISIS Team: LSS, SANS

#27336 Fix no script output when Workbench is first opened
  qt/applications/workbench/workbench/app/mainwindow.py
Labels: Bug, Easy, ISIS Team: CoreTeam, Python, Workbench

#27320 RROA now scales IvsQ outputs
  Framework/Algorithms/inc/MantidAlgorithms/ReflectometryReductionOneAuto3.h
  Framework/Algorithms/src/ReflectometryReductionOneAuto3.cpp
  Framework/Algorithms/test/ReflectometryReductionOneAuto3Test.h
  docs/source/algorithms/ReflectometryReductionOneAuto-v3.rst
  docs/source/release/v4.2.0/reflectometry.rst
Labels: Framework, ISIS Team: LSS, Reflectometry

#27328 Rename Iqt fit multifit workspaces with run and spectrum numbe…
  qt/scientific_interfaces/Indirect/IndirectFitOutput.cpp
Labels: ISIS Team: Spectroscopy, Indirect Inelastic

#27347 Fix import error opening old Reflectometry GUI
  scripts/Interface/ui/reflectometer/refl_gui.py
Labels: Bug, ISIS Team: LSS, MantidPlot, Reflectometry

#27352 Fix legend transparency not showing correct value in figure options
  qt/python/mantidqt/widgets/plotconfigdialog/legendtabwidget/presenter.py
Labels: Easy, ISIS Team: CoreTeam, Python, Workbench

#27264 Muon AlC interface crashes
  docs/source/release/v4.2.0/muon.rst
  qt/scientific_interfaces/Muon/ALCDataLoadingPresenter.cpp
  qt/scientific_interfaces/Muon/ALCLatestFileFinder.cpp
  qt/scientific_interfaces/test/ALCLatestFileFinderTest.h
Labels: Added during Sprint, ISIS Team: Spectroscopy

#27356 Fix plot types for plots created from data table
  Framework/PythonInterface/mantid/plots/__init__.py
  qt/python/mantidqt/widgets/fitpropertybrowser/fitpropertybrowser.py
Labels: High Priority, ISIS Team: CoreTeam, Workbench

#27358 Fix CreateDetectorTable causing crash when value entered for WorkspaceIndices is outside of the range of workspace indices
  Framework/Algorithms/inc/MantidAlgorithms/CreateDetectorTable.h
  Framework/Algorithms/src/CreateDetectorTable.cpp
Labels: Framework, ISIS Team: CoreTeam

#27322 Fix problem with help window appearing behind Indirect settings
  MantidPlot/src/ApplicationWindow.cpp
  qt/applications/workbench/workbench/app/mainwindow.py
  qt/scientific_interfaces/Indirect/IndirectInterface.cpp
  qt/scientific_interfaces/Indirect/IndirectSettings.cpp
  qt/scientific_interfaces/Indirect/IndirectSettings.h
  qt/widgets/common/inc/MantidQtWidgets/Common/InterfaceManager.h
  qt/widgets/common/src/InterfaceManager.cpp
Labels: Bug, Indirect Inelastic

#27335 Updates to release notes v4.2 Step 4
  docs/source/images/ALFview.PNG
  docs/source/images/Indirect_Data_Analysis_IqtFit.PNG
  docs/source/release/v4.2.0/diffraction.rst
  docs/source/release/v4.2.0/direct_geometry.rst
  docs/source/release/v4.2.0/index.rst
  docs/source/release/v4.2.0/mantidworkbench.rst
  docs/source/release/v4.2.0/muon.rst
  docs/source/release/v4.2.0/reflectometry.rst
  docs/source/release/v4.2.0/sans.rst
Labels: Documentation, High Priority

#27357 Disallow opening multiple instances of an interface
  qt/applications/workbench/workbench/app/mainwindow.py
Labels: ISIS Team: CoreTeam, ISIS Team: LSS

#27338 Muon load next run
  scripts/Muon/GUI/Common/load_run_widget/load_run_presenter.py
  scripts/test/Muon/load_run_widget/loadrun_presenter_increment_decrement_test.py
  scripts/test/Muon/load_run_widget/loadrun_presenter_multiple_file_test.py
Labels: ISIS Team: Spectroscopy, Muon

#27277 Update naming iniqt fit
  qt/scientific_interfaces/Indirect/CMakeLists.txt
  qt/scientific_interfaces/Indirect/IndirectBayes.h
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisTab.h
  qt/scientific_interfaces/Indirect/IndirectFitAnalysisTab.cpp
  qt/scientific_interfaces/Indirect/IndirectFitAnalysisTab.h
  qt/scientific_interfaces/Indirect/IqtFit.cpp
  qt/scientific_interfaces/Indirect/test/CMakeLists.txt
  qt/scientific_interfaces/Indirect/test/IndirectFitAnalysisTabTest.h
Labels: ISIS Team: Spectroscopy, Indirect Inelastic

#27339 Fix problem with naming of output workspaces from Jump Fit (aka F(Q) Fit)
  qt/scientific_interfaces/Indirect/JumpFitModel.cpp
Labels: ISIS Team: Spectroscopy, Indirect Inelastic

#27344 Fix crash with completion API on workbench
  qt/python/mantidqt/widgets/codeeditor/completion.py
  qt/python/mantidqt/widgets/codeeditor/test/test_completion.py
Labels: High Priority, Workbench

#27341 Use full wavelength range in HRPD efficiency correction
  Testing/SystemTests/tests/analysis/ISIS_PowderHRPDTest.py
  Testing/SystemTests/tests/analysis/reference/HRPD66063_focused_with_sac.nxs.md5
  docs/source/release/v4.2.0/diffraction.rst
  scripts/Diffraction/isis_powder/hrpd.py
  scripts/Diffraction/isis_powder/hrpd_routines/hrpd_param_mapping.py
Labels: Diffraction

#27366 Allow Scripts Containing Encoding Declarations to be Loaded and Run in Workbench
  qt/python/mantidqt/widgets/codeeditor/completion.py
  qt/python/mantidqt/widgets/codeeditor/execution.py
Labels: Framework, Python, Workbench

#27373 Add Poisson documentation
  docs/source/fitting/fitcostfunctions/Poisson.rst
  docs/source/fitting/fitcostfunctions/index.rst
  docs/source/fitting/index.rst
  docs/source/images/Poisson.png
  docs/source/index.rst
Labels: Documentation, ISIS Team: Spectroscopy

#27343 Fix crash when setting max cores lower than machine cores on Linux
  Framework/Algorithms/src/SofQWNormalisedPolygon.cpp
  docs/source/release/v4.2.0/indirect_geometry.rst
Labels: Direct Inelastic, High Priority, Linux Only

#27385 Fix legend resetting after clearing fit curves
  Framework/PythonInterface/mantid/plots/__init__.py
Labels: Bug, Easy, ISIS Team: CoreTeam, Python, Workbench

#27388 Release notes 4.2 final fixes
  docs/source/images/WB_ColorbarMin0KnownIssue.PNG
  docs/source/release/v4.2.0/diffraction.rst
  docs/source/release/v4.2.0/index.rst
  docs/source/release/v4.2.0/mantidworkbench.rst
Labels: Documentation, High Priority

#27402 Handle point/binned numeric axes in workbench data table.
  qt/python/mantidqt/widgets/workspacedisplay/matrix/table_view_model.py
  qt/python/mantidqt/widgets/workspacedisplay/matrix/test/test_matrixworkspacedisplay_table_view_model.py
Labels: High Priority, Workbench

#27403 Fix issue with scripts containing unicode characters on unix systems
  qt/python/mantidqt/utils/writetosignal.py
Labels: High Priority, Linux Only, Workbench, macOS Only

#27404 Make c++ interfaces not children of workbench
  qt/applications/workbench/workbench/app/mainwindow.py
Labels: High Priority, Workbench

#27419 Fix settings not being respected in SANS settings
  scripts/SANS/sans/gui_logic/presenter/presenter_common.py
  scripts/test/SANS/gui_logic/presenter_tests/CMakeLists.txt
  scripts/test/SANS/gui_logic/presenter_tests/presenter_common_test.py
Labels: Bug, ISIS Team: LSS, SANS

#27421 Fix minimising crash on linux
  qt/applications/workbench/workbench/app/mainwindow.py
Labels: Bug, Linux Only, Workbench

#27423 Fix crash when opening any help menu after opening the Manage User Directories help menu
  docs/source/release/v4.2.0/mantidplot.rst
  docs/source/release/v4.2.0/mantidworkbench.rst
  qt/widgets/common/src/ManageUserDirectories.cpp
Labels: Bug, Easy, ISIS Team: CoreTeam, MantidPlot, Workbench

#27410 Rewrite the HB3A IDF
  instrument/HB3A_Definition_20190926_3.xml
Labels: Diffraction, Single Crystal

#27351 EQSANS adjust detector bank position when loading the instrument
  docs/source/release/v4.3.0/sans.rst
  instrument/EQ-SANS_Definition.xml
  instrument/EQ-SANS_Definition_20190615_20190930.xml
Labels: SANS

#27422 Elemental analysis cannot load if dirty paths
  scripts/Muon/GUI/ElementalAnalysis/LoadWidget/load_utils.py
Labels: Bug, ISIS Team: Spectroscopy

#27425 Fixing layouts in IndirectFitDataView
  qt/scientific_interfaces/Indirect/IndirectFitDataView.ui
Labels: ISIS Team: Spectroscopy

#27426 Adds `hasAnyMaskedBins` on MatrixWorkspace
  Framework/API/inc/MantidAPI/MatrixWorkspace.h
  Framework/API/src/MatrixWorkspace.cpp
  Framework/API/test/MatrixWorkspaceTest.h
  Framework/PythonInterface/mantid/api/src/Exports/MatrixWorkspace.cpp
  Framework/PythonInterface/test/python/mantid/api/MatrixWorkspaceTest.py
Labels: Easy

#27428 Fix performance tests
  Framework/Algorithms/test/FindPeaksTest.h
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/LoadVulcanCalFile.h
  Framework/DataHandling/src/LoadVulcanCalFile.cpp
  Framework/DataHandling/test/LoadVulcanCalFileTest.h
  docs/source/algorithms/LoadVulcanCalFile-v1.rst
Labels: Maintenance

#27326 Custom output name does not have details within
  Testing/SystemTests/tests/analysis/LOQCentreNoGrav_V2.py
  Testing/SystemTests/tests/analysis/LOQReductionGUITest_V2.py
  Testing/SystemTests/tests/analysis/SANS2DBatchTest_V2.py
  Testing/SystemTests/tests/analysis/SANS2DFrontNoGrav.py
  Testing/SystemTests/tests/analysis/SANS2DFrontNoGrav_V2.py
  Testing/SystemTests/tests/analysis/SANS2DLimitEventsTime_V2.py
  Testing/SystemTests/tests/analysis/SANS2DMultiPeriodAddFilesTest_V2.py
  Testing/SystemTests/tests/analysis/SANS2DMultiPeriod_V2.py
  Testing/SystemTests/tests/analysis/SANS2DReductionGUIAddedTest_V2.py
  Testing/SystemTests/tests/analysis/SANS2DReductionGUI_V2.py
  Testing/SystemTests/tests/analysis/SANS2DSlicingTest_V2.py
  Testing/SystemTests/tests/analysis/SANS2DWaveloopsTest_V2.py
  Testing/SystemTests/tests/analysis/SANSBatchReductionTest.py
  Testing/SystemTests/tests/analysis/SANSLOQBatch_V2.py
  Testing/SystemTests/tests/analysis/SANSLOQCan2D_V2.py
  Testing/SystemTests/tests/analysis/SANSMergedDetectorsTest_V2.py
  docs/source/release/v4.2.0/sans.rst
  scripts/SANS/sans/common/general_functions.py
  scripts/test/SANS/common/general_functions_test.py
Labels: Bug, ISIS Team: LSS, SANS

#27457 Require Boost 1.65 as a minimum
  CMakeLists.txt
  Framework/API/src/AlgorithmHistory.cpp
  Framework/API/src/WorkspaceHistory.cpp
  buildconfig/CMake/CommonSetup.cmake
  buildconfig/CMake/FindBoostPython.cmake
Labels: ISIS Team: Diffraction, Maintenance

#27294 error: ‘size_t’ was not declared in this scope
  Framework/Indexing/inc/MantidIndexing/Extract.h
  Framework/Indexing/inc/MantidIndexing/Group.h
Labels: Bug

#27455 Add archive mounting instructions for Ubuntu
  dev-docs/source/GettingStarted.rst
Labels: Documentation, Easy, ISIS Team: Diffraction, Maintenance

#27395 Change the way legends are updated after doing a fit or plot guess
  qt/python/mantidqt/widgets/fitpropertybrowser/fitpropertybrowser.py
Labels: Code Quality, ISIS Team: CoreTeam, Python, Workbench

#27478 Update MaskBTP with the new instrument names
  Framework/PythonInterface/plugins/algorithms/MaskBTP.py
  docs/source/release/v4.3.0/sans.rst
Labels: SANS

#27433 Move unscripted testing from user-docs to dev-docs
  dev-docs/source/Testing/Engineering Diffraction Test Guide.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon Analysis Unscripted Testing Guide.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_Analysis_test_group_1_general.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_Analysis_test_group_2_fitting.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_Analysis_test_group_3_results.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_Analysis_test_group_4_FDAG.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_Analysis_test_group_5_MA2.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/index.rst
  dev-docs/source/Testing/index.rst
  dev-docs/source/images/EngineeringDiffractionTest/EnggDiffExampleFitOutput.png
  dev-docs/source/images/EngineeringDiffractionTest/EnggDiffExampleFocusOutput.png
  dev-docs/source/images/EngineeringDiffractionTest/EnggDiffExampleGSASOutput.png
  dev-docs/source/images/EngineeringDiffractionTest/EnggDiffExpectedLinear.png
  dev-docs/source/images/EngineeringDiffractionTest/EnggDiffExpectedVanCurve.png
  dev-docs/source/images/MuonAnalysisTests/emu20918.png
  dev-docs/source/images/MuonAnalysisTests/emu20918_rebin.png
  dev-docs/source/images/MuonAnalysisTests/fitting_test1.png
  dev-docs/source/images/MuonAnalysisTests/multiperiod-before.png
  dev-docs/source/images/MuonAnalysisTests/multiperiod.png
  dev-docs/source/images/MuonAnalysisTests/results_test1.png
  dev-docs/source/images/MuonAnalysisTests/results_test6.png
  dev-docs/source/images/MuonAnalysisTests/results_tests2and3.png
  dev-docs/source/images/MuonAnalysisTests/results_tests4and5.png
  docs/source/interfaces/Muon Analysis Developers Guide.rst
  docs/source/interfaces/index.rst
Labels: Documentation, Maintenance

#27480 Small fix in JSONGeometryParser
  Framework/NexusGeometry/src/JSONGeometryParser.cpp
Labels: Live Data

#27479 Expose adding weighted events from python
  Framework/PythonInterface/mantid/dataobjects/src/Exports/EventList.cpp
  Framework/PythonInterface/test/python/mantid/dataobjects/EventListTest.py
Labels: Easy, Framework, Low Priority

#27412 Add documentation for polynomial fit function
  docs/source/fitting/fitfunctions/Polynomial.rst
Labels: Documentation, Fitting, Maintenance

#27496 Remov canWrite checks in FileValidator
  Framework/API/src/FileProperty.cpp
  Framework/DataHandling/src/SaveNexusProcessed.cpp
  Framework/Kernel/inc/MantidKernel/FileValidator.h
  Framework/Kernel/src/FileValidator.cpp
  Framework/Kernel/test/FileValidatorTest.h
  Framework/Nexus/inc/MantidNexus/NexusFileIO.h
  Framework/Nexus/src/NexusFileIO.cpp
Labels: Bug, Framework

#27456 Set minimum required standard to C++17
  Framework/API/src/FileFinder.cpp
  Framework/Algorithms/src/CreateGroupingWorkspace.cpp
  Framework/Algorithms/src/Integration.cpp
  Framework/Algorithms/src/RebinByTimeBase.cpp
  Framework/Beamline/inc/MantidBeamline/ComponentInfo.h
  Framework/Beamline/inc/MantidBeamline/DetectorInfo.h
  Framework/Beamline/src/ComponentInfo.cpp
  Framework/Beamline/src/DetectorInfo.cpp
  Framework/Beamline/test/ComponentInfoTest.h
  Framework/Crystal/src/AnvredCorrection.cpp
  Framework/Crystal/src/SaveHKL.cpp
  Framework/Crystal/src/SaveLauenorm.cpp
  Framework/Crystal/test/FindSXPeaksHelperTest.h
  Framework/CurveFitting/src/Algorithms/LeBailFit.cpp
  Framework/DataHandling/src/LoadPSIMuonBin.cpp
  Framework/DataObjects/src/EventList.cpp
  Framework/DataObjects/src/PeaksWorkspace.cpp
  Framework/DataObjects/test/EventListTest.h
  Framework/DataObjects/test/Histogram1DTest.h
  Framework/Geometry/inc/MantidGeometry/Math/MapSupport.h
  Framework/Geometry/src/MDGeometry/MDGeometryXMLParser.cpp
  Framework/Geometry/src/Math/Acomp.cpp
  Framework/Geometry/src/Objects/CSGObject.cpp
  Framework/Kernel/inc/MantidKernel/LogFilter.h
  Framework/Kernel/inc/MantidKernel/MultiThreaded.h
  Framework/Kernel/inc/MantidKernel/VectorHelper.h
  Framework/Kernel/inc/MantidKernel/WarningSuppressions.h
  Framework/Kernel/test/ThreadPoolRunnableTest.h
  Framework/MDAlgorithms/src/CreateMDHistoWorkspace.cpp
  Framework/MDAlgorithms/src/ImportMDHistoWorkspaceBase.cpp
  Framework/MDAlgorithms/src/MaskMD.cpp
  Framework/MPIAlgorithms/src/GatherWorkspaces.cpp
  buildconfig/CMake/Bootstrap.cmake
  buildconfig/CMake/CommonSetup.cmake
  buildconfig/CMake/MSVCSetup.cmake
  buildconfig/CMake/WindowsNSIS.cmake
  qt/paraview_ext/VatesAPI/inc/MantidVatesAPI/FieldDataToMetadata.h
  qt/paraview_ext/VatesAPI/inc/MantidVatesAPI/TimeStepToTimeStep.h
  qt/paraview_ext/VatesAPI/inc/MantidVatesAPI/TimeToTimeStep.h
  qt/paraview_ext/VatesAPI/src/TimeToTimeStep.cpp
  qt/scientific_interfaces/Indirect/IndirectFunctionBrowser/IqtFunctionModel.cpp
  qt/widgets/common/src/FitPropertyBrowser.cpp
  qt/widgets/plotting/inc/MantidQtWidgets/Plotting/Qwt/SafeQwtPlot.h
  qt/widgets/sliceviewer/src/CompositePeaksPresenter.cpp
Labels: Maintenance

#27481 Add a CMake option to disable OpenGL
  Framework/Geometry/CMakeLists.txt
  Framework/Geometry/inc/MantidGeometry/Rendering/RenderingHelpers.h
  Framework/Geometry/src/Rendering/RenderingHelpersOpenGL.cpp
  Framework/Geometry/src/Rendering/RenderingHelpersThrowing.cpp
  buildconfig/CMake/CommonSetup.cmake
  qt/widgets/instrumentview/CMakeLists.txt
Labels: ISIS Team: Diffraction, Maintenance

#27211 Update sans testing docs
  dev-docs/source/ISISSANSReductionBackend.rst
  dev-docs/source/Testing/SANSGUI/SANSGUITests.rst
Labels: Documentation, Maintenance

#27511 LoadNGEM: Convert tof to double when converting to microseconds
  Framework/DataHandling/inc/MantidDataHandling/LoadNGEM.h
  Framework/DataHandling/src/LoadNGEM.cpp
  Framework/DataHandling/test/LoadNGEMTest.h
  docs/source/release/v4.3.0/framework.rst
Labels: Bug, ISIS Team: Diffraction

#27503 Reading Registered Colormaps Function change
  qt/python/mantidqt/widgets/plotconfigdialog/imagestabwidget/view.py
Labels: Bug, Python

#27514 Fix crash when using figure options in 2d plots
  docs/source/release/v4.3.0/mantidworkbench.rst
  qt/python/mantidqt/widgets/plotconfigdialog/imagestabwidget/presenter.py
Labels: Added during Sprint, Bug, ISIS Team: CoreTeam

#27229 Fix problem with PyCharm.bat on Windows
  buildconfig/windows/pycharm.bat.in
Labels: Windows Only

#27250 ISIS interfaces set default facility
  qt/scientific_interfaces/ISISReflectometry/GUI/MainWindow/MainWindowPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/MainWindow/MainWindowPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/RunsTable/QtRunsTableView.cpp
  qt/scientific_interfaces/test/ISISReflectometry/MainWindow/MainWindowPresenterTest.h
  scripts/SANS/sans/common/enums.py
  scripts/SANS/sans/gui_logic/presenter/run_tab_presenter.py
  scripts/test/SANS/gui_logic/run_tab_presenter_test.py
Labels: ISIS Team: LSS, MantidPlot, Reflectometry, SANS, Workbench
