Repository mantidproject/mantid, pull requests merged in 2021-12, with the labels that each got.

#33066 Fix linux pre commit
  .pre-commit-config.yaml
  Framework/Algorithms/test/PDFFourierTransform2Test.h
  docs/source/tutorials/mantid_basic_course/connecting_data_to_instruments/01_introduction.rst
  docs/source/tutorials/mantid_basic_course/connecting_data_to_instruments/02_displaying_and_navigating.rst
  docs/source/tutorials/mantid_basic_course/connecting_data_to_instruments/03_investigating_data.rst
  docs/source/tutorials/mantid_basic_course/connecting_data_to_instruments/04_masking_and_grouping.rst
  docs/source/tutorials/mantid_basic_course/connecting_data_to_instruments/05_instrument_tree.rst
  docs/source/tutorials/mantid_basic_course/connecting_data_to_instruments/06_sample_logs.rst
  docs/source/tutorials/mantid_basic_course/connecting_data_to_instruments/08_exercises_c.rst
  docs/source/tutorials/mantid_basic_course/connecting_data_to_instruments/index.rst
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/BankRenderingHelpers.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/BankTextureBuilder.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/BaseCustomInstrumentMocks.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/BinDialog.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/GLColor.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/InstrumentRenderer.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/InstrumentWidgetRenderTab.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/InstrumentWidgetTab.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/InstrumentWidgetTreeTab.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/MiniPlotQwt.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/PanelsSurface.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/PeakOverlay.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/RectF.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/UnwrappedDetector.h
  qt/widgets/instrumentview/src/MiniPlotQwt.cpp
  qt/widgets/instrumentview/test/InstrumentWidgetEncoderTest.h
  scripts/abins/instruments/__init__.py
Labels: High Priority, Bug, Linux Only

#33010 Remove predefined size for seq fit button
  docs/source/release/v6.3.0/muon.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/seq_fitting_tab_widget/seq_fitting_tab.ui
Labels: Muon, GUI, ISIS Team: Spectroscopy

#33026 fix muon plot bug with shade region
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/plot_widget/plotting_canvas/plotting_canvas_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/plot_widget/plotting_canvas/plotting_canvas_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/plot_widget/plotting_canvas/plotting_canvas_view.py
  qt/python/mantidqtinterfaces/test/Muon/plotting_canvas/plotting_canvas_presenter_test.py
  qt/python/mantidqtinterfaces/test/Muon/plotting_canvas/plotting_canvas_view_test.py
Labels: ISIS Team: Spectroscopy

#32823 Refactor enginx script to call UI code
  Framework/Algorithms/inc/MantidAlgorithms/PDCalibration.h
  Framework/Algorithms/src/PDCalibration.cpp
  Testing/SystemTests/tests/framework/EnginXScriptTest.py
  Testing/SystemTests/tests/framework/reference/299080_engggui_focusing_output_ws_Texture.nxs.md5
  Testing/SystemTests/tests/framework/reference/299080_engggui_focusing_output_ws_bank.nxs.md5
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/algorithms/EnggCalibrate-v1.rst
  docs/source/concepts/calibration/PowderDiffractionCalibration.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/calibration/model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/focus/model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/focus/test/test_focus_model.py
  scripts/Engineering/EnggUtils.py
  scripts/Engineering/EnginX.py
  scripts/Engineering/template_ENGINX_241391_North_and_South_banks.prm
  scripts/Engineering/template_ENGINX_241391_North_bank.prm
  scripts/Engineering/template_ENGINX_241391_South_bank.prm
  scripts/Engineering/template_ENGINX_241391_Texture.prm
Labels: Diffraction, ISIS Team: Diffraction

#32910 LoadAndMerge fix for ignored loader version
  Framework/PythonInterface/plugins/algorithms/LoadAndMerge.py
  docs/source/release/v6.3.0/framework.rst
Labels: Bug, ILL Team

#33097 CppCheck nullptrs IPropertyManager from DevWS
  Framework/Kernel/inc/MantidKernel/IPropertyManager.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance

#33106 Update Windows system test file for PowderReduceP2DTest
  Testing/Data/SystemTest/PowderReduceP2D_reference_msvc.p2d.md5
  Testing/SystemTests/tests/framework/PowderReduceP2DTest.py
Labels: High Priority, Windows Only

#33107 Fix detector shape created by LoadNXSPE
  Framework/DataHandling/inc/MantidDataHandling/LoadNXSPE.h
  Framework/DataHandling/src/LoadNXSPE.cpp
  docs/source/release/v6.3.0/direct_geometry.rst
Labels: Direct Inelastic

#32995 VesuvioAnalysis: Allow constraints for more than two masses
  Framework/PythonInterface/plugins/algorithms/VesuvioAnalysis.py
  Framework/PythonInterface/test/python/plugins/algorithms/VesuvioAnalysisTest.py
  docs/source/algorithms/VesuvioAnalysis-v1.rst
  docs/source/release/v6.3.0/indirect_geometry.rst
  scripts/Inelastic/vesuvio/analysisHelpers.py
Labels: ISIS Team: Excitations/Vesuvio

#33062 Add details on delta_r in TOML docs
  docs/source/techniques/SANS-Toml-v1.rst
Labels: SANS, Documentation, ISIS Team: LSS

#33011 Make muon GUI's show doubles in a nicer format
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/corrections_tab_widget/background_corrections_view.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/seq_fitting_tab_widget/QSequentialTableModel.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/seq_fitting_tab_widget/QSequentialTableView.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/utilities/table_utils.py
Labels: ISIS Team: Spectroscopy

#33113 Update Windows conda getting started instructions
  dev-docs/source/GettingStarted/GettingStartedCondaWindows.rst
Labels: Documentation, ISIS Team: Core

#33000 Fix crash in DiscusMultipleScatteringCorrection
  Framework/Algorithms/src/DiscusMultipleScatteringCorrection.cpp
  Framework/Algorithms/test/DiscusMultipleScatteringCorrectionTest.h
  docs/source/release/v6.3.0/framework.rst
Labels: ISIS Team: Diffraction

#33068 Save files multiple directories eng diff UI
  dev-docs/source/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.rst
  docs/source/interfaces/diffraction/Engineering Diffraction.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/calibration/model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/calibration/test/test_calib_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/focus/model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/focus/test/test_focus_model.py
Labels: Diffraction, ISIS Team: Diffraction

#33025 Critial Peak of Relexation Rate fitting function
  Framework/CurveFitting/CMakeLists.txt
  Framework/CurveFitting/inc/MantidCurveFitting/Functions/CriticalPeakRelaxationRate.h
  Framework/CurveFitting/src/Functions/CriticalPeakRelaxationRate.cpp
  Framework/CurveFitting/test/Functions/CriticalPeakRelaxationRateTest.h
  docs/source/fitting/fitfunctions/CriticalPeakRelaxationRate.rst
  docs/source/release/v6.3.0/muon.rst
Labels: Muon, ISIS Team: Spectroscopy

#33084 fix muon plot offset bug
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/contexts/plot_settings_context.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/plot_widget/plotting_canvas/plotting_canvas_view.py
Labels: ISIS Team: Spectroscopy

#33105 Cppcheck - Ignore build dir in invocation
  Framework/Kernel/inc/MantidKernel/Strings.h
  buildconfig/CMake/CppCheckSetup.cmake
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance

#33028 Bump Eigen to 3.4.0
  CMakeLists.txt
  buildconfig/CMake/Eigen.cmake
  buildconfig/CMake/Eigen.in
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: Maintenance, Framework

#33103 Save Indirect contour ws in Bayes Stretch
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.3.0/indirect_geometry.rst
  qt/scientific_interfaces/Indirect/Stretch.cpp
Labels: Bug, Indirect Inelastic, Maintenance, ISIS Team: Spectroscopy

#33059 Add relative error to PeaksWorkspaces in CompareWorkspaces
  Framework/Algorithms/src/CompareWorkspaces.cpp
  Framework/Algorithms/test/CompareWorkspacesTest.h
  docs/source/release/v6.3.0/framework.rst
Labels: Bug, ISIS Team: Core, Added during Sprint

#33005 Muon undo fit resets correctly
  docs/source/release/v6.3.0/muon.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_presenter.py
  qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_presenter_test.py
Labels: ISIS Team: Spectroscopy, Reported By User

#33085 DecouplingAsymPowderMag Fitting function for Muons
  Framework/CurveFitting/CMakeLists.txt
  Framework/CurveFitting/inc/MantidCurveFitting/Functions/DecoupAsymPowderMagLong.h
  Framework/CurveFitting/inc/MantidCurveFitting/Functions/DecoupAsymPowderMagRot.h
  Framework/CurveFitting/inc/MantidCurveFitting/MuonHelpers.h
  Framework/CurveFitting/src/Functions/DecoupAsymPowderMagLong.cpp
  Framework/CurveFitting/src/Functions/DecoupAsymPowderMagRot.cpp
  Framework/CurveFitting/src/MuonHelpers.cpp
  Framework/CurveFitting/test/Functions/DecoupAsymPowderMagLongTest.h
  Framework/CurveFitting/test/Functions/DecoupAsymPowderMagRotTest.h
  Framework/CurveFitting/test/MuonHelperTest.h
  docs/source/fitting/fitfunctions/DecoupAsymPowderMagLong.rst
  docs/source/fitting/fitfunctions/DecoupAsymPowderMagRot.rst
  docs/source/release/v6.3.0/muon.rst
Labels: Muon, ISIS Team: Spectroscopy

#33112 Remove instructions for cmake-format
  dev-docs/source/ToolsOverview.rst
Labels: Documentation

#33096 Add instructions to install conda behind ILL proxy
  dev-docs/source/GettingStarted/GettingStartedCondaLinux.rst
Labels: Documentation, ILL Team

#33093 Scale large intensities (and errors) in save reflections so doesn't overflow into previous column
  Framework/PythonInterface/plugins/algorithms/SaveReflections.py
  Framework/PythonInterface/test/python/plugins/algorithms/SaveReflectionsTest.py
  docs/source/release/v6.3.0/diffraction.rst
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction, Added during Sprint

#33132 Increase memory requirement of WAND Q conversion tests
  Testing/SystemTests/tests/framework/ConvertWANDSCDtoQTest.py
Labels: High Priority, ISIS Team: Core, Added during Sprint

#33119 Select between field and freq in FDA
  docs/source/release/v6.3.0/muon.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/contexts/frequency_domain_analysis_context.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/plot_widget/plotting_canvas/plotting_canvas_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/utilities/algorithm_utils.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/FrequencyDomainAnalysis/FFT/fft_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/FrequencyDomainAnalysis/MaxEnt/maxent_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/FrequencyDomainAnalysis/frequency_context.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/FrequencyDomainAnalysis/frequency_domain_analysis.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/FrequencyDomainAnalysis/plot_widget/dual_plot_maxent_pane/dual_plot_maxent_pane_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/FrequencyDomainAnalysis/plot_widget/frequency_analysis_plot_widget.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/FrequencyDomainAnalysis/plot_widget/plot_freq_fit_pane_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/FrequencyDomainAnalysis/plot_widget/plot_freq_fit_pane_presenter.py
  qt/python/mantidqtinterfaces/test/Muon/CMakeLists.txt
  qt/python/mantidqtinterfaces/test/Muon/dual_plot_maxent_pane/dual_plot_maxent_pane_presenter_test.py
  qt/python/mantidqtinterfaces/test/Muon/fft_presenter_context_interaction_test.py
  qt/python/mantidqtinterfaces/test/Muon/frequency_domain_context_test.py
  qt/python/mantidqtinterfaces/test/Muon/plot_fit_panes/plot_freq_fit_pane_model_test.py
  qt/python/mantidqtinterfaces/test/Muon/plot_fit_panes/plot_freq_fit_pane_presenter_test.py
  qt/python/mantidqtinterfaces/test/Muon/plot_widget/frequency_analysis_plot_widget_test.py
Labels: ISIS Team: Spectroscopy

#33133 Added a dev doc for mockups with Balsamiq
  dev-docs/source/BalsamiqWireframes.rst
  dev-docs/source/images/balsamiq_cloud.png
  dev-docs/source/images/balsamiq_new_project.png
  dev-docs/source/images/balsamiq_ui.png
  dev-docs/source/index.rst
Labels: Documentation, Maintenance

#33092 Enable other focussing modes for tt_mode=custom in PEARL powder diff scripts
  Testing/Data/SystemTest/ISIS_Powder/input/PEARL00098472_splined.nxs.md5
  Testing/Data/SystemTest/ISIS_Powder/input/calibration/pearl/DAC_group.cal.md5
  Testing/SystemTests/tests/framework/ISIS_PowderPearlTest.py
  Testing/SystemTests/tests/framework/reference/ISIS_Powder-PEARL00098507_tt70Atten.nxs.md5
  Testing/SystemTests/tests/framework/reference/ISIS_Powder-PEARL00098507_tt70NoEmptySub.nxs.md5
  docs/source/release/v6.3.0/diffraction.rst
  scripts/Diffraction/isis_powder/pearl.py
  scripts/Diffraction/isis_powder/pearl_routines/pearl_algs.py
  scripts/Diffraction/isis_powder/pearl_routines/pearl_output.py
  scripts/Diffraction/isis_powder/routines/run_details.py
Labels: ISIS Team: Diffraction

#33128 Updated documentation for CEF for two step fitting
  docs/source/interfaces/direct/Crystal Field Python Interface.rst
Labels: Documentation, ISIS Team: Excitations/Vesuvio

#33138 ensure monospace fonts in python editor and ipython
  docs/source/release/v6.3.0/mantidworkbench.rst
  qt/applications/workbench/workbench/app/mainwindow.py
  qt/applications/workbench/workbench/config/fonts.py
Labels: GUI

#33115 added fit wizard to muon feature flags
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/features/add_fitting.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_tab_widget/fitting_tab_widget.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/fit_controls_view.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/FrequencyDomainAnalysis/frequency_domain_analysis.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/MuonAnalysis/muon_analysis_2.py
  qt/python/mantidqtinterfaces/test/Muon/CMakeLists.txt
  qt/python/mantidqtinterfaces/test/Muon/feature_flags/add_fitting_test.py
Labels: ISIS Team: Spectroscopy

#33108 Extend guess range outside of data range in Muon analysis
  docs/source/release/v6.3.0/muon.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/contexts/fitting_contexts/basic_fitting_context.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/fit_function_options_view.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/utilities/algorithm_utils.py
  qt/python/mantidqtinterfaces/test/Muon/basic_fitting_context_test.py
  qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_model_test.py
  qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_presenter_test.py
  qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py
Labels: Muon, ISIS Team: Spectroscopy

#33100 More detailed profiling
  Framework/API/inc/MantidAPI/AlgoTimeRegister.h
  Framework/API/inc/MantidAPI/Algorithm.h
  Framework/API/src/AlgoTimeRegister.cpp
  Framework/API/src/AlgorithmExecute.cpp
  Framework/API/src/AlgorithmExecuteProfile.cpp
  Framework/Algorithms/src/FilterEvents.cpp
  Framework/Kernel/inc/MantidKernel/Timer.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  dev-docs/source/AlgorithmProfiler.rst
Labels: Has Conflicts

#33134 Migrate to GCC 10.3 in conda
  mantid-developer-linux.yml
  qt/widgets/common/src/QtPropertyBrowser/qttreepropertybrowser.cpp
Labels: High Priority, ISIS Team: Core, Linux Only

#33130 Split Activation Fit function into two seperate functions
  Framework/CurveFitting/CMakeLists.txt
  Framework/CurveFitting/inc/MantidCurveFitting/Functions/ActivationK.h
  Framework/CurveFitting/inc/MantidCurveFitting/Functions/ActivationmeV.h
  Framework/CurveFitting/inc/MantidCurveFitting/MuonHelpers.h
  Framework/CurveFitting/src/Functions/Activation.cpp
  Framework/CurveFitting/src/Functions/ActivationK.cpp
  Framework/CurveFitting/src/Functions/ActivationmeV.cpp
  Framework/CurveFitting/src/MuonHelpers.cpp
  Framework/CurveFitting/test/Functions/ActivationKTest.h
  Framework/CurveFitting/test/Functions/ActivationTest.h
  Framework/CurveFitting/test/Functions/ActivationmeVTest.h
  Framework/CurveFitting/test/MuonHelperTest.h
  docs/source/fitting/fitfunctions/ActivationK.rst
  docs/source/fitting/fitfunctions/ActivationmeV.rst
  docs/source/release/v6.3.0/muon.rst
Labels: Muon, ISIS Team: Spectroscopy

#33116 Fix bug in SparseWorkspace feature
  Framework/Algorithms/src/DiscusMultipleScatteringCorrection.cpp
  Framework/Algorithms/src/MonteCarloAbsorption.cpp
  Framework/Algorithms/src/SampleCorrections/SparseWorkspace.cpp
  Framework/Algorithms/test/MonteCarloAbsorptionTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.3.0/framework.rst
Labels: ISIS Team: Diffraction, Absorption Corrections

#33149 Fix scaling of waterfall plots on open
  Framework/PythonInterface/mantid/plots/plotfunctions.py
  docs/source/release/v6.3.0/mantidworkbench.rst
Labels: Bug, ISIS Team: Core, Found in Beta

#32070 CrystalField dual fitting
  docs/source/release/v6.3.0/direct_geometry.rst
  scripts/Inelastic/CrystalField/CrystalFieldMultiSite.py
  scripts/Inelastic/CrystalField/fitting.py
  scripts/Inelastic/CrystalField/normalisation.py
  scripts/test/CrystalFieldMultiSiteTest.py
  scripts/test/CrystalFieldTest.py
Labels: ISIS Team: Excitations/Vesuvio

#33131 improve design document guildelines doc
  dev-docs/source/DesignDocumentGuides.rst
  dev-docs/source/index.rst
Labels: Documentation

#33153 Bug fix to get correct x values in SaveNexus when spec indices
  Framework/DataHandling/test/SaveNexusProcessedTest.h
  Framework/Nexus/inc/MantidNexus/NexusFileIO.h
  Framework/Nexus/src/NexusFileIO.cpp
  docs/source/release/v6.3.0/framework.rst
Labels: ISIS Team: Core

#33168 Updated release note and SHA for MSlice
  docs/source/release/v6.3.0/direct_geometry.rst
  scripts/ExternalInterfaces/CMakeLists.txt
Labels: ISIS Team: Excitations/Vesuvio
