Repository mantidproject/mantid, pull requests merged in 2021-06, with the labels that each got.

#31659 Update CatalogLogin-v1.rst
  docs/source/algorithms/CatalogLogin-v1.rst
Labels: Documentation

#31663 Project Save: Plots should dynamically fill tick properties based on if values are present
  qt/python/mantidqt/project/plotssaver.py
Labels: High Priority, ISIS Team: Core

#31282 Add ability to add and remove peaks from SliceViewer
  Framework/PythonInterface/mantid/api/src/Exports/IPeaksWorkspace.cpp
  docs/source/concepts/LeanElasticPeaksWorkspace.rst
  docs/source/images/wb-sliceviewer52-peaks-actions.png
  docs/source/images/wb-sliceviewer52-peaksoverlay.png
  docs/source/release/v6.2.0/mantidworkbench.rst
  docs/source/workbench/sliceviewer.rst
  qt/python/CMakeLists.txt
  qt/python/mantidqt/widgets/sliceviewer/doc/classes.puml
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/actions.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/actions.ui
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/model.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/presenter.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/representation/alpha.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/representation/draw.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/representation/ellipsoid.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/representation/noshape.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/representation/painter.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/representation/test/test_peaksviewer_representation_ellipsoid.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/test/modeltesthelpers.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/test/test_peaksviewer_actions.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/test/test_peaksviewer_model.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/test/test_peaksviewer_peaksviewercollectionpresenter.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/test/test_peaksviewer_presenter.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/test/test_peaksviewer_sliceviewer_add_delete_peaks_integration.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/view.py
  qt/python/mantidqt/widgets/sliceviewer/presenter.py
  qt/python/mantidqt/widgets/sliceviewer/sliceinfo.py
  qt/python/mantidqt/widgets/sliceviewer/test/test_sliceviewer_presenter.py
  qt/python/mantidqt/widgets/sliceviewer/test/test_sliceviewer_sliceinfo.py
  qt/python/mantidqt/widgets/sliceviewer/toolbar.py
  qt/python/mantidqt/widgets/sliceviewer/view.py
  qt/python/mantidqt/widgets/workspacedisplay/table/marked_columns.py
  qt/python/mantidqt/widgets/workspacedisplay/table/model.py
Labels: Single Crystal

#31595 Added docs page for MSlice interface
  docs/source/interfaces/direct/MSlice.rst
Labels: Documentation, ISIS Team: Excitations/Vesuvio, Maintenance

#31602 Add missing SANS test back to CMake lists
  scripts/SANS/sans/user_file/toml_parsers/toml_v1_parser.py
  scripts/test/SANS/user_file/CMakeLists.txt
  scripts/test/SANS/user_file/toml_parsers/CMakeLists.txt
  scripts/test/SANS/user_file/toml_parsers/parser_helpers/CMakeLists.txt
  scripts/test/SANS/user_file/toml_parsers/parser_helpers/wavelength_parser_test.py
  scripts/test/SANS/user_file/toml_parsers/toml_v1_parser_test.py
  scripts/test/SANS/user_file/toml_parsers/toml_v1_schema_test.py
Labels: ISIS Team: LSS, Maintenance, SANS

#31591 Add missing unit tests for reflectometry interface Group class
  qt/scientific_interfaces/ISISReflectometry/Reduction/Group.cpp
  qt/scientific_interfaces/ISISReflectometry/Reduction/Group.h
  qt/scientific_interfaces/ISISReflectometry/test/Reduction/GroupTest.h
Labels: ISIS Team: LSS, Maintenance, Reflectometry

#31545 Add missing unit tests for BatchAlgorithmRunner
  qt/widgets/common/test/BatchAlgorithmRunnerTest.h
  qt/widgets/common/test/MockConfiguredAlgorithm.h
Labels: ISIS Team: LSS, Maintenance, Reflectometry

#31676 Memory Widget use main GUI thread fix
  qt/python/mantidqt/widgets/memorywidget/memorypresenter.py
  qt/python/mantidqt/widgets/memorywidget/memoryview.py
  qt/python/mantidqt/widgets/memorywidget/test/test_memorypresenter.py
  qt/python/mantidqt/widgets/memorywidget/test/test_memoryview.py
Labels: High Priority, ISIS Team: Core

#31669 Make minor adjustments to Release Checklist
  dev-docs/source/ReleaseChecklist.rst
Labels: Documentation

#31537 Add Splitter on Muon GUIs plotting canvas
  docs/source/release/v6.2.0/muon.rst
  scripts/Muon/GUI/Common/plot_widget/plotting_canvas/plotting_canvas_view.py
Labels: ISIS Team: Spectroscopy, Muon, Reported By User

#31668 Set QT layer for Error Reporter on BigSur
  qt/applications/workbench/workbench/app/start.py
  qt/python/mantidqt/dialogs/errorreports/main.py
  qt/python/mantidqt/utils/qt/__init__.py
Labels: High Priority, ISIS Team: Core

#31693 Fix ConvertToDiffractionMDWorkspace for dSpacing workspaces
  Framework/MDAlgorithms/src/PreprocessDetectorsToMD.cpp
Labels: Diffraction, High Priority, Reported By User

#31683 Update sliceviewer testing docs
  dev-docs/source/Testing/SliceViewer/SliceViewer.rst
Labels: ISIS Team: Core

#31677 Minor fixes to plotting docs
  docs/source/images/PlotClickMenusTiled.png
  docs/source/images/PlotToolbarTiledColorfill.png
  docs/source/plotting/1DPlotsHelp.rst
  docs/source/plotting/index.rst
  docs/source/tutorials/mantid_basic_course/loading_and_displaying_data/04_displaying_2D_data.rst
  docs/source/tutorials/python_in_mantid/solutions/02_pim_sol.rst
Labels: Documentation

#31684 Interruption point after sleep
  Framework/LiveData/src/MonitorLiveData.cpp
  Framework/LiveData/test/MonitorLiveDataTest.h
Labels: Framework

#31703 Increase the d-spacing tolerance in AlignComponents validation
  Framework/PythonInterface/plugins/algorithms/AlignComponents.py
Labels: Powder

#31704 Increase the d-spacing tolerance in AlignComponents validation
  Framework/PythonInterface/plugins/algorithms/AlignComponents.py
Labels: Powder

#31711 Renamed all files and tests to IndirectFitDataTablePresenter
  qt/scientific_interfaces/Indirect/CMakeLists.txt
  qt/scientific_interfaces/Indirect/ConvFitDataTablePresenter.cpp
  qt/scientific_interfaces/Indirect/ConvFitDataTablePresenter.h
  qt/scientific_interfaces/Indirect/FqFitDataTablePresenter.cpp
  qt/scientific_interfaces/Indirect/FqFitDataTablePresenter.h
  qt/scientific_interfaces/Indirect/IndirectFitDataPresenter.cpp
  qt/scientific_interfaces/Indirect/IndirectFitDataPresenter.h
  qt/scientific_interfaces/Indirect/IndirectFitDataTablePresenter.cpp
  qt/scientific_interfaces/Indirect/IndirectFitDataTablePresenter.h
  qt/scientific_interfaces/Indirect/test/CMakeLists.txt
  qt/scientific_interfaces/Indirect/test/IndirectFitDataPresenterTest.h
  qt/scientific_interfaces/Indirect/test/IndirectFitDataTablePresenterTest.h
Labels: ISIS Team: Spectroscopy

#31575 Add parseNames to CreateMDHistoWorkspace
  Framework/MDAlgorithms/inc/MantidMDAlgorithms/ImportMDHistoWorkspaceBase.h
  Framework/MDAlgorithms/src/ImportMDHistoWorkspaceBase.cpp
  docs/source/release/v6.2.0/framework.rst
Labels: Framework, Maintenance, Reported By User

#31029 30778 vesuvio parallel
  Framework/CurveFitting/inc/MantidCurveFitting/Algorithms/VesuvioCalculateMS.h
  Framework/CurveFitting/src/Algorithms/VesuvioCalculateMS.cpp
  docs/source/algorithms/VesuvioAnalysis-v1.rst
Labels: ISIS Team: Excitations/Vesuvio

#31561 Add the two IsoRotDiff functions to ConvFit
  docs/source/release/v6.2.0/indirect_geometry.rst
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisConvFitTab.cpp
  qt/scientific_interfaces/Indirect/IndirectFunctionBrowser/ConvFunctionModel.cpp
  qt/scientific_interfaces/Indirect/IndirectFunctionBrowser/ConvFunctionModel.h
  qt/scientific_interfaces/Indirect/IndirectFunctionBrowser/ConvTypes.cpp
  qt/scientific_interfaces/Indirect/IndirectFunctionBrowser/ConvTypes.h
Labels: ISIS Team: Spectroscopy, Indirect Inelastic

#31712 Required initialization of PyStdoutSink
  Framework/PythonInterface/core/src/PythonStdoutChannel.cpp
Labels: Framework, Patch Candidate

#31715 Required initialization of PyStdoutSink
  Framework/PythonInterface/core/src/PythonStdoutChannel.cpp
Labels: Framework

#31608 InelasticScatteredTransmissionCorrectionMD algorithm
  Framework/Algorithms/inc/MantidAlgorithms/CreateSampleWorkspace.h
  Framework/Algorithms/src/CreateSampleWorkspace.cpp
  Framework/Algorithms/test/CreateSampleWorkspaceTest.h
  Framework/Kernel/inc/MantidKernel/IValidator.h
  Framework/MDAlgorithms/CMakeLists.txt
  Framework/MDAlgorithms/inc/MantidMDAlgorithms/DgsScatteredTransmissionCorrectionMD.h
  Framework/MDAlgorithms/src/DgsScatteredTransmissionCorrectionMD.cpp
  Framework/MDAlgorithms/test/DgsScatteredTransmissionCorrectionMDTest.h
  docs/source/algorithms/DgsScatteredTransmissionCorrectionMD-v1.rst
  docs/source/algorithms/RecordPythonScript-v1.rst
  docs/source/release/v6.2.0/direct_geometry.rst
  docs/source/release/v6.2.0/framework.rst
Labels: ORNL Team

#31609 Deprecate RemoteAlgorithms suite
  Framework/RemoteAlgorithms/CMakeLists.txt
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/AbortRemoteJob.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/AbortRemoteJob2.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/Authenticate.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/Authenticate2.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/DownloadRemoteFile.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/DownloadRemoteFile2.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/Logout2.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/QueryAllRemoteJobs.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/QueryAllRemoteJobs2.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/QueryRemoteFile.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/QueryRemoteFile2.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/QueryRemoteJob.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/QueryRemoteJob2.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/StartRemoteTransaction.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/StartRemoteTransaction2.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/StopRemoteTransaction.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/StopRemoteTransaction2.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/SubmitRemoteJob.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/SubmitRemoteJob2.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/UploadRemoteFile.h
  Framework/RemoteAlgorithms/inc/MantidRemoteAlgorithms/UploadRemoteFile2.h
  Framework/RemoteAlgorithms/src/AbortRemoteJob.cpp
  Framework/RemoteAlgorithms/src/Authenticate.cpp
  Framework/RemoteAlgorithms/src/DownloadRemoteFile.cpp
  Framework/RemoteAlgorithms/src/QueryAllRemoteJobs.cpp
  Framework/RemoteAlgorithms/src/QueryRemoteFile.cpp
  Framework/RemoteAlgorithms/src/QueryRemoteJob.cpp
  Framework/RemoteAlgorithms/src/StartRemoteTransaction.cpp
  Framework/RemoteAlgorithms/src/StopRemoteTransaction.cpp
  Framework/RemoteAlgorithms/src/SubmitRemoteJob.cpp
  Framework/RemoteAlgorithms/src/UploadRemoteFile.cpp
  Framework/RemoteAlgorithms/test/AbortRemoteJobTest.h
  Framework/RemoteAlgorithms/test/AuthenticateTest.h
  Framework/RemoteAlgorithms/test/DownloadRemoteFileTest.h
  Framework/RemoteAlgorithms/test/QueryAllRemoteJobsTest.h
  Framework/RemoteAlgorithms/test/QueryRemoteFileTest.h
  Framework/RemoteAlgorithms/test/QueryRemoteJobTest.h
  Framework/RemoteAlgorithms/test/StartRemoteTransactionTest.h
  Framework/RemoteAlgorithms/test/StopRemoteTransactionTest.h
  Framework/RemoteAlgorithms/test/SubmitRemoteJobTest.h
  Framework/RemoteAlgorithms/test/UploadRemoteFileTest.h
  docs/source/release/v6.2.0/framework.rst
Labels: Maintenance

#29662 Refactor algorithms with simple api
  Framework/PythonInterface/plugins/algorithms/EnggFitPeaks.py
  Framework/PythonInterface/plugins/algorithms/EnggFitTOFFromPeaks.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/__pycache__/SANSReductionCorePreprocess.cpython-38.pyc.2098917564464
Labels: ISIS Team: Core, Maintenance

#31564 Update External Links To Internal Links In Docs
  dev-docs/source/Testing/ErrorReporter-ProjectRecovery/ProjectRecoveryTesting.rst
  dev-docs/source/WritingAnAlgorithm.rst
  dev-docs/source/WritingCustomConvertToMDTransformation.rst
  docs/source/algorithms/AbortRemoteJob-v1.rst
  docs/source/algorithms/AbortRemoteJob-v2.rst
  docs/source/algorithms/ApplyTransmissionCorrection-v1.rst
  docs/source/algorithms/Authenticate-v1.rst
  docs/source/algorithms/Authenticate-v2.rst
  docs/source/algorithms/CalculateTransmissionBeamSpreader-v1.rst
  docs/source/algorithms/ConvertUnits-v1.rst
  docs/source/algorithms/CreateEmptyTableWorkspace-v1.rst
  docs/source/algorithms/DownloadRemoteFile-v1.rst
  docs/source/algorithms/DownloadRemoteFile-v2.rst
  docs/source/algorithms/FindClusterFaces-v1.rst
  docs/source/algorithms/FindDetectorsInShape-v1.rst
  docs/source/algorithms/LoadVesuvio-v1.rst
  docs/source/algorithms/Q1D-v2.rst
  docs/source/algorithms/Q1DWeighted-v1.rst
  docs/source/algorithms/QueryAllRemoteJobs-v1.rst
  docs/source/algorithms/QueryAllRemoteJobs-v2.rst
  docs/source/algorithms/QueryRemoteFile-v1.rst
  docs/source/algorithms/QueryRemoteFile-v2.rst
  docs/source/algorithms/QueryRemoteJob-v1.rst
  docs/source/algorithms/QueryRemoteJob-v2.rst
  docs/source/algorithms/SANSWideAngleCorrection-v1.rst
  docs/source/algorithms/SaveCanSAS1D-v1.rst
  docs/source/algorithms/SaveCanSAS1D-v2.rst
  docs/source/algorithms/SaveNXSPE-v1.rst
  docs/source/algorithms/SplineSmoothing-v1.rst
  docs/source/algorithms/StartRemoteTransaction-v1.rst
  docs/source/algorithms/StartRemoteTransaction-v2.rst
  docs/source/algorithms/StopRemoteTransaction-v1.rst
  docs/source/algorithms/StopRemoteTransaction-v2.rst
  docs/source/algorithms/SubmitRemoteJob-v1.rst
  docs/source/algorithms/SubmitRemoteJob-v2.rst
  docs/source/algorithms/SumEventsByLogValue-v1.rst
  docs/source/algorithms/UpdateScriptRepository-v1.rst
  docs/source/algorithms/UploadRemoteFile-v1.rst
  docs/source/algorithms/UploadRemoteFile-v2.rst
  docs/source/api/python/index.rst
  docs/source/api/python/mantid/api/IMDHistoWorkspace.rst
  docs/source/api/python/mantid/api/ITableWorkspace.rst
  docs/source/api/python/mantid/api/ScriptRepository.rst
  docs/source/concepts/Algorithm.rst
  docs/source/concepts/LETSampleIDF.rst
  docs/source/concepts/MatrixWorkspace.rst
  docs/source/concepts/Properties.rst
  docs/source/concepts/SANS2DSampleIDF.rst
  docs/source/concepts/WorkingWithWorspaces.rst
  docs/source/concepts/calibration/VisualizationofCalibratedTubes.rst
  docs/source/release/v3.10.0/sans.rst
  docs/source/release/v3.12.0/direct_inelastic.rst
  docs/source/release/v3.7.1/framework.rst
  docs/source/release/v5.1.0/mantidplot.rst
  docs/source/techniques/Calibration.rst
  docs/source/techniques/ISISPowder-Index-v1.rst
  docs/source/tutorials/introduction_to_python/using_modules.rst
  docs/source/tutorials/mantid_basic_course/useful/03_user_support.rst
  docs/source/workbench/scriptwindow.rst
Labels: Documentation, Maintenance

#31600 Correctly populate ties when loading function from string in fitbrowser
  Framework/API/inc/MantidAPI/CompositeFunction.h
  qt/python/mantidqt/_common.sip
  qt/python/mantidqt/widgets/test/test_fitpropertybrowser.py
  qt/python/mantidqt/widgets/test/test_fitpropertybrowserbase.py
  qt/widgets/common/inc/MantidQtWidgets/Common/PropertyHandler.h
  qt/widgets/common/src/FitPropertyBrowser.cpp
  qt/widgets/common/src/PropertyHandler.cpp
Labels: ISIS Team: Core

#31743 InelasticScatteredTransmissionCorrectionMD algorithm
  Framework/Algorithms/inc/MantidAlgorithms/CreateSampleWorkspace.h
  Framework/Algorithms/src/CreateSampleWorkspace.cpp
  Framework/Algorithms/test/CreateSampleWorkspaceTest.h
  Framework/Kernel/inc/MantidKernel/IValidator.h
  Framework/MDAlgorithms/CMakeLists.txt
  Framework/MDAlgorithms/inc/MantidMDAlgorithms/DgsScatteredTransmissionCorrectionMD.h
  Framework/MDAlgorithms/src/DgsScatteredTransmissionCorrectionMD.cpp
  Framework/MDAlgorithms/test/DgsScatteredTransmissionCorrectionMDTest.h
  docs/source/algorithms/DgsScatteredTransmissionCorrectionMD-v1.rst
  docs/source/algorithms/RecordPythonScript-v1.rst
  docs/source/release/v6.2.0/direct_geometry.rst
Labels: Direct Inelastic, ORNL Team

#31540 Mock view in home_runinfo_presenter_test
  scripts/test/Muon/home_runinfo_presenter_test.py
Labels: ISIS Team: Core, Maintenance, Muon

#31751 Code editor close tab icon, forced to material design
  docs/source/release/v6.2.0/mantidworkbench.rst
  qt/python/mantidqt/widgets/codeeditor/multifileinterpreter.py
  qt/python/mantidqt/widgets/codeeditor/tab_widget/codeeditor_tab_view.py
Labels: ISIS Team: Core

#31535 Remove qt4 sans
  scripts/SANS/ISISCommandInterface.py
  scripts/SANS/SANSBatchMode.py
  scripts/SANS/isis_instrument.py
  scripts/SANS/isis_reducer.py
  scripts/SANS/sans/algorithm_detail/beamcentrefinder_plotting.py
  scripts/SANS/sans/command_interface/ISISCommandInterface.py
  scripts/SANS/sans/gui_logic/presenter/masking_table_presenter.py
  scripts/SANS/sans/gui_logic/presenter/run_tab_presenter.py
Labels: ISIS Team: LSS, Maintenance, SANS

#31587 Fix Race Condition in test_interpreter
  qt/python/mantidqt/utils/asynchronous.py
  qt/python/mantidqt/widgets/codeeditor/test/test_interpreter.py
Labels: Bug, ISIS Team: Core

#31469 PythonInterfacesStartupTest - close event to unsubscribe from the ADS
  Testing/SystemTests/tests/qt/PythonInterfacesStartupTest.py
Labels: ISIS Team: Core, Maintenance

#31512 About dialog scrollable if screen too small
  docs/source/release/v6.2.0/mantidworkbench.rst
  qt/applications/workbench/workbench/widgets/about/presenter.py
  qt/applications/workbench/workbench/widgets/about/test/test_about_presenter.py
  qt/applications/workbench/workbench/widgets/about/view.py
Labels: Bug, ISIS Team: Core, Reported By User

#31758 Increase memory requirement to try and address Jenkins hang
  Testing/SystemTests/tests/framework/ISIS_WISHSingleCrystalReduction.py
Labels: Diffraction, ISIS Team: Diffraction, Single Crystal

#31761 Re-add Coverage Tooling
  CMakeLists.txt
  Framework/API/CMakeLists.txt
  Framework/Algorithms/CMakeLists.txt
  Framework/Beamline/CMakeLists.txt
  Framework/Catalog/CMakeLists.txt
  Framework/Crystal/CMakeLists.txt
  Framework/CurveFitting/CMakeLists.txt
  Framework/DataHandling/CMakeLists.txt
  Framework/DataObjects/CMakeLists.txt
  Framework/Geometry/CMakeLists.txt
  Framework/HistogramData/CMakeLists.txt
  Framework/ICat/CMakeLists.txt
  Framework/Indexing/CMakeLists.txt
  Framework/Kernel/CMakeLists.txt
  Framework/LiveData/CMakeLists.txt
  Framework/MDAlgorithms/CMakeLists.txt
  Framework/MPIAlgorithms/CMakeLists.txt
  Framework/Muon/CMakeLists.txt
  Framework/Nexus/CMakeLists.txt
  Framework/NexusGeometry/CMakeLists.txt
  Framework/Parallel/CMakeLists.txt
  Framework/Reflectometry/CMakeLists.txt
  Framework/RemoteAlgorithms/CMakeLists.txt
  Framework/RemoteJobManagers/CMakeLists.txt
  Framework/SINQ/CMakeLists.txt
  Framework/ScriptRepository/CMakeLists.txt
  Framework/Types/CMakeLists.txt
  Framework/WorkflowAlgorithms/CMakeLists.txt
  README.md
  Testing/Tools/cxxtest/python/cxxtest/cxxtest_parser.py
  Testing/Tools/cxxtest/python/cxxtest/cxxtestgen.py
  buildconfig/CMake/Coverage.cmake
  buildconfig/CMake/Coveralls.cmake
  buildconfig/CMake/CoverallsClear.cmake
  buildconfig/CMake/CoverallsGenerateGcov.py
  buildconfig/Jenkins/buildscript
  dev-docs/source/CodeCoverage.rst
  dev-docs/source/PyCharm.rst
  dev-docs/source/VSCode.rst
  mantid-developer-linux.yml
Labels: ISIS Team: LSS, Linux Only

#31764 Tighten up the unit tests for parabolic TOF to d
  Framework/Kernel/test/UnitTest.h
Labels: ISIS Team: Diffraction

#31765 Shim interface rendering surface for testing
  .gitignore
  qt/widgets/instrumentview/CMakeLists.txt
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/IMantidGLWidget.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/ISimpleWidget.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/InstrumentWidget.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/MantidGLWidget.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/SimpleWidget.h
  qt/widgets/instrumentview/src/MantidGLWidget.cpp
  qt/widgets/instrumentview/src/SimpleWidget.cpp
Labels: GUI, ISIS Team: LSS

#31741 Add an Autoreduction configurator in SNAPReduce
  Framework/Kernel/src/PropertyManager.cpp
  Framework/PythonInterface/mantid/utils/path.py
  Framework/PythonInterface/plugins/algorithms/SNAPReduce.py
  Framework/PythonInterface/test/python/mantid/utils/pathTest.py
  Testing/SystemTests/tests/framework/SNAPRedux.py
  docs/source/algorithms/SNAPReduce-v1.rst
  docs/source/release/v6.2.0/diffraction.rst
Labels: Diffraction, ORNL Team

#31771 Add an Autoreduction configurator in SNAPReduce
  Framework/Kernel/src/PropertyManager.cpp
  Framework/PythonInterface/mantid/utils/path.py
  Framework/PythonInterface/plugins/algorithms/SNAPReduce.py
  Framework/PythonInterface/test/python/mantid/utils/pathTest.py
  Testing/SystemTests/tests/framework/SNAPRedux.py
  docs/source/algorithms/SNAPReduce-v1.rst
  docs/source/release/v6.2.0/diffraction.rst
Labels: Diffraction, ORNL Team

#31436 GetEI fails on noisy functions
  Framework/Algorithms/src/GetEi2.cpp
  Framework/Algorithms/test/GetEiTest.h
  docs/source/release/v6.2.0/framework.rst
Labels: Bug, Framework, High Priority, Patch Candidate, Reported By User

#31601 Muon - Create Fitting Contexts
  scripts/Muon/GUI/Common/contexts/fitting_contexts/basic_fitting_context.py
  scripts/Muon/GUI/Common/contexts/fitting_contexts/fitting_context.py
  scripts/Muon/GUI/Common/contexts/fitting_contexts/general_fitting_context.py
  scripts/Muon/GUI/Common/contexts/fitting_contexts/tf_asymmetry_fitting_context.py
  scripts/Muon/GUI/Common/contexts/muon_context.py
  scripts/Muon/GUI/Common/contexts/muon_group_pair_context.py
  scripts/Muon/GUI/Common/fitting_tab_widget/fitting_tab_widget.py
  scripts/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_model.py
  scripts/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_presenter.py
  scripts/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py
  scripts/Muon/GUI/Common/fitting_widgets/basic_fitting/fit_controls_view.py
  scripts/Muon/GUI/Common/fitting_widgets/basic_fitting/fit_function_options_view.py
  scripts/Muon/GUI/Common/fitting_widgets/basic_fitting/workspace_selector_view.py
  scripts/Muon/GUI/Common/fitting_widgets/general_fitting/general_fitting_model.py
  scripts/Muon/GUI/Common/fitting_widgets/general_fitting/general_fitting_options_view.py
  scripts/Muon/GUI/Common/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_model.py
  scripts/Muon/GUI/Common/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_options_view.py
  scripts/Muon/GUI/Common/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_presenter.py
  scripts/Muon/GUI/Common/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_mode_switcher_view.py
  scripts/Muon/GUI/Common/plot_widget/plot_widget_presenter.py
  scripts/Muon/GUI/Common/test_helpers/context_setup.py
  scripts/Muon/GUI/FrequencyDomainAnalysis/frequency_domain_analysis.py
  scripts/Muon/GUI/MuonAnalysis/muon_analysis_2.py
  scripts/test/Muon/CMakeLists.txt
  scripts/test/Muon/basic_fitting_context_test.py
  scripts/test/Muon/fit_information_test.py
  scripts/test/Muon/fit_parameters_test.py
  scripts/test/Muon/fitting_context_test.py
  scripts/test/Muon/fitting_widgets/basic_fitting/basic_fitting_model_test.py
  scripts/test/Muon/fitting_widgets/basic_fitting/basic_fitting_presenter_test.py
  scripts/test/Muon/fitting_widgets/general_fitting/general_fitting_model_test.py
  scripts/test/Muon/fitting_widgets/general_fitting/general_fitting_presenter_test.py
  scripts/test/Muon/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_model_test.py
  scripts/test/Muon/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_presenter_test.py
  scripts/test/Muon/general_fitting_context_test.py
  scripts/test/Muon/plot_widget/plot_widget_model_test.py
  scripts/test/Muon/plot_widget/plot_widget_presenter_test.py
  scripts/test/Muon/results_tab_widget/results_tab_model_test.py
  scripts/test/Muon/tf_asymmetry_fitting_context_test.py
Labels: ISIS Team: Spectroscopy, Muon

#31786 Conda: Ensure compatibility with different python versions
  buildconfig/CMake/Bootstrap.cmake
Labels: Linux Only

#31772 Update WISH SX reduction systems tests
  Testing/Data/SystemTest/WISH19612_vana_bank1_SXProcessed.nxs.md5
  Testing/Data/SystemTest/WISH38237_MD.nxs.md5
  Testing/Data/SystemTest/WISHPredictedSingleCrystalPeaks.nxs.md5
  Testing/SystemTests/tests/framework/ISIS_WISHSingleCrystalReduction.py
  Testing/SystemTests/tests/framework/reference/WISH38237_MD_2Dcut.nxs.md5
Labels: Diffraction, ISIS Team: Diffraction, Single Crystal

#31557 Run systemtests under parent python thread by default
  Testing/SystemTests/lib/systemtests/systemtesting.py
  Testing/SystemTests/scripts/runSystemTests.py
  dev-docs/source/SystemTests.rst
Labels: Maintenance

#31558 Use last successful fit as input to subsequent fits in EngDiff sequential fitting
  docs/source/release/v6.2.0/diffraction.rst
  qt/python/mantidqt/_common.sip
  qt/python/mantidqt/widgets/test/test_fitpropertybrowser.py
  qt/widgets/common/inc/MantidQtWidgets/Common/FitPropertyBrowser.h
  qt/widgets/common/src/FitPropertyBrowser.cpp
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/data_model.py
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/test/test_data_model.py
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/EngDiff_fitpropertybrowser.py
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/plot_presenter.py
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/plot_view.py
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/test/test_plot_presenter.py
  scripts/Engineering/gui/engineering_diffraction/test/engineering_diffraction_io_test.py
Labels: Diffraction, ISIS Team: Diffraction

#31788 Add mocks for instrument viewer tests
  qt/widgets/instrumentview/CMakeLists.txt
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/IMantidGLWidget.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/ISimpleWidget.h
  qt/widgets/instrumentview/test/CMakeLists.txt
  qt/widgets/instrumentview/test/InstrumentWidget/InstrumentWidgetTest.h
  qt/widgets/instrumentview/test/InstrumentWidget/MockMantidGLWidget.h
  qt/widgets/instrumentview/test/InstrumentWidget/MockSimpleWidget.h
Labels: GUI, ISIS Team: LSS

#31746 Various minor warning fixes
  Framework/API/src/MatrixWorkspace.cpp
  Framework/API/test/MuParserUtilsTest.h
  Framework/Algorithms/test/GenerateIPythonNotebookTest.h
  qt/widgets/common/src/FunctionModel.cpp
Labels: Framework, Maintenance

#31742 Add a unit test for ISIS and fix bug in ConvertToMDMinMaxLocal
  Framework/Crystal/test/CentroidPeaksTest.h
  Framework/Crystal/test/NormaliseVanadiumTest.h
  Framework/Crystal/test/PeakIntegrationTest.h
  Framework/MDAlgorithms/src/ConvertToMDMinMaxLocal.cpp
  Framework/MDAlgorithms/test/ConvertToDiffractionMDWorkspace3Test.h
  Framework/TestHelpers/src/MDEventsTestHelper.cpp
  docs/source/release/v6.2.0/framework.rst
  instrument/unit_testing/MINITOPAZ_Definition.xml
Labels: ISIS Team: Diffraction

#31582 Add QThread/Python threading adaptor
  qt/python/CMakeLists.txt
  qt/python/mantidqt/utils/async_qt_adaptor.py
  qt/python/mantidqt/utils/test/test_async_qt_adaptor.py
Labels: GUI, ISIS Team: LSS, Maintenance

#31810 Fix Ipython errors
  qt/python/mantidqt/utils/asynchronous.py
Labels: Bug, High Priority, ISIS Team: Core

#31826 Add Mantid Help Forum account to new starter page
  dev-docs/source/DeveloperAccounts.rst
Labels: Documentation

#31784 Fix errors in LeadPressureCalc algorithm
  Framework/PythonInterface/plugins/algorithms/LeadPressureCalc.py
  Framework/PythonInterface/test/python/plugins/algorithms/LeadPressureCalcTest.py
Labels: Diffraction, ISIS Team: Diffraction

#31780 Update IkedaCarpenterPV doc
  docs/source/fitting/fitfunctions/IkedaCarpenterPV.rst
Labels: Diffraction, Documentation

#31835 Fetch 3rdparty windows updates
  buildconfig/CMake/Bootstrap.cmake
Labels: Bug, Windows Only

#31833 Sliceviewer to call BinMD with NormalizeBasisVectors=False for HKL data
  docs/source/release/v6.2.0/mantidworkbench.rst
  qt/python/mantidqt/widgets/sliceviewer/model.py
  qt/python/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py
Labels: Diffraction, ISIS Team: Diffraction, Single Crystal

#31837 Revert "Code editor close tab icon, forced to material design (#31751)"
  docs/source/release/v6.2.0/mantidworkbench.rst
  qt/python/mantidqt/widgets/codeeditor/multifileinterpreter.py
  qt/python/mantidqt/widgets/codeeditor/tab_widget/codeeditor_tab_view.py
Labels: Added during Sprint, High Priority, ISIS Team: Core

#31776 Reinstate citardauq formula in d spacing unit
  Framework/Kernel/src/Unit.cpp
  Framework/Kernel/test/UnitTest.h
Labels: ISIS Team: Diffraction, Patch Candidate

#31839 Fix for muon freqruency domain fitting data selection
  scripts/Muon/GUI/Common/contexts/frequency_domain_analysis_context.py
  scripts/test/Muon/muon_context_with_frequency_test.py
Labels: ISIS Team: Spectroscopy

#31844 Crystal field IntensityScaling improvements and bug fixes
  Framework/CurveFitting/inc/MantidCurveFitting/Functions/CrystalFieldFunction.h
  Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp
  docs/source/interfaces/indirect/Crystal Field Python Interface.rst
  docs/source/release/v6.2.0/direct_geometry.rst
  scripts/Inelastic/CrystalField/fitting.py
Labels: Bug, Direct Inelastic, Documentation, ISIS Team: Excitations/Vesuvio, Reported By User

#31569 Bugs in DrILL
  scripts/Interface/ui/drill/model/DrillModel.py
  scripts/Interface/ui/drill/presenter/DrillPresenter.py
Labels: Bug, ILL Team

#30852 Workspace calculator widget
  docs/source/images/Workbench/WorkspaceCalculator/WorkspaceCalculator.png
  docs/source/release/v6.2.0/mantidworkbench.rst
  docs/source/workbench/index.rst
  docs/source/workbench/workspacecalculator.rst
  qt/applications/workbench/workbench/app/mainwindow.py
  qt/applications/workbench/workbench/plugins/workspacecalculatorwidget.py
  qt/python/CMakeLists.txt
  qt/python/mantidqt/_common.sip
  qt/python/mantidqt/widgets/workspacecalculator/__init__.py
  qt/python/mantidqt/widgets/workspacecalculator/model.py
  qt/python/mantidqt/widgets/workspacecalculator/presenter.py
  qt/python/mantidqt/widgets/workspacecalculator/test/__init__.py
  qt/python/mantidqt/widgets/workspacecalculator/test/test_workspacecalculator_model.py
  qt/python/mantidqt/widgets/workspacecalculator/test/test_workspacecalculator_presenter.py
  qt/python/mantidqt/widgets/workspacecalculator/test/test_workspacecalculator_view.py
  qt/python/mantidqt/widgets/workspacecalculator/view.py
  qt/python/mantidqt/widgets/workspacecalculator/workspace_calculator.ui
  qt/widgets/common/src/WorkspaceSelector.cpp
Labels: GUI, ILL Team

#31756 Speed up performance of ApplyDiffCal on large instruments
  Framework/DataHandling/src/ApplyDiffCal.cpp
  docs/source/release/v6.2.0/diffraction.rst
Labels: Diffraction, ISIS Team: Diffraction

#31818 Fix to fit tab error in Engineering Diffraction
  Testing/SystemTests/tests/framework/EnginXScriptTest.py
  Testing/SystemTests/tests/framework/reference/engg_focusing_output_ws_bank_1.nxs.md5
  Testing/SystemTests/tests/framework/reference/engg_focusing_output_ws_bank_1_gsl1.nxs.md5
  Testing/SystemTests/tests/framework/reference/engg_focusing_output_ws_bank_2.nxs.md5
  Testing/SystemTests/tests/framework/reference/engg_focusing_output_ws_bank_2_gsl1.nxs.md5
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/data_model.py
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/test/test_data_model.py
  scripts/Engineering/gui/engineering_diffraction/tabs/focus/model.py
  scripts/Engineering/gui/engineering_diffraction/tabs/focus/test/test_focus_model.py
Labels: Diffraction, High Priority, ISIS Team: Diffraction

#31708 Update release checklist and author names
  dev-docs/source/ReleaseChecklist.rst
  tools/DOI/authors.py
Labels: Documentation

#31789 Add missing pragma once statements to headers
  qt/scientific_interfaces/ISISReflectometry/Reduction/BackgroundSubtraction.h
  qt/scientific_interfaces/ISISReflectometry/test/Batch/MockBatchView.h
  qt/scientific_interfaces/ISISReflectometry/test/Common/ClipboardTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Common/PlotterTestQt5.h
  qt/scientific_interfaces/ISISReflectometry/test/Event/MockEventView.h
  qt/scientific_interfaces/ISISReflectometry/test/Experiment/MockExperimentOptionDefaults.h
  qt/scientific_interfaces/ISISReflectometry/test/Experiment/MockExperimentView.h
  qt/scientific_interfaces/ISISReflectometry/test/Experiment/PerThetaDefaultsTableValidatorTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Instrument/MockInstrumentOptionDefaults.h
  qt/scientific_interfaces/ISISReflectometry/test/Instrument/MockInstrumentView.h
  qt/scientific_interfaces/ISISReflectometry/test/MainWindow/MockMainWindowPresenter.h
  qt/scientific_interfaces/ISISReflectometry/test/MainWindow/MockMainWindowView.h
  qt/scientific_interfaces/ISISReflectometry/test/Options/MockOptionsDialogModel.h
  qt/scientific_interfaces/ISISReflectometry/test/Options/MockOptionsDialogPresenter.h
  qt/scientific_interfaces/ISISReflectometry/test/Options/MockOptionsDialogView.h
  qt/scientific_interfaces/ISISReflectometry/test/Options/OptionsDialogPresenterTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Reduction/GroupTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Reduction/ParseReflectometryStringsTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Reduction/ReductionJobsMergeTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Reduction/ValidatePerThetaDefaultsTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Reduction/ValidateRowTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Runs/CatalogRunNotifierTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Runs/MockRunsView.h
  qt/scientific_interfaces/ISISReflectometry/test/Runs/QtCatalogSearcherTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Runs/SearchResultTest.h
  qt/scientific_interfaces/ISISReflectometry/test/RunsTable/MockRunsTablePresenter.h
  qt/scientific_interfaces/ISISReflectometry/test/RunsTable/MockRunsTableView.h
  qt/scientific_interfaces/ISISReflectometry/test/Save/MockSaveView.h
Labels: GUI, ISIS Team: LSS, Reflectometry

#31824 Add back to back exponential usage example to PDCalibration
  docs/source/algorithms/PDCalibration-v1.rst
Labels: Diffraction, ISIS Team: Diffraction

#31714 Observe peak parameters in GetDetectorOffset
  Framework/Algorithms/CMakeLists.txt
  Framework/Algorithms/inc/MantidAlgorithms/FitPeaks.h
  Framework/Algorithms/inc/MantidAlgorithms/GetDetectorOffsets.h
  Framework/Algorithms/inc/MantidAlgorithms/PeakParameterHelper.h
  Framework/Algorithms/src/FitPeaks.cpp
  Framework/Algorithms/src/GetDetectorOffsets.cpp
  Framework/Algorithms/src/PeakParameterHelper.cpp
  Framework/Algorithms/test/GetDetectorOffsetsTest.h
  docs/source/algorithms/AlignDetectors-v1.rst
Labels: Diffraction

#31867 Silence validation for WorkspaceCalculatorWidget
  qt/python/mantidqt/widgets/workspacecalculator/model.py
  qt/python/mantidqt/widgets/workspacecalculator/presenter.py
Labels: ILL Team

#31707 Fix IDA fit not appending spectra to workspace if data from that workspace has already been added
  docs/source/release/v6.2.0/indirect_geometry.rst
  qt/scientific_interfaces/Indirect/IndirectFitDataTableModel.cpp
Labels: ISIS Team: Spectroscopy, Indirect Inelastic

#31857 Increase tolerance and disable check on spectra map for WISH systems test failing on mac
  Testing/SystemTests/tests/framework/ISIS_WISHSingleCrystalReduction.py
Labels: Diffraction, ISIS Team: Diffraction, macOS Only

#31785 Fix broken help link in engineering diffraction interface
  docs/source/release/v6.2.0/diffraction.rst
  scripts/Engineering/gui/engineering_diffraction/presenter.py
Labels: Diffraction, ISIS Team: Diffraction

#31828 Add SliceViewer tooltips to widgets that were missing them
  docs/source/release/v6.2.0/mantidworkbench.rst
  qt/python/mantidqt/widgets/sliceviewer/dimensionwidget.py
  qt/python/mantidqt/widgets/sliceviewer/view.py
Labels: GUI, ISIS Team: Core

#31842 Generate new data for merge reductions test
  scripts/test/SANS/algorithm_detail/merge_reductions_test.py
Labels: Added during Sprint, SANS

#31794 Convert diffcal caching
  Framework/Algorithms/inc/MantidAlgorithms/ConvertDiffCal.h
  Framework/Algorithms/src/ConvertDiffCal.cpp
  Framework/Algorithms/test/ConvertDiffCalTest.h
  Framework/TestHelpers/inc/MantidTestHelpers/ComponentCreationHelper.h
  Framework/TestHelpers/src/ComponentCreationHelper.cpp
  docs/source/algorithms/ConvertDiffCal-v1.rst
  docs/source/release/v6.2.0/diffraction.rst
Labels: Diffraction

#31783 Maintain pseudo-multi-spectrum (single spectrum with physical properties) ties
  docs/source/release/v6.2.0/direct_geometry.rst
  scripts/Inelastic/CrystalField/fitting.py
  scripts/test/CrystalFieldTest.py
Labels: ISIS Team: Excitations/Vesuvio

#31797 Segmentation fault in reduction with logging redirection on Mantid 6.0
  Framework/PythonInterface/CMakeLists.txt
  Framework/PythonInterface/core/inc/MantidPythonInterface/core/PythonStdoutChannel.h
  Framework/PythonInterface/core/src/PythonStdoutChannel.cpp
  Framework/PythonInterface/mantid/kernel/src/kernel.cpp.in
  Framework/PythonInterface/test/cpp/CMakeLists.txt
  Framework/PythonInterface/test/cpp/PythonStdoutChannelTest.h
Labels: Framework, ORNL Team

#31809 Don't save empty Engineering Diffraction GUI after close
  docs/source/release/v6.2.0/diffraction.rst
  scripts/Engineering/gui/engineering_diffraction/engineering_diffraction.py
Labels: Diffraction, ISIS Team: Diffraction

#31787 Add serial fit all to Eng Diff UI - fit all workspaces with same initial parameters
  docs/source/release/v6.2.0/diffraction.rst
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/data_model.py
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/data_presenter.py
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/data_view.py
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/data_widget.ui
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/plot_presenter.py
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/test/test_plot_presenter.py
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/presenter.py
Labels: Diffraction, ISIS Team: Diffraction

#31731 Split Comboboxes in EA auto tab
  scripts/Muon/GUI/ElementalAnalysis2/auto_widget/ea_auto_tab_model.py
  scripts/Muon/GUI/ElementalAnalysis2/auto_widget/ea_auto_tab_presenter.py
  scripts/Muon/GUI/ElementalAnalysis2/auto_widget/ea_auto_tab_view.py
  scripts/Muon/GUI/ElementalAnalysis2/ea_group.py
  scripts/Muon/GUI/ElementalAnalysis2/grouping_widget/ea_grouping_table_widget_presenter.py
  scripts/test/Muon/elemental_analysis_2/EA_auto_tab/ea_auto_tab_model_test.py
  scripts/test/Muon/elemental_analysis_2/EA_auto_tab/ea_auto_tab_presenter_test.py
  scripts/test/Muon/elemental_analysis_2/EA_grouping_tab/elemental_analysis_grouping_table_presenter_test.py
Labels: ISIS Team: Spectroscopy, Muon

#31812 Updated LoadElementalAnalysisData algorithm
  Framework/PythonInterface/plugins/algorithms/LoadElementalAnalysisData.py
  Testing/SystemTests/tests/framework/LoadElementalAnalysisTest.py
  docs/source/release/v6.2.0/muon.rst
Labels: ISIS Team: Spectroscopy, Muon

#31861 Python stdout channel
  Framework/PythonInterface/CMakeLists.txt
  Framework/PythonInterface/core/inc/MantidPythonInterface/core/PythonStdoutChannel.h
  Framework/PythonInterface/core/src/PythonStdoutChannel.cpp
  Framework/PythonInterface/mantid/kernel/src/kernel.cpp.in
  Framework/PythonInterface/test/cpp/CMakeLists.txt
  Framework/PythonInterface/test/cpp/PythonStdoutChannelTest.h
Labels: Framework, ORNL Team

#31831 Fix matrix and table workspace display widgets not staying ontop
  docs/source/release/v6.2.0/mantidworkbench.rst
  qt/python/mantidqt/widgets/workspacedisplay/matrix/presenter.py
  qt/python/mantidqt/widgets/workspacedisplay/status_bar_view.py
  qt/python/mantidqt/widgets/workspacedisplay/table/presenter.py
Labels: ISIS Team: Core, Linux Only, macOS Only

#31841 Add custom tt mode for PEARL
  docs/source/release/v6.2.0/diffraction.rst
  docs/source/techniques/ISISPowder-Pearl-v1.rst
  scripts/Diffraction/isis_powder/pearl.py
  scripts/Diffraction/isis_powder/pearl_routines/pearl_advanced_config.py
  scripts/Diffraction/isis_powder/pearl_routines/pearl_algs.py
  scripts/Diffraction/isis_powder/pearl_routines/pearl_enums.py
  scripts/Diffraction/isis_powder/pearl_routines/pearl_output.py
  scripts/Diffraction/isis_powder/pearl_routines/pearl_param_mapping.py
  scripts/Diffraction/isis_powder/routines/common.py
  scripts/Diffraction/isis_powder/routines/focus.py
Labels: ISIS Team: Diffraction

#31877 Fix tied variables not updating in fit browser after a fit
  docs/source/release/v6.2.0/mantidworkbench.rst
  qt/widgets/common/src/FitPropertyBrowser.cpp
Labels: ISIS Team: Core

#31848 Add Yappi proflier option to main
  dev-docs/source/ProfilingOverview.rst
  qt/applications/workbench/workbench/app/main.py
Labels: GUI, Linux Only, macOS Only

#31735 Grid GUI controls inconsistent with plot generated from script.
  docs/source/release/v6.2.0/mantidworkbench.rst
  qt/applications/workbench/CMakeLists.txt
  qt/applications/workbench/workbench/plotting/figuremanager.py
  qt/applications/workbench/workbench/plotting/propertiesdialog.py
  qt/applications/workbench/workbench/plotting/test/test_propertiesdialog.py
  qt/applications/workbench/workbench/plotting/test/test_toolbar.py
  qt/applications/workbench/workbench/plotting/toolbar.py
Labels: Bug, ISIS Team: Core

#31840 Fix systemtest runner bug
  Testing/SystemTests/lib/systemtests/systemtesting.py
  buildconfig/Jenkins/systemtests
Labels: Added during Sprint, Bug

#31882 Fix cmake variable case to find OpenSSL on non-conda builds
  CMakePresets.json
  buildconfig/CMake/DarwinSetup.cmake
Labels: Added during Sprint, macOS Only

#31821 Add steps to test main to correctly init gmock
  Framework/Algorithms/test/MCAbsorptionStrategyTest.h
  Framework/Catalog/test/CMakeLists.txt
  Framework/ICat/test/CMakeLists.txt
  Framework/Json/CMakeLists.txt
  Framework/Kernel/test/MutexTest.h
  Framework/Nexus/test/CMakeLists.txt
  Framework/PythonInterface/test/cpp/CMakeLists.txt
  Framework/WorkflowAlgorithms/test/CMakeLists.txt
  Testing/Tools/cxxtest/python/cxxtest/cxxtestgen.py
  Testing/Tools/generatetestmain.py
  qt/scientific_interfaces/ISISReflectometry/test/RunsTable/RunsTablePresenterRowDeletionTest.h
  qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmProgress/AlgorithmProgressModel.h
  qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmProgress/IAlgorithmProgressWidget.h
  qt/widgets/common/test/AlgorithmProgress/AlgorithmProgressDialogPresenterTest.h
  qt/widgets/common/test/AlgorithmProgress/AlgorithmProgressPresenterTest.h
  qt/widgets/common/test/AlgorithmProgress/MockAlgorithmProgressDialogWidget.h
  qt/widgets/common/test/AlgorithmProgress/MockAlgorithmProgressWidget.h
  qt/widgets/common/test/ImageInfoPresenterTest.h
  qt/widgets/mplcpp/test/CMakeLists.txt
Labels: Bug

#31375 Superplot widget
  Framework/PythonInterface/mantid/plots/plotfunctions.py
  docs/source/images/superplot_1.png
  docs/source/release/v6.2.0/mantidworkbench.rst
  docs/source/workbench/index.rst
  docs/source/workbench/superplot.rst
  qt/applications/workbench/workbench/plotting/figuremanager.py
  qt/applications/workbench/workbench/plotting/figurewindow.py
  qt/applications/workbench/workbench/plotting/toolbar.py
  qt/applications/workbench/workbench/plugins/workspacewidget.py
  qt/python/CMakeLists.txt
  qt/python/mantidqt/_common.sip
  qt/python/mantidqt/plotting/functions.py
  qt/python/mantidqt/project/plotssaver.py
  qt/python/mantidqt/widgets/superplot/__init__.py
  qt/python/mantidqt/widgets/superplot/ads_observer.py
  qt/python/mantidqt/widgets/superplot/bottom_dock_widget.ui
  qt/python/mantidqt/widgets/superplot/model.py
  qt/python/mantidqt/widgets/superplot/presenter.py
  qt/python/mantidqt/widgets/superplot/side_dock_widget.ui
  qt/python/mantidqt/widgets/superplot/test/test_superplot_model.py
  qt/python/mantidqt/widgets/superplot/test/test_superplot_presenter.py
  qt/python/mantidqt/widgets/superplot/test/test_superplot_view.py
  qt/python/mantidqt/widgets/superplot/view.py
  qt/widgets/common/inc/MantidQtWidgets/Common/WorkspacePresenter/WorkspaceTreeWidgetSimple.h
  qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidgetSimple.cpp
Labels: GUI

#31864 Move Dead time to a Corrections tab in Muon Analysis
  scripts/Muon/GUI/Common/calculate_pair_and_group.py
  scripts/Muon/GUI/Common/contexts/corrections_context.py
  scripts/Muon/GUI/Common/contexts/data_analysis_context.py
  scripts/Muon/GUI/Common/contexts/frequency_domain_analysis_context.py
  scripts/Muon/GUI/Common/contexts/muon_context.py
  scripts/Muon/GUI/Common/contexts/muon_data_context.py
  scripts/Muon/GUI/Common/corrections_tab_widget/__init__.py
  scripts/Muon/GUI/Common/corrections_tab_widget/corrections_model.py
  scripts/Muon/GUI/Common/corrections_tab_widget/corrections_presenter.py
  scripts/Muon/GUI/Common/corrections_tab_widget/corrections_tab_widget.py
  scripts/Muon/GUI/Common/corrections_tab_widget/corrections_view.py
  scripts/Muon/GUI/Common/corrections_tab_widget/corrections_view.ui
  scripts/Muon/GUI/Common/corrections_tab_widget/dead_time_corrections_model.py
  scripts/Muon/GUI/Common/corrections_tab_widget/dead_time_corrections_presenter.py
  scripts/Muon/GUI/Common/corrections_tab_widget/dead_time_corrections_view.py
  scripts/Muon/GUI/Common/corrections_tab_widget/dead_time_corrections_view.ui
  scripts/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py
  scripts/Muon/GUI/Common/home_instrument_widget/home_instrument_widget_model.py
  scripts/Muon/GUI/Common/home_instrument_widget/home_instrument_widget_presenter.py
  scripts/Muon/GUI/Common/home_instrument_widget/home_instrument_widget_view.py
  scripts/Muon/GUI/Common/test_helpers/context_setup.py
  scripts/Muon/GUI/FrequencyDomainAnalysis/frequency_domain_analysis.py
  scripts/Muon/GUI/MuonAnalysis/muon_analysis_2.py
  scripts/test/Muon/CMakeLists.txt
  scripts/test/Muon/corrections_context_test.py
  scripts/test/Muon/corrections_tab_widget/__init__.py
  scripts/test/Muon/corrections_tab_widget/corrections_model_test.py
  scripts/test/Muon/corrections_tab_widget/corrections_presenter_test.py
  scripts/test/Muon/corrections_tab_widget/corrections_view_test.py
  scripts/test/Muon/corrections_tab_widget/dead_time_corrections_model_test.py
  scripts/test/Muon/corrections_tab_widget/dead_time_corrections_presenter_test.py
  scripts/test/Muon/corrections_tab_widget/dead_time_corrections_view_test.py
  scripts/test/Muon/home_instrument_widget_test.py
Labels: ISIS Team: Spectroscopy, Muon

#31921 Add readline back to import list for docs config
  docs/source/conf.py
Labels: Added during Sprint, Bug, ISIS Team: Core

#31916 Fix CMake Python_W check
  buildconfig/CMake/Bootstrap.cmake
  qt/applications/workbench/CMakeLists.txt
Labels: Bug, ISIS Team: Core, macOS Only

#31884 Add includes required for compiling again boost 1.76
  Framework/API/src/SpectrumInfo.cpp
  Framework/CurveFitting/src/FuncMinimizers/FABADAMinimizer.cpp
  Framework/MDAlgorithms/src/ConvertToDiffractionMDWorkspace3.cpp
  Framework/PythonInterface/mantid/api/src/Exports/AnalysisDataServiceObserver.cpp
Labels: Added during Sprint, ISIS Team: Core

#31748 Add default peak function setting to EngDiff UI
  docs/source/interfaces/diffraction/Engineering Diffraction.rst
  docs/source/release/v6.2.0/diffraction.rst
  scripts/Engineering/gui/engineering_diffraction/engineering_diffraction.py
  scripts/Engineering/gui/engineering_diffraction/settings/settings_presenter.py
  scripts/Engineering/gui/engineering_diffraction/settings/settings_view.py
  scripts/Engineering/gui/engineering_diffraction/settings/settings_widget.ui
  scripts/Engineering/gui/engineering_diffraction/settings/test/test_settings_presenter.py
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/EngDiff_fitpropertybrowser.py
Labels: Diffraction, ISIS Team: Diffraction
