Repository mantidproject/mantid, pull requests merged in 2021-04, with the labels that each got.

#30971 Fix crash caused by instrument viewer pick tab plot
  docs/source/release/v6.1.0/mantidworkbench.rst
  qt/widgets/instrumentview/src/MiniPlotMpl.cpp
Labels: Bug, ISIS Team: Core

#30199 Initial PR for the Elemental Analysis Grouping Tab
  scripts/Muon/GUI/Common/ADSHandler/ADS_calls.py
  scripts/Muon/GUI/Common/test_helpers/context_setup.py
  scripts/Muon/GUI/ElementalAnalysis2/context/context.py
  scripts/Muon/GUI/ElementalAnalysis2/context/data_context.py
  scripts/Muon/GUI/ElementalAnalysis2/context/ea_group_context.py
  scripts/Muon/GUI/ElementalAnalysis2/ea_group.py
  scripts/Muon/GUI/ElementalAnalysis2/elemental_analysis.py
  scripts/Muon/GUI/ElementalAnalysis2/grouping_widget/ea_grouping_tab_model.py
  scripts/Muon/GUI/ElementalAnalysis2/grouping_widget/ea_grouping_tab_view.py
  scripts/Muon/GUI/ElementalAnalysis2/grouping_widget/ea_grouping_tab_widget_presenter.py
  scripts/Muon/GUI/ElementalAnalysis2/grouping_widget/ea_grouping_table_widget_presenter.py
  scripts/Muon/GUI/ElementalAnalysis2/grouping_widget/ea_grouping_table_widget_view.py
  scripts/Muon/GUI/ElementalAnalysis2/grouping_widget/ea_grouping_widget.py
  scripts/Muon/GUI/ElementalAnalysis2/load_widget/load_models.py
  scripts/Muon/GUI/ElementalAnalysis2/load_widget/load_utils_ea.py
  scripts/Muon/GUI/ElementalAnalysis2/load_widget/load_widget.py
  scripts/Muon/GUI/ElementalAnalysis2/load_widget/load_widget_presenter.py
  scripts/test/Muon/CMakeLists.txt
  scripts/test/Muon/elemental_analysis_2/EA_grouping_tab/elemental_analysis_grouping_tab_model_test.py
  scripts/test/Muon/elemental_analysis_2/EA_grouping_tab/elemental_analysis_grouping_tab_presenter_test.py
  scripts/test/Muon/elemental_analysis_2/EA_grouping_tab/elemental_analysis_grouping_table_presenter_test.py
  scripts/test/Muon/elemental_analysis_2/EA_loading_tab/__init__.py
  scripts/test/Muon/elemental_analysis_2/EA_loading_tab/elemental_analysis_load_model_test.py
  scripts/test/Muon/elemental_analysis_2/EA_loading_tab/elemental_analysis_load_widget_presenter_test.py
  scripts/test/Muon/elemental_analysis_2/EA_loading_tab/elemental_analysis_loadfile_model_test.py
  scripts/test/Muon/elemental_analysis_2/EA_loading_tab/elemental_analysis_loadrun_model_test.py
  scripts/test/Muon/elemental_analysis_2/EA_loading_tab/elemental_analysis_loadrun_presenter_increment_decrement_test.py
  scripts/test/Muon/elemental_analysis_2/EA_loading_tab/elemental_analysis_loadrun_presenter_single_run_test.py
  scripts/test/Muon/elemental_analysis_2/EA_loading_tab/elemental_analysis_loadutils_test.py
  scripts/test/Muon/elemental_analysis_2/elemental_analysis_context_test.py
Labels: ISIS Team: Spectroscopy, Muon, Workbench

#30613 Peak matching algorithm
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/PeakMatching.py
  Framework/PythonInterface/test/python/plugins/algorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/PeakMatchingTest.py
  docs/source/algorithms/PeakMatching-v1.rst
  docs/source/release/v6.1.0/muon.rst
Labels: ISIS Team: Spectroscopy, Muon

#31022 Implement bankName getter and setter in Peak
  Framework/Crystal/src/FilterPeaks.cpp
  Framework/Crystal/src/PredictSatellitePeaks.cpp
  Framework/Crystal/src/SCDCalibratePanels2.cpp
  Framework/DataObjects/inc/MantidDataObjects/BasePeak.h
  Framework/DataObjects/inc/MantidDataObjects/Peak.h
  Framework/DataObjects/src/BasePeak.cpp
  Framework/DataObjects/src/LeanElasticPeaksWorkspace.cpp
  Framework/DataObjects/src/Peak.cpp
  Framework/DataObjects/src/PeakColumn.cpp
  Framework/Geometry/inc/MantidGeometry/Crystal/IPeak.h
  Framework/Geometry/test/MockObjects.h
  Framework/MDAlgorithms/src/FindPeaksMD.cpp
  Framework/PythonInterface/mantid/api/src/Exports/IPeak.cpp
Labels: Single Crystal

#31030 Implement bankName getter and setter in Peak
  Framework/Crystal/src/FilterPeaks.cpp
  Framework/Crystal/src/PredictSatellitePeaks.cpp
  Framework/Crystal/src/SCDCalibratePanels2.cpp
  Framework/DataObjects/inc/MantidDataObjects/BasePeak.h
  Framework/DataObjects/inc/MantidDataObjects/Peak.h
  Framework/DataObjects/src/BasePeak.cpp
  Framework/DataObjects/src/LeanElasticPeaksWorkspace.cpp
  Framework/DataObjects/src/Peak.cpp
  Framework/DataObjects/src/PeakColumn.cpp
  Framework/Geometry/inc/MantidGeometry/Crystal/IPeak.h
  Framework/Geometry/test/MockObjects.h
  Framework/MDAlgorithms/src/FindPeaksMD.cpp
  Framework/PythonInterface/mantid/api/src/Exports/IPeak.cpp
Labels: Single Crystal

#30929 Memory widget on the workbench main-window
  docs/source/release/v6.1.0/mantidworkbench.rst
  qt/applications/workbench/workbench/app/mainwindow.py
  qt/applications/workbench/workbench/plugins/memorywidget.py
  qt/python/CMakeLists.txt
  qt/python/mantidqt/widgets/memorywidget/__init__.py
  qt/python/mantidqt/widgets/memorywidget/memoryinfo.py
  qt/python/mantidqt/widgets/memorywidget/memorypresenter.py
  qt/python/mantidqt/widgets/memorywidget/memoryview.py
  qt/python/mantidqt/widgets/memorywidget/test/__init__.py
  qt/python/mantidqt/widgets/memorywidget/test/test_memoryinfo.py
  qt/python/mantidqt/widgets/memorywidget/test/test_memorypresenter.py
Labels: ISIS Team: Core, Induction

#31035 Fix ModUB initialization
  Framework/Geometry/src/Crystal/OrientedLattice.cpp
  Framework/Geometry/test/OrientedLatticeTest.h
Labels: Bug, Single Crystal

#31016 PredictPeaks for LeanElasticPeaks and new HFIRCalculateGoniometer algorithm
  Framework/Crystal/inc/MantidCrystal/PredictPeaks.h
  Framework/Crystal/src/PredictPeaks.cpp
  Framework/Crystal/test/PredictPeaksTest.h
  Framework/DataObjects/inc/MantidDataObjects/LeanElasticPeak.h
  Framework/DataObjects/src/LeanElasticPeak.cpp
  Framework/DataObjects/test/LeanElasticPeakTest.h
  Framework/MDAlgorithms/src/ConvertHFIRSCDtoMDE.cpp
  Framework/PythonInterface/mantid/geometry/src/Exports/Goniometer.cpp
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/ConvertWANDSCDtoQ.py
  Framework/PythonInterface/plugins/algorithms/HFIRCalculateGoniometer.py
  Framework/PythonInterface/test/python/plugins/algorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/HFIRCalculateGoniometerTest.py
  Testing/SystemTests/tests/framework/ConvertHFIRSCDtoMDETest.py
  Testing/SystemTests/tests/framework/PredictPeaksTest.py
  docs/source/algorithms/HFIRCalculateGoniometer-v1.rst
  docs/source/release/v6.1.0/diffraction.rst
Labels: Single Crystal

#31042 clean row and col getters and setters from IPeak
  Framework/Crystal/test/CentroidPeaksTest.h
  Framework/DataObjects/inc/MantidDataObjects/BasePeak.h
  Framework/DataObjects/inc/MantidDataObjects/Peak.h
  Framework/DataObjects/src/BasePeak.cpp
  Framework/DataObjects/src/Peak.cpp
  Framework/Geometry/inc/MantidGeometry/Crystal/IPeak.h
  Framework/PythonInterface/mantid/api/src/Exports/IPeak.cpp
  Framework/PythonInterface/plugins/algorithms/IntegratePeaksProfileFitting.py
  Framework/PythonInterface/test/python/mantid/api/IPeaksWorkspaceTest.py
  Framework/PythonInterface/test/python/mantid/geometry/IPeakTest.py
  scripts/SCD_Reduction/BVGFitTools.py
Labels: Single Crystal

#31062 Fix RuntimeError: std::bad_cast when using LeanElastic PeakColumn
  Framework/DataObjects/src/PeakColumn.cpp
  Framework/DataObjects/test/LeanElasticPeaksWorkspaceTest.h
  Framework/DataObjects/test/PeakTest.h
Labels: Bug, Single Crystal

#31061 Instrument view: rescale plot y-axis when range changes
  docs/source/release/v6.1.0/mantidworkbench.rst
  qt/widgets/instrumentview/src/MiniPlotMpl.cpp
Labels: Bug, ISIS Team: Core

#29256 IN16B diffraction reduction
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectILLReductionDIFF.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/IndirectILLReductionDIFFTest.py
  docs/source/algorithms/IndirectILLReductionDIFF-v1.rst
  docs/source/release/v6.1.0/diffraction.rst
  instrument/IN16BD_Parameters.xml
Labels: Diffraction, ILL Team, Indirect Inelastic

#30571 SANSILLAutoProcess select stitching reference
  Framework/Algorithms/inc/MantidAlgorithms/Stitch1DMany.h
  Framework/Algorithms/src/Stitch1DMany.cpp
  Framework/Algorithms/test/Stitch1DManyTest.h
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLAutoProcess.py
  Testing/SystemTests/tests/framework/DrillProcessTest.py
  Testing/SystemTests/tests/framework/SANSILLAutoProcessTest.py
  Testing/SystemTests/tests/framework/reference/D11_AutoProcess_CustomStitch_Reference.nxs.md5
  docs/source/algorithms/Stitch1DMany-v1.rst
  docs/source/release/v6.1.0/framework.rst
  docs/source/release/v6.1.0/sans.rst
  scripts/Interface/ui/drill/model/configurations.py
Labels: ILL Team, SANS

#31057 Fix crash when closing plot window and focusing on another
  docs/source/release/v6.1.0/mantidworkbench.rst
  qt/applications/workbench/workbench/widgets/plotselector/presenter.py
  qt/applications/workbench/workbench/widgets/plotselector/view.py
Labels: Added during Sprint, High Priority, ISIS Team: Core, Reported By User

#31053 GenerateLogbook tolerance test fix
  Framework/PythonInterface/plugins/algorithms/GenerateLogbook.py
  Testing/SystemTests/tests/framework/GenerateLogbookTest.py
  Testing/SystemTests/tests/framework/reference/D11B_Logbook_Reference.nxs.md5
  Testing/SystemTests/tests/framework/reference/D11_Logbook_Reference.nxs.md5
  Testing/SystemTests/tests/framework/reference/D16_Logbook_Reference.nxs.md5
  Testing/SystemTests/tests/framework/reference/D22B_Logbook_Reference.nxs.md5
  Testing/SystemTests/tests/framework/reference/D22_Logbook_Reference.nxs.md5
  Testing/SystemTests/tests/framework/reference/D33_Logbook_Reference.nxs.md5
  Testing/SystemTests/tests/framework/reference/IN4_Logbook_Reference.nxs.md5
  Testing/SystemTests/tests/framework/reference/IN5_Logbook_Reference.nxs.md5
  Testing/SystemTests/tests/framework/reference/IN6_Logbook_Reference.nxs.md5
  instrument/D11B_Parameters.xml
  instrument/D11_Parameters.xml
  instrument/D16_Parameters.xml
  instrument/D22B_Parameters.xml
  instrument/D22_Parameters.xml
  instrument/D33_Parameters.xml
  instrument/D7_Parameters.xml
  instrument/IN4_Parameters.xml
  instrument/IN5_Parameters.xml
  instrument/IN6_Parameters.xml
  instrument/PANTHER_Parameters.xml
Labels: Bug, ILL Team, Windows Only

#30977 override label() in bin edge axis
  Framework/API/inc/MantidAPI/Axis.h
  Framework/API/inc/MantidAPI/BinEdgeAxis.h
  Framework/API/inc/MantidAPI/NumericAxis.h
  Framework/API/src/BinEdgeAxis.cpp
  Framework/API/src/NumericAxis.cpp
  Framework/API/test/BinEdgeAxisTest.h
  Framework/PythonInterface/test/python/mantid/plots/datafunctionsTest.py
  docs/source/release/v6.1.0/framework.rst
  docs/source/release/v6.1.0/mantidworkbench.rst
  qt/python/mantidqt/widgets/workspacedisplay/matrix/table_view_model.py
  qt/python/mantidqt/widgets/workspacedisplay/matrix/test/test_matrixworkspacedisplay_table_view_model.py
Labels: Framework

#31025 Correctly format FullProf output in SaveReflections
  Framework/PythonInterface/plugins/algorithms/SaveReflections.py
  Framework/PythonInterface/test/python/plugins/algorithms/SaveReflectionsTest.py
  Testing/Data/UnitTest/fullprof_format.hkl.md5
  Testing/Data/UnitTest/fullprof_format_modulated.hkl.md5
  Testing/Data/UnitTest/jana_format_modulated-m1.hkl.md5
  Testing/Data/UnitTest/jana_format_modulated-m2.hkl.md5
  Testing/Data/UnitTest/jana_format_modulated.hkl.md5
  docs/source/release/v6.1.0/diffraction.rst
Labels: Diffraction, ISIS Team: Diffraction, Single Crystal

#30878 Fix various issues for D16 hot commissionning
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLIntegration.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLReduction.py
  Testing/SystemTests/tests/framework/reference/ILL_D16_Gamma_Scan.nxs.md5
  docs/source/release/v6.1.0/sans.rst
Labels: Bug, ILL Team, SANS

#31084 CorelliPowderCalibrationCreate: Implement rotational constraint
  Framework/PythonInterface/plugins/algorithms/AlignComponents.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/CorelliPowderCalibrationCreate.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/CorelliPowderCalibrationCreateTest.py
  Testing/SystemTests/tests/framework/CorelliPowderCalibrationTest.py
  docs/source/algorithms/AlignComponents-v1.rst
  docs/source/algorithms/CorelliPowderCalibrationCreate-v1.rst
  docs/source/release/v6.1.0/diffraction.rst
Labels: Single Crystal

#31085 CorelliPowderCalibrationCreate: Implement rotational constraint
  Framework/PythonInterface/plugins/algorithms/AlignComponents.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/CorelliPowderCalibrationCreate.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/CorelliPowderCalibrationCreateTest.py
  Testing/SystemTests/tests/framework/CorelliPowderCalibrationTest.py
  docs/source/algorithms/AlignComponents-v1.rst
  docs/source/algorithms/CorelliPowderCalibrationCreate-v1.rst
  docs/source/release/v6.1.0/diffraction.rst
Labels: Single Crystal

#31079 Bump scipy on OSX
  installers/MacInstaller/requirements.txt
Labels: Bug, macOS Only

#31101 Add IsoRotDiff to Indirect Data Analysis ConvFit tab
  docs/source/release/v6.1.0/indirect_geometry.rst
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisConvFitTab.cpp
  qt/scientific_interfaces/Indirect/IndirectFunctionBrowser/ConvFunctionModel.cpp
  qt/scientific_interfaces/Indirect/IndirectFunctionBrowser/ConvFunctionModel.h
  qt/scientific_interfaces/Indirect/IndirectFunctionBrowser/ConvTypes.cpp
  qt/scientific_interfaces/Indirect/IndirectFunctionBrowser/ConvTypes.h
Labels: ISIS Team: Spectroscopy, Indirect Inelastic

#31077 Fix segfault in PredictPeaks when instrument sample position unset
  Framework/Crystal/src/PredictPeaks.cpp
  Framework/Crystal/test/PredictPeaksTest.h
  docs/source/release/v6.1.0/diffraction.rst
Labels: Bug, Single Crystal

#30783 Loading scan mode data for IN5, PANTHER, SHARP
  Framework/DataHandling/inc/MantidDataHandling/LoadILLDiffraction.h
  Framework/DataHandling/src/LoadHelper.cpp
  Framework/DataHandling/src/LoadILLDiffraction.cpp
  Framework/DataHandling/src/LoadILLTOF2.cpp
  Framework/DataHandling/test/LoadILLDiffractionTest.h
  Framework/DataHandling/test/LoadILLTest.h
  Framework/Kernel/src/NexusDescriptor.cpp
  Testing/Data/UnitTest/ILL/IN5/199857.nxs.md5
  Testing/Data/UnitTest/ILL/PANTHER/010578.nxs.md5
  Testing/Data/UnitTest/ILL/SHARP/000104.nxs.md5
  docs/source/algorithms/LoadILLDiffraction-v1.rst
  docs/source/algorithms/LoadILLTOF-v2.rst
  docs/source/release/v6.1.0/diffraction.rst
  docs/source/release/v6.1.0/direct_geometry.rst
Labels: ILL Team

#30965 Prevent deadlock between observe and replace methods in ADS Observers
  Framework/PythonInterface/mantid/api/src/Exports/AnalysisDataServiceObserver.cpp
  docs/source/release/v6.1.0/mantidworkbench.rst
  qt/applications/workbench/workbench/plotting/figuremanager.py
Labels: ISIS Team: Core

#31082 Update docs for LeanElasticPeak
  docs/source/algorithms/PredictPeaks-v1.rst
  docs/source/concepts/LeanElasticPeaksWorkspace.rst
  docs/source/release/v6.1.0/diffraction.rst
Labels: Single Crystal

#31102 Add SNS instruments to PyChop
  docs/source/release/v6.1.0/direct_geometry.rst
  scripts/PyChop.py
  scripts/PyChop/PyChopGui.py
  scripts/PyChop/arcs.yaml
  scripts/PyChop/cncs.yaml
  scripts/PyChop/hyspec.yaml
  scripts/PyChop/sequoia.yaml
  scripts/test/PyChopTest.py
Labels: Direct Inelastic

#31092 Convert TableWorkspace to MaskWorkspace
  docs/source/release/v6.1.0/framework.rst
  scripts/corelli/calibration/database.py
  scripts/test/corelli/calibration/test_database.py
Labels: Single Crystal

#31093 Convert TableWorkspace to MaskWorkspace
  docs/source/release/v6.1.0/framework.rst
  scripts/corelli/calibration/database.py
  scripts/test/corelli/calibration/test_database.py
Labels: Single Crystal

#30960 Sharp parameters
  instrument/SHARP_Parameters.xml
Labels: Direct Inelastic, ILL Team

#31032 SANS - Wav loops speedup
  Framework/PythonInterface/mantid/py36compat/__init__.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSBeamCentreFinderCore.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSBeamCentreFinderMassMethod.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSCreateAdjustmentWorkspaces.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSReductionCore.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSReductionCoreBase.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSReductionCorePreprocess.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSSingleReduction.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSSingleReductionBase.py
  Framework/PythonInterface/test/python/plugins/algorithms/SANSSubtractTest.py
  Testing/SystemTests/tests/framework/ISIS/SANS/SANS2D/SANS2DMultiPeriodAddFiles.py
  Testing/SystemTests/tests/framework/ISIS/SANS/WORKFLOWS/SANSBatchReductionTest.py
  Testing/SystemTests/tests/framework/ISIS/SANS/WORKFLOWS/SANSReductionCoreTest.py
  Testing/SystemTests/tests/framework/ISIS/SANS/WORKFLOWS/SANSSingleReductionTest.py
  Testing/SystemTests/tests/framework/ISIS/SANS/ZOOM/ZOOMLegacyUserFileTest.py
  Testing/SystemTests/tests/framework/ISIS/SANS/ZOOM/ZOOMTomlFileTest.py
  Testing/SystemTests/tests/framework/ISIS/SANS/ZOOM/ZOOMWavLoopsTest.py
  Testing/SystemTests/tests/framework/SANS_TOML_Wav_Loops.py
  Testing/SystemTests/tests/framework/reference/SANS_TOML_Wav_Loops_ref.nxs.md5
  docs/source/release/v6.1.0/sans.rst
  scripts/SANS/sans/algorithm_detail/CreateSANSAdjustmentWorkspaces.py
  scripts/SANS/sans/algorithm_detail/CreateSANSWavelengthPixelAdjustment.py
  scripts/SANS/sans/algorithm_detail/batch_execution.py
  scripts/SANS/sans/algorithm_detail/bundles.py
  scripts/SANS/sans/algorithm_detail/calculate_sans_transmission.py
  scripts/SANS/sans/algorithm_detail/merge_reductions.py
  scripts/SANS/sans/algorithm_detail/normalize_to_sans_monitor.py
  scripts/SANS/sans/algorithm_detail/single_execution.py
  scripts/SANS/sans/command_interface/ISISCommandInterface.py
  scripts/SANS/sans/command_interface/command_interface_state_director.py
  scripts/SANS/sans/common/general_functions.py
  scripts/SANS/sans/gui_logic/models/state_gui_model.py
  scripts/SANS/sans/gui_logic/presenter/run_tab_presenter.py
  scripts/SANS/sans/state/StateObjects/StateCalculateTransmission.py
  scripts/SANS/sans/state/StateObjects/StateNormalizeToMonitor.py
  scripts/SANS/sans/state/StateObjects/StateWavelength.py
  scripts/SANS/sans/state/StateObjects/StateWavelengthAndPixelAdjustment.py
  scripts/SANS/sans/state/StateObjects/wavelength_interval.py
  scripts/SANS/sans/test_helper/test_director.py
  scripts/SANS/sans/user_file/parser_helpers/wavelength_parser.py
  scripts/SANS/sans/user_file/txt_parsers/ParsedDictConverter.py
  scripts/test/SANS/algorithm_detail/batch_execution_test.py
  scripts/test/SANS/algorithm_detail/calculate_sans_transmission_test.py
  scripts/test/SANS/algorithm_detail/create_sans_adjustment_workspaces_test.py
  scripts/test/SANS/algorithm_detail/create_sans_wavelength_pixel_adjustment_test.py
  scripts/test/SANS/algorithm_detail/merge_reductions_test.py
  scripts/test/SANS/algorithm_detail/normalize_to_sans_monitor_test.py
  scripts/test/SANS/command_interface/command_interface_state_director_test.py
  scripts/test/SANS/common/general_functions_test.py
  scripts/test/SANS/gui_logic/CMakeLists.txt
  scripts/test/SANS/gui_logic/gui_state_director_test.py
  scripts/test/SANS/gui_logic/state_gui_model_test.py
  scripts/test/SANS/gui_logic/wavelength_interval_test.py
  scripts/test/SANS/state/calculate_transmission_test.py
  scripts/test/SANS/state/normalize_to_monitor_test.py
  scripts/test/SANS/state/wavelength_and_pixel_adjustment_test.py
  scripts/test/SANS/state/wavelength_test.py
  scripts/test/SANS/user_file/toml_parsers/parser_helpers/wavelength_parser_test.py
  scripts/test/SANS/user_file/toml_parsers/toml_v1_parser_test.py
  scripts/test/SANS/user_file/txt_parsers/ParsedDictConverterTest.py
Labels: ISIS Team: LSS, SANS

#30534 Fix EngDiffUI not converting peak centres from TOF to d post sequential fit
  docs/source/release/v6.1.0/diffraction.rst
  scripts/Engineering/gui/engineering_diffraction/engineering_diffraction_io.py
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/data_model.py
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/test/test_data_model.py
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/EngDiff_fitpropertybrowser.py
  scripts/Engineering/gui/engineering_diffraction/test/engineering_diffraction_io_test.py
Labels: Diffraction, ISIS Team: Diffraction

#31024 Add SliceViewer view test to check ads observer cleared on close
  qt/python/mantidqt/widgets/sliceviewer/adsobsever.py
  qt/python/mantidqt/widgets/sliceviewer/presenter.py
  qt/python/mantidqt/widgets/sliceviewer/test/test_sliceviewer_view.py
Labels: ISIS Team: Core

#31132 Reduce refresh rate on System Memory Widget
  qt/python/mantidqt/widgets/memorywidget/memorypresenter.py
Labels: Workbench

#31142 Save fit results during project save for EnggDiffUI
  scripts/Engineering/gui/engineering_diffraction/engineering_diffraction_io.py
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/data_model.py
  scripts/Engineering/gui/engineering_diffraction/test/engineering_diffraction_io_test.py
Labels: Diffraction, ISIS Team: Diffraction

#31036 Unicode axis label crash
  Framework/Kernel/inc/MantidKernel/UnitLabel.h
  Framework/Kernel/src/UnitLabel.cpp
  Framework/PythonInterface/test/python/mantid/kernel/UnitLabelTest.py
  docs/source/release/v6.1.0/framework.rst
  qt/python/mantidqt/widgets/workspacedisplay/matrix/test/test_matrixworkspacedisplay_table_view_model.py
Labels: Bug, ISIS Team: Core

#30970 Fit Script Generator - Implement Edit Local Parameter dialog
  qt/widgets/common/inc/MantidQtWidgets/Common/FitDomain.h
  qt/widgets/common/inc/MantidQtWidgets/Common/FitScriptGeneratorMockObjects.h
  qt/widgets/common/inc/MantidQtWidgets/Common/FitScriptGeneratorModel.h
  qt/widgets/common/inc/MantidQtWidgets/Common/FitScriptGeneratorPresenter.h
  qt/widgets/common/inc/MantidQtWidgets/Common/FitScriptGeneratorView.h
  qt/widgets/common/inc/MantidQtWidgets/Common/FunctionBrowser/FunctionBrowserUtils.h
  qt/widgets/common/inc/MantidQtWidgets/Common/IFitScriptGeneratorModel.h
  qt/widgets/common/inc/MantidQtWidgets/Common/IFitScriptGeneratorView.h
  qt/widgets/common/src/FitDomain.cpp
  qt/widgets/common/src/FitScriptGeneratorDataTable.cpp
  qt/widgets/common/src/FitScriptGeneratorModel.cpp
  qt/widgets/common/src/FitScriptGeneratorPresenter.cpp
  qt/widgets/common/src/FitScriptGeneratorView.cpp
  qt/widgets/common/src/FunctionBrowser/FunctionBrowserUtils.cpp
  qt/widgets/common/test/FitDomainTest.h
  qt/widgets/common/test/FitScriptGeneratorModelTest.h
Labels: ISIS Team: Spectroscopy, Muon

#30993 Allow Multiple Directories To Be Used In ALC
  Framework/Muon/src/PlotAsymmetryByLogValue.cpp
  docs/source/release/v6.1.0/muon.rst
  qt/scientific_interfaces/Muon/ALCDataLoadingPresenter.cpp
  qt/scientific_interfaces/Muon/ALCDataLoadingPresenter.h
  qt/scientific_interfaces/Muon/test/ALCDataLoadingPresenterTest.h
Labels: ISIS Team: Spectroscopy

#30862 Fix FileFinder crashes with specific characters
  Framework/API/inc/MantidAPI/FileFinder.h
  Framework/API/src/FileFinder.cpp
  Framework/API/src/MultipleFileProperty.cpp
  Testing/Tools/cxxtest/python/cxxtest/cxxtest_parser.py
  qt/widgets/common/test/FindFilesWorkerTest.h
Labels: Bug, ISIS Team: Spectroscopy, Indirect Inelastic

#31157 Update MVP Calculator GUI Example to PyQt5
  dev-docs/source/MVPTutorial/CalculatorExample/Calculator.py
  dev-docs/source/MVPTutorial/CalculatorExample/View.py
Labels: Documentation

#31158 Update MVP Calculator GUI Example to PyQt5
  dev-docs/source/MVPTutorial/CalculatorExample/Calculator.py
  dev-docs/source/MVPTutorial/CalculatorExample/View.py
Labels: Documentation

#31161 Mantidqt typo
  Framework/PythonInterface/plugins/algorithms/HB2AReduce.py
  dev-docs/source/QtDesignerForPython.rst
  docs/source/release/v6.1.0/diffraction.rst
Labels: Documentation

#31151 Fix instrument widget pick tab tool selection after changing integration range
  docs/source/release/v6.1.0/mantidworkbench.rst
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/InstrumentWidget.h
  qt/widgets/instrumentview/src/InstrumentWidget.cpp
  qt/widgets/instrumentview/src/InstrumentWidgetMaskTab.cpp
Labels: ISIS Team: Core

#31096 Fit Script Generator - Generate Sequential Fit Python Script
  Framework/Algorithms/CMakeLists.txt
  Framework/Algorithms/inc/MantidAlgorithms/GeneratePythonFitScript.h
  Framework/Algorithms/src/GeneratePythonFitScript.cpp
  Framework/Algorithms/test/GeneratePythonFitScriptTest.h
  docs/source/algorithms/GeneratePythonFitScript-v1.rst
  docs/source/release/v6.1.0/framework.rst
  qt/widgets/common/inc/MantidQtWidgets/Common/FitScriptGenerator.ui
  qt/widgets/common/inc/MantidQtWidgets/Common/FitScriptGeneratorMockObjects.h
  qt/widgets/common/inc/MantidQtWidgets/Common/FitScriptGeneratorModel.h
  qt/widgets/common/inc/MantidQtWidgets/Common/FitScriptGeneratorPresenter.h
  qt/widgets/common/inc/MantidQtWidgets/Common/FitScriptGeneratorView.h
  qt/widgets/common/inc/MantidQtWidgets/Common/IFitScriptGeneratorModel.h
  qt/widgets/common/inc/MantidQtWidgets/Common/IFitScriptGeneratorView.h
  qt/widgets/common/src/FitScriptGeneratorModel.cpp
  qt/widgets/common/src/FitScriptGeneratorPresenter.cpp
  qt/widgets/common/src/FitScriptGeneratorView.cpp
  qt/widgets/common/test/FitScriptGeneratorModelTest.h
  qt/widgets/common/test/FitScriptGeneratorPresenterTest.h
  qt/widgets/common/test/FitScriptGeneratorViewTest.h
Labels: ISIS Team: Core, ISIS Team: Spectroscopy, Muon

#30819 Remove MPI example scripts written in python2
  Framework/MPIAlgorithms/scripts/CNCS_mpi_example.py
  Framework/MPIAlgorithms/scripts/EnsembleSamples.sh
  Framework/MPIAlgorithms/scripts/NOM1.py
  Framework/MPIAlgorithms/scripts/NOMAD_mpi_example.py
  Framework/MPIAlgorithms/scripts/PG3_mpi_example.py
  Framework/MPIAlgorithms/scripts/PG3_mpi_reduction.py
  Framework/MPIAlgorithms/scripts/bash_profile
  Framework/MPIAlgorithms/scripts/cncs_script.pbs
  Framework/MPIAlgorithms/scripts/run.sh
Labels: ISIS Team: Core

#31159 Workaround a Qt bug on macOS Big Sur
  docs/source/release/v6.1.0/mantidworkbench.rst
  qt/applications/workbench/workbench/app/start.py
Labels: Added during Sprint, High Priority, ISIS Team: Core, macOS Only

#30660 SANSILL process solvent
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLAutoProcess.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLReduction.py
  Testing/Data/SystemTest/ILL/D11/001091.nxs.md5
  Testing/Data/SystemTest/ILL/D11/001106.nxs.md5
  Testing/Data/SystemTest/ILL/D11/001121.nxs.md5
  Testing/SystemTests/tests/framework/SANSILLAutoProcessTest.py
  Testing/SystemTests/tests/framework/reference/D11_AutoProcess_Solvent_Reference.nxs.md5
  docs/source/algorithms/SANSILLReduction-v1.rst
  docs/source/release/v6.1.0/sans.rst
  scripts/Interface/ui/drill/model/configurations.py
Labels: ILL Team, SANS

#31086 Add support for sip-build to CMake
  .cmake-format.json
  buildconfig/CMake/DarwinSetup.cmake
  buildconfig/CMake/FindPyQt.py
  buildconfig/CMake/FindPyQt4.cmake
  buildconfig/CMake/FindPyQt5.cmake
  buildconfig/CMake/FindSIP.cmake
  buildconfig/CMake/FindSIP.py
  buildconfig/CMake/PyQtFindImpl.cmake
  buildconfig/CMake/SipQtTargetFunctions.cmake
  buildconfig/CMake/sip-build/README.md
  buildconfig/CMake/sip-build/project.py.in
  buildconfig/CMake/sip-build/pyproject.toml.in
  buildconfig/CMake/sip-build/sipqtmodule.sip.in
  qt/python/mantidqt/CMakeLists.txt
  qt/python/mantidqt/_common.sip
  qt/python/mantidqt/icons/CMakeLists.txt
  qt/python/mantidqt/icons/_icons.sip
  qt/python/mantidqt/widgets/instrumentview/CMakeLists.txt
  qt/python/mantidqt/widgets/instrumentview/_instrumentview.sip
  qt/python/mantidqt/widgets/jobtreeview/__init__.py
  qt/python/sip/README
  qt/python/sip/exceptions.sip
  qt/python/sip/string.sip
  qt/python/sip/vector.sip
  qt/python/sip/vector.sip.h
  qt/widgets/common/CMakeLists.txt
  tools/sip/sip-sanitize-module.py
  tools/sip/sipwrapper.py
Labels: macOS Only

#31186 Update direct_geometry.rst
  docs/source/release/v6.1.0/direct_geometry.rst
Labels: Documentation

#31164 Ornl direct utils master
  Framework/PythonInterface/mantid/utils/dgs/__init__.py
  Framework/PythonInterface/mantid/utils/dgs/_geometry.py
  Framework/PythonInterface/test/python/mantid/utils/CMakeLists.txt
  Framework/PythonInterface/test/python/mantid/utils/dgsTest.py
  docs/source/release/v6.1.0/direct_geometry.rst
Labels: Direct Inelastic

#31193 Fix small bug applying constraints with GSL minimisers
  Framework/CurveFitting/src/CostFunctions/CostFuncFitting.cpp
  docs/source/release/v6.1.0/mantidworkbench.rst
Labels: Added during Sprint, ISIS Team: Core

#31171 Access diffractometer constants from spectrum info in EngDiff UI
  Framework/PythonInterface/mantid/api/src/Exports/SpectrumInfo.cpp
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/data_model.py
  scripts/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/test/test_data_model.py
Labels: Diffraction, ISIS Team: Diffraction

#31192 Add manual test for memory widget
  dev-docs/source/Testing/Core/Core.rst
Labels: ISIS Team: Core

#31189 Expose addPeak() to python
  Framework/PythonInterface/mantid/api/src/Exports/IMDWorkspace.cpp
  Framework/PythonInterface/mantid/api/src/Exports/IPeaksWorkspace.cpp
  Framework/PythonInterface/mantid/kernel/CMakeLists.txt
  Framework/PythonInterface/mantid/kernel/src/Exports/SpecialCoordinateSystem.cpp
  Framework/PythonInterface/test/python/mantid/api/IPeaksWorkspaceTest.py
  docs/source/release/v6.1.0/diffraction.rst
  qt/python/mantidqt/widgets/sliceviewer/model.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/model.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/test/modeltesthelpers.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/test/test_peaksviewer_model.py
  qt/python/mantidqt/widgets/sliceviewer/sliceinfo.py
  qt/python/mantidqt/widgets/sliceviewer/test/modeltesthelpers.py
  qt/python/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py
  qt/python/mantidqt/widgets/sliceviewer/test/test_sliceviewer_sliceinfo.py
Labels: Single Crystal

#31163 Ornl direct utils
  Framework/PythonInterface/mantid/utils/dgs/__init__.py
  Framework/PythonInterface/mantid/utils/dgs/_geometry.py
  Framework/PythonInterface/test/python/mantid/utils/CMakeLists.txt
  Framework/PythonInterface/test/python/mantid/utils/dgsTest.py
  docs/source/release/v6.1.0/direct_geometry.rst
Labels: Direct Inelastic

#31134 Detect add files without using -add extension
  Testing/Data/UnitTest/ZOOM00009898.nxs.md5
  Testing/Data/UnitTest/ZOOM9947-a.nxs.md5
  docs/source/release/v6.1.0/sans.rst
  scripts/SANS/sans/algorithm_detail/load_data.py
  scripts/SANS/sans/common/file_information.py
  scripts/test/SANS/common/file_information_test.py
Labels: Bug, ISIS Team: LSS, SANS

#31190 Expose addPeak() to python
  Framework/PythonInterface/mantid/api/src/Exports/IMDWorkspace.cpp
  Framework/PythonInterface/mantid/api/src/Exports/IPeaksWorkspace.cpp
  Framework/PythonInterface/mantid/kernel/CMakeLists.txt
  Framework/PythonInterface/mantid/kernel/src/Exports/SpecialCoordinateSystem.cpp
  Framework/PythonInterface/test/python/mantid/api/IPeaksWorkspaceTest.py
  docs/source/release/v6.1.0/diffraction.rst
  qt/python/mantidqt/widgets/sliceviewer/model.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/model.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/test/modeltesthelpers.py
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/test/test_peaksviewer_model.py
  qt/python/mantidqt/widgets/sliceviewer/sliceinfo.py
  qt/python/mantidqt/widgets/sliceviewer/test/modeltesthelpers.py
  qt/python/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py
  qt/python/mantidqt/widgets/sliceviewer/test/test_sliceviewer_sliceinfo.py
Labels: Single Crystal

#30903 PSIBackgroundSubtraction - Add properties StartX and EndX
  Framework/Muon/inc/MantidMuon/PSIBackgroundSubtraction.h
  Framework/Muon/src/PSIBackgroundSubtraction.cpp
  Framework/Muon/test/PSIBackgroundSubtractionTest.h
  docs/source/release/v6.1.0/muon.rst
Labels: ISIS Team: Spectroscopy, Muon

#30463 Use sectors drawn in the instrument viewer for Q1DWeighted
  Framework/Algorithms/inc/MantidAlgorithms/Q1DWeighted.h
  Framework/Algorithms/src/Q1DWeighted.cpp
  Framework/Algorithms/test/Q1DWeightedTest.h
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLAutoProcess.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLIntegration.py
  docs/source/algorithms/Q1DWeighted-v1.rst
  docs/source/images/Q1DWeightedShapeIntegration.png
  docs/source/release/v6.1.0/sans.rst
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/Projection3D.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/ProjectionSurface.h
  qt/widgets/instrumentview/src/InstrumentWidgetMaskTab.cpp
  qt/widgets/instrumentview/src/Projection3D.cpp
  qt/widgets/instrumentview/src/Shape2D.cpp
  qt/widgets/instrumentview/src/Viewport.cpp
  scripts/Interface/ui/drill/model/DrillModel.py
  scripts/Interface/ui/drill/model/configurations.py
Labels: ILL Team, SANS

#31018 Make MCAbs sample only and env only results the same for same shape
  Framework/Algorithms/src/SampleCorrections/MCInteractionVolume.cpp
  Framework/Algorithms/test/MCInteractionVolumeTest.h
  Testing/SystemTests/tests/framework/MonteCarloAbsorptionCorrTest.py
Labels: Absorption Corrections, ISIS Team: Diffraction

#31087 Create SetValueWhenProperty method and edit IntegratePeaksMD dialog
  Framework/Algorithms/inc/MantidAlgorithms/NormaliseToMonitor.h
  Framework/Algorithms/src/NormaliseToMonitor.cpp
  Framework/Kernel/CMakeLists.txt
  Framework/Kernel/inc/MantidKernel/IPropertySettings.h
  Framework/Kernel/inc/MantidKernel/SetValueWhenProperty.h
  Framework/Kernel/src/SetValueWhenProperty.cpp
  Framework/MDAlgorithms/inc/MantidMDAlgorithms/IntegratePeaksMD2.h
  Framework/MDAlgorithms/src/IntegratePeaksMD2.cpp
  docs/source/release/v6.1.0/diffraction.rst
  qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmPropertiesWidget.h
  qt/widgets/common/src/AlgorithmPropertiesWidget.cpp
  qt/widgets/common/src/BoolPropertyWidget.cpp
  qt/widgets/common/src/FilePropertyWidget.cpp
  qt/widgets/common/src/TextPropertyWidget.cpp
Labels: Diffraction, ISIS Team: Diffraction

#30825 Figaro refactor loader
  Framework/DataHandling/inc/MantidDataHandling/LoadILLReflectometry.h
  Framework/DataHandling/src/LoadILLReflectometry.cpp
  Framework/DataHandling/test/LoadILLReflectometryTest.h
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ReflectometryILLPreprocessTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ReflectometryILLSumForegroundTest.py
  Testing/Data/UnitTest/ILL/Figaro/709886.nxs.md5
  Testing/Data/UnitTest/ILL/Figaro/709922.nxs.md5
  instrument/D17_Parameters.xml
  instrument/FIGARO_Parameters.xml
Labels: ILL Team, Reflectometry

#31165 Patch IN16B diff detector reduction
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectILLReductionDIFF.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/IndirectILLReductionDIFFTest.py
  Testing/Data/UnitTest/ILL/IN16B/313719.nxs.md5
  Testing/Data/UnitTest/ILL/IN16B/313720.nxs.md5
  docs/source/release/v6.1.0/indirect_geometry.rst
  instrument/IN16BD_Parameters.xml
Labels: ILL Team, Indirect Inelastic

#31184 Allow Sample Shape Meshes to be plotted
  Framework/PythonInterface/mantid/geometry/CMakeLists.txt
  Framework/PythonInterface/mantid/geometry/src/Exports/MeshObject.cpp
  docs/source/images/PlotClickMenus3DMesh.png
  docs/source/plotting/3DPlotsHelp.rst
  docs/source/plotting/MeshPlotHelp.rst
  docs/source/release/v6.1.0/diffraction.rst
  qt/applications/workbench/workbench/plotting/plothelppages.py
  qt/applications/workbench/workbench/plotting/propertiesdialog.py
  qt/applications/workbench/workbench/plotting/toolbar.py
  qt/python/mantidqt/plotting/figuretype.py
  qt/python/mantidqt/plotting/test/test_figuretype.py
Labels: Diffraction, ISIS Team: Diffraction

#31078 Create new multiple scattering algorithm based on Muscat
  Framework/Algorithms/CMakeLists.txt
  Framework/Algorithms/inc/MantidAlgorithms/CalculateMultipleScattering.h
  Framework/Algorithms/inc/MantidAlgorithms/InterpolationOption.h
  Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/SparseWorkspace.h
  Framework/Algorithms/src/CalculateMultipleScattering.cpp
  Framework/Algorithms/src/InterpolationOption.cpp
  Framework/Algorithms/src/MonteCarloAbsorption.cpp
  Framework/Algorithms/src/SampleCorrections/SparseWorkspace.cpp
  Framework/Algorithms/test/CalculateMultipleScatteringTest.h
  Framework/Algorithms/test/InterpolationOptionTest.h
  Framework/Geometry/inc/MantidGeometry/Surfaces/Cylinder.h
  Framework/Geometry/inc/MantidGeometry/Surfaces/Line.h
  Framework/Geometry/inc/MantidGeometry/Surfaces/LineIntersectVisit.h
  Framework/Geometry/src/Surfaces/Cylinder.cpp
  Framework/Geometry/src/Surfaces/Line.cpp
  Framework/Geometry/src/Surfaces/LineIntersectVisit.cpp
  Framework/Geometry/test/LineIntersectVisitTest.h
  Framework/Geometry/test/LineTest.h
  docs/source/algorithms/CalculateMultipleScattering-v1.rst
  docs/source/release/v6.1.0/framework.rst
Labels: ISIS Team: Diffraction

#31194 Fix position of new widgets when upgrading workbench versions
  docs/source/release/v6.1.0/mantidworkbench.rst
  qt/applications/workbench/workbench/app/mainwindow.py
  qt/applications/workbench/workbench/config/__init__.py
  qt/applications/workbench/workbench/widgets/settings/general/presenter.py
  qt/applications/workbench/workbench/widgets/settings/general/test/test_general_settings.py
Labels: Added during Sprint, High Priority, ISIS Team: Core

#31148 Muon Plotting Context
  scripts/Muon/GUI/Common/contexts/data_analysis_context.py
  scripts/Muon/GUI/Common/contexts/frequency_domain_analysis_context.py
  scripts/Muon/GUI/Common/contexts/muon_context.py
  scripts/Muon/GUI/Common/contexts/muon_gui_context.py
  scripts/Muon/GUI/Common/contexts/plot_edit_context.py
  scripts/Muon/GUI/Common/contexts/plotting_context.py
  scripts/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_presenter.py
  scripts/Muon/GUI/Common/plot_widget/plot_widget_presenter.py
  scripts/Muon/GUI/Common/plot_widget/plotting_canvas/plot_toolbar.py
  scripts/Muon/GUI/Common/plot_widget/plotting_canvas/plotting_canvas_presenter.py
  scripts/Muon/GUI/Common/plot_widget/plotting_canvas/plotting_canvas_view.py
  scripts/Muon/GUI/Common/plot_widget/plotting_canvas/plotting_canvas_view_interface.py
  scripts/Muon/GUI/Common/plot_widget/plotting_canvas/plotting_canvas_widget.py
  scripts/Muon/GUI/Common/plot_widget/quick_edit/__init__.py
  scripts/Muon/GUI/Common/plot_widget/quick_edit/axis_changer/__init__.py
  scripts/Muon/GUI/Common/plot_widget/quick_edit/axis_changer/axis_changer_presenter.py
  scripts/Muon/GUI/Common/plot_widget/quick_edit/axis_changer/axis_changer_view.py
  scripts/Muon/GUI/Common/plot_widget/quick_edit/quick_edit_presenter.py
  scripts/Muon/GUI/Common/plot_widget/quick_edit/quick_edit_view.py
  scripts/Muon/GUI/Common/plot_widget/quick_edit/quick_edit_widget.py
  scripts/Muon/GUI/Common/test_helpers/context_setup.py
  scripts/Muon/GUI/FrequencyDomainAnalysis/frequency_domain_analysis_2.py
  scripts/Muon/GUI/MuonAnalysis/muon_analysis_2.py
  scripts/test/Muon/fitting_widgets/basic_fitting/basic_fitting_presenter_test.py
  scripts/test/Muon/muon_plot_edit_context_test.py
  scripts/test/Muon/muon_plotting_context_test.py
  scripts/test/Muon/plot_widget/plot_widget_presenter_test.py
  scripts/test/Muon/plotting_canvas/plotting_canvas_presenter_test.py
  scripts/test/Muon/quick_edit/__init__.py
  scripts/test/Muon/quick_edit/quick_edit_presenter_test.py
Labels: ISIS Team: Spectroscopy

#31207 Output xvfb-errors to stderr rather than ignoring them
  buildconfig/Jenkins/buildscript
Labels: ISIS Team: Core, Linux Only

#31095 New Automatic tab for new Elemental analysis gui
  scripts/Muon/GUI/Common/ADSHandler/ADS_calls.py
  scripts/Muon/GUI/ElementalAnalysis2/auto_widget/__init__.py
  scripts/Muon/GUI/ElementalAnalysis2/auto_widget/ea_auto_tab_model.py
  scripts/Muon/GUI/ElementalAnalysis2/auto_widget/ea_auto_tab_presenter.py
  scripts/Muon/GUI/ElementalAnalysis2/auto_widget/ea_auto_tab_view.py
  scripts/Muon/GUI/ElementalAnalysis2/auto_widget/ea_auto_table.py
  scripts/Muon/GUI/ElementalAnalysis2/auto_widget/ea_auto_widget.py
  scripts/Muon/GUI/ElementalAnalysis2/auto_widget/ea_match_table_presenter.py
  scripts/Muon/GUI/ElementalAnalysis2/auto_widget/ea_match_table_view.py
  scripts/Muon/GUI/ElementalAnalysis2/context/ea_group_context.py
  scripts/Muon/GUI/ElementalAnalysis2/elemental_analysis.py
  scripts/Muon/GUI/ElementalAnalysis2/grouping_widget/ea_grouping_table_widget_presenter.py
  scripts/test/Muon/CMakeLists.txt
  scripts/test/Muon/elemental_analysis_2/EA_auto_tab/ea_auto_tab_model_test.py
  scripts/test/Muon/elemental_analysis_2/EA_auto_tab/ea_auto_tab_presenter_test.py
  scripts/test/Muon/elemental_analysis_2/EA_auto_tab/ea_match_table_presenter_test.py
Labels: ISIS Team: Spectroscopy, Muon

#31178 Add option to skip masking of edge tubes in all banks in IntegratePeaksMD
  Framework/MDAlgorithms/inc/MantidMDAlgorithms/IntegratePeaksMD2.h
  Framework/MDAlgorithms/src/IntegratePeaksMD2.cpp
  Framework/MDAlgorithms/test/IntegratePeaksMD2Test.h
  Testing/SystemTests/tests/framework/ISIS_WISHSingleCrystalReduction.py
  docs/source/release/v6.1.0/diffraction.rst
Labels: Diffraction, ISIS Team: Diffraction

#30939 Period Button Muons
  Framework/DataHandling/inc/MantidDataHandling/LoadMuonNexus.h
  Framework/DataHandling/src/LoadMuonNexus.cpp
  Framework/DataHandling/src/LoadMuonNexus1.cpp
  Framework/Nexus/inc/MantidNexus/MuonNexusReader.h
  Framework/Nexus/src/MuonNexusReader.cpp
  docs/source/release/v6.1.0/muon.rst
  qt/scientific_interfaces/Muon/test/ALCDataLoadingPresenterTest.h
  scripts/Muon/GUI/Common/contexts/muon_group_pair_context.py
  scripts/Muon/GUI/Common/grouping_tab_widget/grouping_tab_widget_presenter.py
  scripts/Muon/GUI/Common/grouping_tab_widget/grouping_tab_widget_view.py
  scripts/Muon/GUI/Common/home_runinfo_widget/home_runinfo_widget_presenter.py
  scripts/Muon/GUI/Common/muon_period_info_widget.py
  scripts/Muon/GUI/Common/utilities/load_utils.py
  scripts/Muon/GUI/FrequencyDomainAnalysis/frequency_domain_analysis_2.py
  scripts/Muon/GUI/MuonAnalysis/muon_analysis_2.py
  scripts/test/Muon/CMakeLists.txt
  scripts/test/Muon/grouping_tab/grouping_tab_presenter_test.py
  scripts/test/Muon/home_runinfo_presenter_test.py
  scripts/test/Muon/muon_period_info_widget_test.py
  scripts/test/Muon/utilities/load_utils_test.py
Labels: ISIS Team: Spectroscopy, Muon

#31188 Fix bug in ass calculation in PaalmanPingsMonteCarloAbsorption
  Framework/API/inc/MantidAPI/Sample.h
  Framework/API/src/Sample.cpp
  Framework/PythonInterface/mantid/api/src/Exports/Sample.cpp
  Framework/PythonInterface/mantid/geometry/CMakeLists.txt
  Framework/PythonInterface/mantid/geometry/src/Exports/SampleEnvironment.cpp
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/PaalmanPingsMonteCarloAbsorption.py
  Testing/SystemTests/tests/framework/PaalmanPingsMonteCarloAbsorptionTest.py
  docs/source/release/v6.1.0/framework.rst
Labels: Absorption Corrections, Bug, ISIS Team: Diffraction

#31146 Add legend properties to the plot script generator
  docs/source/release/v6.1.0/mantidworkbench.rst
  qt/applications/workbench/CMakeLists.txt
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/__init__.py
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/legend.py
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/test/test_plotscriptgenerator.py
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/test/test_plotscriptgeneratorlegend.py
Labels: ISIS Team: Core

#31212 SANS Handle workspaces not in the ADS
  scripts/SANS/sans/algorithm_detail/batch_execution.py
  scripts/test/SANS/algorithm_detail/batch_execution_test.py
Labels: Bug, ISIS Team: LSS, Reported By User, SANS

#31199 SANS Transmission - Support Added Event Data
  Testing/Data/SystemTest/ISIS_SANS/ZOOM/ZOOM00009946.nxs.md5
  Testing/Data/SystemTest/ISIS_SANS/ZOOM/ZOOM9947_event.nxs.md5
  Testing/Data/SystemTest/ISIS_SANS/ZOOM/ZOOM9947_histo.nxs.md5
  Testing/SystemTests/tests/framework/ISIS/SANS/ZOOM/ZOOMTransEventData.py
  Testing/SystemTests/tests/framework/reference/ZOOM_trans_added_ref.nxs.md5
  Testing/SystemTests/tests/framework/reference/ZOOM_trans_raw_event_ref.nxs.md5
  docs/source/release/v6.1.0/sans.rst
  scripts/SANS/sans/algorithm_detail/load_data.py
Labels: ISIS Team: LSS, SANS

#31145 Update DEMAND workflow to support satellite peaks
  Framework/Crystal/inc/MantidCrystal/OptimizeLatticeForCellType.h
  Framework/Crystal/src/CalculateUMatrix.cpp
  Framework/Crystal/src/OptimizeLatticeForCellType.cpp
  Framework/Crystal/src/PredictSatellitePeaks.cpp
  Framework/Crystal/test/CalculateUMatrixTest.h
  Framework/Crystal/test/OptimizeLatticeForCellTypeTest.h
  Framework/PythonInterface/plugins/algorithms/HB3AIntegratePeaks.py
  Framework/PythonInterface/plugins/algorithms/HB3APredictPeaks.py
  Framework/PythonInterface/test/python/plugins/algorithms/HB3APredictPeaksTest.py
  Testing/SystemTests/tests/framework/HB3AWorkflowTests.py
  docs/source/algorithms/HB3AIntegratePeaks-v1.rst
  docs/source/algorithms/HB3APredictPeaks-v1.rst
  docs/source/images/HB3A_exp0724_satellites.png
  docs/source/release/v6.1.0/diffraction.rst
  qt/python/mantidqt/widgets/sliceviewer/model.py
  qt/python/mantidqt/widgets/sliceviewer/view.py
Labels: Single Crystal

#31160 PSI Background Subtraction - Add function property
  Framework/API/inc/MantidAPI/FunctionProperty.h
  Framework/API/src/FunctionProperty.cpp
  Framework/Muon/inc/MantidMuon/PSIBackgroundSubtraction.h
  Framework/Muon/src/PSIBackgroundSubtraction.cpp
  Framework/Muon/test/PSIBackgroundSubtractionTest.h
  docs/source/algorithms/PSIBackgroundSubtraction-v1.rst
  docs/source/release/v6.1.0/muon.rst
Labels: ISIS Team: Spectroscopy, Muon

#31181 Added more tests for new elemental analysis gui
  scripts/Muon/GUI/ElementalAnalysis2/auto_widget/ea_auto_tab_model.py
  scripts/Muon/GUI/ElementalAnalysis2/context/context.py
  scripts/Muon/GUI/ElementalAnalysis2/context/data_context.py
  scripts/Muon/GUI/ElementalAnalysis2/context/ea_group_context.py
  scripts/Muon/GUI/ElementalAnalysis2/grouping_widget/ea_grouping_table_widget_presenter.py
  scripts/Muon/GUI/ElementalAnalysis2/grouping_widget/ea_grouping_table_widget_view.py
  scripts/test/Muon/elemental_analysis_2/EA_grouping_tab/elemental_analysis_grouping_tab_model_test.py
  scripts/test/Muon/elemental_analysis_2/EA_grouping_tab/elemental_analysis_grouping_tab_presenter_test.py
  scripts/test/Muon/elemental_analysis_2/EA_grouping_tab/elemental_analysis_grouping_table_presenter_test.py
  scripts/test/Muon/elemental_analysis_2/elemental_analysis_context_test.py
Labels: ISIS Team: Spectroscopy, Muon

#30872 Improvements in DrILL interface
  scripts/Interface/ui/drill/model/DrillModel.py
  scripts/Interface/ui/drill/model/configurations.py
  scripts/Interface/ui/drill/presenter/DrillPresenter.py
  scripts/Interface/ui/drill/test/DrillPresenterTest.py
  scripts/Interface/ui/drill/test/DrillTest.py
  scripts/Interface/ui/drill/view/DrillView.py
  scripts/Interface/ui/drill/view/ui/main.ui
Labels: ILL Team

#31213 Avoid error in EnggFocus by not normalising by current if run has zero proton charge
  Framework/PythonInterface/plugins/algorithms/EnggFocus.py
  Framework/PythonInterface/test/python/plugins/algorithms/EnggFocusTest.py
  docs/source/release/v6.1.0/diffraction.rst
Labels: Bug, Diffraction, ISIS Team: Diffraction

#31237 Create release notes for 6.2
  docs/source/release/index.rst
  docs/source/release/v6.2.0/diffraction.rst
  docs/source/release/v6.2.0/direct_geometry.rst
  docs/source/release/v6.2.0/framework.rst
  docs/source/release/v6.2.0/index.rst
  docs/source/release/v6.2.0/indirect_geometry.rst
  docs/source/release/v6.2.0/mantidworkbench.rst
  docs/source/release/v6.2.0/muon.rst
  docs/source/release/v6.2.0/reflectometry.rst
  docs/source/release/v6.2.0/sans.rst
Labels: ISIS Team: Core

#31236 Add Mesh_Plots to toctree and add link to other plothelp page
  docs/source/plotting/1DPlotsHelp.rst
  docs/source/plotting/ColorfillPlotsHelp.rst
  docs/source/plotting/MeshPlotHelp.rst
  docs/source/plotting/WaterfallPlotsHelp.rst
  docs/source/plotting/index.rst
Labels: Bug, Documentation

#31099 Update CHESS geometry
  instrument/CHESS_Definition.xml
Labels: Direct Inelastic

#31239 Add memory widget to main window image.
  docs/source/images/MantidWorkbenchMainWindow.png
  docs/source/tutorials/mantid_basic_course/getting_started/main_window.rst
Labels: Documentation

#31241 Fix Documentation example failing for rhel7 and windows
  docs/source/algorithms/PSIBackgroundSubtraction-v1.rst
Labels: Bug, High Priority, ISIS Team: Core

#31245 Make small changes to Release Checklist
  dev-docs/source/ReleaseChecklist.rst
Labels: Documentation, ISIS Team: Core

#31243 Fix legend script generator tests
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/legend.py
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/test/test_plotscriptgeneratorlegend.py
Labels: High Priority, ISIS Team: Core

#30743 SANSILL: Add headers to ASCII exports
  Framework/DataHandling/inc/MantidDataHandling/SaveAscii2.h
  Framework/DataHandling/src/LoadILLSANS.cpp
  Framework/DataHandling/src/SaveAscii2.cpp
  Framework/DataHandling/test/SaveAscii2Test.h
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLReduction.py
  Testing/SystemTests/tests/framework/DrillProcessTest.py
  docs/source/algorithms/SaveAscii-v2.rst
  docs/source/release/v6.1.0/framework.rst
  docs/source/release/v6.1.0/mantidworkbench.rst
  docs/source/release/v6.1.0/sans.rst
  instrument/D11B_Parameters.xml
  instrument/D11_Parameters.xml
  instrument/D16_Parameters.xml
  instrument/D17_Parameters.xml
  instrument/D1B_Parameters.xml
  instrument/D22B_Parameters.xml
  instrument/D22_Parameters.xml
  instrument/D2B_Parameters.xml
  instrument/D33_Parameters.xml
  qt/python/mantidqt/widgets/samplelogs/test/test_samplelogs_model.py
  scripts/Interface/ui/drill/model/DrillExportModel.py
Labels: ILL Team, SANS

#30910 User feedback fixes to D7YIGPositionCalibration
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/D7YIGPositionCalibration.py
  docs/source/algorithms/D7YIGPositionCalibration-v1.rst
  docs/source/techniques/PolarisedDiffractionILL.rst
Labels: Diffraction, ILL Team, Powder

#31254 Get home limits from full extent of SamplingImage if sliceviewer plotting a matrix workspace
  docs/source/release/v6.1.0/framework.rst
  qt/python/mantidqt/widgets/sliceviewer/model.py
  qt/python/mantidqt/widgets/sliceviewer/presenter.py
  qt/python/mantidqt/widgets/sliceviewer/test/test_sliceviewer_presenter.py
  qt/python/mantidqt/widgets/sliceviewer/view.py
Labels: Bug, ISIS Team: Core

#31278 Fix minor documentation issues found in Workspace Group concept page
  docs/source/concepts/WorkspaceGroup.rst
Labels: Documentation, ISIS Team: Diffraction

#31290 Removed Mantid Plot from Mantid basics course
  docs/source/tutorials/mantid_basic_course/index.rst
  docs/source/tutorials/mantid_basic_course/using_MantidPlot/01_opening_mantid_plot.rst
  docs/source/tutorials/mantid_basic_course/using_MantidPlot/02_lost_the_plot.rst
  docs/source/tutorials/mantid_basic_course/using_MantidPlot/03_differences.rst
  docs/source/tutorials/mantid_basic_course/using_MantidPlot/04_Exercises_Plot.rst
  docs/source/tutorials/mantid_basic_course/using_MantidPlot/index.rst
Labels: Documentation

#31280 Fix error message for simpleapi.Load with invalid property value
  Framework/PythonInterface/mantid/simpleapi.py
  Framework/PythonInterface/test/python/mantid/SimpleAPITest.py
Labels: Bug, High Priority, ISIS Team: Core

#31289 Fix problem with spectrum axis when panning on colour fill plots
  Framework/PythonInterface/mantid/plots/datafunctions.py
  Framework/PythonInterface/test/python/mantid/plots/datafunctionsTest.py
  docs/source/release/v6.1.0/mantidworkbench.rst
Labels: Bug, High Priority, ISIS Team: Diffraction

#31308 Fix problem with spectrum axis when panning on colour fill plots
  Framework/PythonInterface/mantid/plots/datafunctions.py
  Framework/PythonInterface/test/python/mantid/plots/datafunctionsTest.py
  docs/source/release/v6.1.0/mantidworkbench.rst
Labels: Bug, High Priority, ISIS Team: Diffraction

#31230 correct range for showing nominal d-Spacing lines
  scripts/Calibration/tofpd/diagnostics.py
Labels: Powder

#31286 Fix Project Save not saving python interfaces
  qt/python/mantidqt/project/encoderfactory.py
  qt/python/mantidqt/project/test/test_encoderfactory.py
Labels: High Priority, ISIS Team: Core

#31304 Temporary bug fix to stop crash when trying to compare None in peaksviewer
  docs/source/release/v6.1.0/framework.rst
  qt/python/mantidqt/widgets/sliceviewer/peaksviewer/view.py
Labels: High Priority, ISIS Team: Core
