Repository mantidproject/mantid, pull requests merged in 2022-09, with the labels that each got.

#34312 Check for zero proton charge before performing time slicing
  Framework/PythonInterface/plugins/algorithms/ReflectometrySliceEventWorkspace.py
  Framework/PythonInterface/test/python/plugins/algorithms/ReflectometrySliceEventWorkspaceTest.py
  docs/source/release/v6.5.0/Reflectometry/Bugfixes/34312.rst
Labels: Bug, Reflectometry, ISIS Team: LSS

#34252 Validate constraints string in Fit
  Framework/API/inc/MantidAPI/Expression.h
  Framework/API/src/Expression.cpp
  Framework/CurveFitting/inc/MantidCurveFitting/Algorithms/Fit.h
  Framework/CurveFitting/src/Algorithms/Fit.cpp
  Framework/CurveFitting/test/Algorithms/FitTest.h
  docs/source/release/v6.5.0/Framework/Algorithms/Bugfixes/34251.rst
Labels: Bug, Framework, ILL Team

#34320 Sum banks for 2D detectors
  Framework/Geometry/inc/MantidGeometry/Instrument.h
  Framework/Geometry/src/Instrument.cpp
  Framework/Geometry/test/InstrumentTest.h
  Framework/PythonInterface/core/inc/MantidPythonInterface/core/StlExportDefinitions.h
  Framework/PythonInterface/mantid/geometry/src/Exports/Instrument.cpp
  Framework/PythonInterface/mantid/geometry/src/Exports/RectangularDetector.cpp
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISLoadAndProcess.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISSumBanks.py
  Framework/PythonInterface/test/python/plugins/algorithms/ReflectometryReductionOneLiveDataTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISLoadAndProcessTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISSumBanksTest.py
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/ComponentCreationHelper.h
  Framework/TestHelpers/src/ComponentCreationHelper.cpp
Labels: Reflectometry, ISIS Team: LSS

#34314 Fix sig-noise ratio in ConvertWANDSCDToQ
  Framework/PythonInterface/plugins/algorithms/ConvertWANDSCDtoQ.py
  Framework/PythonInterface/test/python/plugins/algorithms/ConvertWANDSCDtoQTest.py
  Testing/SystemTests/tests/framework/reference/ConvertWANDSCDtoQTest_HKL.nxs.md5
  docs/source/release/v6.5.0/Diffraction/Single_Crystal/Bugfixes/34314.rst
Labels: Single Crystal

#34295 Remove GSL from BSpline
  Framework/API/src/IFunction.cpp
  Framework/Algorithms/inc/MantidAlgorithms/WienerSmooth.h
  Framework/Algorithms/src/WienerSmooth.cpp
  Framework/CurveFitting/inc/MantidCurveFitting/Functions/BSpline.h
  Framework/CurveFitting/inc/MantidCurveFitting/RalNlls/TrustRegion.h
  Framework/CurveFitting/src/Algorithms/SplineSmoothing.cpp
  Framework/CurveFitting/src/Functions/BSpline.cpp
  Framework/CurveFitting/src/RalNlls/TrustRegion.cpp
  Framework/CurveFitting/test/Algorithms/SplineSmoothingTest.h
  Framework/CurveFitting/test/FuncMinimizers/LevenbergMarquardtMDTest.h
  Framework/CurveFitting/test/FuncMinimizers/TrustRegionMinimizerTest.h
  Framework/CurveFitting/test/Functions/BSplineTest.h
  Framework/Kernel/inc/MantidKernel/ArrayBoundedValidator.h
  Framework/Kernel/inc/MantidKernel/BoundedValidator.h
  Framework/Kernel/src/ArrayBoundedValidator.cpp
  Framework/Kernel/test/ArrayBoundedValidatorTest.h
  Framework/Kernel/test/BoundedValidatorTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  qt/widgets/common/inc/MantidQtWidgets/Common/FitPropertyBrowser.h
  qt/widgets/common/src/FitPropertyBrowser.cpp
  qt/widgets/common/src/FunctionTreeView.cpp
  qt/widgets/common/src/PropertyHandler.cpp
Labels: ISIS Team: Spectroscopy, ISIS Team: Excitations/Vesuvio

#34321 Update SimpleShapeDiscusInelastic with container functionality
  Framework/Algorithms/inc/MantidAlgorithms/DiscusMultipleScatteringCorrection.h
  Framework/Algorithms/src/DiscusMultipleScatteringCorrection.cpp
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SimpleShapeDiscusInelastic.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/SimpleShapeDiscusInelasticTest.py
  docs/source/algorithms/SimpleShapeDiscusInelastic-v1.rst
  docs/source/release/v6.5.0/Indirect/New_features/34315 Add Container Support to Discus Wrapper Alg.rst
Labels: ISIS Team: Diffraction

#34280 Add GSASII tab to EngDiff interface
  Testing/Data/UnitTest/gsas2_FE_GAMMA.cif.md5
  Testing/Data/UnitTest/gsas2_output.lst.md5
  Testing/Data/UnitTest/gsas2_output_1.csv.md5
  Testing/Data/UnitTest/gsas2_output_cell_parameters_Fe_gamma.txt.md5
  Testing/Data/UnitTest/gsas2_output_reflections_1_Fe_gamma.txt.md5
  Testing/Data/UnitTest/gsas2_output_table_workspace.nxs.md5
  Testing/Data/UnitTest/gsas2_output_workspace_1.nxs.md5
  docs/source/release/v6.5.0/Diffraction/Engineering/New_features/34280 GSAS II Integration.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/CMakeLists.txt
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/engineering_diffraction.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/settings/settings_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/settings/settings_view.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/settings/settings_widget.ui
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/settings/test/test_settings_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/calibration/model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/calibration/presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/output_settings.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/focus/model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/focus/presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/focus/test/test_focus_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/__init__.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/call_G2sc.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/gsas2_tab.ui
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/parse_inputs.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/plot_toolbar.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/test/__init__.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/test/test_gsas2_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/test/test_gsas2_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/view.py
  scripts/Engineering/EnggUtils.py
Labels: ISIS Team: Diffraction

#34330 DGSPlanner fixes for updated goniometer
  docs/source/release/v6.5.0/Diffraction/Single_Crystal/Bugfixes/34330.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/DGSPlanner/DGSPlannerGUI.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/DGSPlanner/InstrumentSetupWidget.py
Labels: Direct Inelastic, Single Crystal

#34250 Masked bins flag needs checking after cropping
  Framework/API/inc/MantidAPI/MatrixWorkspace.h
  Framework/API/src/MatrixWorkspace.cpp
  Framework/Algorithms/src/ExtractSpectra.cpp
  Framework/Algorithms/test/ExtractSpectraTest.h
  docs/source/release/v6.5.0/Framework/Algorithms/Bugfixes/33556.rst
Labels: Bug, Framework, ILL Team

#34286 Fix crash when opening Interface Help Documentation
  Framework/Geometry/inc/MantidGeometry/Instrument/Parameter.h
  Framework/Kernel/inc/MantidKernel/Instantiator.h
  docs/source/release/v6.5.0/Workbench/Bugfixes/34116.rst
  qt/applications/workbench/CMakeLists.txt
  qt/scientific_interfaces/General/MantidEV.cpp
  qt/scientific_interfaces/General/SampleTransmission.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/MainWindow/MainWindowPresenter.cpp
  qt/scientific_interfaces/Indirect/IndirectInterface.cpp
  qt/scientific_interfaces/Indirect/IndirectSettingsView.cpp
  qt/scientific_interfaces/Muon/ALCBaselineModellingView.cpp
  qt/scientific_interfaces/Muon/ALCDataLoadingView.cpp
  qt/scientific_interfaces/Muon/ALCPeakFittingView.cpp
  qt/widgets/common/CMakeLists.txt
  qt/widgets/common/inc/MantidQtWidgets/Common/HelpWindow.h
  qt/widgets/common/inc/MantidQtWidgets/Common/MantidHelpWindow.h
  qt/widgets/common/src/AlgorithmDialog.cpp
  qt/widgets/common/src/FitPropertyBrowser.cpp
  qt/widgets/common/src/FitScriptGeneratorView.cpp
  qt/widgets/common/src/HelpWindow.cpp
  qt/widgets/common/src/ManageUserDirectories.cpp
  qt/widgets/common/src/MantidHelpWindow.cpp
  qt/widgets/common/src/SelectFunctionDialog.cpp
  qt/widgets/common/src/pqHelpWindow.cxx
  qt/widgets/common/test/MantidHelpWindowTest.h
  qt/widgets/instrumentview/src/BaseCustomInstrumentView.cpp
  qt/widgets/instrumentview/src/InstrumentWidget.cpp
  qt/widgets/plugins/algorithm_dialogs/src/LoadDialog.cpp
Labels: Bug, ISIS Team: Core

#34323 Parallelize more of CI pipeline
  CMakePresets.json
  buildconfig/CMake/FindSIP.cmake
  buildconfig/Jenkins/Conda/delete-old-packages.sh
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
  buildconfig/Jenkins/Conda/package-conda
  buildconfig/Jenkins/Conda/package-standalone
  buildconfig/Jenkins/Conda/update-conda-recipes.sh
  installers/conda/linux/create_tarball.sh
  installers/conda/osx/create_bundle.sh
  installers/conda/win/create_package.sh
Labels: High Priority, ISIS Team: Core

#34257 Create Osiris scripts
  Testing/Data/SystemTest/ISIS_Powder/input/OSIRIS00119963.nxs.md5
  Testing/Data/SystemTest/ISIS_Powder/input/OSIRIS00119964.nxs.md5
  Testing/Data/SystemTest/ISIS_Powder/input/OSIRIS00119977.nxs.md5
  Testing/Data/SystemTest/ISIS_Powder/input/OSIRIS00119978.nxs.md5
  Testing/Data/SystemTest/ISIS_Powder/input/OSIRIS0082717.nxs.md5
  Testing/Data/SystemTest/ISIS_Powder/input/OSIRIS0082718.nxs.md5
  Testing/Data/SystemTest/ISIS_Powder/input/calibration/osiris/1_1/OSI119977-119978_d_spacing.nxs.md5
  Testing/Data/SystemTest/ISIS_Powder/input/calibration/osiris/1_1/OSI119977-119988.nxs.md5
  Testing/Data/SystemTest/ISIS_Powder/input/calibration/osiris/osiris_grouping.cal
  Testing/Data/SystemTest/ISIS_Powder/input/yaml_files/osiris_system_test_mapping.yaml
  Testing/Data/SystemTest/ISIS_Powder/input/yaml_files/osiris_system_test_mapping.yaml.md5
  Testing/SystemTests/tests/framework/ISIS_PowderOsirisTest.py
  docs/source/release/v6.5.0/Indirect/New_features/33666.rst
  docs/source/techniques/ISISPowder-OSIRIS-v1.rst
  scripts/Diffraction/isis_powder/gem.py
  scripts/Diffraction/isis_powder/osiris.py
  scripts/Diffraction/isis_powder/osiris_routines/__init__.py
  scripts/Diffraction/isis_powder/osiris_routines/osiris_advanced_config.py
  scripts/Diffraction/isis_powder/osiris_routines/osiris_algs.py
  scripts/Diffraction/isis_powder/osiris_routines/osiris_param_mapping.py
  scripts/Diffraction/isis_powder/routines/common.py
  scripts/Diffraction/isis_powder/routines/common_output.py
Labels: Indirect Inelastic, ISIS Team: Spectroscopy

#34182 New skew integration algorithm for single crystal Bragg peaks
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/IntegratePeaksSkew.py
  Framework/PythonInterface/test/python/plugins/algorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/IntegratePeaksSkewTest.py
  docs/source/algorithms/IntegratePeaksSkew-v1.rst
  docs/source/images/PeakMaskValidation.png
  docs/source/release/v6.5.0/Diffraction/Single_Crystal/New_features/34182.rst
  instrument/WISH_Definition_10Panels.xml
Labels: Single Crystal, ISIS Team: Diffraction

#34332 Create view and model for indirect Sqw
  qt/scientific_interfaces/Indirect/CMakeLists.txt
  qt/scientific_interfaces/Indirect/IndirectMoments.h
  qt/scientific_interfaces/Indirect/IndirectSqw.cpp
  qt/scientific_interfaces/Indirect/IndirectSqw.h
  qt/scientific_interfaces/Indirect/IndirectSqw.ui
  qt/scientific_interfaces/Indirect/IndirectSqwModel.cpp
  qt/scientific_interfaces/Indirect/IndirectSqwModel.h
  qt/scientific_interfaces/Indirect/IndirectSqwView.cpp
  qt/scientific_interfaces/Indirect/IndirectSqwView.h
  qt/scientific_interfaces/Indirect/test/CMakeLists.txt
  qt/scientific_interfaces/Indirect/test/IndirectMomentsModelTest.h
  qt/scientific_interfaces/Indirect/test/IndirectSqwModelTest.h
Labels: Indirect Inelastic, ISIS Team: Spectroscopy

#34340 Disable failing MantidHelpWindowTest temporarily
  qt/widgets/common/CMakeLists.txt
Labels: ISIS Team: Core

#34336 Updated mslice SHA
  docs/source/release/v6.5.0/Direct_Geometry/MSlice/Bugfixes/34336.rst
  docs/source/release/v6.5.0/Direct_Geometry/MSlice/New_features/34336.rst
  scripts/ExternalInterfaces/CMakeLists.txt
Labels: ISIS Team: Excitations/Vesuvio

#34325 Auto restart live data monitor from refl gui
  docs/source/release/v6.5.0/Reflectometry/Bugfixes/34132.rst
  docs/source/release/v6.5.0/Reflectometry/New_features/34132.rst
  qt/scientific_interfaces/ISISReflectometry/GUI/Runs/RunsPresenter.cpp
Labels: Reflectometry, GUI, ISIS Team: LSS

#34345 Create skeleton release notes for v6.6
  docs/source/release/index.rst
  docs/source/release/v6.6.0/Diffraction/Engineering/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Diffraction/Engineering/New_features/.gitkeep
  docs/source/release/v6.6.0/Diffraction/Powder/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Diffraction/Powder/New_features/.gitkeep
  docs/source/release/v6.6.0/Diffraction/Single_Crystal/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Diffraction/Single_Crystal/New_features/.gitkeep
  docs/source/release/v6.6.0/Direct_Geometry/CrystalField/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Direct_Geometry/CrystalField/New_features/.gitkeep
  docs/source/release/v6.6.0/Direct_Geometry/General/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Direct_Geometry/General/New_features/.gitkeep
  docs/source/release/v6.6.0/Direct_Geometry/MSlice/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Direct_Geometry/MSlice/New_features/.gitkeep
  docs/source/release/v6.6.0/Framework/Algorithms/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Framework/Algorithms/New_features/.gitkeep
  docs/source/release/v6.6.0/Framework/Data_Objects/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Framework/Data_Objects/New_features/.gitkeep
  docs/source/release/v6.6.0/Framework/Fit_Functions/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Framework/Fit_Functions/New_features/.gitkeep
  docs/source/release/v6.6.0/Framework/Python/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Framework/Python/New_features/.gitkeep
  docs/source/release/v6.6.0/Indirect/Algorithms/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Indirect/Algorithms/New_features/.gitkeep
  docs/source/release/v6.6.0/Indirect/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Indirect/New_features/.gitkeep
  docs/source/release/v6.6.0/Muon/ALC/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Muon/Algorithms/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Muon/Elemental_Analysis/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Muon/FDA/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Muon/MA_FDA/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Muon/Muon_Analysis/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Reflectometry/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Reflectometry/New_features/.gitkeep
  docs/source/release/v6.6.0/SANS/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/SANS/New_features/.gitkeep
  docs/source/release/v6.6.0/Workbench/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Workbench/InstrumentViewer/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Workbench/InstrumentViewer/New_features/.gitkeep
  docs/source/release/v6.6.0/Workbench/New_features/.gitkeep
  docs/source/release/v6.6.0/Workbench/SliceViewer/Bugfixes/.gitkeep
  docs/source/release/v6.6.0/Workbench/SliceViewer/New_features/.gitkeep
  docs/source/release/v6.6.0/diffraction.rst
  docs/source/release/v6.6.0/direct_geometry.rst
  docs/source/release/v6.6.0/framework.rst
  docs/source/release/v6.6.0/index.rst
  docs/source/release/v6.6.0/indirect_geometry.rst
  docs/source/release/v6.6.0/mantidworkbench.rst
  docs/source/release/v6.6.0/muon.rst
  docs/source/release/v6.6.0/reflectometry.rst
  docs/source/release/v6.6.0/sans.rst
Labels: ISIS Team: Core

#34205 Add direct functionality to Iqt in IDA
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/TransformToIqt.py
  docs/source/release/v6.5.0/Indirect/New_features/34204.rst
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisIqtTab.cpp
Labels: Direct Inelastic, ISIS Team: Spectroscopy

#34337 SliceViewer: Fix a bug when workspaces are replaced from an algorithm with more than 1 output
  docs/source/release/v6.5.0/Workbench/SliceViewer/Bugfixes/34337.rst
  qt/python/mantidqt/mantidqt/utils/qt/qappthreadcall.py
  qt/python/mantidqt/mantidqt/utils/qt/test/test_qappthreadcall.py
Labels: Bug, ISIS Team: LSS

#34342 Changed requirements for setup.py files to reduce build failures
  qt/applications/workbench/CMakeLists.txt
  qt/applications/workbench/setup.py
  qt/python/mantidqtinterfaces/CMakeLists.txt
  qt/python/mantidqtinterfaces/setup.py
Labels: High Priority, ISIS Team: Core

#34343 Update mslice manual testing documentation
  dev-docs/source/Testing/MSlice/MSliceTestGuide.rst
  docs/source/images/cut_q_chi.png
Labels: Documentation, ISIS Team: Excitations/Vesuvio

#34338 Add check to see if the rectangular detector ids are in the workspace
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISLoadAndProcess.py
Labels: Bug, Reflectometry, ISIS Team: LSS

#34316 Fix crash loading event file with no pulse times
  Framework/DataHandling/src/LoadEventNexus.cpp
  Framework/DataHandling/test/LoadEventNexusTest.h
  Testing/Data/UnitTest/LARMOR00067436.nxs.md5
  docs/source/release/v6.5.0/Framework/Algorithms/Bugfixes/34316.rst
Labels: SANS, Framework, ISIS Team: LSS

#34339 SliceViewer bug fixes
  docs/source/release/v6.5.0/Workbench/SliceViewer/Bugfixes/34339.rst
  qt/python/mantidqt/mantidqt/widgets/colorbar/colorbar.py
  qt/python/mantidqt/mantidqt/widgets/colorbar/test/test_colorbar.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/views/dimensionwidget.py
Labels: Bug

#34393 Fix F(q) fit tab crash when no data selected on parameter change.
  docs/source/release/v6.5.0/Indirect/Bugfixes/34348.rst
  qt/scientific_interfaces/Indirect/FqFitDataPresenter.cpp
Labels: Indirect Inelastic

#34395 Correctly autoscale axes limits on workspace update non-axis cut viewer in sliceviewer
  docs/source/release/v6.5.0/Workbench/SliceViewer/Bugfixes/34395.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer/view.py
Labels: ISIS Team: Core

#34390 Fix incorrect error reporter test instructions
  dev-docs/source/Testing/ErrorReporter-ProjectRecovery/ErrorReporterTesting.rst
Labels: Documentation

#34402 Fix copy bin to table bug
  qt/python/mantidqt/mantidqt/widgets/workspacedisplay/matrix/presenter.py
  qt/python/mantidqt/mantidqt/widgets/workspacedisplay/matrix/test/test_matrixworkspacedisplay_presenter.py
Labels: Bug, ISIS Team: Core

#34412 6.5 diffraction release notes - initial revision
  docs/source/release/v6.5.0/diffraction.rst
Labels: Diffraction, Documentation

#34398 Minor testing docs update
  dev-docs/source/Testing/SliceViewer/SliceViewer.rst
Labels: Documentation

#34400 Check workspace supports non axis cuts before enabling on toggle nonortho view off in sliceviewer
  docs/source/release/v6.5.0/Workbench/SliceViewer/Bugfixes/34400.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenters/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_presenter.py
Labels: ISIS Team: Core

#34405 Update MSlice manual testing doc
  dev-docs/source/Testing/MSlice/MSliceTestGuide.rst
Labels: Documentation

#34419 6.5 sans release notes - initial revisions
  docs/source/release/v6.5.0/sans.rst
Labels: SANS, Documentation

#34426 6.5 direct geometry release notes - initial revisions
  docs/source/interfaces/direct/Crystal Field Python Interface.rst
  docs/source/release/v6.5.0/direct_geometry.rst
Labels: Direct Inelastic, Documentation

#34394 Update user support docs with history database fix
  dev-docs/source/UserSupport.rst
Labels: Documentation

#34420 6.5 framework release notes - initial revisions
  docs/source/release/v6.5.0/framework.rst
Labels: Documentation, Framework

#34389 Improve the beam centre finder test instructions
  dev-docs/source/Testing/SANSGUI/ISISSANSGUITests.rst
Labels: Documentation

#34444 Reduce precision on FitIncidentSpectrum test so passes on all platforms
  Framework/PythonInterface/test/python/plugins/algorithms/FitIncidentSpectrumTest.py
Labels: ISIS Team: Diffraction

#34442 Fix links in Osiris script docs.
  docs/source/techniques/ISISPowder-OSIRIS-v1.rst
Labels: Documentation

#34425 6.5 reflectometry release notes - initial revisions
  docs/source/interfaces/reflectometry/ISIS Reflectometry.rst
  docs/source/release/v6.5.0/reflectometry.rst
Labels: Reflectometry, Documentation

#34423 6.5 workbench release notes - initial revisions
  docs/source/release/v6.5.0/Workbench/SliceViewer/Bugfixes/Used/34339.rst
  docs/source/release/v6.5.0/mantidworkbench.rst
Labels: Documentation

#34335 Allow wavlength ranges in WavRangeReduction
  Testing/SystemTests/tests/framework/ISIS/SANS/ZOOM/ZOOMWavLoopsTest.py
  docs/source/release/v6.5.0/SANS/New_features/34335.rst
  scripts/SANS/sans/command_interface/ISISCommandInterface.py
  scripts/SANS/sans/command_interface/command_interface_state_director.py
  scripts/SANS/sans/state/StateObjects/StateWavelength.py
  scripts/test/SANS/state/wavelength_test.py
Labels: SANS, ISIS Team: LSS

#34408 Always add API import to top of file
  docs/source/release/v6.6.0/Workbench/Bugfixes/34386.rst
  qt/python/mantidqt/mantidqt/widgets/codeeditor/scriptcompatibility.py
  qt/python/mantidqt/mantidqt/widgets/codeeditor/test/test_multifileinterpreter.py
Labels: Bug, ISIS Team: Core, Found in Beta

#34415 Add retry options to nightly pipeline
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
Labels: ISIS Team: Core

#34306 Loader for SANS-1 at MLZ
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/LoadSANS1MLZ.py
  Framework/PythonInterface/plugins/algorithms/SANS1DataMLZ.py
  Framework/PythonInterface/test/python/plugins/algorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/LoadSANS1MLZTest.py
  Testing/Data/UnitTest/D0122881.001.md5
  docs/source/algorithms/LoadSANS1MLZ-v1.rst
  docs/source/images/LoadSANS1MLZ_show_detectors.png
  docs/source/images/LoadSANS1MLZ_show_instrument.png
  docs/source/release/v6.5.0/Framework/Algorithms/New_features/34306_LoadSANS1MLZ.rst
  instrument/SANS-1_MLZ_Definition.xml
  instrument/SANS-1_MLZ_Parameters.xml
Labels: SANS, MLZ Team

#34453 6.5 release notes images and updates
  docs/source/images/6_5_release/Diffraction/GSASII_tab.png
  docs/source/images/6_5_release/Direct/mslice_quick_options.png
  docs/source/images/6_5_release/Indirect/chudley-elliot-fit.png
  docs/source/images/6_5_release/Reflectometry/ascii_checkbox.png
  docs/source/release/v6.5.0/Diffraction/Powder/Bugfixes/Used/34436.rst
  docs/source/release/v6.5.0/SANS/Bugfixes/Used/34433.rst
  docs/source/release/v6.5.0/Workbench/SliceViewer/Bugfixes/Used/34395.rst
  docs/source/release/v6.5.0/Workbench/SliceViewer/Bugfixes/Used/34400.rst
  docs/source/release/v6.5.0/diffraction.rst
  docs/source/release/v6.5.0/direct_geometry.rst
  docs/source/release/v6.5.0/indirect_geometry.rst
  docs/source/release/v6.5.0/mantidworkbench.rst
  docs/source/release/v6.5.0/reflectometry.rst
  docs/source/release/v6.5.0/sans.rst
Labels: Documentation

#34449 Add troubleshooting section to UserSupport for broken Qt Help display
  dev-docs/source/UserSupport.rst
Labels: Documentation
