Repository mantidproject/mantid, pull requests merged in 2022-06, with the labels that each got.

#34005 indirect calibration resolution selection fix
  docs/source/release/v6.4.0/Indirect/Bugfixes/no_issue_cal_fix.rst
  qt/scientific_interfaces/Indirect/ISISCalibration.cpp
Labels: ISIS Team: Spectroscopy

#33986 Tidy and Revise 6.4 Direct Geometry Release Notes
  docs/source/release/v6.4.0/direct_geometry.rst
Labels: Direct Inelastic, Documentation

#33985 Tidy and Revise v6.4 Reflectometry Release Notes
  docs/source/interfaces/reflectometry/ISIS Reflectometry.rst
  docs/source/release/v6.4.0/reflectometry.rst
Labels: Reflectometry, Documentation

#33976 Fix UnEx and Deprecation Warning in Waterfall Plots
  Framework/PythonInterface/mantid/plots/datafunctions.py
  Framework/PythonInterface/mantid/plots/mantidaxes.py
  docs/source/release/v6.4.0/Workbench/Bugfixes/33913.rst
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/curvestabwidget/presenter.py
Labels: High Priority, Bug

#33992 Update developer site build to use https and token access
  buildconfig/Jenkins/dev_site.sh
Labels: Maintenance

#34009 Fix Waterfall Plot's Reverse Order Button
  qt/applications/workbench/workbench/plotting/figuremanager.py
  qt/applications/workbench/workbench/plotting/test/test_figuremanager.py
Labels: Bug

#34019 Prevent Mantid from installing if uninstaller missing
  docs/source/release/v6.4.0/Workbench/Bugfixes/33940.rst
  installers/conda/win/project.nsi
Labels: High Priority, Bug, ISIS Team: Core, Windows Only

#34017 Main revision of Muon release notes for v6.4.0
  docs/source/release/v6.4.0/muon.rst
Labels: Muon, Documentation

#34023 Relabel assets as they are uploaded to GitHub
  buildconfig/Jenkins/Conda/publish-to-github
Labels: ISIS Team: Core

#33972 Fix PointData/Histogram conversion of RebinnedOutput
  Framework/Algorithms/src/XDataConverter.cpp
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SofQWMoments.py
  Testing/Data/UnitTest/iris26176_graphite002_sqw_moments.nxs.md5
  Testing/SystemTests/tests/framework/reference/II.IRISMoments.nxs.md5
  Testing/SystemTests/tests/framework/reference/II.OSIRISMoments.nxs.md5
  docs/source/algorithms/ConvertToPointData-v1.rst
  docs/source/release/v6.4.0/Framework/Algorithms/Bugfixes/33972.rst
Labels: Bug, ISIS Team: Spectroscopy

#34020 Convert QSetting properties to boolean if a boolean is expected
  qt/applications/workbench/workbench/widgets/settings/general/presenter.py
  qt/applications/workbench/workbench/widgets/settings/general/test/test_general_settings.py
Labels: Bug, ISIS Team: Core

#33994 Add Sliceviewer link to Workbench Docs
  docs/source/workbench/index.rst
Labels: Documentation

#34029 Correct sample orientation on Discus inelastic usage example
  Framework/Algorithms/test/DiscusMultipleScatteringCorrectionTest.h
  Framework/Kernel/src/V3D.cpp
  docs/source/algorithms/DiscusMultipleScatteringCorrection-v1.rst
Labels: ISIS Team: Diffraction

#34024 Collate v6.4.0 release notes
  docs/source/release/v6.4.0/Diffraction/Engineering/Bugfixes/Used/33877.rst
  docs/source/release/v6.4.0/Direct_Geometry/Algorithms/New_features/Used/33390.rst
  docs/source/release/v6.4.0/Direct_Geometry/General/Bugfixes/Used/33779.rst
  docs/source/release/v6.4.0/Direct_Geometry/MSlice/Bugfixes/Used/33989.rst
  docs/source/release/v6.4.0/Direct_Geometry/MSlice/New_features/Used/33822.rst
  docs/source/release/v6.4.0/Direct_Geometry/MSlice/New_features/Used/33989.rst
  docs/source/release/v6.4.0/Framework/Algorithms/Bugfixes/Used/33973_FixCrashOnOpeningDiscusAlgDialog.rst
  docs/source/release/v6.4.0/Framework/Kernel/Bugfixes/Used/33896.rst
  docs/source/release/v6.4.0/Framework/Python/New_features/Used/33981.rst
  docs/source/release/v6.4.0/Indirect/Bugfixes/Used/33872.rst
  docs/source/release/v6.4.0/Indirect/Bugfixes/Used/no_issue_cal_fix.rst
  docs/source/release/v6.4.0/SANS/Bugfixes/Used/33962.rst
  docs/source/release/v6.4.0/Workbench/Bugfixes/Used/33913.rst
  docs/source/release/v6.4.0/Workbench/Bugfixes/Used/33925.rst
  docs/source/release/v6.4.0/Workbench/Bugfixes/Used/33944.rst
  docs/source/release/v6.4.0/Workbench/Bugfixes/Used/33990 FixErrorOnSavingPropertiesOnImagePlots.rst
  docs/source/release/v6.4.0/Workbench/SliceViewer/Bugfixes/Used/33882.rst
  docs/source/release/v6.4.0/diffraction.rst
  docs/source/release/v6.4.0/direct_geometry.rst
  docs/source/release/v6.4.0/framework.rst
  docs/source/release/v6.4.0/indirect_geometry.rst
  docs/source/release/v6.4.0/mantidworkbench.rst
  docs/source/release/v6.4.0/sans.rst
Labels: Documentation

#34035 SHA update for MSlice interface and release notes
  docs/source/release/v6.4.0/Direct_Geometry/MSlice/Bugfixes/34035.rst
  scripts/ExternalInterfaces/CMakeLists.txt
Labels: ISIS Team: Excitations/Vesuvio

#34037 Windows admin system wide installation
  installers/conda/win/create_package.sh
  installers/conda/win/project.nsi
Labels: High Priority, ISIS Team: Core, Windows Only

#34039 Fix Help Information in the Instrument Viewer
  docs/source/images/Workbench/InstrumentViewer/DrawBinMask.png
  docs/source/images/Workbench/InstrumentViewer/DrawPropertyBrowser.png
  docs/source/images/Workbench/InstrumentViewer/DrawShapesExample.jpg
  docs/source/images/Workbench/InstrumentViewer/PeakComparisonExample.png
  docs/source/images/Workbench/InstrumentViewer/PeaksAlignmentExample.png
  docs/source/images/Workbench/InstrumentViewer/PickTubeContextMenu.png
  docs/source/images/Workbench/InstrumentViewer/SingleCrystalPeakExample.png
  docs/source/release/v6.4.0/Workbench/InstrumentViewer/Bugfixes/33437.rst
  docs/source/workbench/instrumentviewer.rst
  qt/widgets/instrumentview/src/InstrumentWidget.cpp
Labels: Bug, Documentation

#34036 Complete the Index File for the v6.4.0 Release Notes
  docs/source/release/v6.4.0/index.rst
  docs/source/tutorials/extending_mantid_with_python/python_fit_functions/03_attributes.rst
Labels: Documentation

#34033 Windows compile without precompiled headers
  Framework/Algorithms/src/MaxEnt/MaxentTransformMultiFourier.cpp
  Framework/DataHandling/inc/MantidDataHandling/BankPulseTimes.h
  Framework/DataHandling/inc/MantidDataHandling/LoadBankFromDiskTask.h
  Framework/DataHandling/inc/MantidDataHandling/LoadEventNexus.h
  Framework/DataHandling/src/BankPulseTimes.cpp
  Framework/DataHandling/src/DetermineChunking.cpp
  Framework/DataHandling/src/LoadBankFromDiskTask.cpp
  Framework/DataHandling/src/LoadEventNexus.cpp
  Framework/Nexus/inc/MantidNexus/NexusIOHelper.h
  Framework/WorkflowAlgorithms/inc/MantidWorkflowAlgorithms/HFIRInstrument.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  qt/python/mantidqtinterfaces/MANIFEST.in
  qt/scientific_interfaces/Indirect/CMakeLists.txt
Labels: Maintenance, ISIS Team: Core, Windows Only

#34046 Disallow PyQt5 >=5.15
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: High Priority

#34016 Fix a bug saving add files for multi period data
  scripts/SANS/SANSadd2.py
Labels: High Priority, Bug, SANS, GUI, ISIS Team: LSS

#34047 Compute final package options in jenkinsfile
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
  buildconfig/Jenkins/Conda/package
Labels: High Priority

#34087 Pick info on hovering in the instrument view
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/ProjectionSurface.h
  qt/widgets/instrumentview/src/ProjectionSurface.cpp
Labels: Bug

#34093 Use patch version rather than date for release packages
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
  buildconfig/Jenkins/Conda/package
  buildconfig/Jenkins/Conda/update-conda-recipes.sh
Labels: High Priority

#34092 Fix Sliceviewer grids cannot be enabled with lineplots
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenters/lineplots.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_lineplots.py
Labels: High Priority, Bug

#34095 Fix for Alf view not loading data bug
  qt/widgets/instrumentview/src/InstrumentWidget.cpp
Labels: High Priority, Bug, Found in Beta, ISIS Team: Excitations/Vesuvio

#34097 Disabled script and color line options for contour plots
  docs/source/release/v6.4.0/mantidworkbench.rst
  qt/applications/workbench/workbench/plotting/toolbar.py
  qt/python/mantidqt/mantidqt/plotting/figuretype.py
  qt/python/mantidqt/mantidqt/plotting/test/test_figuretype.py
Labels: High Priority

#34099 Fix for hard crash when masking bins via Instrumentview
  qt/widgets/instrumentview/src/InstrumentActor.cpp
  qt/widgets/instrumentview/src/MaskBinsData.cpp
Labels: High Priority, Bug, Framework, ILL Team

#34086 Change interface documentation category for Fit Script Generator
  docs/source/interfaces/general/Fit Script Generator.rst
  qt/widgets/common/src/FitScriptGeneratorView.cpp
Labels: High Priority, Bug

#34119 Updated MSlice SHA for release
  scripts/ExternalInterfaces/CMakeLists.txt
Labels: High Priority

#34115 DIRECTILL: Fix PANTHER experiment identifier logbook entry
  instrument/PANTHER_Parameters.xml
Labels: Bug, Direct Inelastic, ILL Team

#34134 Fix problems starting up workbench for developers
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: ISIS Team: Diffraction

#34145 Remove PyChop2 interface and deprecate PyChop2 import
  Testing/SystemTests/tests/framework/CrystalFieldPythonInterface.py
  docs/source/images/PyChopGui.png
  docs/source/interfaces/direct/Crystal Field Python Interface.rst
  docs/source/interfaces/direct/PyChop.rst
  docs/source/techniques/CrystalField.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/PyChop/__init__.py
  qt/python/mantidqtinterfaces/test/CMakeLists.txt
  qt/python/mantidqtinterfaces/test/PyChopInstrumentTest.py
  scripts/abins/instruments/pychop.py
  scripts/pychop/Instruments.py
  scripts/pychop/PyChop2.py
  scripts/pychop/__init__.py
Labels: Maintenance, ISIS Team: Excitations/Vesuvio

#34152 Fix windows conversion warnings between int and size_t
  qt/widgets/common/src/FunctionModel.cpp
  qt/widgets/instrumentview/src/PanelsSurface.cpp
Labels: High Priority, ISIS Team: Core

#34104 Move Linked Wiki Files to Main Docs Directories
  dev-docs/source/ISISSANSReductionBackend.rst
  docs/source/algorithms/BinMD-v1.rst
  docs/source/algorithms/LoadFullprofResolution-v1.rst
  docs/source/concepts/InstrumentDefinitionFile.rst
  docs/source/fitting/fitfunctions/BackToBackExponential.rst
  docs/source/fitting/fitfunctions/Bk2BkExpConvPV.rst
  docs/source/fitting/fitfunctions/IkedaCarpenterPV.rst
  docs/source/images/BinMDCoordinateTransformations/BinMD_Coordinate_Transforms.png
  docs/source/images/BinMDCoordinateTransformations/BinMD_Coordinate_Transforms_withLine.png
  docs/source/interfaces/isis_sans/User File Format.rst
  docs/source/techniques/BinMDCoordinateTransformations.rst
  docs/source/techniques/CreateBackToBackParameters.rst
  docs/source/techniques/CreateIkedaCarpenterParameters.rst
  docs/source/techniques/CreateIkedaCarpenterParametersFullprof.rst
  docs/source/techniques/CreateIkedaCarpenterParametersGSAS.rst
  docs/source/techniques/ScriptingSANSReductions.rst
Labels: Documentation, Maintenance

#34112 New TOPAZ file
  Framework/PythonInterface/test/python/plugins/algorithms/MaskBTPTest.py
  docs/source/algorithms/LoadIsawSpectrum-v1.rst
  docs/source/release/v6.5.0/Diffraction/Single_Crystal/New_features/34112.rst
  instrument/TOPAZ_Definition_2019-06-01.xml
  instrument/TOPAZ_Definition_2022-05-23.xml
Labels: Diffraction

#34013 Fix waterfall for log axes in plots
  Framework/PythonInterface/mantid/plots/datafunctions.py
  Framework/PythonInterface/mantid/plots/mantidaxes.py
  Framework/PythonInterface/test/python/mantid/plots/mantidaxesTest.py
  docs/source/release/v6.5.0/Workbench/Bugfixes/33980.rst
Labels: Bug

#34148 Visual Studio: Define a new build configuration for debugging with Conda
  buildconfig/CMake/MSVCSetup.cmake
  buildconfig/CMake/Sanitizers.cmake
Labels: ISIS Team: Core

#33602 Implement uniform distribution of events in N sphere in FakeMD
  Framework/DataObjects/src/FakeMD.cpp
  Framework/MDAlgorithms/test/FindPeaksMDTest.h
  Framework/MDAlgorithms/test/IntegratePeaksMD2Test.h
  Framework/MDAlgorithms/test/IntegratePeaksMDHKLTest.h
  Framework/MDAlgorithms/test/IntegratePeaksMDTest.h
  Framework/PythonInterface/test/python/plugins/algorithms/DeltaPDF3DTest.py
  docs/source/algorithms/BinMD-v1.rst
  docs/source/algorithms/DeltaPDF3D-v1.rst
  docs/source/algorithms/IntegratePeaksMDHKL-v1.rst
  docs/source/algorithms/MDHistoToWorkspace2D-v1.rst
  docs/source/algorithms/ThresholdMD-v1.rst
  docs/source/concepts/LeanElasticPeaksWorkspace.rst
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction

#34159 Create and Embed the RegionSelector In the Reflectometry GUI
  qt/python/mantidqt/mantidqt/widgets/regionselector/presenter.py
  qt/scientific_interfaces/ISISReflectometry/CMakeLists.txt
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/IPreviewView.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewWidget.ui
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/QtPreviewView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/QtPreviewView.h
  qt/scientific_interfaces/ISISReflectometry/test/CMakeLists.txt
  qt/scientific_interfaces/ISISReflectometry/test/Preview/MockPreviewView.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/PreviewPresenterTest.h
  qt/widgets/CMakeLists.txt
  qt/widgets/regionselector/CMakeLists.txt
  qt/widgets/regionselector/inc/MantidQtWidgets/RegionSelector/DllConfig.h
  qt/widgets/regionselector/inc/MantidQtWidgets/RegionSelector/RegionSelector.h
  qt/widgets/regionselector/src/RegionSelector.cpp
Labels: Reflectometry, GUI, ISIS Team: LSS

#34160 Remove Reference to `master` from PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation, ISIS Team: LSS, Added during Sprint

#34142 Set the qt5_dir when conda environment is active for windows
  qt/applications/workbench/CMakeLists.txt
Labels: Bug, Maintenance, ISIS Team: Core, Windows Only

#34162 Force size_t with std::accumulate
  Framework/Beamline/src/SpectrumInfo.cpp
Labels: Bug
