Repository mantidproject/mantid, pull requests merged in 2022-05, with the labels that each got.

#33802 Preventing a memory leak using weak pointers in ADS.
  Framework/PythonInterface/mantid/api/src/Exports/AnalysisDataService.cpp
  Framework/PythonInterface/test/python/mantid/api/AnalysisDataServiceTest.py
  docs/source/release/v6.4.0/Workbench/Bugfixes/33802.rst
Labels: ISIS Team: Core

#33794 Fix the cppcheck warnings in indirect code
  Framework/DataHandling/inc/MantidDataHandling/LoadILLIndirect2.h
  Framework/DataHandling/src/LoadILLIndirect2.cpp
  Framework/WorkflowAlgorithms/src/ProcessIndirectFitParameters.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  qt/scientific_interfaces/Indirect/DensityOfStates.cpp
  qt/scientific_interfaces/Indirect/IndirectCorrections.cpp
  qt/scientific_interfaces/Indirect/IndirectDataAnalysis.cpp
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisConvFitTab.cpp
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisIqtFitTab.cpp
  qt/scientific_interfaces/Indirect/IndirectDataValidationHelper.cpp
  qt/scientific_interfaces/Indirect/IndirectFitData.cpp
  qt/scientific_interfaces/Indirect/IndirectFitDataModel.cpp
  qt/scientific_interfaces/Indirect/IndirectFitPropertyBrowser.cpp
  qt/scientific_interfaces/Indirect/IndirectFunctionBrowser/ConvTypes.h
  qt/scientific_interfaces/Indirect/IndirectLoadILL.cpp
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsModel.cpp
  qt/scientific_interfaces/Indirect/IndirectSymmetrise.cpp
Labels: Indirect Inelastic, Maintenance, ISIS Team: Spectroscopy

#33738 Ignored OutputCompositeMembers fix
  Framework/CurveFitting/src/Algorithms/Fit.cpp
  Framework/CurveFitting/src/MultiDomainCreator.cpp
  Framework/CurveFitting/test/MultiDomainCreatorTest.h
  docs/source/release/v6.4.0/Framework/Fit_Functions/Bugfixes/33737.rst
Labels: Bug, Framework

#33807 Fix WISHProcessVanadiumforNormalisationTest
  Testing/SystemTests/tests/framework/ISIS_WISHSingleCrystalReduction.py
Labels: High Priority, ISIS Team: Core

#33806 Add C++ SipTest disabled on Apple
  qt/widgets/common/CMakeLists.txt
Labels: High Priority, macOS Only, ISIS Team: Core, Added during Sprint

#33810 Create standalone DMG bundle from Conda inside nightly jenkins pipeline
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
  installers/conda/osx/create_bundle.sh
Labels: ISIS Team: Core

#33780 Loading data with whitespaces in path
  Framework/API/src/FileProperty.cpp
  Framework/API/src/MultipleFileProperty.cpp
  Framework/Kernel/inc/MantidKernel/MultiFileNameParser.h
  Framework/Kernel/src/MultiFileNameParser.cpp
  Framework/Kernel/src/UsageService.cpp
  Framework/Kernel/test/MultiFileNameParserTest.h
  Framework/PythonInterface/mantid/kernel/src/Exports/Property.cpp
  Framework/PythonInterface/plugins/algorithms/LoadAndMerge.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/DirectILLCollectData.py
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.4.0/Direct_Geometry/33779.rst
  docs/source/release/v6.4.0/Framework/Algorithms/Bugfixes/33779.rst
  docs/source/release/v6.4.0/Framework/Python/New_features/33779.rst
Labels: Bug, Framework, Reported By User

#33796 Discus Multiple Scattering Usability Enhancements
  Framework/Algorithms/inc/MantidAlgorithms/DiscusMultipleScatteringCorrection.h
  Framework/Algorithms/src/DiscusMultipleScatteringCorrection.cpp
  Framework/Algorithms/test/DiscusMultipleScatteringCorrectionTest.h
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/SimpleShapeDiscusInelasticTest.py
  docs/source/algorithms/DiscusMultipleScatteringCorrection-v1.rst
  docs/source/concepts/AbsorptionAndMultipleScattering.rst
  docs/source/release/v6.4.0/Framework/Algorithms/Bugfixes/33796.rst
  docs/source/release/v6.4.0/Framework/Algorithms/New_features/33796.rst
Labels: ISIS Team: Diffraction

#33795 Add model fitting tab docs and update muon docs
  docs/source/interfaces/muon/Frequency Domain Analysis.rst
  docs/source/interfaces/muon/feature_flags.rst
  docs/source/interfaces/muon/muon_analysis_plotting_window.rst
  docs/source/interfaces/muon/muon_model_fitting_tab.rst
  docs/source/interfaces/muon/muon_plotting_window.rst
  docs/source/release/v6.4.0/Muon/MA_FDA/New_features/33689.rst
Labels: Muon, ISIS Team: Spectroscopy

#33817 Update Conda build script for incremental builds
  buildconfig/Jenkins/Conda/conda-buildscript
Labels: High Priority, ISIS Team: Core

#33693 Loader for Salsa instrument at ILL
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/LoadILLSALSA.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLTOF2.h
  Framework/DataHandling/src/LoadILLDiffraction.cpp
  Framework/DataHandling/src/LoadILLSALSA.cpp
  Framework/DataHandling/src/LoadILLTOF2.cpp
  Framework/DataHandling/test/LoadILLSALSATest.h
  Framework/DataHandling/test/LoadILLTest.h
  Testing/Data/UnitTest/ILL/SALSA/046430.nxs.md5
  Testing/Data/UnitTest/ILL/SALSA/046508.nxs.md5
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.4.0/Diffraction/Engineering/New_features/33693.rst
  instrument/SALSA_Definition.xml
Labels: ILL Team

#33771 Add documentation for how to create an environment to benchmark Mantid minimizers
  dev-docs/source/ObtainingABenchmarkForMantidFitting.rst
  dev-docs/source/WindowsSubsystemForLinux.rst
  dev-docs/source/index.rst
Labels: Documentation, ISIS Team: Core, ISIS Team: Excitations/Vesuvio

#33814 Modify some variables names to clarify summed empty instrument
  scripts/Diffraction/isis_powder/gem_routines/gem_algs.py
  scripts/Diffraction/isis_powder/hrpd_routines/hrpd_algs.py
  scripts/Diffraction/isis_powder/pearl_routines/pearl_algs.py
  scripts/Diffraction/isis_powder/polaris_routines/polaris_algs.py
  scripts/Diffraction/isis_powder/routines/calibrate.py
  scripts/Diffraction/isis_powder/routines/focus.py
  scripts/Diffraction/isis_powder/routines/run_details.py
  scripts/Diffraction/isis_powder/test/ISISPowderAbstractInstrumentTest.py
  scripts/Diffraction/isis_powder/test/ISISPowderRunDetailsTest.py
Labels: ISIS Team: Diffraction

#33813 Update muon plots for new matplotlib
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/plot_widget/plotting_canvas/plot_toolbar.py
Labels: ISIS Team: Spectroscopy

#33823 Add Windows standalone package creation to Conda Jenkins pipeline.
  buildconfig/Jenkins/Conda/conda-build-recipes
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
  installers/conda/win/create_package.sh
Labels: High Priority, ISIS Team: Core

#33767 Investigate changing the step size for fitting
  Framework/API/inc/MantidAPI/CompositeFunction.h
  Framework/API/inc/MantidAPI/IFunction.h
  Framework/API/inc/MantidAPI/IFunction1D.tcc
  Framework/API/src/CompositeFunction.cpp
  Framework/API/src/IFunction.cpp
  Framework/API/test/CompositeFunctionTest.h
  Framework/API/test/IFunctionTest.h
  Framework/CurveFitting/inc/MantidCurveFitting/IFittingAlgorithm.h
  Framework/CurveFitting/src/IFittingAlgorithm.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/algorithms/Fit-v1.rst
  docs/source/release/v6.4.0/Framework/Algorithms/New_features/33616.rst
Labels: ISIS Team: Core, ISIS Team: Excitations/Vesuvio

#33815 Use re compile for regex strings in CrystalField
  scripts/Inelastic/CrystalField/CrystalFieldMultiSite.py
  scripts/Inelastic/CrystalField/fitting.py
  scripts/Inelastic/CrystalField/function.py
  scripts/Inelastic/CrystalField/normalisation.py
  scripts/Inelastic/CrystalField/pointcharge.py
Labels: Maintenance, ISIS Team: Excitations/Vesuvio

#33819 Add script to create standalone Linux tarball
  buildconfig/CMake/Packaging/launch_mantidworkbench.sh.in
  installers/conda/linux/create_tarball.sh
  qt/applications/workbench/workbench/app/start.py
  qt/python/mantidqt/mantidqt/dialogs/errorreports/main.py
Labels: ISIS Team: Core, Linux Only, Added during Sprint

#33822 Updated MSlice SHA and release notes
  docs/source/release/v6.4.0/Direct_Geometry/MSlice/Bugfixes/33822.rst
  docs/source/release/v6.4.0/Direct_Geometry/MSlice/New_features/33822.rst
  scripts/ExternalInterfaces/CMakeLists.txt
Labels: ISIS Team: Excitations/Vesuvio

#33789 Add asymmetric Pearson VII fit function to PoldiDataAnalysis algorithm
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/PoldiDataAnalysis.py
  Framework/SINQ/inc/MantidSINQ/PoldiFitPeaks2D.h
  Framework/SINQ/src/PoldiFitPeaks2D.cpp
  Framework/SINQ/test/PoldiFitPeaks2DTest.h
  docs/source/release/v6.4.0/Framework/Algorithms/New_features/33789.rst
Labels: Powder

#33765 Non axis aligned cutting tool in sliceviewer
  dev-docs/source/Testing/SliceViewer/SliceViewer.rst
  dev-docs/source/images/SliceViewer/CutViewer_HKplane.png
  dev-docs/source/images/SliceViewer/CutViewer_KLplane.png
  docs/source/images/SliceViewer_CutViewer.png
  docs/source/release/v6.4.0/Workbench/SliceViewer/New_features/33765.rst
  docs/source/workbench/sliceviewer.rst
  qt/python/mantidqt/CMakeLists.txt
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer/model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer/representation/cut_representation.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer/representation/test/test_cut_representation.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer/test/test_cutviewer_model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer/test/test_cutviewer_presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer/view.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/workspaceinfo.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenters/base_presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenters/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_workspace_info.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/views/dataview.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/views/toolbar.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/views/view.py
Labels: ISIS Team: Core

#33798 Remove convert to point data from SofQWMoments
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SofQWMoments.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/SofQWMomentsTest.py
  Testing/Data/UnitTest/iris26176_graphite002_sqw_moments.nxs.md5
  Testing/SystemTests/tests/framework/reference/II.IRISMoments.nxs.md5
  Testing/SystemTests/tests/framework/reference/II.OSIRISMoments.nxs.md5
  docs/source/release/v6.4.0/Indirect/Bugfixes/33777.rst
Labels: Indirect Inelastic, ISIS Team: Spectroscopy

#33859 Fix compilation with boost 1.77 on Windows
  qt/applications/workbench/CMakeLists.txt
  qt/applications/workbench/mantidworkbench.cpp
  qt/scientific_interfaces/ISISReflectometry/test/Reduction/ParseReflectometryStringsTest.h
Labels: High Priority

#33860 Workaround boost 1.77 on clang 13
  qt/applications/workbench/CMakeLists.txt
Labels: macOS Only

#33848 Update mantid benchmark documentation
  dev-docs/source/ObtainingABenchmarkForMantidFitting.rst
Labels: Documentation, ISIS Team: Core, ISIS Team: Excitations/Vesuvio

#33825 Fix Issues with SANS Systemtest on Conda Builds
  Framework/Algorithms/inc/MantidAlgorithms/ReplaceSpecialValues.h
  Framework/Algorithms/src/ReplaceSpecialValues.cpp
  Framework/Algorithms/test/ReplaceSpecialValuesTest.h
  Testing/SystemTests/tests/framework/ISIS/SANS/SANS2D/SANS2D_GDW20_4m_cycle_22_02.py
  Testing/SystemTests/tests/framework/reference/SANS2D_GDW20_4m_cycle_22_02_2D_M4_V2_ref.nxs.md5
  Testing/SystemTests/tests/framework/reference/SANS2D_GDW20_4m_cycle_22_02_2D_M4_v3_ref.nxs.md5
  docs/source/release/v6.4.0/Framework/Algorithms/New_features/sans_systest.rst
  scripts/SANS/isis_reduction_steps.py
  scripts/SANS/sans/algorithm_detail/convert_to_q.py
  scripts/SANS/sans/command_interface/ISISCommandInterface.py
Labels: High Priority, SANS, Framework

#33889 Fix the prototype nightly deployment pipeline
  Framework/DataObjects/inc/MantidDataObjects/PeakShapeFactory.h
  Framework/Geometry/src/Crystal/ReflectionCondition.cpp
  Framework/Geometry/src/Crystal/SymmetryOperationSymbolParser.cpp
  Framework/Kernel/src/StringTokenizer.cpp
  Framework/Nexus/inc/MantidNexus/NexusIOHelper.h
  buildconfig/Jenkins/Conda/conda-build-recipes
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
  buildconfig/Jenkins/Conda/update-conda-recipes.sh
  installers/conda/linux/create_tarball.sh
  installers/conda/linux/qt.conf
  installers/conda/win/create_package.sh
  installers/conda/win/project.nsi
  qt/scientific_interfaces/ISISReflectometry/GUI/Common/IJobRunner.h
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsView.cpp
  qt/widgets/common/src/Batch/ExtractSubtrees.cpp
  qt/widgets/common/src/Batch/FindSubtreeRoots.cpp
Labels: High Priority, Bug

#33916 Save workspace name in workspacedisplay.model and allow renaming
  qt/python/mantidqt/mantidqt/widgets/workspacedisplay/matrix/model.py
  qt/python/mantidqt/mantidqt/widgets/workspacedisplay/matrix/presenter.py
Labels: High Priority, Bug, ISIS Team: Core, Found in Beta

#33918 BUGFIX: DensityOfStates .phonon import
  docs/source/release/v6.4.0/Indirect/Bugfixes/33918.rst
  scripts/Inelastic/dos/load_helper.py
Labels: High Priority, Bug

#33895 Fix deadlock with AlgorithmManager Python exports
  Framework/PythonInterface/mantid/api/src/Exports/AlgorithmManager.cpp
Labels: High Priority, Bug, ISIS Team: LSS

#33922 Fix display of bundled documentation in workbench
  installers/conda/common/common.sh
  installers/conda/common/qt.conf
  installers/conda/linux/create_tarball.sh
  installers/conda/linux/qt.conf
  installers/conda/osx/create_bundle.sh
  installers/conda/osx/qt.conf
  installers/conda/win/create_package.sh
Labels: High Priority, Bug

#33926 Move facility in drill test
  qt/python/mantidqtinterfaces/mantidqtinterfaces/drill/test/DrillTest.py
Labels: Bug, ILL Team

#33906 update manual tests for indirect inelastic
  dev-docs/source/Testing/IndirectInelastic/IndirectInelasticAcceptanceTests.rst
Labels: Indirect Inelastic, Documentation

#33921 Fix error when copying spectrum from ragged workspace
  docs/source/release/v6.4.0/Workbench/Bugfixes/33905.rst
  qt/python/mantidqt/mantidqt/widgets/workspacedisplay/matrix/presenter.py
  qt/python/mantidqt/mantidqt/widgets/workspacedisplay/matrix/test/test_matrixworkspacedisplay_presenter.py
  qt/python/mantidqt/mantidqt/widgets/workspacedisplay/test/test_workspacedisplay_view.py
Labels: Bug, ISIS Team: Core

#33919 Fix muon change instrument crash
  docs/source/release/v6.4.0/Muon/MA_FDA/Bugfixes/33890.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/results_tab_widget/results_tab_presenter.py
  qt/python/mantidqtinterfaces/test/Muon/results_tab_widget/results_tab_presenter_test.py
Labels: Bug, ISIS Team: Spectroscopy

#33876 Add `python.templates.directory` to config service paths
  Framework/Kernel/src/ConfigService.cpp
  docs/source/interfaces/general/Fit Script Generator.rst
Labels: Bug, ISIS Team: Core

#33902 fixed missing unsubscribe in muon GUI's
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/FrequencyDomainAnalysis/frequency_domain_analysis.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/MuonAnalysis/muon_analysis_2.py
Labels: Bug, ISIS Team: Spectroscopy

#33936 Fix Deprecation Warnings from matplotlib
  qt/python/mantidqt/mantidqt/widgets/fitpropertybrowser/fitpropertybrowser.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/axestabwidget/presenter.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/axestabwidget/test/test_axestabwidgetpresenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenters/lineplots.py
  qt/python/mantidqt/mantidqt/widgets/test/test_fitpropertybrowser.py
Labels: High Priority, Bug

#33933 Improvements to reflectometry GUI manual testing instructions
  dev-docs/source/Testing/ReflectometryGUI/ReflectometryGUITests.rst
Labels: Documentation

#33928 Read EngDiff save location at runtime
  docs/source/release/v6.4.0/Diffraction/Engineering/Bugfixes/33877.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/calibration/model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/calibration/test/test_calib_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/focus/model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/focus/test/test_focus_model.py
Labels: Bug, Diffraction, ISIS Team: Diffraction, Found in Beta

#33931 Fix peak overlay and add peak action for 4D workspace in sliceviewer
  docs/source/release/v6.4.0/Workbench/SliceViewer/Bugfixes/33931.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/sliceinfo.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/test/test_peaksviewer_model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/test/test_peaksviewer_presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenters/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_sliceinfo.py
Labels: ISIS Team: Core

#33935 Fix plot options error for inset axes
  Framework/PythonInterface/mantid/plots/utility.py
  Framework/PythonInterface/test/python/mantid/plots/UtilityTest.py
  docs/source/release/v6.4.0/Workbench/Bugfixes/33915.rst
Labels: Bug, ISIS Team: Core

#33941 Fix slice viewer bug caused by switching to `Log` or `SymmetricLog` on masked data
  docs/source/release/v6.4.0/Workbench/SliceViewer/Bugfixes/33310.rst
  docs/source/release/v6.4.0/Workbench/SliceViewer/Bugfixes/33883.rst
  qt/python/mantidqt/CMakeLists.txt
  qt/python/mantidqt/mantidqt/widgets/colorbar/colorbar.py
  qt/python/mantidqt/mantidqt/widgets/colorbar/test/__init__.py
  qt/python/mantidqt/mantidqt/widgets/colorbar/test/test_colorbar.py
Labels: Bug, ISIS Team: Core

#33960 Move dropdown for group by sample in indirect energy transfer.
  qt/scientific_interfaces/Indirect/ISISEnergyTransfer.ui
Labels: Indirect Inelastic, ISIS Team: Spectroscopy

#33948 Fix problem on plots zooming out when plotting guess
  Framework/PythonInterface/mantid/plots/__init__.py
  Framework/PythonInterface/mantid/plots/mantidaxes.py
  Framework/PythonInterface/mantid/plots/utility.py
  Framework/PythonInterface/test/python/mantid/plots/mantidaxesTest.py
  qt/applications/workbench/workbench/plotting/figureinteraction.py
  qt/applications/workbench/workbench/plotting/test/test_figureinteraction.py
  qt/python/mantidqt/mantidqt/widgets/fitpropertybrowser/fitpropertybrowser.py
  qt/python/mantidqt/mantidqt/widgets/fitpropertybrowser/fitpropertybrowserplotinteraction.py
  qt/python/mantidqt/mantidqt/widgets/test/test_fitpropertybrowser.py
  qt/python/mantidqt/mantidqt/widgets/test/test_fitpropertybrowserplotinteraction.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/plot_widget/external_plotting/external_plotting_view.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/plot_widget/plotting_canvas/plotting_canvas_view.py
Labels: High Priority, Bug, ISIS Team: Diffraction

#33967 Main revision of Indirect Geometry release notes for v6.4.0
  docs/source/interfaces/indirect/Indirect Data Reduction.rst
  docs/source/release/v6.4.0/indirect_geometry.rst
Labels: Indirect Inelastic, Documentation

#33961 Main revision of Diffraction release notes for v6.4.0.
  docs/source/release/v6.4.0/Framework/Algorithms/Bugfixes/Used/33617_rebin2d_release_notes.rst
  docs/source/release/v6.4.0/diffraction.rst
  docs/source/release/v6.4.0/framework.rst
Labels: Diffraction, Documentation, ISIS Team: Diffraction

#33963 Change GroupBySampleChangerPosition to give no text for no samp_posn
  Framework/PythonInterface/plugins/algorithms/GroupBySampleChangerPosition.py
  Framework/PythonInterface/test/python/plugins/algorithms/GroupBySampleChangerPositionTest.py
Labels: Indirect Inelastic, ISIS Team: Spectroscopy

#33970 Fix unhandled exception if user file not found
  docs/source/release/v6.4.0/SANS/Bugfixes/33962.rst
  scripts/SANS/sans/gui_logic/models/async_workers/sans_run_tab_async.py
  scripts/SANS/sans/gui_logic/presenter/gui_state_director.py
  scripts/test/SANS/gui_logic/models/async_workers/test_beam_centre_async.py
  scripts/test/SANS/gui_logic/models/async_workers/test_sans_run_tab_async.py
Labels: High Priority, Bug, ISIS Team: LSS, Found in Beta

#33930 Replot resolution data in ISIS calibration when instrument changed
  docs/source/release/v6.4.0/Indirect/Bugfixes/33872.rst
  qt/scientific_interfaces/Indirect/ISISCalibration.cpp
  qt/scientific_interfaces/Indirect/ISISCalibration.h
  qt/scientific_interfaces/Indirect/IndirectTab.cpp
  qt/scientific_interfaces/Indirect/IndirectTab.h
Labels: Indirect Inelastic, ISIS Team: Spectroscopy

#33982 Tidy and revise 6.4 Framework Release Notes
  docs/source/release/v6.4.0/framework.rst
Labels: Documentation

#33984 Tidy and Revise v6.4 SANS Release Notes
  docs/source/release/v6.4.0/sans.rst
Labels: Documentation

#33981 Expose `getNumberDetectors` to python
  Framework/PythonInterface/mantid/geometry/src/Exports/Instrument.cpp
  Framework/PythonInterface/test/python/mantid/geometry/InstrumentTest.py
  docs/source/release/v6.4.0/Framework/Python/New_features/33981.rst
Labels: ISIS Team: Core

#33896 Bug in tridiagonal matrix inversion
  Framework/Kernel/src/Matrix.cpp
  Framework/Kernel/test/MatrixTest.h
  docs/source/release/v6.4.0/Framework/Kernel/Bugfixes/33896.rst
Labels: Bug

#33990 Fix crash on colorfill plot when more than one image sharing a color bar
  docs/source/release/v6.4.0/Workbench/Bugfixes/33990 FixErrorOnSavingPropertiesOnImagePlots.rst
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/imagestabwidget/presenter.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/imagestabwidget/test/test_imagestabwidgetpresenter.py
Labels: Bug, GUI, ISIS Team: Diffraction

#33975 Fix crash on adding user function to a plot with guess present
  Framework/CurveFitting/src/Functions/UserFunction.cpp
  docs/source/release/v6.4.0/Workbench/Bugfixes/33925.rst
  qt/python/mantidqt/mantidqt/widgets/fitpropertybrowser/fitpropertybrowserplotinteraction.py
  qt/python/mantidqt/mantidqt/widgets/test/test_fitpropertybrowserplotinteraction.py
Labels: Bug, ISIS Team: Diffraction

#33973 Fix crash on opening Discus algorithm dialog
  Framework/Algorithms/src/DiscusMultipleScatteringCorrection.cpp
  Framework/Algorithms/test/DiscusMultipleScatteringCorrectionTest.h
  docs/source/release/v6.4.0/Framework/Algorithms/Bugfixes/33973_FixCrashOnOpeningDiscusAlgDialog.rst
Labels: Bug, ISIS Team: Diffraction

#34007 Use .tar.xz as suffix for manylinux bundle
  buildconfig/Jenkins/Conda/conda-build-recipes
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
  installers/conda/linux/create_tarball.sh
Labels: High Priority, Bug

#33968 Prevent setting readLock on a workspace already locked
  docs/source/release/v6.4.0/Workbench/SliceViewer/Bugfixes/33882.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenters/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/views/view.py
Labels: Bug, ISIS Team: Core, Found in Beta
