Repository mantidproject/mantid, pull requests merged in 2022-01, with the labels that each got.

#33141 Fix Crash When Changing Tabs on MacOS
  docs/source/release/v6.3.0/muon.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/dock/dockable_tabs.py
Labels: Muon, macOS Only, ISIS Team: Spectroscopy, ISIS Team: LSS, Added during Sprint

#33151 Fix sliceviewer view tests that are failing locally
  qt/python/mantidqt/CMakeLists.txt
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_dataview.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_view.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/view.py
Labels: Maintenance, GUI

#33171 Fix a bug in what units were generated for G(r) files
  Framework/DataHandling/src/LoadPDFgetNFile.cpp
  Framework/DataHandling/test/LoadPDFgetNFileTest.h
  docs/source/release/v6.3.0/diffraction.rst
Labels: Bug, Diffraction, Powder

#33161 Ensure HKL labels within instrument view miniplot remain visble when zooming
  docs/source/release/v6.3.0/mantidworkbench.rst
  qt/widgets/instrumentview/CMakeLists.txt
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/MiniPlot.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/MiniPlotQwt.h
  qt/widgets/instrumentview/src/MiniPlotMpl.cpp
  qt/widgets/instrumentview/src/MiniPlotQwt.cpp
  qt/widgets/mplcpp/inc/MantidQtWidgets/MplCpp/Artist.h
  qt/widgets/mplcpp/inc/MantidQtWidgets/MplCpp/Axes.h
  qt/widgets/mplcpp/src/Axes.cpp
  qt/widgets/mplcpp/test/ArtistTest.h
  qt/widgets/mplcpp/test/AxesTest.h
Labels: GUI, ISIS Team: Core

#33159 Add 30 group texture option to EngDiff UI
  Testing/SystemTests/tests/framework/EnginXScriptTest.py
  Testing/SystemTests/tests/framework/reference/299080_engggui_focusing_output_ws_Texture30.nxs.md5
  docs/source/interfaces/diffraction/Engineering Diffraction.rst
  docs/source/release/v6.3.0/diffraction.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/calibration/test/test_calib_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/calibration/test/test_calib_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/cropping/cropping_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/cropping/cropping_widget.ui
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/focus/test/test_focus_model.py
  scripts/Engineering/EnggUtils.py
  scripts/Engineering/calib/ENGINX_Texture20_grouping.xml
  scripts/Engineering/calib/ENGINX_Texture30_grouping.xml
  scripts/Engineering/common/calibration_info.py
Labels: Diffraction, ISIS Team: Diffraction

#33177 Rename master to main in ReleaseChecklist documentation
  dev-docs/source/ReleaseChecklist.rst
Labels: Documentation, Maintenance

#33160 Add a Citation file to Mantid
  CITATION.cff
  README.md
  dev-docs/source/PatchReleaseChecklist.rst
  dev-docs/source/ReleaseChecklist.rst
Labels: ISIS Team: Core

#33179 Fix flaky test for EnggEstimateFocusedBackground
  Framework/PythonInterface/test/python/plugins/algorithms/EnggEstimateFocussedBackgroundTest.py
Labels: Diffraction, ISIS Team: Diffraction

#33180 Include Euphonic with win32 Python bundle
  Testing/SystemTests/tests/framework/SimulatedDensityOfStatesEuphonicPackaging.py
  buildconfig/CMake/Bootstrap.cmake
  docs/source/release/v6.3.0/framework.rst
  docs/source/release/v6.3.0/indirect_geometry.rst
Labels: ISIS Team: Spectroscopy, Windows Only

#33210 Create v6.4 skeleton release notes
  docs/source/release/index.rst
  docs/source/release/v6.4.0/diffraction.rst
  docs/source/release/v6.4.0/direct_geometry.rst
  docs/source/release/v6.4.0/framework.rst
  docs/source/release/v6.4.0/index.rst
  docs/source/release/v6.4.0/indirect_geometry.rst
  docs/source/release/v6.4.0/mantidworkbench.rst
  docs/source/release/v6.4.0/muon.rst
  docs/source/release/v6.4.0/reflectometry.rst
  docs/source/release/v6.4.0/sans.rst
  tools/release_generator/release.py
Labels: ISIS Team: Core

#33178 Introduce a TemporaryWorkingDirectory system test helper
  Testing/SystemTests/lib/systemtests/systemtesting.py
  Testing/SystemTests/tests/framework/HFIRBackgroundAPIv2.py
  Testing/SystemTests/tests/framework/HFIREffAPIv2.py
  Testing/SystemTests/tests/framework/HFIRReductionAPIv2.py
  Testing/SystemTests/tests/framework/HFIRTestsAPIv2.py
  Testing/SystemTests/tests/framework/HFIRTransAPIv2.py
Labels: High Priority, Windows Only

#33220 33218 fix IDA crash on spectra removal
  qt/scientific_interfaces/Indirect/IndirectFittingModel.cpp
Labels: High Priority, Bug, Indirect Inelastic, ISIS Team: Spectroscopy

#33205 Fix muon plotting rounding bug
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/plot_widget/plotting_canvas/plotting_canvas_view.py
Labels: Bug, ISIS Team: Spectroscopy

#33231 Muon TF asymmetry bug
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/plot_widget/plotting_canvas/plotting_canvas_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/plot_widget/plotting_canvas/plotting_canvas_view.py
  qt/python/mantidqtinterfaces/test/Muon/plotting_canvas/plotting_canvas_presenter_test.py
  qt/python/mantidqtinterfaces/test/Muon/plotting_canvas/plotting_canvas_view_test.py
Labels: High Priority, Bug, ISIS Team: Spectroscopy

#33217 Main cleanup of SANS & Reflectometry v6.3 release notes
  docs/source/interfaces/reflectometry/ISIS Reflectometry.rst
  docs/source/release/v6.3.0/reflectometry.rst
  docs/source/release/v6.3.0/sans.rst
Labels: Reflectometry, SANS, Documentation

#33242 rename single fitting button in IDA
  docs/source/release/v6.4.0/indirect_geometry.rst
  qt/scientific_interfaces/Indirect/IndirectFitPreviewPlot.ui
Labels: Indirect Inelastic, Maintenance, ISIS Team: Spectroscopy

#33216 Manually remove extra include/share directories from macOS bundle
  qt/applications/workbench/CMakeLists.txt
Labels: High Priority, Bug, macOS Only

#32933 CodeEditor auto-completion switch
  docs/source/release/v6.4.0/mantidworkbench.rst
  qt/applications/workbench/workbench/config/__init__.py
  qt/applications/workbench/workbench/plugins/editor.py
  qt/applications/workbench/workbench/widgets/settings/general/presenter.py
  qt/applications/workbench/workbench/widgets/settings/general/section_general.ui
  qt/applications/workbench/workbench/widgets/settings/general/test/test_general_settings.py
  qt/python/mantidqt/mantidqt/widgets/codeeditor/interpreter.py
  qt/python/mantidqt/mantidqt/widgets/codeeditor/multifileinterpreter.py
Labels: GUI, ILL Team

#33243 Fix error reporter
  Framework/Json/src/Json.cpp
  Framework/Json/test/JsonTest.h
  Framework/Kernel/test/ErrorReporterTest.h
Labels: High Priority, Bug, Found in Beta

#33233 Update indirect inelastic manual tests
  dev-docs/source/Testing/IndirectInelastic/IndirectInelasticAcceptanceTests.rst
Labels: Indirect Inelastic, Documentation, ISIS Team: Spectroscopy

#33203 Stop updating slicepoint when slider updated post spinbox changed
  docs/source/release/v6.3.0/33203_framework.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/dimensionwidget.py
Labels: ISIS Team: Core

#33256 Refactoring of Direct Geometry release notes for v6.3
  docs/source/release/v6.3.0/direct_geometry.rst
Labels: Direct Inelastic, Documentation, ISIS Team: Excitations/Vesuvio

#32876 Fix segfault when folding the pick tab in the instrument viewer
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.3.0/32876_mantidworkbench.rst
  docs/source/release/v6.3.0/mantidworkbench.rst
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/InstrumentWidget.h
  qt/widgets/instrumentview/src/InstrumentWidget.cpp
  qt/widgets/instrumentview/src/InstrumentWidgetPickTab.cpp
Labels: Bug

#33250 Bug - Superplot does not support mdworkspace
  qt/python/mantidqt/mantidqt/widgets/superplot/model.py
  qt/python/mantidqt/mantidqt/widgets/superplot/test/test_superplot_model.py
Labels: Bug, GUI

#33147 Set bin errors in CreateSimulationWorkspace
  Framework/DataHandling/src/CreateSimulationWorkspace.cpp
  Framework/DataHandling/test/CreateSimulationWorkspaceTest.h
  docs/source/release/v6.3.0/33147_Framework.rst
Labels: Single Crystal

#33209 Improve manual testing instructions for the refl gui
  dev-docs/source/Testing/ReflectometryGUI/ReflectometryGUITests.rst
Labels: Reflectometry, Documentation, ISIS Team: LSS

#33274 Refactoring 6.3 workbench release notes
  docs/source/release/v6.3.0/32876_mantidworkbench.rst
  docs/source/release/v6.3.0/33203_framework.rst
  docs/source/release/v6.3.0/framework.rst
  docs/source/release/v6.3.0/mantidworkbench.rst
Labels: Documentation, ISIS Team: Core

#33278 SANS: Catch KeyError from CSV parser
  docs/source/release/v6.3.0/33238_SANS.rst
  scripts/SANS/sans/gui_logic/presenter/run_tab_presenter.py
  scripts/test/SANS/gui_logic/test_run_tab_presenter.py
Labels: Bug, SANS, ISIS Team: LSS

#33259 Fix not being able to set z axis limits on linux
  docs/source/release/v6.3.0/30014_mantidworkbench.rst
  qt/applications/workbench/workbench/plotting/propertiesdialog.py
Labels: Bug, GUI, ISIS Team: LSS, Linux Only, Windows Only

#33253 Fix behaviour on ADS deletion of workspaces and peaks workspaces in sliceviewer
  docs/source/release/v6.3.0/33253_mantidworkbench.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/test/test_peaksviewer_peaksviewercollectionpresenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_presenter.py
Labels: High Priority, Bug, ISIS Team: Core

#33257 Refactored Indirect Geometry v6.3 release notes
  docs/source/interfaces/indirect/Indirect Simulation.rst
  docs/source/release/v6.3.0/indirect_geometry.rst
Labels: Indirect Inelastic, Documentation, ISIS Team: Spectroscopy

#33202 Main cleanup of Muon v 6.3 release notes
  docs/source/fitting/fitfunctions/ActivationK.rst
  docs/source/fitting/fitfunctions/ActivationmeV.rst
  docs/source/fitting/fitfunctions/DecoupAsymPowderMagLong.rst
  docs/source/fitting/fitfunctions/DecoupAsymPowderMagRot.rst
  docs/source/fitting/fitfunctions/MagneticOrderParameter.rst
  docs/source/fitting/fitfunctions/PowerLaw.rst
  docs/source/fitting/fitfunctions/SmoothTransition.rst
  docs/source/images/Muon_error_shading.png
  docs/source/release/v6.3.0/muon.rst
Labels: Muon, Documentation, ISIS Team: Spectroscopy

#33251 Fix crash on instrument viewer draw tab
  docs/source/release/v6.3.0/33251_mantidworkbench.rst
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/InstrumentWidgetMaskTab.h
  qt/widgets/instrumentview/src/InstrumentWidgetMaskTab.cpp
  qt/widgets/instrumentview/test/InstrumentWidget/InstrumentWidgetTest.h
  qt/widgets/instrumentview/test/InstrumentWidget/MockProjectionSurface.h
Labels: High Priority, Bug, GUI, ISIS Team: Diffraction

#33279 Workbench Logging: Remove logger channel on exit
  qt/widgets/common/src/MessageDisplay.cpp
Labels: Bug

#33268 Check for active ws name in fit results dict when updating tables post-fit in EngDiff UI
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/data_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/test/test_data_model.py
Labels: Diffraction, ISIS Team: Diffraction

#33288 Get correct extents for MDHisto roi cut exports in sliceviewer
  docs/source/release/v6.3.0/33288_mantidworkbench.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py
Labels: ISIS Team: Core

#33301 Add new loader for PSD event data for DNS at MLZ
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/BitStream.h
  Framework/DataHandling/inc/MantidDataHandling/LoadDNSEvent.h
  Framework/DataHandling/src/LoadDNSEvent.cpp
  Framework/DataHandling/test/LoadDNSEventTest.h
  Testing/Data/UnitTest/DNS_psd_150c_first_tube.mdat.md5
  docs/source/algorithms/LoadDNSEvent-v1.rst
  docs/source/release/v6.3.0/direct_geometry.rst
  instrument/DNS-PSD_Definition.xml
Labels: Framework

#33299 Various small fixes to the Engineering UI Fitting tab
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  qt/python/mantidqt/mantidqt/_common.sip
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/data_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/fitting_ads_observer.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/EngDiff_fitpropertybrowser.py
  qt/widgets/common/src/FitPropertyBrowser.cpp
Labels: ISIS Team: Diffraction

#32206 PolDiffILLReduction: TOF mode support
  Framework/DataHandling/inc/MantidDataHandling/LoadILLPolarizedDiffraction.h
  Framework/DataHandling/src/LoadILLPolarizedDiffraction.cpp
  Framework/DataHandling/test/LoadILLPolarizedDiffractionTest.h
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/D7AbsoluteCrossSections.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/PolDiffILLReduction.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/D7AbsoluteCrossSectionsTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/PolDiffILLReductionTest.py
  Testing/Data/SystemTest/ILL/D7/395639.nxs.md5
  Testing/Data/SystemTest/ILL/D7/395640.nxs.md5
  Testing/Data/SystemTest/ILL/D7/396017.nxs.md5
  Testing/Data/UnitTest/ILL/D7/395639.nxs.md5
  Testing/Data/UnitTest/ILL/D7/395639_reduced.nxs.md5
  Testing/Data/UnitTest/ILL/D7/396016.nxs.md5
  Testing/Data/UnitTest/ILL/D7/vanadium_xyz.nxs.md5
  Testing/SystemTests/tests/framework/D7AbsoluteCrossSectionsTest.py
  Testing/SystemTests/tests/framework/PolDiffILLReductionTest.py
  Testing/SystemTests/tests/framework/reference/ILL_D7_Powder_6p.nxs.md5
  Testing/SystemTests/tests/framework/reference/ILL_D7_Powder_XYZ.nxs.md5
  Testing/SystemTests/tests/framework/reference/ILL_D7_SingleCrystal_6p.nxs.md5
  Testing/SystemTests/tests/framework/reference/ILL_D7_SingleCrystal_XYZ.nxs.md5
  Testing/SystemTests/tests/framework/reference/ILL_D7_TOF_Z.nxs.md5
  docs/source/algorithms/D7AbsoluteCrossSections-v1.rst
  docs/source/algorithms/PolDiffILLReduction-v1.rst
  docs/source/diagrams/D7AbsoluteCrossSections-v1_wkflw.dot
  docs/source/diagrams/PolDiffILLReduction-v1_sample_wkflw.dot
  docs/source/diagrams/PolDiffILLReduction-v1_transmission_wkflw.dot
  docs/source/diagrams/PolDiffILLReduction-v1_vanadium_wkflw.dot
  docs/source/release/v6.3.0/32206_diffraction.rst
  docs/source/techniques/PolarisedDiffractionILL.rst
  instrument/D7_Definition.xml
  instrument/D7_Parameters.xml
  instrument/D7_YIG_calibration_TOF.xml
Labels: ILL Team

#33297 Fix error transposing 2D MDworkspaces in sliceviewer
  docs/source/release/v6.3.0/33297_mantidworkbench.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_presenter.py
Labels: ISIS Team: Core

#33309 Make coding standard changes from review
  qt/widgets/instrumentview/test/InstrumentWidget/InstrumentWidgetTest.h
  qt/widgets/instrumentview/test/InstrumentWidget/MockInstrumentWidgetMaskTab.h
Labels: ISIS Team: Diffraction

#33293 Bug in DrILL close event
  qt/python/mantidqtinterfaces/mantidqtinterfaces/drill/presenter/DrillSettingsPresenter.py
Labels: Bug, ILL Team

#33289 Bug in DrILL settings dialog
  qt/python/mantidqtinterfaces/mantidqtinterfaces/drill/presenter/DrillSettingsPresenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/drill/view/DrillSettingsDialog.py
Labels: Bug, ILL Team

#33287 Fixed ALC bug allowed decimal detector groupings
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.3.0/33283_muon.rst
  qt/scientific_interfaces/Muon/ALCDataLoadingPresenter.cpp
  qt/scientific_interfaces/Muon/test/ALCDataLoadingPresenterTest.h
Labels: Bug, ISIS Team: Spectroscopy

#33334 Add Warning of Restart Requirement to Project Recovery Settings
  docs/source/release/v6.3.0/33272_mantidworkbench.rst
  qt/applications/workbench/workbench/widgets/settings/general/section_general.ui
Labels: Bug, GUI, ISIS Team: LSS, Found in Beta

#33282 Allow Deletion of Empty Workspace Groups
  Framework/Algorithms/inc/MantidAlgorithms/DeleteWorkspace.h
  Framework/Algorithms/src/DeleteWorkspace.cpp
  Framework/Algorithms/src/DeleteWorkspaces.cpp
  Framework/Algorithms/test/DeleteWorkspaceTest.h
  Framework/Algorithms/test/DeleteWorkspacesTest.h
  docs/source/release/v6.3.0/33221_mantidworkbench.rst
Labels: Bug, Framework, GUI, ISIS Team: LSS

#33254 Main refactoring of v6.3 diffraction release notes
  docs/source/images/engggui_texture.png
  docs/source/release/v6.2.0/diffraction.rst
  docs/source/release/v6.3.0/diffraction.rst
Labels: Diffraction, Documentation, Powder, Single Crystal

#33314 Added release note and updated SHA
  docs/source/release/v6.3.0/MSlice_DirectGeometry.rst
  scripts/ExternalInterfaces/CMakeLists.txt
Labels: ISIS Team: Excitations/Vesuvio

#33294 Fix Canvas Colour Not Being Preserved by Script Generator
  docs/source/release/v6.3.0/33225_mantidworkbench.rst
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/__init__.py
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/axes.py
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/test/test_plotscriptgenerator.py
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/test/test_plotscriptgeneratoraxes.py
  qt/python/mantidqt/mantidqt/project/plotsloader.py
  qt/python/mantidqt/mantidqt/project/plotssaver.py
  qt/python/mantidqt/mantidqt/project/test/test_plotsloader.py
  qt/python/mantidqt/mantidqt/project/test/test_plotssaver.py
Labels: Bug, GUI, ISIS Team: LSS

#33343 Muon plots with fits on top of data
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/plot_widget/plotting_canvas/plotting_canvas_view.py
Labels: ISIS Team: Spectroscopy

#33300 Major refactor of 6.3 framework release notes
  docs/source/release/v6.3.0/33147_Framework.rst
  docs/source/release/v6.3.0/33173_Framework.rst
  docs/source/release/v6.3.0/framework.rst
Labels: Documentation, Framework

#33292 Update muon testing docs
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon Analysis Unscripted Testing Guide.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_ALC.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_ARGUS.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_Analysis_MUSR.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_Analysis_PSI.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_Analysis_test_group_1_general.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_Analysis_test_group_2_fitting.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_Analysis_test_group_3_results.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_Analysis_test_group_4_FDAG.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_EMU.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_FDA.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_HIFI.rst
Labels: Documentation, ISIS Team: Spectroscopy

#33291 Add usage tracking to Mantid-Help
  qt/applications/workbench/workbench/app/mainwindow.py
Labels: GUI

#33342 Fix Symmetrise failing on workspaces with different bin width
  Framework/PythonInterface/plugins/algorithms/Symmetrise.py
  Framework/PythonInterface/test/python/plugins/algorithms/SymmetriseTest.py
  docs/source/release/v6.3.0/33339_indirect_geometry.rst
Labels: Bug, Indirect Inelastic, ISIS Team: Spectroscopy

#33307 Add parent to Engineering UI when loaded from a project
  docs/source/release/v6.4.0/diffraction.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/engineering_diffraction_io.py
Labels: ISIS Team: Diffraction

#33329 Fix Tiny About Workbench Comboboxes on macOS
  docs/source/release/v6.3.0/33265_mantidworkbench.rst
  qt/applications/workbench/workbench/widgets/about/view.py
Labels: Bug, GUI, macOS Only

#33335 Handle OSError exceptions when trying to remove recovery checkpoints
  docs/source/release/v6.3.0/33335_mantidworkbench.rst
  qt/applications/workbench/workbench/app/mainwindow.py
  qt/applications/workbench/workbench/projectrecovery/projectrecovery.py
  qt/applications/workbench/workbench/projectrecovery/test/test_projectrecovery.py
  qt/applications/workbench/workbench/test/test_mainwindow.py
Labels: Bug, GUI

#33347 Muon reselect fits in results tab
  docs/source/release/v6.3.0/33315_muon.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/results_tab_widget/results_tab_presenter.py
  qt/python/mantidqtinterfaces/test/Muon/results_tab_widget/results_tab_presenter_test.py
Labels: ISIS Team: Spectroscopy

#33344 Change default mechanics for scaling in IndirectCalibration
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectCalibration.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/IndirectCalibrationTest.py
  docs/source/release/v6.3.0/33212_indirect_geometry.rst
  qt/scientific_interfaces/Indirect/ISISCalibration.cpp
Labels: Indirect Inelastic, ISIS Team: Spectroscopy

#33348 Update to v6.3 release notes
  docs/source/release/v6.3.0/30014_mantidworkbench.rst
  docs/source/release/v6.3.0/32206_diffraction.rst
  docs/source/release/v6.3.0/33221_mantidworkbench.rst
  docs/source/release/v6.3.0/33225_mantidworkbench.rst
  docs/source/release/v6.3.0/33238_SANS.rst
  docs/source/release/v6.3.0/33251_mantidworkbench.rst
  docs/source/release/v6.3.0/33253_mantidworkbench.rst
  docs/source/release/v6.3.0/33272_mantidworkbench.rst
  docs/source/release/v6.3.0/33277_Framework.rst
  docs/source/release/v6.3.0/33283_muon.rst
  docs/source/release/v6.3.0/33288_mantidworkbench.rst
  docs/source/release/v6.3.0/33296_muon.rst
  docs/source/release/v6.3.0/33297_mantidworkbench.rst
  docs/source/release/v6.3.0/MSlice_DirectGeometry.rst
  docs/source/release/v6.3.0/diffraction.rst
  docs/source/release/v6.3.0/direct_geometry.rst
  docs/source/release/v6.3.0/framework.rst
  docs/source/release/v6.3.0/indirect_geometry.rst
  docs/source/release/v6.3.0/mantidworkbench.rst
  docs/source/release/v6.3.0/muon.rst
  docs/source/release/v6.3.0/sans.rst
  docs/source/workbench/instrumentviewer.rst
Labels: Diffraction, SANS, Documentation, Framework, ISIS Team: Spectroscopy, ISIS Team: Diffraction, ISIS Team: Core, ISIS Team: Excitations/Vesuvio

#33352 Check for valid x/y before passing event to add_peak
  docs/source/release/v6.3.0/33352_mantidworkbench.rst
  qt/python/mantidqt/mantidqt/widgets/fitpropertybrowser/mouse_state_machine.py
Labels: Bug, ISIS Team: Core

#33360 Sync muon frequency plots
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/FrequencyDomainAnalysis/plot_widget/dual_plot_maxent_pane/dual_plot_maxent_pane_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/FrequencyDomainAnalysis/plot_widget/frequency_analysis_plot_widget.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/FrequencyDomainAnalysis/plot_widget/plot_freq_fit_pane_presenter.py
  qt/python/mantidqtinterfaces/test/Muon/dual_plot_maxent_pane/dual_plot_maxent_pane_presenter_test.py
  qt/python/mantidqtinterfaces/test/Muon/plot_fit_panes/plot_freq_fit_pane_presenter_test.py
  qt/python/mantidqtinterfaces/test/Muon/plot_widget/frequency_analysis_plot_widget_test.py
Labels: ISIS Team: Spectroscopy

#33346 Stop rectangle ROI using x/y data from event outside colorfill axes when ROI resized/moved
  docs/source/release/v6.3.0/33346_mantidworkbench.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/lineplots.py
Labels: ISIS Team: Core

#33351 Fix Crash when Using Invalid Files on ConvertAxesToRealSpace
  Framework/Algorithms/src/ConvertAxesToRealSpace.cpp
  Framework/Algorithms/test/ConvertAxesToRealSpaceTest.h
  docs/source/release/v6.3.0/32434_framework.rst
Labels: Bug, Framework, ISIS Team: LSS

#32883 Direct ILL absolute unit normalisation
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/DirectILLReduction.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/DirectILLReductionTest.py
  docs/source/release/v6.3.0/32883_direct_geometry.rst
Labels: Bug, Direct Inelastic, ILL Team

#33368 muon instrument changed warning
  docs/source/release/v6.3.0/33365_muon.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/load_file_widget/presenter.py
  qt/python/mantidqtinterfaces/test/Muon/load_file_widget/loadfile_presenter_single_file_test.py
Labels: ISIS Team: Spectroscopy

#33364 Update to v6.3 release notes
  docs/source/interfaces/indirect/Indirect Data Reduction.rst
  docs/source/release/v6.3.0/33212_indirect_geometry.rst
  docs/source/release/v6.3.0/33265_mantidworkbench.rst
  docs/source/release/v6.3.0/33315_muon.rst
  docs/source/release/v6.3.0/33335_mantidworkbench.rst
  docs/source/release/v6.3.0/33336_mantidworkbench.rst
  docs/source/release/v6.3.0/33339_indirect_geometry.rst
  docs/source/release/v6.3.0/33349_mantidworkbench.rst
  docs/source/release/v6.3.0/indirect_geometry.rst
  docs/source/release/v6.3.0/mantidworkbench.rst
  docs/source/release/v6.3.0/muon.rst
  docs/source/workbench/instrumentviewer.rst
Labels: Documentation, ISIS Team: Spectroscopy, ISIS Team: Core

#33373 Fix LoadNXSPE incorrect detector size
  Framework/DataHandling/src/LoadNXSPE.cpp
  docs/source/release/v6.3.0/33373_direct_geometry.rst
Labels: Bug, Direct Inelastic, ISIS Team: Spectroscopy

#33371 Add comment to RebinToWorkspace documentation
  docs/source/algorithms/RebinToWorkspace-v1.rst
Labels: Maintenance

#33374 Plot script facecolor to hex
  Framework/PythonInterface/mantid/plots/__init__.py
  Framework/PythonInterface/mantid/plots/datafunctions.py
  Framework/PythonInterface/mantid/plots/legend.py
  Framework/PythonInterface/mantid/plots/utility.py
  Framework/PythonInterface/test/python/mantid/plots/mantidaxesTest.py
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/__init__.py
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/axes.py
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/figure.py
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/legend.py
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/test/test_plotscriptgenerator.py
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/test/test_plotscriptgeneratoraxes.py
  qt/applications/workbench/workbench/plotting/test/test_figureinteraction.py
  qt/applications/workbench/workbench/plotting/toolbar.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/colorselector.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/curvestabwidget/__init__.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/curvestabwidget/test/test_curvestabwidgetpresenter.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/test/test_apply_all_properties.py
  qt/python/mantidqt/mantidqt/widgets/waterfallplotfillareadialog/presenter.py
Labels: ISIS Team: Core

#33378 Allow ISISCalibration to set defaults for range from workspaces if date is outside of instrument range.
  docs/source/release/v6.3.0/33267_indirect_geometry.rst
  qt/scientific_interfaces/Indirect/ISISCalibration.cpp
Labels: Bug, Indirect Inelastic, ISIS Team: Spectroscopy

#33350 Remove last modified dates from algorithm documentation pages
  docs/source/conf.py
  docs/source/release/v6.3.0/33349_framework.rst
  docs/sphinxext/mantiddoc/directives/sourcelink.py
  docs/sphinxext/mantiddoc/tools/git_last_modified.py
Labels: Documentation

#33359 Improve Dev Docs for Multithreading
  dev-docs/source/MultiThreadingInAlgorithms.rst
  dev-docs/source/MultiThreadingInMantid.rst
Labels: Documentation, ISIS Team: LSS

#33395 Fixed crash in Absorption Corrections Tab in Indirect
  qt/scientific_interfaces/Indirect/ApplyAbsorptionCorrections.cpp
Labels: High Priority, Indirect Inelastic, ISIS Team: Spectroscopy, Absorption Corrections, Reported By User

#33401 Fix generation of doc source links on windows
  docs/sphinxext/mantiddoc/directives/sourcelink.py
Labels: High Priority, Documentation

#33403 Add a Historgram validation check to Indirect Absorption Corrections
  docs/source/interfaces/indirect/Indirect Corrections.rst
  docs/source/release/v6.3.0/33403_indirect_geometry.rst
  qt/scientific_interfaces/Indirect/ApplyAbsorptionCorrections.cpp
  qt/scientific_interfaces/Indirect/ApplyAbsorptionCorrections.h
Labels: Indirect Inelastic, ISIS Team: Spectroscopy, Absorption Corrections

#33398 Minor release note edits from ISIS diffraction team
  docs/source/release/v6.3.0/33398_framework.rst
  docs/source/release/v6.3.0/diffraction.rst
Labels: ISIS Team: Diffraction

#33358 Add Breadcrumb to user docs
  docs/source/_templates/navbar.html
  docs/source/conf-qthelp.py
Labels: Documentation

#33363 Hide axes labels and ticks of colorfill axes when lineplots enabled in sliceviewer
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/lineplots.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_lineplots.py
Labels: Bug, ISIS Team: Core

#33317 Update Inspect bg plot when parameters changed in EngDiff UI fitting tab
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/data_model.py
Labels: ISIS Team: Diffraction

#33399 Fix package name for Indirect Bayes Routines
  buildconfig/CMake/Bootstrap.cmake
  docs/source/release/v6.3.0/33399_indirect_geometry.rst
  scripts/Inelastic/IndirectImport.py
  scripts/Inelastic/QLdata_win64.cp38-win_amd64.pyd
  scripts/Inelastic/QLres_win64.cp38-win_amd64.pyd
  scripts/Inelastic/QLse_win64.cp38-win_amd64.pyd
  scripts/Inelastic/Quest_win64.cp38-win_amd64.pyd
  scripts/Inelastic/ResNorm_win64.cp38-win_amd64.pyd
  scripts/Inelastic/cp27/QLdata_win64.pyd
  scripts/Inelastic/cp27/QLres_win64.pyd
  scripts/Inelastic/cp27/QLse_win64.pyd
  scripts/Inelastic/cp27/Quest_win64.pyd
  scripts/Inelastic/cp27/ResNorm_win64.pyd
  scripts/Inelastic/cp27/cylabs_win64.pyd
  scripts/Inelastic/cp27/muscat_win64.pyd
  scripts/Inelastic/cylabs_lnx64.so
  scripts/Inelastic/cylabs_win64.cp38-win_amd64.pyd
  scripts/Inelastic/fltabs_lnx64.so
  scripts/Inelastic/muscat_lnx64.so
  scripts/Inelastic/muscat_win64.cp38-win_amd64.pyd
Labels: High Priority, Bug, Indirect Inelastic
