Repository mantidproject/mantid, pull requests merged in 2022-08, with the labels that each got.

#34236 Visual Indication for selected ROI and implement delete key
  qt/python/mantidqt/mantidqt/widgets/regionselector/presenter.py
  qt/python/mantidqt/mantidqt/widgets/regionselector/test/test_regionselector_presenter.py
  qt/python/mantidqt/mantidqt/widgets/regionselector/view.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenters/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_base_presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/views/dataview.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/views/dataviewsubscriber.py
Labels: Reflectometry, ISIS Team: LSS

#34247 Link preview and batch presenters in refl GUI
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/IPreviewPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/IPreviewView.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/QtPreviewView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/QtPreviewView.h
  qt/scientific_interfaces/ISISReflectometry/test/Batch/BatchPresenterTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/MockPreviewPresenter.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/MockPreviewView.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/PreviewPresenterTest.h
Labels: Reflectometry, GUI, ISIS Team: LSS

#34239 Reflectometry Update Angle button
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/IPreviewView.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewWidget.ui
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/QtPreviewView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/QtPreviewView.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/MockPreviewView.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/PreviewPresenterTest.h
Labels: Reflectometry, ISIS Team: LSS

#34230 Allow cmake to configure for a docs-only or workbench-only build
  CMakeLists.txt
  Framework/Kernel/src/Memory.cpp
  buildconfig/CMake/BundleOSXConda.cmake
  buildconfig/CMake/CommonSetup.cmake
  buildconfig/CMake/MSVCSetup.cmake
  docs/CMakeLists.txt
  qt/applications/workbench/CMakeLists.txt
  qt/widgets/common/src/AlgorithmDialog.cpp
Labels: ISIS Team: Core

#34089 Fix Save Project after opening multiple mantid instances
  docs/source/release/v6.5.0/Workbench/Bugfixes/34089.rst
  qt/applications/workbench/workbench/app/mainwindow.py
  qt/applications/workbench/workbench/config/test/test_user.py
  qt/applications/workbench/workbench/config/user.py
  qt/applications/workbench/workbench/plugins/editor.py
  qt/applications/workbench/workbench/utils/recentlyclosedscriptsmenu.py
  qt/applications/workbench/workbench/widgets/about/presenter.py
  qt/applications/workbench/workbench/widgets/settings/general/presenter.py
  qt/applications/workbench/workbench/widgets/settings/general/test/test_general_settings.py
  qt/applications/workbench/workbench/widgets/settings/model.py
  qt/applications/workbench/workbench/widgets/settings/test/test_settings_model.py
  qt/python/mantidqt/mantidqt/dialogs/errorreports/report.py
  qt/python/mantidqt/mantidqt/project/project.py
  qt/python/mantidqt/mantidqt/widgets/codeeditor/multifileinterpreter.py
  qt/python/mantidqt/mantidqt/widgets/messagedisplay.py
  qt/python/mantidqt/mantidqt/widgets/saveprojectdialog/test/test_saveprojectdialog.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/HFIR_4Circle_Reduction/reduce4circleGUI.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/reduction_application.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/reduction_gui/settings/application_settings.py
  scripts/Interface/ui/sans_isis/run_selector_widget.py
Labels: Bug, ISIS Team: Core

#34248 Replaced float comparison with numpy iclose
  scripts/Inelastic/CrystalField/fitting.py
  scripts/test/CrystalFieldMultiSiteTest.py
Labels: Maintenance, ISIS Team: Excitations/Vesuvio

#34266 Fix workbench startup test after removing custom MantidWorkbench targets
  Testing/SystemTests/tests/qt/WorkbenchStartupTest.py
Labels: Bug, ISIS Team: Core

#34244 Added check for ties in free parameter detection in the CEF two step fitting
  docs/source/release/v6.5.0/Direct_Geometry/CrystalField/Bugfixes/34244.rst
  scripts/Inelastic/CrystalField/fitting.py
Labels: Bug, ISIS Team: Excitations/Vesuvio

#34246 Added alternative option for gofit installation to CEF docs
  docs/source/interfaces/direct/Crystal Field Python Interface.rst
Labels: Documentation, ISIS Team: Excitations/Vesuvio

#34200 Crate SQE fit functions and add to ConvFit
  Framework/CurveFitting/CMakeLists.txt
  Framework/CurveFitting/inc/MantidCurveFitting/Functions/ChudleyElliotSQE.h
  Framework/CurveFitting/inc/MantidCurveFitting/Functions/FickDiffusionSQE.h
  Framework/CurveFitting/inc/MantidCurveFitting/Functions/HallRossSQE.h
  Framework/CurveFitting/src/Functions/ChudleyElliotSQE.cpp
  Framework/CurveFitting/src/Functions/FickDiffusionSQE.cpp
  Framework/CurveFitting/src/Functions/HallRossSQE.cpp
  Framework/CurveFitting/test/Functions/ChudleyElliotSQETest.h
  Framework/CurveFitting/test/Functions/FickDiffusionSQETest.h
  Framework/CurveFitting/test/Functions/HallRossSQETest.h
  docs/source/fitting/fitfunctions/ChudleyElliotSQE.rst
  docs/source/fitting/fitfunctions/FickDiffusionSQE.rst
  docs/source/fitting/fitfunctions/HallRossSQE.rst
  docs/source/release/v6.5.0/Indirect/New_features/34190.rst
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisConvFitTab.cpp
  qt/scientific_interfaces/Indirect/IndirectFunctionBrowser/ConvFunctionModel.cpp
  qt/scientific_interfaces/Indirect/IndirectFunctionBrowser/ConvFunctionModel.h
  qt/scientific_interfaces/Indirect/IndirectFunctionBrowser/ConvTypes.cpp
  qt/scientific_interfaces/Indirect/IndirectFunctionBrowser/ConvTypes.h
Labels: Indirect Inelastic, ISIS Team: Spectroscopy

#34277 Remove legacy macOS startup executable
  dev-docs/source/UserSupport.rst
  installers/conda/common/common.sh
  installers/conda/osx/BundleExecutable
Labels: Bug, macOS Only, ISIS Team: Core

#34263 Notify region changed when region is deleted
  qt/python/mantidqt/mantidqt/widgets/regionselector/presenter.py
  qt/python/mantidqt/mantidqt/widgets/regionselector/test/test_regionselector_presenter.py
Labels: Reflectometry, ISIS Team: LSS

#34264 Support sphere in SetSample
  Framework/DataHandling/inc/MantidDataHandling/SetSample.h
  Framework/DataHandling/src/SetSample.cpp
  Framework/DataHandling/test/SetSampleTest.h
  docs/source/algorithms/SetSample-v1.rst
  docs/source/release/v6.5.0/Framework/Algorithms/New_features/32892.rst
Labels: Diffraction, ISIS Team: Diffraction

#34281 Extend workbench system test process timeout
  Testing/SystemTests/tests/qt/WorkbenchStartupTest.py
Labels: ISIS Team: Core, Windows Only

#34282 Cannot open slice viewer bug
  Testing/SystemTests/tests/qt/SliceViewerIntegrationTest.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_dataview.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/views/dataview.py
Labels: High Priority, Bug

#34276 GroupToXResolution documentation figures fix
  docs/source/algorithms/GroupToXResolution-v1.rst
  docs/source/release/v6.5.0/Framework/Algorithms/Bugfixes/34273.rst
Labels: Bug, Documentation, ILL Team

#34253 Clear plots if processing fails in preview tab
  qt/python/mantidqt/mantidqt/widgets/regionselector/presenter.py
  qt/python/mantidqt/mantidqt/widgets/regionselector/test/test_regionselector_presenter.py
  qt/python/mantidqt/mantidqt/widgets/regionselector/view.py
  qt/scientific_interfaces/ISISReflectometry/GUI/Common/IJobManager.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewJobManager.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/MockPlotPresenter.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/PreviewJobManagerTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/PreviewPresenterTest.h
  qt/scientific_interfaces/ISISReflectometry/test/ReflMockObjects.h
  qt/widgets/plotting/inc/MantidQtWidgets/Plotting/PlotWidget/PlotModel.h
  qt/widgets/plotting/inc/MantidQtWidgets/Plotting/PlotWidget/PlotPresenter.h
  qt/widgets/plotting/src/PlotWidget/PlotModel.cpp
  qt/widgets/plotting/src/PlotWidget/PlotPresenter.cpp
  qt/widgets/plotting/test/PlotWidget/PlotModelTest.h
  qt/widgets/regionselector/inc/MantidQtWidgets/RegionSelector/IRegionSelector.h
  qt/widgets/regionselector/inc/MantidQtWidgets/RegionSelector/RegionSelector.h
  qt/widgets/regionselector/src/RegionSelector.cpp
  qt/widgets/regionselector/test/MockRegionSelector.h
Labels: Reflectometry, ISIS Team: LSS

#34285 Use PROJ_MATRIX_LOG_NAME for MDH
  docs/source/release/v6.5.0/Workbench/SliceViewer/Bugfixes/34285.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py
Labels: Bug

#34284 Correct EigenJacobian and remove GSL from JacobianImpl1
  Framework/CurveFitting/CMakeLists.txt
  Framework/CurveFitting/inc/MantidCurveFitting/EigenJacobian.h
  Framework/CurveFitting/inc/MantidCurveFitting/FuncMinimizers/TrustRegionMinimizer.h
  Framework/CurveFitting/inc/MantidCurveFitting/GSLFunctions.h
  Framework/CurveFitting/src/FuncMinimizers/TrustRegionMinimizer.cpp
  Framework/CurveFitting/src/GSLFunctions.cpp
  Framework/CurveFitting/test/EigenJacobianTest.h
  Framework/CurveFitting/test/EigenToGSLTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: ISIS Team: Excitations/Vesuvio

#34289 Add checkbox to include row outputs in autosave
  docs/source/release/v6.5.0/Reflectometry/New_features/34289.rst
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchJobManager.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchJobManager.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/IBatchJobManager.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/ISavePresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/ISaveView.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/QtSaveView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/QtSaveView.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/SavePresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/SavePresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/SaveWidget.ui
  qt/scientific_interfaces/ISISReflectometry/test/Batch/BatchJobManagerWorkspacesTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Batch/BatchPresenterTest.h
  qt/scientific_interfaces/ISISReflectometry/test/ReflMockObjects.h
  qt/scientific_interfaces/ISISReflectometry/test/Save/MockSaveView.h
  qt/scientific_interfaces/ISISReflectometry/test/Save/SavePresenterTest.h
Labels: Reflectometry, ISIS Team: LSS

#34288 Ignore reduction type when not applicable
  docs/source/release/v6.5.0/Reflectometry/Bugfixes/34288.rst
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/RowProcessingAlgorithm.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/ExperimentWidget.ui
  qt/scientific_interfaces/ISISReflectometry/Reduction/ReductionType.h
  qt/scientific_interfaces/ISISReflectometry/TestHelpers/ModelCreationHelper.cpp
  qt/scientific_interfaces/ISISReflectometry/TestHelpers/ModelCreationHelper.h
  qt/scientific_interfaces/ISISReflectometry/test/Batch/RowProcessingAlgorithmTest.h
Labels: Reflectometry, ISIS Team: LSS

#34261 Notify Batch Presenter on Preview Apply
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchJobManager.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/IBatchPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/ExperimentPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/ExperimentPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/IExperimentPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/IPreviewModel.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/IPreviewPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/IPreviewView.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewModel.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewModel.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewWidget.ui
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/QtPreviewView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/QtPreviewView.h
  qt/scientific_interfaces/ISISReflectometry/Reduction/Batch.cpp
  qt/scientific_interfaces/ISISReflectometry/Reduction/CMakeLists.txt
  qt/scientific_interfaces/ISISReflectometry/Reduction/Experiment.cpp
  qt/scientific_interfaces/ISISReflectometry/Reduction/Experiment.h
  qt/scientific_interfaces/ISISReflectometry/Reduction/LookupRow.cpp
  qt/scientific_interfaces/ISISReflectometry/Reduction/LookupRow.h
  qt/scientific_interfaces/ISISReflectometry/Reduction/LookupTable.cpp
  qt/scientific_interfaces/ISISReflectometry/Reduction/LookupTable.h
  qt/scientific_interfaces/ISISReflectometry/Reduction/RowExceptions.h
  qt/scientific_interfaces/ISISReflectometry/TestHelpers/ModelCreationHelper.cpp
  qt/scientific_interfaces/ISISReflectometry/TestHelpers/ModelCreationHelper.h
  qt/scientific_interfaces/ISISReflectometry/test/Batch/BatchJobManagerProcessingTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Batch/BatchPresenterTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/MockPreviewModel.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/MockPreviewPresenter.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/PreviewModelTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/PreviewPresenterTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Reduction/LookupTableTest.h
  qt/scientific_interfaces/ISISReflectometry/test/ReflMockObjects.h
Labels: Reflectometry, ISIS Team: LSS

#34260 Fix excessive text elision workbench data view
  docs/source/release/v6.5.0/Workbench/Bugfixes/34260.rst
  qt/python/mantidqt/CMakeLists.txt
  qt/python/mantidqt/mantidqt/widgets/workspacedisplay/matrix/delegate.py
  qt/python/mantidqt/mantidqt/widgets/workspacedisplay/matrix/presenter.py
  qt/python/mantidqt/mantidqt/widgets/workspacedisplay/matrix/test/test_matrixworkspacedisplay_delegate.py
  qt/python/mantidqt/mantidqt/widgets/workspacedisplay/matrix/test/test_matrixworkspacedisplay_presenter.py
  qt/python/mantidqt/mantidqt/widgets/workspacedisplay/matrix/view.py
Labels: Bug, ISIS Team: Core

#34291 Update GSL to v2.7
  docs/source/release/v6.5.0/Framework/New_features/33337.rst
  docs/source/release/v6.5.0/framework.rst
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: ISIS Team: Core

#34292 Fix SHELX format in SaveReflections
  Framework/PythonInterface/plugins/algorithms/SaveReflections.py
  Framework/PythonInterface/test/python/plugins/algorithms/SaveReflectionsTest.py
  Testing/Data/UnitTest/shelx_format.hkl.md5
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction

#34296 Fix windows packaging
  installers/conda/win/create_package.sh
Labels: High Priority, Bug, ISIS Team: Core, Windows Only, Added during Sprint

#34297 Add unit tests for method notifyPreviewApplyRequested
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/ExperimentPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewModel.cpp
  qt/scientific_interfaces/ISISReflectometry/Reduction/LookupRow.cpp
  qt/scientific_interfaces/ISISReflectometry/Reduction/LookupRow.h
  qt/scientific_interfaces/ISISReflectometry/Reduction/PreviewRow.cpp
  qt/scientific_interfaces/ISISReflectometry/Reduction/PreviewRow.h
  qt/scientific_interfaces/ISISReflectometry/test/Experiment/ExperimentPresenterTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Reduction/LookupTableTest.h
Labels: Reflectometry, ISIS Team: LSS

#34307 Update set up instructions for CLion on linux
  dev-docs/source/GettingStarted/GettingStartedCondaLinux.rst
Labels: Documentation

#34271 Skip Sum Banks Algo for Linear detector
  qt/scientific_interfaces/ISISReflectometry/Common/CMakeLists.txt
  qt/scientific_interfaces/ISISReflectometry/Common/Detector.cpp
  qt/scientific_interfaces/ISISReflectometry/Common/Detector.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/IPreviewModel.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/IPreviewView.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewModel.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewModel.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/QtPreviewView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/QtPreviewView.h
  qt/scientific_interfaces/ISISReflectometry/test/CMakeLists.txt
  qt/scientific_interfaces/ISISReflectometry/test/Common/DetectorTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/MockPreviewModel.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/MockPreviewView.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/PreviewPresenterTest.h
Labels: Reflectometry, ISIS Team: LSS

#34283 Prevent Mantid crash when fitting Gaussian peaks for a CrystalFieldFunction
  Framework/API/inc/MantidAPI/IFunction.h
  Framework/API/src/IFunction.cpp
  Framework/CurveFitting/inc/MantidCurveFitting/Functions/CrystalFieldFunction.h
  Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp
  Framework/CurveFitting/test/Functions/CrystalFieldFunctionTest.h
  docs/source/release/v6.5.0/Direct_Geometry/CrystalField/Bugfixes/34283.rst
  scripts/test/CrystalFieldMultiSiteTest.py
Labels: Bug, Added during Sprint, ISIS Team: Excitations/Vesuvio

#34304 Include save rows checkbox in Save Batch output
  Testing/Data/UnitTest/ISISReflectometry/batch_with_save_rows_box.json.md5
  qt/scientific_interfaces/ISISReflectometry/GUI/Common/Decoder.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Common/Encoder.cpp
  qt/scientific_interfaces/ISISReflectometry/test/Common/CoderCommonTester.h
  qt/scientific_interfaces/ISISReflectometry/test/Common/DecoderTest.h
Labels: Reflectometry, ISIS Team: LSS
