Repository mantidproject/mantid, pull requests merged in 2022-12, with the labels that each got.

#34797 Pin pygments to fix cppcheck
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: High Priority, ISIS Team: Core

#34799 D16B: corrected wire order
  Framework/DataHandling/test/LoadILLSANSTest.h
  instrument/D16B_Definition.xml
Labels: Bug, SANS, ILL Team

#34810 Change links from svn to github
  dev-docs/source/WritingAnAlgorithm.rst
Labels: Documentation

#34748 Loader and reduction for Lagrange at ILL
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/LagrangeILLReduction.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/LagrangeILLReductionTest.py
  Testing/Data/UnitTest/ILL/IN1/012869.md5
  Testing/Data/UnitTest/ILL/IN1/012870.md5
  Testing/Data/UnitTest/ILL/IN1/012871.md5
  Testing/Data/UnitTest/ILL/IN1/012882.md5
  Testing/Data/UnitTest/ILL/IN1/012883.md5
  Testing/Data/UnitTest/ILL/IN1/012884.md5
  Testing/Data/UnitTest/ILL/IN1/correction-water-cu220-2020.txt.md5
  Testing/Data/UnitTest/ILL/LAGRANGE/012869.md5
  Testing/Data/UnitTest/ILL/LAGRANGE/012870.md5
  Testing/Data/UnitTest/ILL/LAGRANGE/012871.md5
  Testing/Data/UnitTest/ILL/LAGRANGE/012882.md5
  Testing/Data/UnitTest/ILL/LAGRANGE/012883.md5
  Testing/Data/UnitTest/ILL/LAGRANGE/012884.md5
  Testing/Data/UnitTest/ILL/LAGRANGE/correction-water-cu220-2020.txt.md5
  docs/source/algorithms/LagrangeILLReduction-v1.rst
  docs/source/release/v6.6.0/Direct_Geometry/General/New_features/34748.rst
  instrument/Facilities.xml
  qt/python/mantidqtinterfaces/mantidqtinterfaces/drill/model/configurations.py
Labels: ILL Team

#34777 Allow Preview Widgets to be Dockable
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/CMakeLists.txt
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/IPreviewDockedWidgets.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/IPreviewView.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewDockedWidgets.ui
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewWidget.ui
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/QtPreviewDockedWidgets.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/QtPreviewDockedWidgets.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/QtPreviewView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/QtPreviewView.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/MockPreviewDockedWidgets.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/MockPreviewView.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/PreviewPresenterTest.h
Labels: Reflectometry, GUI, ISIS Team: LSS

#34796 Fix bug SaveReflections with empty table
  Framework/PythonInterface/plugins/algorithms/SaveReflections.py
  Framework/PythonInterface/test/python/plugins/algorithms/SaveReflectionsTest.py
  docs/source/release/v6.6.0/Diffraction/Single_Crystal/Bugfixes/34796.rst
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction

#34779 Add peak picker to ALFView analysis plot
  qt/python/mantidqt/mantidqt/plotting/markers.py
  qt/scientific_interfaces/Direct/ALFAnalysisModel.cpp
  qt/scientific_interfaces/Direct/ALFAnalysisModel.h
  qt/scientific_interfaces/Direct/ALFAnalysisPresenter.cpp
  qt/scientific_interfaces/Direct/ALFAnalysisPresenter.h
  qt/scientific_interfaces/Direct/ALFAnalysisView.cpp
  qt/scientific_interfaces/Direct/ALFAnalysisView.h
  qt/scientific_interfaces/Direct/ALFInstrumentView.cpp
  qt/scientific_interfaces/Direct/ALFInstrumentView.h
  qt/scientific_interfaces/Direct/test/ALFAnalysisMocks.h
  qt/scientific_interfaces/Direct/test/ALFAnalysisModelTest.h
  qt/scientific_interfaces/Direct/test/ALFAnalysisPresenterTest.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/InstrumentWidget.h
  qt/widgets/instrumentview/src/InstrumentWidget.cpp
  qt/widgets/mplcpp/inc/MantidQtWidgets/MplCpp/PeakMarker.h
  qt/widgets/mplcpp/src/PeakMarker.cpp
  qt/widgets/plotting/inc/MantidQtWidgets/Plotting/PeakPicker.h
  qt/widgets/plotting/inc/MantidQtWidgets/Plotting/PreviewPlot.h
  qt/widgets/plotting/src/PeakPicker.cpp
  qt/widgets/plotting/src/PreviewPlot.cpp
Labels: Direct Inelastic, ISIS Team: Excitations/Vesuvio

#34813 Added tolerance in CEF tests for ResolutionModel
  scripts/test/CrystalFieldTest.py
Labels: ISIS Team: Core, Linux Only

#34793 Correct the image of SampleShapePlot on the MeshPlotHelp docs page
  docs/source/images/ShowSampleShape.png
Labels: Documentation, ISIS Team: Diffraction

#34805 Update Reflectometry algorithms to take optional polarization efficiencies workspace
  Framework/PythonInterface/plugins/algorithms/ReflectometryReductionOneLiveData.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISLoadAndProcess.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISLoadAndProcessTest.py
  Framework/Reflectometry/inc/MantidReflectometry/ReflectometryReductionOneAuto3.h
  Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp
  Framework/Reflectometry/test/ReflectometryReductionOneAuto3Test.h
Labels: Reflectometry, ISIS Team: LSS

#34819 Fix missing script from nightly pipeline
  buildconfig/Jenkins/Conda/package-standalone
Labels: High Priority, Bug, ISIS Team: Core

#34727 Reduce dependency on MatrixWorkspace in DiscusMultipleScatteringCorrection
  Framework/Algorithms/inc/MantidAlgorithms/DiscusMultipleScatteringCorrection.h
  Framework/Algorithms/src/DiscusMultipleScatteringCorrection.cpp
  Framework/Algorithms/test/DiscusMultipleScatteringCorrectionTest.h
Labels: ISIS Team: Diffraction

#34804 Remove Update Estimate button and reshuffle analysis widgets on ALFView
  qt/scientific_interfaces/Direct/ALFAnalysisPresenter.cpp
  qt/scientific_interfaces/Direct/ALFAnalysisPresenter.h
  qt/scientific_interfaces/Direct/ALFAnalysisView.cpp
  qt/scientific_interfaces/Direct/ALFAnalysisView.h
  qt/scientific_interfaces/Direct/ALFInstrumentView.cpp
  qt/scientific_interfaces/Direct/ALFView.cpp
  qt/scientific_interfaces/Direct/test/ALFAnalysisMocks.h
  qt/scientific_interfaces/Direct/test/ALFAnalysisPresenterTest.h
Labels: Direct Inelastic, ISIS Team: Excitations/Vesuvio

#34778 Remove error on running POLARIS focus twice
  Testing/SystemTests/tests/framework/ISIS_PowderPolarisTest.py
  docs/source/release/v6.6.0/Diffraction/Powder/Bugfixes/34778.rst
  scripts/Diffraction/isis_powder/routines/absorb_corrections.py
  scripts/Diffraction/isis_powder/routines/calibrate.py
  scripts/Diffraction/isis_powder/routines/common.py
  scripts/Diffraction/isis_powder/routines/focus.py
  scripts/Diffraction/isis_powder/test/ISISPowderCommonTest.py
Labels: Bug, ISIS Team: Diffraction

#34807 Fix problem with beam arrow not showing when sample shape loaded from file
  qt/python/mantidqt/mantidqt/plotting/sample_shape.py
  qt/python/mantidqt/mantidqt/plotting/test/test_sample_shape.py
Labels: Bug, ISIS Team: Diffraction

#34721 Prevent error on ALFView when not drawing miniplot
  qt/widgets/instrumentview/src/InstrumentWidgetPickTab.cpp
Labels: Bug, Direct Inelastic, ISIS Team: Excitations/Vesuvio

#34801 rework Nexus loadPropertyCommon to speedup MDE load times
  Framework/Kernel/src/PropertyNexus.cpp
  Framework/Kernel/test/PropertyNexusTest.h
  docs/source/release/v6.6.0/Framework/Kernel/34801_FixMDEWorkspaceLoadTimes
Labels: Framework, Patch Candidate

#34782 Increase sensitivity of markers and region handles
  docs/source/release/v6.6.0/Workbench/Bugfixes/34782.rst
  docs/source/release/v6.6.0/Workbench/InstrumentViewer/Bugfixes/34782.rst
  qt/python/mantidqt/mantidqt/plotting/markers.py
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/Shape2D.h
  qt/widgets/instrumentview/src/Shape2D.cpp
  qt/widgets/instrumentview/src/Shape2DCollection.cpp
Labels: Direct Inelastic, ISIS Team: Core, ISIS Team: Excitations/Vesuvio

#34149 D4 reduction basic workflow
  Framework/DataHandling/src/LoadILLDiffraction.cpp
  Framework/DataHandling/test/LoadILLDiffractionTest.h
  Framework/DataHandling/test/LoadILLTest.h
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/D4ILLReduction.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/D4ILLReductionTest.py
  Testing/Data/UnitTest/ILL/D4/387229.nxs.md5
  Testing/Data/UnitTest/ILL/D4/387230.nxs.md5
  docs/source/algorithms/D4ILLReduction-v1.rst
  docs/source/algorithms/LoadILLDiffraction-v1.rst
  docs/source/diagrams/D4ILLReduction-v1_wkflw.dot
  docs/source/release/v6.6.0/Diffraction/Powder/New_features/34149.rst
  instrument/D4C_Definition.xml
  instrument/D4C_Parameters.xml
Labels: Diffraction, ILL Team

#34839 Fix compiler error on Windows with Ninja
  Framework/Geometry/src/MDGeometry/MDBoxImplicitFunction.cpp
Labels: Windows Only

#34816 Fix summation error on instrument view and ALF view
  Testing/Data/UnitTest/ALF83743.raw.md5
  docs/source/release/v6.6.0/Workbench/InstrumentViewer/Bugfixes/34816.rst
  qt/scientific_interfaces/Direct/ALFInstrumentModel.cpp
  qt/scientific_interfaces/Direct/ALFInstrumentView.cpp
  qt/scientific_interfaces/Direct/ALFInstrumentWidget.h
  qt/scientific_interfaces/Direct/test/ALFInstrumentModelTest.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/Shape2D.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/Shape2DCollection.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/UnwrappedDetector.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/UnwrappedSurface.h
  qt/widgets/instrumentview/src/InstrumentWidgetPickTab.cpp
  qt/widgets/instrumentview/src/Shape2D.cpp
  qt/widgets/instrumentview/src/Shape2DCollection.cpp
  qt/widgets/instrumentview/src/UnwrappedDetector.cpp
  qt/widgets/instrumentview/src/UnwrappedSurface.cpp
Labels: Direct Inelastic, ISIS Team: Core, ISIS Team: Excitations/Vesuvio

#34764 Added axis editors on double click for the sliceviewer plot axis
  docs/source/release/v6.6.0/Workbench/SliceViewer/New_features/34608.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenters/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_presenter.py
Labels: GUI, ISIS Team: Core

#34848 AlignAndFocusPowderFromFilesTest.ChunkingCompare system test stability
  Testing/SystemTests/tests/framework/AlignAndFocusPowderFromFilesTest.py
Labels: Bug, Diffraction, Powder

#34859 Catch exception when workspace was deleted
  qt/python/mantidqtinterfaces/mantidqtinterfaces/DGSPlanner/DGSPlannerGUI.py
Labels: Bug, Direct Inelastic, GUI

#34855 Update Source Directories for Pycharm docs
  dev-docs/source/PyCharm.rst
Labels: Documentation

#34761 Fixed about widget URLs
  docs/source/release/v6.6.0/Workbench/Bugfixes/34738.rst
  qt/applications/workbench/workbench/widgets/about/presenter.py
Labels: Documentation, ISIS Team: Core

#34836 Added axes editor tests to test_figureinteraction
  qt/applications/workbench/workbench/plotting/test/test_figureinteraction.py
Labels: ISIS Team: Core

#34869 Disable SNSPowderRedux tests due to failures
  Testing/SystemTests/tests/framework/SNSPowderRedux.py
Labels: High Priority, ISIS Team: Core

#34879 Temporarily pinning numpy version in developer .yaml files
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: High Priority, ISIS Team: Core

#34878 Avoid using any agent in pipeline
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
Labels: High Priority, Extra Attention, ISIS Team: Core, Added during Sprint, DevOps

#34860 Add instructions for installing Java 11 on macOS
  buildconfig/Jenkins/jenkins-slave.sh
  dev-docs/source/JenkinsConfiguration.rst
Labels: DevOps

#34864 Fix for LoadNXSPE warning
  Framework/DataHandling/src/LoadNXSPE.cpp
  docs/source/algorithms/LoadNexusProcessed-v2.rst
  docs/source/algorithms/SaveNXSPE-v1.rst
  docs/source/release/v6.6.0/Framework/Data_Objects/Bugfixes/34864.rst
Labels: Bug, Documentation, ISIS Team: Core, ISIS Team: Excitations/Vesuvio

#34862 Lagrange: user feedback features
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/LagrangeILLReduction.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/LagrangeILLReductionTest.py
  Testing/Data/UnitTest/ILL/LAGRANGE/012869_close_scans.md5
  docs/source/algorithms/LagrangeILLReduction-v1.rst
  docs/source/release/v6.6.0/Direct_Geometry/General/New_features/34837.rst
Labels: Bug, Direct Inelastic, ILL Team

#34863 Update Indirect Manual Testing documentation Elwin Eq2 unit
  dev-docs/source/Testing/IndirectInelastic/IndirectInelasticAcceptanceTests.rst
Labels: Documentation, Induction, ISIS Team: Spectroscopy

#34870 Better formatting for arrays of values in the sample logs
  docs/source/release/v6.6.0/Workbench/Bugfixes/34870.rst
  qt/python/mantidqt/mantidqt/widgets/samplelogs/model.py
Labels: Bug

#34776 Add indeterminate progress bar below EngDiff FitPropertyBrowser
  docs/source/release/v6.6.0/Diffraction/Engineering/New_features/34776.rst
  qt/python/mantidqt/mantidqt/utils/asynchronous.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/CMakeLists.txt
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/engineering_diffraction_io.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/data_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/EngDiff_fitpropertybrowser.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/plot_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/plot_view.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/plot_widget.ui
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/test/test_plot_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/test/test_presenter.py
  qt/widgets/common/inc/MantidQtWidgets/Common/FitPropertyBrowser.h
  qt/widgets/common/src/FitPropertyBrowser.cpp
Labels: GUI, ISIS Team: Diffraction, Reported By User

#34806 Update h5py
  Framework/API/inc/MantidAPI/IBoxControllerIO.h
  Framework/DataObjects/inc/MantidDataObjects/BoxControllerNeXusIO.h
  Framework/DataObjects/src/BoxControllerNeXusIO.cpp
  Framework/DataObjects/test/BoxControllerNeXusIOTest.h
  Framework/MDAlgorithms/src/CloneMDWorkspace.cpp
  Framework/MDAlgorithms/src/SaveMD.cpp
  Framework/MDAlgorithms/test/CMakeLists.txt
  Framework/MDAlgorithms/test/CloneMDWorkspaceTest.h
  Framework/PythonInterface/test/python/plugins/algorithms/EnggSaveGSASIIFitResultsToHDF5Test.py
  Framework/PythonInterface/test/python/plugins/algorithms/ExportSampleLogsToHDF5Test.py
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/BoxControllerDummyIO.h
  docs/source/release/v6.6.0/Framework/New_features/.gitkeep
  docs/source/release/v6.6.0/Framework/New_features/34806.rst
  docs/source/release/v6.6.0/framework.rst
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
  scripts/test/Abins/AbinsIOmoduleTest.py
Labels: ISIS Team: Core

#34774 MPL 3.6 updates
  Framework/PythonInterface/mantid/plots/legend.py
  Framework/PythonInterface/mantid/plots/utility.py
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
  qt/applications/workbench/workbench/plotting/figureinteraction.py
  qt/applications/workbench/workbench/plotting/test/test_figureinteraction.py
  qt/applications/workbench/workbench/plotting/test/test_figurewindow.py
  qt/python/mantidqt/mantidqt/plotting/test/test_functions.py
  qt/python/mantidqt/mantidqt/project/plotsloader.py
  qt/python/mantidqt/mantidqt/widgets/codeeditor/completion.py
  qt/python/mantidqt/mantidqt/widgets/colorbar/colorbar.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/imagestabwidget/view.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/test/test_apply_all_properties.py
  qt/python/mantidqt/mantidqt/widgets/regionselector/test/test_regionselector_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/simplescanviewer/rectangle_selection.py
  qt/python/mantidqtinterfaces/test/SimpleScanViewer/RectanglePlotTest.py
  qt/widgets/mplcpp/test/FigureCanvasQtTest.h
  scripts/ExternalInterfaces/CMakeLists.txt
Labels: ISIS Team: Core

#34873 Composite function missing initialization
  Framework/PythonInterface/mantid/fitfunctions.py
Labels: Bug, Framework, ILL Team
