Repository mantidproject/mantid, pull requests merged in 2023-10, with the labels that each got.

#36153 Use `throw(std::exception)` in sip bindings
  qt/python/mantidqt/mantidqt/_common.sip
Labels: Maintenance

#36181 Discard the Figure resize event if it has a negative size
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.8.0/Workbench/InstrumentViewer/Bugfixes/36181.rst
  qt/widgets/mplcpp/CMakeLists.txt
  qt/widgets/mplcpp/inc/MantidQtWidgets/MplCpp/FigureEventFilter.h
  qt/widgets/mplcpp/src/ColorbarWidget.cpp
  qt/widgets/mplcpp/src/FigureEventFilter.cpp
Labels: Bug, ISIS Team: Core, Linux Only

#36192 Add missing init to fix import statement
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/__init__.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/helpers/__init__.py
Labels: High Priority, Bug, Found in Beta

#36208 Remove pragma pack from DateAndTime
  Framework/Types/inc/MantidTypes/Core/DateAndTime.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance

#36209 Return DateAndTime by const reference
  Framework/DataObjects/inc/MantidDataObjects/Events.h
  Framework/Types/inc/MantidTypes/Event/TofEvent.h
  Framework/Types/src/Event/TofEvent.cpp
  Framework/Types/test/TofEventTest.h
Labels: Maintenance

#36212 Fix cppcheck issues in DateAndTime
  Framework/Types/src/Core/DateAndTime.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance

#36211 Create Basic Doc for MagnetismReflectometryReduction-v1
  docs/source/algorithms/MagnetismReflectometryReduction-v1.rst
  docs/source/release/v6.8.0/reflectometry.rst
Labels: Documentation, ISIS Team: LSS

#36204 Use unique pointer to prevent leaking event filter
  qt/widgets/mplcpp/inc/MantidQtWidgets/MplCpp/ColorbarWidget.h
  qt/widgets/mplcpp/src/ColorbarWidget.cpp
  qt/widgets/mplcpp/src/FigureEventFilter.cpp
Labels: ISIS Team: Core

#36169 Warnings about missing pip packages
  Framework/PythonInterface/mantid/utils/pip.py
  Framework/PythonInterface/plugins/algorithms/ResNorm.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesQuasi.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesQuasi2.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesStretch.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesStretch2.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/BayesQuasi2Test.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/BayesQuasiTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/BayesStretch2Test.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/BayesStretchTest.py
  docs/source/algorithms/BayesQuasi-v1.rst
  docs/source/algorithms/BayesStretch-v1.rst
  docs/source/concepts/PipInstall.rst
  docs/source/interfaces/direct/Crystal Field Python Interface.rst
  docs/source/release/v6.8.0/Framework/Python/New_features/36169.rst
  scripts/Inelastic/IndirectImport.py
Labels: Documentation, ISIS Team: Core

#36217 pin python in publish anaconda env
  buildconfig/Jenkins/Conda/publish-to-anaconda
Labels: High Priority, Bug, Dependencies, DevOps

#36188 Add manual testing docs for sample transmission calculator
  dev-docs/source/Testing/General/SampleTransmissionCalculatorTestGuide.rst
  dev-docs/source/Testing/index.rst
  dev-docs/source/images/SampleTransmissionCalculatorTest.png
Labels: Documentation, ISIS Team: Core

#36195 Perform unweighted average of log data in Eng Diff UI fitting tab if no proton_charge log
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/data_handling/test/test_data_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/output_sample_logs.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/test/test_gsas2_model.py
Labels: ISIS Team: Diffraction

#36172 Fix `PDCalibration` with workspace indices
  Framework/Algorithms/inc/MantidAlgorithms/FitPeaks.h
  Framework/Algorithms/src/FitPeaks.cpp
  Framework/Algorithms/src/PDCalibration.cpp
  Framework/Algorithms/test/FitPeaksTest.h
  docs/source/algorithms/FitPeaks-v1.rst
  docs/source/release/v6.8.0/Diffraction/Powder/Bugfixes/36123.rst
Labels: Diffraction, Powder

#36189 Update muon docs
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_EMU.rst
  dev-docs/source/images/MuonAnalysisTests/MATestingIDF.png
Labels: Muon, Documentation, Manual Tests

#36223 Fix inconsistency in StretchedExpFT documentation
  docs/source/fitting/fitfunctions/StretchedExpFT.rst
  docs/source/release/v6.8.0/Framework/Fit_Functions/Bugfixes/36223.rst
Labels: Documentation, Reported By User

#36218 Release note summary and images for v6.8
  docs/source/images/6_8_release/Diffraction/DEMAND_DGSPlanner.png
  docs/source/images/6_8_release/MantidWorkbench/SliceviewerAutoscaleOptions.png
  docs/source/images/6_8_release/MantidWorkbench/TOFConverterUI.png
  docs/source/images/6_8_release/Python_v3p10.png
  docs/source/release/v6.8.0/Diffraction/Engineering/New_features/Used/36195.rst
  docs/source/release/v6.8.0/Diffraction/Powder/Bugfixes/Used/36123.rst
  docs/source/release/v6.8.0/Framework/Fit_Functions/Bugfixes/Used/36223.rst
  docs/source/release/v6.8.0/Framework/Python/New_features/Used/36169.rst
  docs/source/release/v6.8.0/diffraction.rst
  docs/source/release/v6.8.0/direct_geometry.rst
  docs/source/release/v6.8.0/framework.rst
  docs/source/release/v6.8.0/index.rst
  docs/source/release/v6.8.0/mantidworkbench.rst
Labels: Documentation

#36199 fix bayesStretch2 label
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesStretch2.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/BayesStretch2Test.py
Labels: ISIS Team: Spectroscopy, Reported By User, Found in Beta

#36216 Improve DiffractionFocussing performance for PreserveEvents=False
  Framework/Algorithms/inc/MantidAlgorithms/DiffractionFocussing2.h
  Framework/Algorithms/src/DiffractionFocussing2.cpp
  Framework/WorkflowAlgorithms/test/AlignAndFocusPowderTest.h
  docs/source/release/v6.9.0/Diffraction/Powder/New_features/36216.rst
Labels: Diffraction, Powder

#36224 Fix unreliable ALFView segmentation fault
  docs/source/release/v6.8.0/direct_geometry.rst
  qt/scientific_interfaces/Direct/ALFAlgorithmManager.cpp
  qt/scientific_interfaces/Direct/ALFAlgorithmManager.h
  qt/widgets/common/inc/MantidQtWidgets/Common/BatchAlgorithmRunner.h
  qt/widgets/common/inc/MantidQtWidgets/Common/IJobRunner.h
  qt/widgets/common/inc/MantidQtWidgets/Common/MockJobRunner.h
  qt/widgets/common/inc/MantidQtWidgets/Common/QtJobRunner.h
  qt/widgets/common/src/BatchAlgorithmRunner.cpp
  qt/widgets/common/src/QtJobRunner.cpp
Labels: High Priority, Bug, Direct Inelastic, ISIS Team: Core, Linux Only, ISIS Team: Excitations/Vesuvio

#36226 EventList performance improvements and minor refactor
  Framework/DataObjects/inc/MantidDataObjects/EventList.h
  Framework/DataObjects/src/EventList.cpp
  Framework/DataObjects/src/EventWorkspaceMRU.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance

#36193 Set default number density units as formula units/Ang^3 in single crystal reduction classes
  Testing/SystemTests/tests/framework/SXDAnalysis.py
  docs/source/release/v6.9.0/Diffraction/Single_Crystal/Bugfixes/36193.rst
  scripts/Diffraction/single_crystal/base_sx.py
  scripts/Diffraction/single_crystal/test/test_sxd.py
Labels: Single Crystal, ISIS Team: Diffraction

#36269 Reenable error handling in FitPropertyBrowser
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/EngDiff_fitpropertybrowser.py
  qt/widgets/common/inc/MantidQtWidgets/Common/FitPropertyBrowser.h
  qt/widgets/common/src/FitPropertyBrowser.cpp
Labels: High Priority

#36164 Stop plotting data with different data units to plot on Engineering diffraction fitting tab
  docs/source/release/v6.9.0/Diffraction/Engineering/Bugfixes/36164.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/engineering_diffraction_io.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/data_handling/data_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/data_handling/test/test_data_presenter.py
Labels: Bug, Diffraction, ISIS Team: Diffraction

#36232 Take into account the projection matrix when adding and showing peaks
  docs/source/release/v6.9.0/Workbench/SliceViewer/Bugfixes/36232.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/sliceinfo.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/test/test_peaksviewer_model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/test/test_peaksviewer_sliceviewer_add_delete_peaks_integration.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenters/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_sliceinfo.py
Labels: Bug

#36278 Fix index error in `LoadMuonNexusV2`
  Framework/DataHandling/inc/MantidDataHandling/LoadMuonNexusV2NexusHelper.h
  Framework/DataHandling/src/LoadMuonNexusV2.cpp
  Framework/DataHandling/src/LoadMuonNexusV2NexusHelper.cpp
  Framework/DataHandling/test/LoadMuonNexusV2Test.h
  Testing/Data/UnitTest/HIFI00183810.nxs.md5
  docs/source/release/v6.9.0/Muon/Algorithms/Bugfixes/36270.rst
Labels: Bug, Muon, ISIS Team: Spectroscopy, Reported By User

#36214 Add colorbar autoscaling limits tests
  qt/python/mantidqt/mantidqt/widgets/colorbar/test/test_colorbar.py
Labels: Bug, Single Crystal

#36167 Conda developer docs
  dev-docs/source/CondaPackageManager.rst
  dev-docs/source/index.rst
Labels: Documentation, Maintenance

#36293 Remove rst files for deleted algorithms
  Framework/MDAlgorithms/test/FitResolutionConvolvedModelTest.h
  docs/source/algorithms/CreateChopperModel-v1.rst
  docs/source/algorithms/CreateModeratorModel-v1.rst
  docs/source/algorithms/FitResolutionConvolvedModel-v1.rst
  docs/source/algorithms/SANSConvertToWavelength-v1.rst
  docs/source/algorithms/SANSCrop-v1.rst
  docs/source/algorithms/SaveMDWorkspaceToVTK-v1.rst
  docs/source/algorithms/SimulateResolutionConvolvedModel-v1.rst
  qt/applications/workbench/workbench/projectrecovery/projectrecoverysaver.py
Labels: Documentation

#36288 Add rstcheck as pre-commit hook and fix issues
  .pre-commit-config.yaml
  .rstcheck.project.cfg
  dev-docs/source/CLion.rst
  dev-docs/source/EnumeratedString.rst
  dev-docs/source/ISISSANSReductionBackend.rst
  dev-docs/source/MVPTutorial/AddButton.rst
  dev-docs/source/MVPTutorial/Mocking.rst
  dev-docs/source/Standards/DeprecateAlgorithm.rst
  dev-docs/source/Standards/ReleaseNotesGuide.rst
  dev-docs/source/SystemTests.rst
  dev-docs/source/Testing/ErrorReporter-ProjectRecovery/ProjectRecoveryTesting.rst
  dev-docs/source/ToolsOverview.rst
  docs/source/algorithms/AlignAndFocusPowderFromFiles-v1.rst
  docs/source/algorithms/BASISPowderDiffraction-v1.rst
  docs/source/algorithms/BASISReduction-v1.rst
  docs/source/algorithms/CatalogGetDataFiles-v1.rst
  docs/source/algorithms/CatalogGetDataSets-v1.rst
  docs/source/algorithms/CatalogListInstruments-v1.rst
  docs/source/algorithms/CatalogListInvestigationTypes-v1.rst
  docs/source/algorithms/CatalogLogin-v1.rst
  docs/source/algorithms/CatalogMyDataSearch-v1.rst
  docs/source/algorithms/CatalogSearch-v1.rst
  docs/source/algorithms/CentroidPeaksMD-v2.rst
  docs/source/algorithms/ClearCache-v1.rst
  docs/source/algorithms/CutMD-v1.rst
  docs/source/algorithms/DeltaPDF3D-v1.rst
  docs/source/algorithms/DownloadFile-v1.rst
  docs/source/algorithms/DownloadInstrument-v1.rst
  docs/source/algorithms/FindPeaksMD-v1.rst
  docs/source/algorithms/GSASIIRefineFitPeaks-v1.rst
  docs/source/algorithms/GenerateIPythonNotebook-v1.rst
  docs/source/algorithms/GetIPTS-v1.rst
  docs/source/algorithms/ISISJournalGetExperimentRuns-v1.rst
  docs/source/algorithms/IntegrateEllipsoids-v1.rst
  docs/source/algorithms/IntegrateEllipsoids-v2.rst
  docs/source/algorithms/IntegrateEllipsoidsTwoStep-v1.rst
  docs/source/algorithms/IntegratePeaksMD-v2.rst
  docs/source/algorithms/IntegratePeaksProfileFitting-v1.rst
  docs/source/algorithms/IqtFitSequential-v1.rst
  docs/source/algorithms/IqtFitSimultaneous-v1.rst
  docs/source/algorithms/LoadCIF-v1.rst
  docs/source/algorithms/LoadLamp-v1.rst
  docs/source/algorithms/MDNormDirectSC-v1.rst
  docs/source/algorithms/MergeRuns-v1.rst
  docs/source/algorithms/ModeratorTzero-v1.rst
  docs/source/algorithms/ModeratorTzeroLinear-v1.rst
  docs/source/algorithms/NMoldyn4Interpolation-v1.rst
  docs/source/algorithms/PolDiffILLReduction-v1.rst
  docs/source/algorithms/PoldiCreatePeaksFromFile-v1.rst
  docs/source/algorithms/SCDCalibratePanels-v2.rst
  docs/source/algorithms/SaveToSNSHistogramNexus-v1.rst
  docs/source/algorithms/VesuvioCalculateMS-v1.rst
  docs/source/release/v3.10.0/framework.rst
  docs/source/release/v3.7.1/ui.rst
Labels: Documentation, Maintenance

#36206 34368 Reverting invalid bg params on Engineering Diffraction's fitting tab
  docs/source/release/v6.9.0/Diffraction/Engineering/Bugfixes/34368.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/data_handling/data_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/data_handling/data_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/data_handling/data_view.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/data_handling/test/test_data_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/data_handling/test/test_data_presenter.py
Labels: Bug, Diffraction, ISIS Team: Diffraction

#36289 Home button on 3D plots now resets the view
  docs/source/release/v6.9.0/Workbench/Bugfixes/36107.rst
  qt/applications/workbench/workbench/plotting/toolbar.py
Labels: Bug, ISIS Team: Core, Found in Beta

#36282 Redraw rescaled y axis in superplot on normalisation
  docs/source/release/v6.9.0/Workbench/Bugfixes/36103.rst
  qt/python/mantidqt/mantidqt/widgets/superplot/presenter.py
Labels: Bug, ISIS Team: Core, ILL Team, Found in Beta

#36294 mark DSFInterp and DSFInterp1DFit for deprecation
  Framework/PythonInterface/plugins/algorithms/DSFinterp.py
  Framework/PythonInterface/plugins/functions/DSFinterp1DFit.py
  docs/source/algorithms/DSFinterp-v1.rst
  docs/source/release/v6.9.0/Framework/Algorithms/Bugfixes/36294.rst
  docs/source/release/v6.9.0/Framework/Fit_Functions/Bugfixes/36294.rst
Labels: Maintenance

#36300 Fix rstcheck issues - part 2
  .pre-commit-config.yaml
  .rstcheck.project.cfg
  docs/source/concepts/FitFunctionsInPython.rst
  docs/source/concepts/HowToDefineGeometricShape.rst
  docs/source/concepts/InstrumentDefinitionFile.rst
  docs/source/concepts/PythonNotebook.rst
  docs/source/concepts/calibration/EngineeringCalibration.rst
  docs/source/tutorials/extending_mantid_with_python/python_algorithms/01_basic_algorithm_structure.rst
  docs/source/tutorials/introduction_to_python/control_structures.rst
  docs/source/tutorials/introduction_to_python/looping.rst
  docs/source/tutorials/introduction_to_python/type_conversions.rst
  docs/source/tutorials/introduction_to_python/using_modules.rst
  docs/source/tutorials/introduction_to_python/working_with_functions.rst
  docs/source/tutorials/mantid_basic_course/connecting_data_to_instruments/06_sample_logs.rst
  docs/source/tutorials/mantid_basic_course/connecting_data_to_instruments/07_invalid_sample_logs.rst
  docs/source/tutorials/python_in_mantid/algorithms_and_workspaces/06_alg_help.rst
  docs/source/tutorials/python_in_mantid/further_alg_ws/05_advanced_logs.rst
  docs/source/tutorials/python_in_mantid/solutions/01_pim_sol.rst
Labels: Documentation, Maintenance

#36290 Fix crash from setting both waterfall offsets to 0
  Framework/PythonInterface/mantid/plots/mantidaxes.py
  docs/source/release/v6.9.0/Workbench/Bugfixes/35257.rst
Labels: Bug, ISIS Team: Core

#36228 Fix crash when closing cpp interface while processing
  docs/source/release/v6.9.0/Direct_Geometry/General/Bugfixes/36227.rst
  qt/widgets/common/src/BatchAlgorithmRunner.cpp
Labels: Bug, Direct Inelastic, ISIS Team: Excitations/Vesuvio

#36296 Fix versioning for untagged past release candidate
  buildconfig/CMake/VersionNumber.cmake
Labels: Bug, Maintenance

#36302 Add dev docs for using performance measurement tools
  dev-docs/source/AlgorithmProfiler.rst
  dev-docs/source/ProfilingOverview.rst
  dev-docs/source/ProfilingWithPerf.rst
  dev-docs/source/images/MantidProfiler.png
  dev-docs/source/images/vtune_configure.png
  dev-docs/source/index.rst
Labels: Documentation

#36309 Fix issue clicking on 2D view in Slice Viewer
  docs/source/release/v6.9.0/Workbench/SliceViewer/Bugfixes/36266.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/test/test_peaksviewer_peaksviewercollectionpresenter.py
Labels: Bug, ISIS Team: Core

#36308 Remove unnecessary `IndirectFitAnalysisTab` class
  dev-docs/source/IndirectDataAnalysisFileStructure.rst
  dev-docs/source/images/QENS/IndirectFitClassStructure.png
  dev-docs/source/images/QENS/indirectFitClassStructure.uxf
  qt/scientific_interfaces/Indirect/CMakeLists.txt
  qt/scientific_interfaces/Indirect/IIndirectFitDataModel.h
  qt/scientific_interfaces/Indirect/IIndirectFitOutput.h
  qt/scientific_interfaces/Indirect/IIndirectFittingModel.h
  qt/scientific_interfaces/Indirect/IndirectDataAnalysis.cpp
  qt/scientific_interfaces/Indirect/IndirectDataAnalysis.h
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisConvFitTab.cpp
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisConvFitTab.h
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisFqFitTab.cpp
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisFqFitTab.h
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisIqtFitTab.cpp
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisIqtFitTab.h
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisMSDFitTab.cpp
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisMSDFitTab.h
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisTab.cpp
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisTab.h
  qt/scientific_interfaces/Indirect/IndirectFitAnalysisTab.cpp
  qt/scientific_interfaces/Indirect/IndirectFitAnalysisTab.h
  qt/scientific_interfaces/Indirect/IndirectFitDataModel.h
  qt/scientific_interfaces/Indirect/IndirectFitOutput.h
  qt/scientific_interfaces/Indirect/test/CMakeLists.txt
  qt/scientific_interfaces/Indirect/test/IndirectDataAnalysisTabTest.h
  qt/scientific_interfaces/Indirect/test/IndirectFitDataModelTest.h
Labels: Indirect Inelastic, Maintenance, ISIS Team: Spectroscopy

#36272 Fix deprecation warning and simplify Indirect Data Analysis external plotting
  qt/scientific_interfaces/Indirect/CMakeLists.txt
  qt/scientific_interfaces/Indirect/IndirectFitPlotModel.cpp
  qt/scientific_interfaces/Indirect/IndirectFitPlotModel.h
  qt/scientific_interfaces/Indirect/IndirectFitPlotPresenter.cpp
  qt/scientific_interfaces/Indirect/IndirectFitPlotPresenter.h
  qt/scientific_interfaces/Indirect/LazyAsyncRunner.h
  qt/scientific_interfaces/Indirect/test/IndirectFitPlotModelTest.h
Labels: Bug, Indirect Inelastic, Maintenance, ISIS Team: Spectroscopy

#36291 32689 Hide legend button added to fit toolbar
  docs/source/release/v6.9.0/Diffraction/Engineering/New_features/32689.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/plot_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/plot_toolbar.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/plot_view.py
Labels: Diffraction, ISIS Team: Diffraction

#36202 Add pre-commit hook to check release note bullet point stlye
  .pre-commit-config.yaml
  docs/source/release/v6.8.0/Diffraction/Powder/Bugfixes/Used/36122.rst
Labels: Documentation, Maintenance

#36314 Add release note directory for `Inelastic` category
  dev-docs/source/Standards/ReleaseNotesGuide.rst
  docs/source/release/templates/inelastic.rst
  docs/source/release/v6.9.0/Inelastic/Algorithms/Bugfixes/.gitkeep
  docs/source/release/v6.9.0/Inelastic/Algorithms/New_features/.gitkeep
  docs/source/release/v6.9.0/Inelastic/Bugfixes/.gitkeep
  docs/source/release/v6.9.0/Inelastic/New_features/.gitkeep
  docs/source/release/v6.9.0/index.rst
  docs/source/release/v6.9.0/inelastic.rst
  tools/release_generator/release.py
Labels: ISIS Team: Spectroscopy, Inelastic

#36225 Add gatekeeper guidance
  dev-docs/source/Gatekeeping.rst
  dev-docs/source/ReviewingAPullRequest.rst
  dev-docs/source/index.rst
Labels: Documentation

#35928 Unpin sphinx and pygments
  buildconfig/Jenkins/Conda/conda-buildscript
  buildconfig/Jenkins/Conda/package-conda
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantiddocs/meta.yaml
  docs/sphinxext/mantiddoc/directives/algorithm.py
  docs/sphinxext/mantiddoc/directives/base.py
  docs/sphinxext/mantiddoc/directives/interface.py
  docs/sphinxext/mantiddoc/directives/plot_directive.py
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: Bug, ISIS Team: Core

#36328 Update pre-commit-hooks commit hash
  .pre-commit-config.yaml
Labels: Maintenance

#36279 34367 Diffraction RB Number box validation and unit tests
  docs/source/release/v6.9.0/Diffraction/Engineering/Bugfixes/34367.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/engineering_diffraction.py
Labels: Bug, Diffraction, ISIS Team: Diffraction

#36026 Remove unnecessary options for IRIS and OSIRIS in ISIS Energy Transfer
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransfer.ui
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModel.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModel.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferPresenter.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferView.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferView.h
Labels: Indirect Inelastic, ISIS Team: Spectroscopy

#36312 35665 Move Data Analysis GUI to Inelastic Tab Category
  Testing/SystemTests/tests/framework/InterfaceDocumentationTest.py
  docs/source/interfaces/index.rst
  docs/source/interfaces/inelastic/Inelastic Data Analysis.rst
  docs/source/interfaces/inelastic/Inelastic Data Manipulation.rst
  docs/source/interfaces/inelastic/QENS Fitting.rst
  docs/source/release/v6.9.0/Inelastic/New_features/35665.rst
  qt/scientific_interfaces/Indirect/IndirectDataAnalysis.h
Labels: Indirect Inelastic, GUI, ISIS Team: Spectroscopy

#36317 Enable colour selection tool in contour plots
  docs/source/release/v6.9.0/Workbench/Bugfixes/36317.rst
  qt/applications/workbench/workbench/plotting/figuremanager.py
  qt/applications/workbench/workbench/plotting/test/test_toolbar.py
  qt/applications/workbench/workbench/plotting/toolbar.py
Labels: Bug, GUI, ISIS Team: Core

#36229 Improved width validation in Sample Transmission Calculator
  docs/source/release/v6.9.0/Framework/Algorithms/Bugfixes/36196.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/SampleTransmissionCalculator/stc_model.py
  qt/python/mantidqtinterfaces/test/sample_transmission_calculator/stc_model_test.py
Labels: Bug, ISIS Team: Core

#36331 Fix unreliable python interface startup test
  Testing/SystemTests/tests/qt/PythonInterfacesStartupTest.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/reduction_application.py
Labels: High Priority, Bug, ISIS Team: Core

#36329 Fix crash in surface plot after changing properties
  docs/source/release/v6.9.0/Workbench/Bugfixes/36264.rst
  qt/python/mantidqt/mantidqt/plotting/functions.py
Labels: Bug, ISIS Team: Core

#36285 Fix unhandled exception when removing a curve with bad labels
  docs/source/release/v6.9.0/Workbench/Bugfixes/36102.rst
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/curvestabwidget/presenter.py
Labels: Bug, ISIS Team: Core, Found in Beta

#36342 upload conda packages to github releases
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
  buildconfig/Jenkins/Conda/publish-to-github
Labels: ISIS Team: Core, DevOps
