Repository mantidproject/mantid, pull requests merged in 2023-05, with the labels that each got.

#35491 EstimateResolutionDiffraction source parameters
  Framework/Algorithms/inc/MantidAlgorithms/EstimateResolutionDiffraction.h
  Framework/Algorithms/src/EstimateResolutionDiffraction.cpp
  Framework/Algorithms/test/EstimateResolutionDiffractionTest.h
  docs/source/algorithms/EstimateResolutionDiffraction-v1.rst
  docs/source/release/v6.7.0/Diffraction/Powder/Improvements/35491.rst
Labels: Diffraction, Powder

#35445 Add new stitch parameters to POLREF_Parameters file
  Testing/SystemTests/tests/framework/PolrefExample.py
  docs/source/release/v6.7.0/Reflectometry/New_features/34843.rst
  instrument/POLREF_Parameters.xml
Labels: Reflectometry, GUI, ISIS Team: LSS

#35441 Vasp IBRION=6 import: ignore selective dynamics (as VASP does)
  Testing/Data/UnitTest/si_ibrion6_selective_LoadVASP.xml.md5
  Testing/Data/UnitTest/si_ibrion6_selective_LoadVASP_atomic_displacements_data_0.txt.md5
  Testing/Data/UnitTest/si_ibrion6_selective_LoadVASP_data.txt.md5
  docs/source/release/v6.7.0/Indirect/Algorithms/Bugfixes/35441.rst
  scripts/abins/input/vasploader.py
  scripts/test/Abins/AbinsLoadVASPTest.py
Labels: ISIS Team: Spectroscopy

#35482 Use native file browsers on GTK-based linux environments
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid/meta.yaml
  conda/recipes/mantidqt/meta.yaml
  docs/source/release/v6.7.0/Workbench/Bugfixes/34820.rst
  mantid-developer-linux.yml
  mantid-developer-win.yml
Labels: High Priority, Bug, GUI, ISIS Team: Core, Linux Only, Reported By User, Dependencies

#35372 Separate QSettings for ALFView and InstrumentView
  docs/source/release/v6.7.0/Direct_Geometry/General/Bugfixes/35003.rst
  qt/scientific_interfaces/Direct/ALFInstrumentWidget.cpp
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/InstrumentActor.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/InstrumentWidget.h
  qt/widgets/instrumentview/src/InstrumentActor.cpp
  qt/widgets/instrumentview/src/InstrumentWidget.cpp
Labels: Bug, Direct Inelastic, ISIS Team: Excitations/Vesuvio

#35450 Update tied properties in the FitPropertyBrowser
  Framework/API/inc/MantidAPI/IFunction.h
  Framework/API/src/IFunction.cpp
  Framework/API/test/FunctionParameterDecoratorTest.h
  Framework/API/test/ParameterTieTest.h
  docs/source/release/v6.7.0/Workbench/Bugfixes/32365.rst
  qt/widgets/common/src/FitPropertyBrowser.cpp
  qt/widgets/common/src/PropertyHandler.cpp
  qt/widgets/common/test/FitPropertyBrowserTest.h
Labels: ISIS Team: Core

#35439 Abins CRYSTAL.out: Treat "anti-phase" eigenvectors as imaginary part
  Testing/Data/UnitTest/crystal23_diamond.out.md5
  Testing/Data/UnitTest/crystal23_diamond_atomic_displacements_data_0.txt.md5
  Testing/Data/UnitTest/crystal23_diamond_atomic_displacements_data_1.txt.md5
  Testing/Data/UnitTest/crystal23_diamond_atomic_displacements_data_2.txt.md5
  Testing/Data/UnitTest/crystal23_diamond_atomic_displacements_data_3.txt.md5
  Testing/Data/UnitTest/crystal23_diamond_data.txt.md5
  docs/source/release/v6.7.0/Indirect/Algorithms/Bugfixes/35439.rst
  scripts/abins/input/crystalloader.py
  scripts/abins/input/tester.py
  scripts/test/Abins/AbinsLoadCRYSTALTest.py
Labels: ISIS Team: Spectroscopy

#35469 Close slice viewer when an original workspace is deleted
  Framework/API/inc/MantidAPI/MDGeometry.h
  Framework/API/src/MDGeometry.cpp
  docs/source/release/v6.7.0/Workbench/SliceViewer/Bugfixes/33434.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenters/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_presenter.py
Labels: Bug, ISIS Team: Core

#35508 Estimate PD resolution for focussed SNAP instrument
  Framework/Algorithms/src/EstimateResolutionDiffraction.cpp
  Framework/Algorithms/test/EstimateResolutionDiffractionTest.h
  Testing/Data/UnitTest/SNAPLite_Definition.xml.md5
  docs/source/algorithms/EstimateResolutionDiffraction-v1.rst
  docs/source/release/v6.7.0/Diffraction/Powder/Improvements/35508.rst
Labels: Diffraction, Powder

#35504 Fix Developer Documentation pipeline
  buildconfig/Jenkins/Conda/build-and-publish-devsite.sh
  dev-docs/source/index.rst
Labels: High Priority, Documentation, DevOps

#35517 Add PyCIFRW runtime dependency to mantid packge
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid/meta.yaml
  docs/source/release/v6.7.0/Framework/Algorithms/New_features/35514.rst
Labels: ISIS Team: Core, Dependencies

#35485 Improve readability of Jenkins nightly pipeline in Jenkins UI
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
Labels: ISIS Team: Core

#35516 Updated images in Stitch1DMany documentation
  docs/source/algorithms/Stitch1DMany-v1.rst
  docs/source/images/Stitch1D1.png
  docs/source/images/Stitch1D2.png
Labels: Documentation, ISIS Team: LSS

#35512 Correct documentation on custom slicing in ISIS Reflectometry GUI
  docs/source/interfaces/reflectometry/ISIS Reflectometry.rst
Labels: Reflectometry, Documentation, ISIS Team: LSS

#35444 Updating algorithms for modulation vectors - fixing common issues
  Framework/Algorithms/src/CompareWorkspaces.cpp
  Framework/Algorithms/test/CompareWorkspacesTest.h
  Framework/Crystal/src/FilterPeaks.cpp
  Framework/Crystal/src/IndexPeaks.cpp
  Framework/Crystal/src/LoadHKL.cpp
  Framework/Crystal/src/OptimizeLatticeForCellType.cpp
  Framework/Crystal/src/PeakStatisticsTools.cpp
  Framework/Crystal/src/SaveHKL.cpp
  Framework/Crystal/test/FilterPeaksTest.h
  Framework/Crystal/test/IndexPeaksTest.h
  Framework/Crystal/test/LoadHKLTest.h
  Framework/Crystal/test/OptimizeLatticeForCellTypeTest.h
  Framework/Crystal/test/PeakStatisticsToolsTest.h
  Framework/Crystal/test/SaveHKLTest.h
  Framework/Crystal/test/SortHKLTest.h
  Framework/Crystal/test/StatisticsOfPeaksWorkspaceTest.h
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  Framework/DataObjects/src/BasePeak.cpp
  Framework/DataObjects/src/LeanElasticPeaksWorkspace.cpp
  Framework/DataObjects/src/PeakColumn.cpp
  Framework/DataObjects/src/PeaksWorkspace.cpp
  Framework/DataObjects/test/LeanElasticPeaksWorkspaceTest.h
  Framework/DataObjects/test/PeaksWorkspaceTest.h
  Framework/PythonInterface/plugins/algorithms/LinkedUBs.py
  Testing/Data/SystemTest/SortHKL/reflections_Cmmm.hkl.md5
  Testing/Data/SystemTest/SortHKL/reflections_Fm-3m.hkl.md5
  Testing/Data/SystemTest/SortHKL/reflections_Fmmm.hkl.md5
  Testing/Data/SystemTest/SortHKL/reflections_I4_mmm.hkl.md5
  Testing/Data/SystemTest/SortHKL/reflections_Im-3m.hkl.md5
  Testing/Data/SystemTest/SortHKL/reflections_Immm.hkl.md5
  Testing/Data/SystemTest/SortHKL/reflections_P4_mmm.hkl.md5
  Testing/Data/SystemTest/SortHKL/reflections_Pm-3m.hkl.md5
  Testing/Data/SystemTest/SortHKL/reflections_Pmmm.hkl.md5
  Testing/Data/SystemTest/TOPAZ_3132_reference_04012021.hkl.md5
  Testing/Data/SystemTest/refine_satellites_auto_q_test_04012021.nxs.md5
  Testing/Data/SystemTest/refine_satellites_fixed_q_test_04012021.nxs.md5
  Testing/Data/UnitTest/gsas_format.hkl.md5
  Testing/SystemTests/tests/framework/SingleCrystalPeaksTest.py
  docs/source/release/v6.7.0/Diffraction/Single_Crystal/Bugfixes/35444.rst
  docs/source/release/v6.7.0/Diffraction/Single_Crystal/New_features/35444.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/presenter.py
Labels: Bug, Diffraction, Single Crystal

#35456 Add unit option to Indirection Diffraction UI output plot options
  docs/source/release/v6.7.0/Indirect/New_features/35456.rst
  qt/scientific_interfaces/Indirect/IndirectDiffractionReduction.cpp
  qt/scientific_interfaces/Indirect/IndirectDiffractionReduction.ui
  qt/scientific_interfaces/Indirect/IndirectPlotOptions.ui
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsModel.cpp
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsModel.h
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsPresenter.cpp
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsPresenter.h
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsView.cpp
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsView.h
Labels: ISIS Team: Spectroscopy

#35494 Alter ISISReflectometryCalibration algorithm
  Framework/DataHandling/src/MoveInstrumentComponent.cpp
  Framework/DataHandling/test/MoveInstrumentComponentTest.h
  Framework/PythonInterface/mantid/geometry/src/Exports/DetectorInfo.cpp
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISCalibration.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISLoadAndProcess.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISPreprocess.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISCalibrationTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISLoadAndProcessTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISPreprocessTest.py
  Framework/Reflectometry/src/SpecularReflectionPositionCorrect2.cpp
  Framework/Reflectometry/test/SpecularReflectionPositionCorrect2Test.h
  Testing/Data/UnitTest/ISISReflectometry/calibration_test_data.dat.md5
  Testing/Data/UnitTest/ISISReflectometry/calibration_test_data_INTER45455.dat.md5
  docs/source/release/v6.7.0/Reflectometry/New_features/35494.rst
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/RowPreprocessingAlgorithm.cpp
  qt/scientific_interfaces/ISISReflectometry/test/Batch/RowPreprocessingAlgorithmTest.h
Labels: Reflectometry, Framework, ISIS Team: LSS

#35529 Fixing 4d workspace projection issue for SliceViewer
  Testing/SystemTests/tests/qt/SliceViewerIntegrationTest.py
  docs/source/release/v6.7.0/Workbench/SliceViewer/Bugfixes/35529.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py
Labels: Bug, Single Crystal, GUI

#35509 Update documentation following changes to ReflectometryISISCalibration
  docs/source/algorithms/ApplyCalibration-v1.rst
  docs/source/algorithms/ReflectometryISISCalibration-v1.rst
  docs/source/algorithms/ReflectometryISISLoadAndProcess-v1.rst
  docs/source/release/v6.7.0/Reflectometry/New_features/35494.rst
Labels: Reflectometry, Documentation, ISIS Team: LSS

#35523 Edit docs to help readability for GenerateEventsFilter
  docs/source/algorithms/GenerateEventsFilter-v1.rst
Labels: Documentation

#35590 Fix Some Docs Issues Found in Testing
  dev-docs/source/Testing/Core/Core.rst
  dev-docs/source/Testing/ErrorReporter-ProjectRecovery/ErrorReporterTesting.rst
  docs/source/interfaces/muon/Feature Flags.rst
Labels: Documentation

#35526 Fix GroupingWorkspace accessors and use less memory in PD calibration
  Framework/DataObjects/inc/MantidDataObjects/GroupingWorkspace.h
  Framework/DataObjects/src/GroupingWorkspace.cpp
  Framework/DataObjects/test/GroupingWorkspaceTest.h
  Framework/PythonInterface/mantid/dataobjects/src/Exports/GroupingWorkspace.cpp
  Framework/PythonInterface/test/python/mantid/dataobjects/GroupingWorkspaceTest.py
  docs/source/release/v6.7.0/Framework/Data_Objects/New_features/35486.rst
  docs/source/release/v6.7.0/Framework/Python/New_features/35486.rst
  scripts/Calibration/tofpd/group_calibration.py
  scripts/test/Calibration/tofpd/test_group_calibration.py
Labels: Diffraction, Powder

#35609 Fix bug calculating time-avg-mean with duplicates
  Framework/Kernel/src/TimeSeriesProperty.cpp
  Framework/Kernel/test/TimeSeriesPropertyTest.h
Labels: Bug

#35604 Improve auto-population behaviour for Save File input in ISIS SANS GUI
  docs/source/release/v6.7.0/SANS/Bugfixes/35604.rst
  scripts/Interface/ui/sans_isis/add_runs_page.py
Labels: SANS, ISIS Team: LSS

#35577 Fix Stitch1DMany child workspace names
  Framework/Algorithms/inc/MantidAlgorithms/Stitch1DMany.h
  Framework/Algorithms/src/Stitch1DMany.cpp
  Framework/Algorithms/test/Stitch1DManyTest.h
Labels: Reflectometry, ISIS Team: LSS

#35612 Change developer docs for ~/.ssh/config inside ORNL
  dev-docs/source/GettingStarted/GettingStarted.rst
Labels: Documentation

#35588 Fix ConvertUnits logic error in indirect data reduction interface
  qt/scientific_interfaces/Indirect/IndirectDiffractionReduction.cpp
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsPresenter.cpp
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsPresenter.h
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsView.cpp
Labels: Bug, Indirect Inelastic, ISIS Team: Spectroscopy

#35594 Adding integer tick marks to slice viewer for HKL-axes
  Testing/SystemTests/tests/qt/SliceViewerIntegrationTest.py
  docs/source/release/v6.8.0/Workbench/SliceViewer/New_features/35594.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/sliceinfo.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenters/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_dataview.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/views/dataview.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/views/view.py
Labels: Single Crystal, GUI

#35602 Fix user doc errors and warnings before starting 6.7 release note work
  docs/source/algorithms/ConvertToMDMinMaxGlobal-v1.rst
  docs/source/algorithms/LagrangeILLReduction-v1.rst
  docs/source/release/v3.10.0/ui.rst
  docs/source/release/v6.5.0/Diffraction/Powder/Bugfixes/34710.rst
  docs/source/release/v6.7.0/Diffraction/Engineering/New_features/34709_SampleLogs.rst
  docs/source/release/v6.7.0/Diffraction/Powder/New_features/34877.rst
  docs/source/release/v6.7.0/Diffraction/Powder/New_features/35284.rst
  docs/source/release/v6.7.0/Diffraction/Powder/New_features/35334.rst
  docs/source/release/v6.7.0/Diffraction/Powder/New_features/35491.rst
  docs/source/release/v6.7.0/Diffraction/Powder/New_features/35508.rst
  docs/source/release/v6.7.0/Direct_Geometry/General/New_features/35152.rst
  docs/source/release/v6.7.0/Indirect/Algorithms/New_features/35166.rst
  docs/source/release/v6.7.0/Indirect/Bugfixes/34486.rst
  docs/source/release/v6.7.0/Indirect/Bugfixes/35298.rst
  docs/source/release/v6.7.0/Indirect/New_features/34633.rst
  docs/source/release/v6.7.0/Reflectometry/Bugfixes/34844.rst
  docs/source/release/v6.7.0/Reflectometry/Bugfixes/35277.rst
  docs/source/release/v6.7.0/Reflectometry/Bugfixes/35309.rst
  docs/source/release/v6.7.0/Reflectometry/Bugfixes/35333.rst
  docs/source/release/v6.7.0/Reflectometry/New_features/35279.rst
  docs/source/release/v6.7.0/Workbench/Bugfixes/31662.rst
  docs/source/release/v6.7.0/Workbench/Bugfixes/33269.rst
  docs/source/release/v6.7.0/Workbench/New_features/35092.rst
  docs/source/release/v6.7.0/framework.rst
  docs/source/workbench/instrumentviewer.rst
Labels: Documentation

#35623 Switch to appy or not apply goniometer tilt in LoadWANDSCD
  Framework/PythonInterface/plugins/algorithms/LoadWANDSCD.py
  Framework/PythonInterface/test/python/plugins/algorithms/LoadWANDSCDTest.py
  Testing/Data/UnitTest/HB2C_475936.nxs.h5.md5
  docs/source/algorithms/LoadWANDSCD-v1.rst
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/New_features/35623.rst
Labels: Diffraction, Single Crystal

#35615 Fix for sequential and Serial fit buttons in Eng Diff interface
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/plot_view.py
Labels: Bug, Diffraction

#35622 Fix live data listener properties section in Start Live Data Dialogue
  qt/widgets/plugins/algorithm_dialogs/inc/MantidQtWidgets/Plugins/AlgorithmDialogs/StartLiveDataDialog.h
  qt/widgets/plugins/algorithm_dialogs/src/StartLiveDataDialog.cpp
Labels: High Priority, Bug, Framework

#35591 Update muon testing docs
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_ARGUS.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_Analysis_MUSR.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_Analysis_PSI.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_EMU.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_HIFI.rst
  dev-docs/source/images/MuonAnalysisTests/HIFI-TF-Result.png
Labels: Documentation, ISIS Team: Spectroscopy

#35564 Update ALFView test docs
  dev-docs/source/Testing/DirectInelastic/ALFViewTests.rst
Labels: Documentation, ISIS Team: Excitations/Vesuvio

#35606 Add note to SANS GUI manual testing docs about known issue
  dev-docs/source/Testing/SANSGUI/ISISSANSGUITests.rst
Labels: Documentation, ISIS Team: LSS

#35627 Update Mslice SHA
  scripts/ExternalInterfaces/CMakeLists.txt
Labels: High Priority

#35618 Remove ipykernel pin to fix qtconsole
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantidworkbench/meta.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: High Priority

#35628 Update mslice SHA pre-beta 6.7.0
  scripts/ExternalInterfaces/CMakeLists.txt
Labels: High Priority

#35634 Fix bug in save/load grouping workspace
  Framework/Algorithms/src/CompareWorkspaces.cpp
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  Framework/DataHandling/src/SaveNexusProcessed.cpp
Labels: Bug, Found in Beta
