Repository mantidproject/mantid, pull requests merged in 2023-04, with the labels that each got.

#34811 Updated property handler to remove and rename ties when a function is removed from the fitting widget
  docs/source/release/v6.6.0/Workbench/Bugfixes/31662.rst
  qt/widgets/common/inc/MantidQtWidgets/Common/PropertyHandler.h
  qt/widgets/common/src/PropertyHandler.cpp
  qt/widgets/common/test/FitPropertyBrowserTest.h
Labels: ISIS Team: Core

#35286 Support multiple phases in GSAS tab
  docs/source/release/v6.7.0/Diffraction/Engineering/New_features/35286.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/call_G2sc.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/test/test_gsas2_model.py
Labels: Diffraction, ISIS Team: Diffraction

#35412 Improve Colours on the Preview Tab's ROI Selectors
  docs/source/release/v6.7.0/Reflectometry/Bugfixes/35349.rst
  qt/python/mantidqt/mantidqt/widgets/regionselector/presenter.py
  qt/python/mantidqt/mantidqt/widgets/regionselector/test/test_regionselector_presenter.py
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/ROIType.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/PreviewPresenterTest.h
  qt/widgets/regionselector/inc/MantidQtWidgets/RegionSelector/IRegionSelector.h
  qt/widgets/regionselector/inc/MantidQtWidgets/RegionSelector/RegionSelector.h
  qt/widgets/regionselector/src/RegionSelector.cpp
  qt/widgets/regionselector/test/MockRegionSelector.h
Labels: Reflectometry, GUI, ISIS Team: LSS

#35376 Allow Linear Detectors on the Preview Tab
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISSumBanks.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISSumBanksTest.py
  docs/source/release/v6.7.0/Reflectometry/New_features/35264_preview_1d.rst
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/test/Preview/PreviewPresenterTest.h
Labels: Reflectometry, GUI, ISIS Team: LSS

#35341 Disable ALFView when running algorithms
  docs/source/release/v6.7.0/Direct_Geometry/General/New_features/35114.rst
  qt/scientific_interfaces/Direct/ALFAnalysisPresenter.cpp
  qt/scientific_interfaces/Direct/ALFAnalysisView.cpp
  qt/scientific_interfaces/Direct/ALFAnalysisView.h
  qt/scientific_interfaces/Direct/ALFInstrumentPresenter.cpp
  qt/scientific_interfaces/Direct/ALFInstrumentView.cpp
  qt/scientific_interfaces/Direct/ALFInstrumentView.h
  qt/scientific_interfaces/Direct/ALFView.cpp
  qt/scientific_interfaces/Direct/ALFView.h
  qt/scientific_interfaces/Direct/test/ALFAnalysisMocks.h
  qt/scientific_interfaces/Direct/test/ALFAnalysisPresenterTest.h
  qt/scientific_interfaces/Direct/test/ALFInstrumentMocks.h
  qt/scientific_interfaces/Direct/test/ALFInstrumentPresenterTest.h
  qt/widgets/plotting/src/PreviewPlot.cpp
Labels: Direct Inelastic, ISIS Team: Excitations/Vesuvio

#35397 Make Preview Reduction Use All Values From Experiment Settings Tab
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISLoadAndProcess.py
  Framework/PythonInterface/test/python/plugins/algorithms/ReflectometryReductionOneLiveDataTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISLoadAndProcessTest.py
  docs/source/release/v6.7.0/Reflectometry/Bugfixes/35276.rst
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/RowProcessingAlgorithm.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewJobManager.cpp
  qt/scientific_interfaces/ISISReflectometry/test/Preview/PreviewJobManagerTest.h
Labels: Reflectometry, ISIS Team: LSS

#35420 Update technical release manager instructions
  dev-docs/source/ReleaseChecklist.rst
  dev-docs/source/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_EMU.rst
  dev-docs/source/Workbench/RunningWorkbench.rst
Labels: Documentation, ISIS Team: Core, Added during Sprint

#35431 Fix small issues for TimeROI discovered by coverity
  Framework/Kernel/src/FilteredTimeSeriesProperty.cpp
  Framework/Kernel/src/LogFilter.cpp
  Framework/Kernel/src/TimeROI.cpp
Labels: Maintenance

#35423 Event filtering release notes
  docs/source/release/v6.7.0/Diffraction/Powder/New_features/35284.rst
  docs/source/release/v6.7.0/Framework/Data_Objects/New_features/34908.rst
  docs/source/release/v6.7.0/Reflectometry/Bugfixes/35277.rst
  docs/source/release/v6.7.0/framework.rst
Labels: Documentation

#35436 Make `CleanFileCacheTest` independent of system time
  Framework/PythonInterface/test/python/plugins/algorithms/CleanFileCacheTest.py
Labels: DevOps

#35413 Enable default sitich output parameters to be pulled from IPF
  instrument/unit_testing/REFL_Parameters_Experiment.xml
  qt/scientific_interfaces/ISISReflectometry/Common/OptionDefaults.cpp
  qt/scientific_interfaces/ISISReflectometry/Common/OptionDefaults.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/ExperimentOptionDefaults.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Instrument/InstrumentOptionDefaults.cpp
  qt/scientific_interfaces/ISISReflectometry/test/Experiment/ExperimentOptionDefaultsTest.h
Labels: Reflectometry, GUI, ISIS Team: LSS

#35453 Uncomment debug print statement
  Testing/SystemTests/tests/qt/AlgorithmDialogsStartupTestBase.py
Labels: DevOps

#34912 Reimplement Meier function using C++
  Framework/CurveFitting/CMakeLists.txt
  Framework/CurveFitting/inc/MantidCurveFitting/Functions/Meier.h
  Framework/CurveFitting/src/Functions/Meier.cpp
  Framework/CurveFitting/test/Functions/MeierTest.h
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/functions/Meier.py
  Framework/PythonInterface/test/python/plugins/functions/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/functions/MeierTest.py
  docs/source/fitting/fitfunctions/Meier.rst
  docs/source/release/v6.7.0/Framework/Fit_Functions/New_features/34912.rst
Labels: Maintenance

#35452 Update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation, Maintenance

#35415 Fix for crop workspace memory bug
  Framework/Algorithms/inc/MantidAlgorithms/ExtractSpectra.h
  Framework/Algorithms/src/ExtractFFTSpectrum.cpp
  Framework/Algorithms/src/ExtractSpectra.cpp
  Framework/Algorithms/test/CropWorkspaceTest.h
  Framework/Algorithms/test/ExtractSpectraTest.h
  Framework/HistogramData/CMakeLists.txt
  Framework/HistogramData/inc/MantidHistogramData/Slice.h
  Framework/HistogramData/src/Slice.cpp
  Framework/HistogramData/test/SliceTest.h
  docs/source/release/v6.7.0/Workbench/Bugfixes/34735.rst
Labels: Bug, ISIS Team: Core

#35463 Pin qtconsole to avoid crash in jupyter console
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantidworkbench/meta.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: High Priority, Bug, ISIS Team: Core

#35216 Bug fix for Mantid not opening on windows with a non-ascii username
  Framework/Kernel/src/ConfigService.cpp
  Framework/PythonInterface/test/python/mantid/kernel/ConfigServiceTest.py
  docs/source/release/v6.7.0/Workbench/Bugfixes/35091.rst
Labels: ISIS Team: Core, Windows Only

#35428 Fix bug that prevented workspace update in fit function
  docs/source/release/v6.7.0/Framework/Fit_Functions/Bugfixes/35426.rst
  docs/source/release/v6.7.0/Indirect/Bugfixes/35426.rst
  qt/widgets/common/src/FunctionTreeView.cpp
Labels: Bug, ISIS Team: Spectroscopy, Reported By User

#35334 Tidy up pearl output files naming and save directories
  Testing/SystemTests/tests/framework/ISIS_PowderPearlTest.py
  docs/source/release/v6.7.0/Diffraction/Powder/Improvements/35334.rst
  scripts/Diffraction/isis_powder/abstract_inst.py
  scripts/Diffraction/isis_powder/pearl.py
  scripts/Diffraction/isis_powder/pearl_routines/pearl_output.py
Labels: Diffraction, Powder, ISIS Team: Diffraction

#35449 Add Q-Spacing Output for OSIRIS Instrument in Indirect Diffraction UI
  docs/source/release/v6.7.0/Indirect/New_features/35449.rst
  qt/scientific_interfaces/Indirect/IndirectDiffractionReduction.cpp
Labels: ISIS Team: Spectroscopy

#35429 Fixed crash in indirect data analysis
  docs/source/release/v6.7.0/Indirect/Bugfixes/35427.rst
  qt/scientific_interfaces/Indirect/IndirectFitDataPresenter.cpp
  qt/scientific_interfaces/Indirect/IndirectFitDataPresenter.h
Labels: ISIS Team: Spectroscopy

#35434 Upgrade Qt to 5.15.8
  Framework/Geometry/inc/MantidGeometry/Crystal/BasicHKLFilters.h
  Framework/Geometry/test/BasicHKLFiltersTest.h
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid/meta.yaml
  conda/recipes/mantidqt/meta.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
  qt/applications/workbench/workbench/plotting/mantidfigurecanvas.py
Labels: ISIS Team: Core, Dependencies

#35481 Move pipeline stage to avoid build-up of nightly packages on Anaconda
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
Labels: High Priority, ISIS Team: Core, Added during Sprint, DevOps

#35466 Simplified child workspace names in stitich group
  Framework/Algorithms/src/Stitch1DMany.cpp
  Framework/Algorithms/test/Stitch1DManyTest.h
  docs/source/release/v6.7.0/Reflectometry/Bugfixes/34842.rst
Labels: Bug, Reflectometry, ISIS Team: LSS
