Repository mantidproject/mantid, pull requests merged in 2023-02, with the labels that each got.

#35117 Normalise sample by vanadium before dSpacing conversion
  qt/scientific_interfaces/Direct/ALFInstrumentModel.cpp
  qt/scientific_interfaces/Direct/test/ALFInstrumentModelTest.h
Labels: Bug, Direct Inelastic, Reported By User, ISIS Team: Excitations/Vesuvio

#35106 Fix access violation crash in Muon Analysis Interface
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/corrections_tab_widget/background_corrections_model.py
Labels: Bug, ISIS Team: Spectroscopy

#35103 Update sliceviewer manual testing docs
  dev-docs/source/Testing/SliceViewer/SliceViewer.rst
Labels: Documentation, ISIS Team: Core

#35110 Reconnect ProjectionSurface on ALFView after reset
  docs/source/release/v6.7.0/Direct_Geometry/General/Bugfixes/35108.rst
  qt/scientific_interfaces/Direct/ALFInstrumentModel.cpp
  qt/scientific_interfaces/Direct/ALFInstrumentView.cpp
  qt/scientific_interfaces/Direct/ALFInstrumentView.h
Labels: Bug, Direct Inelastic, Found in Beta, ISIS Team: Excitations/Vesuvio

#34926 Allow use of True and False in Option Text Entry in the Refl GUI
  docs/source/release/v6.6.0/Reflectometry/Bugfixes/34844.rst
  qt/scientific_interfaces/ISISReflectometry/Reduction/ParseReflectometryStrings.cpp
  qt/scientific_interfaces/ISISReflectometry/test/Experiment/ExperimentPresenterTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Reduction/ParseReflectometryStringsTest.h
Labels: Bug, Reflectometry, ISIS Team: LSS

#35112 Get current device pixel ratio for Zoombox
  docs/source/release/v6.7.0/Workbench/Bugfixes/34079.rst
  qt/applications/workbench/workbench/plotting/mantidfigurecanvas.py
  qt/applications/workbench/workbench/plotting/test/test_mantidfigurecanvas.py
Labels: Bug, macOS Only, ISIS Team: Core, Found in Beta

#35128 InstrumentView Control points too large
  qt/widgets/instrumentview/src/Shape2D.cpp
Labels: Bug, ISIS Team: Core

#35136 Corrected merged log for D16
  instrument/D16B_Parameters.xml
  instrument/D16_Parameters.xml
Labels: SANS, ILL Team

#35111 Update WSL developer documentation to refer to X Server use
  dev-docs/source/WindowsSubsystemForLinux.rst
Labels: Documentation, Maintenance

#35130 Minor clarification on SANS GUI instructions
  dev-docs/source/Testing/SANSGUI/ISISSANSGUITests.rst
Labels: Documentation, ISIS Team: LSS

#35151 Tidy 6.6 SANS Release Notes
  docs/source/release/v6.6.0/sans.rst
Labels: SANS, Documentation

#35132 muon GUI vanishing data
  docs/source/release/v6.6.0/Muon/MA_FDA/Bugfixes/35125.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/contexts/muon_context.py
  qt/python/mantidqtinterfaces/test/Muon/muon_context_test.py
Labels: Bug, ISIS Team: Spectroscopy

#35068 Load Dialog crash after closing when loading
  docs/source/release/v6.7.0/Workbench/Bugfixes/35056.rst
  qt/widgets/common/inc/MantidQtWidgets/Common/FindFilesThreadPoolManager.h
  qt/widgets/common/src/FindFilesThreadPoolManager.cpp
  qt/widgets/plugins/algorithm_dialogs/inc/MantidQtWidgets/Plugins/AlgorithmDialogs/LoadDialog.h
  qt/widgets/plugins/algorithm_dialogs/src/LoadDialog.cpp
Labels: Bug, Extra Attention, ISIS Team: Core

#35143 Tidy Diffraction 6.6 Release Notes
  docs/source/images/6_6_release/diffraction/DiffractionUpdateEngineeringFitting.png
  docs/source/release/v6.6.0/diffraction.rst
Labels: Diffraction, Documentation

#35139 Fix GSAS-II interaction in Engineering UI
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/model.py
Labels: ISIS Team: Diffraction, Windows Only

#35161 Lagrange: fix for single point reduction
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/LagrangeILLReduction.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/LagrangeILLReductionTest.py
  Testing/Data/UnitTest/ILL/LAGRANGE/014220.md5
  docs/source/release/v6.7.0/Direct_Geometry/General/Bugfixes/35159.rst
Labels: Bug, Direct Inelastic, ILL Team

#35163 Tidy 6.6 Release Notes Index
  docs/source/images/6_6_release/MajorChanges.png
  docs/source/release/v6.6.0/index.rst
Labels: Documentation

#35169 Divide two theta by two for rotation angle calculation
  qt/scientific_interfaces/Direct/ALFAnalysisModel.cpp
  qt/scientific_interfaces/Direct/test/ALFAnalysisModelTest.h
Labels: Bug, Direct Inelastic, Found in Beta, ISIS Team: Excitations/Vesuvio

#35174 Fxed muon bug caused by spaces in run bar
  docs/source/release/v6.6.0/Muon/MA_FDA/Bugfixes/35153.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/utilities/run_string_utils.py
  qt/python/mantidqtinterfaces/test/Muon/utilities/run_string_utils_conversion_test.py
Labels: ISIS Team: Spectroscopy

#35004 Fix for FSG when fitting spectra from same workspace
  Framework/Algorithms/src/GeneratePythonFitScript.cpp
  docs/source/images/FitScriptGenerator_SequentialFit.PNG
  docs/source/images/FitScriptGenerator_SequentialFit.png
  docs/source/images/FitScriptGenerator_SimultaneousFit.PNG
  docs/source/images/FitScriptGenerator_SimultaneousFit.png
  docs/source/interfaces/general/Fit Script Generator.rst
  docs/source/release/v6.7.0/Workbench/Bugfixes/35004.rst
  scripts/templates/GeneratePythonFitScript_SequentialFit.py.in
  scripts/templates/GeneratePythonFitScript_SimultaneousFit.py.in
  scripts/templates/GeneratePythonFitScript_VariableSetup.py.in
  scripts/templates/reference/generate_sequential_fit_script_reference_file.py
  scripts/templates/reference/generate_simultaneous_fit_script_reference_file.py
Labels: Bug, ISIS Team: Core

#35109 New parameters for ILL/D1B
  instrument/D1B_Parameters.xml
Labels: ILL Team

#35154 Tidy 6.6 Framework release notes
  docs/source/images/6_6_release/Framework/loadtimes.png
  docs/source/release/v6.6.0/framework.rst
Labels: Has Conflicts

#35175 Add information on how time average mean works
  docs/source/concepts/EventFiltering.rst
Labels: Documentation

#35126 Windows compilation warnings fix
  Framework/Algorithms/CMakeLists.txt
  buildconfig/CMake/WindowsSetup.cmake
  qt/scientific_interfaces/Indirect/CMakeLists.txt
Labels: ISIS Team: Core, Windows Only

#35079 Use correct signature when connecting slot
  qt/widgets/plugins/algorithm_dialogs/src/StartLiveDataDialog.cpp
Labels: Bug, ISIS Team: Core

#35142 Muon GUI with nxs_v1
  Framework/DataHandling/src/LoadMuonNexusV2.cpp
  docs/source/release/v6.6.0/Muon/Algorithms/New_features/35141.rst
  docs/source/release/v6.6.0/Muon/MA_FDA/New_features/35141.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/utilities/muon_file_utils.py
  qt/python/mantidqtinterfaces/test/Muon/utilities/muon_file_utils_test.py
Labels: ISIS Team: Spectroscopy

#35186 Change sample changer group option name
  docs/source/release/v6.6.0/Indirect/New_features/34636.rst
  qt/scientific_interfaces/Indirect/ISISEnergyTransfer.cpp
  qt/scientific_interfaces/Indirect/ISISEnergyTransfer.ui
Labels: Indirect Inelastic, Induction, ISIS Team: Spectroscopy

#34910 Update the dev docs for obtaining a fit benchmark
  dev-docs/source/ObtainingABenchmarkForMantidFitting.rst
Labels: Documentation, ISIS Team: Core

#35104 Migrate from obselete QGLWidget to QOpenGLWidget
  dev-docs/source/CLion.rst
  dev-docs/source/GettingStarted/GettingStartedCondaOSX.rst
  dev-docs/source/PyCharm.rst
  dev-docs/source/VSCode.rst
  dev-docs/source/macos-opengl-version-warning.txt
  docs/source/release/v6.7.0/Workbench/InstrumentViewer/Bugfixes/35103.rst
  qt/applications/workbench/workbench/app/start.py
  qt/widgets/instrumentview/CMakeLists.txt
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/GLDisplay.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/GLObject.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/IGLDisplay.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/InstrumentWidget.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/UnwrappedSurface.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/Viewport.h
  qt/widgets/instrumentview/src/DetXMLFile.cpp
  qt/widgets/instrumentview/src/GLDisplay.cpp
  qt/widgets/instrumentview/src/GLObject.cpp
  qt/widgets/instrumentview/src/InstrumentWidget.cpp
  qt/widgets/instrumentview/src/InstrumentWidgetMaskTab.cpp
  qt/widgets/instrumentview/src/InstrumentWidgetPickTab.cpp
  qt/widgets/instrumentview/src/PeakOverlay.cpp
  qt/widgets/instrumentview/src/ProjectionSurface.cpp
  qt/widgets/instrumentview/src/Shape2DCollection.cpp
  qt/widgets/instrumentview/src/UnwrappedSurface.cpp
  qt/widgets/instrumentview/src/Viewport.cpp
  qt/widgets/instrumentview/test/InstrumentWidget/InstrumentWidgetTest.h
  qt/widgets/plugins/algorithm_dialogs/CMakeLists.txt
  qt/widgets/plugins/algorithm_dialogs/inc/MantidQtWidgets/Plugins/AlgorithmDialogs/MantidGLWidget.h
  qt/widgets/plugins/algorithm_dialogs/src/MantidGLWidget.cpp
Labels: macOS Only, ISIS Team: Core

#34851 Enable Ninja Builds in Visual Studio
  CMakePresets.json
  buildconfig/CMake/Bootstrap.cmake
  buildconfig/CMake/QtTargetFunctions.cmake
  buildconfig/CMake/SipQtTargetFunctions.cmake
  buildconfig/CMake/WindowsSetup.cmake
  buildconfig/windows/visual-studio_conda_ninja.bat.in
  dev-docs/source/GettingStarted/GettingStartedCondaWindows.rst
Labels: ISIS Team: Diffraction, Windows Only

#35183 Fixes to the Inelastic Data Manipulation notes
  docs/source/interfaces/indirect/Inelastic Data Manipulation.rst
Labels: Documentation

#35179 Simplify and deduplicate CMake presets
  CMakePresets.json
Labels: Maintenance

#35182 Channels in instrument definition of ILL/SALSA
  Framework/DataHandling/src/LoadILLSALSA.cpp
  instrument/SALSA_Definition.xml
Labels: ILL Team

#35178 LAGRANGE: Add instrument definition
  instrument/Facilities.xml
  instrument/Lagrange_Definition.xml
Labels: Direct Inelastic, ILL Team

#35121 Only publish from a single Jenkins pipeline by default
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
  dev-docs/source/ReleaseChecklist.rst
Labels: Extra Attention, ISIS Team: Core

#35090 Maintain aspect ratios in 2D instrument views
  docs/source/images/Workbench/InstrumentViewer/DisplaySettings.png
  docs/source/images/Workbench/InstrumentViewer/Overview.png
  docs/source/images/Workbench/InstrumentViewer/PickTab.png
  docs/source/images/Workbench/InstrumentViewer/RenderTab.png
  docs/source/release/v6.7.0/Workbench/InstrumentViewer/New_features/35090 Maintain aspect ratios in 2D views.rst
  qt/python/mantidqt/mantidqt/widgets/instrumentview/test/test_instrumentview_io.py
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/QtPreviewDockedWidgets.cpp
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/InstrumentWidget.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/InstrumentWidgetRenderTab.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/PanelsSurface.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/ProjectionSurface.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/RotationSurface.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/UnwrappedCylinder.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/UnwrappedSphere.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/UnwrappedSurface.h
  qt/widgets/instrumentview/src/InstrumentDisplay.cpp
  qt/widgets/instrumentview/src/InstrumentWidget.cpp
  qt/widgets/instrumentview/src/InstrumentWidgetDecoder.cpp
  qt/widgets/instrumentview/src/InstrumentWidgetEncoder.cpp
  qt/widgets/instrumentview/src/InstrumentWidgetRenderTab.cpp
  qt/widgets/instrumentview/src/PanelsSurface.cpp
  qt/widgets/instrumentview/src/ProjectionSurface.cpp
  qt/widgets/instrumentview/src/QtDisplay.cpp
  qt/widgets/instrumentview/src/RotationSurface.cpp
  qt/widgets/instrumentview/src/UnwrappedCylinder.cpp
  qt/widgets/instrumentview/src/UnwrappedSphere.cpp
  qt/widgets/instrumentview/src/UnwrappedSurface.cpp
  qt/widgets/instrumentview/test/InstrumentWidget/InstrumentWidgetTest.h
Labels: GUI, ISIS Team: Diffraction

#35171 Added the ability read the notes from ISIS nexus files
  Framework/DataHandling/src/LoadISISNexus2.cpp
  Framework/DataHandling/test/LoadISISNexusTest.h
  docs/source/release/v6.7.0/Framework/Data_Objects/New_features/34908.rst
  docs/source/release/v6.7.0/Muon/Algorithms/New_features/34908.rst
  docs/source/release/v6.7.0/Muon/MA_FDA/New_features/34908.rst
Labels: Framework, Extra Attention, ISIS Team: Spectroscopy

#35207 Correct Visual Studio 2022 toolset prefix from vs to just v
  CMakePresets.json
Labels: ISIS Team: Diffraction

#35070 Allow bank layout to be specified in side by side view
  Framework/API/src/ExperimentInfo.cpp
  Framework/Crystal/src/SortHKL.cpp
  Framework/DataHandling/src/LoadANSTOHelper.cpp
  Framework/DataHandling/src/LoadEMU.cpp
  Framework/DataHandling/src/LoadILLSANS.cpp
  Framework/DataObjects/src/BasePeak.cpp
  Framework/Geometry/inc/MantidGeometry/IComponent.h
  Framework/Geometry/inc/MantidGeometry/Instrument/Component.h
  Framework/Geometry/inc/MantidGeometry/Instrument/DetectorGroup.h
  Framework/Geometry/inc/MantidGeometry/Instrument/InstrumentDefinitionParser.h
  Framework/Geometry/src/Instrument/Component.cpp
  Framework/Geometry/src/Instrument/DetectorGroup.cpp
  Framework/Geometry/src/Instrument/InstrumentDefinitionParser.cpp
  Framework/Geometry/src/Rendering/GeometryHandler.cpp
  Framework/Kernel/inc/MantidKernel/V2D.h
  Framework/PythonInterface/mantid/geometry/src/Exports/Instrument.cpp
  docs/source/concepts/InstrumentDefinitionFile.rst
  docs/source/release/v6.7.0/Workbench/InstrumentViewer/New_features/35070 Support bank centre overrides in IDF.rst
  docs/source/workbench/instrumentviewer.rst
  instrument/SXD_Definition.xml
  instrument/Schema/IDF/1.0/IDFSchema.xsd
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/PanelsSurface.h
  qt/widgets/instrumentview/src/PanelsSurface.cpp
Labels: ISIS Team: Diffraction

#35203 Add groovy script to clean single node to dev docs
  dev-docs/source/JenkinsConfiguration.rst
Labels: Maintenance, DevOps

#35131 Add ISIS Reflectometry GUI Preview Tab manual testing instructions
  dev-docs/source/Testing/ReflectometryGUI/ReflectometryGUITests.rst
Labels: Reflectometry, Documentation, Maintenance, ISIS Team: LSS

#35196 Shut down FrameworkManager on close
  dev-docs/source/CLion.rst
  dev-docs/source/PyCharm.rst
  dev-docs/source/VSCode.rst
  dev-docs/source/Workbench/RunningWorkbench.rst
  dev-docs/source/Workbench/index.rst
  qt/applications/workbench/workbench/app/start.py
Labels: Bug, ISIS Team: Core, Linux Only

#35222 Increase number of neighbors in detector search
  Framework/API/src/DetectorSearcher.cpp
  Testing/Data/SystemTest/WISHPredictedSingleCrystalPeaks.nxs.md5
  Testing/SystemTests/tests/framework/ISIS_WISHSingleCrystalReduction.py
  Testing/SystemTests/tests/framework/PredictPeaksTest.py
  docs/source/release/v6.7.0/Diffraction/Single_Crystal/Bugfixes/35222.rst
Labels: Bug, Diffraction, Single Crystal

#35206 D16B commissioning
  Framework/DataHandling/inc/MantidDataHandling/LoadILLSANS.h
  Framework/DataHandling/src/LoadILLSANS.cpp
  Framework/DataHandling/test/LoadILLSANSTest.h
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLAutoProcess.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLCommon.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLIntegration.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLMultiProcess.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLParameterScan.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLReduction.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLReduction2.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSStitch.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/SANSILLIntegrationTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/SANSILLParameterScanTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/SANSILLReduction2Test.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/SANSILLReductionTest.py
  Testing/Data/UnitTest/ILL/D16/066416.nxs.md5
  Testing/Data/UnitTest/ILL/D16/212_8-02-927_023094-23354_sample.nxs.md5
  Testing/Data/UnitTest/ILL/D16/212_8-02-927_046364-046624_container.nxs.md5
  Testing/Data/UnitTest/ILL/D16/213_exp_9-13-1035_25786-26046.nxs.md5
  Testing/Data/UnitTest/ILL/D16/sensitivity_d16.nxs.md5
  docs/source/interfaces/ILL/SimpleScanViewer.rst
  docs/source/release/v6.7.0/SANS/Bugfixes/35092.rst
  docs/source/release/v6.7.0/SANS/New_features/35092.rst
  docs/source/release/v6.7.0/Workbench/New_features/35092.rst
  instrument/D16B_Definition.xml
  qt/python/mantidqtinterfaces/mantidqtinterfaces/simplescanviewer/rectangle_controller.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/simplescanviewer/rectangle_plot.py
  qt/python/mantidqtinterfaces/test/SimpleScanViewer/RectanglePlotTest.py
Labels: SANS, ILL Team

#35227 Added control for index overflow in isMonitor methods
  Framework/API/test/DetectorInfoTest.h
  Framework/Beamline/src/DetectorInfo.cpp
  Framework/Beamline/test/DetectorInfoTest.h
  Framework/DataHandling/test/LoadILLDiffractionTest.h
  docs/source/release/v6.7.0/Framework/Beamline/BugFixes/.gitkeep
  docs/source/release/v6.7.0/Framework/Beamline/BugFixes/35227.rst
Labels: Bug, ILL Team

#35231 Avoid calling OpenGL functions too early in Instrument View
  qt/widgets/instrumentview/src/InstrumentWidget.cpp
  qt/widgets/instrumentview/src/Viewport.cpp
  qt/widgets/instrumentview/test/InstrumentWidget/InstrumentWidgetTest.h
Labels: Bug, ISIS Team: Core

#35212 Fixed buggy logger call
  Framework/PythonInterface/plugins/algorithms/LoadFullprofFile.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/DirectILLCollectData.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/PowderILLDetectorScan.py
  docs/source/release/v6.7.0/Framework/Algorithms/Bugfixes/Used/35212.rst
Labels: Bug, ILL Team

#34893 Keep error reporter open if it fails to send report
  dev-docs/source/Testing/ErrorReporter-ProjectRecovery/ErrorReporterTesting.rst
  docs/source/release/v6.6.0/Workbench/Bugfixes/33269.rst
  qt/python/mantidqt/mantidqt/dialogs/errorreports/presenter.py
  qt/python/mantidqt/mantidqt/dialogs/errorreports/report.py
Labels: ISIS Team: Core

#35124 Update Engineering Diffraction instructions
  dev-docs/source/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.rst
Labels: Documentation, ISIS Team: Diffraction

#35185 Add extra validation to GSAS2 path in Engineering UI
  docs/source/release/v6.7.0/Diffraction/Engineering/Bugfixes/35185 HandleErrorOnRunningGSASRefinement.rst
  qt/python/mantidqt/mantidqt/_common.sip
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/settings/settings_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/settings/settings_view.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/test/test_gsas2_model.py
  qt/widgets/common/src/FileFinderWidget.cpp
Labels: ISIS Team: Diffraction

#35219 Move QtJobRunner and IJobRunner to the MantidQtWidgetsCommon library
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchPresenterFactory.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/IBatchView.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/QtBatchView.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Common/CMakeLists.txt
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewJobManager.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewJobManager.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenterFactory.h
  qt/scientific_interfaces/ISISReflectometry/test/Batch/BatchPresenterTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/PreviewJobManagerTest.h
  qt/scientific_interfaces/ISISReflectometry/test/ReflMockObjects.h
  qt/widgets/common/CMakeLists.txt
  qt/widgets/common/inc/MantidQtWidgets/Common/IJobRunner.h
  qt/widgets/common/inc/MantidQtWidgets/Common/MockJobRunner.h
  qt/widgets/common/inc/MantidQtWidgets/Common/QtJobRunner.h
  qt/widgets/common/src/QtJobRunner.cpp
Labels: Reflectometry, Direct Inelastic, Maintenance, ISIS Team: Excitations/Vesuvio

#35133 Fix failing doctests
  docs/source/algorithms/ConvolveWorkspaces-v1.rst
  docs/source/algorithms/CopyInstrumentParameters-v1.rst
  docs/source/algorithms/CorelliCalibrationDatabase-v1.rst
  docs/source/algorithms/CorrectTOFAxis-v1.rst
  docs/source/algorithms/CreateEPP-v1.rst
  docs/source/algorithms/CreateSampleWorkspace-v1.rst
  docs/source/algorithms/EnggSaveGSASIIFitResultsToHDF5-v1.rst
  docs/source/algorithms/FindEPP-v2.rst
  docs/source/algorithms/FindPeaks-v1.rst
  docs/source/algorithms/Fit-v1.rst
  docs/source/algorithms/FitGaussian-v1.rst
  docs/source/algorithms/FitPeaks-v1.rst
  docs/source/algorithms/GetDetectorOffsets-v1.rst
  docs/source/algorithms/HB3AIntegrateDetectorPeaks-v1.rst
  docs/source/algorithms/IntegrateEPP-v1.rst
  docs/source/algorithms/Integration-v1.rst
  docs/source/algorithms/LoadEMU-v1.rst
  docs/source/algorithms/LoadILLTOF-v2.rst
  docs/source/algorithms/LoadSESANS-v1.rst
  docs/source/algorithms/MSDFit-v1.rst
  docs/source/algorithms/MatchPeaks-v1.rst
  docs/source/algorithms/MayersSampleCorrection-v1.rst
  docs/source/algorithms/PolDiffILLReduction-v1.rst
  docs/source/algorithms/SaveReflectometryAscii-v1.rst
  docs/source/algorithms/SaveVulcanGSS-v1.rst
  docs/source/algorithms/SpecularReflectionPositionCorrect-v2.rst
  docs/source/techniques/PolarisedDiffractionILL.rst
  docs/source/techniques/ReflectometryILL.rst
Labels: Documentation, Maintenance

#35213 Update Mantid basic course
  docs/source/images/600px-ImageViewer.png
  docs/source/images/ColourFillPlotMar11060.png
  docs/source/images/MBC_Ragged.png
  docs/source/images/MBC_Rebinned.png
  docs/source/images/PickTabSelectWholeInstButton.png
  docs/source/images/PickTabToolButtons.png
  docs/source/images/SampleLogs.png
  docs/source/plotting/1DPlotsHelp.rst
  docs/source/tutorials/mantid_basic_course/connecting_data_to_instruments/03_investigating_data.rst
  docs/source/tutorials/mantid_basic_course/connecting_data_to_instruments/04_masking_and_grouping.rst
  docs/source/tutorials/mantid_basic_course/connecting_data_to_instruments/06_sample_logs.rst
  docs/source/tutorials/mantid_basic_course/fitting_data/02_complex_case.rst
Labels: Documentation, Maintenance

#34931 Bug superplot tight layout
  qt/applications/workbench/workbench/plugins/workspacewidget.py
  qt/python/mantidqt/mantidqt/plotting/functions.py
  qt/python/mantidqt/mantidqt/widgets/superplot/presenter.py
  qt/python/mantidqt/mantidqt/widgets/superplot/test/test_superplot_presenter.py
Labels: Bug

#35273 Make LoadGeometry::isNexus more specific
  Framework/DataHandling/inc/MantidDataHandling/LoadGeometry.h
  Framework/DataHandling/src/LoadGeometry.cpp
  Framework/DataHandling/test/LoadEventNexusTest.h
  Framework/Kernel/inc/MantidKernel/NexusDescriptor.h
  Framework/Kernel/src/NexusDescriptor.cpp
  Testing/Data/UnitTest/MAR28482.nxs.md5
Labels: Framework

#35284 More than one detector height range in ILLPowderDetectorScan
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/PowderILLDetectorScan.py
  Testing/SystemTests/tests/framework/ILLPowderDetectorScanTest.py
  Testing/SystemTests/tests/framework/reference/D2B_1D.nxs.md5
  Testing/SystemTests/tests/framework/reference/D2B_2D.nxs.md5
  Testing/SystemTests/tests/framework/reference/D2B_2DTubes.nxs.md5
  Testing/SystemTests/tests/framework/reference/D2B_LowCounts.nxs.md5
  docs/source/release/v6.7.0/Diffraction/Powder/New_features/35284.rst
Labels: ILL Team

#35218 LoadAndMerge: clean up concatenated workspaces
  Framework/PythonInterface/plugins/algorithms/LoadAndMerge.py
  Framework/PythonInterface/test/python/plugins/algorithms/LoadAndMergeTest.py
  docs/source/release/v6.7.0/Framework/Algorithms/Bugfixes/35217.rst
Labels: Bug, ILL Team

#35311 Remove matplotlib version checks
  Framework/PythonInterface/mantid/plots/mantidaxes.py
  Framework/PythonInterface/mantid/plots/modest_image/modest_image.py
  Framework/PythonInterface/plugins/algorithms/StringToPng.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SavePlot1D.py
  Framework/PythonInterface/test/python/mantid/plots/axesfunctionsTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/SavePlot1DTest.py
  qt/applications/workbench/workbench/plotting/figuremanager.py
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/figure.py
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/test/test_plotscriptgenerator.py
  qt/applications/workbench/workbench/plotting/propertiesdialog.py
  qt/python/mantidqt/mantidqt/plotting/functions.py
  qt/python/mantidqt/mantidqt/plotting/mantid_navigation_toolbar.py
  qt/python/mantidqt/mantidqt/plotting/test/test_tiledplots.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/imagestabwidget/test/test_imagestabwidgetpresenter.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/test/test_apply_all_properties.py
  qt/python/mantidqt/mantidqt/widgets/regionselector/presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/DGSPlanner/DGSPlannerGUI.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/DGSPlanner/InstrumentSetupWidget.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/HFIR_4Circle_Reduction/mplgraphicsview3d.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/PyChop/PyChopGui.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/QECoverage/QECoverageGUI.py
Labels: ISIS Team: Core

#35313 Prepend drive to jenkins workspace if missing on VM agents
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
Labels: High Priority, Bug, ISIS Team: Core, Windows Only, DevOps

#35205 Fix Multiple Calib Paths Appearing on GSAS II Tab
  docs/source/release/v6.7.0/Diffraction/Engineering/Bugfixes/34829.txt
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/calibration/model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/calibration/presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/calibration/test/test_calib_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/view.py
  scripts/CMakeLists.txt
  scripts/Engineering/EnggUtils.py
  scripts/Engineering/test/test_EnggUtils.py
Labels: Diffraction, ISIS Team: Diffraction

#35299 IN16B: fix loading spectrometer data
  Framework/DataHandling/src/LoadILLIndirect2.cpp
  Framework/DataHandling/test/LoadILLIndirect2Test.h
  Testing/Data/UnitTest/ILL/IN16B/353970.nxs.md5
  docs/source/release/v6.7.0/Indirect/Bugfixes/35298.rst
Labels: Bug, Indirect Inelastic, ILL Team

#35291 ILL Reflectometry log overwrite
  Framework/DataHandling/src/LoadILLReflectometry.cpp
  Framework/DataHandling/test/LoadILLReflectometryTest.h
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ReflectometryILLAutoProcess.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ReflectometryILLPreprocess.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ReflectometryILLPreprocessTest.py
  docs/source/algorithms/LoadILLReflectometry-v1.rst
  docs/source/algorithms/ReflectometryILLAutoProcess-v1.rst
  docs/source/release/v6.7.0/Reflectometry/New_features/35279.rst
Labels: Reflectometry, ILL Team

#35315 New definition and parameters for D2B
  instrument/D2B_Definition_2023-01-01.xml
  instrument/D2B_Parameters_2023-01-01.xml
Labels: ILL Team

#35233 Update to error report manual test docs
  dev-docs/source/Testing/ErrorReporter-ProjectRecovery/ErrorReporterTesting.rst
Labels: Documentation, Maintenance
