Repository mantidproject/mantid, pull requests merged in 2023-03, with the labels that each got.

#35198 Clean up unused CMake config
  CMakeLists.txt
  CMakePresets.json
  Framework/PythonInterface/CMakeLists.txt
  buildconfig/CMake/Bootstrap.cmake
  buildconfig/CMake/CPackCommon.cmake
  buildconfig/CMake/CPackLinuxSetup.cmake
  buildconfig/CMake/CommonSetup.cmake
  buildconfig/CMake/DarwinSetup.cmake
  buildconfig/CMake/Eigen.cmake
  buildconfig/CMake/FindBoostPython.cmake
  buildconfig/CMake/FindCppcheck.cmake
  buildconfig/CMake/FindCxxTest.cmake
  buildconfig/CMake/FindGitLFS.cmake
  buildconfig/CMake/FindQScintillaQt5.cmake
  buildconfig/CMake/LinuxPackageScripts.cmake
  buildconfig/CMake/MPISetup.cmake
  buildconfig/CMake/MantidUtils.cmake
  buildconfig/CMake/NSIS.template.in
  buildconfig/CMake/PyQtFindImpl.cmake
  buildconfig/CMake/PythonPackageTargetFunctions.cmake
  buildconfig/CMake/QScintillaFindImpl.cmake
  buildconfig/CMake/QtTargetFunctions.cmake
  buildconfig/CMake/Sanitizers.cmake
  buildconfig/CMake/SetMantidSubprojects.cmake
  buildconfig/CMake/SipQtTargetFunctions.cmake
  buildconfig/CMake/TargetFunctions.cmake
  buildconfig/CMake/WindowsNSIS.cmake
  buildconfig/CMake/WindowsNSISQt5.cmake
  buildconfig/CMake/WindowsSetup.cmake
  buildconfig/CMake/WriteSiteCustomize.cmake
  buildconfig/CMake/conda.cmake
  buildconfig/CMake/conda_update_recipe.py.in
  buildconfig/CMake/f2pylibraries.cmake
  buildconfig/CMake/hdf5-config.cmake
  buildconfig/CMake/hdf5-targets-windows.cmake
  buildconfig/windows/pycharm.bat.in
  buildconfig/windows/thirdpartypaths.bat.in
  buildconfig/windows/visual-studio.bat.in
  conda/recipes/mantid/bld.bat
  conda/recipes/mantid/build.sh
  conda/recipes/mantiddocs/build.sh
  conda/recipes/mantidqt/bld.bat
  conda/recipes/mantidqt/build.sh
  conda/recipes/mantidworkbench/bld.bat
  conda/recipes/mantidworkbench/build.sh
  dev-docs/source/BuildingWithCMake.rst
  installers/LinuxInstaller/launcher-template.desktop.in
  installers/LinuxInstaller/modulefile.template
  installers/MacInstaller/CMakeDMGSetup.scpt.in
  installers/MacInstaller/Info.plist.in
  installers/MacInstaller/hdiutilwrap
  installers/MacInstaller/make_package.rb
  installers/MacInstaller/sitecustomize.py
  installers/WinInstaller/.gitignore
  installers/WinInstaller/License.rtf
  installers/WinInstaller/License.txt
  installers/WinInstaller/qt.conf
  qt/applications/workbench/CMakeLists.txt
Labels: Maintenance, ISIS Team: Core

#35323 DrILL: fix for loading export algorithms from rundex
  docs/source/release/v6.7.0/Workbench/Bugfixes/35322.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/drill/model/DrillExportModel.py
Labels: Bug, GUI, ILL Team

#35215 Add a developer document describing the script repository
  dev-docs/source/ScriptRepository.rst
  dev-docs/source/images/scriptrepository-architecture.drawio
  dev-docs/source/images/scriptrepository-architecture.png
  dev-docs/source/index.rst
Labels: Documentation

#35289 Refactoring assert raises in python algorithm tests part 1
  Framework/PythonInterface/plugins/algorithms/Abins.py
  Framework/PythonInterface/plugins/algorithms/ApplyDetectorScanEffCorr.py
  Framework/PythonInterface/plugins/algorithms/ComputeIncoherentDOS.py
  Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/ApplyDetectorScanEffCorrTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/BinWidthAtXTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/CalculateEfficiencyCorrectionTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/CalculateSampleTransmissionTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/ComputeIncoherentDOSTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/CreateCacheFilenameTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/CylinderPaalmanPingsCorrection2Test.py
  Framework/PythonInterface/test/python/plugins/algorithms/DNSComputeDetEffCorrCoefsTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/DNSFlippingRatioCorrTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/DNSMergeRunsTest.py
  scripts/abins/abinsalgorithm.py
Labels: Bug, Maintenance, ISIS Team: Core

#35310 Figaro: loading cycle231 data fix
  Framework/DataHandling/src/LoadILLReflectometry.cpp
  Framework/DataHandling/test/LoadILLReflectometryTest.h
  Testing/Data/UnitTest/ILL/Figaro/745522.nxs.md5
  docs/source/release/v6.7.0/Reflectometry/Bugfixes/35309.rst
Labels: Reflectometry, ILL Team

#35305 Move `AlgorithmRuntimeProps` and `AlgorithmProperties` to Mantid API
  Framework/API/CMakeLists.txt
  Framework/API/inc/MantidAPI/AlgorithmProperties.h
  Framework/API/inc/MantidAPI/AlgorithmRuntimeProps.h
  Framework/API/inc/MantidAPI/IAlgorithmRuntimeProps.h
  Framework/API/src/AlgorithmProperties.cpp
  Framework/API/src/AlgorithmRuntimeProps.cpp
  Framework/API/test/AlgorithmRuntimePropsTest.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/AlgorithmProperties.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchJobAlgorithm.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchJobAlgorithm.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchJobManager.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchJobManager.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/CMakeLists.txt
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/GroupProcessingAlgorithm.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/GroupProcessingAlgorithm.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/IBatchJobManager.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/IBatchPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/RowPreprocessingAlgorithm.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/RowProcessingAlgorithm.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/RowProcessingAlgorithm.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/SumBanksAlgorithm.cpp
  qt/scientific_interfaces/ISISReflectometry/test/Batch/GroupProcessingAlgorithmTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Batch/RowPreprocessingAlgorithmTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Batch/RowProcessingAlgorithmTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Batch/SumBanksAlgorithmTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/PreviewJobManagerTest.h
  qt/scientific_interfaces/ISISReflectometry/test/ReflMockObjects.h
  qt/scientific_interfaces/ISISReflectometry/test/Runs/RunsPresenterTest.h
  qt/scientific_interfaces/Indirect/ApplyAbsorptionCorrections.cpp
  qt/scientific_interfaces/Indirect/CalculatePaalmanPings.cpp
  qt/scientific_interfaces/Indirect/ISISCalibration.cpp
  qt/scientific_interfaces/Indirect/ISISEnergyTransfer.cpp
  qt/scientific_interfaces/Indirect/IndirectDiffractionReduction.cpp
  qt/scientific_interfaces/Indirect/IndirectTab.cpp
  qt/scientific_interfaces/Indirect/InelasticDataManipulationElwinTab.cpp
  qt/scientific_interfaces/Indirect/InelasticDataManipulationElwinTabModel.cpp
  qt/scientific_interfaces/Indirect/InelasticDataManipulationElwinTabView.cpp
  qt/scientific_interfaces/Indirect/InelasticDataManipulationIqtTabModel.cpp
  qt/scientific_interfaces/Indirect/InelasticDataManipulationIqtTabView.cpp
  qt/scientific_interfaces/Indirect/InelasticDataManipulationSqwTab.cpp
  qt/scientific_interfaces/Indirect/InelasticDataManipulationSqwTabModel.cpp
  qt/scientific_interfaces/Indirect/InelasticDataManipulationSymmetriseTabModel.cpp
  qt/widgets/common/CMakeLists.txt
  qt/widgets/common/inc/MantidQtWidgets/Common/BatchAlgorithmRunner.h
  qt/widgets/common/inc/MantidQtWidgets/Common/ConfiguredAlgorithm.h
  qt/widgets/common/inc/MantidQtWidgets/Common/IConfiguredAlgorithm.h
  qt/widgets/common/inc/MantidQtWidgets/Common/ParseKeyValueString.h
  qt/widgets/common/src/BatchAlgorithmRunner.cpp
  qt/widgets/common/src/ConfiguredAlgorithm.cpp
  qt/widgets/common/src/ParseKeyValueString.cpp
  qt/widgets/common/test/BatchAlgorithmRunnerTest.h
  qt/widgets/common/test/MockConfiguredAlgorithm.h
  qt/widgets/common/test/ParseKeyValueStringTest.h
Labels: Reflectometry, Direct Inelastic, Maintenance, ISIS Team: Excitations/Vesuvio

#35316 Fix for ALFView when Maintain Aspect Ratio is on
  qt/scientific_interfaces/Direct/ALFInstrumentView.cpp
  qt/widgets/instrumentview/src/UnwrappedSurface.cpp
Labels: Bug, Direct Inelastic, ISIS Team: Excitations/Vesuvio

#35221 Add a developer page describing the packaging strategy for mantid
  dev-docs/source/Packaging.rst
  dev-docs/source/conf.py
  dev-docs/source/index.rst
Labels: Documentation

#34905 Update muon manual testing docs
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon Analysis Unscripted Testing Guide.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_ALC.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_Analysis_MUSR.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_Analysis_PSI.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_EMU.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_FDA.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_HIFI.rst
Labels: Documentation, Maintenance, ISIS Team: Spectroscopy

#35324 Use JobRunners for loading data in ALFView
  Framework/API/inc/MantidAPI/AlgorithmProperties.h
  Framework/API/inc/MantidAPI/AlgorithmRuntimeProps.h
  Framework/API/inc/MantidAPI/IAlgorithmRuntimeProps.h
  Framework/API/src/AlgorithmProperties.cpp
  Framework/API/src/AlgorithmRuntimeProps.cpp
  Framework/Kernel/src/PropertyManager.cpp
  qt/scientific_interfaces/Direct/ALFAlgorithmManager.cpp
  qt/scientific_interfaces/Direct/ALFAlgorithmManager.h
  qt/scientific_interfaces/Direct/ALFData.h
  qt/scientific_interfaces/Direct/ALFInstrumentModel.cpp
  qt/scientific_interfaces/Direct/ALFInstrumentModel.h
  qt/scientific_interfaces/Direct/ALFInstrumentPresenter.cpp
  qt/scientific_interfaces/Direct/ALFInstrumentPresenter.h
  qt/scientific_interfaces/Direct/ALFView.cpp
  qt/scientific_interfaces/Direct/CMakeLists.txt
  qt/scientific_interfaces/Direct/IALFAlgorithmManagerSubscriber.h
  qt/scientific_interfaces/Direct/test/ALFAlgorithmManagerTest.h
  qt/scientific_interfaces/Direct/test/ALFInstrumentMocks.h
  qt/scientific_interfaces/Direct/test/ALFInstrumentModelTest.h
  qt/scientific_interfaces/Direct/test/ALFInstrumentPresenterTest.h
  qt/scientific_interfaces/Direct/test/CMakeLists.txt
  qt/scientific_interfaces/Direct/test/MockALFAlgorithmManager.h
  qt/scientific_interfaces/Direct/test/MockALFAlgorithmManagerSubscriber.h
  qt/widgets/common/inc/MantidQtWidgets/Common/BatchAlgorithmRunner.h
  qt/widgets/common/inc/MantidQtWidgets/Common/IJobRunner.h
  qt/widgets/common/inc/MantidQtWidgets/Common/MockJobRunner.h
  qt/widgets/common/inc/MantidQtWidgets/Common/QtJobRunner.h
  qt/widgets/common/src/BatchAlgorithmRunner.cpp
  qt/widgets/common/src/QtJobRunner.cpp
Labels: Direct Inelastic, ISIS Team: Excitations/Vesuvio

#35331 Refactoring assert raises in python algorithm tests part 2
  Framework/PythonInterface/test/python/plugins/algorithms/EnggEstimateFocussedBackgroundTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/EnggFocusTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/ExtractMonitorsTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/FindGlobalBMatrixTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/FindGoniometerFromUBTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/FitGaussianTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/GenerateLogbookTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/HB3AAdjustSampleNormTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/IndirectTransmissionTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/LoadCIFTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/LoadDNSLegacyTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/LoadGudrunOutputTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/LoadLampTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/LoadNMoldyn3AsciiTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/LoadNMoldyn4Ascii1DTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/LoadNMoldyn4AsciiTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/MatchPeaksTest.py
Labels: Maintenance, ISIS Team: Core

#35336 Remove sourceforge text from release notes
  docs/source/release/v6.7.0/index.rst
  docs/source/workbench/scriptrepository.rst
  tools/release_generator/release.py
Labels: ISIS Team: Core, Added during Sprint

#35339 Added option to specify x range for getSpectrum in CEF Python interface
  docs/source/interfaces/direct/Crystal Field Python Interface.rst
  docs/source/release/v6.7.0/Direct_Geometry/CrystalField/New_features/35339.rst
  scripts/Inelastic/CrystalField/CrystalFieldMultiSite.py
  scripts/Inelastic/CrystalField/fitting.py
  scripts/test/CrystalFieldMultiSiteTest.py
  scripts/test/CrystalFieldTest.py
Labels: Direct Inelastic, ISIS Team: Excitations/Vesuvio

#35340 Refactoring assert raises in python algorithm tests part 3
  Framework/PythonInterface/plugins/algorithms/NormaliseSpectra.py
  Framework/PythonInterface/plugins/algorithms/TOFTOFCropWorkspace.py
  Framework/PythonInterface/plugins/algorithms/VesuvioThickness.py
  Framework/PythonInterface/test/python/plugins/algorithms/MatchSpectraTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/MeanTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/MedianBinWidthTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/NMoldyn4InterpolationTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/NormaliseSpectraTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/PoldiMergeTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/ReflectometryReductionOneLiveDataTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/RetrieveRunInfoTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/SANSWideAngleCorrectionTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/SaveReflectionsTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/SaveYDATest.py
  Framework/PythonInterface/test/python/plugins/algorithms/SelectNexusFilesByMetadataTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/SetSampleFromLogsTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/SymmetriseTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/TOFTOFCropWorkspaceTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/TOFTOFMergeRunsTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/VesuvioPeakPredictionTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/VesuvioPreFitTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/VesuvioResolutionTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/VesuvioTOFFitTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/VesuvioThicknessTest.py
Labels: Bug, Maintenance, ISIS Team: Core

#35343 New function to pretty print eigenvectors for a CrystalField object
  docs/source/interfaces/direct/Crystal Field Python Interface.rst
  docs/source/release/v6.7.0/Direct_Geometry/CrystalField/New_features/35343.rst
  scripts/Inelastic/CrystalField/fitting.py
Labels: Direct Inelastic, ISIS Team: Excitations/Vesuvio

#35232 Unpin Numpy
  Framework/PythonInterface/plugins/algorithms/MuonMaxent.py
  Framework/PythonInterface/plugins/algorithms/PEARLTransfit.py
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid/meta.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
  scripts/test/Abins/AbinsAtomsDataTest.py
  scripts/test/Abins/AbinsKpointsDataTest.py
Labels: ISIS Team: Core

#35338 Clean before checkout and increase timeout
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
Labels: DevOps

#35195 Make plots resize with windows better
  Framework/PythonInterface/mantid/plots/plotfunctions.py
  Framework/PythonInterface/test/python/mantid/plots/plotfunctionsTest.py
  docs/source/release/v6.7.0/Workbench/Bugfixes/35014.rst
  qt/applications/workbench/workbench/plotting/toolbar.py
  qt/python/mantidqt/mantidqt/plotting/functions.py
  qt/python/mantidqt/mantidqt/plotting/test/test_functions.py
  qt/python/mantidqt/mantidqt/project/plotsloader.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer/view.py
Labels: GUI, ISIS Team: Core

#35320 Allow Selection of Flood and Polarization Efficiencies Workspace by File Path
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISLoadAndProcess.py
  Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp
  Testing/Data/UnitTest/ISISReflectometry/batch_with_save_rows_box_POLREF.json.md5
  dev-docs/source/Testing/ReflectometryGUI/ReflectometryGUITests.rst
  docs/source/release/v6.7.0/Reflectometry/New_features/34720_pol_by_file.rst
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/RowProcessingAlgorithm.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Common/Decoder.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Common/Decoder.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Common/Encoder.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Common/IFileHandler.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/ExperimentPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/ExperimentPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/ExperimentPresenterFactory.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/ExperimentWidget.ui
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/IExperimentView.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/QtExperimentView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/QtExperimentView.h
  qt/scientific_interfaces/ISISReflectometry/GUI/MainWindow/QtMainWindowView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/MainWindow/QtMainWindowView.h
  qt/scientific_interfaces/ISISReflectometry/Reduction/FloodCorrections.h
  qt/scientific_interfaces/ISISReflectometry/Reduction/PolarizationCorrections.h
  qt/scientific_interfaces/ISISReflectometry/test/Common/CoderCommonTester.h
  qt/scientific_interfaces/ISISReflectometry/test/Common/DecoderTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Common/EncoderTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Experiment/ExperimentPresenterTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Experiment/MockExperimentView.h
  qt/scientific_interfaces/ISISReflectometry/test/ReflMockObjects.h
Labels: Reflectometry, ISIS Team: LSS

#35326 Refactoring assert raises in python algorithm tests part 4
  .gitignore
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/FlatPlatePaalmanPingsCorrection.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/AddSampleLogMultipleTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ApplyPaalmanPingsCorrectionTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/BayesStretchTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/D7YIGPositionCalibrationTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/DetectorFloodWeightingTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/DirectILLReductionTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/FindPeakAutomaticTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/FitGaussianPeaksTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/FlatPlatePaalmanPingsCorrectionTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ISISIndirectDiffractionReductionTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransferTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransferWrapperTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/IndirectReplaceFitResultTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/IndirectSampleChangerTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/IqtFitMultipleTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/IqtFitSequentialTest.py
Labels: Bug, Maintenance, ISIS Team: Core

#35365 Add new interface menu for Shiver
  Framework/Properties/Mantid.properties.template
  docs/source/release/v6.7.0/Direct_Geometry/General/New_features/35365.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Shiver.py
Labels: GUI

#35234 Output sample logs to workspace group in GSAS tab
  docs/source/release/v6.6.0/Diffraction/Engineering/New_features/34709_SampleLogs.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/settings/settings_widget.ui
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/output_sample_logs.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/workspace_record.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/data_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/data_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/test/test_data_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/data_handling/test/test_data_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/test/test_gsas2_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/test/engineering_diffraction_io_test.py
Labels: Diffraction, ISIS Team: Diffraction

#35356 Update QA role with smoke testing facilitating role
  dev-docs/source/ReleaseChecklist.rst
Labels: Documentation

#35166 Abins: Bose factors for improved simulation of temperature effects
  Framework/PythonInterface/mantid/kernel/environment.py
  Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py
  Testing/Data/SystemTest/AbinsCRYSTAL2D.nxs.md5
  Testing/Data/SystemTest/Mapi.nxs.md5
  Testing/Data/UnitTest/Si2-sc_CalculatePowder_powder.txt.md5
  Testing/Data/UnitTest/Si2-sc_CalculateSPowder_1d_o10_S.txt.md5
  Testing/Data/UnitTest/Si2-sc_CalculateSPowder_1d_o2_S.txt.md5
  Testing/Data/UnitTest/Si2-sc_CalculateSPowder_2d_o1_mari_S.txt.md5
  Testing/Data/UnitTest/Si2-sc_CalculateSPowder_2d_o2_panther_S.txt.md5
  Testing/Data/UnitTest/Si2-sc_CalculateSPowder_S.txt.md5
  Testing/Data/UnitTest/benzene_CalculatePowder_powder.txt.md5
  docs/source/concepts/DynamicalStructureFactorFromAbInitio.rst
  docs/source/release/v6.7.0/Indirect/Algorithms/35166.rst
  scripts/abins/constants.py
  scripts/abins/input/tester.py
  scripts/abins/instruments/broadening.py
  scripts/abins/io.py
  scripts/abins/parameters.py
  scripts/abins/powdercalculator.py
  scripts/abins/powderdata.py
  scripts/abins/spowdersemiempiricalcalculator.py
  scripts/abins/test_helpers.py
  scripts/test/Abins/AbinsCalculateSPowderTest.py
  scripts/test/Abins/AbinsPowderCalculatorTest.py
  scripts/test/Abins/AbinsPowderDataTest.py
Labels: ISIS Team: Spectroscopy

#35229 Match Osiris script with the indirect diffraction UI
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/OSIRISDiffractionReduction.py
  Testing/Data/SystemTest/ISIS_Powder/input/OSI82717.nxs.md5
  Testing/Data/SystemTest/ISIS_Powder/input/OSI82718.nxs.md5
  Testing/Data/SystemTest/ISIS_Powder/input/calibration/osiris/1_1/OSI119977-119978_d_spacing.nxs.md5
  Testing/Data/SystemTest/ISIS_Powder/input/calibration/osiris/1_1/OSI119977-119988.nxs.md5
  Testing/Data/SystemTest/ISIS_Powder/input/calibration/osiris/osiris_grouping.cal
  Testing/Data/SystemTest/ISIS_Powder/input/calibration/osiris/osiris_grouping.cal.md5
  Testing/SystemTests/tests/framework/ISIS_PowderOsirisTest.py
  Testing/SystemTests/tests/framework/reference/OSI119977-119978_d_spacing.nxs.md5
  Testing/SystemTests/tests/framework/reference/OSI119977_d_spacing.nxs.md5
  Testing/SystemTests/tests/framework/reference/OsirisDiffractionTest.nxs.md5
  docs/source/release/v6.7.0/Diffraction/Powder/Bugfixes/35229.rst
  scripts/Diffraction/isis_powder/osiris.py
  scripts/Diffraction/isis_powder/osiris_routines/osiris_algs.py
Labels: Indirect Inelastic, ISIS Team: Spectroscopy

#35364 Updated Polarization Efficiencies error for PolRef
  Framework/DataHandling/src/ExtractPolarizationEfficiencies.cpp
  docs/source/release/v6.7.0/Reflectometry/Bugfixes/34812.rst
Labels: Reflectometry, GUI

#35280 Per detector placzek and vanadium
  Framework/CurveFitting/inc/MantidCurveFitting/Algorithms/SplineBackground.h
  Framework/CurveFitting/src/Algorithms/SplineBackground.cpp
  Framework/CurveFitting/test/Algorithms/SplineBackgroundTest.h
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/TotScatCalculateSelfScattering.py
  Testing/Data/SystemTest/ISIS_Powder/input/ISIS_Powder-POLARIS98533_TotalScatteringInputPerDetector.nxs.md5
  Testing/Data/SystemTest/ISIS_Powder/input/POLARIS00098532_splined_per_det.nxs.md5
  Testing/SystemTests/tests/framework/ISIS_PowderPolarisTest.py
  Testing/SystemTests/tests/framework/reference/ISIS_Powder-POLARIS00098532_splined_per_det.nxs.md5
  Testing/SystemTests/tests/framework/reference/ISIS_Powder-POLARIS00098532_unsplined_per_det.nxs.md5
  Testing/SystemTests/tests/framework/reference/ISIS_Powder-POLARIS98533_FocusPerDet.nxs.md5
  docs/source/release/v6.7.0/Diffraction/Powder/New_features/35280_PerDetectorVNormalisation.rst
  docs/source/release/v6.7.0/Framework/Algorithms/New_features/35280_FitMultipleSpectraInSplineBackground.rst
  docs/source/techniques/ISISPowder-Polaris-v1.rst
  scripts/Diffraction/isis_powder/abstract_inst.py
  scripts/Diffraction/isis_powder/gem_routines/gem_param_mapping.py
  scripts/Diffraction/isis_powder/hrpd_routines/hrpd_param_mapping.py
  scripts/Diffraction/isis_powder/pearl_routines/pearl_param_mapping.py
  scripts/Diffraction/isis_powder/polaris.py
  scripts/Diffraction/isis_powder/polaris_routines/Examples/polaris_config_example.yaml
  scripts/Diffraction/isis_powder/polaris_routines/polaris_advanced_config.py
  scripts/Diffraction/isis_powder/polaris_routines/polaris_algs.py
  scripts/Diffraction/isis_powder/polaris_routines/polaris_param_mapping.py
  scripts/Diffraction/isis_powder/routines/calibrate.py
  scripts/Diffraction/isis_powder/routines/common.py
  scripts/Diffraction/isis_powder/routines/focus.py
Labels: ISIS Team: Diffraction

#35357 Support more PEP440 version numbers
  Framework/DataHandling/inc/MantidDataHandling/CheckMantidVersion.h
  Framework/DataHandling/src/CheckMantidVersion.cpp
  Framework/DataHandling/test/CheckMantidVersionTest.h
  Framework/Kernel/inc/MantidKernel/MantidVersion.h
  Framework/Kernel/src/MantidVersion.cpp.in
  Framework/Kernel/test/MantidVersionTest.h.in
  Framework/PythonInterface/mantid/kernel/src/Exports/MantidVersion.cpp
  Framework/PythonInterface/test/python/mantid/kernel/MantidVersionTest.py
  buildconfig/CMake/VersionNumber.cmake
Labels: Extra Attention, ISIS Team: Core, Added during Sprint

#35383 Revert "Clean before checkout and increase timeout"
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
Labels: High Priority, ISIS Team: Core, Added during Sprint, DevOps

#35359 Add `--debug` flag for package-conda script
  buildconfig/Jenkins/Conda/package-conda
Labels: DevOps

#35335 Use job runner for ALFView Analysis
  Framework/API/inc/MantidAPI/AlgorithmProperties.h
  Framework/API/src/AlgorithmProperties.cpp
  qt/scientific_interfaces/Direct/ALFAlgorithmManager.cpp
  qt/scientific_interfaces/Direct/ALFAlgorithmManager.h
  qt/scientific_interfaces/Direct/ALFAnalysisModel.cpp
  qt/scientific_interfaces/Direct/ALFAnalysisModel.h
  qt/scientific_interfaces/Direct/ALFAnalysisPresenter.cpp
  qt/scientific_interfaces/Direct/ALFAnalysisPresenter.h
  qt/scientific_interfaces/Direct/ALFInstrumentPresenter.cpp
  qt/scientific_interfaces/Direct/ALFInstrumentView.cpp
  qt/scientific_interfaces/Direct/ALFInstrumentView.h
  qt/scientific_interfaces/Direct/ALFView.cpp
  qt/scientific_interfaces/Direct/IALFAlgorithmManagerSubscriber.h
  qt/scientific_interfaces/Direct/test/ALFAlgorithmManagerTest.h
  qt/scientific_interfaces/Direct/test/ALFAnalysisMocks.h
  qt/scientific_interfaces/Direct/test/ALFAnalysisModelTest.h
  qt/scientific_interfaces/Direct/test/ALFAnalysisPresenterTest.h
  qt/scientific_interfaces/Direct/test/ALFInstrumentMocks.h
  qt/scientific_interfaces/Direct/test/ALFInstrumentPresenterTest.h
  qt/scientific_interfaces/Direct/test/MockALFAlgorithmManager.h
  qt/scientific_interfaces/Direct/test/MockALFAlgorithmManagerSubscriber.h
Labels: Direct Inelastic, ISIS Team: Excitations/Vesuvio

#35390 Fail Jenkins pipeline early if publishing parameters aren't specified
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
Labels: ISIS Team: Core, DevOps

#35386 Update MSlice SHA for latest bug fixes
  docs/source/release/v6.7.0/Direct_Geometry/MSlice/Bugfixes/35386.rst
  scripts/ExternalInterfaces/CMakeLists.txt
Labels: Bug, Reported By User, ISIS Team: Excitations/Vesuvio

#35409 Pin filelock to <3.10.2 to fix doc segmentation fault
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid/meta.yaml
  mantid-developer-linux.yml
Labels: DevOps

#35393 Update OSIRIS docs
  docs/source/release/v6.7.0/Diffraction/Powder/New_features/35362.rst
  docs/source/techniques/ISISPowder-Index-v1.rst
  docs/source/techniques/ISISPowder-OSIRIS-v1.rst
  scripts/Diffraction/isis_powder/osiris_routines/Examples/Calibrations/1_1/osiris_grouping.cal
  scripts/Diffraction/isis_powder/osiris_routines/Examples/Calibrations/osiris_grouping.cal
  scripts/Diffraction/isis_powder/osiris_routines/Examples/osiris_config_example.yaml
  scripts/Diffraction/isis_powder/osiris_routines/Examples/osiris_run_mapping.yaml
  scripts/Diffraction/isis_powder/routines/common.py
Labels: ISIS Team: Spectroscopy

#35189 Remove unused Sample Transmission c++ interface
  qt/scientific_interfaces/General/CMakeLists.txt
  qt/scientific_interfaces/General/LatticePresenter.cpp
  qt/scientific_interfaces/General/LatticePresenter.h
  qt/scientific_interfaces/General/LatticeView.h
  qt/scientific_interfaces/General/MantidEV.cpp
  qt/scientific_interfaces/General/MantidEV.h
  qt/scientific_interfaces/General/MantidEV.ui
  qt/scientific_interfaces/General/MantidEVWorker.cpp
  qt/scientific_interfaces/General/MantidEVWorker.h
  qt/scientific_interfaces/General/ProjectSave.ui
  qt/scientific_interfaces/General/ReflOptionsDialog.ui
  qt/scientific_interfaces/General/ReflWindow.ui
  qt/scientific_interfaces/General/SampleTransmission.cpp
  qt/scientific_interfaces/General/SampleTransmission.h
  qt/scientific_interfaces/General/SampleTransmission.ui
  qt/scientific_interfaces/General/Updateable.h
Labels: Maintenance, ISIS Team: Core
