Repository mantidproject/mantid, pull requests merged in 2023-07, with the labels that each got.

#35781 ReplaceSpecialValues after division by solid angle correction in powder script
  scripts/Diffraction/isis_powder/routines/calibrate.py
Labels: High Priority, Diffraction, Powder, ISIS Team: Diffraction

#35655 Add IgnoreInvalidData to the indirect data analysis interface
  Framework/CurveFitting/src/MultiDomainCreator.cpp
  Testing/SystemTests/tests/framework/D7YIGPositionCalibrationTest.py
  docs/source/algorithms/Fit-v1.rst
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisConvFitTab.cpp
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisFqFitTab.cpp
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisIqtFitTab.cpp
  qt/scientific_interfaces/Indirect/IndirectDataAnalysisMSDFitTab.cpp
  qt/scientific_interfaces/Indirect/IndirectFitPropertyBrowser.cpp
  qt/widgets/common/src/FitOptionsBrowser.cpp
Labels: ISIS Team: Spectroscopy

#35774 Make Windows system test failures fail the build
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
Labels: ISIS Team: Core

#35764 Improve validation for algorithms being excluded from system tests
  Framework/PythonInterface/plugins/algorithms/DNSFlippingRatioCorr.py
  Framework/PythonInterface/plugins/algorithms/DNSMergeRuns.py
  Framework/PythonInterface/plugins/algorithms/HB3AIntegratePeaks.py
  Framework/PythonInterface/plugins/algorithms/MatchPeaks.py
  Framework/PythonInterface/plugins/algorithms/Mean.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesStretch.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/CalculateMonteCarloAbsorption.py
  Testing/SystemTests/tests/framework/AlgorithmMDWorkspaceValidateInputsTest.py
  Testing/SystemTests/tests/framework/AlgorithmMatrixWorkspaceValidateInputsTest.py
  Testing/SystemTests/tests/framework/AlgorithmTableWorkspaceValidateInputsTest.py
  Testing/SystemTests/tests/framework/AlgorithmValidateInputsTestBase.py
  Testing/SystemTests/tests/framework/AlgorithmWorkspaceGroupValidateInputsTest.py
Labels: Bug, ISIS Team: Core

#35647 Remove `CONDA_ENV` variable from CMake
  CMakeLists.txt
  CMakePresets.json
  Framework/API/CMakeLists.txt
  Framework/Algorithms/CMakeLists.txt
  Framework/Beamline/CMakeLists.txt
  Framework/CMakeLists.txt
  Framework/Catalog/CMakeLists.txt
  Framework/Crystal/CMakeLists.txt
  Framework/CurveFitting/CMakeLists.txt
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/test/CMakeLists.txt
  Framework/DataObjects/CMakeLists.txt
  Framework/Geometry/CMakeLists.txt
  Framework/HistogramData/CMakeLists.txt
  Framework/ICat/CMakeLists.txt
  Framework/Indexing/CMakeLists.txt
  Framework/Json/CMakeLists.txt
  Framework/Kernel/CMakeLists.txt
  Framework/LiveData/CMakeLists.txt
  Framework/MDAlgorithms/CMakeLists.txt
  Framework/Muon/CMakeLists.txt
  Framework/Nexus/CMakeLists.txt
  Framework/NexusGeometry/CMakeLists.txt
  Framework/Parallel/CMakeLists.txt
  Framework/PythonInterface/core/CMakeLists.txt
  Framework/PythonInterface/mantid/BundlePython.cmake
  Framework/PythonInterface/mantid/CMakeLists.txt
  Framework/Reflectometry/CMakeLists.txt
  Framework/SINQ/CMakeLists.txt
  Framework/ScriptRepository/CMakeLists.txt
  Framework/Types/CMakeLists.txt
  Framework/WorkflowAlgorithms/CMakeLists.txt
  buildconfig/CMake/Bootstrap.cmake
  buildconfig/CMake/FindNexus.cmake
  buildconfig/CMake/FindPoco.cmake
  buildconfig/CMake/GNUSetup.cmake
  buildconfig/CMake/LinuxPackageScripts.cmake
  buildconfig/CMake/WindowsSetup.cmake
  conda/recipes/mantid/bld.bat
  conda/recipes/mantid/build.sh
  conda/recipes/mantiddocs/build.sh
  conda/recipes/mantidqt/bld.bat
  conda/recipes/mantidqt/build.sh
  conda/recipes/mantidworkbench/bld.bat
  conda/recipes/mantidworkbench/build.sh
  dev-docs/source/GettingStarted/GettingStartedCondaLinux.rst
  dev-docs/source/GettingStarted/GettingStartedCondaOSX.rst
  dev-docs/source/GettingStarted/GettingStartedCondaWindows.rst
  qt/applications/workbench/CMakeLists.txt
  qt/applications/workbench/mantidworkbench.cpp
Labels: Maintenance

#35532 JSON read/write for some Abins data structures
  Testing/Data/UnitTest/Si2-sc_CalculatePowder.json.md5
  Testing/Data/UnitTest/Si2-sc_CalculatePowder.phonon.md5
  Testing/Data/UnitTest/Si2-sc_CalculateSPowder.json.md5
  Testing/Data/UnitTest/Si2-sc_CalculateSPowder.phonon.md5
  Testing/Data/UnitTest/benzene_CalculatePowder.json.md5
  Testing/Data/UnitTest/benzene_CalculatePowder.phonon.md5
  Testing/Data/UnitTest/mgo-abinsdata-dump.json.md5
  scripts/abins/abinsdata.py
  scripts/abins/atomsdata.py
  scripts/abins/kpointsdata.py
  scripts/abins/test_helpers.py
  scripts/test/Abins/AbinsAtomsDataTest.py
  scripts/test/Abins/AbinsCalculateSPowderTest.py
  scripts/test/Abins/AbinsDataTest.py
  scripts/test/Abins/AbinsKpointsDataTest.py
  scripts/test/Abins/AbinsPowderCalculatorTest.py
Labels: ISIS Team: Spectroscopy

#35656 Consolidate ALFView tests
  Testing/Data/UnitTest/ALF82301_preprocessed.nxs.md5
  qt/scientific_interfaces/Direct/ALFInstrumentModel.cpp
  qt/scientific_interfaces/Direct/ALFInstrumentModel.h
  qt/scientific_interfaces/Direct/test/ALFAnalysisPresenterTest.h
  qt/scientific_interfaces/Direct/test/ALFInstrumentModelTest.h
Labels: Direct Inelastic, Maintenance, ISIS Team: Excitations/Vesuvio

#35789 update number of banks for BIOSANS in MaskBTP
  Framework/PythonInterface/plugins/algorithms/MaskBTP.py
  Framework/PythonInterface/test/python/plugins/algorithms/MaskBTPTest.py
  docs/source/release/v6.8.0/Framework/Algorithms/Bugfixes/35789.rst
Labels: Framework, ORNL Team

#35788 Add threshold I/sigma parameter in SaveReflections
  Framework/Crystal/src/FilterPeaks.cpp
  Framework/Crystal/test/FilterPeaksTest.h
  Framework/PythonInterface/plugins/algorithms/SaveReflections.py
  Framework/PythonInterface/test/python/plugins/algorithms/SaveReflectionsTest.py
  Testing/Data/UnitTest/lean_peak_GSAS.hkl.md5
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/Bugfixes/35706.rst
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/New_features/35706.rst
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction

#35797 Pin importlib_resources to fix failing euphonic test
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantidworkbench/meta.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: High Priority

#35782 Update documentation on how to write algorithms
  dev-docs/source/PythonVSCppAlgorithms.rst
  dev-docs/source/ToolsOverview.rst
  dev-docs/source/WritingAnAlgorithm.rst
  dev-docs/source/class_maker.txt
  dev-docs/source/cppalgexample/MyAlg.cpp
  dev-docs/source/cppalgexample/MyAlg.h
  dev-docs/source/cppalgexample/MyAlg_initial.cpp
  dev-docs/source/cppalgexample/MyAlg_initial.h
  docs/source/api/python/mantid/api/IPeaksWorkspaceProperty.rst
  docs/source/tutorials/extending_mantid_with_python/python_algorithms/01_basic_algorithm_structure.rst
  docs/source/tutorials/extending_mantid_with_python/python_algorithms/02_basic_properties.rst
  docs/source/tutorials/extending_mantid_with_python/python_algorithms/03_validating_input.rst
  docs/source/tutorials/extending_mantid_with_python/python_algorithms/04_main_algorithm_body.rst
  docs/source/tutorials/extending_mantid_with_python/python_algorithms/05_logging.rst
  docs/source/tutorials/extending_mantid_with_python/python_algorithms_and_workspaces/01_algorithms_and_workspaces.rst
  docs/source/tutorials/extending_mantid_with_python/python_algorithms_and_workspaces/02_workspace_validators.rst
  docs/source/tutorials/extending_mantid_with_python/python_algorithms_and_workspaces/03_combining_validators.rst
  docs/source/tutorials/extending_mantid_with_python/python_algorithms_and_workspaces/04_file_properties.rst
Labels: Documentation

#35805 Fail the pipeline if a system test fails on Windows
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
Labels: High Priority, Bug, Extra Attention, ISIS Team: Core, Windows Only, Added during Sprint, DevOps

#35809 Update black to 23.7.0
  .pre-commit-config.yaml
Labels: DevOps

#35511 Enable cross compilation on M1 Macs
  Framework/API/test/IFunction1DTest.h
  Framework/Algorithms/test/ExportTimeSeriesLogTest.h
  Framework/CurveFitting/src/Algorithms/FitPowderDiffPeaks.cpp
  Framework/DataHandling/src/FindDetectorsPar.cpp
  Framework/DataObjects/inc/MantidDataObjects/MDGridBox.tcc
  Framework/DataObjects/test/MDBoxSaveableTest.h
  Framework/Geometry/src/Math/Acomp.cpp
  Framework/Kernel/src/Matrix.cpp
  Framework/PythonInterface/CMakeLists.txt
  Framework/PythonInterface/mantid/_plugins/CMakeLists.txt
  Framework/PythonInterface/mantid/api/CMakeLists.txt
  Framework/PythonInterface/mantid/dataobjects/CMakeLists.txt
  Framework/PythonInterface/mantid/geometry/CMakeLists.txt
  Framework/PythonInterface/mantid/kernel/CMakeLists.txt
  buildconfig/CMake/Bootstrap.cmake
  buildconfig/CMake/CommonSetup.cmake
  buildconfig/CMake/PythonPackageTargetFunctions.cmake
  buildconfig/CMake/QtTargetFunctions.cmake
  buildconfig/CMake/TargetFunctions.cmake
  buildconfig/Jenkins/Conda/conda-buildscript
  buildconfig/Jenkins/Conda/download-and-install-mambaforge
  buildconfig/Jenkins/Conda/package-conda
  conda/recipes/archive_env_logs.sh
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid/build.sh
  conda/recipes/mantid/meta.yaml
  conda/recipes/mantiddocs/build.sh
  conda/recipes/mantiddocs/meta.yaml
  conda/recipes/mantidqt/build.sh
  conda/recipes/mantidqt/meta.yaml
  conda/recipes/mantidworkbench/build.sh
  conda/recipes/mantidworkbench/meta.yaml
  conda/recipes/osx_64.yaml
  mantid-developer-osx.yml
  qt/applications/workbench/CMakeLists.txt
  qt/python/mantidqt/CMakeLists.txt
  qt/python/mantidqt/mantidqt/CMakeLists.txt
  qt/python/mantidqt/mantidqt/icons/CMakeLists.txt
  qt/python/mantidqt/mantidqt/widgets/instrumentview/CMakeLists.txt
Labels: DevOps

#35765 Fix bug in powder absolute unit normalisation
  Testing/SystemTests/tests/framework/ISIS_PowderPolarisTest.py
  Testing/SystemTests/tests/framework/reference/ISIS_Powder-POLARIS00098532_splined.nxs.md5
  Testing/SystemTests/tests/framework/reference/ISIS_Powder-POLARIS00098532_splined_per_det.nxs.md5
  Testing/SystemTests/tests/framework/reference/ISIS_Powder-POLARIS00098532_unsplined.nxs.md5
  Testing/SystemTests/tests/framework/reference/ISIS_Powder-POLARIS00098532_unsplined_per_det.nxs.md5
  docs/source/release/v6.8.0/Diffraction/Powder/Bugfixes/35765.rst
  scripts/Diffraction/isis_powder/gem.py
  scripts/Diffraction/isis_powder/gem_routines/gem_algs.py
  scripts/Diffraction/isis_powder/gem_routines/gem_param_mapping.py
  scripts/Diffraction/isis_powder/hrpd.py
  scripts/Diffraction/isis_powder/hrpd_routines/hrpd_algs.py
  scripts/Diffraction/isis_powder/hrpd_routines/hrpd_param_mapping.py
  scripts/Diffraction/isis_powder/osiris_routines/osiris_param_mapping.py
  scripts/Diffraction/isis_powder/pearl_routines/pearl_param_mapping.py
  scripts/Diffraction/isis_powder/polaris.py
  scripts/Diffraction/isis_powder/polaris_routines/polaris_algs.py
  scripts/Diffraction/isis_powder/polaris_routines/polaris_param_mapping.py
  scripts/Diffraction/isis_powder/routines/absorb_corrections.py
  scripts/Diffraction/isis_powder/routines/focus.py
Labels: Diffraction, Powder, ISIS Team: Diffraction

#35812 Fixing sliceviewer projection matrix calculation for workspaces with basis vectors
  Testing/SystemTests/tests/qt/SliceViewerIntegrationTest.py
  docs/source/release/v6.8.0/Workbench/SliceViewer/Bugfixes/35812.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py
Labels: Bug, Single Crystal, GUI

#35800 CombineDiffCal with partial GroupedCalibration workspace
  Framework/API/src/MatrixWorkspace.cpp
  Framework/API/src/SpectrumInfo.cpp
  Framework/Algorithms/src/CombineDiffCal.cpp
  Framework/Algorithms/test/CombineDiffCalTest.h
  docs/source/algorithms/CombineDiffCal-v1.rst
  docs/source/release/v6.8.0/Diffraction/Powder/New_features/35800.rst
Labels: Diffraction, Powder

#35810 update cppcheck to 2.10.3
  Framework/DataHandling/src/SaveFullprofResolution.cpp
  buildconfig/CMake/CppCheckSetup.cmake
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  buildconfig/CMake/FindCxxTest.cmake
  buildconfig/CMake/cppcheck-clean-compile-commands.py
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
  tools/Cppcheck/generate_cppcheck_suppressions_list.py
Labels: ISIS Team: Core

#35818 Powder diffraction gui DataOffset parameter
  Framework/PythonInterface/plugins/algorithms/SNSPowderReduction.py
  Framework/PythonInterface/test/python/plugins/algorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/SNSPowderReductionTest.py
  docs/source/release/v6.8.0/Diffraction/Powder/New_features/35818.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/reduction_gui/widgets/diffraction/diffraction_adv_setup.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/ui/diffraction/diffraction_adv_setup.ui
  scripts/reduction_gui/reduction/diffraction/diffraction_adv_setup_script.py
Labels: Diffraction, Powder

#35823 Fix variable name that only is compiled in debug builds
  Framework/API/src/MatrixWorkspace.cpp
Labels: Bug

#35799 Add algorithm to load gauss cube files
  Framework/MDAlgorithms/CMakeLists.txt
  Framework/MDAlgorithms/inc/MantidMDAlgorithms/LoadGaussCube.h
  Framework/MDAlgorithms/src/LoadGaussCube.cpp
  Framework/MDAlgorithms/test/LoadGaussCubeTest.h
  Testing/Data/UnitTest/gauss_cube_example.cube.md5
  docs/source/algorithms/LoadGaussCube-v1.rst
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/New_features/35799.rst
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction

#35824 Update scipy version specification to avoid security vulnerability
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid/meta.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: ISIS Team: Core, Vulnerability

#35778 Adding Silicon analyser to OSIRIS
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransfer.py
  instrument/OSIRIS_Definition.xml
  instrument/OSIRIS_Parameters.xml
  instrument/OSIRIS_silicon_111_Parameters.xml
  instrument/OSIRIS_silicon_333_Parameters.xml
Labels: ISIS Team: Spectroscopy

#35462 Add prompt to install new version of MantidWorkbench in the error reporter
  docs/source/release/v6.7.0/Workbench/New_features/35332.rst
  qt/python/mantidqt/mantidqt/dialogs/errorreports/errorreport.ui
  qt/python/mantidqt/mantidqt/dialogs/errorreports/report.py
Labels: GUI, ISIS Team: Core

#35833 Add usage report to fitting minimizers
  Framework/CurveFitting/inc/MantidCurveFitting/Algorithms/Fit.h
  Framework/CurveFitting/src/Algorithms/Fit.cpp
Labels: ISIS Team: Core, Investigation

#35834 Make CombineDiffCal more resilient against arbitrary types in the columns
  Framework/Algorithms/inc/MantidAlgorithms/CombineDiffCal.h
  Framework/Algorithms/src/CombineDiffCal.cpp
Labels: Diffraction, Powder

#35806 Update sxd back to back exp parameters
  Testing/SystemTests/tests/framework/SXDAnalysis.py
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/New_features/35703.rst
  instrument/SXD_Parameters.xml
  scripts/Diffraction/single_crystal/test/test_sxd.py
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction

#35821 Abins gaussian parser: read Standard Orientation
  Testing/Data/UnitTest/BENZENE4_g03_win_LoadGAUSSIAN_atomic_displacements_data_0.txt.md5
  Testing/Data/UnitTest/BENZENE4_g03_win_LoadGAUSSIAN_data.txt.md5
  Testing/Data/UnitTest/BENZENE4_g09_win_LoadGAUSSIAN_atomic_displacements_data_0.txt.md5
  Testing/Data/UnitTest/BENZENE4_g09_win_LoadGAUSSIAN_data.txt.md5
  Testing/Data/UnitTest/C6H5Cl_LoadGAUSSIAN_atomic_displacements_data_0.txt.md5
  Testing/Data/UnitTest/C6H5Cl_LoadGAUSSIAN_data.txt.md5
  docs/source/release/v6.8.0/Indirect/Algorithms/Bugfixes/35821.rst
  scripts/abins/input/gaussianloader.py
  scripts/abins/input/textparser.py
Labels: ISIS Team: Spectroscopy

#35676 Clean up mismatch filename
  Testing/SystemTests/lib/systemtests/systemtesting.py
Labels: ISIS Team: Spectroscopy

#35837 PDCalibration spectrumnumber
  Framework/Algorithms/inc/MantidAlgorithms/PDCalibration.h
  Framework/Algorithms/src/CombineDiffCal.cpp
  Framework/Algorithms/src/FitPeaks.cpp
  Framework/Algorithms/src/PDCalibration.cpp
  Framework/Algorithms/test/PDCalibrationTest.h
  docs/source/algorithms/PDCalibration-v1.rst
  docs/source/release/v6.8.0/Diffraction/Powder/New_features/35837.rst
Labels: Diffraction, Powder

#35842 Pin libkafka <= 2.1.1
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid/meta.yaml
Labels: High Priority, Dependencies, DevOps

#35846 Add progress for loading experiment info
  Framework/MDAlgorithms/src/LoadMD.cpp
  docs/source/release/v6.8.0/Framework/Algorithms/Bugfixes/35846.rst
Labels: Bug, Direct Inelastic, Framework

#35679 Clean up after documentation tests
  Framework/Crystal/src/LoadHKL.cpp
  Framework/CurveFitting/src/Algorithms/FitPowderDiffPeaks.cpp
  Testing/Data/DocTest/ILL/D17/676978.nxs.md5
  Testing/Data/DocTest/ILL/D17/676979.nxs.md5
  Testing/Data/DocTest/ILL/D17/676980.nxs.md5
  Testing/Data/DocTest/ILL/D17/676981.nxs.md5
  Testing/Data/DocTest/ILL/D17/676982.nxs.md5
  Testing/Data/DocTest/ILL/D17/676983.nxs.md5
  Testing/Data/DocTest/ILL/D17/676985.nxs.md5
  Testing/Data/DocTest/ILL/FIGARO/732252.nxs.md5
  Testing/Data/DocTest/ILL/FIGARO/732254.nxs.md5
  Testing/Data/DocTest/ILL/FIGARO/732255.nxs.md5
  Testing/Data/DocTest/ILL/FIGARO/743465.nxs.md5
  Testing/Data/DocTest/ILL/FIGARO/743466.nxs.md5
  buildconfig/Jenkins/Conda/conda-buildscript
  docs/source/algorithms/Abins-v1.rst
  docs/source/algorithms/Abins2D-v1.rst
  docs/source/algorithms/ConvertMultipleRunsToSingleCrystalMD-v1.rst
  docs/source/algorithms/CorelliCalibrationDatabase-v1.rst
  docs/source/algorithms/D7YIGPositionCalibration-v1.rst
  docs/source/algorithms/DiffractionEventCalibrateDetectors-v1.rst
  docs/source/algorithms/DirectILLAutoProcess-v1.rst
  docs/source/algorithms/EstimateResolutionDiffraction-v1.rst
  docs/source/algorithms/FitPeaks-v1.rst
  docs/source/algorithms/GeneratePythonFitScript-v1.rst
  docs/source/algorithms/LoadILLReflectometry-v1.rst
  docs/source/algorithms/MDNorm-v1.rst
  docs/source/algorithms/PolarizationCorrectionWildes-v1.rst
  docs/source/algorithms/ReflectometryILLAutoProcess-v1.rst
  docs/source/algorithms/ReflectometryISISCalibration-v1.rst
  docs/source/algorithms/ReflectometrySliceEventWorkspace-v1.rst
  docs/source/algorithms/SANSILLParameterScan-v1.rst
  docs/source/algorithms/SNSPowderReduction-v1.rst
  docs/source/algorithms/SaveHKL-v1.rst
  docs/source/algorithms/SaveHKLCW-v1.rst
  docs/source/algorithms/SavePlot1DAsJson-v1.rst
  docs/source/algorithms/SaveReflections-v1.rst
  docs/source/algorithms/SaveZODS-v1.rst
  docs/source/concepts/MDNorm.rst
  docs/source/concepts/calibration/PowderDiffractionCalibration.rst
  docs/source/plotting/index.rst
  docs/source/techniques/DirectILL.rst
  docs/source/techniques/ReflectometryILL.rst
  docs/source/tutorials/python_in_mantid/further_alg_ws/02_scripting_workspaces.rst
  scripts/Calibration/tofpd/group_calibration.py
Labels: Documentation

#35838 Remove ZenHub references from dev docs
  dev-docs/source/GettingStarted/GettingStarted.rst
  dev-docs/source/IssueTracking.rst
Labels: Documentation, Added during Sprint

#35849 Update mambaforge version in build scripts
  buildconfig/Jenkins/Conda/download-and-install-mambaforge
Labels: ISIS Team: Core

#35430 Add absorbtion corrections to the OSIRIS scripts
  Testing/Data/SystemTest/ISIS_Powder/input/OSIRIS00120032.nxs.md5
  Testing/Data/SystemTest/ISIS_Powder/input/yaml_files/osiris_system_test_mapping.yaml.md5
  Testing/SystemTests/tests/framework/ISIS_PowderOsirisTest.py
  Testing/SystemTests/tests/framework/reference/OSI120032_d_spacing_paalman_corrected.nxs.md5
  Testing/SystemTests/tests/framework/reference/OSI120032_d_spacing_simple_corrected.nxs.md5
  scripts/Diffraction/isis_powder/abstract_inst.py
  scripts/Diffraction/isis_powder/osiris.py
  scripts/Diffraction/isis_powder/osiris_routines/osiris_algs.py
  scripts/Diffraction/isis_powder/osiris_routines/osiris_param_mapping.py
  scripts/Diffraction/isis_powder/routines/focus.py
Labels: ISIS Team: Spectroscopy

#35763 Reset colour bar limit if syntactially invalid value is entered
  docs/source/release/v6.8.0/Workbench/SliceViewer/Bugfixes/34997.rst
  docs/source/release/v6.8.0/Workbench/SliceViewer/New_features/34997.rst
  qt/python/mantidqt/mantidqt/widgets/colorbar/colorbar.py
  qt/python/mantidqt/mantidqt/widgets/colorbar/test/test_colorbar.py
Labels: Bug, ISIS Team: Core

#35822 Preparation for Euphonic version bump: make compatible with both 0.6 and 1.*
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SimulatedDensityOfStates.py
  Testing/SystemTests/tests/framework/SimulatedDensityOfStatesEuphonicPackaging.py
  Testing/SystemTests/tests/framework/SimulatedDensityOfStatesTest.py
  scripts/Inelastic/dos/load_euphonic.py
  scripts/abins/abinsalgorithm.py
  scripts/abins/input/euphonicloader.py
  scripts/test/Abins/AbinsLoadPhonopyTest.py
Labels: ISIS Team: Spectroscopy

#35856 Fix bug that would open a duplicate tab if a file was already open
  docs/source/release/v6.8.0/Workbench/Bugfixes/34979.rst
  qt/python/mantidqt/mantidqt/widgets/codeeditor/multifileinterpreter.py
  qt/python/mantidqt/mantidqt/widgets/codeeditor/test/test_multifileinterpreter.py
Labels: Bug, Induction, ISIS Team: Core

#35848 Abins GAUSSIAN parser: use Input orientation if Standard unavailable
  Testing/Data/UnitTest/croconic_input_orientation_LoadGAUSSIAN.log.md5
  Testing/Data/UnitTest/croconic_input_orientation_LoadGAUSSIAN_atomic_displacements_data_0.txt.md5
  Testing/Data/UnitTest/croconic_input_orientation_LoadGAUSSIAN_data.txt.md5
  scripts/abins/input/gaussianloader.py
  scripts/test/Abins/AbinsLoadGAUSSIANTest.py
Labels: ISIS Team: Spectroscopy
