Repository mantidproject/mantid, pull requests merged in 2023-11, with the labels that each got.

#36343 Changes in Redfield documentation.
  docs/source/fitting/fitfunctions/Redfield.rst
Labels: Documentation, ISIS Team: Spectroscopy

#36336 Fix for waterfall plots not updating their axes limits when offsets were updated
  Framework/PythonInterface/mantid/plots/mantidaxes.py
  Framework/PythonInterface/test/python/mantid/plots/mantidaxesTest.py
  docs/source/release/v6.9.0/Workbench/Bugfixes/36261.rst
Labels: Bug, ISIS Team: Core

#36295 Fix bug in plot settings where apply to all would clear an edited title
  docs/source/release/v6.9.0/Workbench/Bugfixes/32303.rst
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/axestabwidget/axes_tab_widget.ui
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/axestabwidget/presenter.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/plot_config_dialog.ui
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/presenter.py
Labels: Bug, ISIS Team: Core

#36333 Fix UserFunction not updating in Muon Analysis
  Framework/CurveFitting/src/Functions/UserFunction.cpp
  Framework/CurveFitting/test/Functions/UserFunctionTest.h
  docs/source/release/v6.9.0/Muon/Muon_Analysis/Bugfixes/35621.rst
Labels: Bug, Muon, ISIS Team: Spectroscopy

#36353 Only load test data once for BayesStretch2Test
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/BayesStretch2Test.py
Labels: Maintenance, ISIS Team: Spectroscopy

#36334 Update boost to 1.78
  conda/recipes/conda_build_config.yaml
  docs/source/release/templates/framework.rst
  docs/source/release/v6.9.0/Framework/Dependencies/Bugfixes/.gitkeep
  docs/source/release/v6.9.0/Framework/Dependencies/New_features/.gitkeep
  docs/source/release/v6.9.0/Framework/Dependencies/New_features/36315.rst
  docs/source/release/v6.9.0/framework.rst
  docs/sphinxext/mantiddoc/directives/amalgamate.py
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
  tools/release_generator/release.py
Labels: ISIS Team: Core, Added during Sprint, Dependencies

#36273 Clean up running algorithms on AlgorithmManager shutdown
  Framework/API/src/AlgorithmManager.cpp
  Framework/DataHandling/src/DownloadInstrument.cpp
  Framework/PythonInterface/mantid/api/src/Exports/AlgorithmManager.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.9.0/Framework/Algorithms/Bugfixes/35367.rst
Labels: Bug, ISIS Team: Core, Reported By User

#36327 LoadMuonNexusV2 handle no grouping provided
  Framework/DataHandling/inc/MantidDataHandling/LoadMuonNexusV2NexusHelper.h
  Framework/DataHandling/inc/MantidDataHandling/LoadMuonStrategy.h
  Framework/DataHandling/src/LoadMuonNexusV2NexusHelper.cpp
  Framework/DataHandling/src/LoadMuonStrategy.cpp
  Framework/DataHandling/src/MultiPeriodLoadMuonStrategy.cpp
  Framework/DataHandling/src/SinglePeriodLoadMuonStrategy.cpp
  Framework/DataHandling/test/LoadMuonNexusV2Test.h
  Testing/Data/UnitTest/ARGUS00073601.nxs.md5
  docs/source/release/v6.9.0/Muon/Algorithms/Bugfixes/35325.rst
Labels: Bug, Muon, ISIS Team: Spectroscopy

#36330 LoadEventNexus code cleanup and small performance improvements
  Framework/DataHandling/inc/MantidDataHandling/BankPulseTimes.h
  Framework/DataHandling/inc/MantidDataHandling/LoadBankFromDiskTask.h
  Framework/DataHandling/inc/MantidDataHandling/LoadEventNexus.h
  Framework/DataHandling/inc/MantidDataHandling/ProcessBankData.h
  Framework/DataHandling/src/BankPulseTimes.cpp
  Framework/DataHandling/src/LoadBankFromDiskTask.cpp
  Framework/DataHandling/src/LoadEventNexus.cpp
  Framework/DataHandling/src/ProcessBankData.cpp
  Framework/Types/inc/MantidTypes/Core/DateAndTime.h
  Framework/Types/inc/MantidTypes/Event/TofEvent.h
Labels: Diffraction, Powder

#36350 33394 sliceviewer cut exports error fixes
  docs/source/release/v6.9.0/Workbench/SliceViewer/Bugfixes/33394.rst
  qt/python/mantidqt/CMakeLists.txt
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/roi.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_roi.py
Labels: Bug, ISIS Team: Core

#36335 HFIR Background Calculation
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/ConvertWANDSCDtoQ.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/HFIRGoniometerIndependentBackground.py
  Framework/PythonInterface/test/python/plugins/algorithms/ConvertWANDSCDtoQTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/HFIRGoniometerIndependentBackgroundTest.py
  docs/source/algorithms/ConvertWANDSCDtoQ-v1.rst
  docs/source/algorithms/HFIRGoniometerIndependentBackground-v1.rst
  docs/source/release/v6.9.0/Framework/Python/New_features/36335.rst
Labels: Single Crystal

#36367 Remove the `ISISIndirectEnergyTransferWrapper` algorithm
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/EnergyWindowScan.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransferWrapper.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectResolution.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SofQWMomentsScan.py
  Framework/PythonInterface/test/python/plugins/algorithms/GroupBySampleChangerPositionTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransferWrapperTest.py
  dev-docs/source/ISISEnergyTransferTab.rst
  docs/source/algorithms/ISISIndirectEnergyTransferWrapper-v1.rst
  docs/source/diagrams/IndirectResolution-v1_wkflw.dot
  docs/source/release/v4.0.0/indirect_inelastic.rst
  docs/source/release/v6.9.0/Indirect/Algorithms/Bugfixes/36367.rst
  qt/scientific_interfaces/Indirect/ISISCalibration.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModel.cpp
  qt/scientific_interfaces/Indirect/test/ISISEnergyTransferModelTest.h
Labels: Indirect Inelastic, Maintenance, ISIS Team: Spectroscopy

#36379 LoadEventNexus coverity issues
  Framework/DataHandling/src/BankPulseTimes.cpp
  Framework/DataObjects/src/EventList.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance

#36351 Upgrade to matplotlib 3.7
  Framework/PythonInterface/mantid/plots/mantidaxes.py
  Framework/PythonInterface/mantid/plots/resampling_image/samplingimage.py
  Framework/PythonInterface/mantid/plots/utility.py
  Framework/PythonInterface/test/python/mantid/plots/mantidaxesTest.py
  conda/recipes/conda_build_config.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
  qt/applications/workbench/workbench/plotting/figureerrorsmanager.py
  qt/applications/workbench/workbench/plotting/figuremanager.py
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/__init__.py
  qt/applications/workbench/workbench/plotting/toolbar.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/axestabwidget/test/test_axestabwidgetpresenter.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/curvestabwidget/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer/representation/cut_representation.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/representation/test/test_peaksviewer_representation_painter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/HFIR_4Circle_Reduction/mplgraphicsview.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/HFIR_4Circle_Reduction/mplgraphicsview3d.py
  qt/widgets/mplcpp/inc/MantidQtWidgets/MplCpp/Colormap.h
  qt/widgets/mplcpp/src/Colormap.cpp
  qt/widgets/mplcpp/src/MantidColorMap.cpp
  qt/widgets/mplcpp/test/ColormapTest.h
  qt/widgets/mplcpp/test/MantidColormapTest.h
Labels: Maintenance, ISIS Team: Core

#36388 Stop 3D plot shrinking on colorbar change
  Framework/PythonInterface/mantid/plots/datafunctions.py
  docs/source/release/v6.9.0/Workbench/Bugfixes/36388.rst
Labels: Bug, ISIS Team: Core

#36340 Stop plot legends interfering with tight layout
  Framework/PythonInterface/mantid/plots/legend.py
  Framework/PythonInterface/mantid/plots/plotfunctions.py
  Framework/PythonInterface/test/python/mantid/plots/legendTest.py
  docs/source/release/v6.9.0/Workbench/Bugfixes/36267.rst
Labels: Bug, ISIS Team: Core

#35506 Save Additional Metadata to SANS Reduced Output
  Framework/DataHandling/inc/MantidDataHandling/NXcanSASDefinitions.h
  Framework/DataHandling/src/LoadCanSAS1D.cpp
  Framework/DataHandling/src/LoadNXcanSAS.cpp
  Framework/DataHandling/src/SaveCanSAS1D.cpp
  Framework/DataHandling/src/SaveNXcanSAS.cpp
  Framework/DataHandling/test/LoadNXcanSASTest.h
  Framework/DataHandling/test/NXcanSASTestHelper.cpp
  Framework/DataHandling/test/NXcanSASTestHelper.h
  Framework/DataHandling/test/SaveNXcanSASTest.h
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSSave.py
  docs/source/release/v6.9.0/SANS/Bugfixes/28998.rst
  docs/source/release/v6.9.0/SANS/New_features/28998.rst
  scripts/SANS/sans/algorithm_detail/save_workspace.py
  scripts/SANS/sans/algorithm_detail/scale_sans_workspace.py
  scripts/SANS/sans/common/enums.py
  scripts/SANS/sans/common/file_information.py
  scripts/SANS/sans/common/general_functions.py
  scripts/test/SANS/common/general_functions_test.py
Labels: SANS, ISIS Team: LSS

#36404 Load data into a single bin in SNSPowderReduction
  Framework/PythonInterface/plugins/algorithms/SNSPowderReduction.py
Labels: Diffraction, Powder, Maintenance

#36403 Fix deadlock when closing plot while processing
  docs/source/release/v6.9.0/Workbench/Bugfixes/34751.rst
  qt/applications/workbench/workbench/plotting/figuremanager.py
Labels: Bug, ISIS Team: Core

#36231 Fix usage stats for IndirectSettings
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  qt/scientific_interfaces/Indirect/CMakeLists.txt
  qt/scientific_interfaces/Indirect/IIndirectSettingsView.h
  qt/scientific_interfaces/Indirect/IndirectBayes.cpp
  qt/scientific_interfaces/Indirect/IndirectCorrections.cpp
  qt/scientific_interfaces/Indirect/IndirectDataReduction.cpp
  qt/scientific_interfaces/Indirect/IndirectDiffractionReduction.cpp
  qt/scientific_interfaces/Indirect/IndirectInterface.cpp
  qt/scientific_interfaces/Indirect/IndirectInterface.h
  qt/scientific_interfaces/Indirect/IndirectSettings.cpp
  qt/scientific_interfaces/Indirect/IndirectSettings.h
  qt/scientific_interfaces/Indirect/IndirectSettingsPresenter.cpp
  qt/scientific_interfaces/Indirect/IndirectSettingsPresenter.h
  qt/scientific_interfaces/Indirect/IndirectSettingsView.cpp
  qt/scientific_interfaces/Indirect/IndirectSettingsView.h
  qt/scientific_interfaces/Indirect/IndirectSimulation.cpp
  qt/scientific_interfaces/Indirect/IndirectTools.cpp
  qt/scientific_interfaces/Indirect/test/IndirectSettingsPresenterTest.h
  qt/scientific_interfaces/Inelastic/Analysis/IndirectDataAnalysis.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulation.cpp
Labels: Bug, Indirect Inelastic, ISIS Team: Spectroscopy

#36391 Fixes Crash in ApplyAbsorptionCorrections if Corrections file incomplete
  docs/source/release/v6.9.0/Indirect/Bugfixes/36391.rst
  qt/scientific_interfaces/Indirect/ApplyAbsorptionCorrections.cpp
Labels: Bug, Indirect Inelastic, ISIS Team: Spectroscopy, Absorption Corrections

#36338 Fix error in generated MDHisto plot script
  Framework/PythonInterface/mantid/plots/axesfunctions.py
  Framework/PythonInterface/mantid/plots/mantidaxes.py
  docs/source/release/v6.9.0/Workbench/Bugfixes/35749.rst
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/lines.py
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/test/test_plotscriptgeneratorlines.py
Labels: Bug, ISIS Team: Core

#36393 Add tracking between axis title, window title, and plot name
  docs/source/release/v6.9.0/Workbench/New_features/33224.rst
  qt/applications/workbench/workbench/plotting/figuremanager.py
  qt/applications/workbench/workbench/plotting/test/test_figuremanager.py
  qt/applications/workbench/workbench/widgets/plotselector/model.py
  qt/applications/workbench/workbench/widgets/plotselector/test/test_plotselector_model.py
Labels: GUI, ISIS Team: Core

#36416 Avoid qtconsole 5.5.0
  conda/recipes/conda_build_config.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: High Priority, Dependencies

#36339 Refactor `plotRaw` function in ISISEnergyTransferModel
  qt/scientific_interfaces/ISISReflectometry/test/ReflMockObjects.h
  qt/scientific_interfaces/Indirect/CMakeLists.txt
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModel.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModel.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModelUtils.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferPresenter.cpp
  qt/scientific_interfaces/Indirect/Reduction/ReductionAlgorithmUtils.cpp
  qt/scientific_interfaces/Indirect/Reduction/ReductionAlgorithmUtils.h
  qt/scientific_interfaces/Indirect/test/CMakeLists.txt
  qt/scientific_interfaces/Indirect/test/ISISEnergyTransferModelTest.h
  qt/scientific_interfaces/Indirect/test/ISISEnergyTransferModelUtilsTest.h
  qt/scientific_interfaces/Indirect/test/ReductionAlgorithmUtilsTest.h
  qt/widgets/common/inc/MantidQtWidgets/Common/ConfiguredAlgorithm.h
  qt/widgets/common/inc/MantidQtWidgets/Common/IConfiguredAlgorithm.h
  qt/widgets/common/src/BatchAlgorithmRunner.cpp
  qt/widgets/common/src/ConfiguredAlgorithm.cpp
  qt/widgets/common/test/MockConfiguredAlgorithm.h
Labels: Indirect Inelastic, ISIS Team: Spectroscopy

#36386 StartX and EndX columns in Data Analysis tabs are automatically formatted to a precision of six digits
  docs/source/release/v6.9.0/Inelastic/Bugfixes/35714.rst
  qt/scientific_interfaces/Inelastic/Analysis/ConvFitDataView.cpp
  qt/scientific_interfaces/Inelastic/Analysis/ConvFitDataView.h
  qt/scientific_interfaces/Inelastic/Analysis/FqFitDataView.cpp
  qt/scientific_interfaces/Inelastic/Analysis/FqFitDataView.h
  qt/scientific_interfaces/Inelastic/Analysis/IIndirectFitDataView.h
  qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataPresenter.cpp
  qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataPresenter.h
  qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp
  qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.h
  qt/scientific_interfaces/Inelastic/test/ConvFitDataPresenterTest.h
  qt/scientific_interfaces/Inelastic/test/FqFitDataPresenterTest.h
  qt/scientific_interfaces/Inelastic/test/IndirectFitDataPresenterTest.h
Labels: Bug, GUI, ISIS Team: Spectroscopy, Inelastic

#36420 Change qtconsole version pin to minimum plus ban
  conda/recipes/conda_build_config.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: Bug, Reported By User, Dependencies

#36425 Support configurable branch names in jenkins config when using the nightly pipeline jenkinsfile
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
Labels: Bug, Extra Attention, ISIS Team: Core, Added during Sprint, ORNL Team, DevOps

#36392 Add MinimumPeakTotalCount to PDCalibration and FitPeaks.
  Framework/Algorithms/inc/MantidAlgorithms/FitPeaks.h
  Framework/Algorithms/src/FitPeaks.cpp
  Framework/Algorithms/src/PDCalibration.cpp
  Framework/Algorithms/test/FitPeaksTest.h
  docs/source/release/v6.9.0/Diffraction/Powder/New_features/36392.rst
Labels: Diffraction, Powder

#36417 Remove readline and filelock pins
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantiddocs/meta.yaml
  docs/source/conf.py
  mantid-developer-linux.yml
  qt/applications/workbench/workbench/app/start.py
  qt/python/mantidqt/mantidqt/widgets/test/test_jupyterconsole.py
Labels: Maintenance, ISIS Team: Core, DevOps

#36423 Bugfix for pan/zoom/rotate not releasing in plots when double click dialog opens
  docs/source/release/v6.9.0/Workbench/Bugfixes/36106.rst
  docs/source/release/v6.9.0/Workbench/Bugfixes/36384.rst
  qt/applications/workbench/workbench/plotting/figureinteraction.py
  qt/applications/workbench/workbench/plotting/test/test_figureinteraction.py
Labels: Bug, ISIS Team: Core

#36381 IndirectPlotOptionsPresenter is no longer a QObject
  qt/scientific_interfaces/Indirect/CMakeLists.txt
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsPresenter.cpp
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsPresenter.h
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsView.cpp
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsView.h
  qt/scientific_interfaces/Indirect/test/IndirectPlotOptionsPresenterTest.h
Labels: Indirect Inelastic, Maintenance, ISIS Team: Spectroscopy

#36380 Add new options and properties to control a default plot zoom / axes limits
  Framework/Properties/Mantid.properties.template
  Framework/PythonInterface/mantid/plots/plotfunctions.py
  docs/source/concepts/PropertiesFile.rst
  docs/source/release/v6.9.0/Workbench/New_features/35666.rst
  qt/applications/workbench/workbench/widgets/settings/plots/presenter.py
  qt/applications/workbench/workbench/widgets/settings/plots/section_plots.ui
  qt/applications/workbench/workbench/widgets/settings/plots/test/test_plot_settings.py
Labels: ISIS Team: Core

#36402 create amend_config context manager
  Framework/PythonInterface/mantid/kernel/AmendConfig.py
  Framework/PythonInterface/mantid/kernel/__init__.py
  Framework/PythonInterface/test/python/mantid/kernel/AmendConfigTest.py
  Framework/PythonInterface/test/python/mantid/kernel/CMakeLists.txt
  docs/source/api/python/mantid/kernel/AmendConfig.rst
  docs/source/api/python/mantid/kernel/ConfigServiceImpl.rst
  docs/source/concepts/PropertiesFile.rst
  docs/source/release/v6.9.0/Framework/Python/New_features/36402.rst
Labels: ORNL Team

#36366 Improve handling of cvalue information in SANSTubeCalibration algorithm
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSTubeCalibration.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/sans/SANSTubeCalibrationTest.py
  Testing/SystemTests/tests/framework/ISIS/SANS/SANS2D/SANS2DTubeCalibrationTest.py
  docs/source/algorithms/SANSTubeCalibration-v1.rst
  docs/source/release/v6.9.0/SANS/New_features/35981.rst
Labels: SANS, ISIS Team: LSS

#36421 Fix a bug in TimeSplitter::getWorkspaceIndexName().
  Framework/DataObjects/src/TimeSplitter.cpp
  Testing/Data/SystemTest/EQSANS_104088.nxs.h5.md5
  Testing/SystemTests/tests/framework/FilterEventsWithHighFirstIndexSplitter.py
Labels: SANS

#36406 Update PDCalibration documentation.
  Framework/Algorithms/src/FindPeaks.cpp
  Framework/Algorithms/src/FitPeaks.cpp
  Framework/Algorithms/src/PDCalibration.cpp
  Framework/Algorithms/src/StripPeaks.cpp
  docs/source/algorithms/PDCalibration-v1.rst
Labels: Diffraction, Documentation, Powder

#36409 Remove references to unity build
  CMakeLists.txt
  Framework/API/CMakeLists.txt
  Framework/Algorithms/CMakeLists.txt
  Framework/Beamline/CMakeLists.txt
  Framework/Catalog/CMakeLists.txt
  Framework/Crystal/CMakeLists.txt
  Framework/CurveFitting/CMakeLists.txt
  Framework/DataHandling/CMakeLists.txt
  Framework/DataObjects/CMakeLists.txt
  Framework/Geometry/CMakeLists.txt
  Framework/HistogramData/CMakeLists.txt
  Framework/ICat/CMakeLists.txt
  Framework/Indexing/CMakeLists.txt
  Framework/Kernel/CMakeLists.txt
  Framework/LiveData/CMakeLists.txt
  Framework/MDAlgorithms/CMakeLists.txt
  Framework/WorkflowAlgorithms/CMakeLists.txt
  buildconfig/CMake/UnityBuild.cmake
Labels: Maintenance, ISIS Team: Core

#36287 Remove Auto-Generated Docs Screenshots
  docs/source/release/v6.9.0/Workbench/Bugfixes/36287.rst
  docs/sphinxext/mantiddoc/directives/algorithm.py
Labels: Documentation, Maintenance

#36430 unique_name and unique_hidden_name
  Framework/API/inc/MantidAPI/AnalysisDataService.h
  Framework/API/src/AnalysisDataService.cpp
  Framework/API/test/AnalysisDataServiceTest.h
  Framework/PythonInterface/mantid/api/src/Exports/AnalysisDataService.cpp
  Framework/PythonInterface/test/python/mantid/api/AnalysisDataServiceTest.py
  dev-docs/source/TestingUtilities.rst
  docs/source/release/v6.9.0/Framework/Python/New_features/36430.rst
Labels: ORNL Team

#36434 Allow Selection of Beam Centre Adjustment Values Based on Selected Detector in ISIS SANS
  docs/source/release/v6.9.0/SANS/New_features/35957.rst
  scripts/SANS/sans/gui_logic/models/state_gui_model.py
  scripts/SANS/sans/gui_logic/presenter/beam_centre_presenter.py
  scripts/SANS/sans/gui_logic/presenter/run_tab_presenter.py
  scripts/SANS/sans/user_file/toml_parsers/toml_v1_parser.py
  scripts/test/SANS/gui_logic/beam_centre_presenter_test.py
  scripts/test/SANS/gui_logic/state_gui_model_test.py
  scripts/test/SANS/user_file/toml_parsers/toml_v1_parser_test.py
Labels: SANS, GUI, ISIS Team: LSS

#36419 Remove Indirect Settings from interface menu
  qt/scientific_interfaces/Indirect/CMakeLists.txt
  qt/scientific_interfaces/Indirect/IndirectInterface.cpp
  qt/scientific_interfaces/Indirect/IndirectSettings.cpp
  qt/scientific_interfaces/Indirect/IndirectSettings.h
  qt/scientific_interfaces/Indirect/IndirectSettings.ui
  qt/widgets/common/inc/MantidQtWidgets/Common/InterfaceManager.h
  qt/widgets/common/src/InterfaceManager.cpp
Labels: Maintenance, ISIS Team: Spectroscopy, Inelastic

#36447 Pin openblas away from 0.3.25 to fix system test failure
  conda/recipes/conda_build_config.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
Labels: High Priority, DevOps

#36438 Adds a missing import line on Bayes Stretch
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesStretch.py
  docs/source/release/v6.9.0/Framework/Algorithms/Bugfixes/36438.rst
Labels: Bug, ISIS Team: Spectroscopy

#36446 Fix plot not updating in Slice Viewer
  docs/source/release/v6.9.0/Workbench/SliceViewer/Bugfixes/34403.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/cutviewer/view.py
Labels: Bug, ISIS Team: Core

#36424 Fix crash from adding new batches in the ISIS Reflectometry GUI
  dev-docs/source/Testing/ReflectometryGUI/ReflectometryGUITests.rst
  docs/source/release/v6.9.0/Reflectometry/Bugfixes/36424.rst
  qt/widgets/mplcpp/src/FigureCanvasQt.cpp
Labels: High Priority, Reflectometry, ISIS Team: LSS

#36449 Limit what is printed in the sample logs viewer for large arrays
  docs/source/release/v6.9.0/Workbench/Bugfixes/36449.rst
  qt/python/mantidqt/mantidqt/widgets/samplelogs/model.py
Labels: GUI

#36354 Check for "bank" component before running Indirect diffraction
  Framework/Geometry/src/Instrument.cpp
  Framework/Kernel/src/Exception.cpp
  Framework/PythonInterface/test/python/plugins/algorithms/RetrieveRunInfoTest.py
  docs/source/release/v6.9.0/Indirect/Bugfixes/36019.rst
  qt/scientific_interfaces/Indirect/IndirectDiffractionReduction.cpp
  qt/scientific_interfaces/Indirect/IndirectDiffractionReduction.h
Labels: Bug, Indirect Inelastic, ISIS Team: Spectroscopy

#36432 Set figure grid enabled option in all cases
  docs/source/release/v6.9.0/Workbench/Bugfixes/36432.rst
  qt/applications/workbench/workbench/plotting/propertiesdialog.py
Labels: Bug, ISIS Team: Core

#36439 Replaces Plot Contour Option in Indirect/Inelastic interfaces with opening Slice Viewer.
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  dev-docs/source/Testing/IndirectInelastic/IndirectInelasticAcceptanceTests.rst
  docs/source/interfaces/indirect/Indirect Corrections.rst
  docs/source/interfaces/indirect/Indirect Data Reduction.rst
  docs/source/interfaces/indirect/Indirect Diffraction.rst
  docs/source/interfaces/indirect/Indirect Simulation.rst
  docs/source/interfaces/inelastic/Inelastic Data Manipulation.rst
  docs/source/release/v6.9.0/Indirect/New_features/36344.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/__init__.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenters/presenter.py
  qt/scientific_interfaces/Indirect/ApplyAbsorptionCorrections.cpp
  qt/scientific_interfaces/Indirect/ContainerSubtraction.cpp
  qt/scientific_interfaces/Indirect/IndirectDiffractionReduction.cpp
  qt/scientific_interfaces/Indirect/IndirectMolDyn.cpp
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsModel.cpp
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsModel.h
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsPresenter.cpp
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsPresenter.h
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsView.cpp
  qt/scientific_interfaces/Indirect/IndirectPlotOptionsView.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferPresenter.cpp
  qt/scientific_interfaces/Indirect/test/IndirectPlotOptionsModelTest.h
  qt/scientific_interfaces/Indirect/test/IndirectPlotOptionsPresenterTest.h
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationSqwTab.cpp
  qt/widgets/mplcpp/inc/MantidQtWidgets/MplCpp/Plot.h
  qt/widgets/mplcpp/src/Plot.cpp
  qt/widgets/plotting/inc/MantidQtWidgets/Plotting/ExternalPlotter.h
  qt/widgets/plotting/src/ExternalPlotter.cpp
Labels: ISIS Team: Spectroscopy, Inelastic

#36458 Fix bug where dragging a group workspace onto a plot would cause an unhandled exception
  docs/source/release/v6.9.0/Workbench/Bugfixes/36458.rst
  qt/applications/workbench/workbench/plotting/figurewindow.py
Labels: ISIS Team: Core

#36450 Stop the splash screen hijacking the display
  docs/source/release/v6.9.0/Workbench/Bugfixes/36450.rst
  qt/applications/workbench/workbench/app/mainwindow.py
Labels: ISIS Team: Core

#36455 Only remove old anaconda packages from nightly label
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
Labels: Bug, Extra Attention, ISIS Team: Core, Added during Sprint, DevOps

#36461 Improve Slice Viewer colour bar memory leak
  docs/source/release/v6.9.0/Workbench/SliceViewer/Bugfixes/36428.rst
  qt/python/mantidqt/mantidqt/widgets/colorbar/colorbar.py
Labels: ISIS Team: LSS

#36451 Added Wrapper alias for ISISIndirectEnergyTransfer algorithm
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransfer.py
Labels: Indirect Inelastic, ISIS Team: Spectroscopy

#36487 Pin openssl to resolve mantidqt environment issue
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid/meta.yaml
Labels: High Priority, ISIS Team: Core, Linux Only, Added during Sprint, Dependencies, DevOps

#36463 Load files with periods with no data
  Framework/DataHandling/inc/MantidDataHandling/LoadEventNexus.h
  Framework/DataHandling/src/LoadEventNexus.cpp
  Framework/DataHandling/test/LoadEventNexusTest.h
  Testing/Data/UnitTest/LARMOR00062766.nxs.md5
  docs/source/release/v6.9.0/Framework/Data_Handling/Bugfixes/33729.rst
Labels: Bug, ISIS Team: Core

#36345 Add a new option to AppendSpectra to append Y-axis values
  Framework/Algorithms/inc/MantidAlgorithms/AppendSpectra.h
  Framework/Algorithms/src/AppendSpectra.cpp
  Framework/Algorithms/test/AppendSpectraTest.h
  docs/source/algorithms/AppendSpectra-v1.rst
  docs/source/release/v6.9.0/Framework/Algorithms/New_features/36345.rst
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationElwinTabModel.cpp
Labels: Framework, ISIS Team: Spectroscopy

#36495 Fix makensis syntax in windows packaging script
  installers/conda/win/create_package.sh
Labels: High Priority, Windows Only, DevOps
