Repository mantidproject/mantid, pull requests merged in 2023-09, with the labels that each got.

#35991 Temporarily disable `TransformToIqt` doctest
  docs/source/algorithms/TransformToIqt-v1.rst
Labels: High Priority, DevOps

#35993 Add missing regex escape in delete old nightly releases workflow
  .github/workflows/delete_old_nightly_releases.yml
Labels: Bug, Extra Attention, ISIS Team: Core, Added during Sprint, DevOps

#35972 Fix crash in muon analysis fitting interface
  docs/source/release/v6.8.0/Muon/Muon_Analysis/Bugfixes/35505.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/utilities/algorithm_utils.py
  qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_model_test.py
Labels: Bug, Muon, ISIS Team: Spectroscopy

#36001 Pin libopenblas again
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid/meta.yaml
  conda/recipes/mantidqt/meta.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
Labels: High Priority, macOS Only, ISIS Team: Core, Linux Only, Added during Sprint, Dependencies, DevOps

#35986 Updated SHA and added release note
  docs/source/release/v6.8.0/mslice_direct_geometry.rst
  mantid-developer-win.yml
  scripts/ExternalInterfaces/CMakeLists.txt
Labels: High Priority, ISIS Team: Excitations/Vesuvio

#35938 Fix bug where plot script generator button wouldn't show on certain tiled plots
  docs/source/release/v6.8.0/Workbench/Bugfixes/33226.rst
  qt/applications/workbench/workbench/plotting/plotscriptgenerator/__init__.py
  qt/applications/workbench/workbench/plotting/test/test_toolbar.py
  qt/applications/workbench/workbench/plotting/toolbar.py
Labels: Bug, ISIS Team: Core

#35988 Allow BackgroundWorkspace to be given as an OutputName
  docs/source/interfaces/isis_sans/Runs Tab.rst
  scripts/SANS/sans/algorithm_detail/batch_execution.py
  scripts/test/SANS/algorithm_detail/batch_execution_test.py
Labels: SANS, GUI, ISIS Team: LSS

#35998 Improve right-click behaviour in table view
  docs/source/release/v6.8.0/Workbench/Bugfixes/35583.rst
  qt/python/mantidqt/mantidqt/widgets/workspacedisplay/matrix/view.py
Labels: Bug, ISIS Team: Core

#35914 Improved single-crystal peak finding algorithm
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/FindSXPeaksConvolve.py
  Framework/PythonInterface/plugins/algorithms/IntegratePeaksSkew.py
  Framework/PythonInterface/test/python/plugins/algorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/FindSXPeaksConvolveTest.py
  docs/source/algorithms/FindSXPeaksConvolve-v1.rst
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/New_features/35914.rst
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction

#35984 Add tube calibration algorithms for Sans2d
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSTubeCalibration.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSTubeMerge.py
  Framework/PythonInterface/plugins/functions/FlatTopPeak.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/sans/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/sans/SANSTubeCalibrationTest.py
  Framework/PythonInterface/test/python/plugins/functions/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/functions/FlatTopPeakTest.py
  Testing/Data/SystemTest/SANS2D00069116.nxs.md5
  Testing/Data/SystemTest/SANS2D00069117.nxs.md5
  Testing/Data/SystemTest/SANS2D00069118.nxs.md5
  Testing/Data/SystemTest/SANS2D00069119.nxs.md5
  Testing/Data/SystemTest/SANS2D00069120.nxs.md5
  Testing/SystemTests/tests/framework/ISIS/SANS/SANS2D/SANS2DTubeCalibrationTest.py
  Testing/SystemTests/tests/framework/ISIS/SANS/SANS2D/SANS2DTubeMergeTest.py
  Testing/SystemTests/tests/framework/reference/SANS2DTubeCalibration_cvalues_front.nxs.md5
  Testing/SystemTests/tests/framework/reference/SANS2DTubeCalibration_cvalues_rear.nxs.md5
  Testing/SystemTests/tests/framework/reference/SANS2DTubeMerge_empty_instr.nxs.md5
  Testing/SystemTests/tests/framework/reference/SANS2DTubeMerge_front.nxs.md5
  Testing/SystemTests/tests/framework/reference/SANS2DTubeMerge_rear.nxs.md5
  docs/source/algorithms/SANSTubeCalibration-v1.rst
  docs/source/algorithms/SANSTubeMerge-v1.rst
  docs/source/images/SANSTubeCalibration_calibrated.png
  docs/source/images/SANSTubeCalibration_original.png
  docs/source/release/v6.8.0/SANS/New_features/35984.rst
Labels: SANS, ISIS Team: LSS

#36002 Group Background Subtracted Workspaces Correctly
  scripts/SANS/sans/algorithm_detail/batch_execution.py
  scripts/test/SANS/algorithm_detail/batch_execution_test.py
Labels: Bug, SANS, ISIS Team: LSS

#36014 Make const references as suggested by coverity
  Framework/Algorithms/src/CorelliCalibrationDatabase.cpp
  Framework/Algorithms/src/CreateDetectorTable.cpp
  Framework/Algorithms/src/SumEventsByLogValue.cpp
  Framework/Crystal/src/GoniometerAnglesFromPhiRotation.cpp
  Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp
  Framework/DataHandling/src/SaveReflectometryAscii.cpp
  Framework/DataObjects/inc/MantidDataObjects/MortonIndex/WideIntImpl.h
  Framework/MDAlgorithms/src/LoadDNSSCD.cpp
  Framework/MDAlgorithms/src/MDNorm.cpp
  Framework/Muon/src/ConvertFitFunctionForMuonTFAsymmetry.cpp
  Framework/Muon/src/MuonAlgorithmHelper.cpp
  Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp
  qt/scientific_interfaces/Indirect/FqFitDataPresenter.cpp
  qt/scientific_interfaces/Indirect/IndirectFitData.cpp
  qt/widgets/common/src/FunctionModel.cpp
  qt/widgets/common/src/FunctionTreeView.cpp
  qt/widgets/instrumentview/src/InstrumentActor.cpp
  qt/widgets/instrumentview/src/InstrumentWidgetPickTab.cpp
Labels: Maintenance

#35937 Fix workspaces being overwritten in individual focussing mode ISIS powder scripts
  docs/source/release/v6.8.0/Diffraction/Powder/Bugfixes/35937.rst
  scripts/Diffraction/isis_powder/abstract_inst.py
  scripts/Diffraction/isis_powder/test/ISISPowderAbstractInstrumentTest.py
Labels: Diffraction, Powder, ISIS Team: Diffraction

#36006 Minor fixes for isis single-crystal reduction class
  Testing/SystemTests/tests/framework/ISIS_WISHSingleCrystalReduction.py
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/Bugfixes/36006.rst
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/New_features/36006.rst
  scripts/Diffraction/single_crystal/base_sx.py
  scripts/Diffraction/single_crystal/sxd.py
  scripts/Diffraction/single_crystal/test/test_sxd.py
  scripts/Diffraction/wish/wishSX.py
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction

#35927 Add multiple scattering correction to OSIRIS script
  Testing/SystemTests/tests/framework/ISIS_PowderOsirisTest.py
  Testing/SystemTests/tests/framework/reference/OSI120032_d_multiple_scattering_corrected.nxs.md5
  Testing/SystemTests/tests/framework/reference/OSI120032_d_spacing_paalman_corrected.nxs.md5
  Testing/SystemTests/tests/framework/reference/OSI120032_d_spacing_simple_corrected.nxs.md5
  scripts/Diffraction/isis_powder/osiris.py
  scripts/Diffraction/isis_powder/osiris_routines/osiris_param_mapping.py
Labels: Diffraction, ISIS Team: Spectroscopy

#36020 Remove obsolete setuptools warnings
  Testing/SystemTests/lib/systemtests/systemtesting.py
  buildconfig/CMake/Packaging/launch_mantidworkbench.sh.in
Labels: ISIS Team: Core, Linux Only, Added during Sprint

#36022 Fix SANSTubeCalibration system test
  Testing/SystemTests/tests/framework/ISIS/SANS/SANS2D/SANS2DTubeCalibrationTest.py
Labels: High Priority, SANS, ISIS Team: LSS

#35985 Remove unused `killall` command and `use-core-dumps` option
  buildconfig/Jenkins/Conda/conda-buildscript
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
  buildconfig/Jenkins/Conda/run-tests
  buildconfig/Jenkins/buildscript
Labels: Maintenance, DevOps

#36008 distutils.LooseVersion deprecated in Python 3.10
  Framework/PythonInterface/mantid/plots/legend.py
  Framework/PythonInterface/mantid/plots/scales.py
  Framework/PythonInterface/mantid/plots/utility.py
  Framework/PythonInterface/plugins/algorithms/ExportSampleLogsToCSVFile.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/FindPeaksAutomatic.py
  Framework/PythonInterface/test/python/mantid/kernel/DateAndTimeTest.py
  Framework/PythonInterface/test/python/mantid/plots/ScalesTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/CalculateFluxTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/ExportSampleLogsToCSVFileTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/DirectILLApplySelfShieldingTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/DirectILLCollectDataTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/DirectILLReductionTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/DirectILLSelfShieldingTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/FindPeakAutomaticTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ReflectometryILLPreprocessTest.py
  Framework/PythonInterface/test/testhelpers/__init__.py
  Testing/SystemTests/tests/framework/ILLDetectorEfficiencyCorUserTest.py
  docs/source/conf.py
  docs/sphinxext/mantiddoc/directives/plot_directive.py
  qt/applications/workbench/workbench/plotting/test/test_figureinteraction.py
  qt/python/mantidqt/mantidqt/utils/qt/__init__.py
  qt/python/mantidqt/mantidqt/widgets/codeeditor/test/test_completion.py
  qt/python/mantidqt/mantidqt/widgets/colorbar/colorbar.py
  scripts/test/CrystalFieldMultiSiteTest.py
Labels: ISIS Team: Core, Added during Sprint

#35989 Add InterpolateBackground to SNSPowderReduction
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/AlignAndFocusPowderFromFiles.py
  Framework/PythonInterface/plugins/algorithms/SNSPowderReduction.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/InterpolateBackground.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/InterpolateBackgroundTest.py
  docs/source/algorithms/InterpolateBackground-v1.rst
  docs/source/release/v6.8.0/Framework/Python/New_features/35989.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/reduction_gui/widgets/diffraction/diffraction_run_setup.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/ui/diffraction/diffraction_run_setup.ui
  scripts/reduction_gui/reduction/diffraction/diffraction_reduction_script.py
  scripts/reduction_gui/reduction/diffraction/diffraction_run_setup_script.py
Labels: Diffraction, Powder

#35901 Refactor ISIS Energy Transfer to make it MVP compatible
  dev-docs/source/ISISEnergyTransferTab.rst
  qt/scientific_interfaces/Indirect/CMakeLists.txt
  qt/scientific_interfaces/Indirect/ISISEnergyTransfer.cpp
  qt/scientific_interfaces/Indirect/ISISEnergyTransfer.h
  qt/scientific_interfaces/Indirect/IndirectDataReduction.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransfer.ui
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferData.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModel.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModel.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModelUtils.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferPresenter.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferPresenter.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferValidator.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferValidator.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferView.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferView.h
  qt/scientific_interfaces/Indirect/test/CMakeLists.txt
  qt/scientific_interfaces/Indirect/test/ISISEnergyTransferModelTest.h
  qt/scientific_interfaces/Indirect/test/ISISEnergyTransferModelUtilsTest.h
Labels: ISIS Team: Spectroscopy

#36010 Add New Algorithm InterpolateBackground
  docs/source/release/v6.8.0/Framework/Python/New_features/36010.rst
Labels: Diffraction, Powder

#35933 Add new Stale github action
  .github/stale.yml
  .github/workflows/stale.yml
Labels: Maintenance, ISIS Team: Core

#36029 Fix problem with macOS version check.
  qt/python/mantidqt/mantidqt/utils/qt/__init__.py
Labels: High Priority, Extra Attention, macOS Only, ISIS Team: Core

#35389 Powder Elastic mode for the DNS Reduction GUI
  docs/source/images/DNS_interface_powder_elastic_options_tab.png
  docs/source/images/DNS_interface_powder_elastic_overview.png
  docs/source/images/DNS_interface_powder_elastic_plotting_tab.png
  docs/source/images/DNS_interface_powder_elastic_script_generator_tab.png
  docs/source/interfaces/direct/dns_reduction/DNS Powder Elastic.rst
  docs/source/interfaces/direct/dns_reduction/DNS Reduction.rst
  docs/source/interfaces/direct/dns_reduction/dns_powder_elastic_options_tab.rst
  docs/source/interfaces/direct/dns_reduction/dns_powder_elastic_plotting_tab.rst
  docs/source/interfaces/direct/dns_reduction/dns_powder_elastic_script_generator_tab.rst
  docs/source/release/v6.8.0/Direct_Geometry/DNS_Reduction/New_features/.gitkeep
  docs/source/release/v6.8.0/Direct_Geometry/DNS_Reduction/New_features/35389.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/DNS_Reduction.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/command_line/__init__.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/command_line/command_check.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/data_structures/__init__.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/data_structures/dns_binning.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/data_structures/dns_elastic_powder_dataset.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/data_structures/dns_plot_list.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/data_structures/field_names.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/helpers/converters.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/options/__init__.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/options/elastic_powder_options.ui
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/options/elastic_powder_options_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/options/elastic_powder_options_view.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/options/elastic_powder_options_widget.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/plot/__init__.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/plot/elastic_powder_plot.ui
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/plot/elastic_powder_plot_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/plot/elastic_powder_plot_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/plot/elastic_powder_plot_view.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/plot/elastic_powder_plot_widget.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/script_generator/__init__.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/script_generator/elastic_powder_script_generator_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/script_generator/elastic_powder_script_generator_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/script_generator/elastic_powder_script_generator_widget.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/scripts/__init__.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_elastic/scripts/md_powder_elastic.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_tof/dns_gui_main_reduced_menu.ui
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_tof/dns_modus.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_tof/file_selector/file_selector_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_tof/helpers/helpers_for_testing.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_tof/main_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_tof/main_view.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_tof/main_widget.py
  qt/python/mantidqtinterfaces/test/CMakeLists.txt
  qt/python/mantidqtinterfaces/test/dns_powder_elastic/CMakeLists.txt
  qt/python/mantidqtinterfaces/test/dns_powder_elastic/command_line/command_check_test.py
  qt/python/mantidqtinterfaces/test/dns_powder_elastic/data_structures/dns_binning_test.py
  qt/python/mantidqtinterfaces/test/dns_powder_elastic/data_structures/dns_elastic_powder_dataset_test.py
  qt/python/mantidqtinterfaces/test/dns_powder_elastic/data_structures/dns_plot_list_test.py
  qt/python/mantidqtinterfaces/test/dns_powder_elastic/data_structures/field_names_test.py
  qt/python/mantidqtinterfaces/test/dns_powder_elastic/options/elastic_powder_options_presenter_test.py
  qt/python/mantidqtinterfaces/test/dns_powder_elastic/options/elastic_powder_options_widget_test.py
  qt/python/mantidqtinterfaces/test/dns_powder_elastic/plot/elastic_powder_plot_model_test.py
  qt/python/mantidqtinterfaces/test/dns_powder_elastic/plot/elastic_powder_plot_presenter_test.py
  qt/python/mantidqtinterfaces/test/dns_powder_elastic/plot/elastic_powder_plot_widget_test.py
  qt/python/mantidqtinterfaces/test/dns_powder_elastic/script_generator/elastic_powder_script_generator_model_test.py
  qt/python/mantidqtinterfaces/test/dns_powder_elastic/script_generator/elastic_powder_script_generator_presenter_test.py
  qt/python/mantidqtinterfaces/test/dns_powder_elastic/script_generator/elastic_powder_script_generator_widget_test.py
  qt/python/mantidqtinterfaces/test/dns_powder_elastic/scripts/md_powder_elastic_test.py
Labels: Powder, GUI, MLZ Team

#36035 Remove expletive
  Framework/SINQ/src/ProjectMD.cpp
Labels: Maintenance

#36111 Add time slicing info to SANS scaled background subtraction docs
  docs/source/interfaces/isis_sans/Runs Tab.rst
Labels: SANS, Documentation, ISIS Team: LSS

#36094 Fix sample log implicit conversion warning
  docs/source/release/v6.8.0/Workbench/Bugfixes/36089.rst
  qt/python/mantidqt/mantidqt/widgets/samplelogs/model.py
Labels: Bug, ISIS Team: Core

#36100 Fix bug when trying to select the EISFDiffSphereAlky function
  Framework/PythonInterface/mantid/api/src/FitFunctions/IFunctionAdapter.cpp
  Framework/PythonInterface/plugins/functions/EISFDiffSphereAlkyl.py
  docs/source/release/v6.8.0/Indirect/Bugfixes/36076.rst
Labels: High Priority, Bug, Indirect Inelastic, ISIS Team: Core

#36117 Matplotlib backend is imported before Gcf is initialised
  qt/applications/workbench/workbench/app/start.py
  qt/applications/workbench/workbench/plotting/config.py
Labels: High Priority, Bug, ISIS Team: Core

#36086 Update FSG usage example screenshots
  docs/source/images/FitScriptGenerator_SequentialFit.png
  docs/source/images/FitScriptGenerator_SimultaneousFit.png
Labels: Documentation, Maintenance

#36119 Clip colorbar range in Sliceviewer
  qt/python/mantidqt/mantidqt/widgets/colorbar/colorbar.py
Labels: Bug, Single Crystal

#35978 Refactor LoadEmptyInstrument and LoadCalFile
  Framework/DataHandling/inc/MantidDataHandling/LoadEmptyInstrument.h
  Framework/DataHandling/src/LoadCalFile.cpp
  Framework/DataHandling/src/LoadEmptyInstrument.cpp
  Framework/DataHandling/test/LoadCalFileTest.h
  Framework/DataHandling/test/LoadEmptyInstrumentTest.h
  Framework/Kernel/inc/MantidKernel/EnumeratedString.h
  Framework/Kernel/test/EnumeratedStringTest.h
  docs/source/release/v6.9.0/Framework/Data_Handling/New_features/35978.rst
Labels: Diffraction, Powder

#36135 AlignAndFocusPowderFromFiles: get value from StringArrayProperty to add the values to a list
  Framework/PythonInterface/plugins/algorithms/AlignAndFocusPowderFromFiles.py
Labels: Bug, Diffraction, Powder

#36125 Fix GUI hang when eng diff peak type invalid
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/EngDiff_fitpropertybrowser.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/test/test_presenter.py
  qt/widgets/common/src/FitPropertyBrowser.cpp
Labels: Bug, Diffraction, ISIS Team: LSS

#36132 Propagate C++ exception to python for `createDialogFromName`
  qt/python/mantidqt/mantidqt/_common.sip
  qt/python/mantidqt/sip/exceptions.sip
Labels: Bug, ISIS Team: Core

#36124 Fix bug in sliceviewer to exclude non-Q components from basis vectors in proj matrix
  Testing/SystemTests/tests/qt/SliceViewerIntegrationTest.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py
Labels: Bug, ISIS Team: Core

#36155 Include Imports Required to Run Scripts in Workspace Group Docs
  docs/source/concepts/WorkspaceGroup.rst
Labels: Documentation, Maintenance, ISIS Team: LSS

#36066 Avoid use of unit test data in manual tests
  dev-docs/source/Testing/DirectInelastic/MSliceTestGuide.rst
  dev-docs/source/Testing/ReflectometryGUI/ReflectometryGUITests.rst
Labels: Documentation

#36158 `PDCalibration` should sort peak windows with centers
  Framework/Algorithms/src/PDCalibration.cpp
  docs/source/release/v6.8.0/Diffraction/Powder/Bugfixes/36122.rst
Labels: Diffraction, Powder, ORNL Team

#36163 Fix `ConvertDiffcal` logic and error throwing for signed mode
  Framework/Algorithms/src/ConvertDiffCal.cpp
  Framework/Algorithms/test/ConvertDiffCalTest.h
Labels: Diffraction, Found in Beta, ORNL Team

#36160 Initial LSS release notes for v6.8
  docs/source/release/v6.8.0/Reflectometry/Bugfixes/Used/35717.rst
  docs/source/release/v6.8.0/Reflectometry/Bugfixes/Used/35826.rst
  docs/source/release/v6.8.0/Reflectometry/Bugfixes/Used/35941.rst
  docs/source/release/v6.8.0/Reflectometry/Bugfixes/Used/35942.rst
  docs/source/release/v6.8.0/Reflectometry/Bugfixes/Used/35945.rst
  docs/source/release/v6.8.0/Reflectometry/Bugfixes/Used/36024.rst
  docs/source/release/v6.8.0/Reflectometry/New_features/Used/35873.rst
  docs/source/release/v6.8.0/SANS/Bugfixes/Used/35715.rst
  docs/source/release/v6.8.0/SANS/New_features/Used/35446.rst
  docs/source/release/v6.8.0/SANS/New_features/Used/35984.rst
  docs/source/release/v6.8.0/reflectometry.rst
  docs/source/release/v6.8.0/sans.rst
Labels: Documentation

#36157 Initial diffraction release notes for v6.8
  docs/source/release/v6.8.0/Diffraction/Engineering/New_features/Used/35885.rst
  docs/source/release/v6.8.0/Diffraction/Powder/Bugfixes/Used/35765.rst
  docs/source/release/v6.8.0/Diffraction/Powder/Bugfixes/Used/35768.rst
  docs/source/release/v6.8.0/Diffraction/Powder/Bugfixes/Used/35937.rst
  docs/source/release/v6.8.0/Diffraction/Powder/Bugfixes/Used/36122.rst
  docs/source/release/v6.8.0/Diffraction/Powder/New_features/Used/35671.rst
  docs/source/release/v6.8.0/Diffraction/Powder/New_features/Used/35760.rst
  docs/source/release/v6.8.0/Diffraction/Powder/New_features/Used/35783.rst
  docs/source/release/v6.8.0/Diffraction/Powder/New_features/Used/35800.rst
  docs/source/release/v6.8.0/Diffraction/Powder/New_features/Used/35818.rst
  docs/source/release/v6.8.0/Diffraction/Powder/New_features/Used/35837.rst
  docs/source/release/v6.8.0/Diffraction/Powder/New_features/Used/35872.rst
  docs/source/release/v6.8.0/Diffraction/Powder/New_features/Used/36027.rst
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/Bugfixes/Used/35706.rst
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/Bugfixes/Used/35776.rst
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/Bugfixes/Used/36006.rst
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/New_features/Used/35623.rst
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/New_features/Used/35703.rst
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/New_features/Used/35706.rst
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/New_features/Used/35776.rst
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/New_features/Used/35799.rst
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/New_features/Used/35861.rst
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/New_features/Used/35868.rst
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/New_features/Used/35914.rst
  docs/source/release/v6.8.0/Diffraction/Single_Crystal/New_features/Used/36006.rst
  docs/source/release/v6.8.0/diffraction.rst
Labels: Documentation

#36165 Move verifyAndClear to teardown method in ExperimentPresenterTest
  qt/scientific_interfaces/ISISReflectometry/test/Experiment/ExperimentPresenterTest.h
Labels: Reflectometry, ISIS Team: LSS

#36034 Update sliceviewer testing instructions
  dev-docs/source/Testing/SliceViewer/SliceViewer.rst
  dev-docs/source/images/SliceViewer/CutViewer_HKplane.png
Labels: Documentation, ISIS Team: Core

#36177 Add link to release notes guide in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation

#36162 Initial framework and workbench release notes for v6.8
  docs/source/interfaces/general/Sample Transmission Calculator.rst
  docs/source/interfaces/utility/TOF Converter.rst
  docs/source/release/v6.8.0/Framework/Algorithms/Bugfixes/Used/34255.rst
  docs/source/release/v6.8.0/Framework/Algorithms/Bugfixes/Used/35687.rst
  docs/source/release/v6.8.0/Framework/Algorithms/Bugfixes/Used/35787.rst
  docs/source/release/v6.8.0/Framework/Algorithms/Bugfixes/Used/35789.rst
  docs/source/release/v6.8.0/Framework/Algorithms/Bugfixes/Used/35846.rst
  docs/source/release/v6.8.0/Framework/Algorithms/New_features/Used/35724.rst
  docs/source/release/v6.8.0/Framework/Algorithms/New_features/Used/35862.rst
  docs/source/release/v6.8.0/Framework/Algorithms/New_features/Used/35896.rst
  docs/source/release/v6.8.0/Framework/Algorithms/New_features/Used/35936.rst
  docs/source/release/v6.8.0/Framework/Algorithms/New_features/Used/35971.rst
  docs/source/release/v6.8.0/Framework/Data_Handling/New_features/Used/35867.rst
  docs/source/release/v6.8.0/Framework/Data_Handling/New_features/Used/35976.rst
  docs/source/release/v6.8.0/Framework/Data_Objects/Bugfixes/Used/35767.rst
  docs/source/release/v6.8.0/Framework/Data_Objects/Bugfixes/Used/35784.rst
  docs/source/release/v6.8.0/Framework/Data_Objects/Bugfixes/Used/35793.rst
  docs/source/release/v6.8.0/Framework/Data_Objects/Bugfixes/Used/35802.rst
  docs/source/release/v6.8.0/Framework/Data_Objects/New_features/Used/35462.rst
  docs/source/release/v6.8.0/Framework/Python/New_features/Used/35228.rst
  docs/source/release/v6.8.0/Framework/Python/New_features/Used/35989.rst
  docs/source/release/v6.8.0/Framework/Python/New_features/Used/36010.rst
  docs/source/release/v6.8.0/Framework/Python/New_features/Used/36021.rst
  docs/source/release/v6.8.0/Workbench/Bugfixes/Used/32474.rst
  docs/source/release/v6.8.0/Workbench/Bugfixes/Used/33226.rst
  docs/source/release/v6.8.0/Workbench/Bugfixes/Used/33369.rst
  docs/source/release/v6.8.0/Workbench/Bugfixes/Used/34397.rst
  docs/source/release/v6.8.0/Workbench/Bugfixes/Used/34979.rst
  docs/source/release/v6.8.0/Workbench/Bugfixes/Used/35011.rst
  docs/source/release/v6.8.0/Workbench/Bugfixes/Used/35583.rst
  docs/source/release/v6.8.0/Workbench/Bugfixes/Used/35636.rst
  docs/source/release/v6.8.0/Workbench/Bugfixes/Used/35885.rst
  docs/source/release/v6.8.0/Workbench/Bugfixes/Used/36089.rst
  docs/source/release/v6.8.0/Workbench/InstrumentViewer/Bugfixes/Used/35907.rst
  docs/source/release/v6.8.0/Workbench/New_features/Used/34787.rst
  docs/source/release/v6.8.0/Workbench/SliceViewer/Bugfixes/Used/34997.rst
  docs/source/release/v6.8.0/Workbench/SliceViewer/Bugfixes/Used/35812.rst
  docs/source/release/v6.8.0/Workbench/SliceViewer/New_features/Used/34997.rst
  docs/source/release/v6.8.0/Workbench/SliceViewer/New_features/Used/35594.rst
  docs/source/release/v6.8.0/Workbench/SliceViewer/New_features/Used/35857.rst
  docs/source/release/v6.8.0/framework.rst
  docs/source/release/v6.8.0/mantidworkbench.rst
Labels: Documentation

#36136 Implement EventList generateHistogram without sorting, use within AlignAndFocusPowder
  Framework/Algorithms/src/Rebin.cpp
  Framework/Algorithms/test/RebinTest.h
  Framework/DataObjects/inc/MantidDataObjects/EventList.h
  Framework/DataObjects/inc/MantidDataObjects/EventWorkspace.h
  Framework/DataObjects/src/EventList.cpp
  Framework/DataObjects/test/EventListTest.h
  Framework/WorkflowAlgorithms/inc/MantidWorkflowAlgorithms/AlignAndFocusPowder.h
  Framework/WorkflowAlgorithms/src/AlignAndFocusPowder.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.9.0/Diffraction/Powder/New_features/36136.rst
  docs/source/release/v6.9.0/Framework/Algorithms/New_features/36136.rst
Labels: Diffraction, Powder

#36185 Updates to Indirect Inelastic manual testing doc
  dev-docs/source/Testing/IndirectInelastic/IndirectInelasticAcceptanceTests.rst
Labels: Indirect Inelastic, Documentation, Manual Tests

#36159 Initial spectroscopy and muon release notes for v6.8
  docs/source/release/v6.8.0/Direct_Geometry/CrystalField/Bugfixes/Used/35840.rst
  docs/source/release/v6.8.0/Direct_Geometry/DNS_Reduction/New_features/Used/35389.rst
  docs/source/release/v6.8.0/Indirect/Algorithms/Bugfixes/Used/33761.rst
  docs/source/release/v6.8.0/Indirect/Algorithms/Bugfixes/Used/35821.rst
  docs/source/release/v6.8.0/Indirect/Algorithms/Bugfixes/Used/35908.rst
  docs/source/release/v6.8.0/Indirect/Algorithms/Bugfixes/Used/36015.rst
  docs/source/release/v6.8.0/Indirect/Algorithms/New_features/Used/35917.rst
  docs/source/release/v6.8.0/Indirect/Bugfixes/Used/35920.rst
  docs/source/release/v6.8.0/Indirect/Bugfixes/Used/36076.rst
  docs/source/release/v6.8.0/Indirect/New_features/Used/35716.rst
  docs/source/release/v6.8.0/Indirect/New_features/Used/35966.rst
  docs/source/release/v6.8.0/Muon/Muon_Analysis/Bugfixes/Used/35505.rst
  docs/source/release/v6.8.0/direct_geometry.rst
  docs/source/release/v6.8.0/indirect_geometry.rst
  docs/source/release/v6.8.0/mslice_direct_geometry.rst
  docs/source/release/v6.8.0/muon.rst
Labels: Documentation

#36176 Fix bug in error propagation in FindSXPeaksConvolve
  Framework/PythonInterface/plugins/algorithms/FindSXPeaksConvolve.py
  Framework/PythonInterface/test/python/plugins/algorithms/FindSXPeaksConvolveTest.py
  docs/source/algorithms/FindSXPeaksConvolve-v1.rst
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction
