Repository mantidproject/mantid, pull requests merged in 2024-01, with the labels that each got.

#36600 Pin doxygen to avoid new warning
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: High Priority, ISIS Team: Core, Added during Sprint, Dependencies, DevOps

#36567 Better Colorbar range when opening Slice Viewer from the 'IndirectPlotOptions' widget.
  qt/widgets/mplcpp/src/Plot.cpp
Labels: Bug, Indirect Inelastic, ISIS Team: Spectroscopy

#36537 Elwin tab presenter is no longer a QObject and View is passed to constructor.
  qt/scientific_interfaces/Indirect/ISISCalibration.cpp
  qt/scientific_interfaces/Indirect/ISISDiagnostics.cpp
  qt/scientific_interfaces/Indirect/IndirectTab.cpp
  qt/scientific_interfaces/Indirect/IndirectTab.h
  qt/scientific_interfaces/Inelastic/CMakeLists.txt
  qt/scientific_interfaces/Inelastic/Manipulation/IElwinView.h
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulation.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationElwinTab.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationElwinTab.h
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationElwinTabModel.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationElwinTabModel.h
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationElwinTabView.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationElwinTabView.h
  qt/scientific_interfaces/Inelastic/test/Manipulation/InelasticDataManipulationElwinTabModelTest.h
Labels: Indirect Inelastic, Maintenance, ISIS Team: Spectroscopy

#36601 MC Corrections workspace contains sample shape in name
  docs/source/release/v6.9.0/Inelastic/Bugfixes/36597.rst
  qt/scientific_interfaces/Inelastic/Corrections/AbsorptionCorrections.cpp
Labels: ISIS Team: Spectroscopy, Inelastic

#36604 Realigned UI elements in the Elwin Tab of the Data Manipulation Interface.
  docs/source/release/v6.9.0/Inelastic/Bugfixes/36072.rst
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationElwinTab.ui
Labels: Indirect Inelastic, GUI, ISIS Team: Spectroscopy, Found in Beta

#36598 Use full fit function names for Inelastic Data Analysis ConvFit tab
  dev-docs/source/IndirectDataAnalysisAddingFitType.rst
  docs/source/release/v6.9.0/Inelastic/Bugfixes/36576.rst
  qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvTypes.cpp
Labels: ISIS Team: Spectroscopy, Inelastic

#36602 Reinstate excludeInPullRequests for system tests
  buildconfig/Jenkins/Conda/build
  buildconfig/Jenkins/Conda/conda-buildscript
  buildconfig/Jenkins/Conda/run-tests
  buildconfig/Jenkins/buildscript
  dev-docs/source/SystemTests.rst
Labels: ISIS Team: Core

#36607 Update EISFDiffCylinder to use `scipy.special` Bessel functions
  Framework/PythonInterface/plugins/functions/EISFDiffCylinder.py
  Framework/PythonInterface/test/python/plugins/functions/EISFDiffCylinderTest.py
  docs/source/fitting/fitfunctions/EISFDiffCylinder.rst
Labels: Indirect Inelastic, ISIS Team: Spectroscopy

#36513 Iqt presenter is no longer a QObject and view is passed to constructor.
  qt/scientific_interfaces/Inelastic/CMakeLists.txt
  qt/scientific_interfaces/Inelastic/Manipulation/IIqtView.h
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulation.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulation.h
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationIqtTab.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationIqtTab.h
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationIqtTabView.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationIqtTabView.h
Labels: Indirect Inelastic, Maintenance, ISIS Team: Spectroscopy

#36613 Improving the performance of CrystalStructure creation.
  Framework/Geometry/inc/MantidGeometry/Crystal/CompositeBraggScatterer.h
  Framework/Geometry/src/Crystal/CompositeBraggScatterer.cpp
  Framework/Geometry/src/Crystal/CrystalStructure.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.9.0/Diffraction/Single_Crystal/Bugfixes/36613.rst
Labels: Bug, Single Crystal

#36605 Fail Windows packaging if no package was generated.
  installers/conda/win/create_package.sh
Labels: Maintenance, ISIS Team: Core, Windows Only

#36615 Allow Negative Values for dQ/Q in the Refl GUI
  docs/source/release/v6.9.0/Reflectometry/Bugfixes/35876.rst
  qt/scientific_interfaces/ISISReflectometry/Reduction/ParseReflectometryStrings.cpp
  qt/scientific_interfaces/ISISReflectometry/test/Reduction/ParseReflectometryStringsTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Reduction/ValidateLookupRowTest.h
Labels: Bug, Reflectometry, ISIS Team: LSS

#36583 Move Values Saved to `sasprocessnote` to `sasprocess` in SaveNXCanSAS
  Framework/DataHandling/src/SaveNXcanSAS.cpp
  Framework/DataHandling/test/SaveNXcanSASTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.9.0/SANS/Bugfixes/36552.rst
Labels: SANS, ISIS Team: LSS, Reported By User

#36481 New shoebox integration algorithm for single-crystal Bragg peaks
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/FindSXPeaksConvolve.py
  Framework/PythonInterface/plugins/algorithms/IntegratePeaksShoeboxTOF.py
  Framework/PythonInterface/plugins/algorithms/IntegratePeaksSkew.py
  Framework/PythonInterface/test/python/plugins/algorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/IntegratePeaksShoeboxTOFTest.py
  Testing/SystemTests/tests/framework/SXDAnalysis.py
  docs/source/algorithms/FindSXPeaksConvolve-v1.rst
  docs/source/algorithms/IntegratePeaksShoeboxTOF-v1.rst
  docs/source/images/IntegratePeaksShoeboxTOF_OutputFile.png
  docs/source/release/v6.9.0/Diffraction/Single_Crystal/New_features/36481.rst
  scripts/Diffraction/single_crystal/base_sx.py
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction

#36628 Add Inelastic directory before Indirect directory
  qt/scientific_interfaces/CMakeLists.txt
Labels: Bug, Indirect Inelastic, ISIS Team: Spectroscopy, Reported By User, Dependencies

#36616 cppcheck variableScope warnings
  Framework/API/inc/MantidAPI/WorkspaceProperty.tcc
  Framework/API/src/FileProperty.cpp
  Framework/API/src/IFunction.cpp
  Framework/API/src/NotebookBuilder.cpp
  Framework/API/src/ScriptBuilder.cpp
  Framework/Algorithms/src/AddAbsorptionWeightedPathLengths.cpp
  Framework/Algorithms/src/CalculateDynamicRange.cpp
  Framework/Algorithms/src/FilterEvents.cpp
  Framework/Algorithms/src/RenameWorkspace.cpp
  Framework/Algorithms/src/UnwrapSNS.cpp
  Framework/Crystal/src/IntegratePeakTimeSlices.cpp
  Framework/Crystal/src/OptimizeLatticeForCellType.cpp
  Framework/Crystal/src/SaveHKL.cpp
  Framework/Crystal/src/TransformHKL.cpp
  Framework/CurveFitting/src/Algorithms/PlotPeakByLogValue.cpp
  Framework/CurveFitting/src/Algorithms/RefinePowderInstrumentParameters.cpp
  Framework/CurveFitting/src/Algorithms/RefinePowderInstrumentParameters3.cpp
  Framework/CurveFitting/src/Functions/ChudleyElliotSQE.cpp
  Framework/CurveFitting/src/Functions/CriticalPeakRelaxationRate.cpp
  Framework/CurveFitting/src/Functions/FickDiffusionSQE.cpp
  Framework/CurveFitting/src/Functions/HallRossSQE.cpp
  Framework/CurveFitting/src/Functions/TeixeiraWaterSQE.cpp
  Framework/DataHandling/src/LoadAscii2.cpp
  Framework/DataHandling/src/LoadDetectorsGroupingFile.cpp
  Framework/DataHandling/src/LoadEventNexus.cpp
  Framework/DataHandling/src/LoadFullprofResolution.cpp
  Framework/DataHandling/src/LoadGSASInstrumentFile.cpp
  Framework/DataHandling/src/LoadHelper.cpp
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  Framework/DataHandling/src/LoadSESANS.cpp
  Framework/DataHandling/src/LoadSampleEnvironment.cpp
  Framework/DataHandling/src/LoadSassena.cpp
  Framework/DataHandling/src/LoadTBL.cpp
  Framework/DataHandling/src/SaveNXcanSAS.cpp
  Framework/DataObjects/src/TimeSplitter.cpp
  Framework/Geometry/src/Crystal/IndexingUtils.cpp
  Framework/Geometry/src/Instrument.cpp
  Framework/Geometry/src/Instrument/Goniometer.cpp
  Framework/Kernel/src/PropertyNexus.cpp
  Framework/MDAlgorithms/src/GetSpiceDataRawCountsFromMD.cpp
  Framework/Muon/src/AsymmetryCalc.cpp
  Framework/Muon/src/MuonAlgorithmHelper.cpp
  Framework/PythonInterface/mantid/api/inc/MantidPythonInterface/api/PythonAlgorithm/DataProcessorAdapter.h
  Framework/PythonInterface/mantid/api/src/Exports/BinaryOperations.cpp
  Framework/SINQ/src/PoldiFitPeaks2D.cpp
  Framework/SINQ/src/PoldiUtilities/PoldiSpectrumPawleyFunction.cpp
  Framework/TestHelpers/src/MuonWorkspaceCreationHelper.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  qt/widgets/common/src/AlgorithmHistoryWindow.cpp
  qt/widgets/common/src/AlgorithmPropertiesWidget.cpp
  qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidget.cpp
Labels: Maintenance, ISIS Team: Core

#36620 Speed improvements for LoadAscii
  Framework/DataHandling/inc/MantidDataHandling/LoadAscii2.h
  Framework/DataHandling/src/LoadAscii2.cpp
  docs/source/release/v6.9.0/Framework/Algorithms/Bugfixes/36541.rst
Labels: Bug, ISIS Team: Core, Reported By User

#36633 Make `FunctionModel::checkIndex` safer by removing the unguarded throw
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  qt/python/mantidqt/mantidqt/_common.sip
  qt/widgets/common/inc/MantidQtWidgets/Common/FunctionModel.h
  qt/widgets/common/src/FunctionModel.cpp
Labels: Bug, Muon, ISIS Team: Spectroscopy, Reported By User

#36629 LoadNexusMonitors Set tof range for empty monitors to be 0 to 1
  Framework/DataHandling/src/LoadNexusMonitors2.cpp
  Framework/DataHandling/test/LoadEventNexusTest.h
  Testing/Data/UnitTest/CG3_22446_empty.nxs.h5.md5
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.9.0/Framework/Data_Handling/Bugfixes/36629.rst
Labels: Bug, SANS

#36622 Fix Workbench Crashing if Invalid Options are Given in the Options Column of the Refl GUI
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.9.0/Reflectometry/Bugfixes/34925.rst
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchJobManager.cpp
  qt/scientific_interfaces/ISISReflectometry/test/Batch/BatchJobManagerProcessingTest.h
Labels: Reflectometry, ISIS Team: LSS

#36564 IndirectFitDataPresenter is no longer a QObject
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  qt/scientific_interfaces/Inelastic/Analysis/ConvFitAddWorkspaceDialog.cpp
  qt/scientific_interfaces/Inelastic/Analysis/ConvFitDataPresenter.cpp
  qt/scientific_interfaces/Inelastic/Analysis/ConvFitDataPresenter.h
  qt/scientific_interfaces/Inelastic/Analysis/ConvFitDataView.cpp
  qt/scientific_interfaces/Inelastic/Analysis/ConvFitDataView.h
  qt/scientific_interfaces/Inelastic/Analysis/FqFitAddWorkspaceDialog.cpp
  qt/scientific_interfaces/Inelastic/Analysis/FqFitAddWorkspaceDialog.ui
  qt/scientific_interfaces/Inelastic/Analysis/FqFitDataPresenter.cpp
  qt/scientific_interfaces/Inelastic/Analysis/FqFitDataPresenter.h
  qt/scientific_interfaces/Inelastic/Analysis/FqFitDataView.cpp
  qt/scientific_interfaces/Inelastic/Analysis/FqFitDataView.h
  qt/scientific_interfaces/Inelastic/Analysis/IIndirectFitDataView.h
  qt/scientific_interfaces/Inelastic/Analysis/IndirectDataAnalysisTab.cpp
  qt/scientific_interfaces/Inelastic/Analysis/IndirectDataAnalysisTab.h
  qt/scientific_interfaces/Inelastic/Analysis/IndirectDockWidgetArea.cpp
  qt/scientific_interfaces/Inelastic/Analysis/IndirectDockWidgetArea.h
  qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataPresenter.cpp
  qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataPresenter.h
  qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp
  qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.h
  qt/scientific_interfaces/Inelastic/CMakeLists.txt
  qt/scientific_interfaces/Inelastic/Common/IndirectAddWorkspaceDialog.cpp
  qt/scientific_interfaces/Inelastic/test/Analysis/ConvFitDataPresenterTest.h
  qt/scientific_interfaces/Inelastic/test/Analysis/FqFitDataPresenterTest.h
  qt/scientific_interfaces/Inelastic/test/Analysis/IndirectFitDataPresenterTest.h
  qt/scientific_interfaces/Inelastic/test/Analysis/MockObjects.h
Labels: Maintenance, ISIS Team: Spectroscopy, Inelastic

#36650 Pin openblas to fix systest failure after dep update
  conda/recipes/conda_build_config.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
Labels: High Priority, ISIS Team: LSS, DevOps

#36585 Add a checkbox to decide if a custom output filename should be used in the Sum Runs tab
  docs/source/release/v6.9.0/SANS/New_features/35869.rst
  scripts/Interface/ui/sans_isis/add_runs_page.py
  scripts/Interface/ui/sans_isis/add_runs_page.ui
  scripts/SANS/sans/gui_logic/presenter/add_runs_presenter.py
  scripts/test/SANS/gui_logic/add_runs_presenter_test.py
Labels: SANS, ISIS Team: LSS

#36627 Fix Background Subtraction Workspace Deletion When Saving to File
  docs/source/release/v6.9.0/SANS/Bugfixes/36621.rst
  scripts/SANS/sans/algorithm_detail/batch_execution.py
  scripts/test/SANS/algorithm_detail/batch_execution_test.py
Labels: Bug, SANS, ISIS Team: LSS

#36643 updated CG3 definition
  instrument/BIOSANS_Definition.xml
  instrument/CG3_Definition.xml
Labels: ORNL Team

#36635 36591 added nexus file support in PEARLTransfit algorithm
  Framework/PythonInterface/plugins/algorithms/PEARLTransfit.py
  Framework/PythonInterface/test/python/plugins/algorithms/PEARLTransfitTest.py
  Testing/Data/UnitTest/PEARL00112777.nxs.md5
  docs/source/release/v6.9.0/Diffraction/Powder/New_features/36591.rst
Labels: Diffraction, Powder, ISIS Team: Diffraction

#36634 Always Return to Default Save Options When Reduction Mode is Switched
  Framework/DataHandling/inc/MantidDataHandling/SaveCanSAS1D.h
  Framework/DataHandling/inc/MantidDataHandling/SaveCanSAS1D2.h
  Framework/DataHandling/inc/MantidDataHandling/SaveNXcanSAS.h
  Framework/DataHandling/inc/MantidDataHandling/SaveRKH.h
  Framework/DataHandling/src/SaveCanSAS1D.cpp
  Framework/DataHandling/src/SaveNXcanSAS.cpp
  dev-docs/source/Testing/SANSGUI/ISISSANSGUITests.rst
  docs/source/algorithms/SaveCanSAS1D-v2.rst
  docs/source/algorithms/SaveNXcanSAS-v1.rst
  docs/source/algorithms/SaveRKH-v1.rst
  docs/source/release/v6.9.0/SANS/Bugfixes/36115.rst
  scripts/SANS/sans/gui_logic/models/POD/save_options.py
  scripts/SANS/sans/gui_logic/models/run_tab_model.py
  scripts/test/SANS/gui_logic/models/test_run_tab_model.py
Labels: Bug, SANS, Documentation, ISIS Team: LSS

#36647 Fix for crash when closing an executing tab
  dev-docs/source/Testing/Core/Core.rst
  docs/source/release/v6.9.0/Workbench/Bugfixes/36647.rst
  qt/python/mantidqt/mantidqt/widgets/codeeditor/interpreter.py
Labels: Bug, ISIS Team: Core, Reported By User

#36656 Add ORSO Ascii save format to the ISIS Reflectometry GUI manual tests
  dev-docs/source/Testing/ReflectometryGUI/ReflectometryGUITests.rst
Labels: Reflectometry, Documentation, ISIS Team: LSS

#36665 Pin updated dependencies to resolve mantidqt env
  conda/recipes/mantid/meta.yaml
Labels: High Priority, ISIS Team: Core, Linux Only, Added during Sprint, Dependencies, DevOps

#36657 Fix for crash on deleting workspaces while project save is running
  docs/source/release/v6.9.0/Workbench/Bugfixes/32361.rst
  qt/python/mantidqt/mantidqt/project/workspacesaver.py
Labels: Bug, ISIS Team: Core

#36653 Disable Option to Save to CanSAS1D if 2D reduction Mode is Selected in ISIS SANS GUI
  dev-docs/source/Testing/SANSGUI/ISISSANSGUITests.rst
  docs/source/release/v6.9.0/SANS/Bugfixes/36398.rst
  scripts/Interface/ui/sans_isis/sans_data_processor_gui.py
  scripts/SANS/sans/gui_logic/presenter/run_tab_presenter.py
  scripts/test/SANS/gui_logic/test_run_tab_presenter.py
Labels: SANS, ISIS Team: LSS

#36658 Added testing instructions for a scaled workspace
  dev-docs/source/Testing/Direct/MSliceTestGuide.rst
Labels: Documentation, ISIS Team: Excitations/Vesuvio

#36659 Updated SHA for MSlice and added release notes
  docs/source/release/v6.9.0/Direct_Geometry/MSlice/Bugfixes/36659.rst
  docs/source/release/v6.9.0/Direct_Geometry/MSlice/New_features/36659.rst
  scripts/ExternalInterfaces/CMakeLists.txt
Labels: ISIS Team: Excitations/Vesuvio

#36644 Fix error on cancelling save
  qt/python/mantidqt/mantidqt/widgets/codeeditor/multifileinterpreter.py
  qt/python/mantidqt/mantidqt/widgets/codeeditor/test/test_multifileinterpreter.py
Labels: Bug, ISIS Team: Core

#36581 Add option for number of cylinder slices to SolidAngle
  Framework/Algorithms/src/SolidAngle.cpp
  Framework/Geometry/CMakeLists.txt
  Framework/Geometry/inc/MantidGeometry/IObjComponent.h
  Framework/Geometry/inc/MantidGeometry/Instrument/ComponentInfo.h
  Framework/Geometry/inc/MantidGeometry/Instrument/Container.h
  Framework/Geometry/inc/MantidGeometry/Instrument/DetectorGroup.h
  Framework/Geometry/inc/MantidGeometry/Instrument/GridDetector.h
  Framework/Geometry/inc/MantidGeometry/Instrument/ObjComponent.h
  Framework/Geometry/inc/MantidGeometry/Instrument/SolidAngleParams.h
  Framework/Geometry/inc/MantidGeometry/Instrument/StructuredDetector.h
  Framework/Geometry/inc/MantidGeometry/Objects/CSGObject.h
  Framework/Geometry/inc/MantidGeometry/Objects/IObject.h
  Framework/Geometry/inc/MantidGeometry/Objects/MeshObject.h
  Framework/Geometry/inc/MantidGeometry/Objects/MeshObject2D.h
  Framework/Geometry/src/Instrument/ComponentInfo.cpp
  Framework/Geometry/src/Instrument/DetectorGroup.cpp
  Framework/Geometry/src/Instrument/GridDetector.cpp
  Framework/Geometry/src/Instrument/ObjComponent.cpp
  Framework/Geometry/src/Instrument/StructuredDetector.cpp
  Framework/Geometry/src/Objects/CSGObject.cpp
  Framework/Geometry/src/Objects/MeshObject.cpp
  Framework/Geometry/src/Objects/MeshObject2D.cpp
  Framework/Geometry/test/CSGObjectTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.9.0/Framework/Algorithms/New_features/36581.rst
Labels: Bug, ISIS Team: Core

#36664 DiffractionFocussing code cleanup
  Framework/Algorithms/inc/MantidAlgorithms/DiffractionFocussing2.h
  Framework/Algorithms/src/DiffractionFocussing2.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Diffraction, Powder, Maintenance

#36569 Add extra load file tooltip on Linux aimed at IDAaaS users
  Framework/API/CMakeLists.txt
  Framework/API/inc/MantidAPI/FileFinder.h
  Framework/API/inc/MantidAPI/IArchiveSearch.h
  Framework/API/inc/MantidAPI/Result.h
  Framework/API/src/DataProcessorAlgorithm.cpp
  Framework/API/src/FileFinder.cpp
  Framework/API/src/FileProperty.cpp
  Framework/API/src/MultipleFileProperty.cpp
  Framework/API/test/FileFinderTest.h
  Framework/API/test/ResultTest.h
  Framework/DataHandling/inc/MantidDataHandling/ISISDataArchive.h
  Framework/DataHandling/inc/MantidDataHandling/ORNLDataArchive.h
  Framework/DataHandling/src/ISISDataArchive.cpp
  Framework/DataHandling/src/ORNLDataArchive.cpp
  Framework/DataHandling/test/ISISDataArchiveTest.h
  Framework/DataHandling/test/ORNLDataArchiveTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.9.0/Workbench/New_features/36566.rst
Labels: ISIS Team: Core, IDAaaS Only

#36667 Fix ISIS SANS GUI Mask tab unhandled exception
  docs/source/release/v6.9.0/SANS/Bugfixes/36666.rst
  scripts/SANS/sans/gui_logic/presenter/masking_table_presenter.py
  scripts/test/SANS/gui_logic/masking_table_presenter_test.py
Labels: SANS, ISIS Team: LSS

#36661 Estimate the FWHM parameter in ConvFit for Lorentzians
  docs/source/release/v6.9.0/Inelastic/New_features/36346.rst
  qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvFunctionModel.cpp
Labels: Bug, ISIS Team: Spectroscopy, Inelastic

#36632 Remove length check for github api token
  Framework/Kernel/src/GitHubApiHelper.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.9.0/Framework/Algorithms/New_features/36549.rst
Labels: ISIS Team: Core

#36678 Pin scipy to fix unit test failures
  conda/recipes/conda_build_config.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: High Priority, DevOps

#36683 Pin scipy to fix test failures
  conda/recipes/conda_build_config.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: High Priority, DevOps

#36680 Fix Direct Calls to `pi`, `tanh`, and `sinh` in `scipy`.
  Framework/PythonInterface/plugins/algorithms/ComputeCalibrationCoefVan.py
Labels: Bug, DevOps

#36681 Unpin conda-build
  buildconfig/Jenkins/Conda/package-conda
Labels: Maintenance, ISIS Team: Core, Dependencies

#36675 Configure special branches to auto-merge on push
  .github/workflows/automerge.yml
Labels: DevOps

#36750 Create gh action to close issues that are fixed by PRs merged into release-next
  .github/workflows/close_issues.yml
  tools/Issues/close_merged_issues.py
  tools/Issues/requirements.txt
Labels: ISIS Team: Core, DevOps

#36751 Fix string format for multiple files input in Elwin tab.
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationElwinTab.cpp
Labels: Bug, ISIS Team: Spectroscopy, Manual Tests

#36759 Debugging RectangleSelection after matplotlib API upgrade
  qt/python/mantidqtinterfaces/mantidqtinterfaces/simplescanviewer/rectangle_selection.py
Labels: Bug, ILL Team, Found in Beta

#36624 IAddWorkspaceDialog moved to a common location and no longer a qobject
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/interfaces/general/Fit Script Generator.rst
  qt/scientific_interfaces/Inelastic/Analysis/ConvFitAddWorkspaceDialog.cpp
  qt/scientific_interfaces/Inelastic/Analysis/ConvFitAddWorkspaceDialog.h
  qt/scientific_interfaces/Inelastic/Analysis/ConvFitAddWorkspaceDialog.ui
  qt/scientific_interfaces/Inelastic/Analysis/ConvFitDataView.cpp
  qt/scientific_interfaces/Inelastic/Analysis/ConvFitDataView.h
  qt/scientific_interfaces/Inelastic/Analysis/FqFitAddWorkspaceDialog.cpp
  qt/scientific_interfaces/Inelastic/Analysis/FqFitAddWorkspaceDialog.h
  qt/scientific_interfaces/Inelastic/Analysis/FqFitAddWorkspaceDialog.ui
  qt/scientific_interfaces/Inelastic/Analysis/FqFitDataPresenter.cpp
  qt/scientific_interfaces/Inelastic/Analysis/FqFitDataPresenter.h
  qt/scientific_interfaces/Inelastic/Analysis/FqFitDataView.cpp
  qt/scientific_interfaces/Inelastic/Analysis/FqFitDataView.h
  qt/scientific_interfaces/Inelastic/Analysis/IIndirectFitDataModel.h
  qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataModel.cpp
  qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataModel.h
  qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataPresenter.cpp
  qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataPresenter.h
  qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp
  qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.h
  qt/scientific_interfaces/Inelastic/CMakeLists.txt
  qt/scientific_interfaces/Inelastic/Common/IndirectAddWorkspaceDialog.cpp
  qt/scientific_interfaces/Inelastic/Common/IndirectAddWorkspaceDialog.h
  qt/scientific_interfaces/Inelastic/Common/IndirectAddWorkspaceDialog.ui
  qt/scientific_interfaces/Inelastic/Manipulation/IElwinView.h
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationElwinTab.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationElwinTab.h
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationElwinTabView.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationElwinTabView.h
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationIqtTabView.cpp
  qt/scientific_interfaces/Inelastic/test/Analysis/ConvFitDataPresenterTest.h
  qt/scientific_interfaces/Inelastic/test/Analysis/FqFitDataPresenterTest.h
  qt/scientific_interfaces/Inelastic/test/Analysis/IndirectFitDataModelTest.h
  qt/scientific_interfaces/Inelastic/test/Analysis/IndirectFitDataPresenterTest.h
  qt/scientific_interfaces/Inelastic/test/Analysis/IndirectFittingModelTest.h
  qt/scientific_interfaces/Inelastic/test/Analysis/MockObjects.h
  qt/widgets/common/CMakeLists.txt
  qt/widgets/common/inc/MantidQtWidgets/Common/AddWorkspaceDialog.h
  qt/widgets/common/inc/MantidQtWidgets/Common/AddWorkspaceDialog.ui
  qt/widgets/common/inc/MantidQtWidgets/Common/FitScriptGeneratorMockObjects.h
  qt/widgets/common/inc/MantidQtWidgets/Common/FitScriptGeneratorPresenter.h
  qt/widgets/common/inc/MantidQtWidgets/Common/FitScriptGeneratorView.h
  qt/widgets/common/inc/MantidQtWidgets/Common/IAddWorkspaceDialog.h
  qt/widgets/common/inc/MantidQtWidgets/Common/IFitScriptGeneratorPresenter.h
  qt/widgets/common/inc/MantidQtWidgets/Common/IFitScriptGeneratorView.h
  qt/widgets/common/src/AddWorkspaceDialog.cpp
  qt/widgets/common/src/FitScriptGeneratorPresenter.cpp
  qt/widgets/common/src/FitScriptGeneratorView.cpp
  qt/widgets/common/test/AddWorkspaceDialogTest.h
  qt/widgets/common/test/FitScriptGeneratorPresenterTest.h
  qt/widgets/common/test/FitScriptGeneratorViewTest.h
Labels: Maintenance, ISIS Team: Spectroscopy, Inelastic

#36752 Fix for fit property browser fixes being unfixable
  docs/source/release/v6.9.0/Workbench/Bugfixes/36722.rst
  qt/widgets/common/inc/MantidQtWidgets/Common/FitPropertyBrowser.h
  qt/widgets/common/src/FitPropertyBrowser.cpp
Labels: Bug, ISIS Team: Core, Found in Beta

#36765 Fix hang from quickly overplotting with plotSpectrum
  Framework/PythonInterface/mantid/plots/plotfunctions.py
  docs/source/release/v6.9.0/Workbench/Bugfixes/36727.rst
Labels: Bug, ISIS Team: Core, Found in Beta

#36767 36747 avoid crash on GSAS-II
  docs/source/release/v6.9.0/Diffraction/Engineering/Bugfixes/36747.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/model.py
Labels: Bug, Diffraction, ISIS Team: Diffraction

#36780 Update .pre-commit-config.yaml in release-next to match main
  .pre-commit-config.yaml
Labels: ISIS Team: Core

#36781 Update MSlice SHA for beta testing release 6.9
  docs/source/release/v6.9.0/Direct_Geometry/MSlice/Bugfixes/36781.rst
  scripts/ExternalInterfaces/CMakeLists.txt
Labels: High Priority

#36773 Fix error when opening contour plot for multiple workspaces
  qt/applications/workbench/workbench/plotting/figuremanager.py
  qt/python/mantidqt/mantidqt/plotting/functions.py
Labels: Bug, Found in Beta

#36789 Update close_issues action to fix max int bug
  .github/workflows/close_issues.yml
Labels: High Priority, Bug, DevOps

#36768 Fix Rebin dialog crash with group workspace
  Framework/Algorithms/inc/MantidAlgorithms/Rebin.h
  Framework/Algorithms/src/Rebin.cpp
  Framework/Algorithms/test/RebinTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.9.0/Workbench/Bugfixes/36689.rst
Labels: Bug

#36786 Expose PeakShapes and IPeak.setPeakShape to Python
  Framework/PythonInterface/mantid/api/src/Exports/IPeak.cpp
  Framework/PythonInterface/mantid/dataobjects/CMakeLists.txt
  Framework/PythonInterface/mantid/dataobjects/src/Exports/NoShape.cpp
  Framework/PythonInterface/mantid/dataobjects/src/Exports/PeakShapeEllipsoid.cpp
  Framework/PythonInterface/mantid/dataobjects/src/Exports/PeakShapeSpherical.cpp
  Framework/PythonInterface/test/python/mantid/dataobjects/CMakeLists.txt
  Framework/PythonInterface/test/python/mantid/dataobjects/PeakShapes.py
  Framework/PythonInterface/test/python/mantid/geometry/IPeakTest.py
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/concepts/PeaksWorkspace.rst
  docs/source/release/v6.10.0/Framework/Python/New_features/36786.rst
Labels: Single Crystal

#36791 Call atexit.register with ADS.clear(True)
  Framework/PythonInterface/mantid/api/src/Exports/AnalysisDataService.cpp
Labels: High Priority, Bug, Found in Beta
