Repository mantidproject/mantid, pull requests merged in 2024-07, with the labels that each got.

#37622 Move verify and clear method to tear down method in isis reflectometry unit tests
  qt/scientific_interfaces/ISISReflectometry/test/MainWindow/MainWindowPresenterTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Runs/CatalogRunNotifierTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Runs/QtCatalogSearcherTest.h
Labels: Reflectometry, ISIS Team: LSS

#37606 Update link to ISIS Reflectometry Interface
  dev-docs/source/ISISReflectometryInterface.rst
Labels: Documentation

#37610 Replace use of interp2d and then unpin scipy
  Framework/PythonInterface/plugins/algorithms/NMoldyn4Interpolation.py
  Framework/PythonInterface/test/python/plugins/algorithms/NMoldyn4InterpolationTest.py
  conda/recipes/conda_build_config.yaml
  docs/source/release/v6.11.0/Framework/Algorithms/New_features/37605.rst
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: Maintenance, ISIS Team: Core

#37632 Update Broken Link to `muparser` Docs
  docs/source/algorithms/MaskBinsIf-v1.rst
Labels: Documentation, ISIS Team: LSS

#37596 Add option to ignore masked pixels in integration algorithms and improve skew background determination
  Framework/PythonInterface/plugins/algorithms/IntegratePeaks1DProfile.py
  Framework/PythonInterface/plugins/algorithms/IntegratePeaksShoeboxTOF.py
  Framework/PythonInterface/plugins/algorithms/IntegratePeaksSkew.py
  Framework/PythonInterface/test/python/plugins/algorithms/IntegratePeaks1DProfileTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/IntegratePeaksShoeboxTOFTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/IntegratePeaksSkewTest.py
  docs/source/release/v6.11.0/Diffraction/Single_Crystal/New_features/37596.rst
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction

#37631 Update cppcheck to 2.14.2
  buildconfig/CMake/CppCheckSetup.cmake
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
  qt/icons/src/CharIconPainter.cpp
Labels: ISIS Team: Core

#37638 Fix nightly version regex in delete nightly workflow
  .github/workflows/delete_old_nightly_releases.yml
Labels: Bug, Extra Attention, ISIS Team: Core

#37530 Run open interface system tests with both window behaviours
  Testing/SystemTests/tests/qt/CppInterfacesStartupTest.py
  Testing/SystemTests/tests/qt/PythonInterfacesStartupTest.py
Labels: Maintenance, ISIS Team: Core

#37633 Fix for line order chagning when editing plot settings
  docs/source/release/v6.11.0/Workbench/Bugfixes/37465.rst
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/curvestabwidget/presenter.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/curvestabwidget/test/test_curvestabwidgetpresenter.py
Labels: Bug, ISIS Team: Core

#37619 Stitch1DMany Algorithm cant be run from the GUI
  Framework/Algorithms/src/Stitch1DMany.cpp
  docs/source/release/v6.11.0/Reflectometry/Bugfixes/37619.rst
Labels: Reflectometry, ISIS Team: LSS

#37612 Use RunWidget in Indirect Tools interface
  qt/scientific_interfaces/Indirect/Tools/ToolsTab.h
  qt/scientific_interfaces/Indirect/Tools/TransmissionCalc.cpp
  qt/scientific_interfaces/Indirect/Tools/TransmissionCalc.h
  qt/scientific_interfaces/Indirect/Tools/TransmissionCalc.ui
Labels: Indirect/Inelastic, Maintenance, ISIS Team: Spectroscopy

#37309 New algorithm to find multiple UB matrices in case of multiple domains or spurious peaks
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/FindMultipleUMatrices.py
  Framework/PythonInterface/test/python/plugins/algorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/FindMultipleUMatricesTest.py
  Testing/SystemTests/tests/framework/CodeConventions.py
  docs/source/algorithms/FindMultipleUMatrices-v1.rst
  docs/source/release/v6.11.0/Diffraction/Single_Crystal/New_features/35711.rst
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction

#37641 Copy changes from main into ornl-next
  .pre-commit-config.yaml
  Framework/PythonInterface/mantid/plots/legend.py
  Framework/PythonInterface/plugins/algorithms/LoadCIF.py
  Framework/PythonInterface/plugins/algorithms/NMoldyn4Interpolation.py
  Framework/PythonInterface/test/python/plugins/algorithms/NMoldyn4InterpolationTest.py
  buildconfig/Jenkins/Conda/conda-buildscript
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid/meta.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
  qt/applications/workbench/workbench/plotting/figureinteraction.py
  qt/applications/workbench/workbench/plotting/test/test_figureinteraction.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/DGSPlanner/DimensionSelectorWidget.py
  scripts/SANS/sans/gui_logic/gui_common.py
  scripts/test/DirectEnergyConversionTest.py
  scripts/test/DirectPropertyManagerTest.py
  scripts/test/RunDescriptorTest.py
Labels: ORNL Team

#37602 Fix recent coverity scan warnings
  Framework/Kernel/src/IPropertyManager.cpp
  qt/scientific_interfaces/Inelastic/Common/DataModel.cpp
  qt/scientific_interfaces/Inelastic/Corrections/ApplyAbsorptionCorrections.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/ConvolutionDataView.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/ConvolutionDataView.h
  qt/scientific_interfaces/Inelastic/QENSFitting/ConvolutionModel.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FitDataView.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FitDataView.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionQDataPresenter.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionQDataView.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionQDataView.h
  qt/scientific_interfaces/Inelastic/QENSFitting/IFitDataView.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/MockObjects.h
Labels: Indirect/Inelastic, Maintenance, ISIS Team: Spectroscopy

#37621 Improve shoebox position determination in `IntegratePeaksShoeboxTOF`
  Framework/PythonInterface/plugins/algorithms/IntegratePeaks1DProfile.py
  Framework/PythonInterface/plugins/algorithms/IntegratePeaksShoeboxTOF.py
  Framework/PythonInterface/test/python/plugins/algorithms/IntegratePeaksShoeboxTOFTest.py
  Testing/SystemTests/tests/framework/SXDAnalysis.py
  docs/source/algorithms/IntegratePeaksShoeboxTOF-v1.rst
  docs/source/release/v6.11.0/Diffraction/Single_Crystal/New_features/37621.rst
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction

#37194 Muon Spin Diffusion fit function
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/functions/SpinDiffusion.py
  Framework/PythonInterface/test/python/plugins/functions/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/functions/SpinDiffusionTest.py
  docs/source/fitting/fitfunctions/SpinDiffusion.rst
  docs/source/release/v6.11.0/Framework/Fit_Functions/New_features/37194.rst
Labels: Muon, ISIS Team: Spectroscopy

#37649 Adding alternative inputs to select old instrument definition files
  Framework/PythonInterface/plugins/algorithms/GenerateGroupingSNSInelastic.py
  Framework/PythonInterface/test/python/plugins/algorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/GenerateGroupingSNSInelasticTest.py
  docs/source/algorithms/GenerateGroupingSNSInelastic-v1.rst
  docs/source/release/v6.11.0/Framework/Algorithms/New_features/37649.rst
Labels: Direct Inelastic, Framework, ORNL Team

#37636 Use RunWidget in Inelastic Data Reduction
  qt/scientific_interfaces/Indirect/Reduction/DataReduction.h
  qt/scientific_interfaces/Indirect/Reduction/DataReductionTab.cpp
  qt/scientific_interfaces/Indirect/Reduction/DataReductionTab.h
  qt/scientific_interfaces/Indirect/Reduction/ILLEnergyTransfer.cpp
  qt/scientific_interfaces/Indirect/Reduction/ILLEnergyTransfer.h
  qt/scientific_interfaces/Indirect/Reduction/ILLEnergyTransfer.ui
  qt/scientific_interfaces/Indirect/Reduction/ISISCalibration.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISCalibration.h
  qt/scientific_interfaces/Indirect/Reduction/ISISCalibration.ui
  qt/scientific_interfaces/Indirect/Reduction/ISISDiagnostics.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISDiagnostics.h
  qt/scientific_interfaces/Indirect/Reduction/ISISDiagnostics.ui
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransfer.ui
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferPresenter.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferPresenter.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferView.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferView.h
  qt/scientific_interfaces/Indirect/Reduction/Transmission.cpp
  qt/scientific_interfaces/Indirect/Reduction/Transmission.h
  qt/scientific_interfaces/Indirect/Reduction/Transmission.ui
  qt/scientific_interfaces/Indirect/Simulation/DensityOfStates.cpp
  qt/scientific_interfaces/Indirect/Simulation/DensityOfStates.h
  qt/scientific_interfaces/Indirect/Simulation/MolDyn.cpp
  qt/scientific_interfaces/Indirect/Simulation/MolDyn.h
  qt/scientific_interfaces/Indirect/Simulation/Sassena.cpp
  qt/scientific_interfaces/Indirect/Simulation/Sassena.h
  qt/scientific_interfaces/Indirect/Tools/Tools.cpp
  qt/scientific_interfaces/Indirect/Tools/Tools.h
  qt/scientific_interfaces/Indirect/Tools/TransmissionCalc.cpp
  qt/scientific_interfaces/Indirect/Tools/TransmissionCalc.h
  qt/scientific_interfaces/Indirect/test/Reduction/ISISEnergyTransferPresenterTest.h
  qt/scientific_interfaces/Indirect/test/Reduction/MockObjects.h
  qt/scientific_interfaces/Inelastic/BayesFitting/Quasi.cpp
  qt/scientific_interfaces/Inelastic/BayesFitting/Quasi.h
  qt/scientific_interfaces/Inelastic/BayesFitting/ResNorm.cpp
  qt/scientific_interfaces/Inelastic/BayesFitting/ResNorm.h
  qt/scientific_interfaces/Inelastic/BayesFitting/Stretch.cpp
  qt/scientific_interfaces/Inelastic/BayesFitting/Stretch.h
  qt/scientific_interfaces/Inelastic/Common/InelasticTab.cpp
  qt/scientific_interfaces/Inelastic/Common/InelasticTab.h
  qt/scientific_interfaces/Inelastic/Common/OutputPlotOptionsPresenter.cpp
  qt/scientific_interfaces/Inelastic/Corrections/AbsorptionCorrections.cpp
  qt/scientific_interfaces/Inelastic/Corrections/ApplyAbsorptionCorrections.cpp
  qt/scientific_interfaces/Inelastic/Corrections/CalculatePaalmanPings.cpp
  qt/scientific_interfaces/Inelastic/Corrections/CalculatePaalmanPings.h
  qt/scientific_interfaces/Inelastic/Corrections/CalculatePaalmanPings.ui
  qt/scientific_interfaces/Inelastic/Corrections/ContainerSubtraction.cpp
  qt/scientific_interfaces/Inelastic/Corrections/Corrections.cpp
  qt/scientific_interfaces/Inelastic/Corrections/CorrectionsTab.cpp
  qt/scientific_interfaces/Inelastic/Corrections/CorrectionsTab.h
  qt/scientific_interfaces/Inelastic/Processor/DataProcessor.cpp
  qt/scientific_interfaces/Inelastic/Processor/DataProcessor.h
  qt/scientific_interfaces/Inelastic/Processor/DataProcessorInterface.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FitTab.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FitTab.h
  qt/scientific_interfaces/Inelastic/QENSFitting/QENSFitting.cpp
Labels: Indirect/Inelastic, Maintenance, ISIS Team: Spectroscopy

#37618 Refactor FunctionQDataPresenter so extra parameter types can be added
  dev-docs/source/Testing/Inelastic/QENSFittingTests.rst
  qt/scientific_interfaces/Inelastic/QENSFitting/CMakeLists.txt
  qt/scientific_interfaces/Inelastic/QENSFitting/FitDataPresenter.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionQDataPresenter.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionQDataPresenter.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionQParameters.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionQParameters.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/CMakeLists.txt
  qt/scientific_interfaces/Inelastic/test/QENSFitting/FunctionQDataPresenterTest.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/FunctionQParametersTest.h
Labels: Indirect/Inelastic, Maintenance, ISIS Team: Spectroscopy

#37599 Add methods to find consistent UBs and optimise goniometer axes and angles in ISIS single-crystal classes
  Framework/PythonInterface/mantid/geometry/src/Exports/Goniometer.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.11.0/Diffraction/Single_Crystal/New_features/37599.rst
  scripts/Diffraction/single_crystal/base_sx.py
  scripts/Diffraction/single_crystal/test/test_base_sx.py
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction

#37655 Fix crash on ALFView when moving cursor and loading
  docs/source/release/v6.11.0/Direct_Geometry/General/Bugfixes/37651.rst
  qt/widgets/instrumentview/src/ProjectionSurface.cpp
  qt/widgets/instrumentview/test/CMakeLists.txt
  qt/widgets/instrumentview/test/InstrumentWidget/ProjectionSurfaceTest.h
Labels: Bug, ISIS Team: Excitations/Vesuvio

#37668 pre-commit autoupdate from #37662 into ornl-next
  .pre-commit-config.yaml
  Framework/PythonInterface/mantid/api/_workspaceops.py
  Framework/PythonInterface/mantid/simpleapi.py
  Framework/PythonInterface/plugins/algorithms/GenerateLogbook.py
  qt/applications/workbench/workbench/plotting/figureinteraction.py
  qt/applications/workbench/workbench/plotting/figuremanager.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/imagestabwidget/__init__.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/HFIR_4Circle_Reduction/reduce4circleControl.py
Labels: ORNL Team

#37666 Fix TOF converter on high res screens
  docs/source/release/v6.11.0/Workbench/Bugfixes/37584.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/TofConverter/converter.ui
Labels: Bug, GUI, ISIS Team: Core

#37665 Fix for crash when opening instrument view with old Muon data
  docs/source/release/v6.11.0/Workbench/InstrumentViewer/Bugfixes/34544.rst
  qt/widgets/instrumentview/src/InstrumentRenderer.cpp
  qt/widgets/instrumentview/test/CMakeLists.txt
  qt/widgets/instrumentview/test/InstrumentRendererTest.h
Labels: Bug, ISIS Team: Core

#37660 Fix 3d plot bug where zoom was toggled by context menu
  Framework/PythonInterface/mantid/plots/mantidaxes.py
  docs/source/release/v6.11.0/Workbench/Bugfixes/37585.rst
Labels: ISIS Team: Core

#37656 Update conda-build recipes to use CentOS 7 cdt packages
  conda/recipes/conda_build_config.yaml
Labels: ISIS Team: Core

#37642 Prevent crash on Bayes Fitting Quasi
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesQuasi.py
  docs/source/release/v6.11.0/Inelastic/Bugfixes/37642.rst
  qt/scientific_interfaces/Inelastic/BayesFitting/Quasi.cpp
  qt/scientific_interfaces/Inelastic/BayesFitting/Quasi.h
  qt/widgets/common/src/DataSelector.cpp
  scripts/Inelastic/IndirectCommon.py
  scripts/test/IndirectCommonTests.py
Labels: Bug, Indirect/Inelastic, ISIS Team: Spectroscopy

#37593 Report underlying processor arch on Arm Macs
  Framework/Kernel/src/ConfigService.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: macOS Only, ISIS Team: Core

#37608 Add instructions for fixing a merge conflict between protected branches
  dev-docs/source/Gatekeeping.rst
  dev-docs/source/GitWorkflow.rst
Labels: Documentation, ISIS Team: Core

#37669 Tie Peak Centres option for Convolution QENS Fitting
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.11.0/Inelastic/New_features/37669.rst
  qt/scientific_interfaces/Inelastic/QENSFitting/FitTabConstants.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionBrowser/ConvFunctionTemplateModel.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionBrowser/ConvFunctionTemplateModel.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionBrowser/FitTypes.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionBrowser/FitTypes.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionBrowser/IqtFunctionTemplateModel.cpp
Labels: Indirect/Inelastic, ISIS Team: Spectroscopy

#37676 37542 add tooltips to editor widget
  docs/source/release/v6.11.0/Workbench/New_features/37542.rst
  qt/python/mantidqt/mantidqt/widgets/codeeditor/tab_widget/codeeditor_tab_view.py
Labels: Induction, ISIS Team: Core

#37653 Use original sample to normalise randomized sample
  Framework/Algorithms/inc/MantidAlgorithms/CalculateIqt.h
  Framework/Algorithms/src/CalculateIqt.cpp
  docs/source/release/v6.11.0/Inelastic/Bugfixes/37653.rst
Labels: Bug, Indirect/Inelastic, ISIS Team: Spectroscopy

#37667 Improve BayesFitting window support for quickbayes
  qt/scientific_interfaces/Inelastic/BayesFitting/BayesFitting.cpp
  qt/scientific_interfaces/Inelastic/BayesFitting/BayesFittingTab.cpp
  qt/scientific_interfaces/Inelastic/BayesFitting/BayesFittingTab.h
  qt/scientific_interfaces/Inelastic/BayesFitting/Quasi.cpp
  qt/scientific_interfaces/Inelastic/BayesFitting/Quasi.h
  qt/scientific_interfaces/Inelastic/BayesFitting/Stretch.cpp
  qt/scientific_interfaces/Inelastic/BayesFitting/Stretch.h
Labels: Indirect/Inelastic, ISIS Team: Spectroscopy

#37675 37659 fixing crash engdiff fit tab when fit is re run for a func having fwhm params
  docs/source/release/v6.11.0/Diffraction/Engineering/Bugfixes/37659.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/plot_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/test/test_plot_model.py
Labels: Bug, Diffraction

#37689 Fixed NumPy deprecation warning for alltrue
  Framework/PythonInterface/plugins/algorithms/RebinRagged.py
  Framework/PythonInterface/test/python/plugins/algorithms/MatchSpectraTest.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/DGSPlanner/InstrumentSetupWidget.py
Labels: Maintenance, ISIS Team: Excitations/Vesuvio

#37690 Fix crash when trying to run algorithms from Corrections interface
  qt/scientific_interfaces/Inelastic/Corrections/AbsorptionCorrections.h
  qt/scientific_interfaces/Inelastic/Corrections/ApplyAbsorptionCorrections.h
  qt/scientific_interfaces/Inelastic/Corrections/ContainerSubtraction.h
Labels: Bug, GUI, ISIS Team: Spectroscopy, Absorption Corrections

#37657 Add ability to load A0 parameters to Function(Q) tab
  docs/source/interfaces/inelastic/Inelastic QENS Fitting.rst
  docs/source/release/v6.11.0/Inelastic/New_features/37657.rst
  qt/scientific_interfaces/Inelastic/QENSFitting/ConvolutionModel.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FitTab.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FittingModel.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionQAddWorkspaceDialog.ui
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionQDataPresenter.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionQParameters.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionQParameters.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/ConvolutionModelTest.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/FunctionQDataPresenterTest.h
  qt/widgets/common/inc/MantidQtWidgets/Common/QtJobRunner.h
  qt/widgets/common/src/QtJobRunner.cpp
Labels: Indirect/Inelastic, ISIS Team: Spectroscopy

#37259 update to boost 1.82
  Framework/DataHandling/inc/MantidDataHandling/LoadStl.h
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid/meta.yaml
  conda/recipes/mantidqt/meta.yaml
  docs/source/release/v6.10.0/Framework/Dependencies/New_features/36687.rst
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: ISIS Team: Core

#37682 Load workspaces from MultiDialog (Elwin) in a background thread
  docs/source/release/v6.11.0/Inelastic/Bugfixes/37682.rst
  qt/widgets/common/inc/MantidQtWidgets/Common/AddWorkspaceMultiDialog.h
  qt/widgets/common/src/AddWorkspaceMultiDialog.cpp
Labels: Indirect/Inelastic, ISIS Team: Spectroscopy

#37573 Update clang from version 15 to 16
  Framework/DataObjects/inc/MantidDataObjects/MortonIndex/WideIntImpl.h
  conda/recipes/conda_build_config.yaml
  docs/source/release/v6.11.0/Workbench/New_features/37518.rst
  mantid-developer-osx.yml
Labels: macOS Only, ISIS Team: Core

#37683 Fix error when plotting live data
  docs/source/release/v6.11.0/Workbench/Bugfixes/36726.rst
  qt/python/mantidqt/mantidqt/plotting/functions.py
Labels: Bug, GUI, ISIS Team: Core

#37645 Draw peak marker using cached position if no detector
  Framework/DataObjects/inc/MantidDataObjects/Peak.h
  docs/source/release/v6.11.0/Workbench/InstrumentViewer/Bugfixes/37514.rst
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/PanelsSurface.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/UnwrappedCylinder.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/UnwrappedSphere.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/UnwrappedSurface.h
  qt/widgets/instrumentview/src/PanelsSurface.cpp
  qt/widgets/instrumentview/src/PeakOverlay.cpp
  qt/widgets/instrumentview/src/UnwrappedCylinder.cpp
  qt/widgets/instrumentview/src/UnwrappedSphere.cpp
  qt/widgets/instrumentview/test/InstrumentWidget/InstrumentWidgetTest.h
  qt/widgets/instrumentview/test/InstrumentWidget/MockProjectionSurface.h
  qt/widgets/instrumentview/test/InstrumentWidget/PanelsSurfaceTest.h
Labels: Bug, ISIS Team: Core

#37540 Update gcc version to 12
  Framework/API/inc/MantidAPI/IFunction.h
  Framework/API/test/CMakeLists.txt
  Framework/API/test/SpectrumDetectorMappingTest.h
  Framework/Algorithms/inc/MantidAlgorithms/DiscusMultipleScatteringCorrection.h
  Framework/Algorithms/src/DiscusMultipleScatteringCorrection.cpp
  Framework/Algorithms/src/SumOverlappingTubes.cpp
  Framework/Algorithms/test/CMakeLists.txt
  Framework/Crystal/test/CMakeLists.txt
  Framework/DataHandling/src/LoadRaw/vms_convert.cpp
  Framework/DataHandling/test/CMakeLists.txt
  Framework/DataObjects/inc/MantidDataObjects/MDGridBox.tcc
  Framework/DataObjects/test/CMakeLists.txt
  Framework/Geometry/src/Instrument.cpp
  Framework/Geometry/test/CMakeLists.txt
  Framework/ICat/src/GSoap/stdsoap2.cpp
  Framework/Kernel/test/UnitTest.h
  Framework/LiveData/test/CMakeLists.txt
  Framework/MDAlgorithms/test/CMakeLists.txt
  Framework/MDAlgorithms/test/CutMDTest.h
  Framework/Muon/src/MuonAlgorithmHelper.cpp
  Framework/NexusGeometry/src/JSONGeometryParser.cpp
  Framework/NexusGeometry/test/CMakeLists.txt
  Framework/Parallel/src/IO/Chunker.cpp
  Framework/PythonInterface/mantid/api/inc/MantidPythonInterface/api/RegisterWorkspacePtrToPython.h
  Framework/PythonInterface/mantid/api/src/Exports/Algorithm.cpp
  Framework/PythonInterface/mantid/api/src/FitFunctions/IFunctionAdapter.cpp
  Framework/PythonInterface/mantid/kernel/inc/MantidPythonInterface/kernel/Registry/TypedPropertyValueHandler.h
  Framework/Reflectometry/src/RefRoi.cpp
  Framework/SINQ/test/CMakeLists.txt
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/MDEventsTestHelper.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  buildconfig/CMake/QtTargetFunctions.cmake
  conda/recipes/conda_build_config.yaml
  docs/source/release/v6.11.0/Framework/Dependencies/New_features/37519.rst
  mantid-developer-linux.yml
  qt/python/mantidqt/mantidqt/_common.sip
  qt/scientific_interfaces/Direct/test/CMakeLists.txt
  qt/scientific_interfaces/ISISReflectometry/GUI/Event/EventPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/test/CMakeLists.txt
  qt/scientific_interfaces/Inelastic/BayesFitting/Quasi.cpp
  qt/scientific_interfaces/Inelastic/test/CMakeLists.txt
  qt/scientific_interfaces/Muon/MuonAnalysisHelper.cpp
  qt/scientific_interfaces/Muon/test/CMakeLists.txt
  qt/widgets/instrumentview/src/InstrumentWidgetMaskTab.cpp
  qt/widgets/instrumentview/test/CMakeLists.txt
Labels: ISIS Team: Core, Linux Only

#37698 Small speed improvement for ReflectometryISISSumBanks
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISSumBanks.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISSumBanksTest.py
Labels: Reflectometry, ISIS Team: LSS

#37697 Create dependabot.yml to update github actions
  .github/dependabot.yml
Labels: Maintenance

#37677 Add output composite members option to Iqt
  docs/source/release/v6.11.0/Inelastic/New_features/37677.rst
  qt/scientific_interfaces/Inelastic/QENSFitting/FitTabConstants.h
Labels: Indirect/Inelastic, ISIS Team: Spectroscopy

#37679 Update OFFSPEC IDF
  instrument/OFFSPEC_Definition_2023.xml
  instrument/OFFSPEC_Definition_July2024.xml
Labels: Reflectometry, ISIS Team: LSS

#37696 Fixed unhandled exception with certain colourmaps in the sliceviewer
  docs/source/release/v6.11.0/Workbench/SliceViewer/Bugfixes/36723.rst
  qt/python/mantidqt/mantidqt/widgets/colorbar/colorbar.py
  qt/python/mantidqt/mantidqt/widgets/colorbar/test/test_colorbar.py
Labels: Bug, GUI, ISIS Team: Core

#37715 Add matplotlib run constraint to mantid conda recipe
  conda/recipes/mantid/meta.yaml
  docs/source/release/v6.11.0/Framework/Dependencies/Bugfixes/37715.rst
Labels: ISIS Team: Core, Dependencies

#37707 Add usage reports for Indirect/Inelastic interfaces
  qt/scientific_interfaces/Indirect/Diffraction/DiffractionReduction.h
  qt/scientific_interfaces/Indirect/Reduction/ILLEnergyTransfer.h
  qt/scientific_interfaces/Indirect/Reduction/ISISCalibration.h
  qt/scientific_interfaces/Indirect/Reduction/ISISDiagnostics.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferPresenter.h
  qt/scientific_interfaces/Indirect/Reduction/Transmission.h
  qt/scientific_interfaces/Indirect/Simulation/DensityOfStates.h
  qt/scientific_interfaces/Indirect/Simulation/MolDyn.h
  qt/scientific_interfaces/Indirect/Simulation/Sassena.h
  qt/scientific_interfaces/Indirect/Tools/TransmissionCalc.h
  qt/scientific_interfaces/Inelastic/BayesFitting/Quasi.h
  qt/scientific_interfaces/Inelastic/BayesFitting/ResNorm.h
  qt/scientific_interfaces/Inelastic/BayesFitting/Stretch.h
  qt/scientific_interfaces/Inelastic/Corrections/AbsorptionCorrections.h
  qt/scientific_interfaces/Inelastic/Corrections/ApplyAbsorptionCorrections.h
  qt/scientific_interfaces/Inelastic/Corrections/CalculatePaalmanPings.h
  qt/scientific_interfaces/Inelastic/Corrections/ContainerSubtraction.h
  qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.h
  qt/scientific_interfaces/Inelastic/Processor/IqtPresenter.h
  qt/scientific_interfaces/Inelastic/Processor/MomentsPresenter.h
  qt/scientific_interfaces/Inelastic/Processor/SqwPresenter.h
  qt/scientific_interfaces/Inelastic/Processor/SymmetrisePresenter.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FitTab.h
  qt/widgets/spectroscopy/inc/MantidQtWidgets/Spectroscopy/MockObjects.h
  qt/widgets/spectroscopy/inc/MantidQtWidgets/Spectroscopy/RunWidget/IRunSubscriber.h
  qt/widgets/spectroscopy/src/RunWidget/RunPresenter.cpp
Labels: Indirect/Inelastic, ISIS Team: Spectroscopy

#37271 Fix bugs when exporting MD Histo cuts workspaces in sliceviewer
  docs/source/release/v6.10.0/Workbench/SliceViewer/Bugfixes/36084.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py
Labels: Diffraction, ISIS Team: Diffraction, ISIS Team: Core

#37687 Unpin cmake to allow >3.26
  CMakeLists.txt
  Framework/Muon/CMakeLists.txt
  Framework/PythonInterface/CMakeLists.txt
  buildconfig/CMake/CommonSetup.cmake
  buildconfig/CMake/GoogleTest.cmake
  buildconfig/CMake/Span.cmake
  conda/recipes/conda_build_config.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: ISIS Team: Core

#37725 Fix segmentation fault in ExtractFFTSpectrum algorithm
  Framework/Algorithms/src/ExtractFFTSpectrum.cpp
  docs/source/algorithms/TransformToIqt-v1.rst
  docs/source/release/v6.11.0/Framework/Algorithms/Bugfixes/37725.rst
  qt/widgets/common/src/EditLocalParameterDialog.cpp
Labels: High Priority, Bug, ISIS Team: Spectroscopy
