Repository mantidproject/mantid, pull requests merged in 2024-09, with the labels that each got.

#37862 Fix small UI issue in IQT tab
  docs/source/release/v6.11.0/Inelastic/Bugfixes/37862.rst
  qt/scientific_interfaces/Inelastic/Processor/IqtTab.ui
Labels: Bug, Indirect/Inelastic, ISIS Team: Spectroscopy, Reported By User

#37805 Fix for random phase value bug in PyChop
  docs/source/interfaces/direct/PyChop.rst
  docs/source/release/v6.11.0/Direct_Geometry/General/Bugfixes/37805.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/PyChop/PyChopGui.py
  scripts/pychop/merlin.yaml
Labels: Bug, Reported By User, ISIS Team: Excitations/Vesuvio

#37838 Update to C++ 20 standard
  Framework/API/inc/MantidAPI/NumericAxis.h
  Framework/API/inc/MantidAPI/TextAxis.h
  Framework/API/src/CompositeFunction.cpp
  Framework/API/src/NotebookBuilder.cpp
  Framework/API/src/NumericAxis.cpp
  Framework/API/src/ScriptBuilder.cpp
  Framework/API/src/TextAxis.cpp
  Framework/API/test/MDFrameValidatorTest.h
  Framework/Algorithms/src/SampleCorrections/MayersSampleCorrection.cpp
  Framework/Crystal/test/FindClusterFacesTest.h
  Framework/CurveFitting/inc/MantidCurveFitting/Functions/ProcessBackground.h
  Framework/CurveFitting/src/Algorithms/RefinePowderInstrumentParameters.cpp
  Framework/CurveFitting/src/Functions/ProcessBackground.cpp
  Framework/CurveFitting/test/Algorithms/ProfileChiSquared1DTest.h
  Framework/DataHandling/src/ApplyDiffCal.cpp
  Framework/DataHandling/src/FilterEventsByLogValuePreNexus.cpp
  Framework/DataHandling/src/LoadEventPreNexus2.cpp
  Framework/DataHandling/src/LoadMuonNexusV2NexusHelper.cpp
  Framework/DataHandling/src/SaveSampleEnvironmentAndShape.cpp
  Framework/DataObjects/src/TableWorkspace.cpp
  Framework/DataObjects/test/EventListTest.h
  Framework/DataObjects/test/TableWorkspaceTest.h
  Framework/Kernel/inc/MantidKernel/EnumeratedString.h
  Framework/Kernel/inc/MantidKernel/cow_ptr.h
  Framework/Kernel/src/MultiFileNameParser.cpp
  Framework/Kernel/test/BinaryStreamReaderTest.h
  Framework/Kernel/test/BinaryStreamWriterTest.h
  Framework/MDAlgorithms/src/ConvertToDiffractionMDWorkspace.cpp
  Framework/MDAlgorithms/test/MDEventWSWrapperTest.h
  Framework/Muon/src/PSIBackgroundSubtraction.cpp
  Framework/Muon/test/PSIBackgroundSubtractionTest.h
  Framework/PythonInterface/mantid/api/src/Exports/IPeaksWorkspace.cpp
  Framework/Reflectometry/src/SpecularReflectionCalculateTheta.cpp
  Framework/Reflectometry/src/SpecularReflectionCalculateTheta2.cpp
  Framework/Reflectometry/src/SpecularReflectionPositionCorrect.cpp
  buildconfig/CMake/CommonSetup.cmake
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  qt/scientific_interfaces/ISISReflectometry/Common/Map.h
  qt/scientific_interfaces/ISISReflectometry/Common/Parse.h
  qt/widgets/common/inc/MantidQtWidgets/Common/Batch/Subtree.h
  qt/widgets/common/inc/MantidQtWidgets/Common/Testing/QApplicationGlobalFixture.h
  qt/widgets/mplcpp/inc/MantidQtWidgets/MplCpp/Axes.h
  qt/widgets/mplcpp/src/Axes.cpp
  qt/widgets/mplcpp/src/Plot.cpp
  qt/widgets/plotting/inc/MantidQtWidgets/Plotting/PreviewPlot.h
  qt/widgets/plotting/src/PreviewPlot.cpp
Labels: Extra Attention, ISIS Team: Core, Technical Debt

#37898 Fix BayesQuasi when sample workspace has numeric axis
  docs/source/release/v6.11.0/Inelastic/Bugfixes/37898.rst
  scripts/Inelastic/IndirectCommon.py
  scripts/test/IndirectCommonTests.py
Labels: Bug, Indirect/Inelastic, ISIS Team: Spectroscopy, Reported By User

#37864 Remove FindUBUsingMinMaxD algorithm
  Framework/Crystal/CMakeLists.txt
  Framework/Crystal/inc/MantidCrystal/FindUBUsingFFT.h
  Framework/Crystal/inc/MantidCrystal/FindUBUsingIndexedPeaks.h
  Framework/Crystal/inc/MantidCrystal/FindUBUsingLatticeParameters.h
  Framework/Crystal/inc/MantidCrystal/FindUBUsingMinMaxD.h
  Framework/Crystal/inc/MantidCrystal/SetUB.h
  Framework/Crystal/src/FindUBUsingMinMaxD.cpp
  Framework/Crystal/test/FindUBUsingMinMaxDTest.h
  docs/source/algorithms/FindUBUsingMinMaxD-v1.rst
  docs/source/release/v6.1.0/diffraction.rst
  docs/source/release/v6.11.0/Framework/Algorithms/Removed/37864.rst
Labels: Diffraction, Framework, ISIS Team: Core

#37837 Abins: support "high precision" GAUSSIAN frequency calculations
  Testing/Data/UnitTest/ethanol_g16_high_precision_LoadGAUSSIAN.log.md5
  Testing/Data/UnitTest/ethanol_g16_high_precision_LoadGAUSSIAN_atomic_displacements_data_0.txt.md5
  Testing/Data/UnitTest/ethanol_g16_high_precision_LoadGAUSSIAN_data.txt.md5
  docs/source/release/v6.11.0/Inelastic/Algorithms/New_features/37837.rst
  scripts/abins/input/gaussianloader.py
  scripts/test/Abins/AbinsLoadGAUSSIANTest.py
Labels: ISIS Team: Spectroscopy

#37866 Add libopenblas v0.3.28 notes to build configs
  conda/recipes/conda_build_config.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
Labels: ISIS Team: Core, DevOps

#37775 Fix setuptools deprecations
  Framework/PythonInterface/pyproject.toml
  Framework/PythonInterface/setup.py
  Framework/PythonInterface/test/python/mantid/SimpleAPITest.py
  buildconfig/CMake/LinuxPackageScripts.cmake
  buildconfig/CMake/PythonPackageTargetFunctions.cmake
  qt/applications/workbench/pyproject.toml
  qt/python/mantidqt/pyproject.toml
  qt/python/mantidqtinterfaces/pyproject.toml
Labels: Maintenance, ISIS Team: Core

#37261 Try using pydantic to cut down on type validation boilerplate
  conda/recipes/mantid/meta.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
  scripts/abins/abinsdata.py
  scripts/abins/atomsdata.py
  scripts/abins/constants.py
  scripts/abins/io.py
  scripts/abins/powderdata.py
  scripts/abins/sdata.py
  scripts/abins/spowdersemiempiricalcalculator.py
  scripts/abins/test_helpers.py
  scripts/test/Abins/AbinsCalculateSPowderTest.py
  scripts/test/Abins/AbinsDataTest.py
  scripts/test/Abins/AbinsIOmoduleTest.py
  scripts/test/Abins/AbinsLoadCASTEPTest.py
  scripts/test/Abins/AbinsPowderDataTest.py
  scripts/test/Abins/AbinsSDataTest.py
Labels: ISIS Team: Core

#37917 Skip Problematically Random OSIRISIqtAndIqtFitMulti System Test
  Testing/SystemTests/tests/framework/ISISIndirectInelastic.py
Labels: Indirect/Inelastic, ISIS Team: LSS

#37914 36213 Incorrect Tab Order On The Figure Options Window
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/axestabwidget/axes_tab_widget.ui
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/curvestabwidget/curves_tab.ui
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/curvestabwidget/errorbarstabwidget/curves_tab_errorbars_tab.ui
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/curvestabwidget/linetabwidget/curves_tab_line_tab.ui
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/imagestabwidget/images_tab.ui
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/legendtabwidget/legend_tab.ui
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/plot_config_dialog.ui
Labels: ISIS Team: Core

#37878 changes to mantid's `assert_almost_equal` test fixture
  Framework/PythonInterface/mantid/_testing/AssertAlmostEqual.py
  Framework/PythonInterface/test/python/mantid/_testing/AssertAlmostEqualTest.py
  docs/source/api/python/mantid/testing/assert_almost_equal.rst
  docs/source/release/v6.11.0/Framework/Python/New_features/37878.rst
Labels: ORNL Team

#37909 Add ScaleInstrumentComponent Algorithm
  Framework/Beamline/inc/MantidBeamline/ComponentInfo.h
  Framework/Beamline/src/ComponentInfo.cpp
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/ScaleInstrumentComponent.h
  Framework/DataHandling/src/ScaleInstrumentComponent.cpp
  Framework/DataHandling/test/ScaleInstrumentComponentTest.h
  Framework/Geometry/inc/MantidGeometry/Instrument/ComponentInfo.h
  Framework/Geometry/src/Instrument/ComponentInfo.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/algorithms/ScaleInstrumentComponent-v1.rst
  docs/source/images/ScaleComponent_default.png
  docs/source/images/ScaleComponent_no_resize.png
  docs/source/images/ScaleComponent_resize.png
  docs/source/release/v6.11.0/Framework/Algorithms/New_features/37909.rst
Labels: ORNL Team

#37923 Disable warning about atomic_shared_ptr<T>
  buildconfig/CMake/CommonSetup.cmake
Labels: High Priority, ISIS Team: Core

#37857 Load() loads incorrect extension when specified
  Framework/API/src/FileFinder.cpp
  Framework/API/test/FileFinderTest.h
  docs/source/release/v6.11.0/Framework/Algorithms/New_features/37857.rst
Labels: Bug, ISIS Team: Core

#37899 Add a System Test for the DepolarizedAnalyserTransmission Algorithm
  Testing/Data/SystemTest/ZOOM00038238.nxs.md5
  Testing/Data/SystemTest/ZOOM00038335.nxs.md5
  Testing/SystemTests/tests/framework/PolarizationCorrections/DepolarizedAnalyserTransmissionTest.py
  Testing/SystemTests/tests/framework/reference/DepolCurvesReference.nxs.md5
  Testing/SystemTests/tests/framework/reference/DepolParamsReference.nxs.md5
Labels: SANS, ISIS Team: LSS

#37925 Fix startup tests
  Testing/SystemTests/tests/qt/WorkbenchStartupTest.py
  qt/applications/workbench/CMakeLists.txt
Labels: High Priority, ISIS Team: Core

#37921 Remove tcbrindle/span and use std::span
  Framework/Kernel/CMakeLists.txt
  Framework/Kernel/src/Atom.cpp
  buildconfig/CMake/CommonSetup.cmake
  buildconfig/CMake/Span.cmake
  buildconfig/CMake/span_disable_testing.patch
  docs/source/release/v6.11.0/Framework/Algorithms/Bugfixes/37842.rst
  tools/PeriodicTable/generate_atom_code.py
Labels: Maintenance, ISIS Team: Core, Dependencies, Technical Debt

#37928 37723 malformed xml crash
  docs/source/release/v6.11.0/Workbench/New_features/37723.rst
  qt/python/mantidqt/mantidqt/widgets/codeeditor/interpreter.py
Labels: ISIS Team: Core

#37648 35373 support for collimator in DiscusMultipleScatteringCorrection algorithm
  Framework/Algorithms/inc/MantidAlgorithms/DiscusMultipleScatteringCorrection.h
  Framework/Algorithms/src/DiscusMultipleScatteringCorrection.cpp
  Framework/Algorithms/test/DiscusMultipleScatteringCorrectionTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.11.0/Framework/Algorithms/New_features/35373.rst
  instrument/ENGIN-X_Parameters.xml
Labels: Diffraction

#37820 Add OutputSuffix to ISISIndirectEnergyTransfer
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransfer.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransferTest.py
  docs/source/release/v6.11.0/Framework/Algorithms/New_features/37820.rst
  scripts/Inelastic/IndirectReductionCommon.py
Labels: Indirect/Inelastic, Framework, ISIS Team: Spectroscopy

#37673 Add run number to output of SaveNXSPE
  Framework/DataHandling/inc/MantidDataHandling/SaveNXSPE.h
  Framework/DataHandling/src/SaveNXSPE.cpp
  Framework/DataHandling/test/SaveNXSPETest.h
  docs/source/algorithms/SaveNXSPE-v1.rst
  docs/source/release/v6.11.0/Direct_Geometry/General/New_features/37673.rst
Labels: Direct Inelastic, Indirect/Inelastic, ISIS Team: Excitations/Vesuvio

#37884 Hide the "Optimise Event Slices" Checkbox In the ISIS SANS GUI
  docs/source/release/v6.11.0/SANS/Bugfixes/37846.rst
  scripts/Interface/ui/sans_isis/sans_data_processor_gui.py
Labels: SANS, ISIS Team: LSS

#37886 Remove SaveDiffFittingAscii algorithm
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/SaveAscii2.h
  Framework/DataHandling/inc/MantidDataHandling/SaveDiffFittingAscii.h
  Framework/DataHandling/src/SaveDiffFittingAscii.cpp
  docs/source/algorithms/SaveDiffFittingAscii-v1.rst
  docs/source/release/v3.8.0/diffraction.rst
  docs/source/release/v3.8.0/framework.rst
  docs/source/release/v6.11.0/Framework/Algorithms/Removed/37886.rst
Labels: Framework, ISIS Team: Core

#37942 Fix to system test `ISISIndirectInelastic.OSIRISIqtAndIqtFitMulti`
  Testing/SystemTests/tests/framework/ISISIndirectInelastic.py
  docs/source/release/v6.11.0/Inelastic/Bugfixes/37920.rst
Labels: Indirect/Inelastic, ISIS Team: Spectroscopy

#37948 isis reduction psi is not accepting 0 value
  scripts/Inelastic/Direct/PropertiesDescriptors.py
  scripts/test/DirectPropertyManagerTest.py
Labels: Bug, Direct Inelastic, ISIS Team: Excitations/Vesuvio, Technical Debt

#37950 Fix failing test in test_fitpropertybrowser
  qt/python/mantidqt/mantidqt/widgets/test/test_fitpropertybrowser.py
Labels: High Priority, DevOps

#37954 Switch to supported clang-format pre-commit hook
  .pre-commit-config.yaml
Labels: Maintenance

#37959 Fix failing test in test_fitpropertybrowser - ornl-next
  .pre-commit-config.yaml
  qt/python/mantidqt/mantidqt/widgets/test/test_fitpropertybrowser.py
Labels: ORNL Team

#37946 Fix Importing results on Muon ALC interface
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.11.0/Muon/ALC/Bugfixes/37946.rst
  qt/scientific_interfaces/Muon/ALCBaselineModellingModel.cpp
  qt/scientific_interfaces/Muon/ALCInterface.cpp
  qt/scientific_interfaces/Muon/ALCPeakFittingModel.cpp
Labels: Muon, ISIS Team: Spectroscopy

#37926 Add System Test for HeliumAnalyserEfficiency
  Testing/Data/SystemTest/ZOOM00038249.nxs.md5
  Testing/Data/SystemTest/ZOOM00038253.nxs.md5
  Testing/SystemTests/tests/framework/PolarizationCorrections/DepolarizedAnalyserTransmissionTest.py
  Testing/SystemTests/tests/framework/PolarizationCorrections/HeliumAnalyserEfficiencyTest.py
  Testing/SystemTests/tests/framework/PolarizationCorrections/SANSPolarizationCorrectionsBase.py
  Testing/SystemTests/tests/framework/PolarizationCorrections/__init__.py
  Testing/SystemTests/tests/framework/reference/HeliumAnalyserCurvesReference.nxs.md5
  Testing/SystemTests/tests/framework/reference/HeliumAnalyserEfficiencyReference.nxs.md5
  Testing/SystemTests/tests/framework/reference/HeliumAnalyserParamsReference.nxs.md5
  Testing/SystemTests/tests/framework/reference/UnpolHeliumAnalyserCurvesReference.nxs.md5
  Testing/SystemTests/tests/framework/reference/UnpolHeliumAnalyserEfficiencyReference.nxs.md5
  Testing/SystemTests/tests/framework/reference/UnpolHeliumAnalyserParamsReference.nxs.md5
Labels: SANS, Maintenance, ISIS Team: LSS

#37646 Use mantid fitting in IntegratePeaks1DProfile (instead of scipy as was too slow)
  Framework/CurveFitting/inc/MantidCurveFitting/Functions/Gaussian.h
  Framework/PythonInterface/mantid/api/src/Exports/IPeakFunction.cpp
  Framework/PythonInterface/plugins/algorithms/IntegratePeaks1DProfile.py
  Framework/PythonInterface/test/python/plugins/algorithms/IntegratePeaks1DProfileTest.py
  Testing/SystemTests/tests/framework/SXDAnalysis.py
  docs/source/algorithms/IntegratePeaks1DProfile-v1.rst
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction

#37924 mantid-developer metapackage
  .pre-commit-config.yaml
  buildconfig/Jenkins/Conda/conda-buildscript
  buildconfig/Jenkins/Conda/cppcheck.sh
  buildconfig/Jenkins/Conda/doxygen.sh
  buildconfig/Jenkins/Conda/mamba-utils
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
  buildconfig/Jenkins/Conda/package-conda
  buildconfig/Jenkins/build_and_publish_docs.sh
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid-developer/meta.yaml
  conda/recipes/mantid/meta.yaml
  conda/recipes/mantiddocs/meta.yaml
  conda/recipes/mantidqt/meta.yaml
  conda/recipes/mantidworkbench/meta.yaml
  dev-docs/source/CondaPackageManager.rst
  dev-docs/source/GettingStarted/GettingStartedCondaLinux.rst
  dev-docs/source/GettingStarted/GettingStartedCondaOSX.rst
  dev-docs/source/GettingStarted/GettingStartedCondaWindows.rst
  dev-docs/source/GettingStarted/MantidDeveloperSetup.rst
  dev-docs/source/Packaging.rst
  dev-docs/source/Standards/PythonStandards.rst
  docs/source/release/v6.11.0/index.rst
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: Extra Attention, ISIS Team: Core, Dependencies, Technical Debt, DevOps

#37865 Remove FilterEventsByLogValuePreNexus Algorithm
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/FilterEventsByLogValuePreNexus.h
  Framework/DataHandling/inc/MantidDataHandling/LoadEventPreNexus2.h
  Framework/DataHandling/src/FilterEventsByLogValuePreNexus.cpp
  Framework/DataHandling/test/FilterEventsByLogValuePreNexusTest.h
  docs/source/algorithms/FilterEventsByLogValuePreNexus-v2.rst
  docs/source/release/v6.11.0/Framework/Algorithms/Removed/37865.rst
  docs/sphinxext/mantiddoc/directives/sourcelink.py
Labels: Framework, ISIS Team: Core

#37962 Increase external data timeout
  Framework/PythonInterface/plugins/algorithms/IntegratePeaks1DProfile.py
  buildconfig/CMake/MantidExternalData.cmake
Labels: High Priority, ISIS Team: Core, DevOps

#37927 Add ScaleInstrumentComponent algorithm
  Framework/Beamline/inc/MantidBeamline/ComponentInfo.h
  Framework/Beamline/src/ComponentInfo.cpp
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/ScaleInstrumentComponent.h
  Framework/DataHandling/src/ScaleInstrumentComponent.cpp
  Framework/DataHandling/test/ScaleInstrumentComponentTest.h
  Framework/Geometry/inc/MantidGeometry/Instrument/ComponentInfo.h
  Framework/Geometry/src/Instrument/ComponentInfo.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/algorithms/ScaleInstrumentComponent-v1.rst
  docs/source/images/ScaleComponent_default.png
  docs/source/images/ScaleComponent_no_resize.png
  docs/source/images/ScaleComponent_resize.png
  docs/source/release/v6.11.0/Framework/Algorithms/New_features/37909.rst
Labels: ORNL Team

#37935 Consistently position const in FileSaver class using east const approach
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/FileSaver.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/FileSaver.h
  qt/scientific_interfaces/ISISReflectometry/test/Save/FileSaverTest.h
Labels: Reflectometry, ISIS Team: LSS

#37883 Update available fit functions on Function Q interface according to data
  Framework/Kernel/inc/MantidKernel/Strings.h
  Framework/Kernel/src/Strings.cpp
  Framework/Kernel/test/StringsTest.h
  docs/source/release/v6.11.0/Inelastic/Bugfixes/37671.rst
  qt/scientific_interfaces/Inelastic/QENSFitting/FitDataPresenter.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FitDataPresenter.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FitDataView.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FitDataView.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FitTab.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionQDataPresenter.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionQDataPresenter.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionQParameters.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/IFitDataView.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/MockObjects.h
Labels: Bug, GUI, ISIS Team: Spectroscopy, Reported By User

#37826 Add signal to sigma post fitting check
  Framework/Algorithms/inc/MantidAlgorithms/FitPeaks.h
  Framework/Algorithms/src/FitPeaks.cpp
  Framework/Algorithms/src/PDCalibration.cpp
  Framework/Algorithms/test/FitPeaksTest.h
  docs/source/release/v6.11.0/Diffraction/Powder/New_features/37826.rst
Labels: Diffraction, ISIS Team: Diffraction

#37937 37594 sliceviewer sample data order
  docs/source/release/v6.11.0/Workbench/SliceViewer/Bugfixes/37594.rst
  qt/applications/workbench/workbench/plugins/workspacewidget.py
Labels: Bug, ISIS Team: Core

#37929 Add option to fit and subtract prompt pulse in HRPD data reduction
  Framework/PythonInterface/plugins/functions/PearsonIV.py
  Testing/SystemTests/tests/framework/ISIS_PowderHRPDTest.py
  docs/source/release/v6.11.0/Diffraction/Powder/New_features/37929.rst
  scripts/Diffraction/isis_powder/hrpd.py
  scripts/Diffraction/isis_powder/hrpd_routines/hrpd_param_mapping.py
Labels: Diffraction, Powder, ISIS Team: Diffraction

#37966 Fix PolarizerEfficiency Equation
  Framework/Algorithms/src/PolarizationCorrections/PolarizerEfficiency.cpp
  Framework/Algorithms/test/PolarizationCorrections/PolarizerEfficiencyTest.h
  docs/source/algorithms/PolarizerEfficiency-v1.rst
Labels: Bug, SANS, ISIS Team: LSS

#37813 Add tool for generating example MVP files from a template
  dev-docs/source/MVPDesign.rst
  tools/MVP/template.py
  tools/MVP/templates/CMakeLists.txt.in
  tools/MVP/templates/Model.cpp.in
  tools/MVP/templates/Model.h.in
  tools/MVP/templates/Presenter.cpp.in
  tools/MVP/templates/Presenter.h.in
  tools/MVP/templates/View.cpp.in
  tools/MVP/templates/View.h.in
  tools/MVP/templates/launch.py.in
  tools/MVP/templates/main.cpp.in
  tools/MVP/templates/model.py.in
  tools/MVP/templates/presenter.py.in
  tools/MVP/templates/view.py.in
Labels: Documentation, ISIS Team: Core

#37972 Increase tolerance in HRPD system test due to suspected OS dependent fitting
  Testing/SystemTests/tests/framework/ISIS_PowderHRPDTest.py
Labels: High Priority, Diffraction, Powder, ISIS Team: Diffraction

#37980 Add -u argument to mambaforge
  buildconfig/Jenkins/Conda/download-and-install-mambaforge
Labels: High Priority, ISIS Team: Core

#37975 Fix calculation of EISF errors in BayesQuasi algorithm
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesQuasi.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/BayesQuasiTest.py
  docs/source/release/v6.11.0/Inelastic/Bugfixes/37973.rst
Labels: Bug, Indirect/Inelastic, ISIS Team: Spectroscopy, Reported By User

#38014 Fix for import error in ISIS SX reduction classes
  Framework/PythonInterface/plugins/algorithms/FindGlobalBMatrix.py
  Framework/PythonInterface/plugins/algorithms/FindGoniometerFromUB.py
  scripts/Diffraction/single_crystal/base_sx.py
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction

#38013 Deprecate LoadDspacemap
  Framework/DataHandling/inc/MantidDataHandling/LoadDspacemap.h
  Framework/DataHandling/src/LoadDspacemap.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.12.0/Framework/Data_Handling/New_features/38013.rst
Labels: Maintenance

#37953 Update MVP tutorial documentation
  dev-docs/source/MVPTutorial/AddButton.rst
  dev-docs/source/MVPTutorial/AddComboBox.rst
  dev-docs/source/MVPTutorial/AddLabel.rst
  dev-docs/source/MVPTutorial/AddLineEdit.rst
  dev-docs/source/MVPTutorial/AddSpinBox.rst
  dev-docs/source/MVPTutorial/CalculatorExample/Calculator.py
  dev-docs/source/MVPTutorial/CalculatorExample/Model.py
  dev-docs/source/MVPTutorial/CalculatorExample/Presenter.py
  dev-docs/source/MVPTutorial/CalculatorExample/View.py
  dev-docs/source/MVPTutorial/CalculatorExample/index.rst
  dev-docs/source/MVPTutorial/CompleteGUI.rst
  dev-docs/source/MVPTutorial/CompleteGUIcode/main.py
  dev-docs/source/MVPTutorial/CompleteGUIcode/main_presenter.py
  dev-docs/source/MVPTutorial/CompleteGUIcode/main_view.py
  dev-docs/source/MVPTutorial/CompleteGUIcode/model_colour.py
  dev-docs/source/MVPTutorial/CompleteGUIcode/model_data.py
  dev-docs/source/MVPTutorial/CompleteGUIcode/plot_presenter.py
  dev-docs/source/MVPTutorial/CompleteGUIcode/plot_view.py
  dev-docs/source/MVPTutorial/CompleteGUIcode/presenter.py
  dev-docs/source/MVPTutorial/CompleteGUIcode/view.py
  dev-docs/source/MVPTutorial/ExtractInfoFromView.rst
  dev-docs/source/MVPTutorial/FinalExercise.rst
  dev-docs/source/MVPTutorial/Layouts.rst
  dev-docs/source/MVPTutorial/Matplotlib.rst
  dev-docs/source/MVPTutorial/Mocking.rst
  dev-docs/source/MVPTutorial/MockingExerciseSolution.rst
  dev-docs/source/MVPTutorial/Model.rst
  dev-docs/source/MVPTutorial/ModelExercise.rst
  dev-docs/source/MVPTutorial/ModelExerciseSolution.rst
  dev-docs/source/MVPTutorial/MultipleViews.rst
  dev-docs/source/MVPTutorial/Presenter.rst
  dev-docs/source/MVPTutorial/PresenterExerciseSolution.rst
  dev-docs/source/MVPTutorial/ReceivingSignalFromView.rst
  dev-docs/source/MVPTutorial/Tables.rst
  dev-docs/source/MVPTutorial/ViewExercise1Solution.rst
  dev-docs/source/MVPTutorial/index.rst
Labels: Documentation

#37901 Add tests for IqtPresenter tab
  qt/scientific_interfaces/Inelastic/Processor/DataProcessor.h
  qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.h
  qt/scientific_interfaces/Inelastic/Processor/IqtPresenter.cpp
  qt/scientific_interfaces/Inelastic/Processor/IqtPresenter.h
  qt/scientific_interfaces/Inelastic/test/Processor/CMakeLists.txt
  qt/scientific_interfaces/Inelastic/test/Processor/IqtPresenterTest.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/MockObjects.h
Labels: Indirect/Inelastic, Maintenance, ISIS Team: Spectroscopy

#38015 Check for legend existing before using in _correct_for_scroll_event_on_legend
  qt/applications/workbench/workbench/plotting/figureinteraction.py
Labels: Bug, Found in Beta

#38031 Fix typo in muon testing docs found during manual testing for v6.11
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_Analysis_MUSR.rst
Labels: Documentation

#38037 Remove workspace history workaround from binaryOpertaions
  Framework/PythonInterface/mantid/api/src/Exports/BinaryOperations.cpp
Labels: Bug, ISIS Team: Core, Found in Beta

#38040 Fix incorrect BayesQuasi calculation
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesQuasi.py
  Testing/SystemTests/tests/framework/BayesQuasiTest.py
  Testing/SystemTests/tests/framework/reference/irs26176_graphite002_QLr_Prob.nxs.md5
  Testing/SystemTests/tests/framework/reference/irs26176_graphite002_QLr_Result.nxs.md5
Labels: Bug, Indirect/Inelastic, ISIS Team: Spectroscopy, Reported By User

#38012 Coverity issue fixes
  Framework/Algorithms/src/DiscusMultipleScatteringCorrection.cpp
  Framework/Crystal/src/RotateSampleShape.cpp
Labels: Diffraction

#38052 Fix wrong filepaths on MVP tutorial documentation
  dev-docs/source/MVPTutorial/CalculatorExample/calculator.py
  dev-docs/source/MVPTutorial/CalculatorExample/model.py
  dev-docs/source/MVPTutorial/CalculatorExample/presenter.py
  dev-docs/source/MVPTutorial/CalculatorExample/view.py
Labels: Documentation

#38069 Skip BayesQuasiTest on macOS
  Testing/SystemTests/tests/framework/BayesQuasiTest.py
Labels: High Priority, Framework

#38036 Avoid limiting the size of the Preview Workspace combobox on Elwin
  qt/scientific_interfaces/Inelastic/Processor/ElwinTab.ui
Labels: Bug, GUI, ISIS Team: Spectroscopy, Reported By User

#38049 Fix restricted suffix not working on Elwin interface.
  docs/source/release/v6.11.0/Inelastic/Bugfixes/38041.rst
  qt/widgets/common/inc/MantidQtWidgets/Common/WorkspaceMultiSelector.h
  qt/widgets/common/src/WorkspaceMultiSelector.cpp
Labels: Bug, ISIS Team: Spectroscopy

#38057 Turn ISIS SANS compatibility mode off by default
  docs/source/interfaces/isis_sans/Settings Tab.rst
  docs/source/release/v6.11.0/SANS/New_features/38053.rst
  scripts/Interface/ui/sans_isis/sans_data_processor_window.ui
  scripts/SANS/sans/state/StateObjects/StateCompatibility.py
  scripts/test/SANS/gui_logic/state_gui_model_test.py
Labels: SANS, ISIS Team: LSS

#38051 Fix Inelastic Symmetrise Preview crash
  qt/scientific_interfaces/Inelastic/Processor/SymmetrisePresenter.cpp
  qt/scientific_interfaces/Inelastic/Processor/SymmetrisePresenter.h
  qt/widgets/common/inc/MantidQtWidgets/Common/DataSelector.h
  qt/widgets/common/inc/MantidQtWidgets/Common/MockUserInputValidator.h
  qt/widgets/common/inc/MantidQtWidgets/Common/UserInputValidator.h
  qt/widgets/common/src/DataSelector.cpp
  qt/widgets/common/src/UserInputValidator.cpp
  qt/widgets/spectroscopy/inc/MantidQtWidgets/Spectroscopy/DataValidationHelper.h
  qt/widgets/spectroscopy/src/DataValidationHelper.cpp
  qt/widgets/spectroscopy/test/DataValidationHelperTest.h
Labels: Bug, Indirect/Inelastic, ISIS Team: Spectroscopy

#38098 Pin mamba=1.5 in package-standalone environment
  buildconfig/Jenkins/Conda/package-standalone
Labels: High Priority, ISIS Team: Core, Dependencies

#38094 Stop observing ADS while the algorithms are running
  qt/scientific_interfaces/Indirect/Reduction/DataReductionTab.h
  qt/scientific_interfaces/Indirect/Reduction/ISISCalibration.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISDiagnostics.cpp
  qt/widgets/spectroscopy/inc/MantidQtWidgets/Spectroscopy/OutputWidget/OutputPlotOptionsPresenter.h
Labels: High Priority, Bug, Indirect/Inelastic, ISIS Team: Spectroscopy

#38055 Update project recovery manual test instructions
  dev-docs/source/Testing/ErrorReporter-ProjectRecovery/ProjectRecoveryTesting.rst
Labels: Documentation

#38071 Remove the deprecation messages in two algorithms
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesQuasi.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesStretch.py
Labels: Indirect/Inelastic, ISIS Team: Spectroscopy

#38093 Remove IndirectNeutron python file
  Framework/PythonInterface/plugins/algorithms/LoadNMoldyn3Ascii.py
  Testing/SystemTests/tests/framework/ISISIndirectLoadAsciiTest.py
  docs/source/release/v6.12.0/Indirect/Bugfixes/38093.rst
  scripts/Inelastic/IndirectNeutron.py
Labels: Indirect/Inelastic, Maintenance, ISIS Team: Spectroscopy, ILL Team

#37984 Fix plot crash on negative errors
  Framework/PythonInterface/mantid/plots/axesfunctions.py
  Framework/PythonInterface/test/python/mantid/plots/axesfunctionsTest.py
  docs/source/release/v6.11.0/Workbench/Bugfixes/37973.rst
Labels: Bug, ISIS Team: Core

#38032 Updated checklist for QA managers
  dev-docs/source/ReleaseChecklist.rst
Labels: Documentation
