Repository mantidproject/mantid, pull requests merged in 2024-05, with the labels that each got.

#37238 Reset loader name and version at end of algorithm
  Framework/DataHandling/src/Load.cpp
  Framework/DataHandling/test/LoadTest.h
  docs/source/release/v6.10.0/Framework/Data_Handling/Bugfixes/37236.rst
Labels: Bug, ISIS Team: Core

#37124 Fix build issues for masOS Sonoma 14.4
  Framework/Kernel/src/NetworkProxyOSX.cpp
Labels: macOS Only

#37246 Remove build warnings in tablet widget validator class
  qt/widgets/common/inc/MantidQtWidgets/Common/TableWidgetValidators.h
  qt/widgets/common/src/TableWidgetValidators.cpp
Labels: Indirect/Inelastic, ISIS Team: Spectroscopy

#37228 Fix Function Browsers going out of sync
  docs/source/release/v6.10.0/Inelastic/Bugfixes/37199.rst
  qt/scientific_interfaces/Inelastic/QENSFitting/InelasticFitPropertyBrowser.cpp
Labels: Bug, Indirect/Inelastic, ISIS Team: Spectroscopy

#37223 Prevent warnings when adding data from dialogs in QENS fitting interface
  docs/source/release/v6.10.0/Inelastic/Bugfixes/37185.rst
  qt/scientific_interfaces/Inelastic/QENSFitting/FqFitAddWorkspaceDialog.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FqFitAddWorkspaceDialog.h
  qt/widgets/common/inc/MantidQtWidgets/Common/AddWorkspaceDialog.h
  qt/widgets/common/inc/MantidQtWidgets/Common/DataSelector.h
  qt/widgets/common/src/AddWorkspaceDialog.cpp
  qt/widgets/common/src/DataSelector.cpp
Labels: Indirect/Inelastic, ISIS Team: Spectroscopy

#37103 Add new integration algorithm for single-crystal Bragg peaks
  Framework/PythonInterface/mantid/api/src/Exports/IPeakFunction.cpp
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/IntegratePeaks1DProfile.py
  Framework/PythonInterface/plugins/algorithms/IntegratePeaksShoeboxTOF.py
  Framework/PythonInterface/test/python/plugins/algorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/IntegratePeaks1DProfileTest.py
  Testing/SystemTests/tests/framework/SXDAnalysis.py
  docs/source/algorithms/IntegratePeaks1DProfile-v1.rst
  docs/source/images/IntegratePeaks1DProfile_OutputFile.png
  docs/source/release/v6.10.0/Diffraction/Single_Crystal/Bugfixes/37103.rst
  docs/source/release/v6.10.0/Diffraction/Single_Crystal/New_features/37103.rst
  scripts/Diffraction/single_crystal/base_sx.py
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction

#37206 Update ISIS Reflectometry GUI manual testing instructions
  dev-docs/source/Testing/ReflectometryGUI/ReflectometryGUITests.rst
Labels: Reflectometry, Documentation, ISIS Team: LSS

#37244 Create AlgorithmRunner with no Qt
  qt/scientific_interfaces/Direct/ALFAlgorithmManager.cpp
  qt/scientific_interfaces/Direct/ALFAlgorithmManager.h
  qt/scientific_interfaces/Direct/test/ALFAlgorithmManagerTest.h
  qt/scientific_interfaces/General/StepScan.cpp
  qt/scientific_interfaces/General/StepScan.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewJobManager.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewJobManager.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Runs/IRunsView.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Runs/QtCatalogSearcher.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Runs/QtRunsView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Runs/QtRunsView.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Runs/RunsPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/test/Runs/MockRunsView.h
  qt/scientific_interfaces/ISISReflectometry/test/Runs/QtCatalogSearcherTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Runs/RunsPresenterTest.h
  qt/scientific_interfaces/Indirect/Common/IndirectInstrumentConfig.cpp
  qt/scientific_interfaces/Indirect/Common/IndirectInstrumentConfig.h
  qt/scientific_interfaces/Indirect/Reduction/IndirectDataReduction.cpp
  qt/scientific_interfaces/Indirect/Reduction/IndirectDataReduction.h
  qt/scientific_interfaces/Indirect/Simulation/IndirectSimulationTab.h
  qt/scientific_interfaces/Inelastic/Common/IndirectTab.h
  qt/scientific_interfaces/Inelastic/Manipulation/DataManipulationInterface.h
  qt/widgets/common/CMakeLists.txt
  qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmRunner.h
  qt/widgets/common/inc/MantidQtWidgets/Common/DataSelector.h
  qt/widgets/common/inc/MantidQtWidgets/Common/IAlgorithmRunnerSubscriber.h
  qt/widgets/common/inc/MantidQtWidgets/Common/IJobRunner.h
  qt/widgets/common/inc/MantidQtWidgets/Common/MockAlgorithmRunner.h
  qt/widgets/common/inc/MantidQtWidgets/Common/MockQtAlgorithmRunner.h
  qt/widgets/common/inc/MantidQtWidgets/Common/QtAlgorithmRunner.h
  qt/widgets/common/src/AlgorithmRunner.cpp
  qt/widgets/common/src/QtAlgorithmRunner.cpp
  qt/widgets/common/test/AlgorithmRunnerTest.h
Labels: Maintenance, ISIS Team: Spectroscopy, ISIS Team: LSS

#37171 Add option to find peaks using ratio variance/ mean in FindSXPeaksConvolve
  Framework/PythonInterface/plugins/algorithms/FindSXPeaksConvolve.py
  Framework/PythonInterface/test/python/plugins/algorithms/FindSXPeaksConvolveTest.py
  Testing/SystemTests/tests/framework/SXDAnalysis.py
  Testing/SystemTests/tests/framework/reference/SXD23767_found_peaks_convolve.nxs.md5
  docs/source/algorithms/FindSXPeaksConvolve-v1.rst
  docs/source/release/v6.10.0/Diffraction/Single_Crystal/New_features/37171.rst
  docs/source/techniques/ISIS_SingleCrystalDiffraction_Workflow.rst
  scripts/Diffraction/single_crystal/sxd.py
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction

#37188 Consider phase offset for disk on Merlin in PyChop
  docs/source/release/v6.10.0/Direct_Geometry/General/New_features/37188.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/PyChop/PyChopGui.py
  qt/python/mantidqtinterfaces/test/PyChopInstrumentTest.py
  scripts/pychop/ISISDisk.py
  scripts/pychop/Instruments.py
  scripts/pychop/MulpyRep.py
  scripts/pychop/merlin.yaml
Labels: Direct Inelastic, ISIS Team: Excitations/Vesuvio

#37257 Muon field orientation make case-insensitive
  Framework/DataHandling/src/LoadMuonNexusV2NexusHelper.cpp
Labels: Bug, Muon, ISIS Team: Spectroscopy

#37178 Fix workspace not opening if a recovery file has been corrupted
  docs/source/release/v6.10.0/Workbench/Bugfixes/37175.rst
  qt/applications/workbench/workbench/projectrecovery/recoverygui/projectrecoverymodel.py
Labels: Bug, ISIS Team: Core

#37266 Fix missing screenshots for Indirect Diffraction
  docs/source/interfaces/indirect/Indirect Diffraction.rst
Labels: Bug, Indirect/Inelastic, Documentation, ISIS Team: Spectroscopy

#37233 Add grouping options for HB3A
  Framework/MDAlgorithms/src/ConvertHFIRSCDtoMDE.cpp
  Framework/PythonInterface/plugins/algorithms/HB3AAdjustSampleNorm.py
  Framework/PythonInterface/test/python/plugins/algorithms/HB3AAdjustSampleNormTest.py
  docs/source/algorithms/HB3AAdjustSampleNorm-v1.rst
  docs/source/release/v6.10.0/Diffraction/Single_Crystal/New_features/37233.rst
Labels: Diffraction, Single Crystal, Framework

#37275 Pin libcxx to v16 to temp resolve pipeline failure
  mantid-developer-osx.yml
Labels: High Priority, DevOps

#37240 Replaced method close_event() in code base
  qt/applications/workbench/workbench/plotting/figuremanager.py
Labels: ISIS Team: Core

#37186 Fix a couple property handler bugs
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.10.0/Workbench/Bugfixes/37129.rst
  qt/widgets/common/inc/MantidQtWidgets/Common/PropertyHandler.h
  qt/widgets/common/src/PropertyHandler.cpp
Labels: Bug, ISIS Team: Core, Reported By User

#37121 Replace plt.show() with fig.show() in the docs
  docs/source/algorithms/ConvertToReflectometryQ-v1.rst
  docs/source/algorithms/ConvertToReflectometryQ-v2.rst
  docs/source/algorithms/CopySample-v1.rst
  docs/source/algorithms/HB2AReduce-v1.rst
  docs/source/algorithms/LagrangeILLReduction-v1.rst
  docs/source/algorithms/SetSample-v1.rst
  docs/source/algorithms/SingleCrystalDiffuseReduction-v1.rst
  docs/source/concepts/HowToDefineGeometricShape.rst
  docs/source/fitting/fitfunctions/BivariateGaussian.rst
  docs/source/interfaces/direct/Crystal Field Python Interface.rst
  docs/source/plotting/1DPlotsHelp.rst
  docs/source/plotting/3DPlotsHelp.rst
  docs/source/plotting/ColorfillPlotsHelp.rst
  docs/source/plotting/MeshPlotHelp.rst
  docs/source/plotting/WaterfallPlotsHelp.rst
  docs/source/release/v5.1.0/mantidworkbench.rst
  docs/source/techniques/CrystalField.rst
  docs/source/tutorials/mantid_basic_course/connecting_data_to_instruments/06_sample_logs.rst
  docs/source/tutorials/mantid_basic_course/getting_started/main_window.rst
  docs/source/tutorials/python_in_mantid/plotting/01_basic_plot_scripting.rst
  docs/source/tutorials/python_in_mantid/solutions/02_pim_sol.rst
  docs/source/tutorials/python_in_mantid/solutions/03_pim_sol.rst
Labels: Documentation, ISIS Team: Core

#37255 Make Muon Analysis fitting code safer
  docs/source/release/v6.10.0/Muon/Muon_Analysis/Bugfixes/37255.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/general_fitting/general_fitting_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_model.py
  qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/general_fitting/general_fitting_model_test.py
  qt/scientific_interfaces/Inelastic/QENSFitting/FitDataModel.cpp
  qt/widgets/common/src/AlgorithmRunner.cpp
  qt/widgets/common/src/QtAlgorithmRunner.cpp
  qt/widgets/common/src/QtJobRunner.cpp
Labels: Bug, Muon, ISIS Team: Spectroscopy

#37279 Fix casting warnings in core team code
  Framework/DataHandling/src/LoadRawHelper.cpp
  Framework/DataHandling/src/SaveISISNexus.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: High Priority, Maintenance, ISIS Team: Core

#37280 resolving cpp check warnings diffraction
  Framework/Crystal/inc/MantidCrystal/FindSXPeaksHelper.h
  Framework/Crystal/src/FindSXPeaks.cpp
  Framework/Crystal/src/FindSXPeaksHelper.cpp
Labels: High Priority, Diffraction, ISIS Team: Diffraction

#37273 Loading LeanPeaksWorkspace loses peak shapes
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  Framework/DataHandling/test/LoadNexusProcessedTest.h
  Testing/Data/UnitTest/SingleCrystalLeanElasticPeakTable.nxs.md5
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.10.0/Diffraction/Single_Crystal/Bugfixes/37273.rst
Labels: Diffraction, Single Crystal, Framework

#37285 Fix compiler warning in HeliumAnalyserEfficiencyTest
  Framework/Algorithms/test/PolarizationCorrections/HeliumAnalyserEfficiencyTest.h
Labels: SANS, ISIS Team: LSS

#37268 Support saving a multi-dataset ORSO file from the ISIS Reflectometry GUI
  Framework/PythonInterface/plugins/algorithms/SaveISISReflectometryORSO.py
  Framework/PythonInterface/test/python/plugins/algorithms/SaveISISReflectometryORSOTest.py
  Testing/Data/UnitTest/ISISReflectometry/batch.json.md5
  Testing/Data/UnitTest/ISISReflectometry/batch_POLREF.json.md5
  Testing/Data/UnitTest/ISISReflectometry/batch_previous.json.md5
  Testing/Data/UnitTest/ISISReflectometry/batch_with_save_rows_box_POLREF.json.md5
  dev-docs/source/Testing/ReflectometryGUI/ReflectometryGUITests.rst
  docs/source/algorithms/SaveISISReflectometryORSO-v1.rst
  docs/source/images/ISISReflectometryInterface/save_tab.png
  docs/source/interfaces/reflectometry/ISIS Reflectometry.rst
  docs/source/release/v6.10.0/Reflectometry/New_features/36396.rst
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Common/Decoder.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Common/Encoder.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/AsciiSaver.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/AsciiSaver.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/IAsciiSaver.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/IAsciiSaver.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/ISaveAlgorithmRunner.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/ISavePresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/ISaveView.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/QtSaveView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/QtSaveView.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/SaveAlgorithmRunner.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/SaveAlgorithmRunner.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/SavePresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/SavePresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/SaveWidget.ui
  qt/scientific_interfaces/ISISReflectometry/test/Batch/BatchJobManagerWorkspacesTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Batch/BatchPresenterTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Common/CoderCommonTester.h
  qt/scientific_interfaces/ISISReflectometry/test/Common/DecoderTest.h
  qt/scientific_interfaces/ISISReflectometry/test/ReflMockObjects.h
  qt/scientific_interfaces/ISISReflectometry/test/Save/AsciiSaverTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Save/MockSaveAlgorithmRunner.h
  qt/scientific_interfaces/ISISReflectometry/test/Save/MockSaveView.h
  qt/scientific_interfaces/ISISReflectometry/test/Save/SavePresenterTest.h
Labels: Reflectometry, ISIS Team: LSS

#37284 Remove build warnings on some indirect classes
  Framework/DataHandling/src/LoadBankFromDiskTask.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionBrowser/ConvFunctionTemplateModel.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionBrowser/ConvFunctionTemplateModel.h
  qt/widgets/common/inc/MantidQtWidgets/Common/TableWidgetValidators.h
  qt/widgets/common/src/EditLocalParameterDialog.cpp
  qt/widgets/common/src/TableWidgetValidators.cpp
  qt/widgets/common/src/WorkspaceUtils.cpp
Labels: Maintenance, ISIS Team: Spectroscopy

#37272 Fix a bug in the pairings table of the Muon Analysis interface
  docs/source/release/v6.10.0/Muon/Muon_Analysis/Bugfixes/37254.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/difference_table_widget/difference_table_widget_view.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/pairing_table_widget/pairing_table_widget_view.py
  qt/python/mantidqtinterfaces/test/Muon/grouping_tab/difference_table_selector_test.py
Labels: Bug, Muon, ISIS Team: Spectroscopy

#37276 Remove unused code and explicitly cast to double
  Framework/DataObjects/inc/MantidDataObjects/MortonIndex/WideInt.h
  Framework/DataObjects/inc/MantidDataObjects/MortonIndex/WideIntImpl.h
  Framework/DataObjects/test/MDLeanEventTest.h
  mantid-developer-osx.yml
  qt/widgets/common/test/AlgorithmRunnerTest.h
Labels: High Priority, DevOps

#37287 Add missing documentation
  Framework/DataHandling/src/LoadBankFromDiskTask.cpp
  docs/source/api/python/mantid/kernel/PropertyManagerProperty.rst
  docs/source/concepts/PropertiesFile.rst
Labels: Documentation

#37302 Treat Doxygen warnings as errors
  Framework/Doxygen/Mantid_template.doxyfile
Labels: High Priority, Maintenance, DevOps

#37297 Improve the disable usage reporting dialogue
  qt/applications/workbench/workbench/widgets/about/usage_verification_view.py
Labels: ISIS Team: Core

#37303 Only add new extents on SliceViewerDataView if requested
  qt/python/mantidqt/mantidqt/widgets/regionselector/view.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_dataview.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/views/dataview.py
Labels: Reflectometry, ISIS Team: LSS

#37289 Add ORSO Nexus save option to ISIS Reflectometry GUI
  Framework/PythonInterface/mantid/utils/reflectometry/orso_helper.py
  Framework/PythonInterface/plugins/algorithms/SaveISISReflectometryORSO.py
  Framework/PythonInterface/test/python/mantid/utils/reflectometry/orso_helper_test.py
  Framework/PythonInterface/test/python/plugins/algorithms/SaveISISReflectometryORSOTest.py
  dev-docs/source/Testing/ReflectometryGUI/ReflectometryGUITests.rst
  docs/source/algorithms/SaveISISReflectometryORSO-v1.rst
  docs/source/images/ISISReflectometryInterface/save_tab.png
  docs/source/interfaces/reflectometry/ISIS Reflectometry.rst
  docs/source/release/v6.10.0/Reflectometry/New_features/37162.rst
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/QtBatchView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/AsciiSaver.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/IAsciiSaver.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/IAsciiSaver.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/SavePresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Save/SaveWidget.ui
  qt/scientific_interfaces/ISISReflectometry/test/Save/AsciiSaverTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Save/SavePresenterTest.h
Labels: Reflectometry, ISIS Team: LSS

#37243 Add information about run numbers for multiple file reduction in Indirect Energy Transfer algorithm
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/OSIRISDiffractionReduction.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ISISIndirectDiffractionReductionTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransferTest.py
  docs/source/release/v6.10.0/Indirect/New_features/36850.rst
  scripts/Inelastic/IndirectReductionCommon.py
Labels: ISIS Team: Spectroscopy

#37304 Updates error reporter manual testing instructions
  dev-docs/source/Testing/ErrorReporter-ProjectRecovery/ErrorReporterTesting.rst
Labels: Documentation, Maintenance, ISIS Team: Core

#37247 Specify input workspace flipper configuration order
  Framework/Algorithms/inc/MantidAlgorithms/PolarizationCorrectionWildes.h
  Framework/Algorithms/inc/MantidAlgorithms/PolarizationCorrections/SpinStateValidator.h
  Framework/Algorithms/src/PolarizationCorrectionWildes.cpp
  Framework/Algorithms/src/PolarizationCorrections/PolarizationCorrectionsHelpers.cpp
  Framework/Algorithms/src/PolarizationCorrections/SpinStateValidator.cpp
  Framework/Algorithms/test/PolarizationCorrectionWildesTest.h
  Framework/Algorithms/test/PolarizationCorrections/SpinStateValidatorTest.h
  docs/source/release/v6.10.0/Framework/Algorithms/New_features/35067.rst
Labels: Reflectometry, SANS, ISIS Team: LSS

#37307 Pin libcxx in Conda recipes
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid/meta.yaml
  conda/recipes/mantidqt/meta.yaml
Labels: High Priority, DevOps

#37305 New FindGoniometerAngles algorithm
  Framework/Crystal/CMakeLists.txt
  Framework/Crystal/inc/MantidCrystal/FindGoniometerAngles.h
  Framework/Crystal/src/FindGoniometerAngles.cpp
  Framework/Crystal/test/FindGoniometerAnglesTest.h
  docs/source/algorithms/FindGoniometerAngles-v1.rst
  docs/source/release/v6.10.0/Diffraction/Single_Crystal/New_features/37305.rst
Labels: Single Crystal

#37313 Add documentation for registering algorithms in external projects with AlgorithmFactory
  dev-docs/source/PythonAlgorithmsInExternalProjects.rst
  dev-docs/source/PythonVSCppAlgorithms.rst
  dev-docs/source/index.rst
Labels: Documentation

#37315 Fix crash on drag overplot using table workspace
  docs/source/release/v6.10.0/Workbench/Bugfixes/37315.rst
  qt/applications/workbench/workbench/plotting/figurewindow.py
Labels: Bug, ISIS Team: Core, Reported By User

#37270 updated eng diff testing instructions
  dev-docs/source/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.rst
Labels: Diffraction, Documentation, Maintenance, ISIS Team: Diffraction

#37263 32679 fixed FindPeaks crash when the number of bins are not sufficient
  Framework/Algorithms/src/FindPeaks.cpp
  Framework/Algorithms/test/FindPeaksTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.10.0/Framework/Algorithms/Bugfixes/32679.rst
Labels: Bug, Diffraction, ISIS Team: Diffraction

#37318 6.11 release notes skeleton
  docs/source/release/index.rst
  docs/source/release/v6.11.0/Diffraction/Engineering/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Diffraction/Engineering/New_features/.gitkeep
  docs/source/release/v6.11.0/Diffraction/Powder/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Diffraction/Powder/New_features/.gitkeep
  docs/source/release/v6.11.0/Diffraction/Single_Crystal/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Diffraction/Single_Crystal/New_features/.gitkeep
  docs/source/release/v6.11.0/Direct_Geometry/CrystalField/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Direct_Geometry/CrystalField/New_features/.gitkeep
  docs/source/release/v6.11.0/Direct_Geometry/General/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Direct_Geometry/General/New_features/.gitkeep
  docs/source/release/v6.11.0/Direct_Geometry/MSlice/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Direct_Geometry/MSlice/New_features/.gitkeep
  docs/source/release/v6.11.0/Framework/Algorithms/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Framework/Algorithms/New_features/.gitkeep
  docs/source/release/v6.11.0/Framework/Data_Objects/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Framework/Data_Objects/New_features/.gitkeep
  docs/source/release/v6.11.0/Framework/Dependencies/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Framework/Dependencies/New_features/.gitkeep
  docs/source/release/v6.11.0/Framework/Fit_Functions/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Framework/Fit_Functions/New_features/.gitkeep
  docs/source/release/v6.11.0/Framework/Python/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Framework/Python/New_features/.gitkeep
  docs/source/release/v6.11.0/Indirect/Algorithms/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Indirect/Algorithms/New_features/.gitkeep
  docs/source/release/v6.11.0/Indirect/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Indirect/New_features/.gitkeep
  docs/source/release/v6.11.0/Inelastic/Algorithms/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Inelastic/Algorithms/New_features/.gitkeep
  docs/source/release/v6.11.0/Inelastic/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Inelastic/New_features/.gitkeep
  docs/source/release/v6.11.0/Muon/ALC/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Muon/Algorithms/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Muon/Elemental_Analysis/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Muon/FDA/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Muon/MA_FDA/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Muon/Muon_Analysis/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Reflectometry/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Reflectometry/New_features/.gitkeep
  docs/source/release/v6.11.0/SANS/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/SANS/New_features/.gitkeep
  docs/source/release/v6.11.0/Workbench/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Workbench/InstrumentViewer/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Workbench/InstrumentViewer/New_features/.gitkeep
  docs/source/release/v6.11.0/Workbench/New_features/.gitkeep
  docs/source/release/v6.11.0/Workbench/SliceViewer/Bugfixes/.gitkeep
  docs/source/release/v6.11.0/Workbench/SliceViewer/New_features/.gitkeep
  docs/source/release/v6.11.0/diffraction.rst
  docs/source/release/v6.11.0/direct_geometry.rst
  docs/source/release/v6.11.0/framework.rst
  docs/source/release/v6.11.0/index.rst
  docs/source/release/v6.11.0/indirect_geometry.rst
  docs/source/release/v6.11.0/inelastic.rst
  docs/source/release/v6.11.0/mantidworkbench.rst
  docs/source/release/v6.11.0/muon.rst
  docs/source/release/v6.11.0/reflectometry.rst
  docs/source/release/v6.11.0/sans.rst
Labels: Documentation

#37187 New IDAaaS data cache index file loading
  Framework/API/CMakeLists.txt
  Framework/API/inc/MantidAPI/FileFinder.h
  Framework/API/inc/MantidAPI/ISISInstrumentDataCache.h
  Framework/API/src/FileFinder.cpp
  Framework/API/src/ISISInstrumentDataCache.cpp
  Framework/API/test/FileFinderTest.h
  Framework/API/test/ISISInstrumentDataCacheTest.h
  Framework/Properties/Mantid.properties.template
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/concepts/PropertiesFile.rst
  docs/source/release/v6.10.0/Framework/Data_Handling/Bugfixes/.gitkeep
  docs/source/release/v6.10.0/Framework/Data_Handling/New_features/.gitkeep
  docs/source/release/v6.10.0/Framework/Data_Handling/New_features/37013.rst
  docs/source/release/v6.10.0/framework.rst
Labels: ISIS Team: Core

#37317 Pass Data Manipulation Models into Presenters
  qt/scientific_interfaces/Inelastic/Manipulation/DataManipulation.h
  qt/scientific_interfaces/Inelastic/Manipulation/DataManipulationInterface.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/DataManipulationInterface.h
  qt/scientific_interfaces/Inelastic/Manipulation/ElwinPresenter.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/ElwinPresenter.h
  qt/scientific_interfaces/Inelastic/Manipulation/ElwinView.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/IqtModel.h
  qt/scientific_interfaces/Inelastic/Manipulation/IqtPresenter.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/IqtPresenter.h
  qt/scientific_interfaces/Inelastic/Manipulation/IqtView.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/MomentsModel.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/MomentsModel.h
  qt/scientific_interfaces/Inelastic/Manipulation/MomentsPresenter.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/MomentsPresenter.h
  qt/scientific_interfaces/Inelastic/Manipulation/MomentsView.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/SqwModel.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/SqwModel.h
  qt/scientific_interfaces/Inelastic/Manipulation/SqwPresenter.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/SqwPresenter.h
  qt/scientific_interfaces/Inelastic/Manipulation/SqwView.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/SymmetriseModel.h
  qt/scientific_interfaces/Inelastic/Manipulation/SymmetrisePresenter.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/SymmetrisePresenter.h
  qt/scientific_interfaces/Inelastic/Manipulation/SymmetriseView.cpp
Labels: Indirect/Inelastic, Maintenance, ISIS Team: Spectroscopy

#37320 Add documentation for build_packages_from_branch jenkins job
  dev-docs/source/Packaging.rst
Labels: Documentation, Maintenance

#37319 Add note to Manual Testing instructions about missing wavelength tooltips
  dev-docs/source/Testing/SANSGUI/ISISSANSGUITests.rst
Labels: SANS, Documentation, ISIS Team: LSS

#37227 ISISEnergyTransferPresenter no longer a QObject
  qt/scientific_interfaces/Indirect/Reduction/CMakeLists.txt
  qt/scientific_interfaces/Indirect/Reduction/DataReduction.cpp
  qt/scientific_interfaces/Indirect/Reduction/DataReduction.h
  qt/scientific_interfaces/Indirect/Reduction/DataReductionTab.cpp
  qt/scientific_interfaces/Indirect/Reduction/DataReductionTab.h
  qt/scientific_interfaces/Indirect/Reduction/ILLEnergyTransfer.cpp
  qt/scientific_interfaces/Indirect/Reduction/ILLEnergyTransfer.h
  qt/scientific_interfaces/Indirect/Reduction/ISISCalibration.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISCalibration.h
  qt/scientific_interfaces/Indirect/Reduction/ISISDiagnostics.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISDiagnostics.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModel.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModel.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferPresenter.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferPresenter.h
  qt/scientific_interfaces/Indirect/Reduction/Transmission.cpp
  qt/scientific_interfaces/Indirect/Reduction/Transmission.h
  qt/scientific_interfaces/Indirect/test/Reduction/ISISEnergyTransferModelTest.h
  qt/scientific_interfaces/Indirect/test/Reduction/ISISEnergyTransferPresenterTest.h
  qt/scientific_interfaces/Indirect/test/Reduction/MockObjects.h
Labels: Indirect/Inelastic, Maintenance, ISIS Team: Spectroscopy

#37264 Create QENS Fitting Presenter
  qt/scientific_interfaces/Inelastic/QENSFitting/CMakeLists.txt
  qt/scientific_interfaces/Inelastic/QENSFitting/FitDataPresenter.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FitDataPresenter.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FitOutput.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FitOutput.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FitPlotModel.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FitPlotModel.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FitPlotPresenter.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FitPlotPresenter.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FitTab.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FitTab.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FittingModel.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FittingModel.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FittingPresenter.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FittingPresenter.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FqFitDataPresenter.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FqFitDataPresenter.h
  qt/scientific_interfaces/Inelastic/QENSFitting/IFitOutput.h
  qt/scientific_interfaces/Inelastic/QENSFitting/IFittingModel.h
  qt/scientific_interfaces/Inelastic/QENSFitting/InelasticFitPropertyBrowser.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/InelasticFitPropertyBrowser.h
  qt/scientific_interfaces/Inelastic/QENSFitting/TabFactory.cpp
  qt/scientific_interfaces/Inelastic/test/QENSFitting/CMakeLists.txt
  qt/scientific_interfaces/Inelastic/test/QENSFitting/FitOutputTest.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/FitPlotModelTest.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/FitPlotPresenterTest.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/FittingModelTest.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/FittingPresenterTest.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/FqFitDataPresenterTest.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/MockObjects.h
Labels: Indirect/Inelastic, Maintenance, ISIS Team: Spectroscopy

#37354 Temporary pin for libcxx in env
  mantid-developer-osx.yml
Labels: High Priority, DevOps

#37359 Fix selection and remove crash on elwin tab of Data Manipulation Interface
  docs/source/release/v6.10.0/Inelastic/Bugfixes/37321.rst
  qt/scientific_interfaces/Inelastic/Manipulation/ElwinTab.ui
  qt/scientific_interfaces/Inelastic/Manipulation/ElwinView.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/ElwinView.h
  qt/scientific_interfaces/Inelastic/Manipulation/IElwinView.h
  qt/scientific_interfaces/Inelastic/Manipulation/IIqtView.h
  qt/scientific_interfaces/Inelastic/Manipulation/IMomentsView.h
  qt/scientific_interfaces/Inelastic/Manipulation/ISqwView.h
  qt/scientific_interfaces/Inelastic/Manipulation/ISymmetriseView.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/MockObjects.h
Labels: Bug, ISIS Team: Spectroscopy, Reported By User

#37349 Don't run doc tests if only dev docs have changed
  buildconfig/Jenkins/Conda/conda-buildscript
Labels: Documentation, Maintenance

#37368 Fix output workspace overwriting in ISIS SANS GUI
  docs/source/release/v6.10.0/SANS/Bugfixes/37356.rst
  scripts/SANS/sans/gui_logic/presenter/gui_state_director.py
  scripts/test/SANS/gui_logic/gui_state_director_test.py
Labels: SANS, ISIS Team: LSS

#37383 Update Indirect Interface Manual Testing Docs with missing info
  dev-docs/source/Testing/Indirect/DataReductionTests.rst
  dev-docs/source/Testing/Inelastic/DataManipulationTests.rst
Labels: Indirect/Inelastic, Documentation, Maintenance, ISIS Team: Spectroscopy

#37399 Update Muon testing instructions
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon Analysis Unscripted Testing Guide.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_Analysis_PSI.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_FDA.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_HIFI.rst
Labels: Muon, Documentation, ISIS Team: Spectroscopy

#37380 Error from selecting curves in plot options
  docs/source/release/v6.10.0/Workbench/Bugfixes/37380.rst
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/curvestabwidget/presenter.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/curvestabwidget/test/test_curvestabwidgetpresenter.py
Labels: Bug, ISIS Team: Core, Reported By User

#37395 Fix Muon error when switching to TF Asymmetry fitting
  docs/source/release/v6.10.0/Muon/Muon_Analysis/Bugfixes/37392.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_model.py
  qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_model_test.py
Labels: Bug, Muon, ISIS Team: Spectroscopy

#37397 Prevent crash when self-tie in Inelastic Fit Property Browser
  Framework/API/src/IFunction.cpp
  docs/source/release/v6.10.0/Inelastic/Bugfixes/37360.rst
  qt/scientific_interfaces/Inelastic/QENSFitting/InelasticFitPropertyBrowser.cpp
Labels: Bug, Indirect/Inelastic, ISIS Team: Spectroscopy

#37405 Pin jemalloc to v5.2.0 for install package
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid/meta.yaml
  conda/recipes/mantiddocs/meta.yaml
  conda/recipes/mantidqt/meta.yaml
  conda/recipes/mantidworkbench/meta.yaml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: Bug

#37404 Bug preventing Mantid from processing algorithms from some indirect/inelastic interfaces
  qt/scientific_interfaces/Indirect/Diffraction/DiffractionReduction.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISDiagnostics.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModel.cpp
  qt/scientific_interfaces/Indirect/test/Reduction/ISISEnergyTransferModelTest.h
  qt/scientific_interfaces/Inelastic/Manipulation/SymmetriseModel.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/SymmetriseModel.h
  qt/scientific_interfaces/Inelastic/Manipulation/SymmetrisePresenter.cpp
  qt/scientific_interfaces/Inelastic/test/Manipulation/SymmetriseModelTest.h
Labels: Bug, Indirect/Inelastic, Extra Attention, ISIS Team: Spectroscopy

#37414 Fix coverity scan warnings in Indirect/Inelastic
  qt/scientific_interfaces/Indirect/Diffraction/DiffractionReduction.cpp
  qt/scientific_interfaces/Indirect/Reduction/DataReduction.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FittingPresenter.cpp
Labels: Indirect/Inelastic, Maintenance, ISIS Team: Spectroscopy

#37412 Fix Indirect Data Reduction crash when open/close interface multiple times
  qt/scientific_interfaces/Indirect/Reduction/DataReduction.cpp
  qt/scientific_interfaces/Indirect/Reduction/DataReduction.h
  qt/scientific_interfaces/Inelastic/Common/OutputPlotOptionsPresenter.cpp
  qt/scientific_interfaces/Inelastic/Common/OutputPlotOptionsPresenter.h
  qt/scientific_interfaces/Inelastic/Manipulation/DataManipulationInterface.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/DataManipulationInterface.h
Labels: Bug, Indirect/Inelastic, ISIS Team: Spectroscopy

#37408 Fix bug with log CompressEvents when using WallClockTolerance
  Framework/DataObjects/src/EventList.cpp
  Framework/DataObjects/test/EventListTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Bug

#37419 Add deprecation message to Calculate Paalman Pings to get user feedback
  docs/source/release/v6.10.0/Inelastic/New_features/37419.rst
  qt/scientific_interfaces/Inelastic/Corrections/CalculatePaalmanPings.ui
Labels: Indirect/Inelastic, ISIS Team: Spectroscopy

#37388 Move plotting in FitTab to plot presenter
  qt/scientific_interfaces/Direct/ALFAnalysisView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Common/Plotter.cpp
  qt/scientific_interfaces/Inelastic/Common/OutputPlotOptionsModel.cpp
  qt/scientific_interfaces/Inelastic/Common/OutputPlotOptionsModel.h
  qt/scientific_interfaces/Inelastic/Common/OutputPlotOptionsPresenter.cpp
  qt/scientific_interfaces/Inelastic/Common/OutputPlotOptionsPresenter.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FitOutputOptionsModel.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FitOutputOptionsModel.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FitOutputOptionsPresenter.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FitOutputOptionsPresenter.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FitTab.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FitTab.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FittingModel.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FittingModel.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FittingPresenter.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FittingPresenter.h
  qt/scientific_interfaces/Inelastic/QENSFitting/IFitOutputOptionsModel.h
  qt/scientific_interfaces/Inelastic/QENSFitting/IFittingModel.h
  qt/scientific_interfaces/Inelastic/test/Common/MockObjects.h
  qt/scientific_interfaces/Inelastic/test/Common/OutputPlotOptionsModelTest.h
  qt/scientific_interfaces/Inelastic/test/Common/OutputPlotOptionsPresenterTest.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/FitOutputOptionsModelTest.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/FitOutputOptionsPresenterTest.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/MockObjects.h
  qt/scientific_interfaces/Muon/ALCInterface.cpp
  qt/scientific_interfaces/Muon/ALCInterface.h
  qt/widgets/mplcpp/inc/MantidQtWidgets/MplCpp/Plot.h
  qt/widgets/mplcpp/src/Plot.cpp
  qt/widgets/mplcpp/test/PlotTest.h
  qt/widgets/plotting/CMakeLists.txt
  qt/widgets/plotting/inc/MantidQtWidgets/Plotting/ExternalPlotter.h
  qt/widgets/plotting/inc/MantidQtWidgets/Plotting/MockExternalPlotter.h
  qt/widgets/plotting/src/ExternalPlotter.cpp
  qt/widgets/plotting/src/PlotWidget/QtPlotView.cpp
Labels: Indirect/Inelastic, Maintenance, ISIS Team: Spectroscopy

#37422 Update to v1.4.0 of gha-mjolnir
  .github/workflows/close_issues.yml
Labels: ISIS Team: Core

#37411 Use ADSObserver in ContourPreviewPlot widget
  qt/widgets/plotting/inc/MantidQtWidgets/Plotting/ContourPreviewPlot.h
  qt/widgets/plotting/src/ContourPreviewPlot.cpp
Labels: Bug, Indirect/Inelastic, Maintenance, ISIS Team: Spectroscopy

#37430 Fix bug where all workspaces are excluded in the Elwin interface when "Restrict allowed input files by name" is deselected
  qt/scientific_interfaces/Inelastic/Common/InterfaceUtils.cpp
  qt/scientific_interfaces/Inelastic/test/Common/InterfaceUtilsTest.h
Labels: Bug

#37427 Re-enabled PythonChannelTest
  Testing/SystemTests/tests/framework/PythonChannels.py
Labels: Maintenance

#37431 Only run doctests on Linux in the nightly pipeline
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
Labels: ISIS Team: Core, DevOps

#37436 Increase autoprocessing timeout in ISIS Reflectometry GUI
  docs/source/release/v6.10.0/Reflectometry/New_features/37435.rst
  qt/scientific_interfaces/ISISReflectometry/GUI/Runs/CatalogRunNotifier.h
Labels: Reflectometry, ISIS Team: LSS

#37434 Fix mapping Elwin bool properties
  docs/source/release/v6.10.0/Inelastic/Bugfixes/37434.rst
  qt/scientific_interfaces/Inelastic/Manipulation/ElwinPresenter.cpp
  qt/scientific_interfaces/Inelastic/test/Manipulation/ElwinPresenterTest.h
Labels: Bug

#37443 Fix segfault in LoadEventNexus when CompressTolerance=0
  Framework/DataHandling/src/DefaultEventLoader.cpp
  Framework/DataHandling/src/LoadBankFromDiskTask.cpp
  Framework/DataHandling/test/LoadEventNexusTest.h
Labels: High Priority, Bug
