Repository mantidproject/mantid, pull requests merged in 2024-02, with the labels that each got.

#36788 Update colormap docs
  docs/source/plotting/index.rst
Labels: Documentation, Maintenance, ISIS Team: Core

#36798 Clone extracted IFunction to separate from python object
  Framework/API/inc/MantidAPI/AlgorithmManager.h
  Framework/API/src/AlgorithmManager.cpp
  Framework/PythonInterface/mantid/api/src/Exports/IFunction.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.9.0/Muon/Muon_Analysis/Bugfixes/36785.rst
Labels: High Priority, Bug

#36674 Add plugin dll directory to windows path
  installers/conda/win/sitecustomize.py
  qt/scientific_interfaces/Inelastic/CMakeLists.txt
Labels: ISIS Team: Spectroscopy, ISIS Team: Core, Dependencies

#36776 Add measurement files metadata to ISIS Reflectometry ORSO file
  Framework/PythonInterface/mantid/utils/reflectometry/orso_helper.py
  Framework/PythonInterface/plugins/algorithms/SaveISISReflectometryORSO.py
  Framework/PythonInterface/test/python/mantid/utils/reflectometry/orso_helper_test.py
  Framework/PythonInterface/test/python/plugins/algorithms/SaveISISReflectometryORSOTest.py
  docs/source/algorithms/SaveISISReflectometryORSO-v1.rst
  docs/source/release/v6.10.0/Reflectometry/New_features/36395.rst
Labels: Reflectometry, ISIS Team: LSS

#36787 Update numpy to 1.23 minimum
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/DirectILLAutoProcess.py
  conda/recipes/conda_build_config.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/test/test_apply_all_properties.py
Labels: Maintenance, ISIS Team: Core

#36754 Improve the SANS Manual Testing Documentation
  dev-docs/source/Testing/SANSGUI/ISISSANSGUITests.rst
Labels: Documentation, Maintenance, GUI

#36818 EventList generate unsorted histogram apply divisor as multiplicative factor
  Framework/DataObjects/inc/MantidDataObjects/EventList.h
  Framework/DataObjects/src/EventList.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: ORNL Team

#36823 Quiet down warnings in StepScanAnalysis
  Framework/Algorithms/src/SumEventsByLogValue.cpp
  Testing/SystemTests/tests/framework/StepScan.py
Labels: Framework, Manual Tests

#36807 Unpin python in publish-anaconda
  buildconfig/Jenkins/Conda/publish-to-anaconda
Labels: Maintenance

#36830 Fix Workspace Calculator Incorrectly Scaling the RHS if both the LHS and RHS Are the Same
  docs/source/release/v6.10.0/Workbench/Bugfixes/36827.rst
  qt/python/mantidqt/mantidqt/widgets/workspacecalculator/model.py
  qt/python/mantidqt/mantidqt/widgets/workspacecalculator/test/test_workspacecalculator_model.py
Labels: Bug, GUI, ISIS Team: LSS

#36814 Cleanup direct geometry release notes
  docs/source/release/v6.9.0/direct_geometry.rst
Labels: Documentation

#36821 Leave Q resolution column unit blank in ISIS Reflectometry ORSO file header
  Framework/PythonInterface/mantid/utils/reflectometry/orso_helper.py
  Framework/PythonInterface/plugins/algorithms/SaveISISReflectometryORSO.py
  Framework/PythonInterface/test/python/mantid/utils/reflectometry/orso_helper_test.py
  Framework/PythonInterface/test/python/plugins/algorithms/SaveISISReflectometryORSOTest.py
Labels: Reflectometry, ISIS Team: LSS

#36825 Fix freeze when deleting ws with muon analysis open
  docs/source/release/v6.10.0/Muon/Muon_Analysis/Bugfixes/36824.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_presenter.py
  qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_presenter_test.py
  qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_presenter_test.py
Labels: Bug, Muon, ISIS Team: Spectroscopy

#36822 Cleanup muon release notes
  docs/source/release/v6.9.0/Muon/Muon_Analysis/Bugfixes/Used/36785.rst
  docs/source/release/v6.9.0/muon.rst
Labels: Documentation

#36810 Improve error messages in CreateDetectorTable algorithm
  Framework/Algorithms/src/CreateDetectorTable.cpp
Labels: Maintenance, Framework

#36817 Add manual testing instructions for Filter Events interface
  dev-docs/source/Testing/Utility/FilterEventsInterfaceTest.rst
  dev-docs/source/Testing/index.rst
Labels: Documentation, Maintenance, Manual Tests

#36799 Move common functions used in Inelastic/Indirect tabs to separate files
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/IndirectFitDataCreationHelper.h
  Framework/TestHelpers/src/IndirectFitDataCreationHelper.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  qt/scientific_interfaces/Indirect/Reduction/ISISCalibration.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISDiagnostics.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModel.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModelUtils.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferPresenter.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferValidator.cpp
  qt/scientific_interfaces/Indirect/Reduction/IndirectDataReduction.h
  qt/scientific_interfaces/Indirect/Reduction/IndirectDataReductionTab.cpp
  qt/scientific_interfaces/Indirect/test/Reduction/ISISEnergyTransferModelUtilsTest.h
  qt/scientific_interfaces/Inelastic/Analysis/ConvFitAddWorkspaceDialog.cpp
  qt/scientific_interfaces/Inelastic/Analysis/IndirectDataAnalysisTab.cpp
  qt/scientific_interfaces/Inelastic/Analysis/IndirectFitDataView.cpp
  qt/scientific_interfaces/Inelastic/BayesFitting/Quasi.cpp
  qt/scientific_interfaces/Inelastic/BayesFitting/ResNorm.cpp
  qt/scientific_interfaces/Inelastic/BayesFitting/Stretch.cpp
  qt/scientific_interfaces/Inelastic/CMakeLists.txt
  qt/scientific_interfaces/Inelastic/Common/IndirectTab.cpp
  qt/scientific_interfaces/Inelastic/Common/IndirectTab.h
  qt/scientific_interfaces/Inelastic/Common/InterfaceUtils.cpp
  qt/scientific_interfaces/Inelastic/Common/InterfaceUtils.h
  qt/scientific_interfaces/Inelastic/Common/WorkspaceUtils.cpp
  qt/scientific_interfaces/Inelastic/Common/WorkspaceUtils.h
  qt/scientific_interfaces/Inelastic/Corrections/AbsorptionCorrections.cpp
  qt/scientific_interfaces/Inelastic/Corrections/ApplyAbsorptionCorrections.cpp
  qt/scientific_interfaces/Inelastic/Corrections/CalculatePaalmanPings.cpp
  qt/scientific_interfaces/Inelastic/Corrections/ContainerSubtraction.cpp
  qt/scientific_interfaces/Inelastic/Corrections/CorrectionsTab.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulation.h
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationElwinTab.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationElwinTabView.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationIqtTab.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationMomentsTab.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationSqwTab.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationSqwTabModel.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationSqwTabModel.h
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationSymmetriseTab.cpp
  qt/scientific_interfaces/Inelastic/Manipulation/InelasticDataManipulationSymmetriseTabView.cpp
  qt/scientific_interfaces/Inelastic/test/CMakeLists.txt
  qt/scientific_interfaces/Inelastic/test/Common/InterfaceUtilsTest.h
  qt/scientific_interfaces/Inelastic/test/Common/WorkspaceUtilsTest.h
  qt/widgets/common/inc/MantidQtWidgets/Common/ParseKeyValueString.h
  qt/widgets/common/src/ParseKeyValueString.cpp
Labels: Indirect/Inelastic, Maintenance, ISIS Team: Spectroscopy

#36815 Cleanup release notes for the diffraction area
  docs/source/images/6_9_release/Diffraction/integrate_peaks_shoebox_tof.png
  docs/source/images/6_9_release/Diffraction/slices_symmetrised_mdhisto.png
  docs/source/release/v6.9.0/diffraction.rst
Labels: Documentation

#36826 Cleanup reflectometry release notes
  docs/source/images/6_9_release/Reflectometry/SaveISISReflectometryORSO.png
  docs/source/release/v6.9.0/reflectometry.rst
Labels: Documentation

#36832 Clean up Indirect release notes
  docs/source/images/6_9_release/Indirect/indirect_option_visibility.png
  docs/source/release/v6.9.0/indirect_geometry.rst
Labels: Documentation

#36828 Cleanup SANS release notes
  docs/source/images/6_9_release/SANS/ISIS_SANS_2D_disable_SaveCanSAS1D.png
  docs/source/images/6_9_release/SANS/ISIS_SANS_beam_centre_finder.png
  docs/source/release/v6.9.0/sans.rst
Labels: Documentation

#36820 Cleanup workbench release notes
  docs/source/images/6_9_release/Workbench/CollapsibleStack.gif
  docs/source/release/v6.9.0/mantidworkbench.rst
Labels: Documentation

#36811 Update muon manual testing instructions
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon Analysis Unscripted Testing Guide.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_Analysis_MUSR.rst
  dev-docs/source/Testing/MuonAnalysis_test_guides/Muon_EMU.rst
  docs/source/interfaces/muon/Feature Flags.rst
Labels: Muon, Documentation, ISIS Team: Spectroscopy

#36831 Increase maximum compatible numpy
  conda/recipes/mantid/meta.yaml
  docs/source/release/v6.10.0/Framework/Dependencies/New_features/36831.rst
Labels: ISIS Team: Core, Dependencies

#36840 Modify atexit function so the ADS is always available
  Framework/PythonInterface/mantid/api/src/Exports/AnalysisDataService.cpp
Labels: Bug

#36833 Clean up Inelastic release notes
  docs/source/images/6_9_release/Inelastic/open_slice_viewer_option.png
  docs/source/interfaces/indirect/Indirect Data Reduction.rst
  docs/source/interfaces/indirect/Indirect Diffraction.rst
  docs/source/interfaces/indirect/Indirect Settings.rst
  docs/source/interfaces/indirect/Indirect Simulation.rst
  docs/source/interfaces/indirect/Indirect Tools.rst
  docs/source/interfaces/inelastic/Inelastic Bayes Fitting.rst
  docs/source/interfaces/inelastic/Inelastic Corrections.rst
  docs/source/interfaces/inelastic/Inelastic Data Analysis.rst
  docs/source/interfaces/inelastic/Inelastic Data Manipulation.rst
  docs/source/release/v4.1.0/indirect_geometry.rst
  docs/source/release/v6.9.0/Inelastic/New_features/Used/36533.rst
  docs/source/release/v6.9.0/inelastic.rst
Labels: Documentation

#36846 Fix missing inelastic interface screenshots
  docs/source/images/Inelastic_Data_Analysis_GUI.png
  docs/source/interfaces/indirect/Indirect Data Reduction.rst
  docs/source/interfaces/indirect/Indirect Settings.rst
  docs/source/interfaces/inelastic/Inelastic Bayes Fitting.rst
  docs/source/interfaces/inelastic/Inelastic Corrections.rst
  docs/source/interfaces/inelastic/Inelastic Data Analysis.rst
  docs/source/interfaces/inelastic/Inelastic Data Manipulation.rst
  qt/scientific_interfaces/Inelastic/Common/IndirectInterface.cpp
Labels: Indirect/Inelastic, Documentation, ISIS Team: Spectroscopy

#36784 Inelastic Template presenters are no longer QObjects
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  qt/scientific_interfaces/Inelastic/Analysis/DataAnalysisTabFactory.cpp
  qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvTemplateBrowser.cpp
  qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvTemplateBrowser.h
  qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvTemplatePresenter.cpp
  qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ConvTemplatePresenter.h
  qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/FunctionTemplatePresenter.cpp
  qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/FunctionTemplatePresenter.h
  qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/ITemplatePresenter.h
  qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/IqtTemplateBrowser.cpp
  qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/IqtTemplateBrowser.h
  qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/IqtTemplatePresenter.cpp
  qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/IqtTemplatePresenter.h
  qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/SingleFunctionTemplateBrowser.cpp
  qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/SingleFunctionTemplateBrowser.h
  qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/SingleFunctionTemplatePresenter.cpp
  qt/scientific_interfaces/Inelastic/Analysis/FunctionBrowser/SingleFunctionTemplatePresenter.h
  qt/scientific_interfaces/Inelastic/Analysis/FunctionTemplateBrowser.cpp
  qt/scientific_interfaces/Inelastic/Analysis/FunctionTemplateBrowser.h
  qt/scientific_interfaces/Inelastic/Analysis/IndirectDataAnalysisTab.h
  qt/scientific_interfaces/Inelastic/Analysis/IndirectFitPropertyBrowser.cpp
  qt/scientific_interfaces/Inelastic/Analysis/IndirectFitPropertyBrowser.h
  qt/scientific_interfaces/Inelastic/CMakeLists.txt
  qt/scientific_interfaces/Inelastic/test/Analysis/IndirectFitPropertyBrowserTest.h
  qt/scientific_interfaces/Inelastic/test/Analysis/MockObjects.h
  qt/widgets/common/inc/MantidQtWidgets/Common/EditLocalParameterDialog.h
  qt/widgets/common/src/EditLocalParameterDialog.cpp
Labels: Indirect/Inelastic, Maintenance, ISIS Team: Spectroscopy

#36845 Documentation manual testing
  dev-docs/source/Testing/Documentation/DocumentationTest.rst
  dev-docs/source/Testing/index.rst
  tools/scripts/OpenMostDocumentationForTesting.py
Labels: Documentation, Maintenance, Manual Tests

#36857 Update sha after beta testing
  docs/source/release/v6.9.0/Direct_Geometry/MSlice/Bugfixes/36857.rst
  scripts/ExternalInterfaces/CMakeLists.txt
Labels: High Priority, Bug, Found in Beta, ISIS Team: Excitations/Vesuvio

#36858 Add missing release note for MSlice bug fix
  docs/source/release/v6.9.0/Direct_Geometry/MSlice/Bugfixes/Used/36857.rst
  docs/source/release/v6.9.0/direct_geometry.rst
Labels: Documentation

#36686 Allow cmake version > 3.27
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: Maintenance, ISIS Team: Excitations/Vesuvio

#36856 Write index release note page for v6.9
  docs/source/images/6_9_release/MajorChanges.png
  docs/source/release/v6.9.0/index.rst
Labels: Documentation

#36855 Update technical release manager smoke testing instructions
  dev-docs/source/ReleaseChecklist.rst
Labels: Documentation, ISIS Team: Core

#36859 Change project recovery to save one recovery script rather than one for each workspace
  docs/source/release/v6.9.0/mantidworkbench.rst
  qt/applications/workbench/workbench/projectrecovery/projectrecoveryloader.py
  qt/applications/workbench/workbench/projectrecovery/projectrecoverysaver.py
  qt/applications/workbench/workbench/projectrecovery/recoverygui/projectrecoverymodel.py
  qt/applications/workbench/workbench/projectrecovery/recoverygui/test/test_projectrecoverymodel.py
  qt/applications/workbench/workbench/projectrecovery/test/test_projectrecoveryloader.py
  qt/applications/workbench/workbench/projectrecovery/test/test_projectrecoverysaver.py
  qt/applications/workbench/workbench/utils/workspacehistorygeneration.py
  qt/python/mantidqt/mantidqt/widgets/codeeditor/multifileinterpreter.py
Labels: ISIS Team: Core, Reported By User

#36848 Fix bug in averageValueInFilter
  Framework/Kernel/inc/MantidKernel/FilteredTimeSeriesProperty.h
  Framework/Kernel/src/FilteredTimeSeriesProperty.cpp
  Framework/Kernel/test/FilteredTimeSeriesPropertyTest.h
  Framework/PythonInterface/test/python/mantid/kernel/FilteredTimeSeriesPropertyTest.py
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.9.0/Framework/Data_Handling/Bugfixes/36848.rst
Labels: Bug, ORNL Team

#36803 Fix Muon crash when adding function with no data selected
  docs/source/release/v6.10.0/Muon/Muon_Analysis/Bugfixes/36801.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/contexts/fitting_contexts/basic_fitting_context.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/contexts/fitting_contexts/general_fitting_context.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/contexts/fitting_contexts/model_fitting_context.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/model_fitting/model_fitting_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/model_fitting/model_fitting_presenter.py
  qt/python/mantidqtinterfaces/test/Muon/basic_fitting_context_test.py
  qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_model_test.py
  qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_presenter_test.py
  qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/general_fitting/general_fitting_model_test.py
  qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/model_fitting/model_fitting_model_test.py
  qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/tf_asymmetry_fitting/tf_asymmetry_fitting_presenter_test.py
  qt/python/mantidqtinterfaces/test/Muon/general_fitting_context_test.py
  qt/python/mantidqtinterfaces/test/Muon/model_fitting_context_test.py
Labels: Bug, Muon, ISIS Team: Spectroscopy

#36862 Move release note into main framework release note file
  docs/source/release/v6.9.0/Framework/Data_Handling/Bugfixes/Used/36848.rst
  docs/source/release/v6.9.0/framework.rst
  docs/source/release/v6.9.0/mantidworkbench.rst
Labels: Documentation

#36861 Add 'NGroups' property to ISISIndirectEnergyTransfer algorithm
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransfer.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransferTest.py
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.10.0/Indirect/Algorithms/New_features/36861.rst
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModel.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModel.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModelUtils.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferValidator.cpp
  qt/scientific_interfaces/Indirect/test/Reduction/ISISEnergyTransferModelTest.h
  qt/scientific_interfaces/Indirect/test/Reduction/ISISEnergyTransferModelUtilsTest.h
  scripts/Inelastic/IndirectReductionCommon.py
  scripts/test/CMakeLists.txt
  scripts/test/IndirectReductionCommonTest.py
Labels: Indirect/Inelastic, Maintenance, ISIS Team: Spectroscopy

#36806 Fix load current run for MUSR in Muon Analysis
  Framework/API/inc/MantidAPI/Algorithm.h
  Framework/API/inc/MantidAPI/LogManager.h
  Framework/API/src/LogManager.cpp
  Framework/DataHandling/src/ISISRunLogs.cpp
  Framework/DataHandling/test/LoadNexusLogsTest.h
  Framework/Kernel/inc/MantidKernel/IPropertyManager.h
  Framework/Kernel/inc/MantidKernel/PropertyManager.h
  Framework/Kernel/inc/MantidKernel/PropertyManagerOwner.h
  Framework/Kernel/src/PropertyManager.cpp
  Framework/Kernel/test/PropertyManagerTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.10.0/Muon/Muon_Analysis/Bugfixes/36800.rst
  qt/python/mantidqt/mantidqt/utils/asynchronous.py
  qt/python/mantidqt/mantidqt/widgets/samplelogs/test/test_samplelogs_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/load_file_widget/presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/load_run_widget/load_run_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/load_run_widget/load_run_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/utilities/load_utils.py
Labels: Bug, Muon, ISIS Team: Spectroscopy

#36895 Increase auto-processing timeout in ISIS Reflectometry GUI
  qt/scientific_interfaces/ISISReflectometry/GUI/Runs/CatalogRunNotifier.h
Labels: High Priority, Reflectometry, ISIS Team: LSS

#36896 Add release note for project recovery improvement
  docs/source/release/v6.9.0/mantidworkbench.rst
Labels: High Priority, Documentation

#36854 35646 fixing a memory leak when loading nexus files
  Framework/Kernel/src/NexusHDF5Descriptor.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.10.0/Workbench/Bugfixes/35646.rst
  qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidget.cpp
Labels: Bug, Maintenance, Reported By User

#36904 Fix spelling mistake in UserFunctionDialog.cpp
  qt/widgets/common/src/UserFunctionDialog.cpp
Labels: Bug

#36757 Ability to have File/Groups/Custom detector grouping in Indirect Diffraction algo
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectDiffractionReduction.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransfer.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ISISIndirectDiffractionReductionTest.py
  Testing/Data/UnitTest/vesuvio_4_by_24.map.md5
  docs/source/release/v6.10.0/Indirect/Algorithms/New_features/36761.rst
Labels: Indirect/Inelastic, ISIS Team: Spectroscopy

#36910 Removed pre-setup of IDAaaS instances from release checklist
  dev-docs/source/ReleaseChecklist.rst
Labels: Documentation, Maintenance

#36914 Provide compatibility for backups pre-6.9
  docs/source/release/v6.9.0/mantidworkbench.rst
  qt/applications/workbench/workbench/projectrecovery/projectrecoveryloader.py
Labels: High Priority, Bug, ISIS Team: Core

#36915 Pass spectra_range to the group_spectra function
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectDiffractionReduction.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransfer.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ISISIndirectDiffractionReductionTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransferTest.py
  docs/source/release/v6.10.0/Indirect/Bugfixes/36915.rst
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferValidator.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferValidator.h
  scripts/Inelastic/IndirectReductionCommon.py
  scripts/test/IndirectReductionCommonTest.py
Labels: Bug, Indirect/Inelastic, ISIS Team: Spectroscopy

#36894 Extract detector grouping options from Indirect Data Reduction
  Framework/API/inc/MantidAPI/AlgorithmRuntimeProps.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/interfaces/indirect/Indirect Data Reduction.rst
  qt/scientific_interfaces/Indirect/CMakeLists.txt
  qt/scientific_interfaces/Indirect/Common/DetectorGroupingOptions.cpp
  qt/scientific_interfaces/Indirect/Common/DetectorGroupingOptions.h
  qt/scientific_interfaces/Indirect/Common/DetectorGroupingOptions.ui
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransfer.ui
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferData.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModel.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModel.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferPresenter.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferPresenter.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferValidator.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferValidator.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferView.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferView.h
  qt/scientific_interfaces/Indirect/test/Reduction/ISISEnergyTransferModelTest.h
Labels: Indirect/Inelastic, Maintenance, ISIS Team: Spectroscopy

#36929 Fix failing doctest due to orso standard version changing
  docs/source/algorithms/SaveISISReflectometryORSO-v1.rst
Labels: High Priority, Reflectometry, Documentation, ISIS Team: LSS, Added during Sprint

#36912 Initialise background colour in projection surface
  docs/source/release/v6.10.0/Workbench/InstrumentViewer/Bugfixes/36912.rst
  qt/widgets/instrumentview/src/InstrumentWidget.cpp
  qt/widgets/instrumentview/src/ProjectionSurface.cpp
Labels: Bug, ISIS Team: Core, Added during Sprint, Found in Beta

#36838 Add reduction call metadata to ISIS ORSO file
  Framework/Algorithms/src/GeneratePythonScript.cpp
  Framework/Algorithms/test/GeneratePythonScriptTest.h
  Framework/PythonInterface/mantid/utils/reflectometry/orso_helper.py
  Framework/PythonInterface/plugins/algorithms/SaveISISReflectometryORSO.py
  Framework/PythonInterface/test/python/mantid/utils/reflectometry/orso_helper_test.py
  Framework/PythonInterface/test/python/plugins/algorithms/SaveISISReflectometryORSOTest.py
  docs/source/algorithms/GeneratePythonScript-v1.rst
  docs/source/algorithms/SaveISISReflectometryORSO-v1.rst
  docs/source/release/v6.10.0/Reflectometry/New_features/36395.rst
Labels: Reflectometry, ISIS Team: LSS

#36936 Fixed instrument view title upon renaming workspace
  docs/source/release/v6.10.0/Workbench/InstrumentViewer/Bugfixes/36936.rst
  qt/python/mantidqt/mantidqt/widgets/instrumentview/view.py
  qt/widgets/instrumentview/src/InstrumentWidget.cpp
Labels: Bug, ISIS Team: Core
