Repository mantidproject/mantid, pull requests merged in 2024-11, with the labels that each got.

#38343 Refactor `eagroup_context_test` for readability and speed
  qt/python/mantidqtinterfaces/test/Muon/elemental_analysis_2/elemental_analysis_eagroup_context_test.py
Labels: Muon, Maintenance, ISIS Team: Spectroscopy

#38077 Matplotlib 3.8 update
  Framework/PythonInterface/mantid/plots/mantidaxes.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/FindPeakAutomaticTest.py
  conda/recipes/conda_build_config.yaml
  docs/source/release/v6.12.0/Framework/Dependencies/New_features/38077.rst
  qt/applications/workbench/workbench/plotting/figureinteraction.py
  qt/applications/workbench/workbench/plotting/figuremanager.py
  qt/applications/workbench/workbench/plotting/toolbar.py
  qt/python/mantidqt/mantidqt/plotting/figuretype.py
  qt/python/mantidqt/mantidqt/plotting/test/test_figuretype.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/DGSPlanner/InstrumentSetupWidget.py
Labels: Maintenance, ISIS Team: Core

#38321 Add test for mvp creation tool
  dev-docs/source/MVPDesign.rst
  tools/MVP/template.py
  tools/MVP/templates/ModelTest.h.in
  tools/MVP/templates/PresenterTest.h.in
  tools/MVP/templates/test_model.py.in
  tools/MVP/templates/test_presenter.py.in
Labels: Indirect/Inelastic, ISIS Team: Spectroscopy

#38319 Enable E741 ruff check
  Framework/PythonInterface/plugins/algorithms/AngularAutoCorrelationsSingleAxis.py
  Framework/PythonInterface/plugins/algorithms/AngularAutoCorrelationsTwoAxes.py
  Framework/PythonInterface/plugins/algorithms/CreateLeBailFitInput.py
  Framework/PythonInterface/plugins/algorithms/CylinderPaalmanPingsCorrection2.py
  Framework/PythonInterface/plugins/algorithms/DeltaPDF3D.py
  Framework/PythonInterface/plugins/algorithms/GSASIIRefineFitPeaks.py
  Framework/PythonInterface/plugins/algorithms/GenerateGroupingSNSInelastic.py
  Framework/PythonInterface/plugins/algorithms/LRReflectivityOutput.py
  Framework/PythonInterface/plugins/algorithms/LinkedUBs.py
  Framework/PythonInterface/plugins/algorithms/LoadFullprofFile.py
  Framework/PythonInterface/plugins/algorithms/LoadNMoldyn3Ascii.py
  Framework/PythonInterface/plugins/algorithms/VelocityCrossCorrelations.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransfer.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLMultiProcess.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SimulatedDensityOfStates.py
  Framework/PythonInterface/plugins/functions/HallRoss.py
  Testing/SystemTests/tests/framework/HB3AWorkflowTests.py
  Testing/SystemTests/tests/framework/ReflectometryISIS.py
  Testing/SystemTests/tests/framework/ReflectometryISIS_v2.py
  Testing/SystemTests/tests/framework/RelectometryInstrumentSignedThetaTest.py
  Testing/Tools/cxxtest/build_tools/SCons/cxxtest.py
  pyproject.toml
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/call_G2sc.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/HFIR_4Circle_Reduction/hfctables.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/HFIR_4Circle_Reduction/reduce4circleControl.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/HFIR_4Circle_Reduction/reduce4circleGUI.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/drill/presenter/DrillPresenter.py
  scripts/DiamondAttenuationCorrection/FitTrans.py
  scripts/DiamondAttenuationCorrection/FitTransReadUB.py
  scripts/DiamondAttenuationCorrection/UBMatrixGenerator.py
  scripts/Diffraction/single_crystal/test/test_base_sx.py
  scripts/Inelastic/CrystalField/pointcharge.py
  scripts/LargeScaleStructures/data_stitching.py
  scripts/LargeScaleStructures/geometry_writer.py
  scripts/Reflectometry/isis_reflectometry/procedures.py
  scripts/SANS/ISISCommandInterface.py
  scripts/abins/input/crystalloader.py
  scripts/abins/input/gaussianloader.py
  scripts/pychop/Instruments.py
  scripts/reduction_gui/reduction/scripter.py
  scripts/test/CrystalFieldTest.py
  tools/CodeAnalysis/gcovr
  tools/unit_test_speed.py
Labels: Maintenance, ISIS Team: Core

#38346 Matplotlib 3.8 and ruff E402 - ornl-next
  Framework/PythonInterface/mantid/plots/mantidaxes.py
  Framework/PythonInterface/plugins/algorithms/AngularAutoCorrelationsSingleAxis.py
  Framework/PythonInterface/plugins/algorithms/AngularAutoCorrelationsTwoAxes.py
  Framework/PythonInterface/plugins/algorithms/CreateLeBailFitInput.py
  Framework/PythonInterface/plugins/algorithms/CylinderPaalmanPingsCorrection2.py
  Framework/PythonInterface/plugins/algorithms/DeltaPDF3D.py
  Framework/PythonInterface/plugins/algorithms/GSASIIRefineFitPeaks.py
  Framework/PythonInterface/plugins/algorithms/GenerateGroupingSNSInelastic.py
  Framework/PythonInterface/plugins/algorithms/LRReflectivityOutput.py
  Framework/PythonInterface/plugins/algorithms/LinkedUBs.py
  Framework/PythonInterface/plugins/algorithms/LoadFullprofFile.py
  Framework/PythonInterface/plugins/algorithms/LoadNMoldyn3Ascii.py
  Framework/PythonInterface/plugins/algorithms/VelocityCrossCorrelations.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransfer.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANSILLMultiProcess.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SimulatedDensityOfStates.py
  Framework/PythonInterface/plugins/functions/HallRoss.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/FindPeakAutomaticTest.py
  Testing/SystemTests/tests/framework/HB3AWorkflowTests.py
  Testing/SystemTests/tests/framework/ReflectometryISIS.py
  Testing/SystemTests/tests/framework/ReflectometryISIS_v2.py
  Testing/SystemTests/tests/framework/RelectometryInstrumentSignedThetaTest.py
  Testing/Tools/cxxtest/build_tools/SCons/cxxtest.py
  conda/recipes/conda_build_config.yaml
  docs/source/release/v6.12.0/Framework/Dependencies/New_features/38077.rst
  pyproject.toml
  qt/applications/workbench/workbench/plotting/figureinteraction.py
  qt/applications/workbench/workbench/plotting/figuremanager.py
  qt/applications/workbench/workbench/plotting/toolbar.py
  qt/python/mantidqt/mantidqt/plotting/figuretype.py
  qt/python/mantidqt/mantidqt/plotting/test/test_figuretype.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/DGSPlanner/InstrumentSetupWidget.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/call_G2sc.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/HFIR_4Circle_Reduction/hfctables.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/HFIR_4Circle_Reduction/reduce4circleControl.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/HFIR_4Circle_Reduction/reduce4circleGUI.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/drill/presenter/DrillPresenter.py
  scripts/DiamondAttenuationCorrection/FitTrans.py
  scripts/DiamondAttenuationCorrection/FitTransReadUB.py
  scripts/DiamondAttenuationCorrection/UBMatrixGenerator.py
  scripts/Diffraction/single_crystal/test/test_base_sx.py
  scripts/Inelastic/CrystalField/pointcharge.py
  scripts/LargeScaleStructures/data_stitching.py
  scripts/LargeScaleStructures/geometry_writer.py
  scripts/Reflectometry/isis_reflectometry/procedures.py
  scripts/SANS/ISISCommandInterface.py
  scripts/abins/input/crystalloader.py
  scripts/abins/input/gaussianloader.py
  scripts/pychop/Instruments.py
  scripts/reduction_gui/reduction/scripter.py
  scripts/test/CrystalFieldTest.py
  tools/CodeAnalysis/gcovr
  tools/unit_test_speed.py
Labels: Maintenance

#38348 Refactor eagroup_context_test for readability and speed - ornl-next
  qt/python/mantidqtinterfaces/test/Muon/elemental_analysis_2/elemental_analysis_eagroup_context_test.py
Labels: Maintenance

#38349 Update developer dependencies
  conda/recipes/mantid-developer/meta.yaml
Labels: Maintenance

#38350 Fix typo in mantid profiling link
  dev-docs/source/AlgorithmProfiler.rst
Labels: High Priority, Bug, ISIS Team: Core

#38308 `EditInstrumentGeometry`: place detectors in single detector bank.
  Framework/Algorithms/src/EditInstrumentGeometry.cpp
  Framework/Algorithms/test/EditInstrumentGeometryTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/algorithms/EditInstrumentGeometry-v1.rst
  docs/source/release/v6.12.0/Framework/Algorithms/New_features/38308.rst
Labels: Framework, ORNL Team

#38359 Do not allow qtpy v2.4.2
  conda/recipes/conda_build_config.yaml
Labels: High Priority, Bug, Dependencies

#38358 Enable E402 ruff check
  .pre-commit-config.yaml
  Framework/PythonInterface/mantid/__init__.py
  Framework/PythonInterface/mantid/api/__init__.py
  Framework/PythonInterface/mantid/geometry/__init__.py
  Framework/PythonInterface/mantid/kernel/__init__.py
  Framework/PythonInterface/mantid/plots/modest_image/modest_image.py
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid/run_test.py
  dev-docs/source/AlgorithmProfiler.rst
  pyproject.toml
  qt/applications/workbench/workbench/app/start.py
  qt/applications/workbench/workbench/plugins/jupyterconsole.py
  qt/python/mantidqt/mantidqt/utils/qt/__init__.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Filter_Events.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/HFIR_4Circle_Reduction.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/reduction_application.py
  scripts/Calibration/Examples/TubeCalibDemoWish1.py
Labels: Maintenance

#38360 Setting invalid value is not an exception
  Framework/Kernel/inc/MantidKernel/EnumeratedString.h
  Framework/Kernel/inc/MantidKernel/EnumeratedStringProperty.hxx
  Framework/Kernel/test/EnumeratedStringPropertyTest.h
Labels: High Priority, Bug, GUI

#38369 Update VULCAN definition
  docs/source/release/v6.12.0/Workbench/New_features/38369.rst
  instrument/VULCAN_Definition.xml
  instrument/VULCAN_Definition_2021-01-01.xml
Labels: ORNL Team

#38355 Fix index error in OS name string extraction method
  Framework/Kernel/src/ConfigService.cpp
  Framework/Kernel/test/ConfigServiceTest.h
  docs/source/release/v6.12.0/Workbench/Bugfixes/38054.rst
Labels: macOS Only, ISIS Team: Core

#38374 Update VULCAN definition - `ornl-next`
  docs/source/release/v6.12.0/Workbench/New_features/38369.rst
  instrument/VULCAN_Definition.xml
  instrument/VULCAN_Definition_2021-01-01.xml
Labels: ORNL Team, ornl-next

#38309 `SaveNexusESS` append mode.
  Framework/Beamline/src/ComponentInfo.cpp
  Framework/DataHandling/inc/MantidDataHandling/H5Util.h
  Framework/DataHandling/inc/MantidDataHandling/LoadNexusProcessed.h
  Framework/DataHandling/inc/MantidDataHandling/LoadNexusProcessed2.h
  Framework/DataHandling/inc/MantidDataHandling/SaveNexusESS.h
  Framework/DataHandling/src/H5Util.cpp
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  Framework/DataHandling/src/LoadNexusProcessed2.cpp
  Framework/DataHandling/src/SaveNexusESS.cpp
  Framework/DataHandling/src/SaveNexusGeometry.cpp
  Framework/DataHandling/src/SaveNexusProcessed.cpp
  Framework/DataHandling/test/H5UtilTest.h
  Framework/DataHandling/test/SaveNexusESSTest.h
  Framework/DataHandling/test/SaveNexusGeometryTest.h
  Framework/Geometry/src/Instrument/InstrumentDefinitionParser.cpp
  Framework/Nexus/src/NexusClasses.cpp
  Framework/NexusGeometry/inc/MantidNexusGeometry/AbstractLogger.h
  Framework/NexusGeometry/inc/MantidNexusGeometry/NexusGeometryParser.h
  Framework/NexusGeometry/inc/MantidNexusGeometry/NexusGeometrySave.h
  Framework/NexusGeometry/inc/MantidNexusGeometry/NexusGeometryUtilities.h
  Framework/NexusGeometry/src/NexusGeometryParser.cpp
  Framework/NexusGeometry/src/NexusGeometrySave.cpp
  Framework/NexusGeometry/src/NexusGeometryUtilities.cpp
  Framework/NexusGeometry/test/NexusGeometryParserTest.h
  Framework/NexusGeometry/test/NexusGeometrySaveTest.h
  Framework/NexusGeometry/test/mockobjects.h
  Framework/PythonInterface/test/testhelpers/WorkspaceCreationHelper/WorkspaceCreationHelperModule.cpp
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/ComponentCreationHelper.h
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/NexusFileReader.h
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/NexusGeometryTestHelpers.h
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/WorkspaceCreationHelper.h
  Framework/TestHelpers/src/ComponentCreationHelper.cpp
  Framework/TestHelpers/src/WorkspaceCreationHelper.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/algorithms/SaveNexusESS-v1.rst
  docs/source/algorithms/SaveNexusGeometry-v1.rst
  docs/source/api/python/mantid/kernel/DateAndTime.rst
  docs/source/release/v6.12.0/Framework/Algorithms/New_features/38309.rst
  instrument/unit_testing/SMALLFAKE_example_multiple_entries.hdf5
Labels: Framework, ORNL Team

#38372 Set multiselect to false in EnumeratedStringProperty
  Framework/Kernel/inc/MantidKernel/EnumeratedStringProperty.h
  Framework/Kernel/inc/MantidKernel/EnumeratedStringProperty.hxx
Labels: High Priority, Bug, Framework

#38378 Set multiselect to false in EnumeratedStringProperty ornl-next
  Framework/Kernel/inc/MantidKernel/EnumeratedStringProperty.h
  Framework/Kernel/inc/MantidKernel/EnumeratedStringProperty.hxx
Labels: Maintenance, ornl-next

#38384 Pull in parameter renaming changes from main into ornl-next
  Framework/DataHandling/inc/MantidDataHandling/LoadNexusProcessed2.h
  Framework/DataHandling/src/H5Util.cpp
  Framework/DataHandling/src/LoadNexusProcessed2.cpp
  Framework/NexusGeometry/inc/MantidNexusGeometry/NexusGeometrySave.h
  Framework/NexusGeometry/src/NexusGeometrySave.cpp
  Framework/TestHelpers/src/WorkspaceCreationHelper.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance, ornl-next

#38357 MVP for the ResNorm tab of the Inelastic Bayes Fitting interface
  qt/scientific_interfaces/Inelastic/BayesFitting/BayesFitting.cpp
  qt/scientific_interfaces/Inelastic/BayesFitting/BayesFitting.h
  qt/scientific_interfaces/Inelastic/BayesFitting/BayesFittingTab.cpp
  qt/scientific_interfaces/Inelastic/BayesFitting/BayesFittingTab.h
  qt/scientific_interfaces/Inelastic/BayesFitting/CMakeLists.txt
  qt/scientific_interfaces/Inelastic/BayesFitting/Quasi.cpp
  qt/scientific_interfaces/Inelastic/BayesFitting/Quasi.h
  qt/scientific_interfaces/Inelastic/BayesFitting/ResNorm.cpp
  qt/scientific_interfaces/Inelastic/BayesFitting/ResNorm.h
  qt/scientific_interfaces/Inelastic/BayesFitting/ResNormModel.cpp
  qt/scientific_interfaces/Inelastic/BayesFitting/ResNormModel.h
  qt/scientific_interfaces/Inelastic/BayesFitting/ResNormPresenter.cpp
  qt/scientific_interfaces/Inelastic/BayesFitting/ResNormPresenter.h
  qt/scientific_interfaces/Inelastic/BayesFitting/ResNormView.cpp
  qt/scientific_interfaces/Inelastic/BayesFitting/ResNormView.h
  qt/scientific_interfaces/Inelastic/BayesFitting/Stretch.cpp
  qt/scientific_interfaces/Inelastic/BayesFitting/Stretch.h
  qt/widgets/spectroscopy/inc/MantidQtWidgets/Spectroscopy/InterfaceUtils.h
  qt/widgets/spectroscopy/src/InterfaceUtils.cpp
Labels: Indirect/Inelastic, Maintenance, ISIS Team: Spectroscopy

#37762 Add identifier for output workspaces in Elwin Interface
  qt/scientific_interfaces/Inelastic/Processor/DataProcessor.h
  qt/scientific_interfaces/Inelastic/Processor/ElwinModel.cpp
  qt/scientific_interfaces/Inelastic/Processor/ElwinModel.h
  qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.cpp
  qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.h
  qt/scientific_interfaces/Inelastic/Processor/ElwinTab.ui
  qt/scientific_interfaces/Inelastic/Processor/ElwinView.cpp
  qt/scientific_interfaces/Inelastic/Processor/ElwinView.h
  qt/scientific_interfaces/Inelastic/Processor/IElwinView.h
  qt/scientific_interfaces/Inelastic/test/Processor/ElwinModelTest.h
  qt/scientific_interfaces/Inelastic/test/Processor/ElwinPresenterTest.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/MockObjects.h
  qt/widgets/spectroscopy/CMakeLists.txt
  qt/widgets/spectroscopy/inc/MantidQtWidgets/Spectroscopy/InelasticTab.h
  qt/widgets/spectroscopy/inc/MantidQtWidgets/Spectroscopy/MockObjects.h
  qt/widgets/spectroscopy/inc/MantidQtWidgets/Spectroscopy/OutputWidget/OutputName.ui
  qt/widgets/spectroscopy/inc/MantidQtWidgets/Spectroscopy/OutputWidget/OutputNameModel.h
  qt/widgets/spectroscopy/inc/MantidQtWidgets/Spectroscopy/OutputWidget/OutputNamePresenter.h
  qt/widgets/spectroscopy/inc/MantidQtWidgets/Spectroscopy/OutputWidget/OutputNameView.h
  qt/widgets/spectroscopy/src/InelasticTab.cpp
  qt/widgets/spectroscopy/src/OutputWidget/OutputNameModel.cpp
  qt/widgets/spectroscopy/src/OutputWidget/OutputNamePresenter.cpp
  qt/widgets/spectroscopy/src/OutputWidget/OutputNameView.cpp
  qt/widgets/spectroscopy/test/CMakeLists.txt
  qt/widgets/spectroscopy/test/OutputWidget/OutputNameModelTest.h
  qt/widgets/spectroscopy/test/OutputWidget/OutputNamePresenterTest.h
Labels: Indirect/Inelastic, GUI, ISIS Team: Spectroscopy

#38256 Stop ReflectometryReductionOneLiveData from re-writing the spectra map on instrument load
  Framework/PythonInterface/plugins/algorithms/ReflectometryReductionOneLiveData.py
  Framework/PythonInterface/test/python/plugins/algorithms/ReflectometryReductionOneLiveDataTest.py
  docs/source/release/v6.12.0/Reflectometry/Bugfixes/38202.rst
Labels: Reflectometry, ISIS Team: LSS

#38382 Improve mantid-profiler-related Documentation Links
  dev-docs/source/AlgorithmProfiler.rst
  dev-docs/source/images/MantidProfiler.png
Labels: Documentation

#38386 Fix for Enumerated String Properties docs bug
  Framework/Kernel/src/Property.cpp
  Framework/PythonInterface/test/python/mantid/SimpleAPITest.py
  docs/sphinxext/mantiddoc/directives/properties.py
Labels: Bug, Documentation

#38299 Use Mslice as conda package instead of an external interface
  buildconfig/Jenkins/Conda/package-conda
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantidworkbench/meta.yaml
  dev-docs/source/ReleaseChecklist.rst
  docs/source/release/v6.12.0/Direct_Geometry/MSlice/New_features/38299.rst
  installers/conda/linux/create_tarball.sh
  installers/conda/osx/create_bundle.sh
  installers/conda/win/create_package.sh
  qt/python/mantidqtinterfaces/mantidqtinterfaces/MSlice.py
  scripts/CMakeLists.txt
  scripts/ExternalInterfaces/CMakeLists.txt
Labels: Direct Inelastic, ISIS Team: Excitations/Vesuvio

#38325 Update SANS Manual Testing Instructions
  dev-docs/source/Testing/SANSGUI/ISISSANSGUITests.rst
Labels: SANS, Documentation, Maintenance, ISIS Team: LSS

#38387 fix coverity issues in FindReflectometryLines Algorithm
  Framework/Reflectometry/src/FindReflectometryLines2.cpp
Labels: Reflectometry, Maintenance, ISIS Team: LSS

#38380 Set `performancelog.filename` default to `algotimeregister.out`
  Framework/Properties/Mantid.properties.template
  docs/source/concepts/PropertiesFile.rst
Labels: ISIS Team: Core, Linux Only

#38211 Remove QObjects from ALCFitting Presenter and Model
  qt/scientific_interfaces/Muon/ALCBaselineModellingPresenter.cpp
  qt/scientific_interfaces/Muon/ALCBaselineModellingPresenter.h
  qt/scientific_interfaces/Muon/ALCInterface.cpp
  qt/scientific_interfaces/Muon/ALCInterface.h
  qt/scientific_interfaces/Muon/ALCPeakFittingModel.cpp
  qt/scientific_interfaces/Muon/ALCPeakFittingModel.h
  qt/scientific_interfaces/Muon/ALCPeakFittingPresenter.cpp
  qt/scientific_interfaces/Muon/ALCPeakFittingPresenter.h
  qt/scientific_interfaces/Muon/ALCPeakFittingView.cpp
  qt/scientific_interfaces/Muon/ALCPeakFittingView.h
  qt/scientific_interfaces/Muon/CMakeLists.txt
  qt/scientific_interfaces/Muon/IALCBaselineModellingPresenterSubscriber.h
  qt/scientific_interfaces/Muon/IALCPeakFittingModel.h
  qt/scientific_interfaces/Muon/IALCPeakFittingModelSubscriber.h
  qt/scientific_interfaces/Muon/IALCPeakFittingView.h
  qt/scientific_interfaces/Muon/IALCPeakFittingViewSubscriber.h
  qt/scientific_interfaces/Muon/test/ALCBaselineModellingPresenterTest.h
  qt/scientific_interfaces/Muon/test/ALCPeakFittingModelTest.h
  qt/scientific_interfaces/Muon/test/ALCPeakFittingPresenterTest.h
Labels: Muon, GUI, ISIS Team: Spectroscopy

#38397 Some unusedVariiable cppckeck error removals.
  Framework/API/src/NumericAxis.cpp
  Framework/Algorithms/src/CalculateCarpenterSampleCorrection.cpp
  Framework/Algorithms/src/GroupWorkspaces.cpp
  Framework/Algorithms/src/InterpolatingRebin.cpp
  Framework/Algorithms/src/SmoothNeighbours.cpp
  Framework/Algorithms/src/Stitch.cpp
  Framework/Algorithms/src/WeightedMeanOfWorkspace.cpp
  Framework/Crystal/src/GoniometerAnglesFromPhiRotation.cpp
  Framework/DataHandling/src/LoadANSTOHelper.cpp
  Framework/DataHandling/src/LoadTBL.cpp
  Framework/DataHandling/src/SavePHX.cpp
  Framework/Kernel/src/LogFilter.cpp
  Framework/LiveData/src/ISIS/DAE/isisds_command.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  qt/widgets/common/src/AlgorithmPropertiesWidget.cpp
  qt/widgets/common/src/RepoModel.cpp
Labels: ISIS Team: Core

#38334 Rename some HeliumAnalyserEfficiency algorithm parameters
  Framework/Algorithms/src/PolarizationCorrections/HeliumAnalyserEfficiency.cpp
  Framework/Algorithms/test/PolarizationCorrections/HeliumAnalyserEfficiencyTest.h
  docs/source/algorithms/HeliumAnalyserEfficiency-v1.rst
  docs/source/release/v6.12.0/Framework/Algorithms/Bugfixes/38290.rst
  docs/source/release/v6.12.0/Framework/Algorithms/New_features/36981.rst
Labels: SANS, ISIS Team: LSS

#38391 Remove deprecated Calculate Paalman Pings tab from Inelastic Corrections
  dev-docs/source/Testing/Inelastic/CorrectionsTests.rst
  docs/source/interfaces/indirect/Indirect Settings.rst
  docs/source/interfaces/inelastic/Inelastic Corrections.rst
  docs/source/release/v6.12.0/Inelastic/New_features/38391.rst
  qt/scientific_interfaces/Inelastic/Corrections/CMakeLists.txt
  qt/scientific_interfaces/Inelastic/Corrections/CalculatePaalmanPings.cpp
  qt/scientific_interfaces/Inelastic/Corrections/CalculatePaalmanPings.h
  qt/scientific_interfaces/Inelastic/Corrections/CalculatePaalmanPings.ui
  qt/scientific_interfaces/Inelastic/Corrections/Corrections.cpp
  qt/scientific_interfaces/Inelastic/Corrections/Corrections.h
  qt/scientific_interfaces/Inelastic/Corrections/Corrections.ui
  qt/widgets/spectroscopy/inc/MantidQtWidgets/Spectroscopy/InterfaceProperties.xml
Labels: Indirect/Inelastic, Maintenance, ISIS Team: Spectroscopy

#38399 Fix error on create_vanadium if no sample details in ISIS powder reduction
  docs/source/release/v6.12.0/Diffraction/Powder/Bugfixes/38399.rst
  scripts/Diffraction/isis_powder/abstract_inst.py
  scripts/Diffraction/isis_powder/test/ISISPowderAbstractInstrumentTest.py
Labels: Diffraction, Powder, ISIS Team: Diffraction

#38337 Minor usability fixes to ISIS sx diffraction class post beta testing
  docs/source/release/v6.12.0/Diffraction/Single_Crystal/New_features/38337.rst
  scripts/Diffraction/single_crystal/base_sx.py
  scripts/Diffraction/single_crystal/test/test_base_sx.py
  scripts/Diffraction/single_crystal/test/test_sxd.py
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction, Added during Sprint

#38379 Use H5Cpp library for LoadMcStas algorithm
  Framework/DataHandling/inc/MantidDataHandling/H5Util.h
  Framework/DataHandling/inc/MantidDataHandling/LoadMcStas.h
  Framework/DataHandling/src/H5Util.cpp
  Framework/DataHandling/src/LoadMcStas.cpp
  Framework/DataHandling/src/LoadNXcanSAS.cpp
  Framework/DataHandling/test/H5UtilTest.h
  Framework/DataHandling/test/LoadMcStasTest.h
  Framework/DataHandling/test/SaveNXcanSASTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance, ISIS Team: Core

#38400 - Maintenance task for polarization correction Fredrikze Algorithm
  Framework/Algorithms/src/PolarizationCorrectionFredrikze.cpp
  docs/source/algorithms/PolarizationCorrectionFredrikze-v1.rst
Labels: Reflectometry, Maintenance, ISIS Team: LSS

#38403 Fix crash when setting invalid filepaths in Flood Corrections and Polarization Corrections settings on Reflectometry interface
  docs/source/release/v6.12.0/Reflectometry/Bugfixes/36469.rst
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/QtExperimentView.h
  qt/scientific_interfaces/ISISReflectometry/GUI/MainWindow/QtMainWindowView.cpp
Labels: Bug, Reflectometry, ISIS Team: LSS, Windows Only

#38401 Document module mantid.utils.reflectometry.orso_helper
  docs/source/api/python/mantid/utils/index.rst
  docs/source/api/python/mantid/utils/reflectometry.rst
  docs/source/images/orso_helper.png
  docs/source/images/orso_helper.puml
Labels: Maintenance, ISIS Team: LSS, ORNL Team

#38402 Document module mantid.utils.reflectometry.orso_helper
  docs/source/api/python/mantid/utils/index.rst
  docs/source/api/python/mantid/utils/reflectometry.rst
  docs/source/images/orso_helper.png
  docs/source/images/orso_helper.puml
Labels: ornl-next

#38404 Update pystog to v0.4.7
  buildconfig/CMake/PyStoG.cmake
  docs/source/release/v6.12.0/Diffraction/Powder/New_features/38404.rst
Labels: Diffraction, Powder, Maintenance

#38363 Add option to write different batch number for each run in various formats output by SaveReflections
  Framework/PythonInterface/plugins/algorithms/SaveReflections.py
  Framework/PythonInterface/test/python/plugins/algorithms/SaveReflectionsTest.py
  Testing/Data/UnitTest/fullprof_format_separate_batch_nums.hkl.md5
  Testing/Data/UnitTest/gsas_format.hkl.md5
  Testing/Data/UnitTest/jana_format_separate_batch_nums.hkl.md5
  Testing/Data/UnitTest/shelx_format_separate_batch_nums.hkl.md5
  docs/source/release/v6.12.0/Diffraction/Single_Crystal/New_features/38363.rst
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction

#38392 Elwin Elastic line integration issue
  docs/source/release/v6.12.0/Inelastic/Bugfixes/38392.rst
  qt/scientific_interfaces/Inelastic/Processor/ElwinModel.cpp
  qt/scientific_interfaces/Inelastic/Processor/ElwinModel.h
  qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.cpp
  qt/scientific_interfaces/Inelastic/Processor/ElwinView.cpp
  qt/scientific_interfaces/Inelastic/Processor/ElwinView.h
  qt/scientific_interfaces/Inelastic/Processor/IElwinView.h
  qt/scientific_interfaces/Inelastic/test/Processor/ElwinModelTest.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/MockObjects.h
Labels: Indirect/Inelastic, ORNL Team

#38416 Elwin Elastic line integration issue - Sister PR
  docs/source/release/v6.12.0/Inelastic/Bugfixes/38392.rst
  qt/scientific_interfaces/Inelastic/Processor/ElwinModel.cpp
  qt/scientific_interfaces/Inelastic/Processor/ElwinModel.h
  qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.cpp
  qt/scientific_interfaces/Inelastic/Processor/ElwinView.cpp
  qt/scientific_interfaces/Inelastic/Processor/ElwinView.h
  qt/scientific_interfaces/Inelastic/Processor/IElwinView.h
  qt/scientific_interfaces/Inelastic/test/Processor/ElwinModelTest.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/MockObjects.h
Labels: Indirect/Inelastic, ornl-next

#38417 Put back pystog test data - ornl-next
  buildconfig/CMake/PyStoG.cmake
Labels: Maintenance

#38432 [pre-commit.ci] pre-commit autoupdate - ornl-next
  .pre-commit-config.yaml
Labels: Maintenance, ornl-next

#38351 Update gcc to version 13
  Framework/API/test/CMakeLists.txt
  Framework/Algorithms/src/FitPeaks.cpp
  Framework/Algorithms/src/SofQWCentre.cpp
  Framework/Algorithms/test/CMakeLists.txt
  Framework/Algorithms/test/CalculateCarpenterSampleCorrectionTest.h
  Framework/Algorithms/test/CarpenterSampleCorrectionTest.h
  Framework/Algorithms/test/FitPeaksTest.h
  Framework/Algorithms/test/NormaliseToMonitorTest.h
  Framework/Crystal/test/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/LoadANSTOEventFile.h
  Framework/DataObjects/src/Workspace2D.cpp
  Framework/DataObjects/test/CMakeLists.txt
  Framework/Geometry/test/CMakeLists.txt
  Framework/Kernel/inc/MantidKernel/EnumeratedStringProperty.hxx
  Framework/Kernel/inc/MantidKernel/PropertyWithValue.tcc
  Framework/Kernel/test/ConfigPropertyObserverTest.h
  Framework/LiveData/test/CMakeLists.txt
  Framework/MDAlgorithms/test/CMakeLists.txt
  Framework/NexusGeometry/src/JSONGeometryParser.cpp
  Framework/NexusGeometry/test/CMakeLists.txt
  Framework/Parallel/src/IO/Chunker.cpp
  Framework/PythonInterface/core/inc/MantidPythonInterface/core/StlExportDefinitions.h
  Framework/PythonInterface/mantid/api/src/Exports/AlgorithmObserver.cpp
  Framework/PythonInterface/mantid/dataobjects/src/Exports/Workspace2D.cpp
  Framework/PythonInterface/mantid/kernel/src/Exports/StlContainers.cpp
  Framework/SINQ/test/CMakeLists.txt
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  buildconfig/CMake/QtTargetFunctions.cmake
  conda/recipes/conda_build_config.yaml
  docs/source/release/v6.12.0/Framework/Dependencies/New_features/38336.rst
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/ExperimentOptionDefaults.cpp
  qt/widgets/common/src/FitScriptGeneratorDataTable.cpp
Labels: ISIS Team: Core, Linux Only

#38430 Fix ApplyFloodWorkspace algorithm not preserving values in missing spectra
  Framework/Algorithms/src/ApplyFloodWorkspace.cpp
  Framework/Algorithms/test/ApplyFloodWorkspaceTest.h
  docs/source/release/v6.12.0/Reflectometry/Bugfixes/38393.rst
Labels: Bug, Reflectometry, ISIS Team: LSS

#38406 Move `H5Util` file to Mantid::Nexus library
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/LoadHelper.h
  Framework/DataHandling/inc/MantidDataHandling/LoadISISNexus2.h
  Framework/DataHandling/inc/MantidDataHandling/LoadMLZ.h
  Framework/DataHandling/inc/MantidDataHandling/LoadNexusProcessed.h
  Framework/DataHandling/inc/MantidDataHandling/LoadSINQFocus.h
  Framework/DataHandling/src/DataBlockComposite.cpp
  Framework/DataHandling/src/LoadDiffCal.cpp
  Framework/DataHandling/src/LoadILLDiffraction.cpp
  Framework/DataHandling/src/LoadISISNexus2.cpp
  Framework/DataHandling/src/LoadInstrumentFromNexus.cpp
  Framework/DataHandling/src/LoadMLZ.cpp
  Framework/DataHandling/src/LoadMcStas.cpp
  Framework/DataHandling/src/LoadMuonNexus2.cpp
  Framework/DataHandling/src/LoadNXcanSAS.cpp
  Framework/DataHandling/src/LoadQKK.cpp
  Framework/DataHandling/src/LoadSINQFocus.cpp
  Framework/DataHandling/src/SaveDiffCal.cpp
  Framework/DataHandling/src/SaveNXcanSAS.cpp
  Framework/DataHandling/test/LoadISISNexusTest.h
  Framework/DataHandling/test/LoadMuonNexus2Test.h
  Framework/DataHandling/test/SaveNXcanSASTest.h
  Framework/DataHandling/test/SaveNexusESSTest.h
  Framework/Nexus/CMakeLists.txt
  Framework/Nexus/inc/MantidNexus/H5Util.h
  Framework/Nexus/inc/MantidNexus/MuonNexusReader.h
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/inc/MantidNexus/NexusFileIO.h
  Framework/Nexus/src/H5Util.cpp
  Framework/Nexus/src/MuonNexusReader.cpp
  Framework/Nexus/src/NexusClasses.cpp
  Framework/Nexus/src/NexusFileIO.cpp
  Framework/Nexus/test/CMakeLists.txt
  Framework/Nexus/test/H5UtilTest.h
  Framework/NexusGeometry/test/NexusGeometryParserTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance, ISIS Team: Core

#38431 Add instructions for creating custom mantid-developer package
  dev-docs/source/Packaging.rst
Labels: Documentation, ISIS Team: Core

#38344 Add new pearl focus mode allowing user to specify which transverse detector modules to focus
  Testing/SystemTests/tests/framework/ISIS_PowderPearlTest.py
  docs/source/release/v6.12.0/Diffraction/Powder/New_features/38340.rst
  docs/source/techniques/ISISPowder-Pearl-v1.rst
  scripts/Diffraction/isis_powder/pearl.py
  scripts/Diffraction/isis_powder/pearl_routines/pearl_enums.py
  scripts/Diffraction/isis_powder/pearl_routines/pearl_output.py
  scripts/Diffraction/isis_powder/pearl_routines/pearl_param_mapping.py
  scripts/Diffraction/isis_powder/test/ISISPowderPearlTest.py
Labels: Diffraction, Powder, ISIS Team: Diffraction, Added during Sprint

#38342 Update Clang to version 18 on macOS
  Framework/CurveFitting/src/Functions/BSpline.cpp
  buildconfig/CMake/CommonSetup.cmake
  buildconfig/CMake/GNUSetup.cmake
  conda/recipes/conda_build_config.yaml
  docs/source/release/v6.12.0/Workbench/New_features/38335.rst
Labels: macOS Only, ISIS Team: Core

#38123 Add gsas2 unit tests
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/call_G2sc.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/test/test_call_G2sc.py
Labels: Maintenance, ISIS Team: Diffraction

#38435 Move from matplotlib 3.8 to 3.9
  Framework/PythonInterface/plugins/algorithms/IntegratePeaksSkew.py
  conda/recipes/conda_build_config.yaml
  docs/source/release/v6.12.0/Framework/Dependencies/New_features/38077.rst
  qt/python/mantidqt/mantidqt/plotting/test/test_sample_shape.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/__init__.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/curvestabwidget/__init__.py
Labels: Maintenance

#38450 clang18, coverity, and matplotlib 3.9 changes into ornl-next
  Framework/API/src/NumericAxis.cpp
  Framework/Algorithms/inc/MantidAlgorithms/FindPeaksConvolve.h
  Framework/Algorithms/src/CalculateCarpenterSampleCorrection.cpp
  Framework/Algorithms/src/FindPeaksConvolve.cpp
  Framework/Algorithms/src/GroupWorkspaces.cpp
  Framework/Algorithms/src/InterpolatingRebin.cpp
  Framework/Algorithms/src/SmoothNeighbours.cpp
  Framework/Algorithms/src/Stitch.cpp
  Framework/Algorithms/src/WeightedMeanOfWorkspace.cpp
  Framework/Algorithms/test/FindPeaksConvolveTest.h
  Framework/Crystal/src/GoniometerAnglesFromPhiRotation.cpp
  Framework/Crystal/src/SCDPanelErrors.cpp
  Framework/CurveFitting/src/Functions/BSpline.cpp
  Framework/DataHandling/src/LoadANSTOHelper.cpp
  Framework/DataHandling/src/LoadTBL.cpp
  Framework/DataHandling/src/SavePHX.cpp
  Framework/Kernel/src/LogFilter.cpp
  Framework/LiveData/src/ISIS/DAE/isisds_command.cpp
  Framework/Muon/inc/MantidMuon/ConvertFitFunctionForMuonTFAsymmetry.h
  Framework/Muon/src/CalculateMuonAsymmetry.cpp
  Framework/Muon/src/ConvertFitFunctionForMuonTFAsymmetry.cpp
  Framework/PythonInterface/plugins/algorithms/IntegratePeaksSkew.py
  Framework/Reflectometry/src/FindReflectometryLines2.cpp
  Framework/WorkflowAlgorithms/src/StepScan.cpp
  buildconfig/CMake/CommonSetup.cmake
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  buildconfig/CMake/GNUSetup.cmake
  buildconfig/Jenkins/Conda/package-conda
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantidworkbench/meta.yaml
  dev-docs/source/ReleaseChecklist.rst
  docs/source/release/v6.12.0/Direct_Geometry/MSlice/New_features/38299.rst
  docs/source/release/v6.12.0/Framework/Algorithms/Bugfixes/37752.rst
  docs/source/release/v6.12.0/Framework/Dependencies/New_features/38077.rst
  docs/source/release/v6.12.0/Workbench/New_features/38335.rst
  installers/conda/linux/create_tarball.sh
  installers/conda/osx/create_bundle.sh
  installers/conda/win/create_package.sh
  qt/python/mantidqt/mantidqt/plotting/test/test_sample_shape.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/__init__.py
  qt/python/mantidqt/mantidqt/widgets/plotconfigdialog/curvestabwidget/__init__.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/MSlice.py
  qt/widgets/common/src/AlgorithmPropertiesWidget.cpp
  qt/widgets/common/src/RepoModel.cpp
  scripts/CMakeLists.txt
  scripts/ExternalInterfaces/CMakeLists.txt
Labels: Maintenance, ornl-next

#38444 LoadEventNexus error when loading single vulcan bank
  Framework/DataHandling/src/LoadEventNexusIndexSetup.cpp
  Framework/DataHandling/test/LoadEventNexusIndexSetupTest.h
  Framework/Indexing/inc/MantidIndexing/IndexType.h
  Framework/Indexing/src/IndexInfo.cpp
  docs/source/release/v6.12.0/Diffraction/Engineering/Bugfixes/.gitkeep
  docs/source/release/v6.12.0/Diffraction/Engineering/Bugfixes/38444.rst
Labels: Bug

#38159 Update indirect diffraction algorithms workflow diagrams
  docs/source/diagrams/ISISIndirectDiffractionReduction-v1_wkflw.dot
  docs/source/diagrams/OSIRISDiffractionReduction-v1_wkflw.dot
Labels: Diffraction, Maintenance, ISIS Team: Spectroscopy
