Repository mantidproject/mantid, pull requests merged in 2024-08, with the labels that each got.

#37726 Remove unnecessary custom TBB cmake module
  Framework/CMakeLists.txt
  buildconfig/CMake/FindTBB.cmake
Labels: Maintenance, ISIS Team: Core

#37692 Remove old non-conda buildscripts
  buildconfig/Jenkins/Conda/conda-buildscript
  buildconfig/Jenkins/buildscript
  buildconfig/Jenkins/buildscript.bat
  buildconfig/Jenkins/pre-commit
  buildconfig/Jenkins/systemtests
  buildconfig/Jenkins/systemtests.bat
Labels: ISIS Team: Core

#37727 Skip PowderReduceP2DTest on macOS and re-enable on Windows
  Testing/SystemTests/tests/framework/PowderReduceP2DTest.py
Labels: ISIS Team: Core

#37729 Fix cmake deprecation warning for Muon target
  Framework/Muon/CMakeLists.txt
Labels: Maintenance, ISIS Team: Core

#37686 Make data processor interface presenters independent of Qt
  qt/scientific_interfaces/Inelastic/Processor/CMakeLists.txt
  qt/scientific_interfaces/Inelastic/Processor/DataProcessor.cpp
  qt/scientific_interfaces/Inelastic/Processor/DataProcessor.h
  qt/scientific_interfaces/Inelastic/Processor/DataProcessorInterface.cpp
  qt/scientific_interfaces/Inelastic/Processor/DataProcessorInterface.h
  qt/scientific_interfaces/Inelastic/Processor/ElwinModel.cpp
  qt/scientific_interfaces/Inelastic/Processor/ElwinModel.h
  qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.cpp
  qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.h
  qt/scientific_interfaces/Inelastic/Processor/IqtModel.cpp
  qt/scientific_interfaces/Inelastic/Processor/IqtModel.h
  qt/scientific_interfaces/Inelastic/Processor/IqtPresenter.cpp
  qt/scientific_interfaces/Inelastic/Processor/IqtPresenter.h
  qt/scientific_interfaces/Inelastic/Processor/MomentsModel.cpp
  qt/scientific_interfaces/Inelastic/Processor/MomentsModel.h
  qt/scientific_interfaces/Inelastic/Processor/MomentsPresenter.cpp
  qt/scientific_interfaces/Inelastic/Processor/MomentsPresenter.h
  qt/scientific_interfaces/Inelastic/Processor/SqwModel.cpp
  qt/scientific_interfaces/Inelastic/Processor/SqwModel.h
  qt/scientific_interfaces/Inelastic/Processor/SqwPresenter.cpp
  qt/scientific_interfaces/Inelastic/Processor/SqwPresenter.h
  qt/scientific_interfaces/Inelastic/Processor/SymmetriseModel.cpp
  qt/scientific_interfaces/Inelastic/Processor/SymmetriseModel.h
  qt/scientific_interfaces/Inelastic/Processor/SymmetrisePresenter.cpp
  qt/scientific_interfaces/Inelastic/Processor/SymmetrisePresenter.h
  qt/scientific_interfaces/Inelastic/test/Processor/ElwinModelTest.h
  qt/scientific_interfaces/Inelastic/test/Processor/ElwinPresenterTest.h
  qt/scientific_interfaces/Inelastic/test/Processor/IqtModelTest.h
  qt/scientific_interfaces/Inelastic/test/Processor/MomentsPresenterTest.h
  qt/scientific_interfaces/Inelastic/test/Processor/SqwModelTest.h
  qt/scientific_interfaces/Inelastic/test/Processor/SymmetriseModelTest.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/MockObjects.h
Labels: Indirect/Inelastic, ISIS Team: Spectroscopy

#37732 Use BoostConfig instead of deprecated cmake code
  Framework/PythonInterface/CMakeLists.txt
  buildconfig/CMake/CommonSetup.cmake
Labels: Maintenance, ISIS Team: Core

#37700 Small speed improvement to Stitch1D
  Framework/Algorithms/inc/MantidAlgorithms/Stitch1D.h
  Framework/Algorithms/src/Stitch1D.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: ISIS Team: Core

#37728 Update developer documentation
  .gitignore
  dev-docs/source/BuildingWithCMake.rst
  dev-docs/source/GettingStarted/GettingStarted.rst
  dev-docs/source/GettingStarted/GettingStartedCondaLinux.rst
  dev-docs/source/GettingStarted/GettingStartedNoneConda.rst
  dev-docs/source/Standards/DocumentationGuideForDevs.rst
  dev-docs/source/index.rst
Labels: Documentation

#37713 Disabled context menu on colourbar
  docs/source/release/v6.11.0/Workbench/Bugfixes/37688.rst
  qt/applications/workbench/workbench/plotting/figureinteraction.py
Labels: Bug, ISIS Team: Core

#37737 Speed improvement for ScaleX ornl-next
  Framework/Algorithms/inc/MantidAlgorithms/ScaleX.h
  Framework/Algorithms/src/ScaleX.cpp
  docs/source/release/v6.11.0/Framework/Algorithms/Bugfixes/37719.rst
Labels: ORNL Team

#37736 Cmake upgrades into ornl-next
  CMakeLists.txt
  Framework/CMakeLists.txt
  Framework/Muon/CMakeLists.txt
  Framework/PythonInterface/CMakeLists.txt
  buildconfig/CMake/CommonSetup.cmake
  buildconfig/CMake/FindTBB.cmake
  buildconfig/CMake/GoogleTest.cmake
  buildconfig/CMake/Span.cmake
  conda/recipes/conda_build_config.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: ORNL Team

#37743 Fix error causing grainsize to evaluate to 0
  Framework/DataObjects/src/EventWorkspace.cpp
  docs/source/release/v6.11.0/Framework/Data_Objects/Bugfixes/37743.rst
Labels: Bug, Patch Candidate, ORNL Team

#37742 Change default Instrument View background colour to opaque black
  docs/source/release/v6.11.0/Workbench/InstrumentViewer/Bugfixes/37370.rst
  qt/widgets/instrumentview/src/InstrumentWidget.cpp
Labels: Bug, ISIS Team: Core, Reported By User

#37718 Added Deprecation policy to Mantid documentation
  docs/source/deprecation.rst
  docs/source/index.rst
  docs/source/release/v6.11.0/Workbench/New_features/37718.rst
Labels: Documentation

#37685 35956 move verify and clear to tear down method in isis reflectometry unit tests
  Framework/DataHandling/test/ISISJournalTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Options/OptionsDialogPresenterTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Runs/RunsPresenterTest.h
Labels: Reflectometry, Maintenance, ISIS Team: LSS

#37733 Add developer instructions to workaround Windows PyCharm bug
  dev-docs/source/PyCharm.rst
Labels: Documentation, ISIS Team: Core, Windows Only, Added during Sprint

#37616 Add Supermirror Polarizer Efficiency Algorithm
  Framework/Algorithms/CMakeLists.txt
  Framework/Algorithms/inc/MantidAlgorithms/PolarizationCorrections/PolarizationCorrectionsHelpers.h
  Framework/Algorithms/inc/MantidAlgorithms/PolarizationCorrections/PolarizerEfficiency.h
  Framework/Algorithms/src/PolarizationCorrections/PolarizationCorrectionsHelpers.cpp
  Framework/Algorithms/src/PolarizationCorrections/PolarizerEfficiency.cpp
  Framework/Algorithms/test/PolarizationCorrectionWildesTest.h
  Framework/Algorithms/test/PolarizationCorrections/PolarizationCorrectionsHelpersTest.h
  Framework/Algorithms/test/PolarizationCorrections/PolarizerEfficiencyTest.h
  docs/source/algorithms/PolarizerEfficiency-v1.rst
  docs/source/release/v6.11.0/SANS/New_features/36139.rst
Labels: SANS, ISIS Team: LSS

#37744 Update release notes template and generator
  dev-docs/source/Standards/ReleaseNotesGuide.rst
  docs/source/conf.py
  docs/source/release/templates/framework.rst
  tools/release_generator/release.py
Labels: Documentation, ISIS Team: Core

#37764 Assert almost equal into ornl-next
  Framework/PythonInterface/mantid/_testing/AssertAlmostEqual.py
  Framework/PythonInterface/test/python/mantid/_testing/AssertAlmostEqualTest.py
  docs/source/api/python/mantid/testing/assert_almost_equal.rst
  docs/source/release/v6.11.0/Framework/Python/New_features/37708.rst
Labels: ORNL Team

#37766 Update to Boost v1.84
  conda/recipes/conda_build_config.yaml
  docs/source/release/v6.10.0/Framework/Dependencies/New_features/36687.rst
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: ISIS Team: Core, Dependencies

#37782 Fix for the LoadIsawUB for MDWorkspaces
  Framework/Crystal/src/LoadIsawUB.cpp
  Framework/Crystal/test/LoadIsawUBTest.h
  docs/source/release/v6.11.0/Framework/Algorithms/Bugfixes/37781.rst
Labels: Bug, Direct Inelastic, Single Crystal

#37731 Fix CombineDiffCal to not scale like $O(N^2)$
  Framework/Algorithms/src/CombineDiffCal.cpp
  Framework/Algorithms/test/CombineDiffCalTest.h
  docs/source/release/v6.11.0/Framework/Algorithms/New_features/37731.rst
Labels: Diffraction, ORNL Team

#37761 Remove convertEmptyToTof from Mantid
  Framework/Algorithms/CMakeLists.txt
  Framework/Algorithms/inc/MantidAlgorithms/ConvertEmptyToTof.h
  Framework/Algorithms/src/ConvertEmptyToTof.cpp
  Framework/Algorithms/test/ConvertEmptyToTofTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/algorithms/ConvertEmptyToTof-v1.rst
  docs/source/release/v3.9.0/framework.rst
  docs/source/release/v6.11.0/Framework/Algorithms/Removed/37761.rst
Labels: Framework, ISIS Team: Core

#37791 Fix the calibration diagnostics plot issue
  docs/source/release/v6.11.0/Diffraction/Powder/Bugfixes/37791.rst
  scripts/Calibration/tofpd/diagnostics.py
Labels: Bug

#37779 Remove CheckWorkspacesMatch from Mantid
  Framework/API/src/Algorithm.cpp
  Framework/Algorithms/CMakeLists.txt
  Framework/Algorithms/inc/MantidAlgorithms/CheckWorkspacesMatch.h
  Framework/Algorithms/inc/MantidAlgorithms/CompareWorkspaces.h
  Framework/Algorithms/src/CheckWorkspacesMatch.cpp
  Framework/Algorithms/test/CheckWorkspacesMatchTest.h
  docs/source/algorithms/CheckWorkspacesMatch-v1.rst
  docs/source/release/v6.11.0/Framework/Algorithms/Removed/37779.rst
  scripts/Inelastic/Direct/ReductionWrapper.py
Labels: Framework, ISIS Team: Core

#37740 Fix error from plot when cropping workspace
  docs/source/release/v6.11.0/Workbench/Bugfixes/37132.rst
  qt/python/mantidqt/mantidqt/dialogs/spectraselectordialog.py
  qt/python/mantidqt/mantidqt/dialogs/test/test_spectraselectiondialog.py
Labels: Bug, GUI, ISIS Team: Core

#37783 Fix crash from ROI banks
  docs/source/release/v6.11.0/Workbench/InstrumentViewer/Bugfixes/34378.rst
  qt/widgets/mplcpp/inc/MantidQtWidgets/MplCpp/MantidColorMap.h
  qt/widgets/mplcpp/src/MantidColorMap.cpp
  qt/widgets/mplcpp/src/ScalarMappable.cpp
Labels: Bug, ISIS Team: Core

#37806 Use consistent naming for spectra in Indirect Reduction
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransfer.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/ISISIndirectEnergyTransferTest.py
  Testing/SystemTests/tests/framework/reference/tosca5224-glucose-ref.nxs.md5
  dev-docs/source/Testing/Indirect/DataReductionTests.rst
  docs/source/release/v6.11.0/Indirect/Bugfixes/37806.rst
  scripts/Inelastic/IndirectReductionCommon.py
Labels: Bug, Indirect/Inelastic, ISIS Team: Spectroscopy, Reported By User

#37635 - Temporarily hide plot results checkbox by default to prevent issues during ISIS SANS merge reduction
  docs/source/concepts/PropertiesFile.rst
  docs/source/interfaces/isis_sans/Runs Tab.rst
  docs/source/release/v6.11.0/SANS/Bugfixes/37577.rst
  scripts/Interface/ui/sans_isis/sans_data_processor_gui.py
  scripts/SANS/sans/gui_logic/presenter/run_tab_presenter.py
  scripts/test/SANS/gui_logic/test_run_tab_presenter.py
Labels: Bug, SANS, ISIS Team: LSS

#37765 Fix polarization corrections not being applied in ReflectometryReductionOneLiveData
  Framework/PythonInterface/plugins/algorithms/ReflectometryReductionOneLiveData.py
  Framework/PythonInterface/test/python/plugins/algorithms/ReflectometryReductionOneLiveDataTest.py
  docs/source/release/v6.11.0/Reflectometry/Bugfixes/34904.rst
Labels: Reflectometry, ISIS Team: LSS

#37797 Fix error when editing y-axis of a plot
  docs/source/release/v6.11.0/Workbench/Bugfixes/37267.rst
  qt/applications/workbench/workbench/plotting/figureinteraction.py
  qt/applications/workbench/workbench/plotting/propertiesdialog.py
  qt/applications/workbench/workbench/plotting/test/test_figureinteraction.py
Labels: Bug, ISIS Team: Core

#37802 Remove uses of load_module()
  Framework/PythonInterface/mantid/kernel/plugins.py
  Framework/PythonInterface/test/python/mantid/kernel/ConfigServiceTest.py
  Framework/PythonInterface/test/testhelpers/testrunner.py
  Testing/SystemTests/lib/systemtests/systemtesting.py
  Testing/Tools/cxxtest/sample/SCons/SConstruct
  Testing/Tools/cxxtest/test/unit/SConstruct
  docs/source/release/v6.11.0/Framework/Python/Bugfixes/37031.rst
Labels: ISIS Team: Core

#37748 New algorithm SaveMDHistoToVTK
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/SaveMDHistoToVTK.py
  Framework/PythonInterface/test/python/plugins/algorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/SaveMDHistoToVTKTest.py
  docs/source/algorithms/SaveMDHistoToVTK-v1.rst
  docs/source/release/v6.11.0/Diffraction/Single_Crystal/New_features/37748.rst
Labels: Single Crystal

#37811 DiffractionFocussing2 bug with sorted events
  Framework/Algorithms/src/DiffractionFocussing2.cpp
  Framework/Algorithms/test/DiffractionFocussing2Test.h
  Framework/DataObjects/inc/MantidDataObjects/EventList.h
  Framework/DataObjects/src/EventList.cpp
  Framework/DataObjects/test/EventListTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.11.0/Diffraction/Powder/Bugfixes/37811.rst
Labels: Bug, Diffraction, Powder, Patch Candidate

#37769 Update orsopy to version 1.2.1
  Testing/SystemTests/tests/framework/reference/ISISReducedPeriodDataWorkspaceORSOFile.ort.md5
  Testing/SystemTests/tests/framework/reference/ISISStitchedWorkspaceORSOFile.ort.md5
  conda/recipes/conda_build_config.yaml
  docs/source/release/v6.11.0/Reflectometry/Bugfixes/37769.rst
  mantid-developer-linux.yml
  mantid-developer-osx.yml
  mantid-developer-win.yml
Labels: Reflectometry, ISIS Team: LSS

#37821 Block libopenblas v0.3.28
  conda/recipes/conda_build_config.yaml
  mantid-developer-linux.yml
  mantid-developer-osx.yml
Labels: High Priority, DevOps

#37822 Change how instrument is specified to fix the doctest
  docs/source/algorithms/LoadDspacemap-v1.rst
Labels: Documentation

#37810 Indirect Reduction avoid loading workspace into ADS during validation
  docs/source/release/v6.11.0/Indirect/Bugfixes/37810.rst
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferValidator.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferValidator.h
Labels: Bug, Indirect/Inelastic, ISIS Team: Spectroscopy

#37794 Fix build error when using Visual Studio
  buildconfig/CMake/UiToPy.cmake
  qt/python/mantidqtinterfaces/mantidqtinterfaces/ui/batchwidget/.gitignore
  qt/python/mantidqtinterfaces/mantidqtinterfaces/ui/batchwidget/batch_widget_gui.py
Labels: ISIS Team: Core

#37724 Fix a freeze in Elwin tab while the interface is running
  docs/source/release/v6.11.0/Inelastic/Bugfixes/37724.rst
  qt/scientific_interfaces/Inelastic/Processor/ElwinModel.cpp
  qt/scientific_interfaces/Inelastic/Processor/ElwinModel.h
  qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.cpp
  qt/scientific_interfaces/Inelastic/test/Processor/ElwinModelTest.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/MockObjects.h
Labels: Indirect/Inelastic, GUI, ISIS Team: Spectroscopy

#37828 Fix error in ISIS Diagnostics tab of Indirect Reduction
  qt/widgets/spectroscopy/src/InelasticTab.cpp
Labels: Bug, Indirect/Inelastic, ISIS Team: Spectroscopy

#37844 Fix ISIS SANS Event Binning Tooltips
  docs/source/interfaces/isis_sans/Settings Tab.rst
  docs/source/release/v6.11.0/SANS/Bugfixes/37827.rst
  scripts/Interface/ui/sans_isis/sans_data_processor_window.ui
Labels: SANS, ISIS Team: LSS

#37819 Run missing tests
  Framework/API/src/LogManager.cpp
  Framework/API/test/CMakeLists.txt
  Framework/API/test/MatrixWorkspaceTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.11.0/Framework/Algorithms/Bugfixes/37819.rst
Labels: Bug, ISIS Team: Core

#37798 Fix coverity warnings on Indirect/Inelastic files
  qt/scientific_interfaces/Inelastic/Processor/ElwinPresenter.cpp
  qt/scientific_interfaces/Inelastic/Processor/SqwPresenter.cpp
  qt/scientific_interfaces/Inelastic/Processor/SymmetrisePresenter.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionQParameters.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionQParameters.h
  qt/widgets/common/src/AddWorkspaceMultiDialog.cpp
Labels: Indirect/Inelastic, ISIS Team: Spectroscopy

#37753 Add algorithm for calculating Wildes polarization efficiencies
  Framework/Algorithms/CMakeLists.txt
  Framework/Algorithms/inc/MantidAlgorithms/PolarizationCorrectionWildes.h
  Framework/Algorithms/inc/MantidAlgorithms/PolarizationCorrections/PolarizationEfficienciesWildes.h
  Framework/Algorithms/src/PolarizationCorrectionWildes.cpp
  Framework/Algorithms/src/PolarizationCorrections/PolarizationEfficienciesWildes.cpp
  Framework/Algorithms/test/PolarizationCorrections/PolarizationEfficienciesWildesTest.h
  docs/source/algorithms/PolarizationCorrectionWildes-v1.rst
  docs/source/algorithms/PolarizationEfficienciesWildes-v1.rst
  docs/source/release/v6.11.0/Reflectometry/New_features/35682.rst
Labels: Reflectometry, ISIS Team: LSS

#37789 Fix typo in IndirectResolution documentation
  Framework/Algorithms/src/CalculateIqt.cpp
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectResolution.py
Labels: Bug, Indirect/Inelastic, ISIS Team: Spectroscopy, ORNL Team

#37684 37376 texts on the mantid workbench main menu could not be seen on osx dark mode
  docs/source/release/v6.11.0/Workbench/New_features/37376.rst
  images/DropDownArrow.png
  qt/applications/workbench/workbench/widgets/about/view.py
Labels: macOS Only, ISIS Team: Core

#37767 Add option to not delete subtracted workspace in container subtraction tab
  docs/source/interfaces/inelastic/Inelastic Corrections.rst
  docs/source/release/v6.11.0/Inelastic/New_features/37763.rst
  qt/scientific_interfaces/Inelastic/Corrections/ApplyAbsorptionCorrections.cpp
  qt/scientific_interfaces/Inelastic/Corrections/ContainerSubtraction.cpp
  qt/scientific_interfaces/Inelastic/Corrections/ContainerSubtraction.h
  qt/scientific_interfaces/Inelastic/Corrections/ContainerSubtraction.ui
Labels: Absorption Corrections, Reported By User

#37777 37626 remove references to the ads from heliumanalyserefficiency algorithm
  Framework/Algorithms/inc/MantidAlgorithms/PolarizationCorrections/HeliumAnalyserEfficiency.h
  Framework/Algorithms/src/PolarizationCorrections/HeliumAnalyserEfficiency.cpp
  Framework/Algorithms/test/PolarizationCorrections/HeliumAnalyserEfficiencyTest.h
Labels: SANS, Maintenance, ISIS Team: LSS

#37643 Allow Determination of Workspace Order from Output of PolarizationCorrectionWildes
  Framework/Algorithms/inc/MantidAlgorithms/PolarizationCorrectionWildes.h
  Framework/Algorithms/inc/MantidAlgorithms/PolarizationCorrections/PolarizationCorrectionsHelpers.h
  Framework/Algorithms/inc/MantidAlgorithms/PolarizationCorrections/SpinStateValidator.h
  Framework/Algorithms/inc/MantidAlgorithms/PolarizationEfficiencyCor.h
  Framework/Algorithms/src/PolarizationCorrectionWildes.cpp
  Framework/Algorithms/src/PolarizationCorrections/FlipperEfficiency.cpp
  Framework/Algorithms/src/PolarizationCorrections/HeliumAnalyserEfficiency.cpp
  Framework/Algorithms/src/PolarizationCorrections/PolarizationEfficienciesWildes.cpp
  Framework/Algorithms/src/PolarizationCorrections/PolarizerEfficiency.cpp
  Framework/Algorithms/src/PolarizationCorrections/SpinStateValidator.cpp
  Framework/Algorithms/src/PolarizationEfficiencyCor.cpp
  Framework/Algorithms/test/PolarizationCorrectionWildesTest.h
  Framework/Algorithms/test/PolarizationCorrections/SpinStateValidatorTest.h
  docs/source/algorithms/PolarizationCorrectionWildes-v1.rst
  docs/source/algorithms/PolarizationEfficiencyCor-v1.rst
  docs/source/release/v6.11.0/Framework/Algorithms/New_features/35067.rst
Labels: Reflectometry, SANS, Framework, ISIS Team: LSS

#37710 Run isCommonBins using multiple threads for greater speed
  Framework/API/inc/MantidAPI/MatrixWorkspace.h
  Framework/API/src/MatrixWorkspace.cpp
  Framework/API/test/MatrixWorkspaceTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Extra Attention, ISIS Team: Core

#37816 add FilterByTime functionality
  Framework/DataHandling/src/BankPulseTimes.cpp
  Framework/DataHandling/src/LoadEventAsWorkspace2D.cpp
  Framework/DataHandling/test/LoadEventAsWorkspace2DTest.h
  docs/source/release/v6.11.0/Framework/Algorithms/New_features/37816.rst
Labels: Framework, ORNL Team

#37847 Correct bug of missing 'Hmag' field in CrystalField interface
  docs/source/release/v6.11.0/Direct_Geometry/CrystalField/Bugfixes/37847.rst
  scripts/Inelastic/CrystalField/function.py
  scripts/test/CrystalFieldTest.py
Labels: Bug, ISIS Team: Excitations/Vesuvio

#37874 Improve clang-tidy docs
  buildconfig/CMake/ClangTidy.cmake
  dev-docs/source/ToolsOverview.rst
Labels: Documentation

#37872 PG3StripPeaks to not use AlignDetectors algorithm
  Testing/SystemTests/tests/framework/SNSPowderRedux.py
Labels: Maintenance

#37658 Unpin libcxx for OSX
  Framework/DataHandling/inc/MantidDataHandling/PDLoadCharacterizations.h
  Framework/DataHandling/src/LoadNexusLogs.cpp
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid/meta.yaml
  conda/recipes/mantidqt/meta.yaml
  mantid-developer-osx.yml
Labels: Maintenance, ISIS Team: Core

#37848 Add warning on QENS Fitting interface for missing workspaces
  docs/source/release/v6.11.0/Inelastic/Bugfixes/37706.rst
  qt/scientific_interfaces/Inelastic/QENSFitting/FitDataPresenter.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FitDataPresenter.h
  qt/widgets/common/inc/MantidQtWidgets/Common/WorkspaceUtils.h
  qt/widgets/common/src/WorkspaceUtils.cpp
Labels: Bug, Indirect/Inelastic

#37885 Fix latest coverity warnings
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  qt/scientific_interfaces/Inelastic/Corrections/ContainerSubtraction.cpp
Labels: Maintenance, ISIS Team: Spectroscopy, ISIS Team: Core

#37815 LoadEventNexus change tofmin to be at the lowest event's tof
  Framework/DataHandling/src/LoadEventNexus.cpp
  Framework/DataHandling/test/LoadEventNexusTest.h
  Testing/Data/SystemTest/3132_Orthorhombic_P.integrate.nxs.md5
  Testing/Data/SystemTest/PowderReduceP2D_reference.p2d.md5
  Testing/SystemTests/tests/framework/TOPAZPeakFinding.py
  Testing/SystemTests/tests/framework/reference/ReflectometryApplyFloodWorkspace.nxs.md5
  docs/source/release/v6.11.0/Framework/Algorithms/Bugfixes/37815.rst
Labels: Bug

#37892 Migrate boost::filesystem to std::filesystem
  Framework/API/inc/MantidAPI/ScopedWorkspace.h
  Framework/API/src/ScopedWorkspace.cpp
  Framework/API/test/CMakeLists.txt
  Framework/Algorithms/CMakeLists.txt
  Framework/Algorithms/src/CorelliCalibrationDatabase.cpp
  Framework/Algorithms/test/CMakeLists.txt
  Framework/Algorithms/test/CorelliCalibrationDatabaseTest.h
  Framework/Crystal/CMakeLists.txt
  Framework/Crystal/src/SCDCalibratePanels2.cpp
  Framework/Crystal/test/CMakeLists.txt
  Framework/Crystal/test/SCDCalibratePanels2ObjFuncTest.h
  Framework/Crystal/test/SCDCalibratePanels2Test.h
  Framework/Crystal/test/SCDCalibratePanelsTest.h
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/src/LoadEMU.cpp
  Framework/DataHandling/src/LoadPLN.cpp
  Framework/DataHandling/src/LoadPSIMuonBin.cpp
  Framework/DataHandling/test/CMakeLists.txt
  Framework/DataHandling/test/SaveNexusESSTest.h
  Framework/Kernel/inc/MantidKernel/Strings.h
  Framework/Kernel/src/Strings.cpp
  Framework/Kernel/test/CMakeLists.txt
  Framework/Kernel/test/FileValidatorTest.h
  Framework/Kernel/test/StringsTest.h
  Framework/NexusGeometry/CMakeLists.txt
  Framework/NexusGeometry/src/NexusGeometrySave.cpp
  Framework/NexusGeometry/test/CMakeLists.txt
  Framework/PythonInterface/test/cpp/PythonStdoutChannelTest.h
  Framework/TestHelpers/CMakeLists.txt
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/FileResource.h
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/NexusFileReader.h
  Framework/TestHelpers/src/FileResource.cpp
  Framework/WorkflowAlgorithms/CMakeLists.txt
  Framework/WorkflowAlgorithms/src/SofTwoThetaTOF.cpp
  Framework/WorkflowAlgorithms/test/CMakeLists.txt
  Framework/WorkflowAlgorithms/test/SofTwoThetaTOFTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  buildconfig/CMake/TestTargetFunctions.cmake
  qt/applications/workbench/mantidworkbench.cpp
Labels: Maintenance

#37839 storeInADS preserved in algorithm history and recreated correctly by script builder
  Framework/API/inc/MantidAPI/AlgorithmHistory.h
  Framework/API/inc/MantidAPI/Workspace.h
  Framework/API/inc/MantidAPI/WorkspaceProperty.tcc
  Framework/API/src/AlgorithmHistory.cpp
  Framework/API/src/ScriptBuilder.cpp
  Framework/API/src/Workspace.cpp
  Framework/API/test/ScriptBuilderTest.h
  Framework/Kernel/inc/MantidKernel/PropertyHistory.h
  Framework/Kernel/src/PropertyHistory.cpp
  Framework/PythonInterface/mantid/api/src/Exports/AlgorithmHistory.cpp
  Framework/PythonInterface/test/python/mantid/api/AlgorithmHistoryTest.py
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.11.0/Workbench/Bugfixes/33252.rst
  qt/widgets/common/src/AlgorithmHistoryWindow.cpp
Labels: Bug, ISIS Team: Core

#37869 Remove RecordPythonScript algorithm
  Framework/Algorithms/CMakeLists.txt
  Framework/Algorithms/inc/MantidAlgorithms/GenerateIPythonNotebook.h
  Framework/Algorithms/inc/MantidAlgorithms/GeneratePythonScript.h
  Framework/Algorithms/inc/MantidAlgorithms/RecordPythonScript.h
  Framework/Algorithms/src/RecordPythonScript.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/algorithms/RecordPythonScript-v1.rst
  docs/source/release/v6.11.0/Framework/Algorithms/Removed/37869.rst
Labels: Framework, ISIS Team: Core

#37814 Fix bug polaris total scattering normalisation for multi-atom unit cells
  Testing/SystemTests/tests/framework/ISIS_PowderPolarisTest.py
  Testing/SystemTests/tests/framework/reference/ISIS_Powder-POLARIS98533_FocusMayers.nxs.md5
  Testing/SystemTests/tests/framework/reference/ISIS_Powder-POLARIS98533_FocusPaalmanPings.nxs.md5
  docs/source/release/v6.11.0/Diffraction/Powder/Bugfixes/37814.rst
  scripts/Diffraction/isis_powder/polaris_routines/polaris_algs.py
Labels: Diffraction, Powder, ISIS Team: Diffraction
