Repository mantidproject/mantid, pull requests merged in 2025-02, with the labels that each got.

#38777 Fix a performance issue in SumSpectra with EventWorkspace
  Framework/Algorithms/src/SumSpectra.cpp
Labels: Bug

#38760 Delete SaveToSNSHistogramNexus :wastebasket:
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/SaveToSNSHistogramNexus.h
  Framework/DataHandling/src/SaveToSNSHistogramNexus.cpp
  Framework/DataHandling/test/SaveToSNSHistogramNexusTest.h
  docs/source/algorithms/SaveToSNSHistogramNexus-v1.rst
  docs/source/release/v6.13.0/Framework/Data_Handling/Removed/38760.rst
  qt/applications/workbench/workbench/utils/workspacehistorygeneration.py
Labels: ORNL Team, Technical Debt

#38780 Delete SaveToSNSHistogramNexus
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/SaveToSNSHistogramNexus.h
  Framework/DataHandling/src/SaveToSNSHistogramNexus.cpp
  Framework/DataHandling/test/SaveToSNSHistogramNexusTest.h
  docs/source/algorithms/SaveToSNSHistogramNexus-v1.rst
  docs/source/release/v6.13.0/Framework/Data_Handling/Removed/38760.rst
  qt/applications/workbench/workbench/utils/workspacehistorygeneration.py
Labels: ornl-next

#38759 Cppcheck suppression team delta - set 61
  Framework/SINQ/inc/MantidSINQ/PoldiPeakSearch.h
  Framework/SINQ/inc/MantidSINQ/PoldiUtilities/MillerIndices.h
  Framework/SINQ/inc/MantidSINQ/PoldiUtilities/PoldiAutoCorrelationCore.h
  Framework/SINQ/inc/MantidSINQ/PoldiUtilities/PoldiInstrumentAdapter.h
  Framework/SINQ/inc/MantidSINQ/PoldiUtilities/PoldiPeak.h
  Framework/SINQ/inc/MantidSINQ/PoldiUtilities/PoldiPeakCollection.h
  Framework/SINQ/inc/MantidSINQ/SliceMDHisto.h
  Framework/SINQ/src/PoldiCreatePeaksFromCell.cpp
  Framework/SINQ/src/PoldiFitPeaks1D2.cpp
  Framework/SINQ/src/PoldiFitPeaks2D.cpp
  Framework/SINQ/src/PoldiIndexKnownCompounds.cpp
  Framework/SINQ/src/PoldiPeakSearch.cpp
  Framework/SINQ/src/PoldiUtilities/MillerIndices.cpp
  Framework/SINQ/src/PoldiUtilities/PoldiAutoCorrelationCore.cpp
  Framework/SINQ/src/PoldiUtilities/PoldiInstrumentAdapter.cpp
  Framework/SINQ/src/PoldiUtilities/PoldiPeak.cpp
  Framework/SINQ/src/PoldiUtilities/PoldiPeakCollection.cpp
  Framework/SINQ/src/SliceMDHisto.cpp
  Framework/SINQ/test/PoldiFitPeaks1D2Test.h
  Framework/SINQ/test/PoldiFitPeaks2DTest.h
  Framework/SINQ/test/PoldiPeakCollectionTest.h
  Framework/SINQ/test/PoldiPeakTest.h
  Framework/ScriptRepository/inc/MantidScriptRepository/ScriptRepositoryImpl.h
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/FakeObjects.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance

#38781 Fix a performance issue in SumSpectra with EventWorkspace - ornl-next
  Framework/Algorithms/src/SumSpectra.cpp
Labels: ornl-next

#38782 Migrate SaveNexusProcessedHelper from napi to NeXusFile -- `ornl-next`
  Framework/DataHandling/inc/MantidDataHandling/LoadNexus.h
  Framework/DataHandling/inc/MantidDataHandling/SaveNexusProcessedHelper.h
  Framework/DataHandling/src/LoadNexus.cpp
  Framework/DataHandling/src/SaveNexusProcessed.cpp
  Framework/DataHandling/src/SaveNexusProcessedHelper.cpp
  Framework/DataHandling/src/StartAndEndTimeFromNexusFileExtractor.cpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile.hpp
  Framework/NexusCpp/src/NeXusFile.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: ORNL Team, Technical Debt, ornl-next

#38766 Refactor LoadHelper to use NeXus::File
  Framework/DataHandling/inc/MantidDataHandling/LoadHelper.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLIndirect2.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLSANS.h
  Framework/DataHandling/src/LoadEventNexus.cpp
  Framework/DataHandling/src/LoadHelper.cpp
  Framework/DataHandling/src/LoadILLDiffraction.cpp
  Framework/DataHandling/src/LoadILLIndirect2.cpp
  Framework/DataHandling/src/LoadILLLagrange.cpp
  Framework/DataHandling/src/LoadILLPolarizedDiffraction.cpp
  Framework/DataHandling/src/LoadILLReflectometry.cpp
  Framework/DataHandling/src/LoadILLSALSA.cpp
  Framework/DataHandling/src/LoadILLSANS.cpp
  Framework/DataHandling/src/LoadILLTOF2.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance

#38784 Refactor LoadHelper to use NeXus::File - `ornl-next`
  Framework/DataHandling/inc/MantidDataHandling/LoadHelper.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLIndirect2.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLSANS.h
  Framework/DataHandling/src/LoadEventNexus.cpp
  Framework/DataHandling/src/LoadHelper.cpp
  Framework/DataHandling/src/LoadILLDiffraction.cpp
  Framework/DataHandling/src/LoadILLIndirect2.cpp
  Framework/DataHandling/src/LoadILLLagrange.cpp
  Framework/DataHandling/src/LoadILLPolarizedDiffraction.cpp
  Framework/DataHandling/src/LoadILLReflectometry.cpp
  Framework/DataHandling/src/LoadILLSALSA.cpp
  Framework/DataHandling/src/LoadILLSANS.cpp
  Framework/DataHandling/src/LoadILLTOF2.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: ornl-next

#38764 Fix crash on inelastic symmetrise interface
  qt/widgets/common/inc/MantidQtWidgets/Common/UserInputValidator.h
  qt/widgets/common/src/UserInputValidator.cpp
Labels: Bug

#38772 Fix segfaulting doctest
  docs/source/algorithms/StartLiveData-v1.rst
Labels: Bug

#38758 Refactor adding new batches in ISIS Reflectometry GUI
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/IBatchPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/MainWindow/MainWindowPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/MainWindow/MainWindowPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Runs/IRunsPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Runs/QtRunsView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Runs/RunsPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Runs/RunsPresenter.h
  qt/scientific_interfaces/ISISReflectometry/test/Batch/BatchPresenterTest.h
  qt/scientific_interfaces/ISISReflectometry/test/MainWindow/MainWindowPresenterTest.h
  qt/scientific_interfaces/ISISReflectometry/test/ReflMockObjects.h
  qt/scientific_interfaces/ISISReflectometry/test/Runs/RunsPresenterTest.h
Labels: Reflectometry, Maintenance, ISIS Team: LSS

#38786 Move all HDF5 loading algorithms to NexusHDF5Descriptor
  Framework/API/src/FileLoaderRegistry.cpp
  Framework/DataHandling/inc/MantidDataHandling/LoadEMU.h
  Framework/DataHandling/inc/MantidDataHandling/LoadEventNexus.h
  Framework/DataHandling/inc/MantidDataHandling/LoadGeometry.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLDiffraction.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLIndirect2.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLLagrange.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLPolarizedDiffraction.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLReflectometry.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLSALSA.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLSANS.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLTOF2.h
  Framework/DataHandling/inc/MantidDataHandling/LoadISISNexus2.h
  Framework/DataHandling/inc/MantidDataHandling/LoadMLZ.h
  Framework/DataHandling/inc/MantidDataHandling/LoadNXSPE.h
  Framework/DataHandling/inc/MantidDataHandling/LoadNXcanSAS.h
  Framework/DataHandling/inc/MantidDataHandling/LoadNexusProcessed2.h
  Framework/DataHandling/inc/MantidDataHandling/LoadPLN.h
  Framework/DataHandling/inc/MantidDataHandling/LoadQKK.h
  Framework/DataHandling/inc/MantidDataHandling/LoadSINQFocus.h
  Framework/DataHandling/inc/MantidDataHandling/LoadSassena.h
  Framework/DataHandling/inc/MantidDataHandling/LoadTOFRawNexus.h
  Framework/DataHandling/inc/MantidDataHandling/ProcessBankData.h
  Framework/DataHandling/src/Load.cpp
  Framework/DataHandling/src/LoadEMU.cpp
  Framework/DataHandling/src/LoadGeometry.cpp
  Framework/DataHandling/src/LoadILLDiffraction.cpp
  Framework/DataHandling/src/LoadILLIndirect2.cpp
  Framework/DataHandling/src/LoadILLLagrange.cpp
  Framework/DataHandling/src/LoadILLPolarizedDiffraction.cpp
  Framework/DataHandling/src/LoadILLReflectometry.cpp
  Framework/DataHandling/src/LoadILLSALSA.cpp
  Framework/DataHandling/src/LoadILLSANS.cpp
  Framework/DataHandling/src/LoadILLTOF2.cpp
  Framework/DataHandling/src/LoadISISNexus2.cpp
  Framework/DataHandling/src/LoadMLZ.cpp
  Framework/DataHandling/src/LoadMcStas.cpp
  Framework/DataHandling/src/LoadMuonNexusV2.cpp
  Framework/DataHandling/src/LoadNXSPE.cpp
  Framework/DataHandling/src/LoadNXcanSAS.cpp
  Framework/DataHandling/src/LoadPLN.cpp
  Framework/DataHandling/src/LoadQKK.cpp
  Framework/DataHandling/src/LoadSINQFocus.cpp
  Framework/DataHandling/src/LoadSassena.cpp
  Framework/DataHandling/src/LoadTOFRawNexus.cpp
  Framework/DataHandling/src/UpdateInstrumentFromFile.cpp
  Framework/DataHandling/test/LoadILLIndirect2Test.h
  Framework/DataHandling/test/LoadQKKTest.h
  Framework/DataHandling/test/LoadSassenaTest.h
  Framework/DataHandling/test/LoadTOFRawNexusTest.h
  Framework/Kernel/inc/MantidKernel/NexusDescriptor.h
  Framework/Kernel/inc/MantidKernel/NexusHDF5Descriptor.h
  Framework/Kernel/src/NexusDescriptor.cpp
  Framework/Kernel/src/NexusHDF5Descriptor.cpp
  Framework/Kernel/test/NexusDescriptorTest.h
  Framework/Kernel/test/NexusHDF5DescriptorTest.h
  Framework/MDAlgorithms/inc/MantidMDAlgorithms/LoadMD.h
  scripts/test/corelli/calibration/test_database.py
Labels: Technical Debt

#38792 Move all HDF5 loading algorithms to NexusHDF5Descriptor
  Framework/API/src/FileLoaderRegistry.cpp
  Framework/DataHandling/inc/MantidDataHandling/LoadEMU.h
  Framework/DataHandling/inc/MantidDataHandling/LoadEventNexus.h
  Framework/DataHandling/inc/MantidDataHandling/LoadGeometry.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLDiffraction.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLIndirect2.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLLagrange.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLPolarizedDiffraction.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLReflectometry.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLSALSA.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLSANS.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLTOF2.h
  Framework/DataHandling/inc/MantidDataHandling/LoadISISNexus2.h
  Framework/DataHandling/inc/MantidDataHandling/LoadMLZ.h
  Framework/DataHandling/inc/MantidDataHandling/LoadNXSPE.h
  Framework/DataHandling/inc/MantidDataHandling/LoadNXcanSAS.h
  Framework/DataHandling/inc/MantidDataHandling/LoadNexusProcessed2.h
  Framework/DataHandling/inc/MantidDataHandling/LoadPLN.h
  Framework/DataHandling/inc/MantidDataHandling/LoadQKK.h
  Framework/DataHandling/inc/MantidDataHandling/LoadSINQFocus.h
  Framework/DataHandling/inc/MantidDataHandling/LoadSassena.h
  Framework/DataHandling/inc/MantidDataHandling/LoadTOFRawNexus.h
  Framework/DataHandling/inc/MantidDataHandling/ProcessBankData.h
  Framework/DataHandling/src/Load.cpp
  Framework/DataHandling/src/LoadEMU.cpp
  Framework/DataHandling/src/LoadGeometry.cpp
  Framework/DataHandling/src/LoadILLDiffraction.cpp
  Framework/DataHandling/src/LoadILLIndirect2.cpp
  Framework/DataHandling/src/LoadILLLagrange.cpp
  Framework/DataHandling/src/LoadILLPolarizedDiffraction.cpp
  Framework/DataHandling/src/LoadILLReflectometry.cpp
  Framework/DataHandling/src/LoadILLSALSA.cpp
  Framework/DataHandling/src/LoadILLSANS.cpp
  Framework/DataHandling/src/LoadILLTOF2.cpp
  Framework/DataHandling/src/LoadISISNexus2.cpp
  Framework/DataHandling/src/LoadMLZ.cpp
  Framework/DataHandling/src/LoadMcStas.cpp
  Framework/DataHandling/src/LoadMuonNexusV2.cpp
  Framework/DataHandling/src/LoadNXSPE.cpp
  Framework/DataHandling/src/LoadNXcanSAS.cpp
  Framework/DataHandling/src/LoadPLN.cpp
  Framework/DataHandling/src/LoadQKK.cpp
  Framework/DataHandling/src/LoadSINQFocus.cpp
  Framework/DataHandling/src/LoadSassena.cpp
  Framework/DataHandling/src/LoadTOFRawNexus.cpp
  Framework/DataHandling/src/UpdateInstrumentFromFile.cpp
  Framework/DataHandling/test/LoadILLIndirect2Test.h
  Framework/DataHandling/test/LoadQKKTest.h
  Framework/DataHandling/test/LoadSassenaTest.h
  Framework/DataHandling/test/LoadTOFRawNexusTest.h
  Framework/Kernel/inc/MantidKernel/NexusDescriptor.h
  Framework/Kernel/inc/MantidKernel/NexusHDF5Descriptor.h
  Framework/Kernel/src/NexusDescriptor.cpp
  Framework/Kernel/src/NexusHDF5Descriptor.cpp
  Framework/Kernel/test/NexusDescriptorTest.h
  Framework/Kernel/test/NexusHDF5DescriptorTest.h
  Framework/MDAlgorithms/inc/MantidMDAlgorithms/LoadMD.h
  scripts/test/corelli/calibration/test_database.py
Labels: ornl-next

#38794 Remove LoadLLB
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/LoadLLB.h
  Framework/DataHandling/src/LoadLLB.cpp
  Framework/DataHandling/test/LoadLLBTest.h
  Testing/Data/UnitTest/LLB_d22418.nxs.md5
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/algorithms/LoadLLB-v1.rst
  docs/source/release/v6.13.0/Framework/Algorithms/Removed/38794.rst
Labels: Technical Debt

#38796 Remove LoadLLB
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/LoadLLB.h
  Framework/DataHandling/src/LoadLLB.cpp
  Framework/DataHandling/test/LoadLLBTest.h
  Testing/Data/UnitTest/LLB_d22418.nxs.md5
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/algorithms/LoadLLB-v1.rst
  docs/source/release/v6.13.0/Framework/Algorithms/Removed/38794.rst
Labels: ornl-next

#38787 Update non-peak plus background starting parameters in mantid basic course
  docs/source/tutorials/mantid_basic_course/fitting_data/03_fit_model_choices.rst
Labels: Documentation, Maintenance

#38731 Bravo team cppcheck set 41
  Framework/Geometry/inc/MantidGeometry/Instrument/InstrumentDefinitionParser.h
  Framework/Geometry/inc/MantidGeometry/Instrument/XMLInstrumentParameter.h
  Framework/Geometry/src/Instrument/InstrumentDefinitionParser.cpp
  Framework/Geometry/src/Instrument/ObjCompAssembly.cpp
  Framework/Geometry/src/Instrument/XMLInstrumentParameter.cpp
  Framework/Geometry/src/Math/Acomp.cpp
  Framework/Geometry/src/Objects/CSGObject.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance

#38793 Remove SaveISISNexus
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/LoadISISNexus2.h
  Framework/DataHandling/inc/MantidDataHandling/SaveISISNexus.h
  Framework/DataHandling/inc/MantidDataHandling/SaveNexus.h
  Framework/DataHandling/inc/MantidDataHandling/SaveNexusProcessed.h
  Framework/DataHandling/src/SaveISISNexus.cpp
  docs/source/algorithms/SaveISISNexus-v1.rst
  docs/source/release/v6.13.0/Framework/Algorithms/Removed/38793.rst
  qt/applications/workbench/workbench/utils/workspacehistorygeneration.py
Labels: Technical Debt

#38808 Remove SaveISISNexus - ornl-next
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/LoadISISNexus2.h
  Framework/DataHandling/inc/MantidDataHandling/SaveISISNexus.h
  Framework/DataHandling/inc/MantidDataHandling/SaveNexus.h
  Framework/DataHandling/inc/MantidDataHandling/SaveNexusProcessed.h
  Framework/DataHandling/src/SaveISISNexus.cpp
  docs/source/algorithms/SaveISISNexus-v1.rst
  docs/source/release/v6.13.0/Framework/Algorithms/Removed/38793.rst
  qt/applications/workbench/workbench/utils/workspacehistorygeneration.py
Labels: ornl-next

#38809 Only log that an invalid monitor was seen once - ornl-next
  Framework/LiveData/inc/MantidLiveData/SNSLiveEventDataListener.h
  Framework/LiveData/src/SNSLiveEventDataListener.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.13.0/Framework/New_features/38803.rst
Labels: ornl-next

#38812 Copy nexus functions into new subpackage for muons - ornl-next
  Framework/CMakeLists.txt
  Framework/LegacyNexus/CMakeLists.txt
  Framework/LegacyNexus/inc/MantidLegacyNexus/NeXusException.hpp
  Framework/LegacyNexus/inc/MantidLegacyNexus/NeXusFile.hpp
  Framework/LegacyNexus/inc/MantidLegacyNexus/NeXusFile_fwd.h
  Framework/LegacyNexus/inc/MantidLegacyNexus/napi.h
  Framework/LegacyNexus/inc/MantidLegacyNexus/napi4.h
  Framework/LegacyNexus/inc/MantidLegacyNexus/napi5.h
  Framework/LegacyNexus/inc/MantidLegacyNexus/napi_internal.h
  Framework/LegacyNexus/inc/MantidLegacyNexus/napiconfig.h
  Framework/LegacyNexus/inc/MantidLegacyNexus/nx_stptok.h
  Framework/LegacyNexus/inc/MantidLegacyNexus/nxstack.h
  Framework/LegacyNexus/src/NeXusException.cpp
  Framework/LegacyNexus/src/NeXusFile.cpp
  Framework/LegacyNexus/src/napi.cpp
  Framework/LegacyNexus/src/napi4.cpp
  Framework/LegacyNexus/src/napi5.cpp
  Framework/LegacyNexus/src/nxstack.cpp
  Framework/LegacyNexus/src/stptok.cpp
  Framework/LegacyNexus/test/leak_test1.cpp
  Framework/LegacyNexus/test/leak_test2.cpp
  Framework/LegacyNexus/test/leak_test3.cpp
  Framework/LegacyNexus/test/napi_attra_test.cpp
  Framework/LegacyNexus/test/napi_test.cpp
  Framework/LegacyNexus/test/napi_test_cpp.cpp
  Framework/LegacyNexus/test/napi_test_util.cpp
  Framework/LegacyNexus/test/napi_test_util.h
  Framework/LegacyNexus/test/test_nxunlimited.cpp
Labels: ornl-next

#38779 Cppcheck delta set 54
  Framework/Muon/inc/MantidMuon/PlotAsymmetryByLogValue.h
  Framework/Muon/src/LoadMuonNexus2.cpp
  Framework/Muon/src/PlotAsymmetryByLogValue.cpp
  Framework/NexusGeometry/src/NexusShapeFactory.cpp
  Framework/Parallel/inc/MantidParallel/IO/EventsListsShmemStorage.h
  Framework/PythonInterface/core/inc/MantidPythonInterface/core/DataServiceExporter.h
  Framework/PythonInterface/core/inc/MantidPythonInterface/core/IsNone.h
  Framework/PythonInterface/core/src/Converters/CloneToNDArray.cpp
  Framework/PythonInterface/core/src/Converters/NDArrayToVector.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance

#38817 Patch struct name in LegacyNexus napi -- `ornl-next`
  Framework/LegacyNexus/src/napi4.cpp
  Framework/LegacyNexus/src/napi5.cpp
Labels: ORNL Team, ornl-next

#38818 Remove napi from NexusClasses - ornl-next
  Framework/API/src/FrameworkManager.cpp
  Framework/DataHandling/src/LoadEventNexus.cpp
  Framework/DataHandling/src/LoadHelper.cpp
  Framework/DataHandling/src/LoadNexus.cpp
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  Framework/DataHandling/src/LoadTOFRawNexus.cpp
  Framework/DataHandling/src/NexusTester.cpp
  Framework/DataHandling/src/SaveNexusProcessed.cpp
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/src/NexusClasses.cpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusException.hpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile.hpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile_fwd.h
  Framework/NexusCpp/inc/MantidNexusCpp/napi.h
  Framework/NexusCpp/src/NeXusException.cpp
  Framework/NexusCpp/src/NeXusFile.cpp
  Framework/NexusGeometry/src/NexusGeometryParser.cpp
Labels: ornl-next

#38816 Change name from HDF4 to Legacy
  Framework/LegacyNexus/inc/MantidLegacyNexus/napi4.h
  Framework/LegacyNexus/inc/MantidLegacyNexus/napi5.h
  Framework/LegacyNexus/inc/MantidLegacyNexus/napi_internal.h
  Framework/LegacyNexus/inc/MantidLegacyNexus/nxstack.h
  Framework/LegacyNexus/src/napi.cpp
  Framework/LegacyNexus/src/napi4.cpp
  Framework/LegacyNexus/src/napi5.cpp
  Framework/LegacyNexus/src/nxstack.cpp
Labels: Maintenance

#38753 Fix cppcheck suppressions set 8
  Framework/Algorithms/inc/MantidAlgorithms/AddLogDerivative.h
  Framework/Algorithms/inc/MantidAlgorithms/AddTimeSeriesLog.h
  Framework/Algorithms/inc/MantidAlgorithms/AnnularRingAbsorption.h
  Framework/Algorithms/inc/MantidAlgorithms/AppendSpectra.h
  Framework/Algorithms/src/AbsorptionCorrection.cpp
  Framework/Algorithms/src/AddLogDerivative.cpp
  Framework/Algorithms/src/AddTimeSeriesLog.cpp
  Framework/Algorithms/src/AnnularRingAbsorption.cpp
  Framework/Algorithms/src/AppendSpectra.cpp
  Framework/Algorithms/src/ApplyDetailedBalance.cpp
  Framework/Algorithms/src/AverageLogData.cpp
  Framework/Algorithms/src/CalculateCountRate.cpp
  Framework/Algorithms/src/CalculateEfficiency.cpp
  Framework/Algorithms/src/CalculatePlaczek.cpp
  Framework/Algorithms/src/CalculatePolynomialBackground.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance

#38729 Fix cpp suppression set 34 - Team Alpha
  Framework/DataHandling/inc/MantidDataHandling/LoadTBL.h
  Framework/DataHandling/src/LoadSpiceXML2DDet.cpp
  Framework/DataHandling/src/LoadTBL.cpp
  Framework/DataHandling/src/LoadTOFRawNexus.cpp
  Framework/DataHandling/src/MaskDetectors.cpp
  Framework/DataHandling/src/RotateSampleShape.cpp
  Framework/DataHandling/src/SaveCSV.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance

#38618 Add additional support for saving data using the ISIS Sans Command Interface
  docs/source/release/v6.13.0/SANS/New_features/38502.rst
  docs/source/techniques/ScriptingSANSReductions.rst
  scripts/SANS/ISISCommandInterface.py
  scripts/SANS/sans/command_interface/ISISCommandInterface.py
  scripts/test/SANS/command_interface/isis_command_interface_test.py
Labels: SANS, ISIS Team: LSS

#38804 Release notes v6.12.0 - Diffraction
  docs/source/release/v6.12.0/Diffraction/Engineering/Bugfixes/Used/35596.rst
  docs/source/release/v6.12.0/Diffraction/Engineering/Bugfixes/Used/38444.rst
  docs/source/release/v6.12.0/Diffraction/Powder/Bugfixes/Used/38399.rst
  docs/source/release/v6.12.0/Diffraction/Powder/Bugfixes/Used/38534.rst
  docs/source/release/v6.12.0/Diffraction/Powder/New_features/Used/38154.rst
  docs/source/release/v6.12.0/Diffraction/Powder/New_features/Used/38188.rst
  docs/source/release/v6.12.0/Diffraction/Powder/New_features/Used/38323.rst
  docs/source/release/v6.12.0/Diffraction/Powder/New_features/Used/38340.rst
  docs/source/release/v6.12.0/Diffraction/Powder/New_features/Used/38404.rst
  docs/source/release/v6.12.0/Diffraction/Powder/New_features/Used/38535.rst
  docs/source/release/v6.12.0/Diffraction/Powder/New_features/Used/38541.rst
  docs/source/release/v6.12.0/Diffraction/Single_Crystal/Bugfixes/Used/38512.rst
  docs/source/release/v6.12.0/Diffraction/Single_Crystal/Bugfixes/Used/38605.rst
  docs/source/release/v6.12.0/Diffraction/Single_Crystal/New_features/Used/36863.rst
  docs/source/release/v6.12.0/Diffraction/Single_Crystal/New_features/Used/37166.rst
  docs/source/release/v6.12.0/Diffraction/Single_Crystal/New_features/Used/38254.rst
  docs/source/release/v6.12.0/Diffraction/Single_Crystal/New_features/Used/38337.rst
  docs/source/release/v6.12.0/Diffraction/Single_Crystal/New_features/Used/38363.rst
  docs/source/release/v6.12.0/Diffraction/Single_Crystal/New_features/Used/38515.rst
  docs/source/release/v6.12.0/diffraction.rst
Labels: Documentation

#38820 Change name from HDF4 to Legacy - ornl-next
  Framework/LegacyNexus/inc/MantidLegacyNexus/napi4.h
  Framework/LegacyNexus/inc/MantidLegacyNexus/napi5.h
  Framework/LegacyNexus/inc/MantidLegacyNexus/napi_internal.h
  Framework/LegacyNexus/inc/MantidLegacyNexus/nxstack.h
  Framework/LegacyNexus/src/napi.cpp
  Framework/LegacyNexus/src/napi4.cpp
  Framework/LegacyNexus/src/napi5.cpp
  Framework/LegacyNexus/src/nxstack.cpp
Labels: ornl-next

#38815 Divide - New Optional Argument - IsDistribution
  Framework/Algorithms/inc/MantidAlgorithms/Divide.h
  Framework/Algorithms/src/Divide.cpp
  Framework/Algorithms/test/MultiplyDivideTest.in.h
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/38815.rst
Labels: Framework, ORNL Team

#38822 Divide - New Optional Argument - IsDistribution [Sibling]
  Framework/Algorithms/inc/MantidAlgorithms/Divide.h
  Framework/Algorithms/src/Divide.cpp
  Framework/Algorithms/test/MultiplyDivideTest.in.h
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/38815.rst
Labels: Framework, ORNL Team, ornl-next

#37799 Remove AlignDetectors algorithm
  Framework/Algorithms/CMakeLists.txt
  Framework/Algorithms/inc/MantidAlgorithms/AlignDetectors.h
  Framework/Algorithms/inc/MantidAlgorithms/CreateCalFileByNames.h
  Framework/Algorithms/inc/MantidAlgorithms/CreateDummyCalFile.h
  Framework/Algorithms/inc/MantidAlgorithms/DiffractionFocussing2.h
  Framework/Algorithms/inc/MantidAlgorithms/ReadGroupsFromFile.h
  Framework/Algorithms/src/AlignDetectors.cpp
  Framework/Algorithms/test/AlignDetectorsTest.h
  Framework/Algorithms/test/DiffractionFocussing2Test.h
  Framework/DataHandling/inc/MantidDataHandling/ApplyDiffCal.h
  Framework/DataHandling/inc/MantidDataHandling/LoadCalFile.h
  Framework/DataHandling/inc/MantidDataHandling/SaveCalFile.h
  Framework/DataHandling/src/SaveGDA.cpp
  Framework/DataObjects/inc/MantidDataObjects/OffsetsWorkspace.h
  Framework/PythonInterface/plugins/algorithms/BASISCrystalDiffraction.py
  Framework/PythonInterface/plugins/algorithms/BASISDiffraction.py
  Framework/PythonInterface/plugins/algorithms/EnggFocus.py
  Framework/PythonInterface/plugins/algorithms/MaskWorkspaceToCalFile.py
  Framework/PythonInterface/plugins/algorithms/MergeCalFiles.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/CorelliPowderCalibrationCreate.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectDiffractionReduction.py
  Testing/SystemTests/tests/framework/WishAnalysis.py
  docs/source/algorithms/AlignComponents-v1.rst
  docs/source/algorithms/AlignDetectors-v1.rst
  docs/source/algorithms/ApplyDiffCal-v1.rst
  docs/source/algorithms/CalculateDIFC-v1.rst
  docs/source/algorithms/ConvertUnits-v1.rst
  docs/source/algorithms/CreateCalFileByNames-v1.rst
  docs/source/algorithms/CreateDummyCalFile-v1.rst
  docs/source/algorithms/DiffractionFocussing-v2.rst
  docs/source/algorithms/EnggFitPeaks-v1.rst
  docs/source/algorithms/EnggFitTOFFromPeaks-v1.rst
  docs/source/algorithms/LoadDspacemap-v1.rst
  docs/source/algorithms/PDCalibration-v1.rst
  docs/source/algorithms/SaveGDA-v1.rst
  docs/source/concepts/UnitFactory.rst
  docs/source/concepts/calibration/CalFile.rst
  docs/source/concepts/calibration/PowderDiffractionCalibration.rst
  docs/source/release/v6.1.0/diffraction.rst
  docs/source/release/v6.13.0/Framework/Algorithms/Deprecated/37799.rst
  scripts/Diffraction/isis_powder/gem_routines/gem_calibration_algs.py
Labels: Diffraction, Framework, Extra Attention, ISIS Team: Core

#38832 Remove AlignDetectors algorithm - ornl-next
  Framework/Algorithms/CMakeLists.txt
  Framework/Algorithms/inc/MantidAlgorithms/AlignDetectors.h
  Framework/Algorithms/inc/MantidAlgorithms/CreateCalFileByNames.h
  Framework/Algorithms/inc/MantidAlgorithms/CreateDummyCalFile.h
  Framework/Algorithms/inc/MantidAlgorithms/DiffractionFocussing2.h
  Framework/Algorithms/inc/MantidAlgorithms/ReadGroupsFromFile.h
  Framework/Algorithms/src/AlignDetectors.cpp
  Framework/Algorithms/test/AlignDetectorsTest.h
  Framework/Algorithms/test/DiffractionFocussing2Test.h
  Framework/DataHandling/inc/MantidDataHandling/ApplyDiffCal.h
  Framework/DataHandling/inc/MantidDataHandling/LoadCalFile.h
  Framework/DataHandling/inc/MantidDataHandling/SaveCalFile.h
  Framework/DataHandling/src/SaveGDA.cpp
  Framework/DataObjects/inc/MantidDataObjects/OffsetsWorkspace.h
  Framework/PythonInterface/plugins/algorithms/BASISCrystalDiffraction.py
  Framework/PythonInterface/plugins/algorithms/BASISDiffraction.py
  Framework/PythonInterface/plugins/algorithms/EnggFocus.py
  Framework/PythonInterface/plugins/algorithms/MaskWorkspaceToCalFile.py
  Framework/PythonInterface/plugins/algorithms/MergeCalFiles.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/CorelliPowderCalibrationCreate.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ISISIndirectDiffractionReduction.py
  Testing/SystemTests/tests/framework/WishAnalysis.py
  docs/source/algorithms/AlignComponents-v1.rst
  docs/source/algorithms/AlignDetectors-v1.rst
  docs/source/algorithms/ApplyDiffCal-v1.rst
  docs/source/algorithms/CalculateDIFC-v1.rst
  docs/source/algorithms/ConvertUnits-v1.rst
  docs/source/algorithms/CreateCalFileByNames-v1.rst
  docs/source/algorithms/CreateDummyCalFile-v1.rst
  docs/source/algorithms/DiffractionFocussing-v2.rst
  docs/source/algorithms/EnggFitPeaks-v1.rst
  docs/source/algorithms/EnggFitTOFFromPeaks-v1.rst
  docs/source/algorithms/LoadDspacemap-v1.rst
  docs/source/algorithms/PDCalibration-v1.rst
  docs/source/algorithms/SaveGDA-v1.rst
  docs/source/concepts/UnitFactory.rst
  docs/source/concepts/calibration/CalFile.rst
  docs/source/concepts/calibration/PowderDiffractionCalibration.rst
  docs/source/release/v6.1.0/diffraction.rst
  docs/source/release/v6.13.0/Framework/Algorithms/Deprecated/37799.rst
  scripts/Diffraction/isis_powder/gem_routines/gem_calibration_algs.py
Labels: ornl-next

#38814 Remove unused git commit hook
  .githooks/commit-msg
Labels: Maintenance

#38801 Matrix Workspace throw exception for invalid plot argument
  Framework/API/src/MatrixWorkspace.cpp
  Framework/API/test/MatrixWorkspaceTest.h
  Framework/PythonInterface/test/python/mantid/api/MatrixWorkspaceTest.py
  docs/source/api/python/mantid/plots/index.rst
  docs/source/concepts/MatrixWorkspace.rst
  docs/source/plotting/index.rst
Labels: ORNL Team

#38834 Revert "Remove napi from NexusClasses"
  Framework/API/src/FrameworkManager.cpp
  Framework/DataHandling/src/LoadEventNexus.cpp
  Framework/DataHandling/src/LoadHelper.cpp
  Framework/DataHandling/src/LoadNexus.cpp
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  Framework/DataHandling/src/LoadTOFRawNexus.cpp
  Framework/DataHandling/src/NexusTester.cpp
  Framework/DataHandling/src/SaveNexusProcessed.cpp
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/src/NexusClasses.cpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusException.hpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile.hpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile_fwd.h
  Framework/NexusCpp/inc/MantidNexusCpp/napi.h
  Framework/NexusCpp/src/NeXusException.cpp
  Framework/NexusCpp/src/NeXusFile.cpp
  Framework/NexusGeometry/src/NexusGeometryParser.cpp
Labels: Maintenance

#38819 Fix Linux standalone package for Ubuntu
  buildconfig/CMake/Packaging/launch_mantidworkbench.sh.in
  docs/source/release/v6.12.0/Workbench/Bugfixes/38797.rst
  installers/conda/common/common.sh
  installers/conda/linux/create_tarball.sh
Labels: High Priority, Bug, Linux Only

#38839 Matrix Workspace throw exception for invalid plot argument
  Framework/API/src/MatrixWorkspace.cpp
  Framework/API/test/MatrixWorkspaceTest.h
  Framework/PythonInterface/test/python/mantid/api/MatrixWorkspaceTest.py
  docs/source/api/python/mantid/plots/index.rst
  docs/source/concepts/MatrixWorkspace.rst
  docs/source/plotting/index.rst
Labels: ORNL Team, ornl-next

#38841 Revert "Remove napi from NexusClasses - ornl-next"
  Framework/API/src/FrameworkManager.cpp
  Framework/DataHandling/src/LoadEventNexus.cpp
  Framework/DataHandling/src/LoadHelper.cpp
  Framework/DataHandling/src/LoadNexus.cpp
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  Framework/DataHandling/src/LoadTOFRawNexus.cpp
  Framework/DataHandling/src/NexusTester.cpp
  Framework/DataHandling/src/SaveNexusProcessed.cpp
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/src/NexusClasses.cpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusException.hpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile.hpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile_fwd.h
  Framework/NexusCpp/inc/MantidNexusCpp/napi.h
  Framework/NexusCpp/src/NeXusException.cpp
  Framework/NexusCpp/src/NeXusFile.cpp
  Framework/NexusGeometry/src/NexusGeometryParser.cpp
Labels: ornl-next

#38717 CppCheck Suppression Team Echo Set 32
  Framework/Algorithms/src/AbsorptionCorrection.cpp
  Framework/DataHandling/src/LoadLog.cpp
  Framework/DataHandling/src/LoadMask.cpp
  Framework/DataHandling/src/LoadMuonStrategy.cpp
  Framework/DataHandling/src/LoadNexusMonitors2.cpp
  Framework/DataHandling/src/LoadPreNexus.cpp
  Framework/DataHandling/src/LoadRaw/isisraw.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance

#38840 Simplify NeXus logging
  Framework/API/inc/MantidAPI/FrameworkManager.h
  Framework/API/src/FrameworkManager.cpp
  Framework/DataHandling/src/SaveNexusProcessed.cpp
  Framework/LegacyNexus/inc/MantidLegacyNexus/napi.h
  Framework/LegacyNexus/src/napi.cpp
  Framework/NexusCpp/inc/MantidNexusCpp/napi.h
  Framework/NexusCpp/src/napi.cpp
  Framework/NexusCpp/src/napi4.cpp
  Framework/NexusCpp/src/napi5.cpp
Labels: ORNL Team, Technical Debt

#38835 Release notes v6.12.0 - direct geometry
  docs/source/release/v6.12.0/Direct_Geometry/General/Bugfixes/Used/38591.rst
  docs/source/release/v6.12.0/Direct_Geometry/General/New_features/Used/38367.rst
  docs/source/release/v6.12.0/Direct_Geometry/MSlice/Bugfixes/Used/38596.rst
  docs/source/release/v6.12.0/Direct_Geometry/MSlice/New_features/Used/38299.rst
  docs/source/release/v6.12.0/Direct_Geometry/MSlice/New_features/Used/38596.rst
  docs/source/release/v6.12.0/direct_geometry.rst
Labels: Direct Inelastic, Documentation

#38747 Cppcheck suppresions set 59
  Framework/PythonInterface/mantid/geometry/src/Exports/Goniometer.cpp
  Framework/PythonInterface/mantid/geometry/src/Exports/Instrument.cpp
  Framework/PythonInterface/mantid/geometry/src/Exports/MeshObject.cpp
  Framework/PythonInterface/mantid/geometry/src/Exports/ReflectionGenerator.cpp
  Framework/PythonInterface/mantid/geometry/src/Exports/UnitCell.cpp
  Framework/PythonInterface/mantid/kernel/src/Exports/ArrayProperty.cpp
  Framework/PythonInterface/mantid/kernel/src/Exports/ConfigService.cpp
  Framework/PythonInterface/mantid/kernel/src/Exports/FacilityInfo.cpp
  Framework/PythonInterface/mantid/kernel/src/Exports/IPropertyManager.cpp
  Framework/PythonInterface/mantid/kernel/src/Exports/Property.cpp
  Framework/PythonInterface/mantid/kernel/src/Exports/Quat.cpp
  Framework/PythonInterface/mantid/kernel/src/Exports/Statistics.cpp
  Framework/PythonInterface/mantid/kernel/src/Exports/TimeSeriesProperty.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance

#38836 Release notes v6.12.0 - indirect and inelastic
  docs/source/release/v6.12.0/Indirect/Algorithms/Bugfixes/Used/38442.rst
  docs/source/release/v6.12.0/Indirect/Algorithms/Bugfixes/Used/38448.rst
  docs/source/release/v6.12.0/Indirect/Algorithms/Bugfixes/Used/38606.rst
  docs/source/release/v6.12.0/Indirect/Algorithms/New_features/Used/38518.rst
  docs/source/release/v6.12.0/Indirect/Bugfixes/Used/38093.rst
  docs/source/release/v6.12.0/Indirect/Bugfixes/Used/38464.rst
  docs/source/release/v6.12.0/Inelastic/Algorithms/New_features/Used/38196_CreateMonteCarloWorkspace.rst
  docs/source/release/v6.12.0/Inelastic/Bugfixes/Used/38392.rst
  docs/source/release/v6.12.0/Inelastic/New_features/Used/38391.rst
  docs/source/release/v6.12.0/Inelastic/New_features/Used/38413.rst
  docs/source/release/v6.12.0/indirect_geometry.rst
  docs/source/release/v6.12.0/inelastic.rst
Labels: Indirect/Inelastic, Documentation

#38850 Simplify NeXus logging -- `ornl-next`
  Framework/API/inc/MantidAPI/FrameworkManager.h
  Framework/API/src/FrameworkManager.cpp
  Framework/DataHandling/src/SaveNexusProcessed.cpp
  Framework/LegacyNexus/inc/MantidLegacyNexus/napi.h
  Framework/LegacyNexus/src/napi.cpp
  Framework/NexusCpp/inc/MantidNexusCpp/napi.h
  Framework/NexusCpp/src/napi.cpp
  Framework/NexusCpp/src/napi4.cpp
  Framework/NexusCpp/src/napi5.cpp
Labels: Technical Debt, ornl-next

#38692 Adding group inputs to SaveNXcanSAS algorithm
  Framework/DataHandling/inc/MantidDataHandling/NXcanSASHelper.h
  Framework/DataHandling/inc/MantidDataHandling/SaveNXcanSAS.h
  Framework/DataHandling/inc/MantidDataHandling/SaveNXcanSASBase.h
  Framework/DataHandling/src/NXcanSASHelper.cpp
  Framework/DataHandling/src/SaveNXcanSAS.cpp
  Framework/DataHandling/src/SaveNXcanSASBase.cpp
  Framework/DataHandling/test/NXcanSASTestHelper.cpp
  Framework/DataHandling/test/NXcanSASTestHelper.h
  Framework/DataHandling/test/SaveNXcanSASTest.h
  docs/source/algorithms/SaveNXcanSAS-v1.rst
  docs/source/release/v6.13.0/Reflectometry/New_features/38504.rst
Labels: SANS, ISIS Team: LSS

#38853 Fix macOS standalone packaging
  installers/conda/common/common.sh
Labels: High Priority, ISIS Team: Core, DevOps

#38849 Change logic to use context manager
  scripts/Inelastic/Direct/ReductionWrapper.py
Labels: Direct Inelastic

#38852 Remove unused git commit hook - ornl-next
  .githooks/commit-msg
Labels: ornl-next

#38846 Close the file after parsing it
  Framework/Kernel/src/NexusHDF5Descriptor.cpp
Labels: Maintenance

#38858 Close the file after parsing it - ornl-next
  Framework/Kernel/src/NexusHDF5Descriptor.cpp
Labels: ornl-next

#38855 Fix performance issue with smoothNeighbours
  Framework/Algorithms/src/SmoothNeighbours.cpp
Labels: Bug, ORNL Team

#38854 Debyewaller ornl next
  Framework/MDAlgorithms/CMakeLists.txt
  Framework/MDAlgorithms/inc/MantidMDAlgorithms/DebyeWallerFactorCorrectionMD.h
  Framework/MDAlgorithms/src/DebyeWallerFactorCorrectionMD.cpp
  Framework/MDAlgorithms/test/DebyeWallerFactorCorrectionMDTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/algorithms/DebyeWallerFactorCorrectionMD-v1.rst
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/38512.rst
Labels: ornl-next

#38844 Hide napi.h in NexusFile.cpp
  Framework/DataHandling/src/LoadEventNexus.cpp
  Framework/DataHandling/src/LoadNexus.cpp
  Framework/DataHandling/src/NexusTester.cpp
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/src/NexusClasses.cpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusException.hpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile.hpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile_fwd.h
  Framework/NexusCpp/inc/MantidNexusCpp/napi.h
  Framework/NexusCpp/src/NeXusException.cpp
  Framework/NexusCpp/src/NeXusFile.cpp
Labels: ORNL Team, Technical Debt

#38860 Hide napi.h in NexusFile.cpp - ornl-next
  Framework/DataHandling/src/LoadEventNexus.cpp
  Framework/DataHandling/src/LoadNexus.cpp
  Framework/DataHandling/src/NexusTester.cpp
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/src/NexusClasses.cpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusException.hpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile.hpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile_fwd.h
  Framework/NexusCpp/inc/MantidNexusCpp/napi.h
  Framework/NexusCpp/src/NeXusException.cpp
  Framework/NexusCpp/src/NeXusFile.cpp
Labels: ornl-next

#38843 Remove unused classes from NexusClasses
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/src/NexusClasses.cpp
Labels: Maintenance

#38857 Change logic to use context manager - ornl-next
  scripts/Inelastic/Direct/ReductionWrapper.py
Labels: ornl-next

#38864 Remove unused classes from NexusClasses - ornl-next
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/src/NexusClasses.cpp
Labels: ornl-next

#38865 Fix performance issue with smoothNeighbours
  Framework/Algorithms/src/SmoothNeighbours.cpp
Labels: ornl-next

#38856 Revert napi lookup of HDF types from NX types
  Framework/NexusCpp/src/napi4.cpp
  Framework/NexusCpp/src/napi5.cpp
Labels: ORNL Team, Technical Debt

#38869 SaveNXcansSAS changes into `ornl-next`
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/NXcanSASHelper.h
  Framework/DataHandling/inc/MantidDataHandling/SaveNXcanSAS.h
  Framework/DataHandling/inc/MantidDataHandling/SaveNXcanSASBase.h
  Framework/DataHandling/src/NXcanSASHelper.cpp
  Framework/DataHandling/src/SaveNXcanSAS.cpp
  Framework/DataHandling/src/SaveNXcanSASBase.cpp
  Framework/DataHandling/test/NXcanSASTestHelper.cpp
  Framework/DataHandling/test/NXcanSASTestHelper.h
  Framework/DataHandling/test/SaveNXcanSASTest.h
  docs/source/algorithms/SaveNXcanSAS-v1.rst
  docs/source/release/v6.13.0/Reflectometry/New_features/38504.rst
Labels: ornl-next

#38867 Fix performance issue with SmoothNeighbours
  Framework/Algorithms/src/SmoothNeighbours.cpp
Labels: High Priority, Bug, ORNL Team

#38868 Update MSlice version number from 2.10.1 to 2.11.0
  conda/recipes/conda_build_config.yaml
Labels: High Priority

#38872 Revert napi lookup of HDF types from NX types -- `ornl-next`
  Framework/NexusCpp/src/napi4.cpp
  Framework/NexusCpp/src/napi5.cpp
Labels: ornl-next

#38866 Set H5F_CLOSE_STRONG because that is how nexus does it
  Framework/DataHandling/src/LoadDiffCal.cpp
  Framework/DataHandling/src/LoadILLDiffraction.cpp
  Framework/DataHandling/src/LoadILLLagrange.cpp
  Framework/DataHandling/src/LoadILLSALSA.cpp
  Framework/DataHandling/src/LoadILLSANS.cpp
  Framework/DataHandling/src/LoadMcStas.cpp
  Framework/DataHandling/src/LoadNXcanSAS.cpp
  Framework/DataHandling/src/LoadSassena.cpp
  Framework/DataHandling/src/SaveDiffCal.cpp
  Framework/DataHandling/src/SaveNXcanSASBase.cpp
  Framework/DataHandling/test/LoadNexusProcessedTest.h
  Framework/DataHandling/test/SaveNXSPETest.h
  Framework/DataHandling/test/SaveNXcanSASTest.h
  Framework/DataHandling/test/SaveNexusESSTest.h
  Framework/MDAlgorithms/test/LoadMDTest.h
  Framework/Nexus/inc/MantidNexus/H5Util.h
  Framework/Nexus/src/H5Util.cpp
  Framework/Nexus/test/H5UtilTest.h
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile.hpp
  Framework/NexusCpp/src/NeXusFile.cpp
  Framework/NexusGeometry/src/NexusGeometryParser.cpp
  Framework/NexusGeometry/src/NexusGeometrySave.cpp
  Framework/NexusGeometry/test/NexusGeometryParserTest.h
  Framework/Parallel/src/IO/EventLoader.cpp
  Framework/Parallel/src/IO/MultiProcessEventLoader.cpp
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/NexusFileReader.h
Labels: Maintenance, Technical Debt

#38875 Set H5F_CLOSE_STRONG because that is how nexus does it - ornl-next
  Framework/DataHandling/src/LoadDiffCal.cpp
  Framework/DataHandling/src/LoadILLDiffraction.cpp
  Framework/DataHandling/src/LoadILLLagrange.cpp
  Framework/DataHandling/src/LoadILLSALSA.cpp
  Framework/DataHandling/src/LoadILLSANS.cpp
  Framework/DataHandling/src/LoadMcStas.cpp
  Framework/DataHandling/src/LoadNXcanSAS.cpp
  Framework/DataHandling/src/LoadSassena.cpp
  Framework/DataHandling/src/SaveDiffCal.cpp
  Framework/DataHandling/src/SaveNXcanSASBase.cpp
  Framework/DataHandling/test/LoadNexusProcessedTest.h
  Framework/DataHandling/test/SaveNXSPETest.h
  Framework/DataHandling/test/SaveNXcanSASTest.h
  Framework/DataHandling/test/SaveNexusESSTest.h
  Framework/MDAlgorithms/test/LoadMDTest.h
  Framework/Nexus/inc/MantidNexus/H5Util.h
  Framework/Nexus/src/H5Util.cpp
  Framework/Nexus/test/H5UtilTest.h
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile.hpp
  Framework/NexusCpp/src/NeXusFile.cpp
  Framework/NexusGeometry/src/NexusGeometryParser.cpp
  Framework/NexusGeometry/src/NexusGeometrySave.cpp
  Framework/NexusGeometry/test/NexusGeometryParserTest.h
  Framework/Parallel/src/IO/EventLoader.cpp
  Framework/Parallel/src/IO/MultiProcessEventLoader.cpp
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/NexusFileReader.h
Labels: ornl-next

#38862 Fixed typo in error message in SaveAscii2
  Framework/DataHandling/src/SaveAscii2.cpp
Labels: Documentation, Maintenance

#38876 Pin `libopenblas` to known working version
  conda/recipes/conda_build_config.yaml
Labels: High Priority, Dependencies, DevOps

#38874 Change `NexusClasses` integer types
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  Framework/DataHandling/src/LoadTOFRawNexus.cpp
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/src/NexusClasses.cpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile.hpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile_fwd.h
  Framework/NexusCpp/src/NeXusFile.cpp
Labels: ORNL Team, Technical Debt

#38885 Change NexusClasses integer types -- `ornl-next`
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  Framework/DataHandling/src/LoadTOFRawNexus.cpp
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/src/NexusClasses.cpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile.hpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile_fwd.h
  Framework/NexusCpp/src/NeXusFile.cpp
Labels: ornl-next

#38842 Remove a number of Cppcheck suppressions
  Framework/CurveFitting/src/Functions/CrystalFieldFunction.cpp
  Framework/CurveFitting/src/GeneralDomainCreator.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferData.h
Labels: Maintenance, ISIS Team: Core

#38838 Display region selectors on Reflectometry GUI Preview Tab slice viewer plot on workspace load
  dev-docs/source/Testing/ReflectometryGUI/ReflectometryGUITests.rst
  docs/source/release/v6.13.0/Reflectometry/New_features/36573.rst
  qt/python/mantidqt/mantidqt/widgets/regionselector/presenter.py
  qt/python/mantidqt/mantidqt/widgets/regionselector/test/test_regionselector_presenter.py
  qt/python/mantidqt/mantidqt/widgets/regionselector/view.py
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/BatchPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/IBatchPresenter.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Preview/PreviewPresenter.h
  qt/scientific_interfaces/ISISReflectometry/test/Batch/BatchPresenterTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Preview/PreviewPresenterTest.h
  qt/scientific_interfaces/ISISReflectometry/test/ReflMockObjects.h
  qt/widgets/regionselector/inc/MantidQtWidgets/RegionSelector/IRegionSelector.h
  qt/widgets/regionselector/inc/MantidQtWidgets/RegionSelector/RegionSelector.h
  qt/widgets/regionselector/src/RegionSelector.cpp
  qt/widgets/regionselector/test/MockRegionSelector.h
Labels: Reflectometry, ISIS Team: LSS

#38851 Release notes v6.12.0 - Framework
  docs/source/api/python/mantid/api/AlgoTimeRegister.rst
  docs/source/release/v6.12.0/Framework/Algorithms/Bugfixes/Used/37752.rst
  docs/source/release/v6.12.0/Framework/Algorithms/Bugfixes/Used/37982.rst
  docs/source/release/v6.12.0/Framework/Algorithms/Bugfixes/Used/38063.rst
  docs/source/release/v6.12.0/Framework/Algorithms/Bugfixes/Used/38075.rst
  docs/source/release/v6.12.0/Framework/Algorithms/Bugfixes/Used/38090.rst
  docs/source/release/v6.12.0/Framework/Algorithms/Bugfixes/Used/38290.rst
  docs/source/release/v6.12.0/Framework/Algorithms/Bugfixes/Used/38324.rst
  docs/source/release/v6.12.0/Framework/Algorithms/Bugfixes/Used/38487.rst
  docs/source/release/v6.12.0/Framework/Algorithms/Bugfixes/Used/38551.rst
  docs/source/release/v6.12.0/Framework/Algorithms/Bugfixes/Used/38564.rst
  docs/source/release/v6.12.0/Framework/Algorithms/Bugfixes/Used/38738.rst
  docs/source/release/v6.12.0/Framework/Algorithms/New_features/Used/36981.rst
  docs/source/release/v6.12.0/Framework/Algorithms/New_features/Used/37931.rst
  docs/source/release/v6.12.0/Framework/Algorithms/New_features/Used/38164.rst
  docs/source/release/v6.12.0/Framework/Algorithms/New_features/Used/38175.rst
  docs/source/release/v6.12.0/Framework/Algorithms/New_features/Used/38198.rst
  docs/source/release/v6.12.0/Framework/Algorithms/New_features/Used/38264.rst
  docs/source/release/v6.12.0/Framework/Algorithms/New_features/Used/38265.rst
  docs/source/release/v6.12.0/Framework/Algorithms/New_features/Used/38308.rst
  docs/source/release/v6.12.0/Framework/Algorithms/New_features/Used/38309.rst
  docs/source/release/v6.12.0/Framework/Algorithms/New_features/Used/38511.rst
  docs/source/release/v6.12.0/Framework/Algorithms/New_features/Used/38550.rst
  docs/source/release/v6.12.0/Framework/Data_Handling/New_features/Used/38013.rst
  docs/source/release/v6.12.0/Framework/Data_Handling/New_features/Used/38133.rst
  docs/source/release/v6.12.0/Framework/Data_Objects/Bugfixes/Used/38100.rst
  docs/source/release/v6.12.0/Framework/Data_Objects/Bugfixes/Used/38519.rst
  docs/source/release/v6.12.0/Framework/Data_Objects/New_features/Used/38177.rst
  docs/source/release/v6.12.0/Framework/Dependencies/New_features/Used/38077.rst
  docs/source/release/v6.12.0/Framework/Dependencies/New_features/Used/38336.rst
  docs/source/release/v6.12.0/Framework/Dependencies/New_features/Used/38420.rst
  docs/source/release/v6.12.0/Framework/Fit_Functions/Bugfixes/Used/38769.rst
  docs/source/release/v6.12.0/Framework/Python/Bugfixes/Used/38650.rst
  docs/source/release/v6.12.0/Framework/Python/New_features/Used/38010.rst
  docs/source/release/v6.12.0/Framework/Python/New_features/Used/38144.rst
  docs/source/release/v6.12.0/Framework/Python/New_features/Used/38166.rst
  docs/source/release/v6.12.0/Framework/Python/New_features/Used/38451.rst
  docs/source/release/v6.12.0/framework.rst
Labels: Documentation, Framework

#38893 Add a new revision to LoadMuonNexus to reenable alg selection - ornl-next
  Framework/Muon/CMakeLists.txt
  Framework/Muon/inc/MantidMuon/LoadMuonNexus3.h
  Framework/Muon/src/LoadMuonNexus3.cpp
  Framework/Muon/test/LoadMuonNexus3Test.h
  docs/source/algorithms/LoadMuonNexus-v3.rst
  docs/source/release/v6.12.0/muon.rst
Labels: ornl-next

#38802 updated images in mantid basic course
  docs/source/images/DisplaySettings.png
  docs/source/images/FilterEventsInterface.png
  docs/source/images/ManageUserDirectories.PNG
  docs/source/images/ManageUserDirectories.png
  docs/source/images/PlotSettings.png
  docs/source/images/SettingsCategories.png
  docs/source/images/SettingsFitting.png
  docs/source/images/SettingsGeneral.png
  docs/source/images/ShowLoadandWorkspaceAreaInMantidWB.png
  docs/source/tutorials/mantid_basic_course/getting_started/getting_started.rst
  docs/source/tutorials/mantid_basic_course/loading_and_displaying_data/01_loading_data.rst
Labels: Documentation, Maintenance

#38824 Change LegacyNexusDescriptor to use LegacyNexusFile
  Framework/API/inc/MantidAPI/FileLoaderRegistry.h
  Framework/API/src/FileLoaderRegistry.cpp
  Framework/Kernel/CMakeLists.txt
  Framework/Kernel/inc/MantidKernel/LegacyNexusDescriptor.h
  Framework/Kernel/src/LegacyNexusDescriptor.cpp
  Framework/Kernel/test/LegacyNexusDescriptorTest.h
  Framework/LegacyNexus/inc/MantidLegacyNexus/napi.h
  Framework/Muon/inc/MantidMuon/LoadMuonNexus.h
  Framework/Muon/inc/MantidMuon/LoadMuonNexus1.h
  Framework/Muon/inc/MantidMuon/LoadMuonNexus2.h
  Framework/Muon/src/LoadMuonNexus.cpp
  Framework/Muon/src/LoadMuonNexus1.cpp
  Framework/Muon/src/LoadMuonNexus2.cpp
  buildconfig/CMake/MantidFrameworkConfig.cmake.in
Labels: Maintenance, Technical Debt

#38899 Get LoadMuonNexus3 compiling in main - ornl-next
  Framework/API/inc/MantidAPI/FileLoaderRegistry.h
  Framework/API/src/FileLoaderRegistry.cpp
  Framework/Kernel/CMakeLists.txt
  Framework/Kernel/inc/MantidKernel/LegacyNexusDescriptor.h
  Framework/Kernel/src/LegacyNexusDescriptor.cpp
  Framework/Kernel/test/LegacyNexusDescriptorTest.h
  Framework/LegacyNexus/inc/MantidLegacyNexus/napi.h
  Framework/Muon/inc/MantidMuon/LoadMuonNexus.h
  Framework/Muon/inc/MantidMuon/LoadMuonNexus1.h
  Framework/Muon/inc/MantidMuon/LoadMuonNexus2.h
  Framework/Muon/inc/MantidMuon/LoadMuonNexus3.h
  Framework/Muon/inc/MantidMuon/PlotAsymmetryByLogValue.h
  Framework/Muon/src/LoadMuonNexus.cpp
  Framework/Muon/src/LoadMuonNexus1.cpp
  Framework/Muon/src/LoadMuonNexus2.cpp
  Framework/Muon/src/LoadMuonNexus3.cpp
  Framework/Muon/src/PlotAsymmetryByLogValue.cpp
  Framework/NexusGeometry/src/NexusShapeFactory.cpp
  Framework/Parallel/inc/MantidParallel/IO/EventsListsShmemStorage.h
  Framework/PythonInterface/core/inc/MantidPythonInterface/core/DataServiceExporter.h
  Framework/PythonInterface/core/inc/MantidPythonInterface/core/IsNone.h
  Framework/PythonInterface/core/src/Converters/CloneToNDArray.cpp
  Framework/PythonInterface/core/src/Converters/NDArrayToVector.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  buildconfig/CMake/MantidFrameworkConfig.cmake.in
Labels: ornl-next

#38873 Update the intersphinx urls as the warnings suggested
  docs/source/conf.py
Labels: Documentation, Maintenance

#38900 Fix addProperty python export when value is a Property
  Framework/Kernel/inc/MantidKernel/Property.h
  Framework/Kernel/src/Property.cpp
  Framework/PythonInterface/mantid/api/src/Exports/Run.cpp
  Framework/PythonInterface/test/python/mantid/api/RunTest.py
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.13.0/Framework/Python/Bugfixes/38886.rst
Labels: ornl-next

#38783 Allow User-Configured Input Spin State Orders From The GUI & Parameter File
  Framework/Algorithms/src/PolarizationEfficiencyCor.cpp
  Framework/PythonInterface/plugins/algorithms/ReflectometryReductionOneLiveData.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/ReflectometryISISLoadAndProcess.py
  Framework/Reflectometry/inc/MantidReflectometry/ReflectometryReductionOneAuto3.h
  Framework/Reflectometry/src/ReflectometryReductionOneAuto3.cpp
  Framework/Reflectometry/test/ReflectometryReductionOneAuto3Test.h
  dev-docs/source/Testing/ReflectometryGUI/ReflectometryGUITests.rst
  docs/source/release/v6.13.0/Reflectometry/New_features/37617.rst
  instrument/POLREF_Parameters.xml
  qt/scientific_interfaces/ISISReflectometry/GUI/Batch/RowProcessingAlgorithm.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Common/Decoder.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Common/Encoder.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/ExperimentPresenter.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/ExperimentWidget.ui
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/IExperimentView.h
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/QtExperimentView.cpp
  qt/scientific_interfaces/ISISReflectometry/GUI/Experiment/QtExperimentView.h
  qt/scientific_interfaces/ISISReflectometry/Reduction/PolarizationCorrections.cpp
  qt/scientific_interfaces/ISISReflectometry/Reduction/PolarizationCorrections.h
  qt/scientific_interfaces/ISISReflectometry/TestHelpers/ModelCreationHelper.cpp
  qt/scientific_interfaces/ISISReflectometry/test/Common/CoderCommonTester.h
  qt/scientific_interfaces/ISISReflectometry/test/Experiment/ExperimentPresenterTest.h
  qt/scientific_interfaces/ISISReflectometry/test/Experiment/MockExperimentView.h
Labels: Reflectometry, ISIS Team: LSS

#38825 Create LegacyNexusClasses
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/LoadMuonLog.h
  Framework/DataHandling/src/LoadInstrumentFromNexus.cpp
  Framework/Muon/CMakeLists.txt
  Framework/Muon/inc/MantidMuon/LegacyNexusClasses.h
  Framework/Muon/inc/MantidMuon/LoadMuonNexus1.h
  Framework/Muon/inc/MantidMuon/LoadMuonNexus2.h
  Framework/Muon/inc/MantidMuon/MuonNexusReader.h
  Framework/Muon/src/LegacyNexusClasses.cpp
  Framework/Muon/src/LoadMuonNexus.cpp
  Framework/Muon/src/LoadMuonNexus1.cpp
  Framework/Muon/src/LoadMuonNexus2.cpp
  Framework/Muon/src/LoadMuonNexus3.cpp
  Framework/Muon/src/MuonNexusReader.cpp
  Framework/Nexus/CMakeLists.txt
Labels: Technical Debt

#38901 Pass DOCS_QTHELP to compiler to control registering MantidHelpWindow
  qt/widgets/common/CMakeLists.txt
  qt/widgets/common/src/InterfaceManager.cpp
Labels: Bug

#38905 Pass DOCS_QTHELP to compiler to control registering MantidHelpWindow
  qt/widgets/common/CMakeLists.txt
  qt/widgets/common/src/InterfaceManager.cpp
Labels: ornl-next

#38907 Update the intersphinx urls as the warnings suggested - ornl-next
  docs/source/conf.py
Labels: ornl-next

#38883 Link between release checklist and timeline
  dev-docs/source/DevelopmentAndReleaseCycle.rst
  dev-docs/source/ReleaseChecklist.rst
Labels: Documentation

#38620 Abins: explicit cache directory management
  Framework/PythonInterface/plugins/algorithms/Abins.py
  Framework/PythonInterface/plugins/algorithms/Abins2D.py
  Framework/PythonInterface/test/python/plugins/algorithms/Abins2BasicTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/AbinsAdvancedParametersTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/AbinsBasicTest.py
  docs/source/algorithms/Abins-v1.rst
  docs/source/algorithms/Abins2D-v1.rst
  docs/source/release/v6.13.0/Indirect/Algorithms/New_features/38620.rst
  scripts/abins/abins2.py
  scripts/abins/abinsalgorithm.py
  scripts/abins/abinsdata.py
  scripts/abins/input/abinitioloader.py
  scripts/abins/input/crystalloader.py
  scripts/abins/input/dmol3loader.py
  scripts/abins/input/gaussianloader.py
  scripts/abins/input/tester.py
  scripts/abins/io.py
  scripts/abins/powdercalculator.py
  scripts/abins/scalculatorfactory.py
  scripts/abins/spowdersemiempiricalcalculator.py
  scripts/abins/test_helpers.py
  scripts/test/Abins/AbinsCalculateSPowderTest.py
  scripts/test/Abins/AbinsDataTest.py
  scripts/test/Abins/AbinsIOmoduleTest.py
  scripts/test/Abins/AbinsLoadCASTEPTest.py
  scripts/test/Abins/AbinsLoadCRYSTALTest.py
  scripts/test/Abins/AbinsLoadDMOL3Test.py
  scripts/test/Abins/AbinsLoadGAUSSIANTest.py
  scripts/test/Abins/AbinsLoadJSONTest.py
  scripts/test/Abins/AbinsLoadPhonopyTest.py
  scripts/test/Abins/AbinsLoadVASPTest.py
  scripts/test/Abins/AbinsPowderCalculatorTest.py
Labels: ISIS Team: Spectroscopy

#38884 Remove napi functions from `NexusClasses`
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/src/NexusClasses.cpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile.hpp
  Framework/NexusCpp/src/NeXusFile.cpp
Labels: ORNL Team, Technical Debt

#38942 Remove napi functions from NexusClasses -- `ornl-next`
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/src/NexusClasses.cpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile.hpp
  Framework/NexusCpp/src/NeXusFile.cpp
Labels: ornl-next

#38805 Change integer type of Mantid:Nexus::NXInfo
  Framework/DataHandling/inc/MantidDataHandling/DataBlockComposite.h
  Framework/DataHandling/inc/MantidDataHandling/LoadHelper.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLSANS.h
  Framework/DataHandling/inc/MantidDataHandling/LoadNexusProcessed.h
  Framework/DataHandling/src/DataBlock.cpp
  Framework/DataHandling/src/LoadHelper.cpp
  Framework/DataHandling/src/LoadILLSANS.cpp
  Framework/DataHandling/src/LoadILLTOF2.cpp
  Framework/DataHandling/src/LoadISISNexus2.cpp
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  Framework/Muon/src/LoadMuonNexus1.cpp
  Framework/Muon/src/LoadMuonNexus2.cpp
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/src/NexusClasses.cpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile_fwd.h
  Framework/NexusCpp/src/NeXusFile.cpp
Labels: Maintenance, Technical Debt

#38944 Change integer type of Mantid:Nexus::NXInfo - ornl-next
  Framework/DataHandling/inc/MantidDataHandling/DataBlockComposite.h
  Framework/DataHandling/inc/MantidDataHandling/LoadHelper.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLSANS.h
  Framework/DataHandling/inc/MantidDataHandling/LoadNexusProcessed.h
  Framework/DataHandling/src/DataBlock.cpp
  Framework/DataHandling/src/LoadHelper.cpp
  Framework/DataHandling/src/LoadILLSANS.cpp
  Framework/DataHandling/src/LoadILLTOF2.cpp
  Framework/DataHandling/src/LoadISISNexus2.cpp
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  Framework/Muon/src/LoadMuonNexus1.cpp
  Framework/Muon/src/LoadMuonNexus2.cpp
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/src/NexusClasses.cpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile_fwd.h
  Framework/NexusCpp/src/NeXusFile.cpp
Labels: ornl-next

#38906 Add documentation on getting images for target dependencies
  dev-docs/source/ToolsOverview.rst
Labels: Documentation

#38939 More changes to size_t and int64_t types
  Framework/API/inc/MantidAPI/IPeaksWorkspace.h
  Framework/DataHandling/inc/MantidDataHandling/DataBlock.h
  Framework/DataHandling/inc/MantidDataHandling/DataBlockComposite.h
  Framework/DataHandling/inc/MantidDataHandling/LoadHelper.h
  Framework/DataHandling/inc/MantidDataHandling/LoadNexusProcessed.h
  Framework/DataHandling/src/DataBlock.cpp
  Framework/DataHandling/src/DataBlockComposite.cpp
  Framework/DataHandling/src/LoadHelper.cpp
  Framework/DataHandling/src/LoadISISNexus2.cpp
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  Framework/DataObjects/inc/MantidDataObjects/LeanElasticPeaksWorkspace.h
  Framework/DataObjects/inc/MantidDataObjects/PeaksWorkspace.h
  Framework/DataObjects/src/LeanElasticPeaksWorkspace.cpp
  Framework/DataObjects/src/PeaksWorkspace.cpp
  Framework/Muon/src/LoadMuonNexus1.cpp
  Framework/Muon/src/LoadMuonNexus2.cpp
  Framework/Nexus/src/NexusClasses.cpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile_fwd.h
Labels: ORNL Team, Technical Debt

#38948 More changes to size_t and int64_t types -- `ornl-next`
  Framework/API/inc/MantidAPI/IPeaksWorkspace.h
  Framework/DataHandling/inc/MantidDataHandling/DataBlock.h
  Framework/DataHandling/inc/MantidDataHandling/DataBlockComposite.h
  Framework/DataHandling/inc/MantidDataHandling/LoadHelper.h
  Framework/DataHandling/inc/MantidDataHandling/LoadNexusProcessed.h
  Framework/DataHandling/src/DataBlock.cpp
  Framework/DataHandling/src/DataBlockComposite.cpp
  Framework/DataHandling/src/LoadHelper.cpp
  Framework/DataHandling/src/LoadISISNexus2.cpp
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  Framework/DataObjects/inc/MantidDataObjects/LeanElasticPeaksWorkspace.h
  Framework/DataObjects/inc/MantidDataObjects/PeaksWorkspace.h
  Framework/DataObjects/src/LeanElasticPeaksWorkspace.cpp
  Framework/DataObjects/src/PeaksWorkspace.cpp
  Framework/Muon/src/LoadMuonNexus1.cpp
  Framework/Muon/src/LoadMuonNexus2.cpp
  Framework/Nexus/src/NexusClasses.cpp
  Framework/NexusCpp/inc/MantidNexusCpp/NeXusFile_fwd.h
Labels: ornl-next

#38949 `NeXusIOHelper` using non-type templates and `enum` for Narrowing
  Framework/DataHandling/src/LoadBankFromDiskTask.cpp
  Framework/Nexus/inc/MantidNexus/NexusIOHelper.h
  Framework/Nexus/test/NexusIOHelperTest.h
Labels: ORNL Team, Technical Debt

#38956 Revert added crosshair option in mantid
  docs/source/release/v6.12.0/mantidworkbench.rst
  qt/applications/workbench/workbench/plotting/figuremanager.py
  qt/applications/workbench/workbench/plotting/test/test_toolbar.py
  qt/applications/workbench/workbench/plotting/toolbar.py
Labels: High Priority

#38894 Add testing for CalibrationInfo
  scripts/Engineering/common/CMakeLists.txt
  scripts/Engineering/common/test/test_calibration_info.py
Labels: Diffraction, Maintenance

#38947 Revert "updated images in mantid basic course"
  docs/source/images/DisplaySettings.png
  docs/source/images/FilterEventsInterface.png
  docs/source/images/ManageUserDirectories.PNG
  docs/source/images/ManageUserDirectories.png
  docs/source/images/PlotSettings.png
  docs/source/images/SettingsCategories.png
  docs/source/images/SettingsFitting.png
  docs/source/images/SettingsGeneral.png
  docs/source/images/ShowLoadandWorkspaceAreaInMantidWB.png
  docs/source/tutorials/mantid_basic_course/getting_started/getting_started.rst
  docs/source/tutorials/mantid_basic_course/loading_and_displaying_data/01_loading_data.rst
Labels: Documentation

#38977 Move NXlog to Muon subpackage
  Framework/DataHandling/inc/MantidDataHandling/LoadNexusProcessed.h
  Framework/Muon/inc/MantidMuon/LegacyNexusClasses.h
  Framework/Muon/inc/MantidMuon/LoadMuonNexus2.h
  Framework/Muon/src/LegacyNexusClasses.cpp
  Framework/Muon/src/LoadMuonNexus2.cpp
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/src/NexusClasses.cpp
Labels: Technical Debt

#38980 Add description parameter to Jenkins pipeline
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
Labels: ISIS Team: Core, DevOps

#38983 Move NXlog to Muon subpackage - ornl-next
  Framework/DataHandling/inc/MantidDataHandling/LoadNexusProcessed.h
  Framework/Muon/inc/MantidMuon/LegacyNexusClasses.h
  Framework/Muon/inc/MantidMuon/LoadMuonNexus2.h
  Framework/Muon/src/LegacyNexusClasses.cpp
  Framework/Muon/src/LoadMuonNexus2.cpp
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/src/NexusClasses.cpp
Labels: ornl-next

#38985 Update citation file for 6.12.0 release
  CITATION.cff
Labels: ISIS Team: Core

#38965 Remove dev-docs about removed tool
  dev-docs/source/ToolsOverview.rst
Labels: Documentation

#38974 Add Arm compiler to mantid-developer metapackage
  conda/recipes/mantid-developer/meta.yaml
Labels: macOS Only, ISIS Team: Core, Epic

#38986 Switch back to main nightly publishing only after the release is published
  dev-docs/source/ReleaseChecklist.rst
Labels: Documentation, ISIS Team: Core, DevOps

#38988 Update `H5Util` type narrowing/coercion methods
  Framework/Nexus/inc/MantidNexus/H5Util.h
  Framework/Nexus/inc/MantidNexus/NexusIOHelper.h
  Framework/Nexus/src/H5Util.cpp
Labels: ORNL Team, Technical Debt

#38993 Remove two CppCheck suppressions on ExperimentInfo
  Framework/API/inc/MantidAPI/FileLoaderRegistry.h
  Framework/API/src/ExperimentInfo.cpp
  Framework/API/test/ExperimentInfoTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance, ORNL Team

#38943 Fix Mantid cmake build with '-DUSESANITIZER=address'
  Framework/CurveFitting/inc/MantidCurveFitting/Functions/ProductFunction.h
  Framework/CurveFitting/src/Functions/ProductFunction.cpp
  buildconfig/CMake/FindAsanLib.cmake
  buildconfig/CMake/LinuxPackageScripts.cmake
  buildconfig/CMake/LinuxSetup.cmake
  docs/source/release/v6.13.0/Framework/Build_tools/Bugfixes/38943.rst
  docs/source/release/v6.13.0/framework.rst
Labels: ORNL Team

#39001 Remove two CppCheck suppressions on ExperimentInfo -- `ornl-next`
  Framework/API/inc/MantidAPI/FileLoaderRegistry.h
  Framework/API/src/ExperimentInfo.cpp
  Framework/API/test/ExperimentInfoTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: ornl-next

#39000 Update `H5Util` type narrowing/coercion methods -- `ornl-next`
  Framework/Nexus/inc/MantidNexus/H5Util.h
  Framework/Nexus/inc/MantidNexus/NexusIOHelper.h
  Framework/Nexus/src/H5Util.cpp
Labels: ornl-next
