Repository mantidproject/mantid, pull requests merged in 2025-05, with the labels that each got.

#39181 Add a CombineTableWorkspaces algorithm
  Framework/Algorithms/CMakeLists.txt
  Framework/Algorithms/inc/MantidAlgorithms/CombineTableWorkspaces.h
  Framework/Algorithms/src/CombineTableWorkspaces.cpp
  Framework/Algorithms/test/CombineTableWorkspacesTest.h
  docs/source/algorithms/CombineTableWorkspaces-v1.rst
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/39181.rst
Labels: Framework, ISIS Team: Core

#39262 Relax BayesQuasiTest system test for consistency across Linux versions
  Testing/SystemTests/tests/framework/BayesQuasiTest.py
Labels: Linux Only, Technical Debt

#39207 Update cov cmake and docs
  buildconfig/CMake/Coverage.cmake
  dev-docs/source/CodeCoverage.rst
Labels: ISIS Team: Core

#39268 Crosshair ornl
  docs/source/release/v6.13.0/Workbench/New_features/39242.rst
  qt/applications/workbench/workbench/plotting/figuremanager.py
  qt/applications/workbench/workbench/plotting/test/test_toolbar.py
  qt/applications/workbench/workbench/plotting/toolbar.py
Labels: ORNL Team, ornl-next

#39270 Update tests to work on alma 9 runners
  Framework/Algorithms/CMakeLists.txt
  Framework/Algorithms/inc/MantidAlgorithms/CombineTableWorkspaces.h
  Framework/Algorithms/src/CombineTableWorkspaces.cpp
  Framework/Algorithms/test/CombineTableWorkspacesTest.h
  Framework/DataObjects/inc/MantidDataObjects/VectorColumn.h
  Framework/Kernel/src/FloatingPointComparison.cpp
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/BayesQuasiTest.py
  Testing/SystemTests/tests/framework/BayesQuasiTest.py
  Testing/SystemTests/tests/framework/SNSPowderRedux.py
  Testing/SystemTests/tests/framework/reference/PG3_4844_reference.gsa.md5
  Testing/SystemTests/tests/framework/reference/PG3_4866_reference.gsa.md5
  docs/source/algorithms/CombineTableWorkspaces-v1.rst
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/39181.rst
Labels: High Priority, ornl-next

#39206 Allow Fitting tab in Engineering Diffraction to use data in D-Spacing
  docs/source/release/v6.13.0/Diffraction/Engineering/New_features/39206.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/EngDiff_fitpropertybrowser.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/plot_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/test/test_plot_model.py
Labels: Diffraction, ISIS Team: Diffraction

#39281 Deprecate IntegratePeaksMD Version=1 - ornl-next
  Framework/MDAlgorithms/inc/MantidMDAlgorithms/IntegratePeaksMD.h
  Framework/MDAlgorithms/src/IntegratePeaksMD.cpp
  docs/source/release/v6.13.0/Framework/Algorithms/Deprecated/39276.rst
Labels: ornl-next

#39280 Change FileLoaderRegistry chooseLoader for HDF5 files to only check LegacyNexus loaders when confidence if too low
  Framework/API/src/FileLoaderRegistry.cpp
Labels: Bug, ORNL Team

#39284 Change FileLoaderRegistry chooseLoader for HDF5 files to only check LegacyNexus loaders when confidence if too low
  Framework/API/src/FileLoaderRegistry.cpp
Labels: ornl-next

#39277 New Python Algorithm: RefineSingleCrystalGoniometer
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/RefineSingleCrystalGoniometer.py
  Framework/PythonInterface/test/python/plugins/algorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/RefineSingleCrystalGoniometerTest.py
  docs/source/algorithms/RefineSingleCrystalGoniometer-v1.rst
  docs/source/release/v6.13.0/Framework/Python/New_features/39277.rst
Labels: Single Crystal, Framework, ORNL Team

#39287 [ornl-next sibling] New Python Algorithm: RefineSingleCrystalGoniometer
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/RefineSingleCrystalGoniometer.py
  Framework/PythonInterface/test/python/plugins/algorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/RefineSingleCrystalGoniometerTest.py
  docs/source/algorithms/RefineSingleCrystalGoniometer-v1.rst
  docs/source/release/v6.13.0/Framework/Python/New_features/39277.rst
Labels: ornl-next

#39282 Deprecate LoadEventPreNexus
  Framework/DataHandling/inc/MantidDataHandling/LoadEventPreNexus2.h
  Framework/DataHandling/src/LoadEventPreNexus2.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.13.0/Framework/Algorithms/Deprecated/39282.rst
Labels: Framework, ORNL Team

#39286 disable Croshair in 3D plots
  docs/source/release/v6.13.0/Workbench/New_features/39242.rst
  docs/source/release/v6.13.0/Workbench/New_features/39286.rst
  qt/applications/workbench/workbench/plotting/test/test_toolbar.py
  qt/applications/workbench/workbench/plotting/toolbar.py
Labels: GUI, ORNL Team

#39291 Deprecate LoadEventPreNexus in ornl-next
  Framework/DataHandling/inc/MantidDataHandling/LoadEventPreNexus2.h
  Framework/DataHandling/src/LoadEventPreNexus2.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.13.0/Framework/Algorithms/Deprecated/39282.rst
Labels: ORNL Team, ornl-next

#39292 Croshair 3d
  docs/source/release/v6.13.0/Workbench/New_features/39242.rst
  docs/source/release/v6.13.0/Workbench/New_features/39286.rst
  qt/applications/workbench/workbench/plotting/test/test_toolbar.py
  qt/applications/workbench/workbench/plotting/toolbar.py
Labels: ornl-next

#39290 Changes to algorithms cmake
  .pre-commit-config.yaml
  Framework/Algorithms/inc/MantidAlgorithms/CreateDetectorTable.h
  Framework/Algorithms/src/CreateDetectorTable.cpp
  Framework/Algorithms/test/CreateDetectorTableTest.h
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/CreatePoleFigureTableWorkspace.py
  Framework/PythonInterface/plugins/algorithms/PoldiAutoCorrelation6.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/PoldiDataAnalysis.py
  Framework/PythonInterface/plugins/algorithms/poldi_utils.py
  Framework/PythonInterface/test/python/plugins/algorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/CreatePoleFigureTableWorkspaceTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/PoldiAutoCorrelation6Test.py
  Testing/Data/UnitTest/POLDI_Definition_448_calibrated.xml.md5
  Testing/Data/UnitTest/poldi_448x500_chopper5k_silicon.txt.md5
  Testing/SystemTests/tests/framework/POLDIAutoCorrelationTest.py
  Testing/SystemTests/tests/framework/POLDIFitPeaks2DTest.py
  docs/source/algorithms/CreatePoleFigureTableWorkspace-v1.rst
  docs/source/algorithms/PoldiAnalyseResiduals-v1.rst
  docs/source/algorithms/PoldiAutoCorrelation-v5.rst
  docs/source/algorithms/PoldiAutoCorrelation-v6.rst
  docs/source/algorithms/PoldiFitPeaks1D-v1.rst
  docs/source/algorithms/PoldiFitPeaks2D-v1.rst
  docs/source/algorithms/PoldiIndexKnownCompounds-v1.rst
  docs/source/algorithms/PoldiPeakSearch-v1.rst
  docs/source/algorithms/PoldiPeakSummary-v1.rst
  docs/source/images/POLDI1p2_silicon_raw2D.jpeg
  docs/source/images/PoldiAutoCorrelation_silicon.jpeg
  docs/source/release/v6.13.0/Diffraction/Engineering/New_features/38440.rst
  docs/source/release/v6.13.0/Diffraction/Engineering/New_features/39197.rst
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/38960.rst
Labels: ornl-next

#39299 Add 'FullBinsOnly' parameter to 'DiffractionFocussing2'
  Framework/Algorithms/src/DiffractionFocussing2.cpp
  Framework/Algorithms/test/DiffractionFocussing2Test.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/algorithms/DiffractionFocussing-v2.rst
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/39289.rst
Labels: ORNL Team, ornl-next

#39297 Deprecate IntegratePeaksCWSD
  Framework/MDAlgorithms/inc/MantidMDAlgorithms/IntegratePeaksCWSD.h
  Framework/MDAlgorithms/src/IntegratePeaksCWSD.cpp
  docs/source/release/v6.13.0/Framework/Algorithms/Deprecated/39297.rst
Labels: Framework, ORNL Team

#39295 Move post-link.bat functionality to python for Windows conda installs
  conda/recipes/mantidworkbench/post-link.bat
  conda/recipes/mantidworkbench/pre-unlink.bat
  qt/applications/workbench/workbench/app/mantidworkbench_launch_wrapper.py
Labels: ISIS Team: Core, Technical Debt

#39288 Add tests for NexusClasses
  Framework/Nexus/CMakeLists.txt
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/src/NexusClasses.cpp
  Framework/Nexus/test/CMakeLists.txt
  Framework/Nexus/test/NexusClassesTest.h
  Framework/Nexus/test/NexusIOHelperTest.h
  Framework/Nexus/test/test_helper.cpp
  Framework/Nexus/test/test_helper.h
Labels: Technical Debt

#39296 Non-fatal warnings in docs-html
  docs/source/index.rst
  docs/source/interfaces/index.rst
  docs/source/techniques/Calibration.rst
  docs/source/techniques/Calibration_implementation.rst
Labels: Documentation, DevOps

#39306 Non-fatal warnings in docs-html
  docs/source/index.rst
  docs/source/interfaces/index.rst
  docs/source/techniques/Calibration.rst
  docs/source/techniques/Calibration_implementation.rst
Labels: ornl-next

#39305 Add tests for NexusClasses
  Framework/Nexus/CMakeLists.txt
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/src/NexusClasses.cpp
  Framework/Nexus/test/CMakeLists.txt
  Framework/Nexus/test/NexusClassesTest.h
  Framework/Nexus/test/NexusIOHelperTest.h
  Framework/Nexus/test/test_helper.cpp
  Framework/Nexus/test/test_helper.h
Labels: ornl-next

#39303 Deprecate IntegratePeaksCWSD
  Framework/MDAlgorithms/inc/MantidMDAlgorithms/IntegratePeaksCWSD.h
  Framework/MDAlgorithms/src/IntegratePeaksCWSD.cpp
  docs/source/release/v6.13.0/Framework/Algorithms/Deprecated/39297.rst
Labels: ORNL Team, ornl-next

#39249 Add capability to save multiple workspaces in ascii format
  docs/source/release/v6.13.0/Workbench/New_features/38807.rst
  qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidget.cpp
Labels: ISIS Team: Core

#39314 Add upper bounds for muparser dependency
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid/meta.yaml
Labels: ornl-next

#39071 Fix an error when exporting Sliceviewer pixel cuts from MDHisto workspaces
  docs/source/release/v6.13.0/Workbench/SliceViewer/Bugfixes/36084.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenters/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py
Labels: Bug, Diffraction, ISIS Team: Diffraction

#39265 39148 investigate load cif unexpected error
  docs/source/release/v6.13.0/Diffraction/Engineering/Bugfixes/39148.rst
  scripts/Engineering/ENGINX/phase_info/CEO2.cif
Labels: Diffraction

#39318 Pin rhash to fix osx failures
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid-developer/meta.yaml
Labels: High Priority, DevOps

#39321 Pin rhash to fix osx failures
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid-developer/meta.yaml
Labels: ornl-next

#39323 Fix an error when exporting Sliceviewer pixel cuts from MDHisto workspaces
  docs/source/release/v6.13.0/Workbench/SliceViewer/Bugfixes/36084.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/models/model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/presenters/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/test/test_sliceviewer_model.py
Labels: ornl-next

#39307 Add docs about customizing log format
  docs/source/concepts/PropertiesFile.rst
  docs/source/tutorials/extending_mantid_with_python/python_algorithms/05_logging.rst
  tools/DefaultConfigFiles/Mantid.user.properties
Labels: Documentation

#39313 Refactor `SaveNexusProcessedTest` for `FileRegistry`
  Framework/DataHandling/test/SaveNexusProcessedTest.h
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/FileResource.h
  Framework/TestHelpers/src/FileResource.cpp
Labels: Technical Debt

#39101 PEARLTransfit improvements relating to binning, error estimation and initial calibration fit
  Framework/PythonInterface/plugins/algorithms/PEARLTransfit.py
  Framework/PythonInterface/test/python/plugins/algorithms/PEARLTransfitTest.py
  docs/source/release/v6.13.0/Diffraction/Powder/Bugfixes/39101.rst
  docs/source/release/v6.13.0/Diffraction/Powder/New_features/39101.rst
Labels: Diffraction, Reported By User

#38990 Add ARM option to building packages on Jenkins
  CMakePresets.json
  Framework/Algorithms/test/AddSampleLogTest.h
  Framework/Algorithms/test/GetDetectorOffsetsTest.h
  Framework/Algorithms/test/RebinByTimeBaseTest.h
  Framework/CurveFitting/test/Algorithms/FitTest.h
  Framework/CurveFitting/test/FuncMinimizers/LevenbergMarquardtMDTest.h
  Framework/CurveFitting/test/FuncMinimizers/LevenbergMarquardtTest.h
  Framework/CurveFitting/test/Functions/ComptonScatteringCountRateTest.h
  Framework/CurveFitting/test/Functions/GaussianComptonProfileTest.h
  Framework/DataHandling/test/LoadILLDiffractionTest.h
  Framework/Geometry/src/Math/PolygonEdge.cpp
  Framework/Kernel/test/UnitTest.h
  Framework/MDAlgorithms/test/EvaluateMDFunctionTest.h
  Framework/Muon/test/CalculateMuonAsymmetryTest.h
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/BayesQuasiTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/D7AbsoluteCrossSectionsTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/DirectILLAutoProcessTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/SANSILLAutoProcessTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/SANSILLIntegrationTest.py
  Framework/SINQ/test/PoldiSpectrumDomainFunctionTest.h
  Framework/SINQ/test/PoldiSpectrumPawleyFunctionTest.h
  Testing/SystemTests/tests/framework/ConvertMultipleRunsToSingleCrystalMDTest.py
  Testing/SystemTests/tests/framework/Diffraction_Workflow_Test.py
  Testing/SystemTests/tests/framework/FindSatellitePeaksTest.py
  Testing/SystemTests/tests/framework/HB3AWorkflowTests.py
  Testing/SystemTests/tests/framework/ILLDirectGeometryReductionTest.py
  Testing/SystemTests/tests/framework/ISIS/SANS/SANS2D/SANS2D_GDW20_4m_cycle_22_02.py
  Testing/SystemTests/tests/framework/ISIS_PowderHRPDTest.py
  Testing/SystemTests/tests/framework/ISIS_WISHSingleCrystalReduction.py
  Testing/SystemTests/tests/framework/MDNormBackgroundHYSPECTest.py
  Testing/SystemTests/tests/framework/MDNormCORELLITest.py
  Testing/SystemTests/tests/framework/POLDIFitPeaks2DTest.py
  Testing/SystemTests/tests/framework/ReduceOneSCD_Run.py
  Testing/SystemTests/tests/framework/ReflectometryISISCalculatePolEffTest.py
  Testing/SystemTests/tests/framework/SingleCrystalDiffuseReductionTest.py
  buildconfig/Jenkins/Conda/build-and-publish-devsite.sh
  buildconfig/Jenkins/Conda/conda-buildscript
  buildconfig/Jenkins/Conda/conda-pre-commit
  buildconfig/Jenkins/Conda/cppcheck.sh
  buildconfig/Jenkins/Conda/delete-old-packages.sh
  buildconfig/Jenkins/Conda/doxygen.sh
  buildconfig/Jenkins/Conda/mamba-utils
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
  buildconfig/Jenkins/Conda/package-conda
  buildconfig/Jenkins/Conda/package-standalone
  buildconfig/Jenkins/Conda/publish-to-anaconda
  buildconfig/Jenkins/Conda/publish-to-github
  buildconfig/Jenkins/build_and_publish_docs.sh
  conda/recipes/archive_env_logs.sh
  conda/recipes/conda_build_config.yaml
  installers/conda/osx/create_bundle.sh
  scripts/test/DirectPropertyManagerTest.py
Labels: macOS Only, ISIS Team: Core, DevOps

#39333 Refactor `SaveNexusProcessedTest` for `FileRegistry` -- `ornl-next`
  Framework/DataHandling/test/SaveNexusProcessedTest.h
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/FileResource.h
  Framework/TestHelpers/src/FileResource.cpp
Labels: ornl-next

#39337 Label macOS ARM package differently to x86_64 on GitHub Releases page
  buildconfig/Jenkins/Conda/publish-to-github
Labels: macOS Only, ISIS Team: Core

#39344 Move to pydantic v2.11.4
  conda/recipes/conda_build_config.yaml
Labels: ornl-next

#39348 GroupDetectors reserve EventList space based on EventType
  Framework/DataHandling/src/GroupDetectors2.cpp
Labels: High Priority, Bug, ORNL Team

#39219 Allow SetGoniometer algorithm to take optional matrix as string
  Framework/Crystal/inc/MantidCrystal/SetGoniometer.h
  Framework/Crystal/src/SetGoniometer.cpp
  Framework/Crystal/test/SetGoniometerTest.h
  Framework/Geometry/inc/MantidGeometry/Instrument/Goniometer.h
  Framework/Geometry/src/Instrument/Goniometer.cpp
  docs/source/algorithms/SetGoniometer-v1.rst
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/39219.rst
Labels: Diffraction, ISIS Team: Diffraction

#39324 Add new algorithm CreateBootstrapWorkspaces
  Framework/Algorithms/CMakeLists.txt
  Framework/Algorithms/inc/MantidAlgorithms/CreateBootstrapWorkspaces.h
  Framework/Algorithms/src/CreateBootstrapWorkspaces.cpp
  Framework/Algorithms/test/CreateBootstrapWorkspacesTest.h
  docs/source/algorithms/CreateBootstrapWorkspaces-v1.rst
  docs/source/images/CreateBootstrapWorkspaces_with_error_sampling.png
  docs/source/images/CreateBootstrapWorkspaces_with_spectra_sampling.png
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/39324.rst
Labels: Framework, ISIS Team: Excitations/Vesuvio

#39338 Fix crash in Muon results table
  docs/source/release/v6.13.0/Muon/Muon_Analysis/Bugfixes/39263.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/results_tab_widget/results_tab_model.py
Labels: Muon

#39355 Remove rhash pinning
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid-developer/meta.yaml
Labels: DevOps

#39346 Add documentation for erroreports.core_dumps property
  docs/source/concepts/PropertiesFile.rst
Labels: Documentation, ISIS Team: Core

#39203 Fix bin edge/centre bugs PDFFourierTransform2
  Framework/Algorithms/src/PDFFourierTransform2.cpp
  Framework/Algorithms/test/PDFFourierTransform2Test.h
  Testing/SystemTests/tests/framework/ISIS_PowderPolarisTest.py
  docs/source/algorithms/PDFFourierTransform-v2.rst
  docs/source/release/v6.13.0/Diffraction/Powder/Bugfixes/39203.rst
Labels: Diffraction, Powder, ISIS Team: Diffraction

#39353 Small changes to DataHandling algorithms
  Framework/API/src/WorkspaceHistory.cpp
  Framework/DataHandling/inc/MantidDataHandling/LoadEMU.h
  Framework/DataHandling/src/LoadBBY.cpp
  Framework/DataHandling/src/LoadBankFromDiskTask.cpp
  Framework/DataHandling/src/LoadEMU.cpp
  Framework/DataHandling/src/LoadNexusLogs.cpp
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  Framework/DataHandling/src/LoadPLN.cpp
  Framework/DataHandling/src/PatchBBY.cpp
  Framework/DataHandling/src/SaveNexusProcessedHelper.cpp
  Framework/DataHandling/src/StartAndEndTimeFromNexusFileExtractor.cpp
  Framework/DataHandling/test/LoadEventNexusTest.h
  Framework/MDAlgorithms/src/LoadMD.cpp
  Framework/Nexus/inc/MantidNexus/NeXusFile.hpp
  Framework/Nexus/inc/MantidNexus/NeXusFile_fwd.h
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/inc/MantidNexus/NexusDescriptor.h
  Framework/Nexus/src/NeXusFile.cpp
  Framework/Nexus/src/NexusClasses.cpp
  Framework/Nexus/src/NexusDescriptor.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Technical Debt

#39331 Add capacity to load polarized files to LoadNXcanSAS
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/LoadNXcanSAS.h
  Framework/DataHandling/inc/MantidDataHandling/NXcanSASDefinitions.h
  Framework/DataHandling/inc/MantidDataHandling/NXcanSASUtil.h
  Framework/DataHandling/inc/MantidDataHandling/SaveNXcanSASHelper.h
  Framework/DataHandling/src/LoadNXcanSAS.cpp
  Framework/DataHandling/src/NXcanSASUtil.cpp
  Framework/DataHandling/src/SaveNXcanSAS.cpp
  Framework/DataHandling/src/SaveNXcanSASBase.cpp
  Framework/DataHandling/src/SaveNXcanSASHelper.cpp
  Framework/DataHandling/src/SavePolarizedNXcanSAS.cpp
  Framework/DataHandling/test/LoadNXcanSASTest.h
  Framework/DataHandling/test/NXcanSASFileTest.h
  Framework/DataHandling/test/NXcanSASTestHelper.h
  Framework/DataHandling/test/SaveNXcanSASTest.h
  Framework/DataHandling/test/SavePolarizedNXcanSASTest.h
  Framework/Nexus/inc/MantidNexus/H5Util.h
  Framework/Nexus/src/H5Util.cpp
  docs/source/algorithms/LoadNXcanSAS-v1.rst
  docs/source/release/v6.13.0/SANS/New_features/38526.rst
Labels: SANS, ISIS Team: LSS

#39300 Correct error propagation on PolarizationEfficienciesWildes algorithm
  Framework/Algorithms/inc/MantidAlgorithms/PolarizationCorrections/PolarizationCorrectionsHelpers.h
  Framework/Algorithms/inc/MantidAlgorithms/PolarizationCorrections/PolarizationEfficienciesWildes.h
  Framework/Algorithms/src/PolarizationCorrections/PolarizationEfficienciesWildes.cpp
  Framework/Algorithms/test/PolarizationCorrections/PolarizationCorrectionsHelpersTest.h
  Framework/Algorithms/test/PolarizationCorrections/PolarizationEfficienciesWildesTest.h
  Testing/SystemTests/tests/framework/ReflectometryISISCalculatePolEffTest.py
  Testing/SystemTests/tests/framework/reference/ReflectometryISISCalculatePolEffAllCorrections.nxs.md5
  Testing/SystemTests/tests/framework/reference/ReflectometryISISCalculatePolEffMag.nxs.md5
  Testing/SystemTests/tests/framework/reference/ReflectometryISISCalculatePolEffNonMag.nxs.md5
Labels: Reflectometry, ISIS Team: LSS

#39347 Apply Polarized Properties in ISIS SANS User File V2 to Reduction Workspaces for Saving
  docs/source/release/v6.13.0/SANS/New_features/38525.rst
  scripts/SANS/sans/algorithm_detail/batch_execution.py
  scripts/SANS/sans/command_interface/ISISCommandInterface.py
  scripts/SANS/sans/user_file/toml_parsers/toml_v2_parser.py
  scripts/SANS/sans/user_file/txt_parsers/ParsedDictConverter.py
  scripts/test/SANS/algorithm_detail/batch_execution_test.py
Labels: SANS, ISIS Team: LSS

#39358 Goniometer can't be set by a rotation matrix with small numerical inaccuracy
  Framework/Geometry/src/Instrument/Goniometer.cpp
  Framework/Geometry/test/GoniometerTest.h
Labels: Bug, Diffraction, Single Crystal

#39360 Update cdt_name to conda
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid-developer/meta.yaml
Labels: ISIS Team: Core, Linux Only, DevOps

#39359 Make changes to enable use of new LOQ IDF with event mode data
  scripts/SANS/SANSadd2.py
  scripts/SANS/sans/algorithm_detail/CreateSANSWavelengthPixelAdjustment.py
Labels: ISIS Team: LSS

#39228 Fixing Mantid Fit for unweighted least squares cost function
  Framework/Algorithms/src/CalculatePolynomialBackground.cpp
  Framework/Algorithms/src/DirectILLTubeBackground.cpp
  Framework/Algorithms/test/DirectILLTubeBackgroundTest.h
  Framework/CurveFitting/inc/MantidCurveFitting/CostFunctions/CostFuncFitting.h
  Framework/CurveFitting/inc/MantidCurveFitting/CostFunctions/CostFuncLeastSquares.h
  Framework/CurveFitting/inc/MantidCurveFitting/CostFunctions/CostFuncRwp.h
  Framework/CurveFitting/inc/MantidCurveFitting/CostFunctions/CostFuncUnweightedLeastSquares.h
  Framework/CurveFitting/src/CostFunctions/CostFuncFitting.cpp
  Framework/CurveFitting/src/CostFunctions/CostFuncLeastSquares.cpp
  Framework/CurveFitting/src/CostFunctions/CostFuncRwp.cpp
  Framework/CurveFitting/src/CostFunctions/CostFuncUnweightedLeastSquares.cpp
  Framework/CurveFitting/src/FitMW.cpp
  Framework/CurveFitting/src/IFittingAlgorithm.cpp
  Framework/CurveFitting/test/Algorithms/FitTest.h
  Framework/CurveFitting/test/Algorithms/SeqDomainSpectrumCreatorTest.h
  Framework/CurveFitting/test/CostFunctions/CostFuncUnweightedLeastSquaresTest.h
  Framework/PythonInterface/test/python/plugins/algorithms/IntegratePeaks1DProfileTest.py
  Framework/Reflectometry/src/ReflectometryBackgroundSubtraction.cpp
  Framework/Reflectometry/test/ReflectometryBackgroundSubtractionTest.py
  Framework/SINQ/src/PoldiFitPeaks1D2.cpp
  Framework/SINQ/src/PoldiFitPeaks2D.cpp
  Framework/SINQ/test/PoldiSpectrumLinearBackgroundTest.h
  Testing/SystemTests/tests/framework/SXDAnalysis.py
  Testing/SystemTests/tests/framework/UnweightedLeastSquaresTest.py
  Testing/SystemTests/tests/framework/reference/ILL_IN5_SofQW.nxs.md5
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/algorithms/IntegratePeaks1DProfile-v1.rst
  docs/source/algorithms/ReflectometryBackgroundSubtraction-v1.rst
  docs/source/release/v6.13.0/Framework/Algorithms/Bugfixes/39107.rst
Labels: ISIS Team: Diffraction

#39394 Use a Relative Tolerance in SXD System Test
  Testing/SystemTests/tests/framework/SXDAnalysis.py
Labels: High Priority, Bug, Diffraction

#39404 Add seeAlso between the various live data algorithms
  Framework/LiveData/inc/MantidLiveData/LoadLiveData.h
  Framework/LiveData/inc/MantidLiveData/MonitorLiveData.h
  Framework/LiveData/inc/MantidLiveData/StartLiveData.h
  Framework/LiveData/src/LoadLiveData.cpp
  Framework/LiveData/src/MonitorLiveData.cpp
  Framework/LiveData/src/StartLiveData.cpp
Labels: Documentation

#39411 Remove `napi` "`impl`" methods
  Framework/Nexus/src/napi.cpp
Labels: Technical Debt, Nexus

#39418 Remove the X in NeXusException and NeXusIOHelper
  Framework/API/src/ExperimentInfo.cpp
  Framework/API/src/FileBackedExperimentInfo.cpp
  Framework/API/src/Sample.cpp
  Framework/API/test/ExperimentInfoTest.h
  Framework/DataHandling/inc/MantidDataHandling/LoadEventNexus.h
  Framework/DataHandling/inc/MantidDataHandling/SaveNexusProcessedHelper.h
  Framework/DataHandling/src/CreateChunkingFromInstrument.cpp
  Framework/DataHandling/src/CreateSimulationWorkspace.cpp
  Framework/DataHandling/src/DetermineChunking.cpp
  Framework/DataHandling/src/LoadBankFromDiskTask.cpp
  Framework/DataHandling/src/LoadEmptyInstrument.cpp
  Framework/DataHandling/src/LoadErrorEventsNexus.cpp
  Framework/DataHandling/src/LoadEventAsWorkspace2D.cpp
  Framework/DataHandling/src/LoadEventNexus.cpp
  Framework/DataHandling/src/LoadHelper.cpp
  Framework/DataHandling/src/LoadILLDiffraction.cpp
  Framework/DataHandling/src/LoadILLIndirect2.cpp
  Framework/DataHandling/src/LoadILLLagrange.cpp
  Framework/DataHandling/src/LoadILLPolarizedDiffraction.cpp
  Framework/DataHandling/src/LoadILLReflectometry.cpp
  Framework/DataHandling/src/LoadILLSANS.cpp
  Framework/DataHandling/src/LoadILLTOF3.cpp
  Framework/DataHandling/src/LoadMcStasNexus.cpp
  Framework/DataHandling/src/LoadNXSPE.cpp
  Framework/DataHandling/src/LoadNexusLogs.cpp
  Framework/DataHandling/src/LoadNexusMonitors2.cpp
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  Framework/DataHandling/src/SNSAppendGeometryToNexus.cpp
  Framework/DataHandling/src/SaveNXTomo.cpp
  Framework/DataHandling/src/SaveNexusProcessedHelper.cpp
  Framework/DataHandling/src/UpdateInstrumentFromFile.cpp
  Framework/Geometry/src/Crystal/OrientedLattice.cpp
  Framework/Kernel/src/PropertyNexus.cpp
  Framework/MDAlgorithms/src/LoadMD.cpp
  Framework/Nexus/CMakeLists.txt
  Framework/Nexus/inc/MantidNexus/NexusException.h
  Framework/Nexus/inc/MantidNexus/NexusIOHelper.h
  Framework/Nexus/src/NexusClasses.cpp
  Framework/Nexus/src/NexusDescriptor.cpp
  Framework/Nexus/src/NexusException.cpp
  Framework/Nexus/src/NexusFile.cpp
  Framework/Nexus/test/NeXusFileTest.h
  Framework/Nexus/test/NexusIOHelperTest.h
  Framework/SINQ/src/LoadFlexiNexus.cpp
  Framework/WorkflowAlgorithms/src/SANSSensitivityCorrection.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Technical Debt, Nexus

#39412 Remove napi external file support
  Framework/Nexus/CMakeLists.txt
  Framework/Nexus/inc/MantidNexus/nx_stptok.h
  Framework/Nexus/src/napi.cpp
  Framework/Nexus/src/stptok.cpp
Labels: Technical Debt, Nexus

#39420 Cleanup NeXus::File forward declarations
  Framework/API/inc/MantidAPI/LogManager.h
  Framework/API/inc/MantidAPI/Run.h
  Framework/API/inc/MantidAPI/WorkspaceHistory.h
  Framework/API/test/ExperimentInfoTest.h
  Framework/DataHandling/inc/MantidDataHandling/AlignAndFocusPowderSlim.h
  Framework/DataHandling/inc/MantidDataHandling/BankPulseTimes.h
  Framework/DataHandling/inc/MantidDataHandling/LoadNexusProcessed.h
  Framework/DataHandling/inc/MantidDataHandling/UpdateInstrumentFromFile.h
  Framework/DataHandling/src/DetermineChunking.cpp
  Framework/DataHandling/test/LoadILLReflectometryTest.h
  Framework/Kernel/inc/MantidKernel/EnumeratedStringProperty.h
  Framework/Kernel/inc/MantidKernel/LegacyNexusDescriptor.h
  Framework/Kernel/inc/MantidKernel/PropertyWithValue.h
  Framework/Kernel/inc/MantidKernel/TimeSeriesProperty.h
  Framework/Kernel/src/PropertyNexus.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Nexus

#39421 Handle import errors when simpleapi modules are imported without matplotlib installed
  Framework/PythonInterface/mantid/simpleapi.py
Labels: Bug, ISIS Team: Core
