Repository mantidproject/mantid, pull requests merged in 2025-10, with the labels that each got.

#40014 Added MIDAS IDF
  instrument/Facilities.xml
  instrument/MIDAS_Definition.xml
Labels: Powder

#40020 Refactor SNSLiveEventDataListener and ADARAParser for improved clarit…
  Framework/LiveData/inc/MantidLiveData/SNSLiveEventDataListener.h
  Framework/LiveData/src/ADARA/ADARAParser.cpp
  Framework/LiveData/src/SNSLiveEventDataListener.cpp
  Framework/PythonInterface/mantid/utils/logging.py
  Framework/PythonInterface/test/python/mantid/utils/loggingTest.py
Labels: ornl-next

#40032 Add usage example for changing the log name
  docs/source/api/python/mantid/kernel/Logger.rst
Labels: Documentation

#40034 Fix `SaveMD` performance regression caused by unlimited data chunk dimensions
  Framework/DataObjects/src/BoxControllerNeXusIO.cpp
  Framework/MDAlgorithms/src/SaveMD.cpp
  Framework/MDAlgorithms/src/SaveMD2.cpp
  Framework/Nexus/inc/MantidNexus/NexusFile_fwd.h
  Framework/Nexus/src/NexusFile.cpp
  Framework/Nexus/test/NexusFileReadWriteTest.h
  docs/source/release/v6.14.0/Framework/Algorithms/Bugfixes/39954.rst
Labels: High Priority, Bug

#40042 Adding IMAGINE instrument
  docs/source/release/v6.15.0/Diffraction/Powder/New_features/40014.rst
  docs/source/release/v6.15.0/Diffraction/Single_Crystal/New_features/40042.rst
  instrument/CG4D_Definition.xml
  instrument/Facilities.xml
Labels: Single Crystal

#39974 New Instrument View - Rectangle selection on 2D projection
  qt/python/instrumentview/CMakeLists.txt
  qt/python/instrumentview/instrumentview/FullInstrumentViewPresenter.py
  qt/python/instrumentview/instrumentview/FullInstrumentViewWindow.py
  qt/python/instrumentview/instrumentview/InteractorStyles.py
  qt/python/instrumentview/instrumentview/test/test_interactor_styles.py
  qt/python/instrumentview/instrumentview/test/test_presenter.py
  qt/python/instrumentview/instrumentview/test/test_view.py
Labels: ISIS: Core, Epic

#40060 Remove osx intel from main nightly run
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
Labels: DevOps

#40055 Add new colorbar norm option to sliceviewer
  docs/source/release/v6.15.0/Workbench/SliceViewer/New_features/40055.rst
  qt/python/mantidqt/mantidqt/widgets/colorbar/colorbar.py
  qt/python/mantidqt/mantidqt/widgets/colorbar/test/test_colorbar.py
Labels: Diffraction, Direct Inelastic, Single Crystal, GUI

#40064 Flowchart diagram for LoadWANDSCD
  Framework/PythonInterface/plugins/algorithms/LoadWANDSCD.py
  docs/source/algorithms/LoadWANDSCD-v1.rst
  docs/source/diagrams/LoadWANDSCD-v1_wkflw.dot
  docs/source/release/v6.15.0/Framework/Algorithms/New_features/40063.rst
Labels: ornl-next

#40068 Asinch colobar PR into ornl-next
  docs/source/release/v6.15.0/Workbench/SliceViewer/New_features/40055.rst
  qt/python/mantidqt/mantidqt/widgets/colorbar/colorbar.py
  qt/python/mantidqt/mantidqt/widgets/colorbar/test/test_colorbar.py
Labels: Diffraction, Single Crystal, GUI

#40072 Add diagnostic messages to cmake to help with SIP
  buildconfig/CMake/FindSIP.cmake
Labels: Maintenance

#40074 Add diagnostic messages to cmake to help with SIP
  buildconfig/CMake/FindSIP.cmake
Labels: ornl-next

#40075 VULCAN single bank loading -- `ornl-next`
  Framework/DataHandling/inc/MantidDataHandling/AlignAndFocusPowderSlim.h
  Framework/DataHandling/src/AlignAndFocusPowderSlim.cpp
  Framework/DataHandling/src/AlignAndFocusPowderSlim/ProcessBankTask.cpp
  Framework/DataHandling/test/AlignAndFocusPowderSlimTest.h
  docs/source/release/v6.15.0/Framework/Algorithms/New_features/40067.rst
Labels: ornl-next

#40071 dev-docs: profiling with jemalloc
  dev-docs/source/ProfilingOverview.rst
  dev-docs/source/ProfilingWithJemalloc.rst
  dev-docs/source/index.rst
Labels: Documentation, ORNL Team

#40062 Updated MSlice pin for beta testing
  conda/recipes/conda_build_config.yaml
Labels: High Priority, ISIS: Core, ISIS: Excitations/Vesuvio

#40079 Remove osx 64 from main nightly
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
Labels: ornl-next

#40082 Mslice version
  .pre-commit-config.yaml
  conda/recipes/conda_build_config.yaml
Labels: ornl-next

#40083 AlignAndFocusPowderSlim output multiple workspaces when using splitter
  Framework/DataHandling/inc/MantidDataHandling/AlignAndFocusPowderSlim.h
  Framework/DataHandling/src/AlignAndFocusPowderSlim.cpp
  Framework/DataHandling/src/AlignAndFocusPowderSlim/NexusLoader.cpp
  Framework/DataHandling/test/AlignAndFocusPowderSlimTest.h
  Framework/DataObjects/inc/MantidDataObjects/TimeSplitter.h
  Framework/DataObjects/src/TimeSplitter.cpp
  docs/source/algorithms/AlignAndFocusPowderSlim-v1.rst
  docs/source/release/v6.15.0/Diffraction/Powder/New_features/40035.rst
Labels: ornl-next

#40027 Removed deprecated option from Filter Events GUI
  docs/source/release/v6.15.0/Workbench/Bugfixes/39993.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/FilterEvents/MainWindow.ui
  qt/python/mantidqtinterfaces/mantidqtinterfaces/FilterEvents/eventFilterGUI.py
Labels: Maintenance
