Repository mantidproject/mantid, pull requests merged in 2025-03, with the labels that each got.

#38998 CMake build with `-DUSE_SANITIZER=Address`
  Framework/CurveFitting/inc/MantidCurveFitting/Functions/ProductFunction.h
  Framework/CurveFitting/src/Functions/ProductFunction.cpp
  buildconfig/CMake/FindAsanLib.cmake
  buildconfig/CMake/LinuxPackageScripts.cmake
  buildconfig/CMake/LinuxSetup.cmake
  docs/source/release/v6.13.0/Framework/Build_tools/Bugfixes/38943.rst
  docs/source/release/v6.13.0/framework.rst
  docs/source/release/v6.13.0/index.rst
Labels: ornl-next

#38984 Update schema version in DOI script
  tools/DOI/doi.py
Labels: ISIS Team: Core

#38999 Forward declares of NexusClasses inside DataHandling files
  Framework/DataHandling/inc/MantidDataHandling/DataBlock.h
  Framework/DataHandling/inc/MantidDataHandling/DataBlockComposite.h
  Framework/DataHandling/inc/MantidDataHandling/DataBlockGenerator.h
  Framework/DataHandling/inc/MantidDataHandling/LoadANSTOHelper.h
  Framework/DataHandling/inc/MantidDataHandling/LoadBBY.h
  Framework/DataHandling/inc/MantidDataHandling/LoadEMU.h
  Framework/DataHandling/inc/MantidDataHandling/LoadHelper.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLDiffraction.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLIndirect2.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLLagrange.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLPolarizedDiffraction.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLReflectometry.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLSANS.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLTOF2.h
  Framework/DataHandling/inc/MantidDataHandling/LoadISISNexus2.h
  Framework/DataHandling/inc/MantidDataHandling/LoadISISNexusHelper.h
  Framework/DataHandling/inc/MantidDataHandling/LoadMLZ.h
  Framework/DataHandling/inc/MantidDataHandling/LoadMuonNexusV2.h
  Framework/DataHandling/inc/MantidDataHandling/LoadMuonNexusV2NexusHelper.h
  Framework/DataHandling/inc/MantidDataHandling/LoadNexusProcessed.h
  Framework/DataHandling/inc/MantidDataHandling/LoadPLN.h
  Framework/DataHandling/inc/MantidDataHandling/LoadSINQFocus.h
  Framework/DataHandling/inc/MantidDataHandling/LoadTOFRawNexus.h
  Framework/DataHandling/inc/MantidDataHandling/MultiPeriodLoadMuonStrategy.h
  Framework/DataHandling/inc/MantidDataHandling/PatchBBY.h
  Framework/DataHandling/inc/MantidDataHandling/SinglePeriodLoadMuonStrategy.h
  Framework/DataHandling/src/DataBlock.cpp
  Framework/DataHandling/src/DataBlockComposite.cpp
  Framework/DataHandling/src/DataBlockGenerator.cpp
  Framework/DataHandling/src/LoadHelper.cpp
  Framework/DataHandling/src/LoadILLDiffraction.cpp
  Framework/DataHandling/src/LoadILLIndirect2.cpp
  Framework/DataHandling/src/LoadILLLagrange.cpp
  Framework/DataHandling/src/LoadILLPolarizedDiffraction.cpp
  Framework/DataHandling/src/LoadILLReflectometry.cpp
  Framework/DataHandling/src/LoadILLSALSA.cpp
  Framework/DataHandling/src/LoadILLSANS.cpp
  Framework/DataHandling/src/LoadILLTOF2.cpp
  Framework/DataHandling/src/LoadISISNexus2.cpp
  Framework/DataHandling/src/LoadISISNexusHelper.cpp
  Framework/DataHandling/src/LoadMLZ.cpp
  Framework/DataHandling/src/LoadMuonNexusV2.cpp
  Framework/DataHandling/src/LoadMuonNexusV2NexusHelper.cpp
  Framework/DataHandling/src/LoadSINQFocus.cpp
  Framework/DataHandling/src/MultiPeriodLoadMuonStrategy.cpp
  Framework/DataHandling/src/PatchBBY.cpp
  Framework/DataHandling/src/SinglePeriodLoadMuonStrategy.cpp
  Framework/DataHandling/test/LoadSINQFocusTest.h
  Framework/DataObjects/src/BoxControllerNeXusIO.cpp
  Framework/Nexus/inc/MantidNexus/NexusClasses_fwd.h
  Framework/Nexus/src/NeXusException.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance, ORNL Team

#38821 Fix stack overflow error due to invalid condition
  Framework/Kernel/src/ConfigService.cpp
  Framework/Kernel/test/ConfigServiceTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.13.0/Framework/Python/Bugfixes/38821.rst
Labels: Bug, ISIS Team: Core, Reported By User

#38892 Add check for groups in SaveNXcanSAS
  Framework/DataHandling/inc/MantidDataHandling/SaveNXcanSAS.h
  Framework/DataHandling/src/SaveNXcanSAS.cpp
Labels: Bug, ISIS Team: LSS

#38994 added colors for f-string syntax highlighting in mantid code editor
  docs/source/release/v6.13.0/Workbench/New_features/38080.rst
  qt/widgets/common/src/AlternateCSPythonLexer.cpp
Labels: ISIS Team: Core

#38746 cppcheck hackathon echo 65
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmProgress/AlgorithmProgressDialogPresenter.h
  qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmProgress/AlgorithmProgressPresenter.h
  qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmProgress/AlgorithmProgressPresenterBase.h
  qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmPropertiesWidget.h
  qt/widgets/common/inc/MantidQtWidgets/Common/BatchAlgorithmRunner.h
  qt/widgets/common/inc/MantidQtWidgets/Common/ConfiguredAlgorithm.h
  qt/widgets/common/inc/MantidQtWidgets/Common/ConvolutionFunctionModel.h
  qt/widgets/common/inc/MantidQtWidgets/Common/EditLocalParameterDialog.h
  qt/widgets/common/inc/MantidQtWidgets/Common/FileFinderWidget.h
  qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressDialogPresenter.cpp
  qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressPresenter.cpp
  qt/widgets/common/src/AlgorithmPropertiesWidget.cpp
  qt/widgets/common/src/EditLocalParameterDialog.cpp
  qt/widgets/common/src/FileFinderWidget.cpp
Labels: Maintenance

#39008 Remove muon dependency from DataHandling
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/LoadIDFFromNexus.h
  Framework/DataHandling/test/UpdateInstrumentFromFileTest.h
  Framework/Muon/CMakeLists.txt
  Framework/Muon/inc/MantidMuon/LoadInstrumentFromNexus.h
  Framework/Muon/inc/MantidMuon/LoadMuonLog.h
  Framework/Muon/src/LoadInstrumentFromNexus.cpp
  Framework/Muon/src/LoadMuonLog.cpp
  Framework/Muon/test/LoadInstrumentFromNexusTest.h
  Framework/Muon/test/LoadMuonLogTest.h
  docs/sphinxext/mantiddoc/directives/sourcelink.py
Labels: High Priority

#39018 Cpp check hackathon echo 65 - ornl-next
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmProgress/AlgorithmProgressDialogPresenter.h
  qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmProgress/AlgorithmProgressPresenter.h
  qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmProgress/AlgorithmProgressPresenterBase.h
  qt/widgets/common/inc/MantidQtWidgets/Common/AlgorithmPropertiesWidget.h
  qt/widgets/common/inc/MantidQtWidgets/Common/BatchAlgorithmRunner.h
  qt/widgets/common/inc/MantidQtWidgets/Common/ConfiguredAlgorithm.h
  qt/widgets/common/inc/MantidQtWidgets/Common/ConvolutionFunctionModel.h
  qt/widgets/common/inc/MantidQtWidgets/Common/EditLocalParameterDialog.h
  qt/widgets/common/inc/MantidQtWidgets/Common/FileFinderWidget.h
  qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressDialogPresenter.cpp
  qt/widgets/common/src/AlgorithmProgress/AlgorithmProgressPresenter.cpp
  qt/widgets/common/src/AlgorithmPropertiesWidget.cpp
  qt/widgets/common/src/EditLocalParameterDialog.cpp
  qt/widgets/common/src/FileFinderWidget.cpp
Labels: ornl-next

#39010 Create tests of `NeXus::File` from old `napi` tests
  Framework/Nexus/CMakeLists.txt
  Framework/Nexus/inc/MantidNexus/NeXusFile.hpp
  Framework/Nexus/src/NeXusFile.cpp
  Framework/Nexus/test/NeXusFileTest.h
Labels: ORNL Team, Technical Debt

#39025 Create tests of NeXus::File from old napi tests -- `ornl-next`
  Framework/Nexus/CMakeLists.txt
  Framework/Nexus/inc/MantidNexus/NeXusFile.hpp
  Framework/Nexus/src/NeXusFile.cpp
  Framework/Nexus/test/NeXusFileTest.h
Labels: ornl-next

#38789 Common code in IntegratePeaksSkew, IntegratePeaksShoeboxTOF, FindSXPeaksConvolve, IntegratePeaks1DProfile algorithms moved to a utility module
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/FindSXPeaksConvolve.py
  Framework/PythonInterface/plugins/algorithms/IntegratePeaks1DProfile.py
  Framework/PythonInterface/plugins/algorithms/IntegratePeaksShoeboxTOF.py
  Framework/PythonInterface/plugins/algorithms/IntegratePeaksSkew.py
  Framework/PythonInterface/plugins/algorithms/peakdata_utils.py
  Framework/PythonInterface/test/python/plugins/algorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/IntegratePeaksSkewTest.py
  Framework/PythonInterface/test/python/plugins/algorithms/peakdata_utilsTest.py
  docs/source/release/v6.13.0/Framework/Algorithms/Bugfixes/36989.rst
Labels: Diffraction, Single Crystal, Maintenance

#39021 Fix formatting in DeprecateAlgorithm dev-docs
  dev-docs/source/Standards/DeprecateAlgorithm.rst
Labels: Documentation

#38607 Add output label option to ISIS Energy Transfer tab of Data Reduction
  docs/source/release/v6.13.0/Indirect/New_features/38607.rst
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransfer.ui
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModel.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferModel.h
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferPresenter.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferView.cpp
  qt/scientific_interfaces/Indirect/Reduction/ISISEnergyTransferView.h
  qt/scientific_interfaces/Indirect/test/Reduction/ISISEnergyTransferModelTest.h
  qt/scientific_interfaces/Indirect/test/Reduction/ISISEnergyTransferPresenterTest.h
  qt/scientific_interfaces/Indirect/test/Reduction/MockObjects.h
  qt/widgets/spectroscopy/inc/MantidQtWidgets/Spectroscopy/MockObjects.h
  qt/widgets/spectroscopy/inc/MantidQtWidgets/Spectroscopy/OutputWidget/OutputName.ui
  qt/widgets/spectroscopy/inc/MantidQtWidgets/Spectroscopy/OutputWidget/OutputNamePresenter.h
  qt/widgets/spectroscopy/inc/MantidQtWidgets/Spectroscopy/OutputWidget/OutputNameView.h
  qt/widgets/spectroscopy/src/OutputWidget/OutputNamePresenter.cpp
  qt/widgets/spectroscopy/src/OutputWidget/OutputNameView.cpp
  qt/widgets/spectroscopy/test/OutputWidget/OutputNamePresenterTest.h
Labels: Indirect/Inelastic, ISIS Team: Spectroscopy

#38744 Cppcheck suppressions set 56
  Framework/PythonInterface/mantid/api/src/Exports/AlgorithmManager.cpp
  Framework/PythonInterface/mantid/api/src/Exports/IAlgorithm.cpp
  Framework/PythonInterface/mantid/api/src/Exports/IEventList.cpp
  Framework/PythonInterface/mantid/api/src/Exports/IFunction1D.cpp
  Framework/PythonInterface/mantid/api/src/Exports/IMaskWorkspace.cpp
  Framework/PythonInterface/mantid/api/src/Exports/IPeakFunction.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Maintenance

#39019 Remove unused NXputattra, NXgetattra, NXgetattrainfo and test
  Framework/Nexus/inc/MantidNexus/napi.h
  Framework/Nexus/inc/MantidNexus/napi5.h
  Framework/Nexus/inc/MantidNexus/napi_internal.h
  Framework/Nexus/src/napi.cpp
  Framework/Nexus/src/napi5.cpp
  Framework/Nexus/test/CMakeLists.txt
  Framework/Nexus/test/napi_attra_test.cpp
Labels: ORNL Team, Technical Debt

#39014 Update quickbayes in standalone to 1.0.1b0
  docs/source/release/v6.13.0/Workbench/New_features/39014.rst
  installers/conda/linux/create_tarball.sh
  installers/conda/osx/create_bundle.sh
  installers/conda/win/create_package.sh
Labels: ISIS Team: Spectroscopy, ISIS Team: Core

#39017 Remove Transpose3D algorithm
  Framework/Algorithms/inc/MantidAlgorithms/Transpose.h
  Framework/MDAlgorithms/inc/MantidMDAlgorithms/TransposeMD.h
  Framework/PythonInterface/plugins/algorithms/LoadSINQFile.py
  Framework/SINQ/CMakeLists.txt
  Framework/SINQ/inc/MantidSINQ/SINQTranspose3D.h
  Framework/SINQ/src/SINQTranspose3D.cpp
  docs/source/algorithms/Transpose3D-v1.rst
  docs/source/release/v3.9.0/framework.rst
  docs/source/release/v6.13.0/Framework/Algorithms/Removed/39017.rst
Labels: ISIS Team: Core

#39030 Fix some Cppcheck warnings
  Framework/API/inc/MantidAPI/AlgorithmRuntimeProps.h
  Framework/API/inc/MantidAPI/AnalysisDataService.h
  Framework/API/inc/MantidAPI/BoostOptionalToAlgorithmProperty.h
  Framework/API/inc/MantidAPI/BoxControllerSettingsAlgorithm.h
  Framework/API/inc/MantidAPI/CatalogSession.h
  Framework/API/inc/MantidAPI/Expression.h
  Framework/API/inc/MantidAPI/FileProperty.h
  Framework/API/inc/MantidAPI/FunctionDomain1D.h
  Framework/API/inc/MantidAPI/FunctionValues.h
  Framework/API/src/AnalysisDataService.cpp
  Framework/API/src/BoostOptionalToAlgorithmProperty.cpp
  Framework/API/src/CatalogSession.cpp
  Framework/PythonInterface/mantid/api/src/Exports/CatalogSession.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: ISIS Team: Core

#39036 Remove unused NXputattra, NXgetattra, NXgetattrainfo and test -- `ornl-next`
  Framework/Nexus/inc/MantidNexus/napi.h
  Framework/Nexus/inc/MantidNexus/napi5.h
  Framework/Nexus/inc/MantidNexus/napi_internal.h
  Framework/Nexus/src/napi.cpp
  Framework/Nexus/src/napi5.cpp
  Framework/Nexus/test/CMakeLists.txt
  Framework/Nexus/test/napi_attra_test.cpp
Labels: ornl-next

#39042 Revert "Update quickbayes in standalone to 1.0.1b0"
  docs/source/release/v6.13.0/Workbench/New_features/39014.rst
  installers/conda/linux/create_tarball.sh
  installers/conda/osx/create_bundle.sh
  installers/conda/win/create_package.sh
Labels: High Priority, Bug, Reported By User

#39043 Stop LegacyNexus namespace pollution from `napi.h` -- `ornl-next`
  Framework/DataHandling/src/LoadILLTOF2.cpp
  Framework/LegacyNexus/inc/MantidLegacyNexus/NeXusFile_fwd.h
  Framework/LegacyNexus/inc/MantidLegacyNexus/napi.h
  Framework/LegacyNexus/inc/MantidLegacyNexus/napi4.h
  Framework/LegacyNexus/inc/MantidLegacyNexus/napi5.h
  Framework/LegacyNexus/src/napi.cpp
  Framework/LegacyNexus/test/leak_test1.cpp
  Framework/LegacyNexus/test/leak_test2.cpp
  Framework/LegacyNexus/test/leak_test3.cpp
  Framework/LegacyNexus/test/napi_attra_test.cpp
  Framework/LegacyNexus/test/napi_test.cpp
  Framework/LegacyNexus/test/napi_test_cpp.cpp
  Framework/LegacyNexus/test/napi_test_util.cpp
  Framework/LegacyNexus/test/napi_test_util.h
  Framework/LegacyNexus/test/test_nxunlimited.cpp
  Framework/Muon/src/LoadMuonNexus1.cpp
  Framework/Muon/src/LoadMuonNexus2.cpp
  Framework/Muon/src/MuonNexusReader.cpp
Labels: ornl-next

#39022 Remove LoadNexusMonitors V1 algorithm
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/LoadNexusMonitors.h
  Framework/DataHandling/src/LoadNexusMonitors.cpp
  Framework/DataHandling/test/LoadNexusMonitorsTest.h
  docs/source/algorithms/LoadNexusMonitors-v1.rst
  docs/source/release/v6.13.0/Framework/Algorithms/Removed/39022.rst
Labels: ISIS Team: Core

#39032 Add caching mechanism to GetIPTS
  Framework/PythonInterface/plugins/algorithms/GetIPTS.py
  Framework/PythonInterface/test/python/plugins/algorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/GetIPTSTest.py
  docs/source/algorithms/GetIPTS-v1.rst
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/.gitkeep
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/39032.rst
Labels: ORNL Team

#39047 Add caching mechanism to GetIPTS - ornl-next
  Framework/PythonInterface/plugins/algorithms/GetIPTS.py
  Framework/PythonInterface/test/python/plugins/algorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/GetIPTSTest.py
  docs/source/algorithms/GetIPTS-v1.rst
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/.gitkeep
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/39032.rst
Labels: ornl-next

#39040 Add PeakShapeDetectorBin to IntegratePeaks1DProfile peak integration algorithm
  Framework/PythonInterface/plugins/algorithms/IntegratePeaks1DProfile.py
  Framework/PythonInterface/test/python/plugins/algorithms/IntegratePeaks1DProfileTest.py
  docs/source/release/v6.13.0/Diffraction/Single_Crystal/New_features/38969.rst
Labels: Diffraction, Single Crystal, ISIS Team: Diffraction

#39033 Remove CentroidPeaksMD v1 algorithm
  Framework/MDAlgorithms/CMakeLists.txt
  Framework/MDAlgorithms/inc/MantidMDAlgorithms/CentroidPeaksMD.h
  Framework/MDAlgorithms/src/CentroidPeaksMD.cpp
  Framework/MDAlgorithms/test/CentroidPeaksMDTest.h
  docs/source/algorithms/CentroidPeaksMD-v1.rst
  docs/source/release/v3.9.0/framework.rst
  docs/source/release/v6.13.0/Framework/Algorithms/Removed/39033.rst
Labels: ISIS Team: Core

#39050 Build changes and removed algorithm
  .pre-commit-config.yaml
  Framework/MDAlgorithms/CMakeLists.txt
  Framework/MDAlgorithms/inc/MantidMDAlgorithms/CentroidPeaksMD.h
  Framework/MDAlgorithms/src/CentroidPeaksMD.cpp
  Framework/MDAlgorithms/test/CentroidPeaksMDTest.h
  conda/recipes/mantid-developer/meta.yaml
  conda/recipes/mantidqt/meta.yaml
  docs/source/algorithms/CentroidPeaksMD-v1.rst
  docs/source/release/v3.9.0/framework.rst
  docs/source/release/v6.13.0/Framework/Algorithms/Removed/39033.rst
Labels: ornl-next

#39048 Split the StandardTestData into UnitTestData and DocsTestData
  Framework/API/test/CMakeLists.txt
  Framework/Algorithms/test/CMakeLists.txt
  Framework/Crystal/test/CMakeLists.txt
  Framework/CurveFitting/test/CMakeLists.txt
  Framework/DataHandling/test/CMakeLists.txt
  Framework/Kernel/test/CMakeLists.txt
  Framework/LiveData/test/CMakeLists.txt
  Framework/MDAlgorithms/test/CMakeLists.txt
  Framework/Muon/test/CMakeLists.txt
  Framework/Nexus/test/CMakeLists.txt
  Framework/NexusGeometry/test/CMakeLists.txt
  Framework/Reflectometry/test/CMakeLists.txt
  Framework/SINQ/test/CMakeLists.txt
  Framework/WorkflowAlgorithms/test/CMakeLists.txt
  buildconfig/CMake/SetupDataTargets.cmake
  docs/CMakeLists.txt
Labels: Maintenance

#39052 Split the StandardTestData into UnitTestData and DocsTestData
  Framework/API/test/CMakeLists.txt
  Framework/Algorithms/test/CMakeLists.txt
  Framework/Crystal/test/CMakeLists.txt
  Framework/CurveFitting/test/CMakeLists.txt
  Framework/DataHandling/test/CMakeLists.txt
  Framework/Kernel/test/CMakeLists.txt
  Framework/LiveData/test/CMakeLists.txt
  Framework/MDAlgorithms/test/CMakeLists.txt
  Framework/Muon/test/CMakeLists.txt
  Framework/Nexus/test/CMakeLists.txt
  Framework/NexusGeometry/test/CMakeLists.txt
  Framework/Reflectometry/test/CMakeLists.txt
  Framework/SINQ/test/CMakeLists.txt
  Framework/WorkflowAlgorithms/test/CMakeLists.txt
  buildconfig/CMake/SetupDataTargets.cmake
  docs/CMakeLists.txt
Labels: ornl-next

#39060 Create more tests of `NeXus::File` using based on old `napi` tests - `ornl-next`
  Framework/Nexus/test/NeXusFileTest.h
  Framework/Nexus/test/napi_test.cpp
Labels: ornl-next

#39061 ORNL fork patch fix
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/.gitkeep
Labels: ornl-next

#39045 Restore Windows PowderReduceP2DTest
  Testing/SystemTests/tests/framework/PowderReduceP2DTest.py
Labels: Powder, Windows Only, ORNL Team

#39051 [Sibling] Restore Windows PowderReduceP2DTest
  Testing/SystemTests/tests/framework/PowderReduceP2DTest.py
Labels: Powder, Windows Only, ORNL Team, ornl-next

#39057 Maintenance for the SANSTubeCalibration algorithm
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSTubeCalibration.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/SANS/SANSTubeMerge.py
  Testing/SystemTests/tests/framework/FittingDocumentationTest.py
  docs/source/fitting/fitfunctions/FlatTopPeak.rst
  docs/source/images/FlatTopPeakFnExample.png
Labels: ISIS Team: LSS

#39070 Ready for ORNL fork release v6.12.0.1rc3
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/LoadDspacemap.h
  Framework/DataHandling/inc/MantidDataHandling/SaveDspacemap.h
  Framework/DataHandling/src/LoadDspacemap.cpp
  Framework/DataHandling/src/SaveDspacemap.cpp
  Framework/DataHandling/test/LoadDspacemapTest.h
  Framework/DataHandling/test/SaveDspacemapTest.h
  docs/source/algorithms/LoadDspacemap-v1.rst
  docs/source/algorithms/SaveDspacemap-v1.rst
  docs/source/release/v6.13.0/Framework/Algorithms/Removed/39053.rst
  installers/conda/linux/create_tarball.sh
  qt/applications/workbench/workbench/utils/workspacehistorygeneration.py
Labels: ORNL Team

#39055 Change the member variables for NexusException
  Framework/Nexus/inc/MantidNexus/NeXusException.hpp
  Framework/Nexus/src/NeXusException.cpp
  Framework/Nexus/src/NeXusFile.cpp
  Testing/Data/UnitTest/LOQ49886.nxs.md5
  Testing/Data/UnitTest/POLREF00004699.nxs.md5
Labels: Technical Debt

#39080 Change the member variables for NexusException - ornl-next
  Framework/Nexus/inc/MantidNexus/NeXusException.hpp
  Framework/Nexus/src/NeXusException.cpp
  Framework/Nexus/src/NeXusFile.cpp
  Testing/Data/UnitTest/LOQ49886.nxs.md5
  Testing/Data/UnitTest/POLREF00004699.nxs.md5
Labels: ornl-next

#39077 Moved image for release notes into docs image folder
  docs/source/algorithms/CreateMonteCarloWorkspace-v1.rst
  docs/source/images/CreateMonteCarloWorkspace_spectrum.png
  docs/source/release/v6.12.0/index.rst
Labels: Documentation, Maintenance

#38887 Enable user defined sample and container geometry for abs correction
  Framework/PythonInterface/mantid/utils/absorptioncorrutils.py
  Framework/PythonInterface/plugins/algorithms/SNSPowderReduction.py
  docs/source/release/v6.13.0/Diffraction/Powder/New_features/38887.rst
Labels: Diffraction, Powder, Absorption Corrections

#39082 Move `NeXusFile` tests to make room for more
  Framework/Nexus/CMakeLists.txt
  Framework/Nexus/inc/MantidNexus/NeXusFile_fwd.h
  Framework/Nexus/inc/MantidNexus/NexusIOHelper.h
  Framework/Nexus/src/NeXusFile.cpp
  Framework/Nexus/src/napi5.cpp
  Framework/Nexus/test/CMakeLists.txt
  Framework/Nexus/test/NeXusFileLeakTest.h
  Framework/Nexus/test/NeXusFileNapiTest.h
  Framework/Nexus/test/NeXusFileReadWriteTest.h
  Framework/Nexus/test/NeXusFileTest.h
  Framework/Nexus/test/test_helper.cpp
  Framework/Nexus/test/test_helper.h
Labels: ORNL Team, Technical Debt

#39039 Remove fix for IB21 for C1 and Ci symmetries
  Framework/CurveFitting/src/Functions/CrystalFieldPeaksBase.cpp
  Framework/CurveFitting/test/Functions/CrystalFieldPeaksTest.h
  docs/source/release/v6.13.0/Direct_Geometry/CrystalField/Bugfixes/39039.rst
Labels: Bug, Added during Sprint, ISIS Team: Excitations/Vesuvio

#39078 Updated MSlice manual testing instructions to cover both cutting methods
  dev-docs/source/Testing/Direct/MSliceTestGuide.rst
  docs/source/images/cut_plot_2.png
Labels: Documentation, Found in Beta

#39087 Rename the template defintions to end in hxx
  .gitignore
  Framework/API/CMakeLists.txt
  Framework/API/inc/MantidAPI/Algorithm.hxx
  Framework/API/inc/MantidAPI/IFunction1D.hxx
  Framework/API/inc/MantidAPI/WorkspaceProperty.hxx
  Framework/API/src/Algorithm.cpp
  Framework/API/src/IFunction1D.cpp
  Framework/API/src/IPeakFunction.cpp
  Framework/API/src/PropertyWithValue.cpp
  Framework/API/src/WorkspaceProperty.cpp
  Framework/API/test/AlgorithmTest.h
  Framework/API/test/WorkspacePropertyTest.h
  Framework/Algorithms/src/ChangePulsetime2.cpp
  Framework/Algorithms/src/ExtractSpectra.cpp
  Framework/Algorithms/src/ExtractSpectra2.cpp
  Framework/Algorithms/src/GetEiMonDet3.cpp
  Framework/Algorithms/src/MaskBins.cpp
  Framework/Algorithms/src/MaskBinsFromWorkspace.cpp
  Framework/Algorithms/test/ChangePulsetime2Test.h
  Framework/Algorithms/test/GetDetectorOffsetsTest.h
  Framework/DataHandling/src/MaskSpectra.cpp
  Framework/DataHandling/test/MaskSpectraTest.h
  Framework/DataObjects/CMakeLists.txt
  Framework/DataObjects/inc/MantidDataObjects/MDBin.hxx
  Framework/DataObjects/inc/MantidDataObjects/MDBox.hxx
  Framework/DataObjects/inc/MantidDataObjects/MDBoxBase.hxx
  Framework/DataObjects/inc/MantidDataObjects/MDBoxIterator.hxx
  Framework/DataObjects/inc/MantidDataObjects/MDEventWorkspace.hxx
  Framework/DataObjects/inc/MantidDataObjects/MDGridBox.hxx
  Framework/DataObjects/src/MDEventFactory.cpp
  Framework/DataObjects/src/PropertyWithValue.cpp
  Framework/DataObjects/src/WorkspaceProperty.cpp
  Framework/Kernel/inc/MantidKernel/PropertyWithValue.hxx
  Framework/Kernel/src/ArrayProperty.cpp
  Framework/Kernel/src/MaskedProperty.cpp
  Framework/Kernel/src/MatrixProperty.cpp
  Framework/Kernel/src/PropertyNexus.cpp
  Framework/Kernel/src/PropertyWithValue.cpp
  Framework/Kernel/test/PropertyManagerPropertyTest.h
  Framework/Kernel/test/PropertyWithValueJSONTest.h
  Framework/LiveData/CMakeLists.txt
  Framework/LiveData/inc/MantidLiveData/Kafka/IKafkaStreamDecoder.hxx
  Framework/LiveData/src/Kafka/IKafkaStreamDecoder.cpp
  Framework/LiveData/src/Kafka/KafkaEventStreamDecoder.cpp
  Framework/LiveData/src/Kafka/KafkaHistoStreamDecoder.cpp
  Framework/Reflectometry/src/ReflectometryBackgroundSubtraction.cpp
  Framework/Reflectometry/src/ReflectometrySumInQ.cpp
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/WorkspaceCreationHelper.hxx
  Framework/TestHelpers/src/FakeObjects.cpp
  dev-docs/source/IndexProperty.rst
Labels: Technical Debt

#39093 Rename the template defintions to end in hxx
  .gitignore
  Framework/API/CMakeLists.txt
  Framework/API/inc/MantidAPI/Algorithm.hxx
  Framework/API/inc/MantidAPI/IFunction1D.hxx
  Framework/API/inc/MantidAPI/WorkspaceProperty.hxx
  Framework/API/src/Algorithm.cpp
  Framework/API/src/IFunction1D.cpp
  Framework/API/src/IPeakFunction.cpp
  Framework/API/src/PropertyWithValue.cpp
  Framework/API/src/WorkspaceProperty.cpp
  Framework/API/test/AlgorithmTest.h
  Framework/API/test/WorkspacePropertyTest.h
  Framework/Algorithms/src/ChangePulsetime2.cpp
  Framework/Algorithms/src/ExtractSpectra.cpp
  Framework/Algorithms/src/ExtractSpectra2.cpp
  Framework/Algorithms/src/GetEiMonDet3.cpp
  Framework/Algorithms/src/MaskBins.cpp
  Framework/Algorithms/src/MaskBinsFromWorkspace.cpp
  Framework/Algorithms/test/ChangePulsetime2Test.h
  Framework/Algorithms/test/GetDetectorOffsetsTest.h
  Framework/DataHandling/src/MaskSpectra.cpp
  Framework/DataHandling/test/MaskSpectraTest.h
  Framework/DataObjects/CMakeLists.txt
  Framework/DataObjects/inc/MantidDataObjects/MDBin.hxx
  Framework/DataObjects/inc/MantidDataObjects/MDBox.hxx
  Framework/DataObjects/inc/MantidDataObjects/MDBoxBase.hxx
  Framework/DataObjects/inc/MantidDataObjects/MDBoxIterator.hxx
  Framework/DataObjects/inc/MantidDataObjects/MDEventWorkspace.hxx
  Framework/DataObjects/inc/MantidDataObjects/MDGridBox.hxx
  Framework/DataObjects/src/MDEventFactory.cpp
  Framework/DataObjects/src/PropertyWithValue.cpp
  Framework/DataObjects/src/WorkspaceProperty.cpp
  Framework/Kernel/inc/MantidKernel/PropertyWithValue.hxx
  Framework/Kernel/src/ArrayProperty.cpp
  Framework/Kernel/src/MaskedProperty.cpp
  Framework/Kernel/src/MatrixProperty.cpp
  Framework/Kernel/src/PropertyNexus.cpp
  Framework/Kernel/src/PropertyWithValue.cpp
  Framework/Kernel/test/PropertyManagerPropertyTest.h
  Framework/Kernel/test/PropertyWithValueJSONTest.h
  Framework/LiveData/CMakeLists.txt
  Framework/LiveData/inc/MantidLiveData/Kafka/IKafkaStreamDecoder.hxx
  Framework/LiveData/src/Kafka/IKafkaStreamDecoder.cpp
  Framework/LiveData/src/Kafka/KafkaEventStreamDecoder.cpp
  Framework/LiveData/src/Kafka/KafkaHistoStreamDecoder.cpp
  Framework/Reflectometry/src/ReflectometryBackgroundSubtraction.cpp
  Framework/Reflectometry/src/ReflectometrySumInQ.cpp
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/WorkspaceCreationHelper.hxx
  Framework/TestHelpers/src/FakeObjects.cpp
  dev-docs/source/IndexProperty.rst
Labels: ornl-next

#39086 Add TeixeiraWaterIqtFT fitting function to QENS ConvFit tab
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/functions/TeixeiraWaterIqt.py
  Framework/PythonInterface/plugins/functions/TeixeiraWaterIqtFT.py
  Framework/PythonInterface/plugins/functions/TeixeiraWaterIqtHelper.py
  Framework/PythonInterface/test/python/plugins/functions/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/functions/TeixeiraWaterIqtFTTest.py
  docs/source/fitting/fitfunctions/TeixeiraWaterIqtFT.rst
  docs/source/release/v6.13.0/Inelastic/New_features/37237.rst
  qt/scientific_interfaces/Inelastic/QENSFitting/FitTabConstants.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionBrowser/ConvFunctionTemplateModel.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionBrowser/ConvFunctionTemplateModel.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionBrowser/FitTypes.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionBrowser/FitTypes.h
  qt/scientific_interfaces/Inelastic/QENSFitting/FunctionBrowser/ParamID.h
Labels: Indirect/Inelastic, ISIS Team: Spectroscopy

#39074 Restore PowderReduceP2DTest
  Testing/SystemTests/tests/framework/PowderReduceP2DTest.py
Labels: Diffraction, Powder, ORNL Team

#39098 [Sibling] Restore PowderReduceP2DTest
  Testing/SystemTests/tests/framework/PowderReduceP2DTest.py
Labels: Powder, ORNL Team, ornl-next

#39097 Deprecate UnwrapSNS
  Framework/Algorithms/inc/MantidAlgorithms/UnwrapSNS.h
  Framework/Algorithms/src/UnwrapSNS.cpp
  Framework/PythonInterface/plugins/algorithms/AlignAndFocusPowderFromFiles.py
  Framework/PythonInterface/plugins/algorithms/SNSPowderReduction.py
  Framework/WorkflowAlgorithms/inc/MantidWorkflowAlgorithms/AlignAndFocusPowder.h
  Framework/WorkflowAlgorithms/src/AlignAndFocusPowder.cpp
  docs/source/algorithms/AlignAndFocusPowder-v1.rst
  docs/source/diagrams/AlignAndFocusPowder-v1_wkflw.dot
  docs/source/release/v6.13.0/Framework/Algorithms/Deprecated/39097.rst
  docs/source/release/v6.13.0/Workbench/New_features/39097.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/reduction_gui/widgets/diffraction/diffraction_adv_setup.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/ui/diffraction/diffraction_adv_setup.ui
  scripts/reduction_gui/reduction/diffraction/diffraction_adv_setup_script.py
Labels: ORNL Team

#39100 Expose fitting parameters from Component class to python
  Framework/Geometry/inc/MantidGeometry/Instrument/Component.h
  Framework/Geometry/src/Instrument/Component.cpp
  Framework/PythonInterface/mantid/geometry/src/Exports/Component.cpp
  Framework/PythonInterface/test/python/mantid/geometry/CMakeLists.txt
  Framework/PythonInterface/test/python/mantid/geometry/ComponentTest.py
  docs/source/release/v6.13.0/Diffraction/Powder/New_features/38968.rst
Labels: Diffraction, Powder, ISIS Team: Diffraction

#38976 38882 gsas2scriptable path search revision
  docs/source/release/v6.13.0/Diffraction/Engineering/Bugfixes/38882.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/call_G2sc.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/gsas2/test/test_call_G2sc.py
Labels: Diffraction, Powder, ISIS Team: Diffraction

#39119 Pin conda=25.1.1 to avoid CMake FindPython error in Windows packaging
  buildconfig/Jenkins/Conda/package-conda
Labels: High Priority, ISIS Team: Core, DevOps

#39056 Reduce duplicate jenkins buildsteps
  buildconfig/Jenkins/Conda/build
Labels: Maintenance

#39073 39013 highlight bool keywords in script editor
  docs/source/release/v6.13.0/Workbench/New_features/39013.rst
  qt/widgets/common/inc/MantidQtWidgets/Common/AlternateCSPythonLexer.h
  qt/widgets/common/src/AlternateCSPythonLexer.cpp
Labels: GUI, ISIS Team: Core
