Repository mantidproject/mantid, pull requests merged in 2025-08, with the labels that each got.

#39754 Nexus to use unsigned dimensions
  Framework/DataHandling/inc/MantidDataHandling/BankPulseTimes.h
  Framework/DataHandling/inc/MantidDataHandling/LoadBankFromDiskTask.h
  Framework/DataHandling/inc/MantidDataHandling/LoadHelper.h
  Framework/DataHandling/inc/MantidDataHandling/LoadILLIndirect2.h
  Framework/DataHandling/inc/MantidDataHandling/SaveNXTomo.h
  Framework/DataHandling/src/BankPulseTimes.cpp
  Framework/DataHandling/src/LoadBankFromDiskTask.cpp
  Framework/DataHandling/src/LoadHelper.cpp
  Framework/DataHandling/src/LoadILLDiffraction.cpp
  Framework/DataHandling/src/LoadILLIndirect2.cpp
  Framework/DataHandling/src/LoadILLSANS.cpp
  Framework/DataHandling/src/LoadILLTOF3.cpp
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  Framework/DataHandling/src/SaveNXSPE.cpp
  Framework/DataHandling/src/SaveNXTomo.cpp
  Framework/DataHandling/src/SaveNexusProcessedHelper.cpp
  Framework/DataHandling/test/LoadDetectorInfoTest.h
  Framework/DataObjects/inc/MantidDataObjects/BoxControllerNeXusIO.h
  Framework/DataObjects/src/BoxControllerNeXusIO.cpp
  Framework/DataObjects/src/LeanElasticPeaksWorkspace.cpp
  Framework/DataObjects/src/PeaksWorkspace.cpp
  Framework/Kernel/src/TimeSeriesProperty.cpp
  Framework/MDAlgorithms/src/LoadMD.cpp
  Framework/MDAlgorithms/src/SaveMD2.cpp
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/inc/MantidNexus/NexusFile.h
  Framework/Nexus/inc/MantidNexus/NexusFile_fwd.h
  Framework/Nexus/inc/MantidNexus/NexusIOHelper.h
  Framework/Nexus/src/NexusClasses.cpp
  Framework/Nexus/src/NexusFile.cpp
  Framework/Nexus/test/NapiUnitTest.h
  Framework/Nexus/test/NexusFileLeakTest.h
  Framework/Nexus/test/NexusFileNapiTest.h
  Framework/Nexus/test/NexusFileReadWriteTest.h
  Framework/Nexus/test/NexusFileTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Nexus

#39779 Fix windows nightly
  .github/PULL_REQUEST_TEMPLATE.md
  CMakePresets.json
  Framework/DataHandling/src/AlignAndFocusPowderSlim.cpp
  Framework/DataHandling/src/LoadLog.cpp
  Framework/DataHandling/src/SaveNXcanSASBase.cpp
  Framework/Geometry/inc/MantidGeometry/Rendering/ShapeInfo.h
  Framework/Geometry/src/Rendering/ShapeInfo.cpp
  Framework/HistogramData/inc/MantidHistogramData/HistogramIterator.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  buildconfig/CMake/WindowsSetup.cmake
  buildconfig/Jenkins/Conda/build
  buildconfig/Jenkins/Conda/conda-buildscript
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
  buildconfig/Jenkins/Conda/vcvarsall.sh
Labels: ornl-next

#39768 Remove Nexus time function -- `ornl-next`
  Framework/LegacyNexus/CMakeLists.txt
  Framework/LegacyNexus/inc/MantidLegacyNexus/napi.h
  Framework/LegacyNexus/src/napi.cpp
  Framework/LegacyNexus/src/napi4.cpp
  Framework/LegacyNexus/src/napi5.cpp
  Framework/Nexus/CMakeLists.txt
  Framework/Nexus/inc/MantidNexus/inverted_napi.h
  Framework/Nexus/src/NexusFile.cpp
  Framework/Nexus/src/inverted_napi.cpp
  Framework/Nexus/test/NexusFileTest.h
  Framework/Types/inc/MantidTypes/Core/DateAndTime.h
  Framework/Types/src/Core/DateAndTime.cpp
  Framework/Types/test/DateAndTimeTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: ornl-next

#39783 Allow AlignAndFocusPowderSlim to filter bad pulses during loading
  Framework/Algorithms/src/FilterBadPulses.cpp
  Framework/DataHandling/src/AlignAndFocusPowderSlim.cpp
  Framework/DataHandling/src/AlignAndFocusPowderSlim/ProcessBankTask.cpp
  Framework/DataHandling/test/AlignAndFocusPowderSlimTest.h
  docs/source/algorithms/AlignAndFocusPowderSlim-v1.rst
  docs/source/release/v6.14.0/Diffraction/Powder/New_features/39740.rst
Labels: ornl-next

#39772 Stop passing run config into run-test script following ninja switch
  buildconfig/Jenkins/Conda/run-tests
Labels: High Priority

#39782 Fix Nexus namespace
  Framework/DataHandling/inc/MantidDataHandling/SaveNexusProcessed.h
  Framework/DataHandling/inc/MantidDataHandling/SaveNexusProcessedHelper.h
  Framework/DataHandling/src/AlignAndFocusPowderSlim.cpp
  Framework/DataHandling/src/AlignAndFocusPowderSlim/NexusLoader.cpp
  Framework/DataHandling/src/AlignAndFocusPowderSlim/ProcessBankTask.cpp
  Framework/DataHandling/src/LoadDiffCal.cpp
  Framework/DataHandling/src/LoadILLDiffraction.cpp
  Framework/DataHandling/src/LoadILLLagrange.cpp
  Framework/DataHandling/src/LoadILLSALSA.cpp
  Framework/DataHandling/src/LoadILLSANS.cpp
  Framework/DataHandling/src/LoadMcStas.cpp
  Framework/DataHandling/src/LoadNXcanSAS.cpp
  Framework/DataHandling/src/LoadSassena.cpp
  Framework/DataHandling/src/NXcanSASUtil.cpp
  Framework/DataHandling/src/SaveDiffCal.cpp
  Framework/DataHandling/src/SaveNXcanSASBase.cpp
  Framework/DataHandling/src/SaveNXcanSASHelper.cpp
  Framework/DataHandling/src/SaveNexusProcessed.cpp
  Framework/DataHandling/src/SaveNexusProcessedHelper.cpp
  Framework/DataHandling/test/LoadNexusProcessedTest.h
  Framework/DataHandling/test/LoadSNSNexusTest.h
  Framework/DataHandling/test/NXcanSASFileTest.h
  Framework/DataHandling/test/SaveNXSPETest.h
  Framework/DataHandling/test/SaveNexusESSTest.h
  Framework/MDAlgorithms/test/LoadMDTest.h
  Framework/Nexus/inc/MantidNexus/H5Util.h
  Framework/Nexus/inc/MantidNexus/NexusAddress.h
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/inc/MantidNexus/NexusDescriptor.h
  Framework/Nexus/inc/MantidNexus/NexusException.h
  Framework/Nexus/inc/MantidNexus/NexusFile.h
  Framework/Nexus/inc/MantidNexus/NexusFile_fwd.h
  Framework/Nexus/inc/MantidNexus/NexusIOHelper.h
  Framework/Nexus/src/H5Util.cpp
  Framework/Nexus/src/NexusClasses.cpp
  Framework/Nexus/src/NexusDescriptor.cpp
  Framework/Nexus/src/NexusFile.cpp
  Framework/Nexus/test/H5UtilTest.h
  Framework/Nexus/test/NexusFileNapiTest.h
  Framework/Nexus/test/NexusIOHelperTest.h
  Framework/NexusGeometry/src/NexusGeometryParser.cpp
  Framework/NexusGeometry/src/NexusGeometrySave.cpp
  Framework/NexusGeometry/test/NexusGeometryParserTest.h
  Framework/Parallel/src/IO/EventLoader.cpp
  Framework/Parallel/src/IO/MultiProcessEventLoader.cpp
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/NexusFileReader.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: Nexus

#39714 Crosshair optimization
  docs/source/release/v6.14.0/Workbench/New_features/39491.rst
  qt/applications/workbench/workbench/plotting/figuremanager.py
Labels: GUI

#39780 Depend on matplotlib-base instead of matplotlib
  conda/recipes/mantid/meta.yaml
Labels: Maintenance

#39785 Stop passing run config into run-test script following ninja switch
  buildconfig/Jenkins/Conda/run-tests
Labels: ornl-next

#39786 Specify glibc for linux in conda recipies
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid/meta.yaml
  conda/recipes/mantidqt/meta.yaml
Labels: High Priority, Linux Only, Added during Sprint

#39794 Specify glibc for linux in conda recipes
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid/meta.yaml
  conda/recipes/mantidqt/meta.yaml
Labels: ornl-next

#39792 Improve compile time of Kernel/Atom.cpp
  Framework/Kernel/src/Atom.cpp
  tools/PeriodicTable/generate_atom_code.py
Labels: Maintenance

#39797 NexusFile cleanup
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/inc/MantidNexus/NexusFile.h
  Framework/Nexus/inc/MantidNexus/NexusIOHelper.h
  Framework/Nexus/src/NexusClasses.cpp
  Framework/Nexus/src/NexusDescriptor.cpp
  Framework/Nexus/src/NexusFile.cpp
  Framework/Nexus/test/NexusFileTest.h
Labels: ornl-next

#39770 Add validator polsans transmission workspaces
  Framework/API/CMakeLists.txt
  Framework/API/inc/MantidAPI/PolSANSWorkspaceValidator.h
  Framework/API/src/PolSANSWorkspaceValidator.cpp
  Framework/API/test/PolSANSWorkspaceValidatorTest.h
  Framework/Algorithms/inc/MantidAlgorithms/PolarizationCorrections/HeliumAnalyserEfficiency.h
  Framework/Algorithms/src/DetermineSpinStateOrder.cpp
  Framework/Algorithms/src/PolarizationCorrections/FlipperEfficiency.cpp
  Framework/Algorithms/src/PolarizationCorrections/HeliumAnalyserEfficiency.cpp
  Framework/Algorithms/src/PolarizationCorrections/PolarizerEfficiency.cpp
  Framework/Algorithms/test/DetermineSpinStateOrderTest.h
  Framework/Algorithms/test/PolarizationCorrections/FlipperEfficiencyTest.h
  Framework/Algorithms/test/PolarizationCorrections/HeliumAnalyserEfficiencyTest.h
  Framework/Algorithms/test/PolarizationCorrections/PolarizerEfficiencyTest.h
  Framework/PythonInterface/mantid/api/src/Exports/WorkspaceValidators.cpp
  Framework/PythonInterface/plugins/algorithms/AssertSpinStateOrder.py
  Framework/PythonInterface/test/python/mantid/api/WorkspaceValidatorsTest.py
  docs/source/algorithms/AssertSpinStateOrder-v1.rst
Labels: SANS, Epic

#39805 Add linux selector to stdlib('c') jinja functions
  conda/recipes/mantid/meta.yaml
  conda/recipes/mantidqt/meta.yaml
Labels: High Priority, ISIS: Core, Added during Sprint, DevOps

#39757 Fix bug where mantid crashes after sample shape and material are set
  Framework/API/src/Sample.cpp
  Framework/Algorithms/test/XrayAbsorptionCorrectionTest.h
  Framework/DataHandling/test/SetSampleTest.h
  Framework/Geometry/inc/MantidGeometry/Objects/CSGObject.h
  Framework/Geometry/src/Objects/CSGObject.cpp
  Framework/PythonInterface/mantid/api/src/Exports/Sample.cpp
  Framework/PythonInterface/mantid/geometry/src/Exports/CSGObject.cpp
  Testing/SystemTests/tests/framework/SampleWithShapeAndMaterialSaveNexusTest.py
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.14.0/Direct_Geometry/General/Bugfixes/39757.rst
Labels: Bug, Framework, ISIS: Core

#39802 Nexus File cleanup :broom: -- 2
  Framework/Nexus/inc/MantidNexus/H5Util.h
  Framework/Nexus/src/H5Util.cpp
  Framework/Nexus/src/NexusFile.cpp
Labels: Nexus

#39541 Add option to update UB matrix when CommonUBForAll=False and table contains only peaks from one run
  Framework/Crystal/src/IndexPeaks.cpp
  Framework/Crystal/test/IndexPeaksTest.h
  docs/source/release/v6.14.0/Framework/Algorithms/New_features/38964.rst
Labels: Diffraction, Single Crystal, ISIS: Diffraction

#39812 Add option to update UB matrix when CommonUBForAll=False and table contains only peaks from one run
  Framework/Crystal/src/IndexPeaks.cpp
  Framework/Crystal/test/IndexPeaksTest.h
  docs/source/release/v6.14.0/Framework/Algorithms/New_features/38964.rst
Labels: ornl-next

#39807 Expose SpinStateValidator to python and use in AssertSpinStateOrder
  Framework/PythonInterface/mantid/api/src/Exports/ADSValidator.cpp
  Framework/PythonInterface/mantid/kernel/CMakeLists.txt
  Framework/PythonInterface/mantid/kernel/src/Exports/SpinStateValidator.cpp
  Framework/PythonInterface/plugins/algorithms/AssertSpinStateOrder.py
Labels: SANS, Maintenance

#39815 update ornl externaldata mirror
  buildconfig/CMake/MantidExternalData.cmake
Labels: DevOps

#39824 Sphinx update
  .pre-commit-config.yaml
  buildconfig/CMake/FindSphinx.cmake
  buildconfig/CMake/FindSphinx.py
  conda/recipes/mantiddocs/build.sh
  dev-docs/source/Standards/DocumentationGuideForDevs.rst
  docs/CMakeLists.txt
  docs/source/conf.py
Labels: ornl-next

#39811 Added troubleshooting section for WSL developer documentation
  dev-docs/source/WindowsSubsystemForLinux.rst
Labels: Documentation, Maintenance, ISIS: Core

#39827 Fix jenkinsfile variable scopes to avoid warnings
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
Labels: ISIS: Core, Added during Sprint, DevOps

#39771 Rework HeliumAnalyserEfficiency Algorithm to make time decay fit
  Framework/Algorithms/inc/MantidAlgorithms/PolarizationCorrections/HeliumAnalyserEfficiency.h
  Framework/Algorithms/src/PolarizationCorrections/HeliumAnalyserEfficiency.cpp
  Framework/Algorithms/test/PolarizationCorrections/HeliumAnalyserEfficiencyTest.h
  Testing/SystemTests/tests/framework/PolarizationCorrections/HeliumAnalyserEfficiencyTest.py
  Testing/SystemTests/tests/framework/reference/HeliumAnalyserCurvesReference.nxs.md5
  Testing/SystemTests/tests/framework/reference/HeliumAnalyserEfficiencyReference.nxs.md5
  Testing/SystemTests/tests/framework/reference/HeliumAnalyserParamsReference.nxs.md5
  Testing/SystemTests/tests/framework/reference/PolarizerEfficiencyReference.nxs.md5
  Testing/SystemTests/tests/framework/reference/UnpolHeliumAnalyserCurvesReference.nxs.md5
  Testing/SystemTests/tests/framework/reference/UnpolHeliumAnalyserEfficiencyReference.nxs.md5
  Testing/SystemTests/tests/framework/reference/UnpolHeliumAnalyserParamsReference.nxs.md5
  Testing/SystemTests/tests/framework/reference/UnpolPolarizerEfficiencyReference.nxs.md5
  docs/source/algorithms/HeliumAnalyserEfficiency-v1.rst
  docs/source/release/v6.14.0/SANS/New_features/39653.rst
Labels: SANS, Epic

#39852 Remove __future__ imports
  Framework/PythonInterface/plugins/algorithms/VesuvioAnalysis.py
  Framework/PythonInterface/test/python/plugins/algorithms/FindGoniometerFromUBTest.py
  buildconfig/CMake/Packaging/AddPythonPath.py.in
  qt/python/mantidqt/mantidqt/plotting/test/test_figuretype.py
  qt/python/mantidqt/mantidqt/widgets/codeeditor/execution.py
  qt/python/mantidqt/mantidqt/widgets/codeeditor/test/test_execution.py
  qt/widgets/common/src/PythonRunner.cpp
  scripts/Inelastic/vesuvio/analysisHelpers.py
  scripts/abins/instruments/ideal2d.py
  scripts/abins/instruments/panther.py
  scripts/reduction_gui/reduction/toftof/toftof_reduction.py
Labels: ornl-next

#39828 Exposed a few methods from Instrumentviewer into python using SIP
  qt/python/mantidqt/mantidqt/widgets/instrumentview/_instrumentview.sip
  qt/python/mantidqt/mantidqt/widgets/instrumentview/presenter.py
  qt/python/mantidqt/mantidqt/widgets/instrumentview/test/test_instrumentview_presenter.py
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/InstrumentWidget.h
Labels: ISIS: Core

#39857 Cmake maintenance
  buildconfig/CMake/Bootstrap.cmake
  buildconfig/CMake/CCacheSetup.cmake
  conda/recipes/mantid/bld.bat
  conda/recipes/mantid/build.sh
  conda/recipes/mantiddocs/build.sh
  conda/recipes/mantidqt/bld.bat
  conda/recipes/mantidqt/build.sh
  conda/recipes/mantidworkbench/bld.bat
  conda/recipes/mantidworkbench/build.sh
Labels: Maintenance

#39858 Cmake maintenance
  buildconfig/CMake/Bootstrap.cmake
  buildconfig/CMake/CCacheSetup.cmake
  conda/recipes/mantid/bld.bat
  conda/recipes/mantid/build.sh
  conda/recipes/mantiddocs/build.sh
  conda/recipes/mantidqt/bld.bat
  conda/recipes/mantidqt/build.sh
  conda/recipes/mantidworkbench/bld.bat
  conda/recipes/mantidworkbench/build.sh
Labels: ornl-next

#39854 Remove conda packages from previous builds before archiving to github
  buildconfig/Jenkins/Conda/nightly_build_and_deploy.jenkinsfile
Labels: Bug, ISIS: Core, DevOps

#39866 Pin to newer seekpath that doesn't depend on future package
  buildconfig/Jenkins/Conda/package-conda
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid-developer/meta.yaml
  conda/recipes/mantid/meta.yaml
  docs/source/release/v6.14.0/Framework/Dependencies/New_features/.gitkeep
  docs/source/release/v6.14.0/Framework/Dependencies/New_features/39866.rst
Labels: Maintenance, Dependencies, Vulnerability

#39612 Add partial functionality to visualisation features in plotting tab
  docs/source/interfaces/direct/dns_reduction/dns_single_crystal_elastic_plotting_tab.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_powder_tof/helpers/helpers_for_testing.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_single_crystal_elastic/data_structures/dns_single_crystal_map.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_single_crystal_elastic/plot/elastic_single_crystal_helpers.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_single_crystal_elastic/plot/elastic_single_crystal_plot_model.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_single_crystal_elastic/plot/elastic_single_crystal_plot_plot.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_single_crystal_elastic/plot/elastic_single_crystal_plot_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_single_crystal_elastic/plot/elastic_single_crystal_plot_view.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/dns_single_crystal_elastic/plot/grid_locator.py
  qt/python/mantidqtinterfaces/test/CMakeLists.txt
  qt/python/mantidqtinterfaces/test/dns_single_crystal_elastic/CMakeLists.txt
  qt/python/mantidqtinterfaces/test/dns_single_crystal_elastic/data_structures/dns_single_crystal_map_test.py
  qt/python/mantidqtinterfaces/test/dns_single_crystal_elastic/plot/elastic_single_crystal_helpers_test.py
  qt/python/mantidqtinterfaces/test/dns_single_crystal_elastic/plot/elastic_single_crystal_plot_model_test.py
  qt/python/mantidqtinterfaces/test/dns_single_crystal_elastic/plot/elastic_single_crystal_plot_plot_test.py
  qt/python/mantidqtinterfaces/test/dns_single_crystal_elastic/plot/elastic_single_crystal_plot_presenter_test.py
  qt/python/mantidqtinterfaces/test/dns_single_crystal_elastic/plot/elastic_single_crystal_plot_widget_test.py
  qt/python/mantidqtinterfaces/test/dns_single_crystal_elastic/plot/grid_locator_test.py
Labels: MLZ Team

#39860 Move jemalloc LD_PRELOAD to be set during environment activation
  buildconfig/CMake/LinuxPackageScripts.cmake
  buildconfig/CMake/Packaging/activate_mantid.sh.in
  buildconfig/CMake/Packaging/deactivate_mantid.sh.in
  conda/recipes/mantiddocs/build.sh
  conda/recipes/mantidqt/build.sh
  conda/recipes/mantidworkbench/build.sh
  docs/source/release/v6.14.0/Framework/Algorithms/New_features/39860.rst
Labels: Framework

#39869 Move jemalloc LD_PRELOAD to be set during environment activation
  buildconfig/CMake/LinuxPackageScripts.cmake
  buildconfig/CMake/Packaging/activate_mantid.sh.in
  buildconfig/CMake/Packaging/deactivate_mantid.sh.in
  conda/recipes/mantiddocs/build.sh
  conda/recipes/mantidqt/build.sh
  conda/recipes/mantidworkbench/build.sh
  docs/source/release/v6.14.0/Framework/Algorithms/New_features/39860.rst
Labels: ornl-next

#39803 Update numpy pinning strategy
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid-developer/meta.yaml
  conda/recipes/mantid/meta.yaml
Labels: ISIS: Core, Dependencies, DevOps

#39871 Fix Windows packaging script after parallel event loader removal
  installers/conda/win/create_package.sh
Labels: High Priority, Windows Only, Added during Sprint

#39875 Update numpy pinning strategy
  .pre-commit-config.yaml
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid-developer/meta.yaml
  conda/recipes/mantid/meta.yaml
  installers/conda/win/create_package.sh
Labels: ornl-next

#39876 Update getting dev-docs for VS2022 install
  dev-docs/source/GettingStarted/CloningMantid.rst
  dev-docs/source/GettingStarted/GettingStartedCondaLinux.rst
  dev-docs/source/GettingStarted/GettingStartedCondaOSX.rst
  dev-docs/source/GettingStarted/GettingStartedCondaWindows.rst
Labels: Documentation, Technical Debt
