Repository mantidproject/mantid, pull requests merged in 2025-04, with the labels that each got.

#38870 38863 Update Engineering Diffraction Calibration region of interest functionality
  Testing/Data/SystemTest/ENGINX/TestingCalFiles/example1/my_grouping.cal.md5
  Testing/Data/SystemTest/ENGINX/TestingCalFiles/example2/my_grouping.cal.md5
  Testing/Data/SystemTest/ENGINX/TestingCalFiles/example3/my_grouping.cal.md5
  Testing/SystemTests/tests/framework/EnginXScriptTest.py
  dev-docs/source/Testing/EngineeringDiffraction/EngineeringDiffractionTestGuide.rst
  docs/source/images/EngDiff_Calibration.png
  docs/source/interfaces/diffraction/Engineering Diffraction.rst
  docs/source/release/v6.13.0/Diffraction/Engineering/Bugfixes/38863.rst
  docs/source/release/v6.13.0/Diffraction/Engineering/New_features/38863.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/calibration/calibration_tab.ui
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/calibration/presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/calibration/test/test_calib_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/calibration/view.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/cropping/cropping_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/cropping/cropping_view.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/cropping/cropping_widget.ui
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/common/cropping/test/test_cropping_presenter.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/focus/test/test_focus_model.py
  scripts/Engineering/EnggUtils.py
  scripts/Engineering/EnginX.py
  scripts/Engineering/common/calibration_info.py
  scripts/Engineering/common/test/test_calibration_info.py
  scripts/Engineering/test/test_EnggUtils.py
Labels: Diffraction, ISIS Team: Diffraction

#39115 A variety of Cppcheck fixes
  Framework/Algorithms/inc/MantidAlgorithms/ExtractMaskToTable.h
  Framework/Algorithms/inc/MantidAlgorithms/GeneratePeaks.h
  Framework/Algorithms/inc/MantidAlgorithms/GetAllEi.h
  Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/SparseWorkspace.h
  Framework/Algorithms/src/ExtractMaskToTable.cpp
  Framework/Algorithms/src/GeneratePeaks.cpp
  Framework/Algorithms/src/GetAllEi.cpp
  Framework/Algorithms/src/PolarizationCorrections/SpinStateValidator.cpp
  Framework/Algorithms/src/SampleCorrections/SparseWorkspace.cpp
  Framework/Crystal/inc/MantidCrystal/LoadIsawSpectrum.h
  Framework/Crystal/inc/MantidCrystal/SaveHKL.h
  Framework/Crystal/src/LoadIsawSpectrum.cpp
  Framework/Crystal/src/SaveHKL.cpp
  Framework/CurveFitting/inc/MantidCurveFitting/Functions/MultivariateGaussianComptonProfile.h
  Framework/CurveFitting/src/Functions/MultivariateGaussianComptonProfile.cpp
  Framework/MDAlgorithms/inc/MantidMDAlgorithms/ImportMDHistoWorkspaceBase.h
  Framework/MDAlgorithms/src/ImportMDHistoWorkspaceBase.cpp
  Framework/Muon/inc/MantidMuon/ApplyMuonDetectorGroupPairing.h
  Framework/Muon/inc/MantidMuon/ApplyMuonDetectorGrouping.h
  Framework/Muon/inc/MantidMuon/AsymmetryCalc.h
  Framework/Muon/inc/MantidMuon/CalMuonDetectorPhases.h
  Framework/Muon/inc/MantidMuon/LoadAndApplyMuonDetectorGrouping.h
  Framework/Muon/inc/MantidMuon/MuonGroupingAsymmetry.h
  Framework/Muon/inc/MantidMuon/MuonGroupingCounts.h
  Framework/Muon/inc/MantidMuon/MuonPairingAsymmetry.h
  Framework/Muon/inc/MantidMuon/MuonPreProcess.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  qt/widgets/common/inc/MantidQtWidgets/Common/FitPropertyBrowser.h
  qt/widgets/common/src/AlgorithmDialog.cpp
  qt/widgets/common/src/FitPropertyBrowser.cpp
Labels: ISIS Team: Core

#39072 Some stl related cppcheck fixes
  Framework/API/src/FileFinder.cpp
  Framework/Geometry/src/Crystal/SpaceGroup.cpp
  Framework/Geometry/src/Crystal/SpaceGroupFactory.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  qt/widgets/common/inc/MantidQtWidgets/Common/MantidWSIndexDialog.h
  qt/widgets/common/src/MantidTreeModel.cpp
  qt/widgets/common/src/MantidTreeWidget.cpp
  qt/widgets/common/src/WorkspacePresenter/WorkspaceTreeWidget.cpp
Labels: Maintenance, ISIS Team: Core

#39127 Pin pydantic to fix failing test
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid-developer/meta.yaml
Labels: High Priority

#39128 Add ORNL mirror for external data
  buildconfig/CMake/MantidExternalData.cmake
Labels: DevOps

#39123 Reduce duplicate jenkins buildsteps - ornl-next
  buildconfig/Jenkins/Conda/build
Labels: ornl-next

#39134 Add ORNL mirror for external data - ornl-next
  buildconfig/CMake/MantidExternalData.cmake
Labels: ornl-next

#39111 Get rid of void pointers for data in NexusFile
  Framework/DataHandling/inc/MantidDataHandling/LoadISISNexus2.h
  Framework/DataHandling/inc/MantidDataHandling/LoadNexusProcessed.h
  Framework/DataHandling/inc/MantidDataHandling/SaveNexusProcessedHelper.h
  Framework/DataHandling/src/LoadEMU.cpp
  Framework/DataHandling/src/LoadISISNexus2.cpp
  Framework/DataHandling/src/LoadNexusProcessed.cpp
  Framework/DataHandling/src/LoadPLN.cpp
  Framework/DataHandling/src/SaveNexusProcessedHelper.cpp
  Framework/DataObjects/src/LeanElasticPeaksWorkspace.cpp
  Framework/DataObjects/src/PeaksWorkspace.cpp
  Framework/MDAlgorithms/inc/MantidMDAlgorithms/LoadMD.h
  Framework/MDAlgorithms/src/LoadMD.cpp
  Framework/Nexus/inc/MantidNexus/NeXusFile.hpp
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/inc/MantidNexus/NexusClasses_fwd.h
  Framework/Nexus/src/NeXusFile.cpp
  Framework/Nexus/src/NexusClasses.cpp
  Framework/Nexus/test/NeXusFileLeakTest.h
  Framework/Nexus/test/NeXusFileNapiTest.h
  Framework/Nexus/test/NeXusFileReadWriteTest.h
  Framework/Nexus/test/napi_test_cpp.cpp
Labels: Technical Debt

#39125 fix same unit on lhs and rhs but output not unitless
  Framework/Algorithms/src/Divide.cpp
  Framework/Algorithms/test/MultiplyDivideTest.in.h
  docs/source/release/v6.13.0/Framework/Algorithms/Bugfixes/.gitkeep
  docs/source/release/v6.13.0/Framework/Algorithms/Bugfixes/39125.rst
Labels: Bug, ORNL Team

#39120 Create unit tests of NeXusFile
  Framework/Nexus/inc/MantidNexus/NeXusFile.hpp
  Framework/Nexus/src/NeXusFile.cpp
  Framework/Nexus/test/NeXusFileReadWriteTest.h
  Framework/Nexus/test/NeXusFileTest.h
  Framework/TestHelpers/src/FileResource.cpp
Labels: Technical Debt

#39084 Change Rasterize function to take separate Gauge Volume Shape and Sample Shape
  Framework/Algorithms/src/AnyShapeAbsorption.cpp
  Framework/Algorithms/src/CylinderAbsorption.cpp
  Framework/Algorithms/src/MultipleScatteringCorrectionDistGraber.cpp
  Framework/Algorithms/src/PaalmanPingsAbsorptionCorrection.cpp
  Framework/Algorithms/test/AnyShapeAbsorptionTest.h
  Framework/Geometry/inc/MantidGeometry/Rasterize.h
  Framework/Geometry/src/Rasterize.cpp
  Framework/Geometry/test/RasterizeTest.h
  docs/source/release/v6.13.0/Diffraction/Engineering/Bugfixes/39084.rst
Labels: Bug, Diffraction

#39142 create specialized vector 3D comparison operators -- `ornl-next`
  Framework/DataObjects/inc/MantidDataObjects/TableColumn.h
  Framework/Kernel/inc/MantidKernel/V3D.h
  Framework/Kernel/src/FloatingPointComparison.cpp
  Framework/Kernel/src/V3D.cpp
  Framework/Kernel/test/FloatingPointComparisonTest.h
Labels: ornl-next

#39143 Create unit tests of NeXusFile -- `ornl-next`
  Framework/Nexus/inc/MantidNexus/NeXusFile.hpp
  Framework/Nexus/src/NeXusFile.cpp
  Framework/Nexus/test/NeXusFileReadWriteTest.h
  Framework/Nexus/test/NeXusFileTest.h
  Framework/TestHelpers/src/FileResource.cpp
Labels: ornl-next

#39145 Change Rasterize function to take separate Gauge Volume Shape and Sample Shape - ORNL-NEXT
  Framework/Algorithms/src/AnyShapeAbsorption.cpp
  Framework/Algorithms/src/CylinderAbsorption.cpp
  Framework/Algorithms/src/MultipleScatteringCorrectionDistGraber.cpp
  Framework/Algorithms/src/PaalmanPingsAbsorptionCorrection.cpp
  Framework/Algorithms/test/AnyShapeAbsorptionTest.h
  Framework/Geometry/inc/MantidGeometry/Rasterize.h
  Framework/Geometry/src/Rasterize.cpp
  Framework/Geometry/test/RasterizeTest.h
  docs/source/release/v6.13.0/Diffraction/Engineering/Bugfixes/39084.rst
Labels: Bug, ORNL Team, ornl-next

#39113 Relax test tolerance in BayesQuasiTest
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/BayesQuasiTest.py
Labels: ISIS Team: Core

#39049 Fix for User Function Dialog button hidden behind scroll bar
  docs/source/release/v6.13.0/Workbench/Bugfixes/39049.rst
  docs/source/tutorials/mantid_basic_course/fitting_data/03_fit_model_choices.rst
  qt/widgets/common/src/QtPropertyBrowser/StringDialogEditor.cpp
Labels: Bug, macOS Only, ISIS Team: Core

#39108 Add mantid-developer update instructions to dev docs
  dev-docs/source/GettingStarted/MantidDeveloperSetup.rst
Labels: Documentation, ISIS Team: Core

#39116 Short forms of H-M symbols can now be used in CIF files
  Framework/PythonInterface/plugins/algorithms/LoadCIF.py
  Framework/PythonInterface/test/python/plugins/algorithms/LoadCIFTest.py
  docs/source/release/v6.13.0/Direct_Geometry/General/New_features/39116.rst
Labels: Added during Sprint, Reported By User, ISIS Team: Excitations/Vesuvio

#39140 Divide fix ornl version
  Framework/Algorithms/src/Divide.cpp
  Framework/Algorithms/test/MultiplyDivideTest.in.h
  docs/source/release/v6.13.0/Framework/Algorithms/Bugfixes/.gitkeep
  docs/source/release/v6.13.0/Framework/Algorithms/Bugfixes/39125.rst
Labels: ORNL Team, ornl-next

#39153 Add git-blame-ignore-revs to hide bot commits - ornl-next
  .git-blame-ignore-revs
  dev-docs/source/GitWorkflow.rst
  docs/source/release/v6.13.0/Framework/New_features/39133.rst
Labels: ornl-next

#39121 [Sibling] Deprecate UnwrapSNS
  Framework/Algorithms/inc/MantidAlgorithms/UnwrapSNS.h
  Framework/Algorithms/src/UnwrapSNS.cpp
  Framework/PythonInterface/plugins/algorithms/AlignAndFocusPowderFromFiles.py
  Framework/PythonInterface/plugins/algorithms/SNSPowderReduction.py
  Framework/WorkflowAlgorithms/inc/MantidWorkflowAlgorithms/AlignAndFocusPowder.h
  Framework/WorkflowAlgorithms/src/AlignAndFocusPowder.cpp
  docs/source/algorithms/AlignAndFocusPowder-v1.rst
  docs/source/diagrams/AlignAndFocusPowder-v1_wkflw.dot
  docs/source/release/v6.13.0/Framework/Algorithms/Deprecated/39097.rst
  docs/source/release/v6.13.0/Workbench/New_features/39097.rst
  qt/python/mantidqtinterfaces/mantidqtinterfaces/reduction_gui/widgets/diffraction/diffraction_adv_setup.py
  qt/python/mantidqtinterfaces/mantidqtinterfaces/ui/diffraction/diffraction_adv_setup.ui
  scripts/reduction_gui/reduction/diffraction/diffraction_adv_setup_script.py
Labels: ORNL Team, ornl-next

#39152 Remove convenience functions for setting int dimensions
  Framework/DataHandling/inc/MantidDataHandling/SaveNexusProcessedHelper.h
  Framework/DataHandling/src/SaveNXTomo.cpp
  Framework/DataHandling/src/SaveNexusProcessed.cpp
  Framework/DataHandling/src/SaveNexusProcessedHelper.cpp
  Framework/DataHandling/test/LoadDetectorInfoTest.h
  Framework/DataHandling/test/LoadNexusMonitorsTest.h
  Framework/DataObjects/src/LeanElasticPeaksWorkspace.cpp
  Framework/DataObjects/src/PeaksWorkspace.cpp
  Framework/Geometry/src/Crystal/OrientedLattice.cpp
  Framework/Kernel/src/TimeSeriesProperty.cpp
  Framework/MDAlgorithms/src/SaveMD2.cpp
  Framework/MDAlgorithms/src/SaveZODS.cpp
  Framework/Nexus/inc/MantidNexus/NeXusFile.hpp
  Framework/Nexus/src/NeXusFile.cpp
  Framework/Nexus/test/NeXusFileNapiTest.h
  Framework/Nexus/test/napi_test_cpp.cpp
Labels: Technical Debt

#39156 Remove convenience functions for setting int dimensions - ornl-next
  Framework/DataHandling/inc/MantidDataHandling/SaveNexusProcessedHelper.h
  Framework/DataHandling/src/SaveNXTomo.cpp
  Framework/DataHandling/src/SaveNexusProcessed.cpp
  Framework/DataHandling/src/SaveNexusProcessedHelper.cpp
  Framework/DataHandling/test/LoadDetectorInfoTest.h
  Framework/DataHandling/test/LoadNexusMonitorsTest.h
  Framework/DataObjects/src/LeanElasticPeaksWorkspace.cpp
  Framework/DataObjects/src/PeaksWorkspace.cpp
  Framework/Geometry/src/Crystal/OrientedLattice.cpp
  Framework/Kernel/src/TimeSeriesProperty.cpp
  Framework/MDAlgorithms/src/SaveMD2.cpp
  Framework/MDAlgorithms/src/SaveZODS.cpp
  Framework/Nexus/inc/MantidNexus/NeXusFile.hpp
  Framework/Nexus/src/NeXusFile.cpp
  Framework/Nexus/test/NeXusFileNapiTest.h
  Framework/Nexus/test/napi_test_cpp.cpp
Labels: ornl-next

#39160 Version pinning - ornl-next
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid-developer/meta.yaml
  conda/recipes/mantid/meta.yaml
Labels: ornl-next

#39067 Change results group workspace suffix for single fits in QENS Fitting interface
  Framework/CurveFitting/inc/MantidCurveFitting/Algorithms/QENSFitUtilities.h
  Framework/CurveFitting/src/Algorithms/QENSFitSequential.cpp
  Framework/CurveFitting/src/Algorithms/QENSFitSimultaneous.cpp
  Framework/CurveFitting/src/Algorithms/QENSFitUtilities.cpp
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/IndirectReplaceFitResult.py
  docs/source/release/v6.13.0/Inelastic/Bugfixes/38827.rst
  qt/scientific_interfaces/Inelastic/QENSFitting/EditResultsDialog.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FitOutputOptionsModel.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FitOutputOptionsView.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FittingModel.cpp
  qt/scientific_interfaces/Inelastic/QENSFitting/FittingModel.h
  qt/scientific_interfaces/Inelastic/test/QENSFitting/FittingModelTest.h
Labels: Bug, Indirect/Inelastic

#39126 Avoid casting negative times to unsigned int
  Framework/Kernel/src/TimeSeriesProperty.cpp
  Framework/Kernel/test/TimeSeriesPropertyTest.h
  docs/source/release/v6.13.0/Framework/Bugfixes/39126.rst
Labels: ISIS Team: Core

#39161 Fix a bunch of typos in algorithm docs
  docs/source/algorithms/AlignAndFocusPowder-v1.rst
  docs/source/algorithms/AlignComponents-v1.rst
  docs/source/algorithms/AnvredCorrection-v1.rst
  docs/source/algorithms/BASISReduction-v1.rst
  docs/source/algorithms/CalculateDynamicRange-v1.rst
  docs/source/algorithms/CalculateEfficiencyCorrection-v1.rst
  docs/source/algorithms/CalculatePlaczekSelfScattering-v1.rst
  docs/source/algorithms/CalculatePlaczekSelfScattering-v2.rst
  docs/source/algorithms/CalculateSlits-v1.rst
  docs/source/algorithms/CheckMantidVersion-v1.rst
  docs/source/algorithms/ClearUB-v1.rst
  docs/source/algorithms/ConvertCWPDMDToSpectra-v1.rst
  docs/source/algorithms/ConvertCWSDExpToMomentum-v1.rst
  docs/source/algorithms/ConvertCWSDMDtoHKL-v1.rst
  docs/source/algorithms/ConvertFitFunctionForMuonTFAsymmetry-v1.rst
  docs/source/algorithms/ConvertPeaksWorkspace-v1.rst
  docs/source/algorithms/ConvertSpiceDataToRealSpace-v1.rst
  docs/source/algorithms/ConvertToMD-v1.rst
  docs/source/algorithms/ConvertWANDSCDtoQ-v1.rst
  docs/source/algorithms/CopyInstrumentParameters-v1.rst
  docs/source/algorithms/CorelliCalibrationApply-v1.rst
  docs/source/algorithms/CreateSampleWorkspace-v1.rst
  docs/source/algorithms/CrossCorrelate-v1.rst
  docs/source/algorithms/CutMD-v1.rst
  docs/source/algorithms/D7AbsoluteCrossSections-v1.rst
  docs/source/algorithms/DNSComputeDetEffCorrCoefs-v1.rst
  docs/source/algorithms/DetermineChunking-v1.rst
  docs/source/algorithms/DiffractionFocussing-v2.rst
  docs/source/algorithms/DirectILLAutoProcess-v1.rst
  docs/source/algorithms/DirectILLReduction-v1.rst
  docs/source/algorithms/DiscusMultipleScatteringCorrection-v1.rst
  docs/source/algorithms/DoublePulseFit-v1.rst
  docs/source/algorithms/EnggCalibrate-v1.rst
  docs/source/algorithms/EnggFocus-v1.rst
  docs/source/algorithms/FitIncidentSpectrum-v1.rst
  docs/source/algorithms/LinkedUBs-v1.rst
  docs/source/algorithms/LoadEventNexus-v1.rst
  docs/source/algorithms/MDNormSCDPreprocessIncoherent-v1.rst
  docs/source/algorithms/MuonMaxent-v1.rst
  docs/source/algorithms/PelicanReduction-v1.rst
  docs/source/algorithms/PolDiffILLReduction-v1.rst
  docs/source/algorithms/ProfileChiSquared1D-v1.rst
  docs/source/algorithms/Rebin-v1.rst
  docs/source/algorithms/Rebin2D-v1.rst
  docs/source/algorithms/RebinRagged-v1.rst
  docs/source/algorithms/RebinRagged-v2.rst
  docs/source/algorithms/ReflectometryMomentumTransfer-v1.rst
  docs/source/algorithms/RotateInstrumentComponent-v1.rst
  docs/source/algorithms/SANSILLIntegration-v1.rst
  docs/source/algorithms/SCDCalibratePanels-v2.rst
  docs/source/algorithms/SaveAscii-v2.rst
  docs/source/algorithms/SaveHKLCW-v1.rst
  docs/source/algorithms/SavePlot1D-v1.rst
  docs/source/algorithms/SetScalingPSD-v1.rst
  docs/source/algorithms/SingleCrystalDiffuseReduction-v1.rst
  docs/source/algorithms/SmoothNeighbours-v1.rst
  docs/source/algorithms/SolidAngle-v1.rst
  docs/source/algorithms/TOFTOFMergeRuns-v1.rst
  docs/source/algorithms/TransposeMD-v1.rst
  docs/source/algorithms/ViewBOA-v1.rst
Labels: Documentation, ISIS Team: Core

#39166 Handle HB2A run merge exceptions - ornl-next
  Framework/PythonInterface/plugins/algorithms/HB2AReduce.py
  Framework/PythonInterface/test/python/plugins/algorithms/HB2AReduceTest.py
  Testing/Data/UnitTest/HB2A_exp0954__Ge_113_IN_vcorr.txt.md5
  Testing/Data/UnitTest/HB2A_exp0954_scan0017.dat.md5
  Testing/Data/UnitTest/HB2A_exp0954_scan0018.dat.md5
  Testing/Data/UnitTest/HB2A_exp0954_scan0022.dat.md5
  docs/source/release/v6.13.0/Diffraction/Powder/Bugfixes/39112.rst
Labels: ornl-next

#39165 Avoid casting negative times to unsigned in -- `ornl-next`
  Framework/Kernel/src/TimeSeriesProperty.cpp
  Framework/Kernel/test/TimeSeriesPropertyTest.h
  docs/source/release/v6.13.0/Framework/Bugfixes/39126.rst
Labels: ornl-next

#39164 A selection of weekly Cppcheck fixes
  Framework/Algorithms/inc/MantidAlgorithms/AbsorptionCorrection.h
  Framework/Algorithms/inc/MantidAlgorithms/ApplyInstrumentToPeaks.h
  Framework/Algorithms/inc/MantidAlgorithms/BinaryOperation.h
  Framework/Algorithms/inc/MantidAlgorithms/CalculateCountRate.h
  Framework/Algorithms/inc/MantidAlgorithms/CalculatePlaczekSelfScattering.h
  Framework/Algorithms/inc/MantidAlgorithms/ConvertToDistribution.h
  Framework/Algorithms/inc/MantidAlgorithms/CuboidGaugeVolumeAbsorption.h
  Framework/Algorithms/inc/MantidAlgorithms/DetectorDiagnostic.h
  Framework/Algorithms/inc/MantidAlgorithms/DiscusMultipleScatteringCorrection.h
  Framework/Algorithms/inc/MantidAlgorithms/EQSANSResolution.h
  Framework/Algorithms/inc/MantidAlgorithms/FFT.h
  Framework/Algorithms/inc/MantidAlgorithms/FindDetectorsOutsideLimits.h
  Framework/Algorithms/inc/MantidAlgorithms/MedianDetectorTest.h
  Framework/Algorithms/src/MedianDetectorTest.cpp
  Framework/Crystal/inc/MantidCrystal/SaveIsawPeaks.h
  Framework/Crystal/src/SaveIsawPeaks.cpp
  Framework/CurveFitting/inc/MantidCurveFitting/Algorithms/FitPowderDiffPeaks.h
  Framework/CurveFitting/src/Algorithms/FitPowderDiffPeaks.cpp
  Framework/DataHandling/inc/MantidDataHandling/LoadGSS.h
  Framework/DataHandling/inc/MantidDataHandling/LoadSpiceAscii.h
  Framework/DataHandling/src/LoadGSS.cpp
  Framework/DataHandling/src/LoadSpiceAscii.cpp
  Framework/Kernel/inc/MantidKernel/MaterialBuilder.h
  Framework/Kernel/src/MaterialBuilder.cpp
  buildconfig/CMake/CppCheck_Suppressions.txt.in
Labels: ISIS Team: Core

#39135 Update BeamProfileFactory
  Framework/Algorithms/CMakeLists.txt
  Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/IBeamProfile.h
  Framework/Algorithms/src/SampleCorrections/CircularBeamProfile.cpp
  Framework/Algorithms/src/SampleCorrections/IBeamProfile.cpp
  Framework/Algorithms/src/SampleCorrections/RectangularBeamProfile.cpp
  Framework/Algorithms/test/IBeamProfileTest.h
Labels: Absorption Corrections, ORNL Team

#39168 Delete `NexusTester`
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/NexusTester.h
  Framework/DataHandling/src/NexusTester.cpp
  Framework/DataHandling/test/NexusTesterTest.h
  docs/source/algorithms/NexusTester-v1.rst
  docs/source/release/v6.13.0/Framework/Algorithms/Removed/39168.rst
Labels: Technical Debt

#39094 Fix for slab size to data size mismatch, on write of ragged workspaces.
  Framework/DataHandling/inc/MantidDataHandling/SaveNexusProcessedHelper.h
  Framework/DataHandling/src/SaveNexusProcessedHelper.cpp
  Framework/DataHandling/test/SaveNexusProcessedTest.h
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/WorkspaceCreationHelper.h
  docs/source/release/v6.13.0/Framework/Algorithms/Bugfixes/39094.rst
Labels: ORNL Team

#38940 SANS TOML V2: Polarization Options Added to User Files
  docs/source/release/v6.13.0/SANS/New_features/38524.rst
  docs/source/techniques/SANS-Toml-v1.rst
  scripts/SANS/sans/gui_logic/presenter/run_tab_presenter.py
  scripts/SANS/sans/state/AllStates.py
  scripts/SANS/sans/state/IStateParser.py
  scripts/SANS/sans/state/StateObjects/StatePolarization.py
  scripts/SANS/sans/test_helper/toml_parser_test_helpers.py
  scripts/SANS/sans/user_file/toml_parsers/toml_base_parser.py
  scripts/SANS/sans/user_file/toml_parsers/toml_base_schema.py
  scripts/SANS/sans/user_file/toml_parsers/toml_parser.py
  scripts/SANS/sans/user_file/toml_parsers/toml_v1_parser.py
  scripts/SANS/sans/user_file/toml_parsers/toml_v1_schema.py
  scripts/SANS/sans/user_file/toml_parsers/toml_v2_parser.py
  scripts/SANS/sans/user_file/toml_parsers/toml_v2_schema.py
  scripts/SANS/sans/user_file/txt_parsers/ParsedDictConverter.py
  scripts/test/SANS/gui_logic/test_run_tab_presenter.py
  scripts/test/SANS/state/CMakeLists.txt
  scripts/test/SANS/state/state_polarization_test.py
  scripts/test/SANS/user_file/toml_parsers/CMakeLists.txt
  scripts/test/SANS/user_file/toml_parsers/toml_parser_test.py
  scripts/test/SANS/user_file/toml_parsers/toml_v1_parser_test.py
  scripts/test/SANS/user_file/toml_parsers/toml_v1_schema_test.py
  scripts/test/SANS/user_file/toml_parsers/toml_v2_parser_test.py
  scripts/test/SANS/user_file/toml_parsers/toml_v2_schema_test.py
Labels: SANS, ISIS Team: LSS

#39163 Fix PredictPeaks Min/Max angle when using CalculateGoniometerForCW
  Framework/Crystal/src/PredictPeaks.cpp
  Framework/Crystal/test/PredictPeaksTest.h
  Framework/Geometry/inc/MantidGeometry/Instrument/Goniometer.h
  Framework/Geometry/src/Instrument/Goniometer.cpp
  Framework/Geometry/test/GoniometerTest.h
  Framework/PythonInterface/mantid/geometry/src/Exports/Goniometer.cpp
  Framework/PythonInterface/test/python/mantid/geometry/GoniometerTest.py
  Testing/SystemTests/tests/framework/PredictPeaksTest.py
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.13.0/Diffraction/Single_Crystal/Bugfixes/39163.rst
Labels: Single Crystal

#39124 Fixed an out of bounds error coming from IntegratePeaksShoeboxTOF alg…
  Framework/PythonInterface/plugins/algorithms/IntegratePeaksShoeboxTOF.py
  Testing/SystemTests/tests/framework/SXDAnalysis.py
  docs/source/release/v6.13.0/Framework/Algorithms/Bugfixes/38143.rst
Labels: Bug, Diffraction, Powder, ISIS Team: Diffraction

#39177 Move conda build tools to base environment
  buildconfig/Jenkins/Conda/package-conda
  buildconfig/Jenkins/Conda/package-standalone
Labels: High Priority, Maintenance, Extra Attention, ISIS Team: Core, Dependencies, Technical Debt, DevOps

#39172 Fix for slab size to data size mismatch, on write of ragged workspaces.
  Framework/DataHandling/inc/MantidDataHandling/SaveNexusProcessedHelper.h
  Framework/DataHandling/src/SaveNexusProcessedHelper.cpp
  Framework/DataHandling/test/SaveNexusProcessedTest.h
  Framework/TestHelpers/inc/MantidFrameworkTestHelpers/WorkspaceCreationHelper.h
  docs/source/release/v6.13.0/Framework/Algorithms/Bugfixes/39094.rst
Labels: ORNL Team, ornl-next

#38600 Capture c++ stack traces from core dump files on linux
  Framework/Kernel/inc/MantidKernel/ErrorReporter.h
  Framework/Kernel/src/ErrorReporter.cpp
  Framework/Kernel/test/ErrorReporterTest.h
  Framework/Properties/Mantid.properties.template
  Framework/PythonInterface/mantid/kernel/src/Exports/ErrorReporter.cpp
  Framework/PythonInterface/test/python/mantid/kernel/ConfigServiceTest.py
  conda/recipes/mantid-developer/meta.yaml
  conda/recipes/mantidworkbench/meta.yaml
  docs/source/release/v6.13.0/Workbench/New_features/38405.rst
  qt/applications/workbench/workbench/app/start.py
  qt/applications/workbench/workbench/app/workbench_process.py
  qt/applications/workbench/workbench/plugins/exception_handler/__init__.py
  qt/python/mantidqt/CMakeLists.txt
  qt/python/mantidqt/mantidqt/dialogs/errorreports/main.py
  qt/python/mantidqt/mantidqt/dialogs/errorreports/presenter.py
  qt/python/mantidqt/mantidqt/dialogs/errorreports/run_pystack.py
  qt/python/mantidqt/mantidqt/dialogs/errorreports/test/test_errorreport_presenter.py
  qt/python/mantidqt/mantidqt/dialogs/errorreports/test/test_run_pystack.py
  tools/DefaultConfigFiles/Mantid.user.properties
Labels: Extra Attention, ISIS Team: Core, Epic

#39104 Add side-by-side-view-locations to SNAP detector panels
  docs/source/release/v6.13.0/Diffraction/Engineering/Bugfixes/39104.rst
  instrument/SNAP_Definition.xml
Labels: ORNL Team

#39141 Assorted cppcheck fixes, mainly in qtwidgetscommon
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  qt/widgets/common/inc/MantidQtWidgets/Common/QtPropertyBrowser/qtpropertymanager.h
  qt/widgets/common/inc/MantidQtWidgets/Common/QtPropertyBrowser/qttreepropertybrowser.h
  qt/widgets/common/inc/MantidQtWidgets/Common/QtPropertyBrowser/qtvariantproperty.h
  qt/widgets/common/src/QtPropertyBrowser/qtpropertymanager.cpp
  qt/widgets/common/src/QtPropertyBrowser/qttreepropertybrowser.cpp
  qt/widgets/common/src/QtPropertyBrowser/qtvariantproperty.cpp
  qt/widgets/common/src/RepoModel.cpp
  qt/widgets/common/src/SequentialFitDialog.cpp
  qt/widgets/common/src/TextPropertyWidget.cpp
  qt/widgets/common/src/WorkspaceSelector.cpp
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/PeakMarker2D.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/Shape2DCollection.h
  qt/widgets/instrumentview/inc/MantidQtWidgets/InstrumentView/Viewport.h
  qt/widgets/instrumentview/src/Shape2D.cpp
  qt/widgets/instrumentview/src/Shape2DCollection.cpp
  qt/widgets/instrumentview/src/Viewport.cpp
  qt/widgets/mplcpp/inc/MantidQtWidgets/MplCpp/PeakMarker.h
  qt/widgets/mplcpp/inc/MantidQtWidgets/MplCpp/RangeMarker.h
  qt/widgets/mplcpp/inc/MantidQtWidgets/MplCpp/SingleMarker.h
  qt/widgets/mplcpp/src/PeakMarker.cpp
  qt/widgets/mplcpp/src/RangeMarker.cpp
  qt/widgets/mplcpp/src/SingleMarker.cpp
Labels: Maintenance, ISIS Team: Core

#39184 Expose `ExperimentInfo::populateInstrumentParameters`
  Framework/PythonInterface/mantid/api/src/Exports/ExperimentInfo.cpp
  docs/source/release/v6.12.0/Framework/Python/New_features/38684.rst
Labels: ornl-next

#39170 Abins number selection improvements
  docs/source/release/v6.13.0/Indirect/Algorithms/New_features/39170.rst
  scripts/abins/abinsalgorithm.py
  scripts/test/Abins/AbinsAlgorithmTest.py
Labels: ISIS Team: Spectroscopy

#39179 Pin quasielasticbayes to 0.3.0
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid-developer/meta.yaml
  conda/recipes/mantid/meta.yaml
Labels: ISIS Team: Core

#39187 Sliceviewer: Add option to display HKL peak positions calculated from q instead of peak index - ornl-next
  docs/source/release/v6.13.0/Workbench/SliceViewer/New_features/39169.rst
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/presenter.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/test/modeltesthelpers.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/test/test_peaksviewer_model.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/test/test_peaksviewer_view.py
  qt/python/mantidqt/mantidqt/widgets/sliceviewer/peaksviewer/view.py
Labels: ornl-next

#39189 Deprecating UnwrapMonitorsInTOF
  Framework/Algorithms/inc/MantidAlgorithms/UnwrapMonitorsInTOF.h
  Framework/Algorithms/src/UnwrapMonitorsInTOF.cpp
  docs/source/release/v6.13.0/Framework/Algorithms/Deprecated/39132.rst
Labels: ornl-next

#39188 Deprecate LoadPreNexus and LoadPreNexusMonitors - ornl-next
  Framework/DataHandling/inc/MantidDataHandling/LoadPreNexus.h
  Framework/DataHandling/inc/MantidDataHandling/LoadPreNexusMonitors.h
  Framework/DataHandling/src/LoadPreNexus.cpp
  Framework/DataHandling/src/LoadPreNexusMonitors.cpp
  docs/source/release/v6.13.0/Framework/Data_Handling/Deprecated/39176.rst
Labels: ornl-next

#39194 Do not allow switching to cmake v4 yet
  conda/recipes/conda_build_config.yaml
Labels: High Priority, Maintenance

#39198 Do not allow switching to cmake v4 yet - ornl-next
  conda/recipes/conda_build_config.yaml
Labels: ornl-next

#39192 rename argument `is_polarized_dataset` as `enable_instrument_settings`
  Framework/PythonInterface/mantid/utils/reflectometry/orso_helper.py
  Framework/PythonInterface/plugins/algorithms/SaveISISReflectometryORSO.py
  Framework/PythonInterface/test/python/mantid/utils/reflectometry/orso_helper_test.py
Labels: ORNL Team

#39191 rename argument `is_polarized_dataset` as `enable_instrument_settings`
  Framework/PythonInterface/mantid/utils/reflectometry/orso_helper.py
  Framework/PythonInterface/plugins/algorithms/SaveISISReflectometryORSO.py
  Framework/PythonInterface/test/python/mantid/utils/reflectometry/orso_helper_test.py
Labels: ornl-next

#39193 Delete NexusTester Algorithm -- `ornl-next`
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/NexusTester.h
  Framework/DataHandling/src/NexusTester.cpp
  Framework/DataHandling/test/NexusTesterTest.h
  docs/source/algorithms/NexusTester-v1.rst
  docs/source/release/v6.13.0/Framework/Algorithms/Removed/39168.rst
Labels: ornl-next

#39195 Remove deprecated algorithm LoadSNSspec
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/LoadSNSspec.h
  Framework/DataHandling/inc/MantidDataHandling/LoadSpec.h
  Framework/DataHandling/src/LoadSNSspec.cpp
  Framework/DataHandling/test/LoadSNSspecTest.h
  docs/source/algorithms/LoadSNSspec-v1.rst
  docs/source/release/v6.13.0/Framework/Algorithms/Removed/39195.rst
Labels: ORNL Team

#39200 Pin quasielasticbayes to fix standalone
  conda/recipes/conda_build_config.yaml
Labels: High Priority, Bug, ISIS Team: Core

#39202 Remove deprecated algorithm LoadSNSspec
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/LoadSNSspec.h
  Framework/DataHandling/inc/MantidDataHandling/LoadSpec.h
  Framework/DataHandling/src/LoadSNSspec.cpp
  Framework/DataHandling/test/LoadSNSspecTest.h
  docs/source/algorithms/LoadSNSspec-v1.rst
  docs/source/release/v6.13.0/Framework/Algorithms/Removed/39195.rst
Labels: ornl-next

#39178 Improve numerical stability of PhaseQuadMuon
  Framework/Muon/CMakeLists.txt
  Framework/Muon/src/PhaseQuadMuon.cpp
  Framework/Muon/test/PhaseQuadMuonTest.h
  docs/source/algorithms/PhaseQuad-v1.rst
  docs/source/release/v6.13.0/Muon/Algorithms/Bugfixes/39178.rst
Labels: Muon, ISIS Team: Core

#39209 Quasielasticbayes pinning - ornl-next
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid-developer/meta.yaml
  conda/recipes/mantid/meta.yaml
Labels: ornl-next

#39190 Update snap idf ornlnext
  docs/source/release/v6.13.0/Diffraction/Engineering/Bugfixes/39104.rst
  instrument/SNAP_Definition.xml
Labels: ornl-next

#39211 ornl-next packaging issue
  Framework/API/inc/MantidAPI/AlgorithmRuntimeProps.h
  Framework/API/inc/MantidAPI/AnalysisDataService.h
  Framework/API/inc/MantidAPI/BoostOptionalToAlgorithmProperty.h
  Framework/API/inc/MantidAPI/BoxControllerSettingsAlgorithm.h
  Framework/API/inc/MantidAPI/CatalogSession.h
  Framework/API/inc/MantidAPI/Expression.h
  Framework/API/inc/MantidAPI/FileProperty.h
  Framework/API/inc/MantidAPI/FunctionDomain1D.h
  Framework/API/inc/MantidAPI/FunctionValues.h
  Framework/API/src/AnalysisDataService.cpp
  Framework/API/src/BoostOptionalToAlgorithmProperty.cpp
  Framework/API/src/CatalogSession.cpp
  Framework/Kernel/inc/MantidKernel/ErrorReporter.h
  Framework/Kernel/src/ErrorReporter.cpp
  Framework/Kernel/test/ErrorReporterTest.h
  Framework/Properties/Mantid.properties.template
  Framework/PythonInterface/mantid/api/src/Exports/CatalogSession.cpp
  Framework/PythonInterface/mantid/kernel/src/Exports/ErrorReporter.cpp
  Framework/PythonInterface/test/python/mantid/kernel/ConfigServiceTest.py
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  conda/recipes/mantid-developer/meta.yaml
  conda/recipes/mantidworkbench/meta.yaml
  docs/source/release/v6.13.0/Workbench/New_features/38405.rst
  qt/applications/workbench/workbench/app/start.py
  qt/applications/workbench/workbench/app/workbench_process.py
  qt/applications/workbench/workbench/plugins/exception_handler/__init__.py
  qt/python/mantidqt/CMakeLists.txt
  qt/python/mantidqt/mantidqt/dialogs/errorreports/main.py
  qt/python/mantidqt/mantidqt/dialogs/errorreports/presenter.py
  qt/python/mantidqt/mantidqt/dialogs/errorreports/run_pystack.py
  qt/python/mantidqt/mantidqt/dialogs/errorreports/test/test_errorreport_presenter.py
  qt/python/mantidqt/mantidqt/dialogs/errorreports/test/test_run_pystack.py
  tools/DefaultConfigFiles/Mantid.user.properties
Labels: ornl-next

#39205 Fix casting negative double to unsigned int in GenerateGroupingPowder
  Framework/DataHandling/src/GenerateGroupingPowder.cpp
  Framework/DataHandling/test/GenerateGroupingPowder2Test.h
  Framework/DataHandling/test/GenerateGroupingPowderTest.h
  docs/source/release/v6.13.0/Framework/Algorithms/Bugfixes/39205.rst
Labels: Bug

#39222 Fix casting negative double to unsigned int in GenerateGroupingPowder -- `ornl-next`
  Framework/DataHandling/src/GenerateGroupingPowder.cpp
  Framework/DataHandling/test/GenerateGroupingPowder2Test.h
  Framework/DataHandling/test/GenerateGroupingPowderTest.h
  docs/source/release/v6.13.0/Framework/Algorithms/Bugfixes/39205.rst
Labels: ornl-next

#39221 Add quickbayes as a mantid dependency
  Framework/PythonInterface/mantid/utils/pip.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesQuasi2.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/BayesStretch2.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/BayesQuasi2Test.py
  Framework/PythonInterface/test/python/plugins/algorithms/WorkflowAlgorithms/BayesStretch2Test.py
  conda/recipes/conda_build_config.yaml
  conda/recipes/mantid-developer/meta.yaml
  conda/recipes/mantid/meta.yaml
  docs/source/release/v6.13.0/Inelastic/Algorithms/New_features/35918.rst
  installers/conda/linux/create_tarball.sh
  installers/conda/osx/create_bundle.sh
  installers/conda/win/create_package.sh
Labels: Indirect/Inelastic, ISIS Team: Core, Dependencies, Technical Debt

#39158 Add Gauge Volume to Monte Carlo Absorption
  Framework/Algorithms/inc/MantidAlgorithms/MonteCarloAbsorption.h
  Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/IMCInteractionVolume.h
  Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/MCAbsorptionStrategy.h
  Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/MCInteractionVolume.h
  Framework/Algorithms/src/AddAbsorptionWeightedPathLengths.cpp
  Framework/Algorithms/src/MonteCarloAbsorption.cpp
  Framework/Algorithms/src/SampleCorrections/MCAbsorptionStrategy.cpp
  Framework/Algorithms/src/SampleCorrections/MCInteractionVolume.cpp
  Framework/Algorithms/test/MCAbsorptionStrategyTest.h
  Framework/Algorithms/test/MCInteractionVolumeTest.h
  Framework/Algorithms/test/MonteCarloAbsorptionTest.h
  docs/source/algorithms/MonteCarloAbsorption-v1.rst
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/39157.rst
Labels: Diffraction, ISIS Team: Diffraction, Absorption Corrections

#39225 Deprecated algo UnwrapMonitor
  Framework/Algorithms/inc/MantidAlgorithms/UnwrapMonitor.h
  Framework/Algorithms/src/UnwrapMonitor.cpp
  docs/source/release/v6.13.0/Framework/Algorithms/Deprecated/39218.rst
Labels: ornl-next

#39197 New Algorithm - CreatePoleFigureTableWorkspace
  Framework/PythonInterface/plugins/CMakeLists.txt
  Framework/PythonInterface/plugins/algorithms/CreatePoleFigureTableWorkspace.py
  Framework/PythonInterface/test/python/plugins/algorithms/CMakeLists.txt
  Framework/PythonInterface/test/python/plugins/algorithms/CreatePoleFigureTableWorkspaceTest.py
  docs/source/algorithms/CreatePoleFigureTableWorkspace-v1.rst
  docs/source/release/v6.13.0/Diffraction/Engineering/New_features/39197.rst
Labels: Diffraction, ISIS Team: Diffraction

#39212 Add Classical option to VesuvioPeakPrediction
  Framework/PythonInterface/plugins/algorithms/VesuvioPeakPrediction.py
  Framework/PythonInterface/test/python/plugins/algorithms/VesuvioPeakPredictionTest.py
  docs/source/release/v6.13.0/Indirect/New_features/39212.rst
Labels: Reported By User, ISIS Team: Excitations/Vesuvio

#39216 Update GSL to 2.8
  conda/recipes/conda_build_config.yaml
Labels: ISIS Team: Core, Dependencies

#38279 AlignAndFocusPowderSlim prototype
  .git-blame-ignore-revs
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/AlignAndFocusPowderSlim.h
  Framework/DataHandling/src/AlignAndFocusPowderSlim.cpp
  Framework/DataHandling/test/AlignAndFocusPowderSlimTest.h
  Framework/DataObjects/inc/MantidDataObjects/EventList.h
  Framework/DataObjects/src/EventList.cpp
  Framework/Geometry/inc/MantidGeometry/Instrument/DetectorInfo.h
  Framework/Geometry/inc/MantidGeometry/Instrument/DetectorInfoItem.h
  Framework/Geometry/src/Instrument/DetectorInfo.cpp
  Testing/Data/UnitTest/VULCAN_218062.nxs.h5.md5
  Testing/SystemTests/tests/framework/LoadLotsOfFiles.py
  docs/source/algorithms/AlignAndFocusPowderSlim-v1.rst
  docs/source/release/v6.13.0/Diffraction/Powder/New_features/.gitkeep
  docs/source/release/v6.13.0/Diffraction/Powder/New_features/38279.rst
Labels: Diffraction, Powder

#39236 AlignAndFocusPowderSlim prototype - ornl-next
  .git-blame-ignore-revs
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/AlignAndFocusPowderSlim.h
  Framework/DataHandling/src/AlignAndFocusPowderSlim.cpp
  Framework/DataHandling/test/AlignAndFocusPowderSlimTest.h
  Framework/DataObjects/inc/MantidDataObjects/EventList.h
  Framework/DataObjects/src/EventList.cpp
  Framework/Geometry/inc/MantidGeometry/Instrument/DetectorInfo.h
  Framework/Geometry/inc/MantidGeometry/Instrument/DetectorInfoItem.h
  Framework/Geometry/src/Instrument/DetectorInfo.cpp
  Testing/Data/UnitTest/VULCAN_218062.nxs.h5.md5
  Testing/SystemTests/tests/framework/LoadLotsOfFiles.py
  docs/source/algorithms/AlignAndFocusPowderSlim-v1.rst
  docs/source/release/v6.13.0/Diffraction/Powder/New_features/.gitkeep
  docs/source/release/v6.13.0/Diffraction/Powder/New_features/38279.rst
Labels: ornl-next

#39208 AnyShapeAbsorption uses beam description to determine volume
  Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/IBeamProfile.h
  Framework/Algorithms/src/AnyShapeAbsorption.cpp
  Framework/Algorithms/src/SampleCorrections/IBeamProfile.cpp
  Framework/Algorithms/test/AnyShapeAbsorptionTest.h
  Framework/Algorithms/test/IBeamProfileTest.h
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/39208.rst
Labels: Absorption Corrections, ORNL Team

#39232 Update Absorption Concept Page
  docs/source/concepts/AbsorptionAndMultipleScattering.rst
Labels: Documentation, Absorption Corrections, ORNL Team

#39214 Stop hidden workspaces leaking to ADS during `LoadAndMerge` algorithm if run as child
  Framework/API/src/AnalysisDataService.cpp
  Framework/PythonInterface/mantid/api/src/Exports/IAlgorithm.cpp
  Framework/PythonInterface/plugins/algorithms/LoadAndMerge.py
  Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms/PolDiffILLReduction.py
  Framework/PythonInterface/test/python/plugins/algorithms/LoadAndMergeTest.py
  docs/source/release/v6.13.0/Framework/Algorithms/Bugfixes/39041.rst
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/39041.rst
Labels: ISIS Team: LSS

#39251 Absorption correction ornl next
  Framework/Algorithms/CMakeLists.txt
  Framework/Algorithms/inc/MantidAlgorithms/MonteCarloAbsorption.h
  Framework/Algorithms/inc/MantidAlgorithms/PaalmanPingsAbsorptionCorrection.h
  Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/IBeamProfile.h
  Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/IMCInteractionVolume.h
  Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/MCAbsorptionStrategy.h
  Framework/Algorithms/inc/MantidAlgorithms/SampleCorrections/MCInteractionVolume.h
  Framework/Algorithms/src/AddAbsorptionWeightedPathLengths.cpp
  Framework/Algorithms/src/AnyShapeAbsorption.cpp
  Framework/Algorithms/src/MonteCarloAbsorption.cpp
  Framework/Algorithms/src/PaalmanPingsAbsorptionCorrection.cpp
  Framework/Algorithms/src/SampleCorrections/CircularBeamProfile.cpp
  Framework/Algorithms/src/SampleCorrections/IBeamProfile.cpp
  Framework/Algorithms/src/SampleCorrections/MCAbsorptionStrategy.cpp
  Framework/Algorithms/src/SampleCorrections/MCInteractionVolume.cpp
  Framework/Algorithms/src/SampleCorrections/RectangularBeamProfile.cpp
  Framework/Algorithms/test/AnyShapeAbsorptionTest.h
  Framework/Algorithms/test/IBeamProfileTest.h
  Framework/Algorithms/test/MCAbsorptionStrategyTest.h
  Framework/Algorithms/test/MCInteractionVolumeTest.h
  Framework/Algorithms/test/MonteCarloAbsorptionTest.h
  Framework/Algorithms/test/PaalmanPingsAbsorptionCorrectionTest.h
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/algorithms/MonteCarloAbsorption-v1.rst
  docs/source/algorithms/PaalmanPingsAbsorptionCorrection-v1.rst
  docs/source/concepts/AbsorptionAndMultipleScattering.rst
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/39157.rst
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/39208.rst
  docs/source/release/v6.13.0/Framework/Algorithms/New_features/39210.rst
Labels: ornl-next

#39246 Fix Performance issue in GroupDetectors
  Framework/DataHandling/src/GroupDetectors2.cpp
  docs/source/release/v6.13.0/Framework/Algorithms/Bugfixes/39246.rst
Labels: Bug, ORNL Team

#39250 Improve NeXusException information
  Framework/DataHandling/inc/MantidDataHandling/SaveNexusProcessedHelper.h
  Framework/DataHandling/src/LoadEmptyInstrument.cpp
  Framework/DataHandling/src/SaveNexusProcessed.cpp
  Framework/DataHandling/src/SaveNexusProcessedHelper.cpp
  Framework/Nexus/inc/MantidNexus/H5Util.h
  Framework/Nexus/inc/MantidNexus/NeXusException.hpp
  Framework/Nexus/src/H5Util.cpp
  Framework/Nexus/src/NeXusException.cpp
  Framework/Nexus/src/NeXusFile.cpp
  Framework/Nexus/test/NeXusFileLeakTest.h
  Framework/Nexus/test/NeXusFileReadWriteTest.h
Labels: Technical Debt

#39239 Specify exact python on launch
  Testing/SystemTests/tests/qt/WorkbenchStartupTest.py
  qt/applications/workbench/workbench/app/start.py
  qt/python/mantidqt/mantidqt/dialogs/errorreports/run_pystack.py
Labels: ISIS Team: Core

#39118 Add SavePolarizationNXcanSAS Algorithm
  Framework/Algorithms/src/PolarizationCorrectionFredrikze.cpp
  Framework/Algorithms/src/PolarizationCorrectionWildes.cpp
  Framework/Algorithms/src/PolarizationEfficiencyCor.cpp
  Framework/DataHandling/CMakeLists.txt
  Framework/DataHandling/inc/MantidDataHandling/NXcanSASDefinitions.h
  Framework/DataHandling/inc/MantidDataHandling/NXcanSASHelper.h
  Framework/DataHandling/inc/MantidDataHandling/SaveNXcanSASBase.h
  Framework/DataHandling/inc/MantidDataHandling/SavePolarizedNXcanSAS.h
  Framework/DataHandling/src/NXcanSASHelper.cpp
  Framework/DataHandling/src/SaveNXcanSAS.cpp
  Framework/DataHandling/src/SaveNXcanSASBase.cpp
  Framework/DataHandling/src/SavePolarizedNXcanSAS.cpp
  Framework/DataHandling/test/LoadNXcanSASTest.h
  Framework/DataHandling/test/NXcanSASFileTest.h
  Framework/DataHandling/test/NXcanSASTestHelper.cpp
  Framework/DataHandling/test/NXcanSASTestHelper.h
  Framework/DataHandling/test/SaveNXcanSASTest.h
  Framework/DataHandling/test/SavePolarizedNXcanSASTest.h
  Framework/Kernel/inc/MantidKernel/SpinStateValidator.h
  Framework/Kernel/inc/MantidKernel/VectorHelper.h
  Framework/Kernel/src/SpinStateValidator.cpp
  Framework/Kernel/src/VectorHelper.cpp
  Framework/Kernel/test/SpinStateValidatorTest.h
  Framework/Kernel/test/VectorHelperTest.h
  docs/source/algorithms/SavePolarizedNXcanSAS-v1.rst
  docs/source/release/v6.13.0/SANS/New_features/38505.rst
  instrument/unit_testing/POLSANSTEST_Definition.xml
Labels: SANS, ISIS Team: LSS

#39245 NeXusFile slow roll, take it easy
  Framework/DataHandling/inc/MantidDataHandling/SaveNexusProcessed.h
  Framework/DataHandling/inc/MantidDataHandling/SaveNexusProcessedHelper.h
  Framework/DataHandling/src/LoadEventNexus.cpp
  Framework/DataHandling/src/SaveNexusProcessed.cpp
  Framework/DataHandling/src/SaveNexusProcessedHelper.cpp
  Framework/DataHandling/test/SaveNexusProcessedTest.h
  Framework/DataObjects/src/BoxControllerNeXusIO.cpp
  Framework/DataObjects/src/LeanElasticPeaksWorkspace.cpp
  Framework/DataObjects/src/MDBoxFlatTree.cpp
  Framework/DataObjects/src/PeaksWorkspace.cpp
  Framework/MDAlgorithms/src/SaveMD2.cpp
  Framework/Nexus/inc/MantidNexus/H5Util.h
  Framework/Nexus/inc/MantidNexus/NeXusFile.hpp
  Framework/Nexus/inc/MantidNexus/NeXusFile_fwd.h
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/inc/MantidNexus/NexusIOHelper.h
  Framework/Nexus/inc/MantidNexus/nxstack.h
  Framework/Nexus/src/H5Util.cpp
  Framework/Nexus/src/NeXusFile.cpp
  Framework/Nexus/src/NexusClasses.cpp
  Framework/Nexus/src/napi.cpp
  Framework/Nexus/src/napi5.cpp
  Framework/Nexus/src/nxstack.cpp
  Framework/Nexus/test/H5UtilTest.h
  Framework/Nexus/test/NeXusFileNapiTest.h
  Framework/Nexus/test/NeXusFileReadWriteTest.h
  Framework/Nexus/test/NeXusFileTest.h
  Framework/Nexus/test/napi_test_cpp.cpp
  Framework/Nexus/test/test_helper.cpp
  Framework/Nexus/test/test_helper.h
Labels: Technical Debt

#39257 Various for fixes from main
  .pre-commit-config.yaml
  Framework/CurveFitting/src/Algorithms/EstimateFitParameters.cpp
  Framework/CurveFitting/src/Functions/BivariateNormal.cpp
  Framework/DataHandling/inc/MantidDataHandling/CheckMantidVersion.h
  Framework/DataHandling/inc/MantidDataHandling/CreatePolarizationEfficienciesBase.h
  Framework/DataHandling/inc/MantidDataHandling/DownloadInstrument.h
  Framework/DataHandling/inc/MantidDataHandling/FindDetectorsPar.h
  Framework/DataHandling/inc/MantidDataHandling/ISISJournal.h
  Framework/DataHandling/inc/MantidDataHandling/LoadDNSEvent.h
  Framework/DataHandling/src/ISISJournal.cpp
  Framework/DataHandling/src/SaveGSASInstrumentFile.cpp
  Framework/Reflectometry/src/CreateTransmissionWorkspace2.cpp
  Framework/Reflectometry/src/ReflectometryBackgroundSubtraction.cpp
  Framework/Reflectometry/src/ReflectometryReductionOne2.cpp
  Framework/Reflectometry/src/ReflectometryWorkflowBase2.cpp
  Testing/SystemTests/tests/qt/WorkbenchStartupTest.py
  buildconfig/CMake/CppCheck_Suppressions.txt.in
  docs/source/release/v6.13.0/Workbench/Bugfixes/39247.rst
  qt/applications/workbench/workbench/app/start.py
  qt/python/mantidqt/mantidqt/dialogs/errorreports/run_pystack.py
  qt/python/mantidqt/mantidqt/widgets/samplelogs/test/test_samplelogs_view.py
  qt/python/mantidqt/mantidqt/widgets/samplelogs/view.py
Labels: ornl-next

#39258 NeXusFile slow roll, take it easy -- `ornl-next`
  Framework/DataHandling/inc/MantidDataHandling/SaveNexusProcessed.h
  Framework/DataHandling/inc/MantidDataHandling/SaveNexusProcessedHelper.h
  Framework/DataHandling/src/LoadEventNexus.cpp
  Framework/DataHandling/src/SaveNexusProcessed.cpp
  Framework/DataHandling/src/SaveNexusProcessedHelper.cpp
  Framework/DataHandling/test/SaveNexusProcessedTest.h
  Framework/DataObjects/src/BoxControllerNeXusIO.cpp
  Framework/DataObjects/src/LeanElasticPeaksWorkspace.cpp
  Framework/DataObjects/src/MDBoxFlatTree.cpp
  Framework/DataObjects/src/PeaksWorkspace.cpp
  Framework/MDAlgorithms/src/SaveMD2.cpp
  Framework/Nexus/inc/MantidNexus/H5Util.h
  Framework/Nexus/inc/MantidNexus/NeXusFile.hpp
  Framework/Nexus/inc/MantidNexus/NeXusFile_fwd.h
  Framework/Nexus/inc/MantidNexus/NexusClasses.h
  Framework/Nexus/inc/MantidNexus/NexusIOHelper.h
  Framework/Nexus/inc/MantidNexus/nxstack.h
  Framework/Nexus/src/H5Util.cpp
  Framework/Nexus/src/NeXusFile.cpp
  Framework/Nexus/src/NexusClasses.cpp
  Framework/Nexus/src/napi.cpp
  Framework/Nexus/src/napi5.cpp
  Framework/Nexus/src/nxstack.cpp
  Framework/Nexus/test/H5UtilTest.h
  Framework/Nexus/test/NeXusFileNapiTest.h
  Framework/Nexus/test/NeXusFileReadWriteTest.h
  Framework/Nexus/test/NeXusFileTest.h
  Framework/Nexus/test/napi_test_cpp.cpp
  Framework/Nexus/test/test_helper.cpp
  Framework/Nexus/test/test_helper.h
Labels: ornl-next

#39242 disable crosshair in titled plot
  docs/source/release/v6.13.0/Workbench/New_features/39242.rst
  qt/applications/workbench/workbench/plotting/figuremanager.py
  qt/applications/workbench/workbench/plotting/test/test_toolbar.py
  qt/applications/workbench/workbench/plotting/toolbar.py
Labels: GUI, ORNL Team
